metasfresh/metasfresh

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5445000_sys_FRESH-252_DatePromised_In_InvoiceCandidate.sql
DatePromised column SQL and field added in Invoice Candidates
=> New Field datePromissed in Invoice Candidates Window

ReleaseNotes.md, de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/LogManager.java
not changing 'em anymore in server mode, see comment
=> FRESH-267 aparently Loglevels are changed somewhere in the code

ReleaseNotes.md, de.metas.scripts.rollout/src/main/bash/bootstrap_local.sh, de.metas.scripts.rollout/src/main/bash/tools.sh
introducing a new environment variable ROLLOUT_BUILD_URL to be set by
the caller. Fallback to BUILD_URL if the new var is not set
=> FRESH-286 jenkins envInject plugin overwrites BUILD_URL value

de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PriceListBL.java, de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PriceListDAO.java, de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PricingBL.java
Fixed: when setting the PL and PLV from PS, Country, Date and Product,
the PricelistBL actually discarded the date.
=> FRESH-333 Procurement candidate prices not updates correctly:

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/session/impl/SessionDAO.java, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5446140_sys_FRESH-314_ad_changelog_no_FKs_requried.sql
*making it clear in the AD that we don't need FKs for AD_Session,
AD_PInstance and AD_Table
* inserting new AD_ChangeLog records with NULL references instead of 0
=> FRESH-314 Foreign BPartner reference included in sales order C_Order.C_BPartner_ID

de.metas.scripts.rollout/src/main/bash/minor_remote.sh, de.metas.scripts.rollout/src/main/bash/sql_remote.sh, de.metas.scripts.rollout/src/main/bash/tools.sh
Added additional function to check for java 1.8.x in tools.sh to be used
by sql_remote.sh and minor_remote.sh
=> #139 FRESH-475 Check for java8 in the rollout-scripts

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidator.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/ILoggerCustomizer.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/LogManager.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/NullLoggerCustomizer.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/SysConfigLoggerCustomizer.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/model/interceptor/LoggingModuleInterceptor.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/service/impl/SysConfigDAO.java, de.metas.business/src/main/java/org/adempiere/model/validator/AdempiereBaseValidator.java, de.metas.util/src/main/java/org/adempiere/util/net/NetUtils.java
After user login, the client now logs the logger customizer config. 
It can be used to check if a host's name (as retrieved by the client) matches any SysConfig values.
=> FRESH-588 #288

de.metas.business/src/main/java/de/metas/adempiere/service/IOrderBL.java, de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/receipt/model/ReceiptScheduleCUKey.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/OrderBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleQtysBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleQtysBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/GenerateReceiptScheduleWorkpackageProcessor.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_OrderLine_ReceiptSchedule.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_ReceiptSchedule.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_ReceiptSchedule_Alloc.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_Close.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_ReOpen.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/AsyncReceiptScheduleProducer.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/impl/CompositeReceiptScheduleListener.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/impl/OrderLineReceiptScheduleListener.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/impl/OrderLineReceiptScheduleProducer.java
* fix ifColumnschanged of C_OrderLine_ReceiptSchedule MI.
* fix saving of the receipt schedule during close and reopen.
* add a bunch of comments and javadocs.
* rename IReceiptScheduleQtysHandler to IReceiptScheduleQtysBL, because 
when it sais "handler", i generally think "SPI" (hoping not to confuse 
others with this rename).
* do minor stuff like fixing typos and removing obsolete prepareIt() 
implementation.
=> FRESH-608 #315 ReceiptSchedule.QtyToMove not properly updated on reopen

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5454810_sys_FRESH-1070_switch-off_autocomplete_c_order_id.sql
Switch off autocomplete for field c_order_id (seq scan takes too long
for large datasets)
=> FRESH-1070 #742 R_Request column c_order_id autocomplete too slow

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
ignore `M_ShipmentSchedule_QtyPicked` if they reference
destroyed/inactive HUs
FRESH-1091 #759 Destroyed HU causes problem with shipment creation
=> FRESH-1091 #759: take into account the HU status

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5455672_sys_FRESH-1257-GrandTotal-missingPurchaseOrder.sql
Add GrandTotal Field into Purchase Order Grid View (workaround: disabled
Advanced Edit).
=> FRESH-1257 #886 GrandTotal missing in Purchase Order Grid view

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java, de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/IPaymentStringDataProvider.java, de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/form/ReadPaymentDialogWindowAdapter.java, de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/form/ReadPaymentDocumentForm.java, de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/form/ReadPaymentDocumentPanel.java, de.metas.payment.esr/src/main/java/de/metas/payment/api/impl/ESRPaymentStringDataProvider.java, de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRBPBankAccountDAO.java, de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/AbstractBPBankAccountDAO.java, de.metas.payment.esr/src/main/sql/postgresql/system/5455800_sys_gh781_ESR_C_BP_BankAccount_UC.sql, de.metas.payment.esr/src/test/java/de/metas/payment/spi/impl/ESRCreaLogixStringParserTests.java
filter and order C_BP_BankAccounts according to ctx-BPartner
* until now it was assumed that there can be only one ESR account per
ESR_RenderedAccountNo and AccountNo, but that's not true.
* as of now, we allow multiple such accounts and make sure that only the
relevant ones are taken into account when an ESR string is scanned.
* by relevant, we mean that the ESR account either belongs to the
BPartner in question or (with lesser priority) to a C_BPArtner which has
a remetTo relation to the BPArtner in question.
* at the same time, we establish a UC (there was none so far) to make
sure that there are no duplicate ESR accounts per bPartner.
FRESH-1113 #781 ESR scan processing returns improper bpartner
=> #781 ESR scan processing returns improper bpartner

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5456960_sys_gh164_migration-missing-menu-entries.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5457000_gh1014_window-layout-purchase-order-warehouse.sql
Moved the field Receipt Warehouse from second column to first and
primary column to be able to record this often adjusted field in a more
efficient way.
FRESH-1481 https://github.com/metasfresh/metasfresh/issues/1014
=> #1014 Add window layout for Purchase Order Field Receipt Warehouse

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/HUReceiptScheduleReportExecutor.java, de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/receipt/model/ReceiptScheduleHUSelectModel.java, de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5457790_sys_gh210_add_process_WEBUI_M_ReceiptSchedule_RunMaterialReceiptJasper.sql
* extract the code from ReceiptScheduleHUSelectModel
(hanndlingunits-client) to new class HUReceiptScheduleReportExecutor
(handlingunits-base) so it can be invoked from many places
* add SQL for new webui process
WEBUI_M_ReceiptSchedule_RunMaterialReceiptJasper
FRESH-1610 metasfresh/metasfresh-webui#210 Print Material Receipt
Document via Material Receipt Candidates Window
=> Extract jasper invocation code into service facade

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5457830_sys_gh1103_VirtualColumn-qtyOrderedTU-Material-Receipt-Schedule.sql
Fix for Virtual Column qtyOrderedTU in Material Receipt Schedule.
FRESH-1652 https://github.com/metasfresh/metasfresh/issues/1103
=> #1103 Fix Virtual Column qtyOrderedTU in Material Receipt Schedule

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5457990_sys_gh1135_translation-empties-receive-action.sql
Adding a better Translation for Empties Receive Window Material Receipt
Candidates in WebUI. It shall allow a better differenciation to Action
Empties return and less wrong clicks for the user.
FRESH-1696 https://github.com/metasfresh/metasfresh/issues/1135
=> #1135 Add Translation for Empties Receive action in window Material Receipt candidate

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5458010_sys_gh1133-reorder-material-receipt-grid-view.sql
Reordering the columns to allow better visibility of important information for the receipt user.
FRESH-1695 https://github.com/metasfresh/metasfresh/issues/1133
=> #1133 Reorder the columns in Grid View for Material Receipt Window

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5458410_sys_gh1102Field-PriceListVersion-search-Field.sql
Changing the FieldType for PriceListVersion from tableDirect to search
an autocomplete in Window Product Prices.
FRESH-1645 https://github.com/metasfresh/metasfresh/issues/1102
=> #1102 Add Field PriceListVersion as search Field

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5459550_sys_gh1260-invoice-documentno-auto.sql
Adding C_DocTypeTarget_ID to Invoice Window in WebUI tio allow recording
of DocuemtnType which is a mandatory field.
FRESH-1878 https://github.com/metasfresh/metasfresh/issues/1260
=> #1260 Add C_DocTypeTarget_ID to window in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5460650_sys_gh1382-packing-item-editable-pp-order.sql
Adjusting the field Packing Item in pp_order, making it editable.
FRESH-2063 https://github.com/metasfresh/metasfresh/issues/1382
=> #1382 Make Packing Item editable in Manufacturing Order Header

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5461030_cli_gh1399-documentno-for-PP-orders.sql
Adjusting the manufacturing Order Documenttypes to allow automatic document No control.
FRESH-2039 https://github.com/metasfresh/metasfresh/issues/1399
=> #1399 DocumentNo not generated for PP_Orders in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5462280_sys_gh1486-status-field-materialdispo-webui.sql
Adding Status Field to Material Disposition Window in WebUI. Included
into Sidelist and Grid View. Minor Adjustments of window Layout.
FRESH-2180 https://github.com/metasfresh/metasfresh/issues/1486
=> #1486 Add Status Field to Material Disposition Window in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463430_sys_gh1628-sales-order-adjustment-webui.sql
Overhauling the Layout of Sales Order Window, implementing as Prototype Layout definition for all Document windows (not master data). Adjusting the Advanced Edit Look&Feel. Decision to not show isActive in Document Windows anymore. And more tweaks.
FRESH-2368 https://github.com/metasfresh/metasfresh/issues/1628
=> #1628 Sales Order Window Advanced edit rearrangement

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463535_sys_gh1657-search-column-date-manufacturing-order.sql
Removing 2 Dates Fields from Manufacturing Order default Filter
FRESH-2399 https://github.com/metasfresh/metasfresh/issues/1657
=> #1657 Removing 2 Dates Fields from Manufacturing Order default Filter

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464230_sys_gh1695-avatar-language-user-webui.sql
Creating 2 new Fields in AD_User Avatar_ID and AD_Language and adding them to the User Window in WebUI, including Advanced Edit, Sidelist and Grid View. Further, added the 2 new Fields to current myProfile Window.
FRESH-2438 https://github.com/metasfresh/metasfresh/issues/1695
=> #1695 Introduce AD_User.Avatar_ID and AD_Language fields

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464310_sys_gh1730-discount-window-webui.sql
Adding the Window for Discount Schema Maintenance to WebUI. Including 2-column Layout Main View, Sidelist, grid View and Advanced Edit. Same for Subtab with Discount Braks. Added missing mandatory Fields to Window and translated System Elements.
FRESH-2488 https://github.com/metasfresh/metasfresh/issues/1730
=> #1730 New Window for Discount Maintenance in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464900_sys_gh1778-kpi-field-trl-window-webui.sql
Creates a new Window for WebUI, that allows the Translation maintenance of KPI Fields for WebUI Users.
Defining the 2-column Layout, Sidelist and Grid View.
FRESH-2557 https://github.com/metasfresh/metasfresh/issues/1778
=> #1778 New Window/ Tab for KPI Field Translation

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465130_sys_gh1754-adjustment-transport-dispo-window-webui.sql
Rearranging the UI Group w/ Org Information. Creating an own UI Section
instead, so the Org/ Client is shown at the bottom of the main view as
usual.
FRESH-2526 https://github.com/metasfresh/metasfresh/issues/1754
=> #1754 Rearranging the UI Group w/ Org Information

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465390_sys_gh1829-rfq-windows-webui.sql
Different RFQ Windows in WebUI. Adding the window Layouts in WebUI for the following windows:
a) C_RFQ_Topic
b) C_RFQResponse
c) C_RFQReponseLine
Including 2-column Main View, Sidelist and Advanced edit Layout.
FRESH-2627 https://github.com/metasfresh/metasfresh/issues/1829
=> #1829 Different RFQ Windows in WebUI

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/session/MFSession.java, de.metas.printing.ait/src/test/java/de/metas/printing/test/integration/TestFromPrintingQueueToClient.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/IPrintingDAO.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PlainPrintingDAO.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintPackageBL.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintingDAO.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/AD_User_Login.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/SwingPrintingClientValidator.java, de.metas.printing/de.metas.printing.base/src/test/java/de/metas/printing/api/impl/Helper.java
also removed superfluous method IPrintingDAO.retrieveCurrentSession()
lazy-assigned Hostkey is not shown in swing-client's settings #1314
1771: add legacy features
Task-Url: https://github.com/metasfresh/metasfresh/issues/1771
(cherry picked from commit 51a6fd13f62c87cb10fb0128d0df6903342d7ebf)
=> Now setting the Hostkey updates both the respective ctx and AD_Session

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465955_sys_gh1872-implicit-selectioncriteria-to-columns.sql
Updates the selection criteria columns for the implicit filterings of
swing client
FRESH-2694 https://github.com/metasfresh/metasfresh/issues/1872
=> #1872 Updates the selection criteria columns for the implicit filterings of swing client

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466070_sys_gh1814-processed-flag-inout-webui.sql
Hide Processed flag from all M_InOut/Returns windows . Removing the flag from Empties receive/ return and Vendor Return window. Making the flag readonly.
FRESH-2612 https://github.com/metasfresh/metasfresh/issues/1814
=> #1814 Hide Processed flag from all M_InOut/Returns windows 

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466140_sys_gh1893-shipment-default-doctype.sql
Adding the default Doctype for SHipment Window. This is only needed for
manually created Shipments, and reduced the fields that have to be
filled initially.
FRESH-2727 https://github.com/metasfresh/metasfresh/issues/1893
=> #1893 Adding a default Doctype to shipment Window

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466670_sys_gh1933-menu-trl-en-us-webui.sql
Establishing the Translations of en_US in metasfresh WebUI menu. Added missing Translations for Menu entries and Window and Tab Names.
FRESH-2788 https://github.com/metasfresh/metasfresh/issues/1933
=> #1933 Menu Translations for Language en_US

ReleaseNotes.md, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467760_sys_gh1995-shorten-language-name.sql
Shortening the Language Names setting them to 2-digit Country Code
FRESH-2901 https://github.com/metasfresh/metasfresh/issues/1995
=> #1995 Language Names too Long

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468490_sys_gh2032-handling-unit-editor-webui.sql
Refining the Layout for the Handling Unit Editor Details in WebUI. Added 2-column Layout. Adjusted the Grid Views anjd Sidelists also Advanced Edit Screeens of Main View and Subtabs.
FRESH-2948 https://github.com/metasfresh/metasfresh/issues/2032
=> #2032 Layout for Handling Unit Editor Window in WebUI

ReleaseNotes.md, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468580_sys_gh2058-table-identifier-work.sql
Changing the Identifier of AD_Table to name instead of Name and
Tablename. Now the denifier looks more User friendly in Table +
Record_ID combinations.
FRESH-2981 https://github.com/metasfresh/metasfresh/issues/2058
=> #2058 Changing the Identifier of AD_Table to name

de.metas.payment.esr/pom.xml, de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java, de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/camt54/ESRDataImporterCamt54.java, de.metas.payment.esr/src/main/sql/postgresql/system/5469020_gh2106_gh_2107_add_AD_Messages.sql, de.metas.payment.esr/src/test/java/de/metas/payment/esr/api/impl/ESRImportBLTest.java, de.metas.payment.esr/src/test/java/de/metas/payment/esr/dataimporter/impl/camt54/ESRDataImporterCamt54Tests.java, de.metas.payment.esr/src/test/resources/camt054.xml, de.metas.payment.esr/src/test/resources/camt54_no_Btch.xml, de.metas.payment.esr/src/test/resources/camt54_one_ESR_reference_ambigous.xml, de.metas.payment.esr/src/test/resources/camt54_one_ESR_reference_missing.xml
* drop assumptions about the number of some XML elements
* allow ctrlQty to remain null
* if the ESR reference is missing and/or if there is an unexpected
transaction type, then don't fail the import, but record an error
* Add AD_Messages for the new non-fatal errors
Task-Urls: 
https://github.com/metasfresh/metasfresh/issues/2106
https://github.com/metasfresh/metasfresh/issues/2107
=> 2106 & 2107: Problems on CAMT 54 Import

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469660_sys_gh2184-order-candidates-window-webui.sql
Removing the processed Flag from Advanced edit mode.
FRESH-3135 https://github.com/metasfresh/metasfresh/issues/2184
=> #2184 Removing processed from Advanced edit

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470200_sys_gh2268-printer-config-window-webui.sql
Adding the Layout Configuration for Printer Config Window in WebUI, incl. Main View 2-column Layout, Grid View, Sidelist. Additionally added missing Translations for en_US Language/ Locale.
FRESH-3208 https://github.com/metasfresh/metasfresh/issues/2268
=> #2268 New Window for Drucker-Zuordnung in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470550_sys_gh2086-sales-order-window-refining-webui.sql
Fixes for failed IT added. Further improvements in Advanced edit (only 1 section/ group now), added Translations for en_US.
FRESH-3008 https://github.com/metasfresh/metasfresh/issues/2086
=> #2086 Sales Order Advanced Edit Window in main View

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470580_sys_gh2306-period-action-open-close.sql
Added the action for period open/ close to Perdiod Window/ Table.
FRESH-3261 https://github.com/metasfresh/metasfresh/issues/2306
=> #2306 Period mass actions missing in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471240_sys_gh2405-invoice-clearing-window-webui.sql
Adding new Window for Invoice Clearing Allocation in WebUI. Is a detailed window as a contracts sub-sub-tab substitute. Includes the Main View with 2-column Layout, Grid View, Sidelist. Translations for de_DE and en_US.
FRESH-3366 https://github.com/metasfresh/metasfresh/issues/2405
=> #2405 New Window for C_Invoice_Clearing_Alloc in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471700_sys_gh2408-contractno-date-flatrate.sql
Adding 2 new Fields to Contract widnow, allowing to have Document No and Date for Contracts. Making it Feel more documentish. Adding Translations for en_US.
FRESH-3367 https://github.com/metasfresh/metasfresh/issues/2408
=> #2408 Contract Date and Contract DocumentNo

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471930_sys_gh2478-initial-filter-sequence-org-webui.sql
Initializing Filter sequence in DB and setting a high sequence No for AD_Org-ID columns
FRESH-3424 https://github.com/metasfresh/metasfresh/issues/2478
=> #2478 Initializing Filter sequence in DB and setting a high sequence No for AD_Org-ID columns

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473350_sys_gh2594-dunning-dispo-window-webui.sql
New Window for Dunning Candidates in WebUI. Main View, 2-Column Layout, Grid Viws and Sidelist. Adding Translations for en_US, de_DE. Adding Filter Criteria and Sequence.
FRESH-3524 https://github.com/metasfresh/metasfresh/issues/2594
=> #2594 New Window for Dunning Candidates in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474090_sys_gh2690-scheduler-window-webui.sql
Adding a New window for AD_Scheduler in WebUI. Created the 2-column Layout for Main View and Subtab Layouts. Grid View, Sidelist and Advanced edit. Added Translations for en_US and de_DE.
FRESH-3617 https://github.com/metasfresh/metasfresh/issues/2690
=> #2690 New window for AD_Scheduler in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477010_sys_gh2934-locator-trl-fix.sql
Fixes a missing Translation for Locator Dimension and adding a mandatory Logic for (X1, Rack)
FRESH-3952 https://github.com/metasfresh/metasfresh/issues/2934
=> #2934 Additional Locator Dimensions

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478830_sys_gh3095-session-audit-window-webui.sql
New window for session audit in webui. Adding 2-column layout for main view, grid layout, sidelist, included subtab layout. Translations added for de_DE, en_US Locale/ Language.
https://github.com/metasfresh/metasfresh/issues/3095
=> #3095 WebUI: new Window for AD_Session in WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479800_sys_gh3159-show-product-trl-again.sql
Fixing the Trabnslation Tab for Products. Now showing the Translation records again.
https://github.com/metasfresh/metasfresh/issues/3159
=> #3159 Translation Tab content missing for Product_Trl

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481150_sys_gh3239-material-receipt-candidates-readonly-webui.sql
WebUI: Material Receipt Candidates Fields not readonly. Adjusting the Window Layout for advanced edit.
https://github.com/metasfresh/metasfresh/issues/3239
=> #3239 WebUI: Material Receipt Candidates Fields not readonly

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481410_sys_gh3260-warehouse-acct-tab-undisplay-webui.sql
Undisplaying the Accounting Tab in Window Warehouse for WebUI
https://github.com/metasfresh/metasfresh/issues/3260
=> #3260 Undisplaying the Accounting Tab in Window Warehouse for WebUI

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5482070_sys_gh3289-materialdispo-cockpit-detail-window-webui.sql
Creates a new Window for the modal Overlay of Document Details in Material Cockpit. Added Grid View and 2-column Layout. Added Translations for de_DE and en_US.
https://github.com/metasfresh/metasfresh/issues/3289
=> #3289 WebUI: New Window for Document Details in Material Cockpit

de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
#3196 dunning run: Exception on PDF generation
=> #3196 If there is no print format defined, throw an exception

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483010_sys_gh3339-doubled-doctype-payment-fix.sql
Rmoving the doubled field doctype from the primary section group
of payment window in webui.
https://github.com/metasfresh/metasfresh/issues/3339
=> #3339 Removing double field doctype from window primary section

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5484410_sys_gh3428-daterange-prepdate-filter-manufacturing-order.sql
Removed Daterange Option in Filter Parm o Preparation Date
https://github.com/metasfresh/metasfresh/issues/3428
=> #3428 Removed Daterange Option in Filter Parm

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5484590_sys_gh3439-go-deliveryorder-improvements-webui.sql
Removing UI Group from GO! Delivery Order WIndow. Rearranging important Fields moving them from advanced edit to the main view.
https://github.com/metasfresh/metasfresh/issues/3439
=> #3439 Improvement of GO Delivery Order Window

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485110_sys_gh3467-preparation-daterange-webui.sql
Adds the daterange config to the preparation date filter in
manufacturing order filter criteria.
https://github.com/metasfresh/metasfresh/issues/3467
=> #3467 Adds Daterange config to preparation Date

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485550_sys_gh3502-window-filter-improvements-webui.sql
Adds different default filter criteria to the sales order, purchase order, order candidates, shipment schedule and invoice candidates window.
https://github.com/metasfresh/metasfresh/issues/3502
=> #3502 Default Filter Improvements

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Env.java, de.metas.adempiere.adempiere/base/src/main/java/org/compiere/util/CtxName.java, de.metas.adempiere.adempiere/base/src/main/java/org/compiere/util/CtxNames.java, de.metas.adempiere.adempiere/base/src/test/java/org/compiere/util/ArrayKeyTest.java, de.metas.adempiere.adempiere/base/src/test/java/org/compiere/util/CtxNamesTests.java
solve bug in CtxNames where defaultValue="NULL" could not be handeled by getValueAsDate()
Also
* add new method CtxNames.ofNameAndDefaultValue to avoid parsing where it is not needed
fix available stock (ATP) display in sales order https://github.com/metasfresh/metasfresh-webui-api/issues/863
=> #863-api - fix available stock (ATP) display in sales order 

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487350_sys_gh3609-default-product-window-pharma-adjustments.sql
Removes pharma specific ui  elements from webui.
https://github.com/metasfresh/metasfresh/issues/3609
=> #3609 Removes pharma specific fields from webui

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491520_sys_gh3897-bpartner-pharma-details-trl.sql
Adds missing Translations for en_US for new Pharma Fields. Adds Default logic. Adds Readonly Logic.
https://github.com/metasfresh/metasfresh/issues/3897
=> #3897 Add Translations for Pharma Business Partner Window

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/impl/BPartnerBL.java
#4078 AD_User_ID/Bill_User_ID not set in Sales Order when using Quick
creation of partner
=> #4078 Set SalesContact and PurchaseContact flags

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494710_sys_gh4118-uom-translation-window-webui.sql
New Window for the maintenance of Unit of Measure Translations. Adds 2-column Layout, Grid View, and Sidelist. Adds Translations for de_DE, en_US. New Window added to WebUI Menu.
https://github.com/metasfresh/metasfresh/issues/4118
=> #4118 WebUI: Translation Window for Unit of Measures

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494890_sys_gh4139-dunning-level-trl-window-webui.sql
New Window for dunning level translations. Adds 2-column layout, sidelist, grid view. Adds translations for den_US, de_DE. Adds Document Reference do dunning level translation window.
https://github.com/metasfresh/metasfresh/issues/4139
=> #4139 WebUI: Translation Window for Dunning Level

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494940_sys_gh4158-webui-menu-missing-trl-en_US.sql
Adds en_US Translations for Sitemap entries, Window names, Tab Names.
https://github.com/metasfresh/metasfresh/issues/4158
=> #4158 WebUI Sitemap: Missing Translations en_US

de.metas.adempiere.adempiere/base/src/main/java/org/compiere/apps/search/UserQueryRepository.java
#4149 User query: IUserQueryRestriction is not built properly all the
time
=> #4149 add by default the AND operator to the segment, not to the entire code

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496550_sys_gh4264-consumer-label-ingredients.sql
Adds 2 new Columns - CU Label Qty, Show Ingredients od Sub BOM - to BOM Line and Manufacturing Order BOM Line. Adds them to BOM Window, Manufacturing Order. These will be used to record Text information of Ingredients Qties for Consumer Labels.
https://github.com/metasfresh/metasfresh/issues/4264
=> #4264 Ingredients Data for Consumer Product Label

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5497330_sys_gh4356-app_C_Payment_Term_fix_null_integer_columns.sql, de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTermService.java
solution: make sure that FixMonthOffset and others are zero in the DB. that way the C_PaymentTerm record will be found next time.
also for performance and stability: cache and select/create out of trx
Sales Orderline:ERROR: duplicate key value violates unique constraint "c_paymentterm_name" #4356
=> #4356-app - solve Sales Orderline error

de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/ITaxBL.java, de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java, de.metas.business/src/main/java-legacy/org/compiere/model/MOrderLine.java, de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java, de.metas.contracts/src/main/java/de/metas/contracts/subscription/invoicecandidatehandler/FlatrateTermSubscription_Handler.java, de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateBLTest.java, de.metas.contracts/src/test/java/de/metas/contracts/invoicecandidate/FlatrateTermHandlerTest.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/InvoiceCandidateWriter.java, de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/InvoiceLineBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/form/CreateInvoiceCandidateDialog.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_InventoryLine_Handler.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tax/api/impl/TaxBL.java, de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/AbstractDeliveryTest.java, de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/C_OrderLine_Handler_Test.java
TaxBL.getTax now uses the shipTo location instead of the billTo location. 
Because it matters where the service is performed, not where the bill is send to.
Also remove three (unused) parameters: chargeId, billC_BPartner_Location_ID and trxName
Sales Order VAT vs. Invoice Candidate VAT #4371
=> #4371-app - Sales Order VAT vs. Invoice Candidate VAT

de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java, de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingResult.java, de.metas.business/src/main/java/org/adempiere/uom/api/impl/UOMConversionBL.java
Pricing engine sets the scale of price amounts to the respective precision https://github.com/metasfresh/metasfresh/issues/4376
=> #4376 - pricing engine updates the price amounts to match the precision

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/ad_field_v.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498305_sys_gh4426-app_change_AD_Field_v.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498380_sys_gh4426-app_add_missing_fields.sql
don't load GridFieldVOs if there is no AD_Field,
Idk why it was done to start with, and it causes problems down the line, if those GridFieldVOs have default value expressions that point to other columns' context expressions.
Error on new purchase order #4426
=> #4426-app - Error on new purchase order

de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5498820_sys_gh4456-app_add_sysconfig.sql
add AD_Sysconfig; preserve the previous behavior
https://github.com/metasfresh/metasfresh/issues/4456
=> #4456-app Material Cockpit - attribute detail rows' dimenstion spec

de.metas.acct.base/src/main/java/org/adempiere/acct/api/impl/PostingRequestBuilder.java, de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/CacheMgt.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/ITrxManager.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/spi/TrxOnCommitCollectorFactory.java, de.metas.async/src/main/java/de/metas/async/api/impl/WorkPackageQueue.java, de.metas.business/src/main/java/de/metas/inout/model/validator/M_InOutLine.java, de.metas.business/src/main/java/org/adempiere/model/validator/AdempiereBaseValidator.java, de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/mrp_productinfo/IMRPProductInfoSelector.java, de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/mrp_productinfo/async/spi/impl/UpdateMRPProductInfoTableWorkPackageProcessor.java, de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/mrp_productinfo/impl/MRPProductInfoBL.java, de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/mrp_productinfo/impl/MRPProductInfoSelectorFactory.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandUpdateSchedulerRequest.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_OrderLine.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/M_InOut.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/M_InOutLine.java
* invoice candidates are no longer invalidated when C_OrderLine.QtyDelivered changes; because this only catches ICs that have an order line
* instead they are invalidated on M_InOut completion (also reactivation, but we already had that before)
also
* IMRPProductInfoSelector et al: fix bug that no async prokpackage was created on M_Transaction delete (e.g. when a shipment was reactivated)
* ITrxManager add method isActive() also for String trxName
* CacheMgt, PostingRequestBuilder and TrxOnCommitCollectorFactory: use ITrxManager.isActive() instead of isNull(), to also handle the case of an already closed trx
* WorkPackageQueue.markReadyForProcessing() make *really* sure that the WP is unlocked at the end
* M_InOutLine move method that is not invoice-candidte-related to the general …
=> #4624-app - invoice candidate not updated after shipment complete

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/callout/AD_Column.java, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5502730_sys_gh4652-app_make_AD_Element_dependent_fields_readonly.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5502731_sys_gh4652-app_make_AD_Element_dependent_fields_readonly_DDL.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5502735_sys_gh4652-app_migrate_AD_Field_Trl_to_AD_Element_Trl.sql, de.metas.business/src/main/java/org/adempiere/model/validator/AdempiereBaseValidator.java
* make AD_Element controlled fields read-only (e.g. AD_Field.Name)
* migrate existing AD_Field_Trls into AD_Element_trl
AD Element Translations leads to wrong fieldname Translations https://github.com/metasfresh/metasfresh/issues/4652
=> 4652-app - AD Element Translations lead to wrong fieldname Translations

de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentConstants.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentEntry.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentEntryFactory.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentEntryService.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/process/AD_AttachmentEntry_Download.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ExecuteReportStrategyUtil.java, de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/test/AdempiereTestHelper.java, de.metas.business/src/main/java/de/metas/invoice/export/InvoiceToExportFactory.java, de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_SalesInvoiceJasperWithAttachedDocuments.java, de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_SalesInvoiceJasperWithAttachedDocumentsStrategy.java, de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5504710_sys_gh4700-app_add_process_update_printformats.sql, de.metas.dunning/src/main/java/de/metas/dunning/modelvalidator/DunningValidator.java, de.metas.dunning/src/main/java/de/metas/dunning/printing/spi/impl/DunningPrintingQueueHandler.java, de.metas.dunning/src/main/java/de/metas/dunning/process/C_DunningDoc_JasperWithInvoicePDFsStrategy.java, de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_HU.java, de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/Main.java, de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformTestsBase.java, de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestinationTestSupport.java, de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUPickingSlotTest.java, de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/impl/HUInternalUseInventoryProducerTests.java, de.metas.order.rest-api/src/main/java/de/metas/order/rest/controller/SalesOrderRestController.java, de.metas.order.rest-api/src/main/java/de/metas/order/rest/model/JsonSalesOrderAttachment.java, de.metas.order.rest-api/src/test/java/de/metas/order/rest/model/JsonSerializationDeserializationTest.java, de.metas.ordercandidate.rest-api-impl/src/main/java/de/metas/ordercandidate/rest/OrderCandidatesRestControllerImpl.java, de.metas.ordercandidate.rest-api/src/main/java/de/metas/ordercandidate/rest/JsonAttachment.java, de.metas.shipper.gateway.dpd-legacy/src/main/java/de/metas/dpd/model/MDPDCountry.java, de.metas.shipper.gateway.dpd-legacy/src/main/java/de/metas/dpd/model/MDPDDepot.java, de.metas.shipper.gateway.dpd-legacy/src/main/java/de/metas/dpd/model/MDPDFileInfo.java, de.metas.shipper.gateway.dpd-legacy/src/main/java/de/metas/dpd/model/MDPDScanCode.java, vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/HealthcareChPdfAttachmentController.java
* Add new tag name to AttachmentConstants
* HealthcareChPdfAttachmentController attaches new attachments with the new tag
* Introduce process C_Invoice_SalesInvoiceJasperWithAttachedDocuments that invokes the "normal" jasper process (config via AD_SysConfig) and appends attachements.
* Extend AttachmentEntryQuery to filter by mimeType (contentType)
* Also:
* extract common code into ExecuteReportStrategyUtil from C_DunningDoc_JasperWithInvoicePDFsStrategy
* rename "contentType" to "mimeType", !!! also in the rest-API !!!
* fix the package name of DunningPrintingQueueHandler
* fix compile trivial issues in dpd-legacy
* minor
https://github.com/metasfresh/metasfresh/issues/4700
=> #4700-app - Allow appending additional PDF-attachments to invoice-PDF

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506275_sys_gh4664_AD_Element_Link_Index.sql
Address SQL problems on different systems by regexp-replacing the "static" inserts with inserts that have a where-clause.
* 5506277_sys_gh4664_AD_Element_Link_Entries_if_not_exist.sql
* adding entries with AD_Element_Link_IDs that the "original" file had.
* this file will run on all DB and will add records that can be added but were not yet added
* 5506280_sys_gh4664_AD_Element_Link_Entries_if_not_exist_REPEAT.sql
* same as 5506277_sys_ but with "original" AD_Element_Link_ID minus 200000
* will add records that can be added (i.e. there is no link for the AD_Element_Link for the resp AD_Field, AD_Tab or AD_Window), but the AD_Element_Link_ID is already taken.
regexp:
(INSERT INTO AD_Element_Link \(AD_Client_ID,AD_Element_ID,AD_Element_Link_ID,AD_Field_ID,AD_Org_ID,AD_Window_ID,Created,Creat …
=> #4664-app - New Window "Application Elements" SQL fixes

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/RelationTypeZoomProvider.java, de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupFactory.java, de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MQuery.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/ILookupDAO.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java, de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/model/RelationTypeZoomProviderFactoryTest.java
Example, from a log file:
```
2018-12-19 23:02:41.096 ERROR 100 --- [https-jsse-nio-8443-exec-6] org.compiere.model.MLookupFactory        : getLookupInfo: WHERE should be fully qualified: issystemuser='Y'
tableRefInfo=TableRefInfo{name=AD_User, tableName=AD_User, keyColumn=AD_User_ID, displayColumn=Name, valueDisplayed=false, whereClause=issystemuser='Y', orderByClause=AD_User.Name, translated=false, zoomWindow=108, zoomWindowPO=123, overrideZoomWindow=-1, autoComplete=false}
```
Note: it seems that this particular where clause was already fixed in `master` in the meantime.
With my change, this message will be
```
2018-12-19 23:02:41.096 ERROR 100 --- [https-jsse-nio-8443-exec-6] org.compiere.model.MLookupFactory        : getLookupInfo: whereClause of tableRefInfo …
```
=> ITableRefInfo - rename "name" to "identifier" and make it more verbose

de.metas.business/src/main/java/de/metas/order/OrderLinePriceUpdateRequest.java, de.metas.business/src/main/java/de/metas/order/impl/OrderLinePricingConditions.java, de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java, de.metas.business/src/main/java/de/metas/pricing/IEditablePricingContext.java, de.metas.business/src/main/java/de/metas/pricing/conditions/PricingConditionsBreakQuery.java, de.metas.business/src/main/java/de/metas/pricing/conditions/service/CalculatePricingConditionsRequest.java, de.metas.business/src/main/java/de/metas/pricing/rules/Discount.java, de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingContext.java, de.metas.device.adempiere/pom.xml, de.metas.device.adempiere/src/main/java/de/metas/device/adempiere/impl/SysConfigDeviceConfigPool.java, de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/order/api/impl/HUOrderBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderLineBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java
...the conditions are actually missing
* Fix item 8. of https://github.com/metasfresh/metasfresh/issues/4282#issuecomment-401004955
* PricingConditionsBreakQuery knows which C_OrderLine column names neccessitate a new query to be applied
* OrderLinePriceCalculator consults PricingConditionsBreakQuery before deciding whether to go on with a preexisting discount schema break
* add some comments and `@Nullable` / `@NonNull` annodations to make the code clearer
* OrderLinePriceUpdateRequest
* OrderLinePricingConditions
* C_OrderLine
* IEditablePricingContext
* CalculatePricingConditionsRequest
* Discount
* PricingContext
* HUOrderBL
* OrderLineBL
https://github.com/metasfresh/metasfresh/issues/4282
=> 4282-app - Order line is flagged as Temporary Pricing Conditions when..

de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5510320_sys_gh1128-api_materialcockpit_limit_empty_products.sql, de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5510390_sys_gh1128-app_materialcockpit_sysconfig_cachesize.sql, de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5510400_sys_gh1130-api_DocumentCollection_CacheSize.sql
add sysconfig to limit the number of "empty" products to be merged into the material cockpit
https://github.com/metasfresh/metasfresh-webui-api/issues/1128
=> 1128-api - Limit number of products shown in material cockpit

de.metas.handlingunits.base/src/main/sql/postgresql/system/5510430_sys_gh4892-app_add_inactive_m_product_fields.sql
add columns, fields, trls, webui-fields etc and deacivate them
* until the BL is in place
* for users to reactivate them again, if they need to prepare their product master in advance
https://github.com/metasfresh/metasfresh/issues/4892
=> 4892-app - Add inactive product fields for hu tracing and label printing

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/CConnection.java, de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/CConnectionDialog.java
* CConnection - tried to make things a bit clearer
* CConnectionDialog - the actual fix is in updateInfo(): don't try to get connection infos from the app server, unless you are a swing client; if you aren't a swing-client, you simply don't need them
Dead lock in CConnection.get() when the metasfresh.properties is not already created #5061
=> 5061-app - solve deadlock in CConnection.get()

de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
Also handle the case for purchase credit memos with writeoff and discount
Basically, this is a "manual" cherry-pick of https://github.com/metasfresh/metasfresh/commit/173c441c8f923fba948dcb20e002db9864e0e38a
Accounting for Payment Allocation and Vendor Credit Memo wrong #5040
=> 5040-app Accounting for Payment Allocation and Vendor Credit Memo wrong

de.metas.ordercandidate.rest-api/src/main/java/de/metas/ordercandidate/rest/JsonBPartnerLocation.java, vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/HealthcareChInvoice440RestController.java, vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsService.java
fix:
* invoice debitor is not always the insurance;
* actually the debitor's masterdata might not be included in the XML after all;
* but the debitor's EAN is always in the transport/to attribute
https://github.com/metasfresh/metasfresh/issues/5116
=> 5116-app - Fixes for XML import/export for Kanton

de.metas.contracts/src/main/java/de/metas/contracts/spi/FallbackFlatrateTermEventListener.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceLineImpl.java
* Extend InvoiceCandDAO.deleteAllReferencingInvoiceCandidates() accordingly.
This amounts to metasfresh allowing to reactivate documents that reference an invoice candidate, if that IC was not yet invoiced
* Also modernize InvoiceLineImpl a bit
#5216 https://github.com/metasfresh/metasfresh/issues/5216
=> 5216-app - Allow deleting candidates if processed_override and not invoiced

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/HUPPOrderIssueReceiptCandidatesProcessor.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/IMaterialTrackingDAO.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/IMaterialTrackingPPOrderBL.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/impl/MaterialTrackingDAO.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/impl/MaterialTrackingPPOrderBL.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/IMaterialTrackingAware.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/I_PP_Order.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/MaterialTrackingDocuments.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/QualityBasedInvoicingDAO.java
* IMaterialTrackingDAO - add isQualityInspection method by might be better in terms of perf
* HUPPOrderIssueReceiptCandidatesProcessor - only attempts to set material-tracking-id if it's about a quality inspection. Background: these are the only ones where material-tracking-ids may not be mixed.
* minor changes/improvemwents
https://github.com/metasfresh/metasfresh/issues/5367
=> 5367-app - Issue different MaterialTracking-IDs to the same PP_Order

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5526880_sys_gh5368_Show_currency_in_DunningType_advancedEdit.sql, de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningDAO.java, de.metas.dunning/src/main/java/de/metas/dunning/api/impl/AbstractDunningDAO.java, de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningDAO.java, de.metas.dunning/src/main/java/de/metas/dunning/invoice/api/impl/InvoiceSourceBL.java, de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Create.java, de.metas.dunning/src/test/java/de/metas/dunning/DunningTestBase.java, de.metas.dunning/src/test/java/de/metas/dunning/api/impl/DunningDAOTest.java, de.metas.dunning/src/test/java/de/metas/dunning/api/impl/PlainDunningDAO.java
https://github.com/metasfresh/metasfresh/issues/5368
=> Show currency in Dunning Type - advanced edit

de.metas.materialtracking/src/main/java/de/metas/materialtracking/IMaterialTrackingPPOrderDAO.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/impl/MaterialTrackingPPOrderDAO.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/I_C_Invoice_Candidate.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/InOutLineAsVendorReceipt.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/MaterialTrackingDocuments.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/MaterialTrackingDocumentsPricingInfo.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/PPOrderQualityCalculator.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/PlainVendorReceipt.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/QualityInspectionLinesBuilder.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/QualityInspectionOrder.java
A normal "Auslagerung" PP_Order can take part in multiple material trackings
Fix a bug where related material receipt lines where not taken into account and therefore the quantities were not correctly extrapolated.
Also minor code improvements
https://github.com/metasfresh/metasfresh/issues/5485
(cherry picked from commit ca876aaa05e255b068572ea07bd799f11ddf66a0)
de.metas.materialtracking/src/main/java/de/metas/materialtracking/IMaterialTrackingPPOrderDAO.java
de.metas.materialtracking/src/main/java/de/metas/materialtracking/impl/MaterialTrackingPPOrderDAO.java
de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/InOutLineAsVendorReceipt.java
de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/imp …
=> 5485-app - PP_Orders with issues from multiple material-trackings

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5532710_sys_gh2518_3_update_de_CH_trl.sql
Update de_CH trl
https://github.com/metasfresh/metasfresh/issues/2518
=>  Purchase Invoice: Add "Read Payment String" action in WebUI

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java, de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IProcessPrecondition.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/POJOQuery.java, de.metas.adempiere.adempiere/base/src/main/java/org/compiere/model/IQuery.java, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5456410_sys_gh942_M_PriceList_Create_supporting_views.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536360_gh5799_MiscElements.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536410_sys_gh5799_AddExportAndImportOfPriceListSchemaLines.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536460_sys_gh5799_AddPriceListSchemaLineWindow_update_Query.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536510_sys_gh5799_AddWindowLink_TweakExportQuery.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536540_sys_gh5799_TrlFixes.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536560_sys_gh5799_AddErrorMessageTRL.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536570_sys_gh5799_FixColumnsNotAppearingInSearch.sql, de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536580_sys_gh5799_FixColumnsNotAppearingInSearch2.sql, de.metas.business/src/main/java/de/metas/pricing/conditions/PricingConditionsBreakId.java, de.metas.business/src/main/java/de/metas/pricing/conditions/PricingConditionsId.java, de.metas.business/src/main/java/de/metas/pricing/conditions/service/CreatePriceListSchemaRequest.java, de.metas.business/src/main/java/de/metas/pricing/conditions/service/IPricingConditionsRepository.java, de.metas.business/src/main/java/de/metas/pricing/conditions/service/impl/PricingConditionsRepository.java, de.metas.business/src/main/java/de/metas/pricing/pricelistschema/PriceListSchemaRepository.java, de.metas.business/src/main/java/de/metas/pricing/process/ImportPriceListSchemaLinesFromAttachment.java, de.metas.business/src/main/java/de/metas/pricing/rules/Discount.java, de.metas.business/src/main/java/de/metas/product/IProductDAO.java, de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java, de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java, de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java, de.metas.business/src/test/java/de/metas/pricing/conditions/service/impl/PricingConditionsTest.java, de.metas.business/src/test/java/de/metas/pricing/conditions/service/impl/PricingConditionsTestData1.java, de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/VendorProductInfoService.java
https://github.com/metasfresh/metasfresh/issues/5799
=> feat: Pricelist Schema export-import

de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java, de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateDAO.java, de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
* FlatrateBL allow copntract with type TYPE_CONDITIONS_Procurement to overlap
* Add a bit of javadoc to explain the issue
#5823
=> 5823-app - Delivery contract with same product but different attributes

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536930_sys_gh5834_UpdateAdMessageTRL.sql, de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java, de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
In this way the bpartner field is no longer cleared (when the transaction is rolled back by the thrown exception)
https://github.com/metasfresh/metasfresh/issues/5834
=>  Dont throw an error notification in case no Bpartner bill-to address exists, but only show an error message over the field

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/TableSequenceChecker.java
NOTE: before was not working because select dba_seq_check_native(?) assumes the table already exists in database, which is not our case
https://github.com/metasfresh/metasfresh/issues/5878
=> bugfix: automatically create native sequence when an AD_Table is created

de.metas.adempiere.adempiere/base/src/main/java/de/metas/organization/impl/OrgDAO.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/QueryOrderByBuilder.java, de.metas.business/src/main/java-legacy/org/compiere/model/MProductPricing.java, de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java, de.metas.business/src/main/java/de/metas/invoice/impl/InvoiceLineBL.java, de.metas.business/src/main/java/de/metas/order/OrderFreightCostsService.java, de.metas.business/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java, de.metas.business/src/main/java/de/metas/pricing/IEditablePricingContext.java, de.metas.business/src/main/java/de/metas/pricing/IPricingContext.java, de.metas.business/src/main/java/de/metas/pricing/attributebased/impl/AttributePricing.java, de.metas.business/src/main/java/de/metas/pricing/rules/PriceListVersion.java, de.metas.business/src/main/java/de/metas/pricing/service/IPricingBL.java, de.metas.business/src/main/java/de/metas/pricing/service/ProductPriceQuery.java, de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java, de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingContext.java, de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java, de.metas.contracts/src/main/java/de/metas/contracts/FlatrateTermPricing.java, de.metas.contracts/src/main/java/de/metas/contracts/commission/invoicecandidate/CommissionShareHandler.java, de.metas.contracts/src/test/java/de/metas/contracts/pricing/SubscriptionPricingRuleTest.java, de.metas.contracts/src/test/java/de/metas/contracts/pricing/SubscriptionPricingTestHelper.java, de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pricing/spi/impl/HUPricing.java, de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/PricingContextBuilder.java, de.metas.procurement.base/src/main/java/de/metas/procurement/base/impl/PMMPricingBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ManualCandidateService.java
* HUPricing - accept packaging prices that are not attribute-dependant, even if the referenced product is ASI-Aware (but do prefer attribute-dependenat prices)
* AttributeSetInstanceBL - fix warning that flooded the log
https://github.com/metasfresh/metasfresh/issues/5917
=> 5917-app - Product price not found if ASI was added to order line

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/mm/attributes/AttributeSetInstanceId.java, de.metas.business/src/main/java/de/metas/order/IOrderDAO.java, de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java, de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSetInstanceAware.java, de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSetInstanceBL.java, de.metas.business/src/main/java/org/adempiere/mm/attributes/api/PlainAttributeSetInstanceAware.java, de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java, de.metas.contracts/src/main/java/de/metas/contracts/inoutcandidate/SubscriptionShipmentScheduleHandler.java, de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/api/impl/DDOrderLineAttributeSetInstanceAware.java, de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/OLCandASIAwareFactory.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleHandlerBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentSchedulePA.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleASIAware.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleHandlerBL.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/IShipmentScheduleInvalidateRepository.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_Order_ShipmentSchedule.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/InOutCandidateValidator.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/ShipmentScheduleHandler.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/inoutcandidate/OrderLineShipmentScheduleHandler.java, de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5539740_sys_gh5960-app_idx_perf_and_message.sql, de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBLTest.java
* close and open affected shipment schedules as the respective sales order is reactivated and completed again
https://github.com/metasfresh/metasfresh/issues/5960
=> Shipmentschedule not updated after order reactivate and re-complete

de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/process/AD_Column_CopySelectedToTable.java, de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_DiscountAllocation_Process.java, de.metas.contracts/src/main/java/de/metas/contracts/process/C_Flatrate_Term_Create_For_BPartners.java, de.metas.edi/src/main/java/de/metas/edi/process/EDIExportDocOutboundLog.java, de.metas.edi/src/main/java/de/metas/edi/process/EDI_Desadv_Aggregate_M_InOuts.java, de.metas.edi/src/main/java/de/metas/edi/process/EDI_Desadv_EnqueueForExport.java, de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/process/M_ShipmentSchedule_EnqueueSelection.java, de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_Generate_M_InOuts.java, de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/process/MD_Candidate_Request_MaterialDocument.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Printing_Queue_ReEnqueue.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Printing_Queue_ResetAggregationKeys.java, de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCand_Validate_Selected.java, de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/OLCandSetOverrideValues.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ShipmentSchedule_ChangeDeliveryDate.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ShipmentSchedule_CloseShipmentSchedules.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inventory/process/M_InventoryLine_AssignSelectedLines.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inventory/process/M_InventoryLine_MarkAsCounted.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/process/C_Invoice_Candidate_Close.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/process/C_Invoice_Candidate_EnqueueSelectionForInvoicing.java, de.metas.swat/de.metas.swat.base/src/main/java/de/metas/payment/process/C_Payment_DiscountAllocation_Process.java
change ProcessInfo to force the dev to decide if she/he want's all or nothing in case no query filter is specified.
fix compile errors by choosing "nothing" in all current cases
IMPORTANT: this is branched from the 5.132_last_christmas branch
=> Make metasfresh more robust in case of unspecified selections

de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/modelvalidator/C_OLCand.java, de.metas.salescandidate.base/src/test/java/de/metas/ordercandidate/modelvalidator/C_OLCandMVTest.java
otherwise there is no point, and e.g. invoice jaspers vill look as if the product name is printed twice on them
=> only set C_OLCand.ProductDescription if different from product-name

de.metas.acct.base/src/main/sql/postgresql/ddl/functions/AccountSheetReport.sql, de.metas.acct.base/src/main/sql/postgresql/ddl/functions/logDebug.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5551900_sys_gh6121_AddAccountSheetReport_and_logDebug_HelperFunction.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5551930_sys_gh6121_AddAccountSheetProcess.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5551980_sys_gh6121_Fixed_Functions.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5552150_sys_gh6121_AddMigrationScript.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5552200_sys_gh6121_UpdateTRL.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5552210_sys_gh6121_UpdateColumnsOrder.sql, de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/service/ExcelExporterService.java, de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java-legacy/org/compiere/server/AlertProcessor.java
https://github.com/metasfresh/metasfresh/issues/6121
=> Jasper Report: `Account Sheet` - `Kontenblatt`

de.metas.marketing/serialletter/src/main/java/de/metas/letter/service/SearialLetterService.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/IPrintingQueueQuery.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PlainPrintingDAO.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintJobBL.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintingDAO.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintingQueueBL.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintingQueueQuery.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/AbstractPrintJobCreate.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Print_Job_Create.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Print_Job_TestPrintQueueItem.java, de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Printing_Queue_ReEnqueue.java, de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/5552890_sys_gh6252-app_tweak_massprint_related_processes.sql, de.metas.printing/de.metas.printing.base/src/test/java/de/metas/printing/api/impl/Helper.java
* C_Print_Job_Create: important fix: if no explicit selection is made, then select *no* item (as opposed to *all* items)
* PrintingQueueQuery
* rename "printed" property to "filterByProcessedQueueItems"
* remove hardcoded queuals, hashcode and toString and use lombok instead
* PrintJobBL, PrintingQueueBL and C_Printing_Queue_ReEnqueue: minor logging-improvals
* AbstractPrintJobCreate: remove obsolete trxName parameter
* fixed parameter names and descriptions in C_Printing_Queue_ReEnqueue
* Fix name of process C_Print_Job_Create
* Fix name and description of AD_User.IsLoginAsHostKey
* Deactivate legacy Process ConcatenatePdfs (which might again be useful in future)
#6252
=> 6252-app - Improve mass printing usability

de.metas.acct.base/src/main/sql/postgresql/ddl/functions/AccountSheetReport.sql, de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5554820_sys_gh6121_MakeAccountSheetReportLanguageAware.sql
https://github.com/metasfresh/metasfresh/issues/6121
=> Hide DocType with name  `** Neu **`

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/CompositeInterfaceWrapperHelper.java, de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
instead of logging, because returning null will probably result in a new trx that will end up idle in transaction
=> CompositeInterfaceWrapperHelper: getTrxName can throw exception

README.md
Hi, the Krihelinator project has reached its [end of life](https://github.com/Nagasaki45/krihelinator). Thats why i removed the badge.
=> Removed Krihelinator badge from Readme file

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/api/BankAccountId.java, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558300_sys_gh6547_UpdateTrls 1.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558310_sys_gh6547_UpdateTrls 2.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558410_sys_gh6547_UpdateTrls 3.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558450_sys_gh6547_UpdateTrls 4.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558460_sys_gh6547_AddValidationRuleFor_C_BankStatementLine.C_Invoice.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558480_sys_gh6547_Clean_CashJournal_Window.sql, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/callout/C_BankStatementLine.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/IBankStatementPaymentBL.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/BankStatementPaymentBL.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/modelvalidator/C_Payment.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/IBankStatementBL.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/IBankingBL.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankStatementBL.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankingBL.java, backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/service/impl/BankStatementPaymentBLTest.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MPayment.java, backend/de.metas.business/src/main/java/de/metas/payment/api/DefaultPaymentBuilder.java, backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentBL.java, backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java, backend/de.metas.business/src/main/java/org/adempiere/bank/BankRepository.java, frontend/buildfile.groovy
https://github.com/metasfresh/metasfresh/issues/6547
=> Cash Journal: Doubled lines after complete and Payment link to wrong line/wrong cashbook

e2e/cypress/integration/picking/pick_HUs_and_create_shipment.js, e2e/cypress/support/commands/navigation.js
Added back tests from the picking
Note that all the other tests from Generate the shipment and below are failing due to the changes in the references added a while back by Teo in the way references are loaded. I commented those for now and want to fix them in a separate Cypress chunk.
=> Add back the picking tests 6557

frontend/src/components/Container.js, frontend/src/components/app/DocumentList/index.js, frontend/src/components/app/MasterWindow.js, frontend/src/components/app/Modal.js, frontend/src/components/app/RawModal.js, frontend/src/components/header/Header.js, frontend/src/components/header/SubHeader.js, frontend/src/containers/Board.js, frontend/src/containers/DocList.js, frontend/src/routes.js, frontend/src/utils/documentListHelper.js, frontend/src/utils/documentReferencesHelper.js
Remove some unnecessary imports, empty objects/arrays, props etc. This limits the number of re-renders by a great deal.
Related to #6666 
Tested on a sales order list with one order when logging renders, and on w101 for performance tests.
Before:
After:
=> Refactor DocList and it's child components

e2e/.gitignore, e2e/README.md, e2e/cypress/config.js_template_local, e2e/cypress/config.js_template_remote, e2e/cypress/plugins/index.js
Make cypress take all its config from `/cypress/config.js`. In this way only the config can be modified whenever cypress has to be run
=> Cypress no longer needs an env variable

frontend/src/components/Container.js, frontend/src/components/app/DocumentList/DocumentList.js, frontend/src/components/app/DocumentList/index.js, frontend/src/components/header/Header.js, frontend/src/containers/DocList.js, frontend/src/reducers/viewHandler.js, frontend/src/utils/documentListHelper.js
Turns out using `PureComponent` works even better than trying to manually compare props before the update. Especially when opening modals, as it decreases the number of refreshes 3x
Related to #6666
=> Proper fix over the temporary hotfix for DocList/quickactions

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/api/IBPBankAccountDAO.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/api/impl/BPBankAccountDAO.java, backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java, backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java, misc/services/admin/src/main/resources/application.properties
* basically the fix is to not deactivate C_BP_BankAccounts that have no IBAN, because those
* are not loaded into the bpartnercomposite and the API can't access them anyways
* would otherwise always be deactiaved
* application.properties: unrelated cleanup
=> Fix accidental inactivation of not-IBAN bank accounts

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561410_gh6848_RemoveAll_ASI.Description_WhichAreAn_ASI_ID.sql
The query in `5561410_gh6848_RemoveAll_ASI.Description_WhichAreAn_ASI_ID.sql` is only partly correct as it checks if the current ASI_ID appears as a description.
What should have been checked instead is that the current description appears in any IDs, and in that case to NULL it.
https://github.com/metasfresh/metasfresh/issues/6848
=> Add sql query to cleanup all ASIs which have description = ASI_ID

backend/de.metas.adempiere.libero.libero/src/test/java/de/metas/material/planning/pporder/impl/PPOrderBOMBLTest.java, backend/de.metas.adempiere.libero.libero/src/test/java/org/eevolution/mrp/api/impl/MRPTestHelper.java, backend/de.metas.business/src/main/java/de/metas/uom/CreateUOMConversionRequest.java, backend/de.metas.business/src/main/java/de/metas/uom/IUOMConversionBL.java, backend/de.metas.business/src/main/java/de/metas/uom/UOMConversionRate.java, backend/de.metas.business/src/main/java/de/metas/uom/UOMPrecision.java, backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMConversionBL.java, backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMConversionDAO.java, backend/de.metas.business/src/test/java/de/metas/business/BusinessTestHelper.java, backend/de.metas.business/src/test/java/de/metas/customs/CustomsInvoiceServiceTest.java, backend/de.metas.business/src/test/java/de/metas/uom/impl/UOMConversionBLTest.java, backend/de.metas.business/src/test/java/de/metas/uom/impl/UOMConversionDAOTest.java, backend/de.metas.business/src/test/java/de/metas/uom/impl/UOMConversionRateTest.java, backend/de.metas.business/src/test/java/de/metas/uom/impl/UOMTestHelper.java, backend/de.metas.edi/src/test/java/de/metas/edi/api/impl/DesadvBLTest_addInOutLine.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/HUTestHelper.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/pporder/api/HUPPOrderIssueProducerTest.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/inoutcandidate/spi/impl/HUReceiptLineCandidatesBuilderTest.java, backend/de.metas.material/planning/src/test/java/de/metas/material/planning/pporder/impl/QtyCalculationsBOMLineTest.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/adempiere/service/impl/OrderLineBLTest.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBLTest.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredQtysLoaderTest.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateFixtureHelper.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.java
https://github.com/metasfresh/metasfresh/issues/6898
=> Avoid using C_UOM_Conversion.DivideRate

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_InvoiceProcessingServiceCompany.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_InvoiceProcessingServiceCompany_BPartnerAssignment.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_InvoiceProcessingServiceCompany.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_InvoiceProcessingServiceCompany_BPartnerAssignment.java, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562340_sys_gh6904_Move_feePercentageOfGrandTotal_fromHeaderToLine.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562420_sys_gh6904_Add_ValidFrom_to_InvoiceProcessingServiceCompany.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562430_sys_gh6904_DropBPartnerUniqueIndexFrom_InvoiceProcessingServiceCompany_BPartnerAssignment.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562660_sys_gh6904_Add_BPartner_IdentifierFor_InvoiceAndPayment.sql, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentDocument.java, backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java, backend/de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/model/PaymentRow.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingFeeCalculation.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingFeeFromPaymentRequest.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingFeeWithPrecalculatedAmountRequest.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfig.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfigId.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfigMap.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfigRepository.java, backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyService.java, backend/de.metas.business/src/test/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyServiceTest.java, backend/de.metas.util/src/main/java/de/metas/util/lang/Percent.java, backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/InvoiceRow.java, backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/InvoiceRowReducers.java, backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java, backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/PaymentRow.java, backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommand.java, backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java
https://github.com/metasfresh/metasfresh/issues/6904
=> Servicefees per Provider Customer

frontend/src/components/app/DocumentList.js, frontend/src/containers/DocumentList.js
Remove the unnecessary request on WS event. Also fix functions for fetching quick actions.
=> [Frontend] Don't hit /filter endpoint on update

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_MatchPO.java
it's enough to create no facts at all.
Usually, system creates separate M_MatchPO records for each receipt
( with @teosarca )
=> hotfix Doc_MatchPO - avoid failing if receipt line is not set

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/WEBUI_CloneLine.java
=> #1253 No longer showing 'Clone Line' action when subtab's table is the same as the document's.

frontend/package.json
Got this advisory on the legacy repo. Still on the monorepo we are using the same version and we need to upgrade it.
=> Upgrade lodash due to security advisory

backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java, backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
Issue #6526 
This change has been validated on PostFinance Test Platform/ SIX Swiss Payment Standards Validation.Portal / ZKB Test Platform
Answer from PostFinance because the SEPA File was not accepted:
Gemäss pain.001 xsd muss bei der xsi:schemaLocation eine gültige URL vorhanden sein. Siehe dazu auch die IG der SIX (https://www.six-group.com/interbank-clearing/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf )
=> fix(SEPA Export): schemaLocation

frontend/src/actions/ViewActions.js
I still have to figure out a way to test it but other than that - good to go.
=> Properly refresh viewId for included view

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
because those HUs are inactive.
=> hotfix: filter does not work in "return HUs to customer" view

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5564840_sys_gh7062_TheresABugInOurTrlGenerationForSure.sql
https://github.com/metasfresh/metasfresh/issues/7062
Especially because on a dev instance on latest master, the trls appear corrrectly. 
On releasetest dev, where i did the dev tesing before merge, the trl is also ok: 
- dev test https://github.com/metasfresh/me03/issues/5217#issuecomment-666290828
- releasetest dev: https://releasetestdev.metasfresh.com/window/540092?refDocumentId=1006059&refType=143&referenceId=AD_RelationType_ID-540193&viewId=540092-C&page=1
wth is wrong with our trl creation?
the sql is the same in both cases
- works: new dev instance, release test dev (old instance where i did a rollout)
- not works: customer extremely old instance where i did a rollout
=> There's 100% a bug in our translation generation, but i cant figure out how to reproduce it

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidate.java
in this case, (like elsewhere too) we fall back to the nominal weight
=> Fix NPE if an invoice candidate is in catch weight but none is given

frontend/src/components/widget/SelectionDropdown.js
Cherry-picking to `blonde_monkey_uat`
=> Prevent `key` naming collision in the SelectionDropdown

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java
This makes creating Requests via process, similar to creating them via `Add New` button in the Request window
https://github.com/metasfresh/metasfresh/issues/7183
=> Set `dateTrx` when creating a new `R_Request` via process

e2e/cypress/integration/inventory/create_disposal_from_handling_unit_editor.js, e2e/cypress/integration/inventory/inventory_aggregatedHUs_spec.js, e2e/cypress/integration/inventory/inventory_singleHU_spec.js, e2e/cypress/integration/picking/pick_HUs_and_create_shipment.js, e2e/cypress/support/commands/action.js, e2e/cypress/support/commands/form.js, e2e/cypress/support/commands/general.js, e2e/cypress/support/functions/index.js, e2e/cypress/support/utils/builder.js, e2e/cypress/support/utils/inventory.js
Related to #10082.
- One of the problems here is that when we clear the filters, page is refreshed but cypress is so fast, it starts clicking elements before the reload finishes. Because of that it can't find some elements.
- A separate problem is that the UOM field is filled when the product is selected. So with the current architecture we won't do the request when nothing changed in the widget. And in this case prefilled value and the one we were typing are the same. I've tried adding a check for the current input value in the lookup helpers but looks like it's not gonna be that easy. 
- Also looks like picking from the picking terminal now doesn't open a modal, but a new window instead. So a lot of actions were tripping over that.
=> Have a swing at fixing failing e2e tests

misc/parent-pom/pom.xml
This fixes some bugs with idea 2020.2 and makes idea 2020.3 work. Without this update idea 2020.3 will not be able to compile metasfresh.
Idea issue: https://youtrack.jetbrains.com/issue/IDEA-252069
Lombok issue: https://github.com/rzwitserloot/lombok/issues/2592
=> Update lombok to 1.18.14 from 1.18.10

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/provider/userQuery/UserQueryDocumentFilterDescriptorsProviderFactory.java
=> #10192 Custom queries now working as default filters, no longer inserting that column's validation rule from the table it refers to.

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/ICurrencyBL.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/exceptions/NoCurrencyRateFoundException.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/impl/CurrencyBL.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MCash.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java, backend/de.metas.business/src/main/java/de/metas/costing/methods/CostingMethodHandlerUtils.java, backend/de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java, backend/de.metas.business/src/main/java/de/metas/money/MoneyService.java, backend/de.metas.business/src/main/java/de/metas/order/OrderFreightCostsService.java
Avoid NPE in case of missing currency conversion. Instead throw a much more understandable exception.
The triggering exception was:
```
de.metas.acct.doc.PostingException: NullPointerException
Buchungsstatus: Verbuchungs-Fehler (Error)
Belegnummer: MMatchPO[1004524,Qty=26.00000,C_OrderLine_ID=1042334,M_InOutLine_ID=1030499,C_InvoiceLine_ID=0]
Preserve Posted status: false
Additional parameters:
issueCategory: ACCOUNTING
recordRef: TableRecordReference{tableName=M_MatchPO, recordId=1004524}
at org.compiere.acct.Doc.newPostingException(Doc.java:1844)
at org.compiere.acct.Doc$1.doCatch(Doc.java:376)
at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.doCatch(TrxCallableWrappers.java:160)
at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:786)
at …
```
=> fix NPE on missing currency conversion

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5572030_sys_add_Fact_Acct_Log_ID.sql, backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java, backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/AdempiereDatabase.java, backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/DB_PostgreSQL.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/dao/selection/QuerySelectionToDeleteHelper.java
for more details check the comments of each commit
=> Avoid using Postgres OID

backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java
https://github.com/metasfresh/mf15/issues/396
=> #396 Implement process precondition

backend/de.metas.business/src/main/java-legacy/org/compiere/model/MRequest.java
https://github.com/metasfresh/metasfresh/issues/10228
=> No longer reset `R_Request.EndTime` when a Request is saved

frontend/src/components/widget/MasterWidget.js
Calls too zoomInto was done like 
```
rest//api/window/ADP_541124/1120502/field/AD_UserGroup_ID/zoomInto
```
After this PR is merged it will use the actual entity for forming the zoomInto path:
```
rest//api/process/ADP_541124/1120502/field/AD_UserGroup_ID/zoomInto
```
Even if this does not exist yet in the BE it fixes the frontend part.
https://www.loom.com/share/dc681d2049714ee4a2411ae1e4c785d9
=> Fix ZoomInto path in the handleZoomInto function to use the entity

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/BPartnerEndpointAdapter.java, backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java, backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest_Create_UpdateMerge_1.json
the olcand's bpartners' "inner" syncadvices are now applied on the bpartner-request's middle level.
That way a user can specify a bpartner to be not updated, but new locators or contacts to be inserted if they don't yet exist
=> redistribute syncadvise when creating bpartner from olcand-bpartnerinfo

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574310_sys_gh10382_changing_reference_to_search_in_basepricelist.sql
https://github.com/metasfresh/me03/issues/6306
=> Changing Reference to Search in Basepricelist

backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
The cache invalidation is needed if any update happens
=> Prices of inactive products

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/CalloutEngine.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/annotations/CalloutMethod.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/annotations/api/ICalloutMethodPointcut.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/annotations/api/impl/AnnotatedCalloutInstance.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/annotations/api/impl/AnnotatedCalloutInstanceFactory.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/annotations/api/impl/CalloutMethodPointcut.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/api/impl/CalloutExecutor.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_OrderLine.java
...and use it to set "manualPrice" to Y *only* if user manually edits priceEntered
=> Add property skipIfIndirectlyCalled to annotation CalloutMethod

frontend/src/components/app/Modal.js
https://github.com/metasfresh/metasfresh/issues/10434
https://www.loom.com/share/79c989f2079344db91760aae2633eedc
Issue was introduced due to the removal of the parentWindowId in here https://github.com/metasfresh/metasfresh/pull/10392/files#diff-ddc5443e1773de9663c1851d07cbcc645f69f2065aea13b2aa8ffc37e9014808L125
Fixed by replacing and using the documentType instead to preserve the functionality.
=> Adapts to fix the patching on hitting the Done button

frontend/src/__tests__/containers/MasterWindow.test.js, frontend/test_setup/jestSetup.js
https://github.com/metasfresh/metasfresh/issues/10436
https://www.loom.com/share/29d2c6ae66fd465ab8e3ca7ec26580e4
=> Set the testing port to a higher one to avoid collitions

backend/de.metas.business/src/main/java/de/metas/order/OrderLinePriceUpdateRequest.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/callout/C_OrderLine.java
https://github.com/metasfresh/metasfresh/issues/10365
=> Fixes for OrderLine.LineNetAmt and Flatrate Conditions

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/payment/JsonPaymentService.java, backend/de.metas.business/src/main/java/de/metas/order/IOrderDAO.java, backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java, misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/payment/JsonInboundPaymentInfo.java
Allow a blank docBaseType if not using doc- as IdentifierString
If OrderIdentifier is of type external, persist to C_Payment.ExternalId;
if OrderIdentifier is not of type external retrieve and persist C_Payment.ExternalId and C_Payment.C_Order_ID
https://github.com/metasfresh/metasfresh/issues/10501
=> #gh10501 bug fixes

backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java, backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java, backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java, backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java, backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java, backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
add haddex validations to:
* partner change
* promised date changed
* order completion
https://github.com/metasfresh/metasfresh/issues/10538
=> refactoring Haddex

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfo.java, backend/de.metas.util.web/src/main/java/de/metas/util/web/exception/RestResponseEntityExceptionHandler.java
..so that it makes use of the given exception's Http-Status
plus a few minor improvements in POInfo
=> improve RestResponseEntityExceptionHandler's "default" method

frontend/src/containers/MasterWindow.js
Looks like this was disabled when I did some quick changes to unblock Petrica on his inline tab widget effort. So this looks like a temporary thing that should be reverted. 
https://github.com/metasfresh/metasfresh/pull/10301/commits/d97d319b84ba30256c7f73d94f2371114d7d6664#diff-1cfcb26643fbe64684980f1488db853ee0b5abe32b52125ee175f6e9054bd87aL55
@petrican where can the inline tab be tested to be sure it's not affected ?
=> Don't show doc actions when they shouldn't be visible

frontend/src/actions/TableActions.js
Will add a better test coverage in a separate PR, but we need this for the release.
Related to #10721
=> Properly refresh quick actions when parent selection changes

frontend/.eslintrc, frontend/src/__tests__/reducers/Tables.test.js, frontend/src/actions/TableActions.js, frontend/src/components/table/Table.js, frontend/src/containers/Table.js, frontend/src/reducers/tables.js, frontend/src/utils/documentListHelper.js, frontend/src/utils/tableHelpers.js
* - fix linter with updated babel parser
* #10715 refactor collapsible tables
* #10715 use empty arrays in case table doesn't exist yet
#	frontend/src/actions/TableActions.js
=> Fix CP error

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/ReverseDraftIssues.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/api/ManufacturingOrderDocumentReportAdvisor.java
- avoid NPE when printing manufacturing orders that have no partner
- use FIFO for the source CUs even when they were split from a bigger CU and then removed
=> Gh10778 - manufacturing improvements

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/QueryStatisticsLogger.java, backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getC_BPartner_Product_Details.sql, backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5581710_sys_getC_BPartner_Product_Details.sql
Test SQL:
```sql
SELECT *
FROM de_metas_endcustomer_fresh_reports.getC_BPartner_Product_Details
(2006673,2156884,0)
;
```
Execution plan before the fix:
Execution plan after fix:
=> fix getC_BPartner_Product_Details performances

frontend/src/actions/FiltersActions.js, frontend/src/components/filters/InlineFilterItem.js, frontend/src/reducers/filters.js, frontend/src/utils/filterHelpers.js
This is a fix for the release but I want to look deeper into that and check if we shouldn't add some more guards, as most of the time we assume everywhere there's only one active filter, or a filter has single parameter.
Related to #10801
=> Fix inline filters

frontend/package.json
Move us to the latest version of babel transpiler and eslint. Also update `axios` because of a critical security fix.
=> Update babel packages

e2e/cypress/support/commands/form.js
https://github.com/metasfresh/metasfresh/issues/10826
https://dashboard.cypress.io/projects/5yp4q1/runs/983/specs
There is only one test remaining that is failing due to a BE bug (opened issue for it https://github.com/metasfresh/mf15/issues/725)
=> Fix e2e tests - flaky

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerOrgBL.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocumentLocationBL.java, backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/MasterdataProviderTest.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrderLine.java, backend/de.metas.business/src/main/java/de/metas/invoice/callout/C_Invoice.java, backend/de.metas.business/src/main/java/de/metas/invoice/export/InvoiceToExportFactory.java, backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceLineBL.java, backend/de.metas.business/src/test/java/de/metas/bpartner/impexp/BPartnerImportTestHelper.java, backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/EDIDocumentBL.java, backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/PickingSlotKey.java, backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/ProductKey.java, backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/setup/process/ClientSetup.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleEffectiveBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/agg/key/impl/ICLineAggregationKeyBuilder_OLD.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/mm/attributes/countryattribute/impl/InvoiceLineCountryAware.java, backend/de.metas.vertical.pharma/src/main/java/de/metas/impexp/bpartner/IFABPartnerLocationImportHelper.java
Because e.g. if you have a completed invoice and someone deactivated the bpartner-location that the invoice refers to, then the invoice should still be able to e.g. get the location's country.
=> In the end, after checking the call hierachy of `getBPartnerLocationById` i think that actually in every case, there should *not* be a `null` returned, even if the C_BPartner_Location was meanwhile deactivated.
=> Return even inactive C_BPartner_Locations at many places

frontend/src/reducers/actionsHandler.js
In the latest immer version the original method doesn't allow passing undefined.
How I tested this on my local to make sure it works fine
https://www.loom.com/share/66dfe2381849489ca085b9cc34ac2713
=> Add safety checks for immer original

frontend/src/components/widget/Checkbox.js
Extra safety check for the case when we do not have the fnct defined (updteItems) - this can happen outside the filters
=> Add extra safety check for the case when we do not have fnct defined

frontend/src/components/table/TableQuickInput.js
This also lets us simplify the component itself and get rid of state.
Related to #10860
=> After adding new entry, table quick input should only focus on first field

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/DB.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/ISqlQueryFilter.java, backend/de.metas.async/src/main/java/de/metas/async/api/impl/WorkPackageBuilder.java, backend/de.metas.async/src/main/java/de/metas/lock/api/ILock.java, backend/de.metas.async/src/main/java/de/metas/lock/api/ILockCommand.java, backend/de.metas.async/src/main/java/de/metas/lock/api/ILockManager.java, backend/de.metas.async/src/main/java/de/metas/lock/api/LockOwner.java, backend/de.metas.async/src/main/java/de/metas/lock/api/impl/AbstractLockDatabase.java, backend/de.metas.async/src/main/java/de/metas/lock/api/impl/Lock.java, backend/de.metas.async/src/main/java/de/metas/lock/api/impl/LockAutoCloseableOnTrxClose.java, backend/de.metas.async/src/main/java/de/metas/lock/exceptions/LockException.java, backend/de.metas.async/src/main/java/de/metas/lock/exceptions/LockFailedException.java, backend/de.metas.async/src/main/java/de/metas/lock/spi/impl/SqlLockDatabase.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/AD_User_StepDef.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/Lock_StepDef.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/issue/AD_Issue_StepDef.java, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createIssue.feature, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/sqlLockDatabase.feature, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/storePInstanceLog.feature, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleEnqueuer.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/CreateMissingShipmentSchedulesWorkpackageProcessor.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java, backend/de.metas.util/src/main/java/org/adempiere/util/concurrent/CloseableReentrantLock.java
* ShipmentScheduleEnqueuer - don't wait for for the lock to be closed async later on
* If aquiring a lock fails, select and output the existing locks
=> ShipmentScheduleEnqueuer - directly close the lock when done

frontend/src/components/table/TableQuickInput.js
https://www.loom.com/share/27ee8a7415264d5cbaf4ef7084e44c32
The dropdown from behind should not be shown anymore.
=> Fix the focus from the quick input table

frontend/src/assets/css/indicator.css, frontend/src/components/charts/Indicator.js, frontend/src/components/charts/RawChart.js
Reshape the dashboard indicators
- pass separately the amount and the unit
- have the amount and unit to be rendered as separate divs to allow further customisation of these when the time comes
- make the caption to be with uppercase
- use our colors
=> 11371 dashboard indicators

frontend/src/components/keyshortcuts/DocumentListContextShortcuts.js, frontend/src/components/table/TableContextMenu.js, frontend/src/components/table/TableWrapper.js
Tested on localhost
http://localhost:3000/window/143/1007847
Going to Product Proposals ALT+B doesn't open the record. Also the TableContextMenu doesn't render it either if you right click. The supportOpenRecord that comes from the BE is considered
Tested also (as regression) other areas and this are showing it 
ex: BP
also SOL in a SO
=> Consider supportOpenRecord on FE side

frontend/src/__tests__/components/table/TableCellLabel.test.js, frontend/src/assets/css/table.css, frontend/src/components/table/TableCellLabel.js, frontend/src/constants/Constants.js
- I didn't had bigger labels to test when first implemented. Now that I had I pushed this fix for those cases when the label is bigger.
- if this is fine it can be cp to other branches as well.
=> Routine that chops the label if that exceeds 10 chars

frontend/src/components/table/TableContextMenu.js
demo
https://www.loom.com/share/0a7646d599564b87b8b34164966bd492
display the popup only after the loading of resources completed (only for the cases when the resources are loaded, when docId is present).
=> Fix rendering the popup when loading references is used

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/annotations/DocValidate.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/modelvalidator/C_AllocationHdr.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/IPaymentAllocationBL.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidate.java, backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java, backend/de.metas.business/src/main/java/de/metas/allocation/api/C_AllocationHdr_Builder.java, backend/de.metas.business/src/main/java/de/metas/allocation/api/IAllocationBL.java, backend/de.metas.business/src/main/java/de/metas/allocation/api/IAllocationDAO.java, backend/de.metas.business/src/main/java/de/metas/allocation/api/impl/AllocationBL.java, backend/de.metas.business/src/main/java/de/metas/allocation/api/impl/AllocationDAO.java, backend/de.metas.business/src/main/java/de/metas/allocation/modelvalidator/C_AllocationHdr.java, backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_AllocationHdr.java, backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java, backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java, backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdvice.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/actionhandler/impl/AbstractESRActionHandler.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/actionhandler/impl/WithCurrenttInvoiceESRActionHandler.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/process/AllocatePayment.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/allocation/api/C_AllocationHdr_ProcessInterceptor.java
* if didn't happen if a credit memo was allocated against a payment and a service invoice (two allocatios)
* i did remove a bunch of now redundant calls too
=> update the invoices' isPaid flag when allocation is completed

frontend/src/actions/TableActions.js, frontend/src/components/table/TableRow.js, frontend/src/containers/DocumentList.js
Updated the recording
https://www.loom.com/share/ff381115156249b99dc7c22942bf50ce
rel to https://github.com/metasfresh/metasfresh/issues/12032
Note: the case when the line is not updated is caused by a BE caching. Documented in the issue
=> consider uncollapseRowsOnChange

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/DB.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/refund/invoicecandidatehandler/FlatrateTermRefund_Handler.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/invoicecandidatehandler/FlatrateTermSubscription_Handler.java, backend/de.metas.contracts/src/test/java/de/metas/contracts/flatrate/impexp/IFlatrateTermFactory.java, backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/AbstractFlatrateTermTest.java, backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java, backend/de.metas.contracts/src/test/java/de/metas/contracts/invoicecandidate/FlatrateTermHandlerTest.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/RunCucumberTest.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java, backend/de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java, backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandInvalidUpdater.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/IInvoiceCandidateHandler.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/InvoiceCandidatesTestHelper.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/C_OrderLine_Handler_Test.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/QtyDeliveredFromOrderToInvoiceTest.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/exceptions/DocumentFieldReadonlyException.java, backend/de.metas.util/src/main/java/de/metas/util/lang/Percent.java
..so the IC does not need to be deleted and recreated.
- implemented for orderLines, inoutLines and subscriptions
- the class PriceAndTax actually can contain the TaxId now
=> invoice candidate updating now can also set the invoice's C_Tax_ID

frontend/src/containers/DocumentList.js
- fixes the edge case that was found during last QA testing (moving from one window to another using the menu and then go back)
https://www.loom.com/share/75b7a8089f2144f9ac9b5b24c19d3332
=> Add extra safety check for calling getData within handleChangePage

frontend/src/utils/locale.js
Fallback to en in case no locale passed
Without this fix cypress encounters thrown error and stops testing
this happens because at the mom of the call to get the LOCAL_LANG from localStorage this could not yet be set in the local storage (cypress is super fast) so we need to provide a fallback mechanism.
=> fix for e2e tests

frontend/src/assets/css/styles.css
rel to https://github.com/metasfresh/metasfresh/issues/12160
Fixes this issue:
After the fix:
Tested also the cases done by Kuba from here https://recordit.co/ObafncCYtt and work as expected.
=> Fix extra scroll on filter items

misc/services/mobile-webui/mobile-webui-frontend/package.json
- lock immer version to prevent future surprises introduced by possible breaking changes
- replaced node-sass because if it were to use the latest version this will bring incompatibility issues with the node version 16
- added `sass` package instead to prevent future issues 
-
=> 12264 mobile UI vulnerable pkgs

backend/de.metas.business/src/main/java/de/metas/pricing/IPricingResult.java, backend/de.metas.business/src/main/java/de/metas/pricing/rules/Discount.java, backend/de.metas.business/src/main/java/de/metas/pricing/rules/PriceListVersion.java, backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingResult.java, backend/de.metas.business/src/test/java/de/metas/pricing/service/impl/PricingTest.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/pricing/SubscriptionPricingRule.java, backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5619761_sys_gh11728_fix_IfForeignDiscountsExist_names.sql
https://github.com/metasfresh/metasfresh/issues/11728
=> #11728 correct IfForeignDiscountsExist names, not just translations. Use isDiscountEditable to also drive order of discounts being applied

frontend/src/assets/css/styles.css
rel to: https://github.com/metasfresh/metasfresh/issues/12160
was added by Kuba as a separator. Agreed with Daniela that we should have consistent layout and that div should not be added.
=> Remove the divider on top of Apply

backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBL.java, backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBL.java
Fix error:
```
org.adempiere.exceptions.AdempiereException: NullPointerException: NullPointerException
Additional parameters:
I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=2974401, trxName=null]
IQueueProcessor: ThreadPoolQueueProcessor{name=DocOutboundWorkpackageProcessor, executor=BlockingExecutorWrapper(semaphore=java.util.concurrent.Semaphore@65f27dad[Permits = 0], delegate=java.util.concurrent.ThreadPoolExecutor@138b507e[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1], logger=Logger[org.adempiere.util.concurrent.BlockingExecutorWrapper])}
trxName: <<ThreadInherited>>
at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:81)
at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAnd …
```
=> #12221 Fix NPE

backend/de.metas.acct.base/src/main/java/de/metas/acct/api/IProductAcctDAO.java, backend/de.metas.acct.base/src/main/java/de/metas/acct/api/impl/ProductAcctDAO.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/activity/model/validator/C_InvoiceLine.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/activity/model/validator/C_OrderLine.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/activity/model/validator/M_InOutLine.java, misc/services/camel/de-metas-camel-externalsystems/pom.xml, misc/services/procurement-webui/procurement-webui-backend/pom.xml
Use respective record's ClientId and OrgId when getting the Activity.
We can't assume that the correct AD_Client_ID and AD_Org_ID are always in the context.
E.g. when processing workpackages they are not.
=> Activity Fix

frontend/webpack.prod.js
Delete first the `dist` folder
To test locally run : `npm run build-prod` and check the dist folder.
=> Fix double dot in bundled images

frontend/package.json
rel to https://github.com/metasfresh/metasfresh/issues/12324
updates packages from the frontend structure that have a new version and can be updated without impact
=> webui: upgrade autoprefixer, webpack, webpack-dev-server, immer

frontend/src/components/dashboard/DraggableWrapper.js
rel to: https://github.com/metasfresh/metasfresh/issues/12359
Note the use of `indicatorsUpdated` flag which is needed because the indicators are initially empty array([]]). Without using that we would see for a split second the logo until the state is updated with the indicators.
=> 12359 hide dashboard logo

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MTree_Base.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/logger/MigrationScriptFileLogger.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/logger/MigrationScriptFileLoggerHolder.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/logger/Sql.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/AD_Column.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/AD_Field.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/AD_Tab.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/AD_Table.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/AD_UI_Element.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/AD_Window.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/TableIdsCache.java
AIM: make our migration scripts easier to read/review.
To achieve this a simple change would be to log additional context info along with the actual SQL command.
Atm, the following application dictionary elements are handled:
* AD_Table
* AD_Column
* AD_Window
* AD_Tab
* AD_Field
* AD_UI_Element
Below you will find some self-explanatory examples
```sql
-- Column: teo_test_3.Name
-- 2022-01-21T01:21:39.215Z
INSERT INTO AD_Column (AD_Client_ID,AD_Column_ID,AD_Element_ID,AD_Org_ID,AD_Reference_ID,AD_Table_ID,ColumnName,Created,CreatedBy,DDL_NoForeignKey,Description,EntityType,FacetFilterSeqNo,FieldLength,Help,IsActive,IsAdvancedText,IsAllowLogging,IsAlwaysUpdateable,IsAutoApplyValidationRule,IsAutocomplete,IsCalculated,IsDimension,IsDLMPartitionBoundary,IsEncrypted,IsExcludeFromZoomTargets,Is …
```
=> Log migration scripts context info

backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java, backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java, backend/de.metas.business/src/test/java/de/metas/order/impl/OrderBLTest.java
only fall back to the order's AD_User as bill-contact if it's consisten with the order's Bill_Partner
=> order's effective bill-contact - only fall back if consistent

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/IdsToFilter.java, backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/window/model/lookup/IdsToFilterTest.java
Fixes issues when a lookup values provider is called with an empty list to IDs.
It shall not throw exception but return empty result.
=> IdsToFilter.streamSingleValues shall return empty if no value

backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
fix OpenAmt incorrect value after vendor credit memo
=> Open amt incorrect after vendor credit memo is created for a vendor invoice

frontend/src/components/widget/DateTime/DatePicker.js
fixes issue introduced by https://github.com/metasfresh/metasfresh/pull/12667
=> DatePicker hotfix: clicking on calendar icon to open the calendar and then clicking on calendar icon again to close it was clearing the input field

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/RelatedDocumentsFactory.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/references/service/WebuiDocumentReferencesService.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/SqlViewFactory.java
the previous error was:
```
Jun 10, 2022 8:56:28 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: No related documents found for source=DocumentAsZoomSource{tableName=M_ReceiptSchedule, recordId=1000000, AD_Window_ID=AdWindowId(repoId=541492)}, targetWindowId=AdWindowId(repoId=540189)] with root cause
org.adempiere.exceptions.AdempiereException: No related documents found for source=DocumentAsZoomSource{tableName=M_ReceiptSchedule, recordId=1000000, AD_Window_ID=AdWindowId(repoId=541492)}, targetWindowId=AdWindowId(repoId=540189)
at de.metas.document.references.related_documents.RelatedDocuments …
```
=> hotfix: don't fail when we open Receipt candidates -> Korrectur

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5648520_sys_gh13368_ispartialpayment_invoice_candidate.sql, backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java, backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
_ change column name to IsInterimInvoice
- regenerated model invoice_candidate
- rewritten from sales invoice to purchase invoice candidate
- changed the filter row
- changed ad_element name fron ispartialpayment to isinteriminvoice
https://github.com/metasfresh/me03/issues/12608
=> rewritten from sales invoice to purchase invoice

frontend/src/components/app/LoginForm.js, frontend/src/containers/App.js
Issue was introduced by https://github.com/metasfresh/metasfresh/pull/12082.
Test cases:
* using a user with single role: try login 
* with OK password => directly login
* with Wrong password => nice error message
* using a user with more than one role: try login 
* with OK password => role selection panel => login OK
* with Wrong password => nice error message
* using a non-existing user (e.g. login user `wfdjlksa`), try login
* => nice error message
* Login using user token, try calling `https://<server>.metasfresh.com/token/<user token>`
* => directly login
=> Fix Login Form: display backend error

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/model/interceptor/AD_Column.java
When creating/updating an AD_Column, the following naming standards will be enforced:
* Lookups shall always end with `_ID` (but not others)
* Account columns shall always end with `_Acct` (but not others)
=> enforce column name naming standards

misc/services/mobile-webui/mobile-webui-frontend/src/utils/qtys.js
i.e. when no precision is provided avoid formatting numbers like '0.076' to something like '0.076000000000001'
=> mobile UI: hotfix formatQtyToHumanReadable

frontend/src/actions/ProcessActions.js
follow-up of https://github.com/metasfresh/metasfresh/pull/13846
=> hotfix: quick actions button remained disabled after openning a new record in a new browser tab

backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5663140_sys_gh13877_fix_AD_Client_ID_of_HU_PI.sql
Change the AD_Client_ID of the "template" and "no packing instruction" HU-PIs from system to "normal". All most all their attributes are already "normal", which causes problems editing them by user-admins
#13877
=> Fix AD_Client_ID of HU-packing instructions

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/model/interceptor/AD_Column.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/ADTableDAO.java
fixes https://github.com/metasfresh/metasfresh/pull/13565
Test case:
* created a new table
* copied columns from X_TableTemplate
=> AD_Column.assertColumnNameValid: allow CreatedBy, UpdatedBy exceptional ID column names

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/expression/api/ILogicExpression.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
* field is flagged as readonly (AD_Field.IsReadOnly=Y)
* column is parent link (AD_Column.IsParent=Y)
* column is mandatory (AD_Column.IsMandatory=Y)
* but the tab does not allow new records (AD_Tab.IsInsertRecord=N)
field shall be readonly because there is no point to make it editable.
The initial intension to make it editable was because in case we want to create a new record we have to set those parent link columns.
But here is not the case, because creating a new record is disabled
NOTE: in our case we didn't made the tab readonly because we want to allow user deleting records.
So we made all the fields readonly.
Before the fix, the field is rendered as editable.
Manufacturing Order Source HU - http://localhost:3000/window/541633
=> webui: hotfix readonly fields (corner case: field flagged as readonly but isparent field, tab insert disabled)

backend/de.metas.elasticsearch/src/main/java/de/metas/fulltextsearch/indexer/process/ES_FTS_Config_Sync.java
i.e. avoid pointless failing in case user asks to delete an ES index which does not exist
=> ES_FTS_Config_Sync: avoid trying to delete index if does not exist

misc/dev-support/docker/infrastructure/search/sources/start-custom.sh
The "search" docker container never started successfully and always stays in "Restarting" state. 
**To reproduce the error:** 
- clone metasfresh repository
- compile & setup intelij ultimate 
- run "Infrastructure: Compose Deployment" 
**Proposed change** 
- after the change of script type to "sh" the container is started successfully 
- tested on windows 10 pro with WSL2 and on Ubuntu 20.04 server VM
I am not really sure why this script doesn't run successfully if "bash" is the type of script file, after all the "sh" is only a symbolic link to "/usr/bin/bash" in the container (I checked).
=> Elasticsearch restarting - docker compose 

backend/de.metas.device.adempiere/src/main/sql/postgresql/system/5667000_sys_gh13840_TcpEndPoint_preserve_behaviour.sql, backend/de.metas.device.scales/pom.xml, backend/de.metas.device.scales/src/main/java/de/metas/device/scales/endpoint/TcpConnectionEndPoint.java, backend/de.metas.device.scales/src/main/java/de/metas/device/scales/endpoint/TcpConnectionReadLineEndPoint.java, backend/de.metas.device.scales/src/main/java/de/metas/device/scales/impl/ConfigureDeviceHandler.java, backend/de.metas.device.scales/src/test/java/de/metas/device/scales/endpoint/TcpConnectionReadLineEndPointTest.java
- change the default behavior of TcpConnectionEndPoint to **not** wait for an EOL when reading the device's response.
- add a subclass that implements the old behavior
(TODO: add migration-script so that exising scales work with the newly added  behavior-preserving endpoint)
=> fix timeout-problem with soehnle devices

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5666800_sys_gh13311_FixWidgetSize_AccountingTransactions.sql
Fix WidgetSize for every ui_element that has the `''` as size instead of null
https://github.com/metasfresh/ab182/issues/237
=> Fix WidgetSize

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5668390_M_Product_Trl_fix_key_columns.sql
**IMPORANT** this PR is fixing only the data (application dictionary).
The code is fixed by
* https://github.com/metasfresh/metasfresh/pull/14134
=> M_Product_Trl: mark M_Product_ID and AD_Language as not lazy loading

backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/IDocOutboundDAO.java, backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/DocOutboundDAO.java, backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java, backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingDataFactory.java
Before this fix the C_Doc_Outbound_Log was searched by AD_Table_ID=AD_Archive, Record_ID=AD_Archive_ID,
and when was created it was using the AD_Archive.AD_Table_ID and Record_ID.
That was causing errors like
```
org.adempiere.exceptions.DBUniqueConstraintException: ERROR: duplicate key value violates unique constraint "c_doc_outbound_log_uc"
Detail: Key (record_id, ad_table_id)=(1007017, 540516) already exists.
SQL: INSERT INTO C_Doc_Outbound_Log (AD_Client_ID,AD_Org_ID,AD_Table_ID,C_Doc_Outbound_Log_ID,Created,CreatedBy,DateDoc,FileName,IsActive,IsInvoiceEmailEnabled,Record_ID,Updated,UpdatedBy) VALUES (1000000,1000000,540516,nextval('c_doc_outbound_log_seq'),TO_TIMESTAMP('2022-12-13 19:16:04','YYYY-MM-DD HH24:MI:SS'),540116,TO_TIMESTAMP('2022-12-13','YYYY-MM-DD'),'Finishedproduct …
```
=> hotfix get/create C_Doc_Outbound_Log

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
follow-up of https://github.com/metasfresh/metasfresh/pull/14839
thx @chemsnouioua  for fixing it
=> HOTFIX NPE on FactLine when setting C_BPartner2_ID

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5682130_AD_Window_ParentChildTableNames_v1.sql
NOTE: in this commit, i just commented out the line about "AND EXISTS (... in menu)" and I've also formatted the code
Impact on data: instead of 1075 records in the view, now we have 1192... so, not much.
=> Invalidate documents even if their window is not in menu

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/PackToHUsProducer.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
i.e. in case the sales order has no packing instructions (i.e. virtual HU) then accept any packing instructions the pick from HU has (ofc if the product and qty is also matching)
=> Avoid changing picking HU

misc/services/camel/de-metas-camel-edi/Dockerfile
https://github.com/metasfresh/metasfresh/issues/15119
Jenkins build without dos2unix command succeeded: https://jenkins.metasfresh.com/job/metasfresh/job/master_gh15119/2/
=> removed dos2unix to rule out potential cause for jenkins build fail

backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
NOTE: we are no longer checking for " && currentCosts.getCurrentQty().isZero() because we agreed that is the responsibility of whom is setting the explicit cost price to decide if it's suitable
=> AveragePOCostingMethodHandler: if explicit cost price is provided then use it

backend/de.metas.business/src/test/java/de/metas/costing/methods/AveragePOCostingMethodHandlerTest.java
Follow-up of https://github.com/metasfresh/metasfresh/pull/15265
=> AveragePOCostingMethodHandler: if explicit cost price is provided then use it (fix unit tests)

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/role_access_add_menu_recursively.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5691130_sys_gh15447_role_access_add_menu_recursively.sql
https://github.com/metasfresh/metasfresh/issues/15447
Adding standard document actions:
- Document Actions:
- Complete add Reverse_Correct would be added to all
- Reactivate only to C_Order
- Close would be added only to PP_Order
=> Gh15447: Adding standard document actions

backend/pom.xml
Update lucene dependency version to match elasticsearch in Java 17 branches
=> master merge is update lucene dependency version to match elasticsearch

backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/RESTUtil.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceRules.feature, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/packingmaterial/shipments.feature, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentSchedule.feature, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentScheduleExport.feature, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/ProcessHUsAndPickingCandidateCommand.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/segments/ShipmentScheduleSegmentFromHUAttribute.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/ShipmentScheduleStockChangedEventHandler.java
* Add ShipmentScheduleStockChangedEventHandler to facilitate schedule-update
this is needed to because the allocated QtyToDeliver and QtyOnHand might change
* add shipmentSchedule.feature to verify the fixed behavior
also:
- M_ShipmentSchedule_StepDef - consolidate two fixtures into one
- minor code improvements
* fix scenario (that i broke before) where the deliveryrule is needed
* Port the rest api cucumber improvement from commit 9bfb9d8cafec7a8807a2dd4bb3bd27d926c1e830
Also add a little improvement from the code-review
* Fix newly introduced error (from the previous commit)
* Fix GLN to be different between two features
(cherry picked from commit f2378b5fdfa211128240b150a5efadf016185eb1)
=> Update affected M_ShipmentSchedules after stock change (#15461)

backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateDAO.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java, backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java, backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5699480_sys_gh16065_add_perf_index_for_modular_related_tabels.sql
- added CCache for `ModularContractSettingsDAO#getByFlatrateTermIdOrNull` && `ModularContractSettingsDAO#getByFlatrateConditonsIdOrNull`
- moved `FlatrateBL#retrieveByModularContractQuery` to `FlatrateDAO` and cached the result using CCache
- created indexes for `ModCntr_Module`, `C_Flatrate_Conditions`, `C_BPartner_InterimContract` && `ModCntr_Log`
=> Vertragsbausteinlog Caching & Co) - Performance enhancements #16065

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationsService.java
Test case:
* login with a user which is using english language
* change the language to something else (e.g. german)
* logout / login
* before the fix the notifications where sent using the english language
=> hotfix: on webui login make sure we are using logged user language

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5707470_sys_Filter_Invoices_from_product_costs_recreate_from_date.sql
* REST API: By default, don't wrap API response (#16375)
* change the sequences' maxvalue from from 2147483647 to the columns' max (#15654) (#16403)
(cherry picked from commit 88fdc92ba34d597d9d1fa998a4ebe7ad6d405e43)
Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>
* Filter Invoice when recomputing product sots (#16469)
---------
Co-authored-by: Teo Sarca <teo.sarca@metasfresh.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Co-authored-by: Cristina Ghita <cristina.ghita@metasfresh.com>
=> metas ts/intensive care uat/merge from tag/intensive care hotfix 60 (#16512)

.github/ISSUE_TEMPLATE/documentation-requests-suggestions
This template shall serve as a note to anyone who wants to create an issue with a documentation request/suggestion and help redirect them to our documentation repository. This way we keep all documentation-related tasks in one place and avoid multiple recording of issues in several repositories.
=> Add template for doc requests (pointing to doc repo)

README.md
Adjusted Twitter follow button/badge to actually redirect to our Twitter profile instead of just opening the badge image. Embeded the code created via https://shields.io/badges/x-formerly-twitter-follow into a markdown link, as suggested here:
- https://github.com/cloudposse/build-harness/issues/88#issue-346757973
=> Update README.md - Fixed Twitter follow button

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5711890_sys_gh16816_webui.lookup.pageLength.sql, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/LookupDescriptorProviders.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/GenericSqlLookupDataSourceFetcher.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSource.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceContext.java
https://github.com/metasfresh/metasfresh/issues/16816
=> Use `webui.lookup.pageLength` sysconfig to determine the default lookup items to be fetched on typeahead

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Document_Action_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Form_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Task_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Window_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Workflow_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Document_Action_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Form_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Task_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Window_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Workflow_Access.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/interceptor/C_DocType.java, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712650_drop_AD_Document_Action_Access_ID.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712680_drop_AD_Window_Access_ID.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712690_drop_AD_Form_Access_ID.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712710_drop_AD_Process_Access_ID.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712740_drop_AD_Task_Access_ID.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712770_drop_AD_Workflow_Access_ID.sql
- drop AD_Document_Action_Access_ID
- drop AD_Window_Access_ID
- drop AD_Form_Access_ID
- drop AD_Process_Access_ID
- drop AD_Task_Access_ID
- drop AD_Workflow_Access_ID
=> Drop single primary key column on some of the AD_*Access tables

frontend/src/containers/MasterWindow.js, frontend/src/reducers/windowHandler.js
- windowHandler.js reducer: preserve layout.activeTab when updating the layout
- MasterWindow.isActiveTab: log a warning in case there is no active tab (that might be a problem/development bug)
=> windowHandler.js reducer: preserve layout.activeTab when updating the layout

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql, backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/IPrintingDAO.java, backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/AbstractPrintingDAO.java, backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingData.java, backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingDataFactory.java, backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingDataToPDFFileStorer.java, backend/de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/80-de.metas.printing/5714630_sys_AD_SysConfig_IncludePInstanceIdInFileName.sql, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/print/DocumentPrintRestController.java
Adjusted the backend to provide a new AD_SysConfig related to generating PDF filename in the printing process. The option controls whether the filename should begin with the process instance ID. Both this sysconfig and `IncludeSystemTimeMSInFileName` can be individually enabled or disabled on the AD_Org level.
=> Add option to include AD_PInstance_ID in PDF filename

frontend/src/__tests__/actions/WindowActions.test.js, frontend/src/actions/WindowActions.js, frontend/src/reducers/windowHandler.js
- windowHandler.js - INIT_DATA_SUCCESS - don't change current state
- windowHandler.js - INIT_DATA_SUCCESS - reset the layout in case we are setting data for a different windowId
=> FE Load documents correctly when going back and forward to/from profile and a given page

frontend/src/components/widget/DateTime/DatePicker.js
fixes
* https://github.com/metasfresh/metasfresh/pull/17287
=> DatePicker: fix setTimezone, convertToTimezone - don't fail when moment is ''

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCompleteCommand.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/GenerateShipmentsForSchedulesRequest.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/GenerateShipmentsRequest.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentService.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentServiceTestImpl.java
Reverts metasfresh/metasfresh#17380 because there is now a new problem. 
- It tried addressing it here: https://github.com/metasfresh/metasfresh/pull/17389 but there needs to be more QA before we can integrate that thas well
=> Revert "PickingJobCompleteCommand now returns directly after shipment-scheds are enqueued"

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Allocation.java, backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java, backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Fact.java, backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLineBuilder.java, backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/MoneySourceAndAcct.java, backend/de.metas.acct.base/src/main/java/de/metas/acct/doc/AcctDocRequiredServicesFacade.java, backend/de.metas.acct.base/src/test/java/de/metas/acct/PostDocumentNow_ManualTest.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/CurrencyPrecision.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/money/CurrencyConversionTypeId.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/money/CurrencyId.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/money/Money.java, backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/money/CurrencyIdTest.java, backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/AllocationAmountsTest.java, backend/de.metas.business/src/test/java/de/metas/money/MoneyTest.java, backend/de.metas.contracts/src/test/java/de/metas/contracts/refund/CandidateAssignmentServiceTest.java
- Doc_AllocationHdr: sync minor changes from master
- Doc_AllocationHdr: sync Money, CurrencyId and CurrencyConversionTypeId from master
- sync Money, CurrencyId and CurrencyConversionTypeId from master
- improve Money.toString()
- CurrencyPrecision.TEN
- Fact.getAcctCurrencyId()
- Doc_AllocationHdr: fix how we calculate the tax correction
- PostDocumentNow_ManualTest: helper class to post a given document (manual testing)
=> Fix Payment allocation posting for the case of foreign currency, discount/writeoff invoice tax correction

misc/services/mobile-webui/mobile-webui-frontend/src/assets/get-qty-dialog.scss, misc/services/mobile-webui/mobile-webui-frontend/src/components/DateInput.jsx, misc/services/mobile-webui/mobile-webui-frontend/src/components/QtyReasonsRadioGroup.jsx, misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx, misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js, misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
- mobile UI: manual picking: show LotNo field
- GetQuantityDialog.jsx in case the modal does not fit into page, add scrolls
- Introduce DateInput component. Use legacy text field for date by default
=> mobile UI picking: manual lot-no field; use text field for date input

backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java, backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5716360_AdjustTheValidationRuleForBOMVersionInPP_Order.sql
* Do no return SparePart as BOM Type
* Adjust the validation rule
(cherry picked from commit a17615d0b36b6c1b10b504b7bd52faa6e1981535)
backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java
=> Do no return Spare Part as BOM Type (#17238)

backend/de.metas.business/src/main/java/org/eevolution/api/IProductBOMDAO.java, backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java, backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMBL.java, backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java, backend/de.metas.business/src/test/java/org/eevolution/api/PPOrderDocBaseTypeTests.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/CreateOrderCommand.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/callout/PP_Order.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/costing/BatchProcessBOMCostCalculatorRepository.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_BOMVersions.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_Planning.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/order/PP_Product_BOM.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/model/interceptor/PP_Product_BOM.java, backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateOrderCandidateCommand.java, backend/de.metas.manufacturing/src/test/java/org/eevolution/event/PPOrderRequestedEventHandlerTests.java, backend/de.metas.material/planning/src/main/java/de/metas/material/planning/ppordercandidate/PPOrderCandidatePojoSupplier.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/picking_bom/PickingBOMService.java
* Product planning data is being ignored when manufacturing orders are generated automatically
refs https://github.com/metasfresh/metasfresh/issues/16873
(cherry picked from commit a23f5f474adf5e247bc1fb5300be2089e123abba)
backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java
backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/CreateOrderCommand.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_Planning.java …
=> Product planning data is being ignored when manufacturing orders are generated automatically (#16875)

misc/services/mobile-webui/mobile-webui-frontend/package.json
WARNING: it increases the build size from ~2Mb (2.717.779 bytes) to ~9Mb (9.127.897 bytes)
=> mobile UI: GENERATE_SOURCEMAP=true on build

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Allocation.java, backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java, backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Fact.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AcctSchema.java
- **Fact.isAccountingCurrency**
- **DocLine_Allocation.getInvoiceCurrencyId (refactored from getInvoiceC_Currency_ID)**
- **Doc_AllocationHdr.createInvoiceWriteOffFacts - use invoice currency context**
- **Doc_AllocationHdr.createInvoiceDiscountFacts - use invoice currency context**
=> Discount/Write-off allocation posting shall always use invoice's currency rate

backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_500_v_view.sql, backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5725160_sys_fix_edi_cctop_119_v_and_end_cctop_invoic_500_v.sql, backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5725160_sys_fix_edicctop_119_v_view.sql
The view on the customer-DB lacked the column "SiteName". But IDK why..the SQL 5624540_sys_gh12476_extend_and_change_invoice_edi.sql which was supposed to add it, was run. Here, i'm creating the view with everything we have on master (additional minor things), to avoid problems when this is merged towards master.
=> Fix SQL problem about exporting INVOIC

backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/storagecost/StorageCostComputingMethod.java
since the logs are created with a negative price for cost invoicing group, StorageCostComputingMethod#compute doesn't have to negate again
=> StorageCostComputingMethod: no need to negate price

backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5726080_sys_gh17795_AD_RelationType_C_Invoice_to_C_Flatrate_Term.sql
This works also if the invoice is reversed, the C_Flatrate_DataEntry is reactivated and the ICs are therefore gone.
#17995
=> Add AD_RelationType such that one can zoom from an invoice its contract

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewConfiguration.java
Fixes
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
┌──->──┐
|  de.metas.ui.web.view.ViewConfiguration defined in file [C:\workspaces\metasfresh\metasfresh\backend\de.metas.ui.web.base\target\classes\de\metas\ui\web\view\ViewConfiguration.class]
└──<-──┘
Action:
Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```
=> Fix webui server fails to start

backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5726670_sys_tweak_edi_cctop_invoic_500_v.sql
If there is no explicit bpartner-GTIN, then assume that the G from GTIN is respected and thus buyer&supplier work with the same value
=> Return our CU-GTIN as buyer-CU-GTIN by default

backend/de.metas.business/src/main/java/de/metas/quantity/Capacity.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_QtyPicked_StepDef.java, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/picking/Pick_MultipleProducts_to_LU.feature, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HUPIItemProduct.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/QtyTU.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/LUTUResult.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestination.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUTransactionAttributeBuilder.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/ASIAttributeStorage.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/IHUAttributeTransferRequest.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/IHUAttributeTransferRequestBuilder.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/impl/CopyHUAttributeTransferStrategy.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/impl/HUAttributeTransferRequest.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/impl/HUAttributeTransferRequestBuilder.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/impl/RedistributeQtyHUAttributeTransferStrategy.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/IHUTransactionBL.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/IHUTransactionCandidate.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/impl/HUTransactionBL.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/impl/HUTransactionCandidate.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHU.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilder.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/QtyTUTest.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformServiceReservationTests.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/util/HUTracerInstance.java
- **QA**
- **QA**
- **QtyTU - more helper methods**
- **IHandlingUnitsDAO.retrievePIItemMaterial**
- **LUTUResult.LU.mergeWith fix**
- **LUTUProducerDestination.setLU(I_M_HU)**
- **ShipmentScheduleWithHU: fix how we determine M_HU_PI_Item_Product_ID for aggregated TUs**
- **HUTransformService.tuToExistingLU: use aggregated TUs as much as possible**
- **LUTUProducerDestination don't override attributes of already existing TUs**
- **PickingJobPickCommand: update attributes of pre-existing LUs**
- **ShipmentLineBuilder: transfer the TUs ASI in case we are dealing with TUs from multiple lines on the same LU**
- **Pick_MultipleProducts_to_LU.feature**
=> intensive care uat pickAggregatedTUs fixes

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHU.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUFactory.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
Regression: make sure that shipments are created via the split process also for the old values of the sys config `de.metas.handlingunits.shipmentschedule.api.ShipmentScheduleWithHUService.PickAvailableHUsOnTheFly`
=> Split shipments: support for shipments with no HUs

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/EMail.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/EMailSentStatus.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/MailAuthenticator.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/mailboxes/Mailbox.java, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5730650_sys_add_AD_SysConfig_Email_Debug.sql, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestController.java
- Before this, `javax.mail`s debug feature was activated whenever the logger of `backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/EMail.java` was set to logevel `debug` resp `trace` (at 2 different places)
Now it can be switched on and off via sysconfig
- In case of a `AuthenticationFailedException` we don't just output "Invalid Username/Password", but also the actual localized exception message
- when sending a mail via `de.metas.ui.web.mail.MailRestController.java` failed, we now also output the mailconfigs that were used
=> Add sysconfig `de.metas.email.Debug` and other minor improvements

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java, backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java, backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java, backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731470_sys_gh_Delete_2_legacy_Callouts.sql, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/callout/OrderPricingSystem.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
OrderPricingSystem: the two callouts were fired before C_Order.C_BPartner_Location_Value_ID was updated and therefore always set the M_PriceList_ID for the country of the location that we are changing **away** from just now.
Instead, set the pricelist now in C_Order => no need to assume the right ordering of callouts
=> remove Callout-Code that was called too early; call it at the right time

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java, backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java, backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java, backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java, backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731470_sys_gh_Delete_2_legacy_Callouts.sql, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/callout/OrderPricingSystem.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
Remove Callout-Code that was called too early; call it at the right time
OrderPricingSystem: the two callouts were fired before C_Order.C_BPartner_Location_Value_ID was updated and therefore always set the M_PriceList_ID for the country of the location that we are changing **away** from just now.
Instead, set the pricelist now in C_Order => no need to assume the right ordering of callouts
CP of https://github.com/metasfresh/metasfresh/pull/18690
(cherry picked from commit d47634d57209e86a5083525497ca9ebe49b2af34)
backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
=> Fix bug where `C_Order.M_PriceList_ID` was set to the wrong value (CP)

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/ad_reference/AdRefListRepositoryOverJdbc.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CCache.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/serviceIssue/S_Issue_StepDef.java
AdRefListRepositoryOverJdbc:
When calling createRefListItem + getById + createRefListItem for the same ref-list value fast (in cucumber), then sometimes getById does not contain the previously created ref-list and then the 2nd createRefListItem call fails with a DBUniqueConstraintException. The only reasons i can think of are
* that cache.clear() doesn't cause the cache to be really empty **before** it returns
* that there is some other element of concurrency between reading and writing
Also make S_Issue_StepDef output in which row it failed (in case the problem persists)
=> Reduce flakyness of effortControlPurchaseInvoiceCandidate.feature by fixing AdRefListRepositoryOverJdbc

backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attributes/sscc18/impl/SSCC18AttributeValueGenerator.java
- guard agains lines with the same product: Don't fail if there are multiple inout/order-lines with the same product that were picked onto the same LU.
- never use the M_HU_ID in SSCCs, see comment in SSCC18AttributeValueGenerator.java
=> DESADV-Fixes

backend/de.metas.postfinance.base/pom.xml
issue introduced by
* https://github.com/metasfresh/metasfresh/pull/17343
=> javax.mail SMTP fix: exclude geronimo-javamail_1.4_mail because that's breaking it

backend/de-metas-salesorder/src/main/java/de/metas/salesorder/candidate/AutoProcessingOLCandService.java, backend/de-metas-salesorder/src/main/java/de/metas/salesorder/service/AutoProcessingOrderService.java, backend/de.metas.async/src/main/java/de/metas/async/AsyncBatchId.java, backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/JsonShipmentService.java, backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/InvoiceService.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java
Cherry-pick of https://github.com/metasfresh/metasfresh/pull/16997 and adapted `de.metas.invoice.InvoiceService#generateInvoicesFromInvoiceCandidateIds` to mirror the master code
=> fix RecreateInvoiceWorkpackageProcessor DB deadlock (#16997)

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheInvalidationRemoteHandler.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/util/agg/key/AbstractHeaderAggregationKeyBuilder.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/imp/RabbitMqListener.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleEffectiveBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleEffectiveBL.java, backend/de.metas.util/src/main/java/org/adempiere/util/agg/key/impl/AggregationKeyRegistry.java, backend/metasfresh-dist/base/src/main/resources/application.properties, backend/metasfresh-webui-api/src/main/resources/application.properties
* minor unrelated improvements in the shipment-schedule logic
* set prefetch-count and concurrent consumers to 1
goal: no more FUD about message ordering
(cherry picked from commit 9be34ced04c0a30ba7f48a7e27c427b21516f33d)
=> RabbitMQ prefetch size and consumer count (#19249)

backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5740590_sys_c_invoice_detail_indexes.sql
* c_invoice_candidate_headeraggregation_invoicinggroupno_ft: hotfix huge performances drop (#15859)
i.e. avoid using generate_series(1,10000000) because generate_series as used there
* is causing a huge performance issue anyways and increasing the number just exponantially drops the performances
* it's exponentially increasing the used temp space to over 260 Gb
(cherry picked from commit b8234b00015ce0d1d68f8d95738f8b2a6ada23a7)
* C_Invoice_Detail indexes
---------
=> Improve invoice performance (#19438)

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5740790_sys_C_ValidCombination_Alt_Index_OnlyActive.sql, backend/de.metas.business/src/main/java/de/metas/costing/ICurrentCostsRepository.java, backend/de.metas.business/src/main/java/de/metas/costing/impl/CurrentCostsRepository.java, backend/de.metas.business/src/main/java/de/metas/costing/interceptors/M_Product.java, backend/de.metas.business/src/main/java/de/metas/product/ProductConstants.java, backend/de.metas.business/src/main/java/de/metas/product/model/interceptor/M_Product.java
* Unique index only on active entries
* Update uom for initial costs of product when the product's uom is updated
* Sync error messages from M_Product UOM change interceptors
=> Corrections for accounting (#19484)

misc/services/mobile-webui/mobile-webui-frontend/src/assets/view-header.scss
it was rendering horizontal scroll when the view header property value string was very long
=> fix mobile UI view header layout

backend/de.metas.payment.esr/src/main/java-gen/de/metas/payment/esr/model/X_ESR_ImportLine.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/actionhandler/impl/DiscountESRActionHandler.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/actionhandler/impl/UnknownInvoiceESRActionHandler.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRImportEnqueuer.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRType.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/camt54/ESRDataImporterCamt54v02.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/camt54/ESRDataImporterCamt54v06.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/camt54/ReferenceStringHelper.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/v11/ESRTransactionLineMatcherUtil.java, backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/model/validator/ESR_Main_Validator.java, backend/de.metas.payment.esr/src/main/sql/postgresql/system/5740950_sys_AddSCORTypeForESRIMport.sql, backend/de.metas.payment.esr/src/main/sql/postgresql/system/5741590_sys_Add_Unknown_Invoice_Action.sql
* Support SCOR type when Importing esr  files
* Validate file type
* Support SCOR payments - do not create payment - just process the line with action UNKNOW Invoice
* Add Unknown_Invoice ESR Action
* Avoid NPE
* Support SCO explicitelly
* Format code
* Avoid NPE
* Improve processing ZIP files
* Fix reference value
* Set to valid and processed scor line
=> Add Support SCOR type when Importing esr  files (#19560) to new_dawn_uat

misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/numbers.test.js, misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/GetCatchWeightModal.jsx, misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx, misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepScanScreen.jsx, misc/services/mobile-webui/mobile-webui-frontend/src/utils/numberUtils.js, misc/services/mobile-webui/mobile-webui-frontend/src/utils/numbers.js
- **move toNumberOrZero to numbers.js, so we can remove numberUtils.js**
- **cleanup**
- **GetCatchWeightModal: allow entering qtys with comma or dot**
=> mobile POS: allow entering weights using comma or dot as decimal separator

backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_Mass.java
...fixing bug from hard_encoded_uat_ToAnotherOrg_Mass 
Inspired by org.adempiere.ad.process.ProcessDocuments
=> Run each org-change in its own trx

misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/attachment/BPartnerAttachmentsRouteBuilder.java, misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBPartnerAttachment.java, misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/java/de/metas/camel/externalsystems/grssignum/from_grs/attachment/BPartnerAttachmentsRouteBuilderTest.java, misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/attachment/0_JsonBPartnerAttachment_missing_ANHANGDATEI.json, misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/attachment/0_JsonBPartnerAttachment_null_ANHANGDATEI.json
refs: https://github.com/metasfresh/metasfresh/issues/19397 (cherry picked from commit 7482c9bad73a6d5e8fda9168b5b139d2face3f7d)
=> GRS-metasfresh Interface - Do not fail when attachmentFilePath is null (#19398)

backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/BankStatementCamt53Service.java, backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/IAccountStatementWrapper.java, backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/IStatementLineWrapper.java, backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/v02/BatchReportEntry2Wrapper.java, backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/v04/BatchReportEntry4Wrapper.java, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bankStatement/camt.53.001.04-Import.feature
* we import the detail lines with amount 0 and all other details that we can find in the XML file IF they are related to QRR ESR. All lines that are not related to QRR ESR should be imported with their payment amount.
* Move method hasNonQRRTransactions to proper class
* QA together with Cristina
* Add cucumber to case when Non QRR transactions exists
* Fix invoice number
* Fix invoice number
* Fix logic for skipping non-QRR transactions
* Fix bankstatement identifier
* Fix bank identifier
(cherry picked from commit abebb8f713b04059b878eaf68c387116d176b220)
=> Import NonQRR transactions as they are (#18648)

backend/de.metas.manufacturing/src/main/java/org/eevolution/model/MPPOrder.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java, backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java, backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBLTest.java
The fix is part of commit https://github.com/metasfresh/metasfresh/commit/178ede5a9c0b2f0134324408c4b2eeb6d4ac6be4
It avoids a race-condition that might happen to M_ShipmentSchedule.QtyReserved when an order is reactivated and completed again in short order
=> Port a shipmentSchedule related fix from master

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/po/POTrlRepository.java, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getBaseLanguage.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/triggers/check_is_system_language_tg.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5745700_getBaseLanguage.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746020_enable_standard_AD_Languages.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746030_enforce_standard_languages_to_be_active.sql, backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746040_ad_language_isbaselanguage_uq_index.sql
- **getBaseLanguage() db function**
- **make sure all standard ad_languages are system languages**
- **when syncing trl to base make sure we do only for base language of the system where the SQL command is running**
=> Make sure translations don't get broken when running migration scripts produced on a system with a different base language

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746180_sys_gh20034_Update_M_Warehouse_Org.sql
https://github.com/metasfresh/metasfresh/issues/20034
=> Prevent setting `M_Warehouse.AD_Org_ID` to `0` neither in the `WebUI` nor via `DB-update`

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidator.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IFactAcctListener.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IFactAcctListenersService.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/FactAcctDAO.java, backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/FactAcctListenersService.java, backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/DocTimingType.java
Avoids following issue when trying to reverse a document
```
org.adempiere.exceptions.AdempiereException: No helper can support given model: ref{M_MatchInv/8875954}
Class: class org.adempiere.util.lang.impl.TableRecordReference
Considered helpers: [org.adempiere.ad.wrapper.POInterfaceWrapperHelper1429748f, org.adempiere.ad.wrapper.GridTabInterfaceWrapperHelper4d605e40, org.adempiere.ad.wrapper.POJOInterfaceWrapperHelper6f70eba9, de.metas.ui.web.window.model.DocumentInterfaceWrapperHelper7efca151]
at org.adempiere.ad.wrapper.CompositeInterfaceWrapperHelper.getHelperThatCanHandle(CompositeInterfaceWrapperHelper.java:87)
at org.adempiere.ad.wrapper.CompositeInterfaceWrapperHelper.getPO(CompositeInterfaceWrapperHelper.java:285)
at org.adempiere.model.InterfaceWrapperHelper.getPO(InterfaceWrapp …
```
=> Comment out TIMING_AFTER_UNPOST because is not used and introduces showstopper bugs

backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HU.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HURepository.java, backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentBL.java, backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/generichumodel/HUTest.java, backend/de.metas.util/src/main/java/de/metas/util/Check.java
Another fix for extraction of Qty and LotNo from HU when creating a DESADV-Pack (#20719)
* Fix an issue that occured with aggregated HUs
* If the HU in question has a LotNo then return that, also if its children have diverging LotNos
* Only look at the children if the HU in question has no LotNo of its own
=> Another fix for extraction of Qty and LotNo from HU when creating a DESADV-Pack (#20719)

backend/metasfresh-dist/base/src/main/jasperreports/de/metas/docs/sales/alternate_inout_2_aggregation/report_details.jrxml
=> Update `Alternative delivery note 2 summary` report: take out `Merkmale`, `Anzahl` and `Packvorschrift` columns

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5758580_M_Material_Needs_Planner_V_make_it_editable_2.sql, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRowEditRestController.java, backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/json/JSONViewRow.java, frontend/src/actions/ViewActions.js, frontend/src/actions/WindowActions.js
- **ViewRowEditRestController: when patching a row, if there is an exception, return the original row and fill the new error field.**
- **FE: when patching a view, handle the new error field from the response**
- **pimp M_Material_needs_Planner_V, make it really editable only when applicable**
=> Improve error handling on webui view patching

backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java, backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java, backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_normal_UOM.feature, backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Order.java, backend/de.metas.edi/src/test/java/de/metas/edi/model/validator/C_Order_SetEdiEnabledForNewOrderTest.java, misc/dev-support/docker/infrastructure/env-files/vampire_textbook_uat.env
before, the buyer (C_Order.C_BPartner_ID) always had to be edi-enabled.
=> C_Order is now EDI-Enabled effective bill- or receipt-partner is

backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5770550_sys_gh25355_edi_cctop_119_v_view.sql
* if the warehouse from which the goods are sent has a partner and location set, then we need to use that partner as supplier
=> Take warehouse partner as supplier

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5771771_sys_gh25519_New_Sales_Order_Candidates_Window.sql
Fix for:
```SQL
psql:/opt/metasfresh/dist/sql/70-de.metas.fresh/5772210_sys_gh24946_Receipt_Schedule_Logistics_Window.sql:3784: ERROR:  duplicate key value violates unique constraint "ad_window_name"
DETAIL:  Key (ad_client_id, name)=(0, Auftragsdisposition (Legacy-EDI-Import)) already exists.
```
=> New `Sales Order Candidates` window
