metasfresh/metasfresh

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/DisplayType.java
https://github.com/metasfresh/metasfresh/issues/12724
> Column names containing "PW" should be considered passwords

- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/SEPAExportContext.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/process/C_PaySelection_SEPA_XmlExport.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/main/sql/postgresql/system/70-de.metas.payment.sepa/5631720_sys_gh12673_rename_sepaexport_param.sql
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
https://github.com/metasfresh/metasfresh/issues/12669
> #12669 rename collectiveTransfer param of SEPA Export process to referenceAsEndToEndId

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSetInstanceBL.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/impl/OrderLineReceiptScheduleProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUIHUCreationWithSerialNumberService.java
https://github.com/metasfresh/metasfresh/issues/12728
> Set an ASI to the receipt schedule even if the order didn't have one

- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/ordercheckup/impl/OrderCheckupBL.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5632330_sys_gh12737_AddOrderCheckupWithBarcode_SysConfig.sql
#12737 Allow different number of copies for ordercheckup with barcode
> #12737 Allow different number of copies for ordercheckup with barcode

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/Bank.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/BankCreateRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/BankId.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/banking/api/BankRepository.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/composite/BPartnerBankAccount.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPBankAccountDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/LocationRepository.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java
- backend/de.metas.business/src/test/java/de/metas/bpartner/composite/BPartnerCompositeTest.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/Invoice450FromCrossVersionModelTool.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/test/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/Invoice450RequestConversionServiceTest.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/test/resources/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/Invoice450RequestConversionServiceTest.snap
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/test/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/Invoice440To450RequestConversionServiceTest.java
https://github.com/metasfresh/metasfresh/issues/12185
> #12185 if XmlBank record is missing from Esr9 record (is optional), attempt to create it from DB before converting to EsrQR (where it's mandatory)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/remote/RabbitMQEventBusRemoteEndpoint.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeDAO.java
- backend/de.metas.business/src/main/java/org/eevolution/api/IProductBOMDAO.java
- backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/scheduler/AD_Scheduler_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bom/asiSupportOnProductBOM.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroupDiscount.feature
- backend/de.metas.material/event/src/main/java/de/metas/material/event/pporder/PPOrderLineCandidate.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPOrderUtil.java
refs: https://github.com/metasfresh/metasfresh/issues/12520
> Follow up on refresh manufacturing candidates on new BOM formula version

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_Location_UpdateFromPreviousAddress.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5632840_sys_gh12747_update_flatrateTerm_locations_with_new_addresses.sql
- backend/de.metas.contracts/src/test/java/de/metas/contracts/bpartner/process/C_BPartner_Location_updateFromPreviousAddressTest.java
https://github.com/metasfresh/metasfresh/issues/12747
> #12727 fix isShipToDefault/isBillToDefault logic, as well as processing order

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/multipleProductionCandidates.feature
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/model/interceptor/PP_Order_Candidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_ReOpenSelection.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5631930_sys_gh12733_PPOrderCandidateErrorMessages.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5632150_sys_gh12733_C_Order_PP_Order_Candidate_RelType.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5632160_sys_gh12733_PP_Order_Candidate_C_OrderLine_Filter.sql
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/shipmentschedule/ShipmentScheduleUpdatedHandler.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/shipmentschedule/ShipmentScheduleUpdatedEvent.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_ShipmentSchedule_PostMaterialEvent.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/material/interceptor/M_ShipmentSchedulePostMaterialEventTest.java
refs: https://github.com/metasfresh/metasfresh/issues/12733
> Solve found production dispo problems

- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5633390_sys_gh12767_Make_BOMVersions_lookup.sql
#12767 BOMVersions: BOMVersions shall be Lookup instead of list
> #12767 BOMVersions: BOMVersions shall be Lookup instead of list

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5633640_sys_gh12783_Rename_Billing_Shipping_Address.sql
https://github.com/metasfresh/metasfresh/issues/12783
> Rename billing address and shipping address

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/command/BPartnerLocationReplaceCommand.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/interceptor/C_BPartner_Location.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_Location_UpdateFromPreviousAddress.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/MainValidator.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/bpartner/process/C_BPartner_Location_updateFromPreviousAddressTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/interceptor/C_BPartner_Location.java
https://github.com/metasfresh/metasfresh/issues/12747
> #12727 rewrote to also replace address in olcands/invoice cands/flatrate terms when replacing in UI

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordService.java
* Bring back standard invoice cand aggregator
https://github.com/metasfresh/metasfresh/issues/12624
* correction in quality discount aggregator
https://github.com/metasfresh/metasfresh/issues/12624
* invoice candidate qtyToInvoiceBeforeDiscount
https://github.com/metasfresh/metasfresh/issues/12624
(cherry picked from commit 54dc906d3c63085ff59a968a0bde8695a6b587b4)
> Corrections in  invoice cand aggregator (#12625)

- misc/services/procurement-webui/procurement-webui-frontend/buildfile.groovy
https://github.com/metasfresh/me03/issues/11578
> procurement-webui-frontend builds fail with TypeScript error

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5634390_sys_gh12800_Chart_Accounts_Element.sql
https://github.com/metasfresh/metasfresh/issues/12800
> Rename Account Element to Chart of Accounts

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5633640_sys_gh12783_Rename_Billing_Shipping_Address.sql
https://github.com/metasfresh/mf15/issues/1335
> fix build failure

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/order/OrderCandidate.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/ImportOrdersRouteContext.java
https://github.com/metasfresh/metasfresh/issues/12785
> #12785 always prefer metasfreshId over bodymedUserId as bpartner identifier

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_OrgChange_History.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_OrgChange_History.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5634910_sys_gh12815_Contract_Voiding_IsCloseInvoiceCandidate.sql
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_ProcessHelper.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeCommand.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeHistoryRepository.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeRequest.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Change_Base.java
https://github.com/metasfresh/metasfresh/issues/12815
> Parameter for closing the invoice candidates when canceling a contract (proto)

- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/Group.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
https://github.com/metasfresh/metasfresh/issues/12830
> #12830 sort order lines before setting groupId, so as to prevent having a group with only compensated products.

- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/ordercheckup/IOrderCheckupBL.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/ordercheckup/impl/OrderCheckupBL.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/ordercheckup/printing/spi/impl/OrderCheckupPrintingQueueHandler.java
#12737 Allow different number of copies for ordercheckup with barcode
> #12737 Choose to differentiate based on Document type

- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/C_Doc_Outbound_Log.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/mailrecipient/impl/InOutDocOutboundLogMailRecipientProvider.java
https://github.com/metasfresh/metasfresh/issues/12448
> Doc outbound email correction

- backend/de.metas.async/src/main/java-gen/de/metas/async/model/I_RV_Async_batch_statistics.java
- backend/de.metas.async/src/main/java-gen/de/metas/async/model/X_RV_Async_batch_statistics.java
- backend/de.metas.async/src/main/sql/postgresql/ddl/view/de.metas.async/RV_Async_Batch_Statistics.sql
- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5636480_sys_gh12882_FixRV_Async_batch_statistics_view.sql
- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5636481_sys_gh12882_FixRV_Async_batch_statistics_table.sql
> #12882 Fix Async Batch window

- backend/de.metas.async/src/main/java/de/metas/async/Async_Constants.java
- backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBL.java
- backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBL.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/printing/spi/impl/DunningPrintingQueueHandler.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Process_AutomaticallyPDFPrinting.java
- backend/de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5636470_sys_gh12881_AddNewDunningProcess.sql
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/async/spi/impl/AutomaticallyDunningPrintinAsyncBatchListener.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/C_Async_Batch.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/ConcatenatePDFsCommand.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/Main.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/PrintingQueueQueryRequest.java
#12881 Implement Autoprinting PDF for Dunning
> #12881 Implement Autoprinting PDF for Dunning 

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
https://github.com/metasfresh/metasfresh/issues/12760
> #12760 prevent cucumber error when priceList_Version is reused

- frontend/src/components/header/MenuOverlayContainer.js
- frontend/src/components/header/MenuOverlayItem.js
follow-up of https://github.com/metasfresh/metasfresh/pull/12897
> FE: Menu: Enter on menu item does not work

- frontend/src/components/header/MenuOverlay.js
- frontend/src/components/header/MenuOverlayContainer.js
- frontend/src/components/header/MenuOverlayItem.js
follow-up of https://github.com/metasfresh/metasfresh/pull/12911
> FE: Menu: More fixes

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/GetOrdersRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/BPartnerUpsertRequestProducer.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/50_CamelUpsertBPartnerCompositeRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/50_CamelUpsertBPartnerCompositeRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_zeroTax/50_CamelUpsertBPartnerCompositeRequest.json
…rted
Also use the bpartner's sync-advice also for the contact, and not the location's sysnc advise
> don't attempt to upsert the contact if the bpartner is RO

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5633030_sys_gh12753_add_bbd_opened_product_window.sql
(cherry picked from commit be4bab6b3822eba934845f12ea2be34d67ff5c5e)
successor of PR https://github.com/metasfresh/metasfresh/pull/12930
> gh12753_add_bbd_opened_product_window

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
https://github.com/metasfresh/metasfresh/issues/12849
> switch base type for negative amts invoices

- misc/de-metas-common/de-metas-common-externalsystem/src/main/java/de/metas/common/externalsystem/ExternalSystemConstants.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/ShopwareClient.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/MultiQueryRequest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/Shopware6QueryRequest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/GetOrdersRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/ImportOrdersRouteContext.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/BuildOrdersContextProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/GetOrdersPageProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/query/OrderQueryHelper.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/query/PageAndLimit.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilderTestScenarios.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_RenumberLines_Tests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_Tests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_withBPartnerLookupVia_metasfreshId.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_withOrderId.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_zeroTax_Tests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/ShopwareTestConstants.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/api/model/TestPOJOs.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/api/model/query/OrderQueryHelperTests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/api/model/query/JsonExtenalSystemRequest_OrderId.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/api/model/query/JsonExtenalSystemRequest_OrderNo.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/api/model/query/JsonExtenalSystemRequest_Updated.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/api/model/query/JsonExtenalSystemRequest_UpdatedOverride.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/10_JsonOrders.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/10_JsonOrders_Page_1.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/10_JsonOrders_Page_2.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_zeroTax/10_JsonOrders.json
refs: https://github.com/metasfresh/metasfresh/issues/12928
> use pagination when retrieving orders from shopware6

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5638360_sys_gh12948_ImprovePerformance.sql
#12948 Improve performance for report.fresh_qty_statistics_report_kg_week
> #12948 Improve performance

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/mm/attributes/AttributeSetInstanceId.java
- backend/de.metas.business/src/main/java/de/metas/order/OrderFactory.java
- backend/de.metas.business/src/main/java/de/metas/order/OrderLineBuilder.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidate.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactory.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remotepurchaseitem/PurchaseItemRepository.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remotepurchaseitem/PurchaseOrderItem.java
also some minor improvements (e.g. using timezone)
> prototype that might fix the issue

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/ImportOrdersRouteContext.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/60_JsonOLCandCreateBulkRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlowRenumberLines/doNotRenumber/60_JsonOLCandCreateBulkRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlowRenumberLines/doRenumber/60_JsonOLCandCreateBulkRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/60_JsonOLCandCreateBulkRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_zeroTax/60_JsonOLCandCreateBulkRequest.json
https://github.com/metasfresh/metasfresh/issues/12951
> #12951 re-add company name to shipping location's bpartner name

- backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentBL.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRImportDAO.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportDAO.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRDataLoaderUtil.java
- backend/de.metas.payment.esr/src/main/sql/postgresql/system/5638430_sys_gh12945_ImproveImportPerformace.sql
- backend/de.metas.payment.esr/src/main/sql/postgresql/system/5638580_sys_gh12945_ESR_ImportLine_Amount_Numeric.sql
https://github.com/metasfresh/metasfresh/issues/12945
> * ESR performance improvements

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/AD_ChangeLog_Insert.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5638570_sys_gh12957_AD_ChangeLog_Insert.sql
https://github.com/metasfresh/metasfresh/issues/12957
> Create a new SQL function to insert AD_ChangeLog

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroup.feature
https://github.com/metasfresh/metasfresh/issues/12830
> #12830 add cucumber test for compensation groups

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/docOutbound/orderDocOutbound.feature
- backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/DunningService.java
https://github.com/metasfresh/metasfresh/issues/12448
> cucumber correction

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPackageBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUShipperTransportationBL.java
- backend/de.metas.shipper.gateway.commons/src/main/java/de/metas/shipper/gateway/commons/ShipperGatewayFacade.java
- backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/DerKurierDeliveryOrderRepository.java
- backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/DerKurierDraftDeliveryOrderCreator.java
- backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/misc/Converters.java
- backend/de.metas.shipper.gateway.derkurier/src/test/java/de/metas/shipper/gateway/derkurier/DerKurierTestTools.java
- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDeliveryOrderRepository.java
- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDraftDeliveryOrderCreator.java
- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
- backend/de.metas.shipper.gateway.dhl/src/test/java/de/metas/shipper/gateway/dhl/CreateShipmentRequestFromDeliveryOrderDEtoCHTest.java
- backend/de.metas.shipper.gateway.dhl/src/test/java/de/metas/shipper/gateway/dhl/DhlTestHelper.java
- backend/de.metas.shipper.gateway.go/src/main/java/de/metas/shipper/gateway/go/GODeliveryOrderConverters.java
- backend/de.metas.shipper.gateway.go/src/main/java/de/metas/shipper/gateway/go/GODraftDeliveryOrderCreator.java
- backend/de.metas.shipper.gateway.go/src/test/java/de/metas/shipper/gateway/go/Application.java
- backend/de.metas.shipper.gateway.spi/src/main/java/de/metas/shipper/gateway/spi/DraftDeliveryOrderCreator.java
- backend/de.metas.shipper.gateway.spi/src/main/java/de/metas/shipper/gateway/spi/model/DeliveryPosition.java
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/CoalesceUtil.java
https://github.com/metasfresh/metasfresh/issues/12978
> #12978 respect KG UOM precision when calculating package weight

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5639810_sys_gh13010_add_validation_rule_for_projects.sql
for https://github.com/metasfresh/metasfresh/issues/13010
added a validation rule for project to be in organisation
apply rule to the fields in pruchase invoice and purchase order
> gh13010 - show projects based on selected organisation

- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5639850_sys_gh13012_add_shopware_product_import.sql
https://github.com/metasfresh/metasfresh/issues/13012
> Automate Shopware order and product import

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5639470_gh13008_Project_Window_Modifications.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5639540_gh13008_Project_Window_Modifications.sql
https://github.com/metasfresh/metasfresh/issues/13008
> Project window modifications

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5640030_sys_gh13018_PickingConfig1_Profile_GroupByOrder.sql
https://github.com/metasfresh/metasfresh/issues/13018
> Picking Config 1 : set Profile to GroupByOrder

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ReceiptSchedule.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ReceiptScheduleRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/IReceiptScheduleProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/impl/OrderLineReceiptScheduleProducer.java
> Propagate C_Project_ID from purchase-C_Order to M_ReceiptSchedule

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInOut.java
- backend/de.metas.business/src/main/java/de/metas/order/OrderLineRepository.java
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/CoalesceUtil.java
https://github.com/metasfresh/metasfresh/issues/12978
> #12978 Attempt UOM conversion if product weight is 0.

- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorContext.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/CopyAttributesFromBOMLineGeneratorTest.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/MacAddressGeneratorTest.java
- backend/de.metas.manufacturing/src/test/java/de/metas/material/planning/pporder/impl/PPOrderBOMBLTest.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/CreatePPOrderCostsCommandTest.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/PPOrderCostsTestHelper.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/ProductLowLevelCalculatorTest.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/costing/OrderBOMCostCalculatorRepositoryTest.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/event/PPOrderRequestedEventHandlerTests.java
- backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/ForecastCreatedHandlerTest.java
- backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/pporder/PPOrderCreatedHandlerTests.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/spi/impl/QRCodeStringParser.java
- backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/QRCodePaymentTest.java
- backend/de.metas.payment.esr/src/test/java/de/metas/payment/spi/impl/QRCodeStringParserTest.java
refs: https://github.com/metasfresh/metasfresh/issues/13043
> Fix disabled unit tests

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Fresh_Account_Info_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5640950_sys_gh13054_Accounts_Information_Report.sql
https://github.com/metasfresh/metasfresh/issues/13054
> Optimize Fresh_Account_Info_Report function

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5640530_sys_gh13037_add_project_hu_window.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5640850_sys_gh13037_add_project_hu_reltype.sql
- backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU.java
- backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU.java
* #generating models
* #adding column and customizing hu window
* #adding project->hu reltype
> Window: Handling Unit (#13050)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5641130_sys_gh13059_Sales_Invoice_window_adjustments.sql
https://github.com/metasfresh/metasfresh/issues/13059
> Sales Invoice window adjustments

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
https://github.com/metasfresh/metasfresh/issues/13058
> Dropship improvement

- backend/buildfile.groovy
https://github.com/metasfresh/metasfresh/pull/12984
> creating pg-init to test the migration script fails; comment it out

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5641230_sys_gh13064_Shipment_window_adjustments.sql
https://github.com/metasfresh/metasfresh/issues/13064
> Shipment window adjustments

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5641310_sys_gh13068_Sales_Order_window_adjustments.sql
https://github.com/metasfresh/metasfresh/issues/13068
> Sales order window adjustments

- backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5641650_sys_gh13086_Adjustment in_Product_Prices_Window.sql
https://github.com/metasfresh/metasfresh/issues/13086
> gh13086_Adjustment_in_Product_Prices_Window

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5641590_sys_gh13082_add_foodadvice_to_product.sql
https://github.com/metasfresh/metasfresh/issues/13082
> Add Foodadvice Attribute to product

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
https://github.com/metasfresh/metasfresh/issues/13037
> Gh11865 window handling unit follow up

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
https://github.com/metasfresh/metasfresh/issues/13037
> #display project at all HU levels..

- backend/de.metas.business/src/main/java/de/metas/freighcost/FreightCostRepository.java
Steps to reproduce:
* make sure you have NO records with M_FreightCost.IsDefault=Y
* try to create an order line => ERROR
```
org.adempiere.exceptions.AdempiereException: ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0"
1: "\tat org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:81)"
2: "\tat org.compiere.model.ModelValidationEngine.invokeModelChangeMethod(ModelValidationEngine.java:973)"
3: "\tat org.compiere.model.ModelValidationEngine.invokeModelChangeMethods(ModelValidationEngine.java:940)"
4: "\tat org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:826)"
5: "\tat org.compiere.model.ModelValidationEngine.lambda$fireModelChange0$2(ModelValidationEngine.java:780)"
6: "\tat …
```
> ArrayIndexOutOfBoundsException when there are no default freight costs defined

- backend/de.metas.business/src/main/java/de/metas/pricing/attributebased/impl/AttributePricing.java
- backend/de.metas.business/src/main/java/de/metas/pricing/rules/PriceListVersion.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/ProductPriceQuery.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_OrderLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_AttributeSetInstance_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_AttributeSet_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_AttributeUse_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_AttributeUse_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_AttributeValue_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_AttributeValue_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_Attribute_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/attribute/M_Attribute_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_PI_Version_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bom/asiSupportOnProductBOM.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/pricing/productPriceNotAttributeDependantS0144_1.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/pricing/productPriceS0144_1.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/pricing/productPriceS0144_2.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/pricing/scalePrices.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pricing/spi/impl/HUPricing.java
* refs: https://github.com/metasfresh/metasfresh/issues/13062
pricing issue cucumber coverage
> Pricing issue cucumber (#13109)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/letter/BoilerPlateId.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642450_sys_gh13114_AD_User_Default_Values.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/letter/LetterRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/login/LoginRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputCallout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/InternalUserSessionData.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/UserSession.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/UserSessionRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/json/JSONUserSession.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/json/JSONUserSessionChangesEvent.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONLookupValuesList.java
- frontend/src/actions/LetterActions.js
- frontend/src/components/letter/NewLetter.js
https://github.com/metasfresh/metasfresh/issues/13114
> Provide default flatrate terms and boiler plate in the user Profile

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterList.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuilder.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_ReverseReceipt.java
https://github.com/metasfresh/metasfresh/issues/13112
> Master merge iron plant uat fix hu zoomacross

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/letter/BoilerPlateId.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642450_sys_gh13114_AD_User_Default_Values.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/letter/LetterRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/login/LoginRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputCallout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/InternalUserSessionData.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/UserSession.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/UserSessionRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/json/JSONUserSession.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/json/JSONUserSessionChangesEvent.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONLookupValuesList.java
https://github.com/metasfresh/metasfresh/issues/13114
> Master merge hard encoded uat defaults

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642620_sys_gh13119_receipt_window_adjustment.sql
https://github.com/metasfresh/metasfresh/issues/13119
> Adjust material receipt window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5642780_sys_gh13127_PLV_Order_By_Newest.sql
https://github.com/metasfresh/metasfresh/issues/13127
> PLV - Order by newest PLV desc

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5642860_sys_gh13132_add_fr_CH_as_Sys_language_and_Trls.sql
https://github.com/metasfresh/metasfresh/issues/13132
> #13132 add fr ch as system language & add missing trls

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642620_sys_gh13119_receipt_window_adjustment.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5642860_sys_gh13132_add_fr_CH_as_Sys_language_and_Trls.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5641340_sys_gh13071_Purchase_Order_window_adjustments.sql
https://github.com/metasfresh/me03/issues/11976
> Master merge inner silence uat add fr ch trls

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_TabularView.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_details.jrxml
- all fonts in Arial
- aligned page number
- checked that text isn't cut off (EN/DE)
https://github.com/metasfresh/me04/issues/402
> changes in the openitems_report

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/RelatedDocumentsFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/references/service/WebuiDocumentReferencesService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/SqlViewFactory.java
merge fix from iron plant
https://github.com/metasfresh/metasfresh/issues/13112
> Gh13112 master merge iron plant fix

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5641590_sys_gh13082_add_foodadvice_to_product.sql
https://github.com/metasfresh/metasfresh/issues/13082
> Foodadvice gridview

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642920_sys_gh13138_show_only_projects_in_line_matching_selected_org.sql
- added for projects to be available for selection, only if they are a part of the selected organisation
for https://github.com/metasfresh/metasfresh/issues/13138
> Add Filtering by Organisation for Projects

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5643160_sys_gh13145_Food_Advice_Table.sql
https://github.com/metasfresh/metasfresh/issues/13145
> Create a new table Food Advice

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Candidate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_Planning.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Candidate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_Planning.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateOrderCandidateCommand.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643210_sys_gh13158_Adjust_Manufacturing_candidate.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643230_sys_gh13158_Adjust_Manufacturing_candidate.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643670_sys_gh13158_Adjust_Manufacturing_candidate.sql
https://github.com/metasfresh/metasfresh/issues/13158
> Gh13158 adjust manufacturing candidate

- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v1/ordercandidates/impl/OrderCandidatesRestControllerImpl_createOrderLineCandidates_Test.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroupDiscount.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandWithUOMForTUsCapacityProvider.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/IOLCandWithUOMForTUsCapacityProvider.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/DefaultOLCandValidator.java
> fix: set QtyItemCapacityInternal only if computed capacity is eligible

- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643780_sys_gh13158_Adjust_Manufacturing_candidate.sql
https://github.com/metasfresh/metasfresh/issues/13158
> Adjust Window Manufacturing candidate

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643780_sys_gh13158_Adjust_Manufacturing_candidate.sql
https://github.com/metasfresh/me03/issues/12157
> Master merge science vessel followup 1

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.kpi/5642335_sys_gh13107_Update_TRLs.sql
https://github.com/metasfresh/metasfresh/issues/13107
> #gh13107 updated KPI labels to Grand Total, instead of Net Total

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644240_sys_gh13183_rename_element_sektion_to_organisation.sql
https://github.com/metasfresh/metasfresh/issues/13183
> gh13183 Rename Sektion to Organisation

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644240_sys_gh13183_rename_element_sektion_to_organisation.sql
https://github.com/metasfresh/metasfresh/issues/13183
> Master merge hostile tractor uat rename sektion organisation

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/receipt/CustomerReturnRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/ShipmentService.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java
- backend/de.metas.business/src/main/java/de/metas/customs/process/ShipmentLinesForCustomsInvoiceRepo.java
- backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceLineBL.java
- backend/de.metas.business/src/main/java/de/metas/quantity/Quantitys.java
- backend/de.metas.business/src/main/java/de/metas/shipment/service/ShipmentDeclarationCreator.java
- backend/de.metas.cucumber/dev-support/10_reset_db_to_seed_dump.sh
- backend/de.metas.cucumber/dev-support/20_convert_db_to_template.sh
- backend/de.metas.cucumber/dev-support/30_reset_db_to_template.sh
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/InfrastructureSupport.java
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5572960_sys_gh10231_tweak_for_swing_client.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/material/interceptor/transactionevent/TransactionEventFactoryForInOutLine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredQtyItem.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/resources/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.snap
- backend/de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaProductRepository.java
https://github.com/metasfresh/metasfresh/issues/13179
> Scary plum merge hotfix to uat

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/receipt/CustomerReturnRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/ShipmentService.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java
- backend/de.metas.business/src/main/java/de/metas/customs/process/ShipmentLinesForCustomsInvoiceRepo.java
- backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceLineBL.java
- backend/de.metas.business/src/main/java/de/metas/quantity/Quantitys.java
- backend/de.metas.business/src/main/java/de/metas/shipment/service/ShipmentDeclarationCreator.java
- backend/de.metas.cucumber/dev-support/10_reset_db_to_seed_dump.sh
- backend/de.metas.cucumber/dev-support/20_convert_db_to_template.sh
- backend/de.metas.cucumber/dev-support/30_reset_db_to_template.sh
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/InfrastructureSupport.java
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5572960_sys_gh10231_tweak_for_swing_client.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/material/interceptor/transactionevent/TransactionEventFactoryForInOutLine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredQtyItem.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/resources/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.snap
- backend/de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaProductRepository.java
https://github.com/metasfresh/metasfresh/issues/13179
> Scary plum uat merge hotfix

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/MailService.java
- backend/de.metas.util/src/main/java/org/adempiere/util/email/EmailValidator.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/imp/process/ImportInvoiceResponseService.java
also improve logging if no AD_MailConfig was found and metasfresh falls back to the AD_Client's config
> Fix bug when looking up mail-config where docBaseAndSubType was ignored

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644620_sys_gh12825_flag_m_tour_id_as_claculated.sql
https://github.com/metasfresh/sv178/issues/89
> Master merge science vessel uat branch

- backend/de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/ContactPersonRepository.java
https://github.com/metasfresh/metasfresh/issues/13206
> #gh13206 add ContactPersonRepository#isEmailInUse

- backend/de.metas.business/src/main/java/de/metas/inout/IInOutBL.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/model/validator/M_InOut.java
#13215 Description and documentnote are not copied from doctype into shipment
> #13215 Copy descriptions from doc type for inout

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5645280_sys_gh13138_Show_only_Projects_Organisation.sql
https://github.com/metasfresh/metasfresh/issues/13138
> Master merge pot hole uat filter project based on organisation

- misc/services/camel/de-metas-camel-externalsystems/ebay/de-metas-camel-ebay-camelroutes/README.md
- misc/services/camel/de-metas-camel-externalsystems/ebay/de-metas-camel-ebay-camelroutes/src/main/java/de/metas/camel/externalsystems/ebay/processor/order/CreateOrderLineCandidateUpsertReqForEbayOrderProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/ebay/de-metas-camel-ebay-camelroutes/src/test/java/de/metas/camel/externalsystems/ebay/EbayApiTest.java
add documentation to execute tests.
update readme.md
> Ebay doc updates gh #10738

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5645500_sys_gh13228_deactivate_M_AttributeSetInstance_ID.sql
deactivates the process parameter_M_AttributeSetInstance_ID completely
for #13228
> Disable deactivate_M_AttributeSetInstance_ID all together

- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config_Shopware6.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Shopware6.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/export/stock/ExportStockToShopwareExternalSystem.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/shopware6/ExternalSystemShopware6Config.java
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5645710_sys_gh13238_add_Perecentage_to_ExternalSystem_Config_Shopware6_.sql
refs https://github.com/metasfresh/metasfresh/issues/13238
> Showpare - percentage that is deducated from the available-to-sales qty

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/ShopwareClient.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/MultiQueryRequest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/QueryHelper.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/Shopware6QueryRequest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/customer/GetCustomersRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/customer/ImportCustomersRouteContext.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/customer/processor/GetCustomersPageProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/BuildOrdersContextProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/GetOrdersPageProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/query/OrderQueryHelper.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_Tests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_zeroTax_Tests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/api/model/TestPOJOs.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/api/model/query/OrderQueryHelperTests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/customer/GetCustomersRouteBuilderTest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/60_JsonOLCandCreateBulkRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/60_JsonOLCandCreateBulkRequest.json
https://github.com/metasfresh/metasfresh/issues/13237
> Master integration gh13237

- backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMBL.java
https://github.com/metasfresh/metasfresh/issues/13248
> fix bug where the wrong ID was added

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Project.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Project_WO_ObjectUnderTest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Project_WO_Resource.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Project_WO_Step.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Project.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Project_WO_ObjectUnderTest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Project_WO_Resource.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Project_WO_Step.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5646470_sys_gh13276_C_Project_new_columns.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5646480_sys_gh13276_C_Project_WO_ObjectUnderTest.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5646490_sys_gh13276_C_Project_WO_Step_new_columns.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5646520_sys_gh13276_C_Project_WO_Resource.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5646580_sys_gh13276_C_Project_new_columns.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5646630_sys_gh13276_C_Project_WO_ObjectUnderTest.sql
https://github.com/metasfresh/metasfresh/issues/13276
> Iron plant uat projectdatamodel

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/get_sysconfig_value_forOrg.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646680_sys_gh13277_SYS_CONFIG_C_Invoice_Send_To_Current_BillTo_Address_And_User .sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646690_sys_gh13277_IsUpdateLocationAndContactForInvoice_Parameter_Default.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646870_sys_gh13277_SQLFunction_get_sysconfig_value_forOrg.sql
https://github.com/metasfresh/metasfresh/issues/13277
> Hard encoded invoice address

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5646990_sys_gh13227_trls_fix.sql
https://github.com/metasfresh/metasfresh/issues/13227
> #gh13227 prevent shipping orders with in-review picking jobs

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/get_sysconfig_value_forOrg.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646680_sys_gh13277_SYS_CONFIG_C_Invoice_Send_To_Current_BillTo_Address_And_User .sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646690_sys_gh13277_IsUpdateLocationAndContactForInvoice_Parameter_Default.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646870_sys_gh13277_SQLFunction_get_sysconfig_value_forOrg.sql
https://github.com/metasfresh/metasfresh/issues/13277
> Master merge hard encoded uat invoice address update

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectJsonToInternalConverter.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectRestService.java
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/project/workorder/WorkOrderProjectRestServiceTest.snap
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WOProjectResource.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WOProjectStep.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WorkOrderProjectResourceRepository.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WorkOrderProjectStepRepository.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/interceptor/C_Project_WO_Step.java
- backend/de.metas.business/src/test/java/de/metas/project/workorder/data/WorkOrderProjectRepositoryTest.java
- frontend/src/pages/calendar/hooks/useSimulations.js
refs https://github.com/metasfresh/metasfresh/issues/13276
> Fixes (#13278)

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/AD_User_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/AD_User_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_Location_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_Location_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Location_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Location_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_HU_PackingMaterial_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/data/DataExportAudit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalreference/S_ExternalReference_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalreference/S_ExternalReference_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/inventory/M_Inventory_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/C_UOM_Conversion_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/pickingterminal/Picking_Terminal_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrder.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroupDiscount.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceRules.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/procurementWebUI.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/upsertProduct.feature
OLCand => Order Extend test-coverage
> OLCand => Order Extend test-coverage cover bill-, dropship- and handover-partners

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/MD_Stock_Update_From_M_HUs_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/ExternalSystem_Config_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/MetasfreshToExternalSystemRabbitMQ_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/availableForSales.feature
- backend/de.metas.externalreference/src/main/java/de/metas/externalreference/ExternalReferenceRepository.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config_Shopware6.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Shopware6.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/export/availableforsales/ExportAvailableForSalesToShopwareExternalSystem.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/shopware6/ExternalSystemShopware6Config.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/shopware6/interceptor/ExternalSystem_Config_Shopware6.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/shopware6/interceptor/MD_Available_For_Sales.java
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5647280_sys_gh13261_migrateExternalSystemConfigShopware6_OldColumnsToNewOnes.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5647290_sys_gh13261_AvailableForSales_FixTerminology.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5647300_sys_gh13261_migrateExternalSystemConfigShopware6_OldColumnsToNewOnes.sql
- backend/de.metas.externalsystem/src/test/java/de/metas/externalsystem/ExternalSystemConfigRepoTest.java
- backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/ExternalSystemConfigRepoTest.snap
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUShipmentAssignmentBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentAssignmentBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOut.java
- backend/de.metas.material/cockpit/src/main/java/de/metas/material/cockpit/stock/HUStockService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/adapter/AvailableForSaleAdapter.java
- misc/de-metas-common/de-metas-common-externalsystem/src/main/java/de/metas/common/externalsystem/ExternalSystemConstants.java
- misc/de-metas-common/de-metas-common-externalsystem/src/main/java/de/metas/common/externalsystem/JsonAvailableAvailableForSales.java
- misc/de-metas-common/de-metas-common-externalsystem/src/main/java/de/metas/common/externalsystem/JsonAvailableForSales.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/README.md
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/stock/ExportStockRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/stock/ExportStockRouteContext.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/stock/10_JsonExternalSystemRequest.json
refs https://github.com/metasfresh/metasfresh/issues/13261
> AvailableForSales to Shopware - Fix terminology

- backend/de.metas.business/src/main/java/de/metas/pricing/attributebased/impl/AttributePricing.java
- backend/de.metas.business/src/main/java/de/metas/pricing/rules/PriceListVersion.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pricing/spi/impl/HUPricing.java
https://github.com/metasfresh/metasfresh/issues/13314
> #gh13314 prevent lookup of product price from base Pricelist

- backend/de.metas.business/src/main/sql/postgresql/ddl/functions/SetBaseLanguage.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647430_sys_gh13302_add_process_change_base_language.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647510_sys_gh13302_add_process_change_base_language.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647580_sys_gh13302_add_process_change_base_language.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647680_sys_gh13302_add_process_change_base_language.sql
https://github.com/metasfresh/metasfresh/issues/13302
> Merge adorable badger uat into master

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Prefinancing_Settings.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5647960_sys_gh13308_C_Prefinancing_Settings_Correction.sql
https://github.com/metasfresh/metasfresh/issues/13308
> C_Prefinancing_Settings corrections

- backend/de.metas.payment.revolut/src/main/java/de/metas/payment/revolut/PaySelectionService.java
- backend/de.metas.payment.revolut/src/test/java/de/metas/payment/revolut/PaySelectionServiceTest.java
https://github.com/metasfresh/metasfresh/issues/13280
> #13280 use correct SwiftCode from C_Bank, instead of routingNumber

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5647960_sys_gh13308_C_Prefinancing_Settings_Correction.sql
https://github.com/metasfresh/metasfresh/issues/13308
> Master merge inner silence uat 2

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648210_sys_gh13337_Adjustment_Payment_and_BankStatement_Windows.sql
https://github.com/metasfresh/sp80/issues/1882
> #13337 Adjustment Payment/Bank Statement Window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5648180_sys_gh13334_Storage_Maintenance.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5648190_sys_gh13334_Storage_Maintenance.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5648200_sys_gh13334_Storage_Maintenance.sql
https://github.com/metasfresh/metasfresh/issues/13334
> Storage location maintenance

- backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentDAO.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/impl/CreateSEPAExportFromPaySelectionCommand.java
https://github.com/metasfresh/metasfresh/issues/13338
> Use QR IBAN in SEPA export

- backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentDAO.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/impl/CreateSEPAExportFromPaySelectionCommand.java
https://github.com/metasfresh/metasfresh/issues/13338
> Support QR IBAN in SEPA export

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648330_sys_gh13302_add_process_change_base_language.sql
https://github.com/metasfresh/metasfresh/issues/13302
> gh13302 restrict process to system  only

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_CostRevaluation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_CostRevaluationLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_DocType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_CostRevaluation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_CostRevaluationLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/ui/spi/ITabCallout.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/ui/spi/TabCalloutAdapter.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5647970_sys_gh13323_Prefinancing_FlatrateConditions.sql
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/CostRevaluationDocumentHandler.java
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/CostRevaluationDocumentHandlerProvider.java
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/CostRevaluationRepository.java
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/callout/M_CostRevaluation.java
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/impl/CostRevaluationId.java
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/impl/CostRevaluationLineId.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647750_sys_gh13319_final_product_price.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647770_sys_gh13319_final_product_price.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647840_sys_gh13319_final_product_price.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647850_sys_gh13319_final_product_price.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648110_sys_gh13319_final_product_price.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648300_sys_gh13319_final_product_price.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648340_sys_gh13319_final_product_price.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/util/lang/All_RepoIdAware_Classes_Test.java
https://github.com/metasfresh/metasfresh/issues/13339
> Master merge inner silence uat gh13339

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648460_sys_gh13337_Adjustment_Payment_and_BankStatement_Windows.sql
https://github.com/metasfresh/metasfresh/issues/13337
> gh13337 fixes business partner bank account filters

- frontend/src/__tests__/components/widget/List/RawList.test.js
- frontend/src/__tests__/pages/calendar/Calendar.test.js
- frontend/src/components/widget/List/RawList.js
- frontend/src/components/widget/List/SimpleList.js
- frontend/src/components/widget/SelectionDropdown.js
Test cases:
* test calendar page, simulation dropdown
Regression:
* sales order: test payment rule list
* sales order: test payment term
* sales order: pricing system
* bpartner: attributes
> hotfix List is not closing when clicking outside

- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
https://github.com/metasfresh/metasfresh/issues/13338
> Add QR Reference to SEPA export

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_PartialPayment_Overview.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_PartialPayment_Overview_Line.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_PartialPayment_Overview.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_PartialPayment_Overview_Line.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5648420_sys_gh13375_Prefinancing_Overview.sql
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/TypeConditions.java
https://github.com/metasfresh/metasfresh/issues/13375
> Inner silence partial invoice overview

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
https://github.com/metasfresh/metasfresh/issues/13380
> gh13380  skip the  copy of windows translations , because  the name_ad_language unique index on window_trl will be broken

- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/main/sql/postgresql/system/70-de.metas.payment.sepa/5648860_sys_gh13384_SEPA_Export_Err_Invalid_Reference.sql
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
https://github.com/metasfresh/metasfresh/issues/13384
> Tests and Error messages for QR IBAN Sepa Export

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5649040_sys_gh13388_ShowFlagsSalesContact_and_PurchaseContact.sql
#13388 Show Flags Sales contact and Purchase contact in Organisation Stammdaten window
>   #13388 Show Flags Sales contact and Purchase contact in Organisation Stammdaten window

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/Msg.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/TranslatableStringBuilder.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/i18n/MsgTest.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5649420_sys_msg_CannotIssueLessMoreThan.sql
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/OrderBOMLineQuantities.java
Follow-up of https://github.com/metasfresh/metasfresh/pull/13157
> manufacturing: Enforce QtyToIssue Tolerance% (part 2)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Incoterms.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Incoterms.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5648520_sys_gh13368_ispartialpayment_invoice_candidate.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5649100_gh13368_rename_to_IsInterimInvoice.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
integrating the PRs into the master branch:
IsInterimInvoice
> Inner silence uat

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5649600_sys_gh17_akontoflag_readonly.sql
Make akonto flag readonly
https://github.com/metasfresh/me03/issues/12608
> Make akonto flag readonly

- backend/de.metas.business/src/main/java/de/metas/quantity/StockQtyAndUOMQty.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_Attribute_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/C_UOM_Conversion_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/C_UOM_Conversion_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/receiptschedule/M_ReceiptSchedule_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateQtyToInvoiceOverride.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidate.java
refs: https://github.com/metasfresh/metasfresh/issues/13316
> Extend invoice-candidate test-coverage to IC QtyToInvoiceOverride

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5650030_sys_gh13413_display_project_field_in_various_windows.sql
https://github.com/metasfresh/metasfresh/issues/13413
> gh13413 display project field in various windows

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/CompositeDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/DocumentLUTUConfigurationManager.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/customer/CustomerReturnLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderBOMLineDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/ReceiptScheduleDocumentLUTUConfigurationHandler.java
https://github.com/metasfresh/metasfresh/issues/13415
> lutu config corrections

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/CompositeDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/DocumentLUTUConfigurationManager.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/customer/CustomerReturnLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderBOMLineDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/ReceiptScheduleDocumentLUTUConfigurationHandler.java
https://github.com/metasfresh/metasfresh/issues/13415
> Master merge intensive care hotfix

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/model/interceptor/C_BPartner.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650270_sys_gh13419_Auto_Update_BPartnerHierarchy.sql
https://github.com/metasfresh/metasfresh/issues/13419
> Auto update the permissions hierarchy for a new BP

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/model/interceptor/C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/BPartnerSalesRepTest.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/AD_User.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650270_sys_gh13419_Auto_Update_BPartnerHierarchy.sql
https://github.com/metasfresh/metasfresh/issues/13419
> Auto update b partner hierarchy

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_InvoiceLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Payment.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_Fact_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_GL_JournalLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InOut.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InOutLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_SectionCode.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_InvoiceLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Payment.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_Fact_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_GL_JournalLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InOut.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InOutLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_SectionCode.java
- backend/de.metas.business/src/main/java/de/metas/freighcost/interceptor/C_Order.java
- backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/shipment/model/interceptor/M_InOut.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5649980_sys_gh13412_SectionCode_Table.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650040_sys_gh13412_SectionCode_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650080_sys_gh13412_SectionCode_Documents.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650160_sys_gh13412_SectionCode_Fact_Acct.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650170_sys_gh13412_Transactions_View.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650180_sys_gh13412_SectionCode_Transactions_View.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650400_sys_gh13412_SectionCode_Documents_Line.sql
https://github.com/metasfresh/metasfresh/issues/13412
> New Section Code window

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Project.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_ProjectType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Project.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_ProjectType.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5650390_sys_gh13424_Inherit_C_BParnter_ID_From_Project_To_Request.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5650490_sys_gh13424_R_StatusCategory_ID_In_Project_And_ProjectType.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5650600_mig_gh13424_R_StatusCategory_ID_In_Project_And_ProjectType_Migration.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5650640_sys_gh13424_R_StatusCategory_ID_In_Project_And_ProjectType_Mandatory.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5650650_sys_gh13424_C_Project_Window_And_Filters_Improvements.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5650700_sys_gh13424_C_Project_R_StatusCategory_Rules.sql
- backend/de.metas.business/src/main/java/de/metas/project/ProjectType.java
- backend/de.metas.business/src/main/java/de/metas/project/ProjectTypeRepository.java
- backend/de.metas.business/src/main/java/de/metas/project/RequestStatusCategoryId.java
- backend/de.metas.business/src/main/java/de/metas/project/service/ProjectService.java
https://github.com/metasfresh/metasfresh/issues/13424
> Adorable badger uat requests and projects

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5633190_sys_Increase_Product_Name_TRL_Length.sql
Make sure the product name trl is long enough so it doesn't cause problems on systems where it was already longer than 80
> Increase Product Name TRL

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5651820_sys_gh13469_Add_Section_Code_Product.sql
https://github.com/metasfresh/metasfresh/issues/13469
> adorable_badger_uat to master

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/inventory/M_Inventory_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/product/M_Product_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_QtyPicked_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_QtyPicked_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/creditLimit.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/delivery/deliveryRules.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/impl/HUPickingSlotBLs/RetrieveAvailableHUsToPick.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageEngine.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUPickingSlotBL_RetrieveAvailableHUsToPickTests.java
- backend/de.metas.storage/src/main/java/de/metas/storage/IStorageEngine.java
> Delivery Rules & Delivery Fifo

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Project.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Project.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5652370_sys_gh13458_C_Project_ExternalId.sql
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/budget/BudgetProjectJsonConverter.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/budget/BudgetProjectRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderMapper.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectObjectUnderTestRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectStepRestService.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectRestServiceTest.java
- backend/de.metas.business/src/main/java/de/metas/project/budget/BudgetProject.java
- backend/de.metas.business/src/main/java/de/metas/project/budget/BudgetProjectQuery.java
- backend/de.metas.business/src/main/java/de/metas/project/budget/BudgetProjectRepository.java
- backend/de.metas.business/src/main/java/de/metas/project/budget/CreateBudgetProjectRequest.java
- backend/de.metas.business/src/main/java/de/metas/project/budget/interceptor/C_Project.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/CreateWOProjectRequest.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WOProject.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WOProjectQuery.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/data/WorkOrderProjectRepository.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5652880_sys_gh13458_externalId_field_project_window.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/project/C_Project_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/budgetProjectAPI.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workOrderProjectAPI.feature
- backend/de.metas.util.web/src/main/java/de/metas/rest_api/utils/IdentifierString.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/project/budget/JsonBudgetProjectResponse.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/project/budget/JsonBudgetProjectUpsertRequest.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/project/workorder/JsonWorkOrderProjectQuery.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/project/workorder/JsonWorkOrderProjectResponse.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/project/workorder/JsonWorkOrderProjectUpsertRequest.java
so far, C_Project_Reference_Ext was used for the job, but it's not generally unique.
iron_plant_uat_c_project_ExternalId
https://github.com/metasfresh/metasfresh/issues/13458
> introduce C_Project.ExternalId

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5652960_sys_CostDetail_window_pimp.sql
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/interceptor/M_CostRevaluation.java
Follow-up of https://github.com/metasfresh/metasfresh/pull/13493
> Cost Revaluation Accounting (part 2)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5653110_sys_cost_revaluation_trls.sql
- backend/de.metas.business/src/main/java/de/metas/costing/methods/CostingMethodHandlerTemplate.java
- backend/de.metas.business/src/main/java/de/metas/costrevaluation/interceptor/M_CostRevaluation.java
follow-up of https://github.com/metasfresh/metasfresh/pull/13495
> Cost Revaluation translations

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5652970_sys_gh13461_Forwarder_Table.sql
https://github.com/metasfresh/metasfresh/issues/13461
> Add BPartner Forwarder table

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/zoom_into/CustomizedWindowInfoMapRepository.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/ADWindowService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/IADWindowDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_ZoomToQuotations.java
Follow-up of https://github.com/metasfresh/metasfresh/pull/13511
> Introduce ADWindowService.getEffectiveWindowIdByInternalName

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5650740_sys_gh13435_Add_NewDocType_AndJasperDocument.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653220_sys_gh13435_add_II_DocSubType_for_Akonto.sql
https://github.com/metasfresh/metasfresh/issues/13435
> doctype ID correction 

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsCommand.java
When receiving to new LU make sure that the LU has:
* HUStatus=A
* HUPlanningReceiptOwnerPM=N (aka isOwnPackingMaterials=false)
> HOTFIX mobile mfg receipt: wrong LU created (HUStatus=P, isOwnPackingMaterials=Y)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653720_sys_gh13519_C_Project_Children_Relation_Type.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653790_sys_gh13519_User_Project_Relation_Type.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653820_sys_gh13519_BPartner_User_Project_Relation_Type.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653870_sys_gh13519_WO_Project_Children_Relation_Type.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653880_sys_gh13519_BUD_Project_Children_Relation_Type.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653890_sys_gh13519_BUD_To_WO_Project_Children_Relation_Type.sql
https://github.com/metasfresh/metasfresh/issues/13519
> Iron plant uat to master gh13519

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5653990_sys_gh13524_Frame_Order_SO_DT.sql
https://github.com/metasfresh/metasfresh/issues/13524
> Adorable badger uat master gh13524

- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/common/JsonMetasfreshId.java
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/Check.java
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/NumberUtils.java
- misc/de-metas-common/de-metas-common-util/src/test/java/de/metas/common/util/NumberUtilsTest.java
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
PR that broke it:
* https://github.com/metasfresh/metasfresh/pull/12668
> HOTFIX mobile HU Manager - set clearance was broken

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5653860_sys_gh13480_Duplicate_TRL_Corrections_From_AD_Element.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5654470_sys_gh13480_avoid_window_duplicates_on_master.sql
https://github.com/metasfresh/metasfresh/issues/13480
> Master avoid duplicate window names

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5654680_gh13555_Fix_Project_Zoom_Across.sql
https://github.com/metasfresh/metasfresh/issues/13555
> Fix Zoom Across where Project reference is pointing to itself

- backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/iinvoicecandidate/I_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/dataImport/importInvoiceCandidate.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredQtyItem.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/ShipmentData.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/resources/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateRecordServiceTest.snap
QtyToInvoice properly set on C_Invoice_Candidate
> BUG: I_C_InvoiceCandidate.QtyDelivered wrongly computed for manual invoice candidates

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MMatchPO.java
- backend/de.metas.business/src/main/java/de/metas/costing/CostDetail.java
- backend/de.metas.business/src/main/java/de/metas/costing/ICostDetailRepository.java
- backend/de.metas.business/src/main/java/de/metas/costing/ICostDetailService.java
- backend/de.metas.business/src/main/java/de/metas/costing/impl/CostDetailRepository.java
- backend/de.metas.business/src/main/java/de/metas/costing/impl/CostDetailService.java
- backend/de.metas.business/src/main/java/de/metas/costing/impl/CostingService.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/CostingMethodHandlerTemplate.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/CostingMethodHandlerUtils.java
> Misc fixes around cost revaluation

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5654910_sys_gh13561_ApprovalForInvoicing_Description.sql
https://github.com/metasfresh/metasfresh/issues/13561
> Description to Approval For Invoicing field and process 

- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/org/adempiere/server/rpl/trx/process/C_OLCand_Update_IsImportedWithIssues_Base.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/callout/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/costing/BatchProcessBOMCostCalculatorRepository.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_Planning.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/IProductPlanningDAO.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/event/SupplyRequiredHandler.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/impl/ProductPlanningDAO.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPOrderUtil.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/picking_bom/PickingBOMService.java
https://github.com/metasfresh/metasfresh/issues/13563
> Manufacturing Order -> Problem when having a PP_Product_Planning that has a BOM but no product

- backend/de.metas.business/src/main/java/de/metas/costing/impl/ProductCostingBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contacts/invoice/interim/invoicecandidatehandler/FlatrateTermInterimInvoice_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
https://github.com/metasfresh/metasfresh/issues/13423
> #13423 fix for material receipts with quality issues

- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/org/adempiere/server/rpl/trx/process/C_OLCand_Update_IsImportedWithIssues_Base.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/callout/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/costing/BatchProcessBOMCostCalculatorRepository.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_Planning.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/IProductPlanningDAO.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/event/SupplyRequiredHandler.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/impl/ProductPlanningDAO.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPOrderUtil.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/picking_bom/PickingBOMService.java
https://github.com/metasfresh/metasfresh/issues/13563
> Merging `science_vessel_uat` to `master`

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_AttributeUse.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_AttributeUse.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5655320_sys_gh13571_M_AttributeUse_MandatoryOnManufacturing.sql
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeSourceDocument.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributesBL.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/IAttributeStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/AbstractAttributeStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/NullAttributeStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/HUPPOrderIssueReceiptCandidatesProcessor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributes.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributesProvider.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataLoader.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/receiptSchedule/HUsToReceiveViewFactory.java
https://github.com/metasfresh/metasfresh/issues/13571
> Mandatory on Manufacturing 

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/dataImport/C_DataImport_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/org/AD_Org_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/dataImport/importInvoiceCandidate.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_I_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_I_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/CInvoiceCandidateImportTableSqlUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/ImportInvoiceCandidatesService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5652120_sys_gh13483_AD_ImpFormat_I_Invoice_Candidate.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5654930_sys_gh13568_I_Invoice_Candidate_trls.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5655230_sys_gh13568_I_Invoice_Candidate_Default_OrgCode_column.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5655390_sys_gh13568_I_Invoice_Candidate_Default_OrgCode_field.sql
Follow - import invoice candidates
> Follow - Generic importer for invoice candidates

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/document/counterDoc/C_Order_CounterDocHandler.java
https://github.com/metasfresh/metasfresh/issues/13578
> #13578 copy dropship information if available

- backend/de.metas.business/src/main/java-legacy/org/compiere/process/InvoicePayScheduleId.java
- backend/de.metas.dunning/src/main/java-gen/de/metas/dunning/model/I_C_Dunning_Candidate.java
- backend/de.metas.dunning/src/main/java-gen/de/metas/dunning/model/X_C_Dunning_Candidate.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningBL.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningCandidateProducer.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningContext.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningDAO.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DefaultDunningCandidateProducer.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningBL.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningContext.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningDAO.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/RecomputeDunningCandidatesQuery.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/api/impl/InvoiceSourceBL.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/api/impl/InvoiceSourceDAO.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/model/validator/C_Invoice.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Create.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Process.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Process_AutomaticallyPDFPrinting.java
- backend/de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5654830_sys_gh13558_dunningCandidate_onlyUpdate.sql
- backend/de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5655240_sys_gh13558_dunningCandidate_onlyUpdate.sql
- backend/de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5655270_sys_gh13558_dunningCandidate_onlyUpdate.sql
- backend/de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5655280_sys_gh13558_dunningCandidate_onlyUpdate.sql
- backend/de.metas.dunning/src/test/java/de/metas/dunning/api/impl/DefaultDunningCandidateProducerTest.java
- backend/de.metas.dunning/src/test/java/de/metas/dunning/api/impl/PlainDunningContext.java
- backend/de.metas.dunning/src/test/java/de/metas/dunning/api/impl/PlainDunningDAO.java
refs: https://github.com/metasfresh/metasfresh/issues/13558
> Improve "update dunning candidate" process

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java-legacy/org/compiere/acct/Doc_BankStatement.java
i.e. distinguish between conversion rounding differences and actual currency rate gain/loss
> Doc_BankStatement: hotfix how we calculate currency gain/loss

- backend/de.metas.business/src/main/java/de/metas/invoice/export/HealthcareXMLAttachedToInvoiceListener.java
https://github.com/metasfresh/metasfresh/issues/13598
> don't attempt to handle non-XML-attachment

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/Database.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaProduction.feature
refs: https://github.com/metasfresh/metasfresh/issues/13586
> Fix material-dispo bug

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/AdvancedSearchBPartnerProcessor.java
https://github.com/metasfresh/metasfresh/issues/13594
> Gh13594 search wizard

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5656020_sys_gh13595_add_bpartner_attribute_handler.sql
- backend/de.metas.handlingunits.base/src/main/java/org/adempiere/mm/attributes/spi/impl/HUBusinessPartnerAttributeHandler.java
- backend/de.metas.handlingunits.base/src/main/java/org/adempiere/mm/attributes/spi/impl/HUBusinessPartnerAttributeValuesProvider.java
https://github.com/metasfresh/metasfresh/issues/13595
> gh13595 add business partner attribute value handler

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5656080_sys_gh107_isDunning_Default.sql
- New Column ab182_isDunningDefault
- add index for only one active default
- changing dunning candidate create
https://github.com/metasfresh/ab182/issues/107
> Add new column AD_User.IsDunningDefault

- backend/de.metas.contracts/src/main/java/de/metas/contacts/invoice/interim/command/InterimInvoiceFlatrateTermCreateCommand.java
https://github.com/metasfresh/metasfresh/issues/13423
> #13423 add correct InterimInvoiceFlatrateTerm.PriceActual and use currency from orderline instead of order

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5656080_sys_gh107_isDunning_Default.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5656020_sys_gh13595_add_bpartner_attribute_handler.sql
- backend/de.metas.handlingunits.base/src/main/java/org/adempiere/mm/attributes/spi/impl/HUBusinessPartnerAttributeHandler.java
- backend/de.metas.handlingunits.base/src/main/java/org/adempiere/mm/attributes/spi/impl/HUBusinessPartnerAttributeValuesProvider.java
https://github.com/metasfresh/metasfresh/issues/13595
> Gh13595 mi adorablebadgeruat

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/invoiceCandidate.feature
> InEffect ICs - testID

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/calendar/ICalendarDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/calendar/IPeriodBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/calendar/impl/AbstractCalendarDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/calendar/impl/CalendarDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/calendar/impl/PeriodBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/calendar/impl/PlainCalendarDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/organization/LocalDateAndOrgId.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Prepare_Closing.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
- backend/de.metas.procurement.base/src/main/java/de/metas/procurement/base/PMMContractBuilder.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/api/impl/MaterialBalanceDetailDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_Forecast.java
https://github.com/metasfresh/metasfresh/issues/13623
> #13623 use only the date portion of C_Flatrate_Term.StartDate when figuring out which C_Period to use

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Clearance.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5656850_sys_gh13635_WEBUI_M_HU_Clearance_process.sql
> Set Clearingstatus on HU-Editor selection

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5657090_sys_gh13644_enlarge_name_printname_in_element_trl.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5657100_sys_gh13644_ad_element_trl_220907_2.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5657120_sys_gh13644_update_fr_CH_element_trl.sql
https://github.com/metasfresh/metasfresh/issues/13644
> gh13644 import fr_CH element translations

- backend/de.metas.async/src/main/java/de/metas/async/eventbus/AsyncBatchNotifyRequest.java
- backend/de.metas.async/src/main/java/de/metas/async/service/AsyncBatchObserver.java
- backend/de.metas.async/src/main/java/de/metas/async/service/AsyncBatchService.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/Check.java
> Investigate and fix flaky Checking the effect of override fields on invoice candidate

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5657170_sys_gh13603_Approved_For_Invoice_Error_Message_Trl_Fix.sql
> Disallow reactivating/reverting documents that have ICs approved for invoicing -> Error TRL Fix

- backend/de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5657300_sys_gh13625_sysconfig_material_cockpit_pmm_qty_atDate.sql
https://github.com/metasfresh/metasfresh/issues/13625
> add missing cockpit sys config 

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidate.java
refs https://github.com/metasfresh/metasfresh/issues/13316
> C_Invoice_Candidate - compute QtyToInvoice fix

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.async/src/main/java/de/metas/async/service/AsyncBatchObserver.java
- backend/de.metas.async/src/main/java/de/metas/async/service/AsyncBatchService.java
related to changes from https://github.com/metasfresh/metasfresh/issues/13629
> AsyncBatchObserver - improve error handling

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/externlasystem/ExternalSystemService.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/ExternalSystem_Config_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/MetasfreshToExternalSystemRabbitMQ_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/externalsystem/invokeExternalSystem.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workOrderProjectAPI.feature
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/other/ExternalSystemOtherConfig.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/other/ExternalSystemOtherConfigRepository.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/other/ExternalSystemOtherValue.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeOtherAction.java
- backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/ExternalSystemConfigRepoTest.snap
- backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/other/ExternalSystemOtherConfigRepositoryTest.snap
invoke "Other" ExternalSystem via API
> Allow invoking "Other" ExternalSystem via API

- backend/de.metas.business/src/main/java/de/metas/activity/repository/ActivityRepository.java
https://github.com/metasfresh/metasfresh/issues/13671
> ActivityID should be Nullable

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5657890_sys_gh13154_FLOID_advanced_edit_only.sql
FLO ID only in advanced edit
for the metasfresh repo
https://github.com/metasfresh/th173/issues/446
> FLO ID only in advanced edit

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5657890_sys_gh13154_FLOID_advanced_edit_only.sql
FLO ID only in advanced edit
for the metasfresh repo
https://github.com/metasfresh/metasfresh/issues/13679
> FLO ID only in advanced edit (#13686)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5657930_sys_gh13688_QtyToDeliver_Override_EN_Trl.sql
https://github.com/metasfresh/metasfresh/issues/13688
> Updating the QtyToDeliver_Override EN Trl

- misc/services/mobile-webui/mobile-webui-frontend/src/components/BarcodeScannerComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/scan/ScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.js
* make sure the onResolvedResult callback is called only once if successful
* avoid multiple concurrent callback calls
> mobile UI: QR code scanner fixes & improvements

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/QueryInsertExecutor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/Pointcut.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
- backend/de.metas.datev/src/main/sql/postgresql/system/5657450_sys_gh13664_RV_DATEV_Export_Fact_Acct_Invoice_generic_fields.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5657450_sys_gh13664_datev_generic_fields.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5657452_sys_gh13664_datev_generic_fields_add_ui_elements.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/data/export/api/impl/AbstractExporter.java
which can be selected for exporting to csv via DATEV_ExportFormat:
- c_tax_rate
- c_doctype_name
refs #13664
> Add two additional columns to DATEV_ExportLine

- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/manufacturing_issue.js
case: QtyToIssue=0, QtyIssued > 0 (i.e. alternative HUs)
> mobile UI: manufacturing issue: hotfix wrong QtyRejectd computed

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/stock/MD_Stock_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bom/asiSupportOnProductBOM.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/delivery/deliveryRules.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/inventory.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/materialDispo_shipmentSchedule.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/materialDispo_stockEstimateEvent.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/reverseMaterialReceipt.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/reverseShipment.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaProduction.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaPurchase.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/multipleProductionCandidates.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/productionCandidate.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/productionSimulation.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/stock/mdStock_AddInventory.feature
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/MaterialDispoRecordRepository.java
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/CandidateRepositoryRetrieval.java
https://github.com/metasfresh/metasfresh/issues/13637
> Cucumber: drop MD_Stock_StepDef#truncateMDStockData

- backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5659010_sys_gh13275_API_Invocation_Msg_rewrite.sql
Changing the msgtext from API Invocation
https://github.com/metasfresh/mf15/issues/1890
> Changing the msgtext from API Invocation

- backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5659010_sys_gh13275_API_Invocation_Msg_rewrite.sql
* Changing the msgtext from API Invocation
Changing the msgtext from API Invocation
https://github.com/metasfresh/mf15/issues/1890
* rewrite for the other API msg
rewrite for the other API msg
https://github.com/metasfresh/mf15/issues/1890
> Changing the msgtext from API Invocation (#13718)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/InOutProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleTestBase.java
https://github.com/metasfresh/metasfresh/issues/13725
> gh13725 c_doctypeshipment_id not respected when generating Receipt/Shipment

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5659200_sys_gh13120-edting_trls_ADreferences.sql
- edit translations for ad_references
https://github.com/metasfresh/ab182/issues/189
> edit translations for ad_references

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5659150_sys_fix_POInvoice_detailData_trl.sql
detail data trl fix (Ad_window_ID=183, tableName=C_Invoice_Detail)
> detail data trl fix (Ad_window_ID=183, tableName=C_Invoice_Detail)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5659150_sys_fix_POInvoice_detailData_trl.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/receiptschedule/impl/AbstractRSAllocationWithWeightAttributeTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/AbstractHUShipmentProcessIntegrationTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHUTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/InOutProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleTestBase.java
https://github.com/metasfresh/metasfresh/issues/13725
> Master integration adorable badger uat

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_GLJournal.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_GLJournal.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_GLJournal_FactTrxStrategy.java
Cherry-picked Doc_GLJournal: consider GL_JournalLine.GL_JournalLine_Group when grouping into FactTrxLines (#13739) to master.
for #13744
> CP GL Journal Split accounting issue

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5660150_sys_gh13753_adjust_autovacuum_settings_on_translation_tables.sql
https://github.com/metasfresh/metasfresh/issues/13753
> #13753 Adjust auto-vacuum settings on translation tables

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_PP_ComponentGenerator.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_PP_ComponentGenerator.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5661090_sys_gh13772_PP_ComponentGenerator_Description.sql
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/MacAddressGenerator.java
https://github.com/metasfresh/metasfresh/issues/13772
> MAC Address: set "-" instead of leaving empty

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5661130_sys_webui_view_invoiceToAllocate_messages.sql
- frontend/src/assets/css/InvoiceToAllocateViewHeader.scss
- frontend/src/components/app/DocumentList.js
- frontend/src/components/paymentAllocation/AmountIndicator.js
- frontend/src/components/paymentAllocation/InvoiceToAllocateViewHeader.js
- frontend/webpack.config.js
- frontend/webpack.prod.js
based on 
* https://github.com/metasfresh/metasfresh/pull/12989
> Invoice to allocate view: show sums of GrandTotal, OpenAmt, DiscountAmt for selected rows (scary_plum_uat)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5661150_sys_DoNotshow_hyphen_fresh_Attributes.sql
> Do not show attributes RouterMAC, RouterPassword and SW_Version that have value -

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5660790_sys_gh13780_Increase_Account_Name_Length.sql
https://github.com/metasfresh/metasfresh/issues/13780
> Increase the length of the name field in Account element

- frontend/src/components/paymentAllocation/InvoiceToAllocateViewHeader.js
follow-up of https://github.com/metasfresh/metasfresh/pull/13776
> Invoice To Allocate view: sum up selected rows only if they have same currency

- misc/services/mobile-webui/mobile-webui-frontend/package.json
attempt to fix issue explicitly adding babel-plugin-dynamic-import-node
> Fixing the mobile-ui build issue

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5661340_sys_gh13784_add_keep_porpsal_prices_process_param.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5661340_sys_gh13784_add_keep_propsal_prices_process_param.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/CreateSalesOrderFromProposalCommand.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_CreateFromProposal.java
- misc/services/mobile-webui/mobile-webui-frontend/package.json
https://github.com/metasfresh/metasfresh/issues/13784
> #13784 Price difference from offer to order

- frontend/src/components/app/DocumentList.js
- frontend/src/components/paymentAllocation/InvoiceToAllocateViewHeader.js
follow-up of 
* https://github.com/metasfresh/metasfresh/pull/13794
* https://github.com/metasfresh/metasfresh/pull/13776
> Invoice To Allocate view: handle all selected (selectedRowIds.includes('all')) - part 2

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_details.jrxml
- misc/services/mobile-webui/mobile-webui-frontend/package.json
https://github.com/metasfresh/metasfresh/issues/13766
> #13766 fix open items report

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/computeFrameOrderRemainingQtyPercentAfterCallOrder.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5661750_sys_gh13363_create_function_computeFrameOrderRemainingQtyPercentAfterCallOrder.sql
* create new function computeFrameOrderRemainingQtyPercent
create new function computeFrameOrderRemainingQtyPercent
https://github.com/metasfresh/metasfresh/issues/13827
> create new function computeFrameOrderRemainingQtyPercent (#13817)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5661990_sys_gh_add_sales_fields_to_partner.sql
- misc/services/mobile-webui/mobile-webui-frontend/package.json
https://github.com/metasfresh/metasfresh/issues/13822
> #13822 Fields for Sales

- backend/de.metas.manufacturing/src/main/sql/postgresql/ddl/functions/PP_Product_BOM_Recursive.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5662030_sys_gh13824_BOM_Recursive_Report.sql
- misc/services/mobile-webui/mobile-webui-frontend/package.json
https://github.com/metasfresh/metasfresh/issues/13824
> The excel export process should consider the latest BOM version

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Role.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Role.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Env.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Login.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/LoginContext.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/IRolesTreeNode.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/Role.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/impl/RoleDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/impl/UserRolePermissionsBuilder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/impl/AbstractTrxManager.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5661930_sys_gh13833_AD_Role_RoleGroup.sql
https://github.com/metasfresh/metasfresh/issues/13833
> Add AD_Role.Role_Group and add is to the context as "#AD_Role_Group"

- backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU.java
- backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ClearanceStatus.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ClearanceStatusInfo.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5661600_sys_M_HU_Clearance_Status_TestPending.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5661870_sys_gh13812_M_HU_ClearanceDate.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5662010_sys_gh13812_M_HU_ClearanceDate_Parameter.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HandlingUnitsBLTest.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Clearance.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveCUs.java
- misc/services/mobile-webui/mobile-webui-frontend/package.json
https://github.com/metasfresh/metasfresh/issues/13812
> HU Clearance: Status Test Pending

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/JsonHUHelper.java
- misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/handlingunits/JsonClearanceStatus.java
https://github.com/metasfresh/metasfresh/issues/13812
> HU Clearance: Status Test Pending (Json)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5661990_sys_gh_add_sales_fields_to_partner.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5662200_sys_gh13822_fixing_sales_fields_to_partner.sql
https://github.com/metasfresh/metasfresh/issues/13822
> Master integration iron plan uat gh13822

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_field_v.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5662580_sys_gh13833_AD_Field_Views_IsAlwaysUpdatable.sql
https://github.com/metasfresh/metasfresh/issues/13801
> AD_Field.IsAlwaysUpdatable views

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5662810_gh13644_add_empty_tab_restult_text_and_hint.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
https://github.com/metasfresh/metasfresh/issues/13644
> #13784 fixes empty_result_text message and hint

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5662970_sys_gh13644_provide_translation_for_filter_caption.sql
- frontend/src/components/filters/FiltersIncluded.js
https://github.com/metasfresh/metasfresh/issues/13644
> #13784 provide translation for Filter caption

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5662990_sys_gh13833_AD_Field_IsAlwaysUpdatable_DefaultEmpty.sql
https://github.com/metasfresh/metasfresh/issues/13801
> Adorable badger uat ad field is always updatable default

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5662990_sys_gh13833_AD_Field_IsAlwaysUpdatable_DefaultNULL.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5663000_sys_gh13833_AD_Field_IsAlwaysUpdatable_DefaultNULL_Update.sql
https://github.com/metasfresh/metasfresh/issues/13801
> AD_Field.IsAlwaysUpdatable default NULL

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/po/CustomColumnService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/util/converter/POValueConverters.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5661340_sys_gh13784_add_keep_propsal_prices_process_param.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableUtil.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5636410_sys_gh12879_ShowAllDateAttributes.sql
- backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/ProductLowLevelCalculatorTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/CreateSalesOrderFromProposalCommand.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_CreateFromProposal.java
https://github.com/metasfresh/metasfresh/issues/13784
> Master integration release 13784

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5663030_sys_AD_Window_AD_Element_ID_unique_index.sql
Prevent earlier problems which will come a bit later
> Add unique index on AD_Window(AD_Element_ID)

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5663100_sys_gh13850_M_HU_UniqueAttribute_Messages_Corrections.sql
https://github.com/metasfresh/metasfresh/issues/13850
> M_HU_Unique_Attributes

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5662680_sys_gh13850_M_HU_Attribute_IsUnique.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5663100_sys_gh13850_M_HU_UniqueAttribute_Messages_Corrections.sql
https://github.com/metasfresh/metasfresh/issues/13850
> Tenacious d uat unique attribute finetuning

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5663120_sys_webui_dashboad_messages.sql
- frontend/src/actions/BoardActions.js
- frontend/src/actions/DashboardActions.js
- frontend/src/actions/GenericActions.js
- frontend/src/components/board/Card.js
- frontend/src/components/charts/Indicator.js
- frontend/src/components/charts/RawChart.js
- frontend/src/components/dashboard/ChartWidget.js
- frontend/src/components/dashboard/DndWidget.js
- frontend/src/components/dashboard/DraggableWrapper.js
- frontend/src/components/dashboard/EntityType.js
- frontend/src/components/dashboard/Placeholder.js
- frontend/src/components/dashboard/Sidenav.js
- frontend/src/constants/ItemTypes.js
1. make it work (was broken by https://github.com/metasfresh/metasfresh/pull/12382 )
2. introduced the following ad_messages to translate hardcoded texts:
| value | msgtext |
| :--- | :--- |
| webui.dashboard.addNew.kpi | Add KPI widget |
| webui.dashboard.addNew.targetIndicator | Add Target Indicator widget |
| webui.dashboard.item.details | DETAILS |
| webui.dashboard.item.maximize | Maximize |
| webui.dashboard.item.minimize | Minimize |
| webui.dashboard.item.settings.caption | Caption |
| webui.dashboard.item.settings.interval.caption | Interval |
| webui.dashboard.item.settings.interval.week | Week |
| webui.dashboard.item.settings.save | Save |
| webui.dashboard.item.settings.when.caption | When |
| webui.dashboard.item.settings.when.lastWeek | Last week |
| …
> Fix webui dashboard

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentEntryId.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentEntryRepository.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/listener/AttachmentListener.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/listener/TableAttachmentListenerService.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/importfile/BankStatementImportFile.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/importfile/listener/BankStatementImportFileAttachmentListener.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/importfile/log/BankStatementImportFileLogRepository.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/importfile/log/BankStatementImportFileLoggable.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/importfile/log/BankStatementImportFileRequestLog.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/org/adempiere/banking/model/I_C_BankStatement_Import_File_Log.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/org/adempiere/banking/model/X_C_BankStatement_Import_File_Log.java
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5662350_sys_gh13844_add_BankStatementImportFileAttachmentListener.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5662380_sys_gh13844_MissingBankStatementLines_msg.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5662470_sys_gh13844_add_C_BankStatement_Import_File_Log.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5662520_sys_gh13844_bankStmt_import_ad_message_logs.sql
- backend/de.metas.banking/de.metas.banking.camt53/README.md
- backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/BankStatementCamt53Service.java
- backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/process/C_BankStatement_Import_File_Camt53_ImportAttachment.java
- backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/AccountStatement2Wrapper.java
- backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/NoBatchReportEntry2Wrapper.java
https://github.com/metasfresh/metasfresh/issues/13844
> Adorable badger uat gh13844

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUUniqueAttributesService.java
https://github.com/metasfresh/metasfresh/issues/13850
> Tenacious d uat blank validation

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/cockpit/MD_Cockpit_DocumentDetail_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/cockpit/MD_Cockpit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialCockpit/materialCockpit_PO_noProductPlanning.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialCockpit/materialCockpit_SO_noProductPlanning.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/materialDispo_shipmentSchedule.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaProduction.feature
- backend/de.metas.material/cockpit/src/main/java/de/metas/material/cockpit/CockpitId.java
- backend/de.metas.material/cockpit/src/main/java/de/metas/material/cockpit/view/eventhandler/ShipmentScheduleEventHandler.java
- backend/de.metas.material/cockpit/src/main/java/de/metas/material/cockpit/view/mainrecord/UpdateMainDataRequest.java
- backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/shipmentschedule/ShipmentScheduleCreatedHandlerTests.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/shipmentschedule/AbstractShipmentScheduleEvent.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/shipmentschedule/ShipmentScheduleCreatedEvent.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/shipmentschedule/ShipmentScheduleDeletedEvent.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/shipmentschedule/ShipmentScheduleDetail.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/shipmentschedule/ShipmentScheduleUpdatedEvent.java
- backend/de.metas.material/event/src/test/java/de/metas/material/event/MaterialEventSerializerTests.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_ShipmentSchedule_PostMaterialEvent.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/material/interceptor/M_ShipmentSchedulePostMaterialEventTest.java
refs: https://github.com/metasfresh/metasfresh/issues/13829
> Test&Fix MD_Cockpit_DocumentDetail

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Candidate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Candidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_EnqueueSelectionForOrdering.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateOrderCandidateCommand.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643230_sys_gh13158_Adjust_Manufacturing_candidate.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5663200_sys_gh13843_PP_Order_Candidate_SeqNo.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5663320_sys_gh13843_PP_Order_SeqNo.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5663510_sys_gh13843_PP_Order_SeqNo_Index.sql
https://github.com/metasfresh/metasfresh/issues/13843
> Gh13843 pp order seq no

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/model/interceptor/AD_Role.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5663460_sys_gh13887_set_column_AD_Role_IsManual_to_IsCalculated.sql
also minor readability-improvement in AD_Role
#13887
> Change AD_Role.IsManual to IsCalculated=Y; see technicalnote

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/impl/LanguageDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/po/POTrlRepository.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5663760_sys_gh13904_C_UOM_Rename_Inactive.sql
https://github.com/metasfresh/metasfresh/issues/13904
> Adorable badger uat trl base language

- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
- frontend/src/components/dashboard/DraggableWrapper.js
follow-up of https://github.com/metasfresh/metasfresh/pull/13876
> Fix webui dashboard items dragging

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_EnqueueSelectionForOrdering.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5663200_sys_gh13843_PP_Order_Candidate_SeqNo.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5663320_sys_gh13843_PP_Order_SeqNo.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5663510_sys_gh13843_PP_Order_SeqNo_Index.sql
- frontend/src/assets/css/PPOrderCandidateViewHeader.scss
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/desadvexport/compudata/CompuDataDesadvBean.java
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/excelimport/ExcelImpCOLCandTypeBuilder.java
- misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
https://github.com/metasfresh/metasfresh/issues/13843
> Tasty_ham_uat to master gh13914

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/impl/LanguageDAO.java
https://github.com/metasfresh/metasfresh/issues/13904
> get rid of int AD_User_ID and replace it with UserId

- backend/de.metas.business/src/main/java/de/metas/product/impexp/MProductImportTableSqlUpdater.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcess.java
https://github.com/metasfresh/metasfresh/issues/13922
> Make UOM key on product import not case sensitive

- backend/de.metas.business/src/main/java/de/metas/product/impexp/MProductImportTableSqlUpdater.java
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/desadvexport/compudata/CompuDataDesadvBean.java
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/excelimport/ExcelImpCOLCandTypeBuilder.java
https://github.com/metasfresh/metasfresh/issues/13922
> Master integration clone wars uat gh13922

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_GLJournal.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_GLJournal.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_GLJournal_FactTrxStrategy.java
(cherry picked from commit ff68b2ceba849d9a5949c6b4df86bd0039b3afdc)
> Doc_GLJournal: consider GL_JournalLine.GL_JournalLine_Group when grouping into FactTrxLines (#13739)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5664780_sys_fix_Gram_UOM_Trl.sql
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/weighting/run/callout/PP_Order_Weighting_Run.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/weighting/spec/WeightingSpecificationsMap.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/weighting/spec/WeightingSpecificationsRepository.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5664770_sys_fix_PP_Order_BOMLine_trl.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5664790_sys_fix_msg_trl.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5664800_sys_allow_VolumeLiquid_UOMs_in_Weighting_run.sql
Fixes 
* https://github.com/metasfresh/metasfresh/pull/13920
> Manufacturing Order - Weighing Run (part 2)

- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPRoutingRepository.java
this prevents us from creating PP_Order with the restpective default-WF happens to have a node which lack a ressource
> fix an error that happenes when an AD_WF_Node has no resource

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/data/DataExportAudit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/MetasfreshToExternalSystemRabbitMQ_StepDef.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemType.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeMetasfreshAction.java
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5663980_sys_gh13929_externalSystemConfig_Metasfresh.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5664540_sys_gh13929_externalSystemMetasfresh_trls.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5664570_sys_gh13929_metasfresh_externalSystemService.sql
- backend/de.metas.externalsystem/src/test/java/de/metas/externalsystem/ExternalSystemConfigRepoTest.java
- backend/de.metas.externalsystem/src/test/java/de/metas/externalsystem/ExternalSystemTestUtil.java
- backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/ExternalSystemConfigRepoTest.snap
- backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/restapi/auth/WebSecurityConfig.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/ErrorReportRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/main/resources/application.properties
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/README.md
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/bpartner/FileBPartnersRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/bpartner/processor/ParseBPartnersProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/restapi/MassJsonRequestDispatcherRoute.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/restapi/MetasfreshRestAPIContext.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/restapi/MetasfreshRestAPIRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/restapi/feedback/MassUpsertFeedbackRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/java/de/metas/camel/externalsystems/metasfresh/restapi/MetasfreshRestAPIRouteBuilderTest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/resources/application.properties
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/resources/de/metas/camel/externalsystems/metasfresh/restapi/10_JsonAuthenticateRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/resources/de/metas/camel/externalsystems/metasfresh/restapi/1_ExternalSystemRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/resources/de/metas/camel/externalsystems/metasfresh/restapi/20_ExternalStatusCreateCamelRequestActive.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/resources/de/metas/camel/externalsystems/metasfresh/restapi/20_ExternalStatusCreateCamelRequestInactive.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/test/resources/de/metas/camel/externalsystems/metasfresh/restapi/20_JsonExpireTokenResponse.json
https://github.com/metasfresh/metasfresh/issues/13929
> ExternalSystem component for batched bpartner-upserts via REST follow up

- backend/de.metas.acct.base/src/main/java/de/metas/acct/model/validator/GL_JournalLine.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5665090_sys_gh13959_Enable_Remote_Cache_For_GL_Journal.sql
https://github.com/metasfresh/metasfresh/issues/13959
> GL Journal: update remote cache 

- backend/de.metas.material/cockpit/src/main/sql/postgresql/ddl/views/MD_Stock_From_HUs_V.sql
- backend/de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5665370_sys_gh13968_include_inactive_HUs_in_MD_stock.sql
https://github.com/metasfresh/metasfresh/issues/13968
> #13968 include inactive HUs in MD_Stock calculation

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheMgt.java
- backend/de.metas.externalreference/src/main/java/de/metas/externalreference/interceptor/S_ExternalReference.java
- backend/de.metas.externalreference/src/main/sql/postgresql/system/80-de.metas.externalreference/5665400_sys_gh13970_adjust_Delete_Externally_Referenced_Error_Msg.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/decorator/DraftInvoiceDecorator.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/decorator/ExternallyReferencedDocumentDecorator.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/decorator/ReadOnlyInfo.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/Document.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentReadonly.java
refs: https://github.com/metasfresh/metasfresh/issues/13970
> Externally referenced records: further improvements

- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5665630_PP_UserInstructions_TextLong.sql
fixes https://github.com/metasfresh/metasfresh/pull/13978
> Use text long for PP_UserInstructions

- misc/services/mobile-webui/mobile-webui-frontend/src/api/launchers.js
fixes
* https://github.com/metasfresh/metasfresh/pull/13977
> mobile UI: hotfix launchers ws connection

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUUniqueAttributesService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/interceptor/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributes.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributesProvider.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataLoader.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataSupplier.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
`tenacious_d_uat` branch to `master` merge
> `Tenacious_d_uat` To `master` merge gh13949

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/DocumentNoBuilder.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/SerialNoBL.java
https://github.com/metasfresh/metasfresh/issues/13992
> Triger cache validation after updating the `Serial No` from `AD_Sequence`

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/DocumentNoBuilder.java
https://github.com/metasfresh/metasfresh/issues/13992
> `Tenacious_d_uat` To `master` merge gh13992

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/cache/Case_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/C_Commission_Fact_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/customColumns/setCustomColumns.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/impl/ShipmentScheduleInvalidateRepository.java
> Inner silence uat gh actions dev

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/testing/AppTestingRestController.java
e.g. http://localhost:8282/api/v2/test/cacheReset?apiKey=....
(copied from master)
> App server /api/v2/test/cacheReset REST endpoint

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_OrderLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDefTableTransformer.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/purchasecandidate/C_PurchaseCandidate_Alloc_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/purchasecandidate/C_PurchaseCandidate_Alloc_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/purchasecandidate/C_PurchaseCandidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaPurchase.feature
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactory.java
- backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactoryTest.java
- backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemsAggregatorTest.java
refs: https://github.com/metasfresh/metasfresh/issues/13998
> Test & Fix Purchase candidate interaction with MD_Cockpit

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/UserSessionRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/session/json/JSONUserSession.java
- frontend/src/utils/settings.js
copied from master. The feature was introduced initially in
* https://github.com/metasfresh/metasfresh/pull/13881
> expose webui.frontend.* sysconfigs to frontend /userSession endpoint

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/AddRemoveChangedRowIdsCollector.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/DefaultView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IViewDataRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRowIdsOrderedSelectionsHolder.java
follow-up of 
* https://github.com/metasfresh/metasfresh/pull/14017
> webui: Make sure all views are notified on view addition changes

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/impl/ShipmentScheduleInvalidateRepository.java
- backend/metasfresh-dist/dist/src/main/docker/db-init/Dockerfile
- docker-builds/Dockerfile.db-standalone
- docker-builds/db/init/init.sh
will be merged with `merge commit`
> Mad orange uat gh actions cucumber

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5666080_sys_gh13942_Delivery_Planning_Identifiers.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5666170_sys_gh13942_Delivery_Planning_AD_Names.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5666180_sys_gh13942_Delivery_Planning_ReadOnlyFields.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
> Adorable badger uat finetunning

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666210_sys_gh14027_display_sepa_revolut_export_details.sql
https://github.com/metasfresh/metasfresh/issues/14027
> #14027 Display SEPA/REVOLUT Export Details

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666210_sys_gh14027_display_sepa_revolut_export_details.sql
https://github.com/metasfresh/metasfresh/issues/14027
> Gh14027 mi display export details

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/SpringContextHolder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/StartupListener.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/test/AdempiereTestHelper.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/C_Commission_Fact_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/customColumns/setCustomColumns.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/impl/ShipmentScheduleInvalidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/spi/impl/MutableQtyAndQualityTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL_QtyAndQuality_FromInOutLine_Test.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuerTest.java
> Release gh actions cucumber

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/SpringContextHolder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/StartupListener.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/test/AdempiereTestHelper.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/spi/impl/MutableQtyAndQualityTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL_QtyAndQuality_FromInOutLine_Test.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuerTest.java
> Yoyo uat gh actions junit

- .github/workflows/cicd.yaml
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/SpringContextHolder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/StartupListener.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/test/AdempiereTestHelper.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/C_Commission_Fact_StepDef.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/impl/ShipmentScheduleInvalidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/spi/impl/MutableQtyAndQualityTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL_QtyAndQuality_FromInOutLine_Test.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuerTest.java
- backend/metasfresh-dist/dist/src/main/docker/db-init/Dockerfile
- docker-builds/Dockerfile.db-preloaded
- docker-builds/Dockerfile.db-standalone
- docker-builds/Dockerfile.junit
- docker-builds/db/init/init.sh
will be merged with `merge commit`
> Adorable badger uat gh actions cucumber

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Update_DateAcctBeforeDate.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5666570_sys_gh14042_Update_DateAcctBeforeDate.sql
https://github.com/metasfresh/metasfresh/issues/14042
> Create a generic function to update the Fact_Acct.DateAcct before date

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Update_DateAcctBeforeDate.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5666570_sys_gh14042_Update_DateAcctBeforeDate.sql
https://github.com/metasfresh/metasfresh/issues/14042
> Mad orange master gh14042

- backend/de.metas.business/src/main/sql/postgresql/ddl/functions/formatQtyToDisplay.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666790_sys_gh341_show_always_three_decimals_in_stock_balance_report.sql
https://github.com/metasfresh/metasfresh/issues/14060
> #13942 Delivery Planning Master Data fixes

- backend/de.metas.business/src/main/sql/postgresql/ddl/functions/formatQtyToDisplay.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666790_sys_gh341_show_always_three_decimals_in_stock_balance_report.sql
https://github.com/metasfresh/metasfresh/issues/14060
> Mi adorable badger uat gh14060

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5666380_cli_gh14036_set_without_oids.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5666390_cli_gh14036_set_without_oids.sql
https://github.com/metasfresh/metasfresh/issues/14036
> remove oids not supported in newer postgres versions

- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
https://github.com/metasfresh/metasfresh/issues/14062
> Flat Rate Term extension uses wrong Bill Partner

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666930_sys_gh13942_delivery_planning_fix_forwarder_reflist.sql
> Mi adorable badger uat delivery planning fixes

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666940_sys_gh13942_delivery_planning_ui_fixes.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
> Mi adorable badger uat delivery planning UI fixes

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667050-gh13846_Fix_trl_NL_duplicates_test.sql
Fix window_trl Duplicates NL name:Test
https://github.com/metasfresh/mf15/issues/1999
> Fix window_trl Duplicates NL name:Test

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5666030_sys_gh14011_MovementDate_Date+Time_ M_Inventory.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/inventory/M_Inventory_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDefTableTransformer.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_Product_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/delivery/deliveryRules.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/inventory.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/materialDispo_stockEstimateEvent.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaPurchase.feature
refs: https://github.com/metasfresh/metasfresh/issues/14011
> Sub-Task No 4: Test & Fix Inventory interaction with MD_Cockpit

- .github/workflows/cicd.yaml
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/SpringContextHolder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/StartupListener.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/test/AdempiereTestHelper.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/ImportInvoiceCandidatesService.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/spi/impl/MutableQtyAndQualityTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL_QtyAndQuality_FromInOutLine_Test.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuerTest.java
- docker-builds/Dockerfile.db-preloaded
- docker-builds/Dockerfile.junit
- docker-builds/README.md
will be merged with `merge commit`
> Inner silence uat gh actions junit

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDef.java
to be merged via `merge commit`
> improve assert logging

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5667460_sys_gh13750_trans_material.sql
> material translation added

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647677_sys_gh13846_Fix_trl_fr_CH_duplicates.sql
trls duplicate fix Fr_CH
https://github.com/metasfresh/mf15/issues/1999
> trls duplicate fix Fr_CH

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5667550_sys_gh214_replaced_product.sql
> replaced produktname

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/taxaccounts_details.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/taxaccounts_perVATCode.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/taxaccountsonly_details.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/MV_Fact_Acct_Sum.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5667270_sys_Adjsut_tax_Accounts_functions.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5667270_sys_Sum_taxaccounts_perVATCode.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5668200_Add_newTax_accounting_report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting/report_recap.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_new/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_new/report_recap.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_recap.jrxml
Summing up only those amounts that are on tax accounts
> Sum amounts per vatcode

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647674_sys_gh13846_Fix_trl_NL_FR_duplicates_test.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647676_sys_gh13846_Fix_trl_NL_duplicates_test.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647677_sys_gh13846_Fix_trl_fr_CH_duplicates.sql
Fixing the script for FR and NL trls fix
https://github.com/metasfresh/mf15/issues/1999
> Fixing the script for FR and NL trls fix

- backend/de.metas.acct.base/src/main/java/de/metas/acct/gljournal_sap/interceptor/SAP_GLJournalLine.java
follow-up of
* https://github.com/metasfresh/metasfresh/pull/14174
> hotfix SAP_GLJournalLine add new manually was not refreshing header totals

- frontend/src/__tests__/components/widget/List/RawList.test.js
- frontend/src/components/widget/List/RawList.js
test case:
GL Journal (SAP) - Batch entry - first field is DR/CR which was not gaining focus even if it was the first field (i.e. pressing DOWN key was doing nothing, pressing TAB was not going to next field)
> webui Dropdown: hotfix focus gained was not working

- misc/dev-support/docker/infrastructure/db/Dockerfile
https://github.com/metasfresh/metasfresh/issues/14187
> update infrastructure db dockerfile

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5669447_sys_gh14191_clean_nl_NL_translations.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5669450_sys_gh14191_translate_technicaldescription.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5669470_sys_gh14191_copy_technicaldescription_data.sql
https://github.com/metasfresh/metasfresh/issues/14191
> #14191 Language Adjustments

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647676_sys_gh13846_Projekt_fix_trls_duplicate.sql
Fixing more trls Problems:
- Projekt
> Fixing more duplicate trls Problems

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5669260_gh14178_add_import_and_export_processor.sql
https://github.com/metasfresh/metasfresh/issues/14178
> Add standard EDI-Replication-Settings

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5669580_sys_gh14164_AcctView_Grid_Order_And_SectionCode.sql
https://github.com/metasfresh/metasfresh/issues/14164
> display sales order and section code in accounting window, grid view

- frontend/src/components/widget/List/List.js
test case:
* open GL Journal (SAP)
* batch entry
* using keyboard, set DR/CR, combination, amount, tax and ENTER
* you are back to DR/CR field
* press DOWN key => dropdown opens but without any items => NOK
> hotfix: webui: List is not loaded in batch entry

- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessor.java
- backend/de.metas.device.scales/src/main/java/de/metas/device/scales/impl/soehenle/SoehenleSendTargetWeightRequest.java
- backend/de.metas.device.scales/src/test/java/de/metas/device/scales/impl/soehenle/SoehenleSendTargetWeightRequestTest.java
https://github.com/metasfresh/metasfresh/issues/14239
> make sure that the target-weight has at least 2 digits after the comma

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/DocumentNoBuilder.java
https://github.com/metasfresh/metasfresh/issues/14201
> #14201 ensure CalendarMonth lookup is performed using least amount of digits

- backend/de.metas.async/src/main/java/de/metas/async/model/validator/C_Queue_WorkPackage.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pporder/PP_OrderCandidate_PP_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pporder/PP_Order_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/multipleProductionCandidates.feature
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/async/GeneratePPOrderFromPPOrderCandidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
* trigger async batch progress check, also after a new C_Queue_Workpackge is created
* process PP_Order_Candidate: sort PP_Order_Candidates by ID within Group
* improve cucumber and logging
> Fixes intensiveCare

- backend/de.metas.async/src/main/java/de/metas/async/model/validator/C_Queue_WorkPackage.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate_inoutline/C_InvoiceCandidate_InOutLine_StepDef.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
* trigger async batch progress check, also after a new C_Queue_WorkPackage is created
* improve cucumber and logging
* fix flaky C_InvoiceCandidate_InOutLine_StepDef
> Fixes bigCoconut

- backend/de.metas.async/src/main/java/de/metas/async/model/validator/C_Queue_WorkPackage.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate_inoutline/C_InvoiceCandidate_InOutLine_StepDef.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/DeliveredDataLoader.java
…ckage is created
* improve cucumber and logging
> Fixes release

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667170_sys_gh13846_extra_trls_reapply.sql
extra trls that needed to be reapplied
> extra trls that needed to be reapplied

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667160_sys_gh13846_fix_trls_AD_Menu.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667170_sys_gh13846_extra_trls_reapply.sql
> Release Branch PRs

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoicecandidates/impl/CreateInvoiceCandidatesService.java
- backend/de.metas.externalreference/src/main/sql/postgresql/system/80-de.metas.externalreference/5671110_sys_gh14257_add_orgId_to_ExternalReferences_window.sql
https://github.com/metasfresh/metasfresh/issues/14257
> #14257 add AD_Org_ID field to External References window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671160_sys_gh13846_missing_trls_master.sql
> some missing trls master

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671150_sys_gh13846_more_missing_trls.sql
> some more missing trls

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5671190_sys_gh14342_Shipment_DESADV_Pack.sql
https://github.com/metasfresh/metasfresh/issues/14342
> Fixing `M_InOut` to `EDI_Desadv_Pack` Relation

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671150_sys_gh13846_more_missing_trls.sql
* some more missing trls
some more missing trls
* Update 5671150_sys_gh13846_more_missing_trls.sql
> some more missing trls (#14313)

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5671190_sys_gh14342_Shipment_DESADV_Pack.sql
https://github.com/metasfresh/metasfresh/issues/14342
> Gh14342 hot uat merge

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671240_sys_gh13846_missing_de_CH_trls.sql
> missing de_CH trls

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671240_sys_gh13846_missing_de_CH_trls.sql
> missing de_CH trls (#14349)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/invoice/InvoiceId.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/invoice/InvoiceLineId.java
- backend/de.metas.business/src/main/java/de/metas/invoice/acct/AccountTypeName.java
- backend/de.metas.business/src/main/java/de/metas/invoice/acct/InvoiceAcct.java
- backend/de.metas.business/src/main/java/de/metas/invoice/acct/InvoiceAcctRepository.java
- backend/de.metas.business/src/main/java/de/metas/invoice/acct/InvoiceAcctService.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5671370_C_Invoice_Acct.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5671480_C_Invoice_Acct_addToMenu.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5671490_C_Invoice_Acct_config_identifier.sql
- backend/de.metas.business/src/test/java/de/metas/invoice/acct/InvoiceAcctRepositoryTest.java
- backend/de.metas.util/src/main/java/de/metas/util/GuavaCollectors.java
- backend/de.metas.util/src/test/java/de/metas/util/GuavaCollectorsTest.java
NOTE to devs:
* use `InvoiceAcctService` to access this feature
> C_Invoice_Acct

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/ProductAllergenRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/ProductRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/helper/ExternalReferenceRequestHelper.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/product/ProductsRestControllerTest.java
- backend/de.metas.business/src/main/java/de/metas/product/CreateProductRequest.java
- backend/de.metas.business/src/main/java/de/metas/product/Product.java
- backend/de.metas.business/src/main/java/de/metas/product/ProductRepository.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/AllergenRepository.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/AllergenService.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/ProductAllergens.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/ProductAllergensRepository.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/ProductAllergensService.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/SaveAllergenRequest.java
- backend/de.metas.business/src/main/java/de/metas/product/allergen/SaveProductAllergenRequest.java
- backend/de.metas.externalreference/src/main/java-gen/de/metas/externalreference/model/X_S_ExternalReference.java
- backend/de.metas.externalreference/src/main/java/de/metas/externalreference/ExternalReferenceTypes.java
- backend/de.metas.externalreference/src/main/java/de/metas/externalreference/allergen/AllergenExternalReferenceType.java
- backend/de.metas.externalreference/src/main/sql/postgresql/system/80-de.metas.externalreference/5671830_sys_gh14223_ExternalReferenceType_Allergen.sql
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestAllergenItem.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestProduct.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestUpsertProductAllergen.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/SyncAdvise.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/bom/processor/PushProductProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonAllergen.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBOM.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/bom/10_ProductUpsertCamelRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/bom/20_BOMUpsertCamelRequest.json
refs: https://github.com/metasfresh/metasfresh/issues/14223
> import Allergens for bom products

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671840_sys_gh13846_missing_de_trls.sql
some more missing trls after IT-Test
> some more missing trls after IT-Test

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/report_not_invoiced_receipts.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5671849_sys_gh14367_report_not_invoiced_receipts.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5671850_sys_gh14367_create_adprocess_for_report_not_invoiced_receipt.sql
https://github.com/metasfresh/metasfresh/issues/14367
> #14367 add reports for Not Invoiced Receipts

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/IHUReceiptScheduleDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleListener.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleWeightNetAdjuster.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/model/validator/M_ReceiptSchedule.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/InOutProducerFromReceiptScheduleHU.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformServiceReceiptCandidatesTests.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/receiptschedule/impl/ReceiptScheduleHUAllocationsTest.java
Also rename IHUReceiptScheduleDAO.retrieveHandlingUnitAllocations to ...retrieve**All**HandlingUnitAllocations for more clarify
> Fix HUReceiptScheduleBL by not collecting the HUs of inactive RSAs

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5672030_sys_gh14381_set_c_doctypetarger_id_as_filter_in_c_order.sql
https://github.com/metasfresh/metasfresh/issues/14381
> #14381 Set C_doctypeTarget_ID as filter in C_Order

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5672030_sys_gh14381_set_c_doctypetarger_id_as_filter_in_c_order.sql
https://github.com/metasfresh/metasfresh/issues/14381
> Mi tenacious d uat gh14381

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Department.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Department_SectionCode.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Department.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Department_SectionCode.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5672690_sys_gh14414_add_department_data_structure.sql
https://github.com/metasfresh/metasfresh/issues/14414
> #14414 Add Department Data Structures

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/DocumentLocation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5672890_sys_gh14412_fix_M_Warehouse_C_Location_ID.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/interceptor/C_BPartner_Location.java
https://github.com/metasfresh/metasfresh/issues/14412
> Use BPartner.C_Location_ID Location in Warehouse instead of M_Warehouse.C_Location_ID

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Delivery_Planning.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Delivery_Planning.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5672860_sys_gh14215_M_Delivery_Planning_M_Shipper_Transportation_ID_Column.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5672861_mig_gh14215_M_Delivery_Planning_M_Shipper_Transportation_ID_UpdateExisting.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/deliveryplanning/DeliveryInstructionUserNotificationsProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/deliveryplanning/interceptor/M_ShipperTransportation.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/deliveryplanning/process/M_Delivery_Planning_GenerateDeliveryInstruction.java
https://github.com/metasfresh/metasfresh/issues/14215
> Adorable badger uat delivery instruction notification

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5672940_sys_gh14414_add_department_data_structure.sql
https://github.com/metasfresh/metasfresh/issues/14414
> #14414 remove ad_client_id from grid  view

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5672940_sys_gh14414_add_department_data_structure.sql
> Mi adorable badger uat gh14414

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5673080_sys_gh14429_decrease_credit_limit.sql
https://github.com/metasfresh/metasfresh/issues/14429
> #14429 Increased Credit Limit for the section partner can be decreased again

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Stats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Stats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/model/interceptor/C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/process/C_BPartner_Stats_ComputeBPartnerStats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPartnerStats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerStatsDAO.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5673170_sys_gh14433_add_section_code_partner_stats.sql
> #14433 Add M_SectionCode_ID to C_BPartner_Stats

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/IVATCodeDAO.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/VATCode.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/impl/VATCodeDAO.java
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5673260_sys_gh14437_added_tax_param_to_PO_from_SO_Process.sql
- backend/de.metas.acct.base/src/test/java/de/metas/acct/vatcode/impl/C_VAT_Code_Builder.java
- backend/de.metas.acct.base/src/test/java/de/metas/acct/vatcode/impl/VATCodeDAOTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOFromSOsAggregator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOLineFromSOLinesAggregator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_CreatePOFromSOs.java
https://github.com/metasfresh/metasfresh/issues/14437
> #14437 allow passing in manual tax rate for CreatePOFromSOs process

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/IVATCodeDAO.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/VATCode.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/impl/VATCodeDAO.java
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5673260_sys_gh14437_added_tax_param_to_PO_from_SO_Process.sql
- backend/de.metas.acct.base/src/test/java/de/metas/acct/vatcode/impl/C_VAT_Code_Builder.java
- backend/de.metas.acct.base/src/test/java/de/metas/acct/vatcode/impl/VATCodeDAOTest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Stats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Stats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/model/interceptor/C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/process/C_BPartner_Stats_ComputeBPartnerStats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPartnerStats.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerStatsDAO.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5673170_sys_gh14433_add_section_code_partner_stats.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOFromSOsAggregator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOLineFromSOLinesAggregator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_CreatePOFromSOs.java
> Mi adorable badger uat 14433

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/RecordBasedLocationAdapter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/RecordBasedLocationUtils.java
- backend/de.metas.business/src/main/java/de/metas/order/location/OrderLocationsUpdater.java
https://github.com/metasfresh/metasfresh/issues/14412
> Update Delivery ToAddress Capture Location when cloning

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5673720_sys_gh14429_decrease_credit_limit.sql
> #14429 decrease credit limit only for Section Partners

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/DocumentLocation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/RecordBasedLocationAdapter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/RecordBasedLocationUtils.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5672890_sys_gh14412_fix_M_Warehouse_C_Location_ID.sql
- backend/de.metas.business/src/main/java/de/metas/order/location/OrderLocationsUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/interceptor/C_BPartner_Location.java
https://github.com/metasfresh/metasfresh/issues/14412
> merging `mad_orange_uat` to `master`

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/DocumentLocation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/RecordBasedLocationAdapter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/RecordBasedLocationUtils.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5672890_sys_gh14412_fix_M_Warehouse_C_Location_ID.sql
- backend/de.metas.business/src/main/java/de/metas/order/location/OrderLocationsUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/interceptor/C_BPartner_Location.java
Replacing https://github.com/metasfresh/metasfresh/pull/14447 PR
> Gh14412 mado master

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5672020_sys_gh14215_M_ShippingPackage_Changes.sql
> fixed shipping package script

- backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice.sql
- backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice_All.sql
- backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice_PerTax.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5674410_sys_accounting_export_views.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5674420_sys_vatcode_column_added.sql
https://github.com/metasfresh/me03/issues/14270
> updated taxcode column

- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
Related to https://github.com/metasfresh/metasfresh/issues/14215
> Use planned dates and qtys in the delivery instruction

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveCUQtyToAnotherLocator.java
> #14470 fix process to be displayed only on active status

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderLineBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderLineBL.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/OnConsignmentAttributeRepository.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/OnConsignmentAttributeService.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5675090_sys_gh14484_AddOnConsignmentColumnAndAttributes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5675092_sys_gh14484_AddProcessAndSchedulerToUpdateStorageMonths.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/AstractMonthsUpdateStrategy.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/AttributeUpdater.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/HUWithExpiryDatesRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/HUWithExpiryDatesService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/UpdateAttributesHelper.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/UpdateMonthsResult.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/UpdateMonthsUntilEndStorageCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/UpdateMonthsUntilExpiryCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/process/M_HU_Update_MonthsUntilExpiry_Attribute.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/process/M_HU_Update_MonthsUntilStoragePeriodEnds_Attribute.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
#14484 Implement Goods on consignment management
> #14484 Implement Goods on consignment management

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getOverdueInvoicesWithOpenOrders.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5675590_sys_gh14408_getOverdueInvoicesWithOpenOrders.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5675600_sys_gh14408_getOverdueInvoicesWithOpenOrders_AD_Process.sql
https://github.com/metasfresh/metasfresh/issues/14408
> Overdue with open orders list 

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5675650_gh14500_cl_usage_view_and_functions.sql
> #14500 script fixes

- backend/de.metas.deliveryplanning.base/src/main/sql/postgresql/system/43-de.metas.deliveryplanning/5676020_sys_gh14881_make documentNo optional.sql
https://github.com/metasfresh/metasfresh/issues/14481
> #14481 build fix

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/BankStatementDocumentHandler.java
#14514 Use proper for Bankstatement
> #14514 Fix org

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_DocType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_DocType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocBaseType.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5674570_sys_gh14492_generate_shortage_overage_process.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5674580_sys_gh14492_shortage_overage_document_types.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5675850_sys_gh14492_adjust_physical_inventory_window.sql
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningReceiptInfo.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/process/M_Delivery_Planning_GenerateShortageOverage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/HUsForInventoryStrategies.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/HuForInventoryLineFactory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/ShortageAndOverageStrategy.java
https://github.com/metasfresh/metasfresh/issues/14492
> deliveryplanning shortage overage

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5675090_sys_gh14484_AddOnConsignmentColumnAndAttributes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5675820_sys_gh14506_InvoiceAdditionalText.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5675830_sys_gh14506_IsNotShowOriginCountry.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5676030_sys_gh14506_AggregationItem.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceHeader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
https://github.com/metasfresh/metasfresh/issues/14506
> Gh14506 ab master

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676310_sys_gh14492_physical_inventory_virtual_column_fix.sql
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/process/M_Delivery_Planning_GenerateShortageOverage.java
https://github.com/metasfresh/metasfresh/issues/14492
> fix virtual columns

- backend/de.metas.acct.base/src/main/java/de/metas/acct/AcctModuleInterceptor.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/model/validator/C_AcctSchema.java
#13636 Allow having only org restriction for primary accounting schema too
> 🍒 FROM https://github.com/metasfresh/metasfresh/pull/13636

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.order/5676220_sys_gh14881_Fix_Trls_for_CreatePOFromSOProcess.sql
https://github.com/metasfresh/metasfresh/issues/14478
> #14478 fix DatePromised TRLs for Create PO from SO process

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5676510_sys_gh14537_Moving_Average_Invoice_Costing_Method.sql
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_CostElement.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_CostElement.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/costing/CostingMethod.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676430_sys_gh14408_Section_Group_Partner_CreditIndicators.sql
https://github.com/metasfresh/metasfresh/issues/14408
> Adorable badger uat credit limit section group

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676530_sys_gh14492_add_process_shortOver_to_quickaction.sql
https://github.com/metasfresh/metasfresh/issues/14492
> add process shortOver to quickactions

- backend/de.metas.handlingunits.base/src/main/java/de/metas/inventory/impexp/InventoryImportProcess.java
https://github.com/metasfresh/metasfresh/issues/14542
> when importing products, prevent summing up qties for different products

- backend/de.metas.deliveryplanning.base/src/main/sql/postgresql/system/43-de.metas.deliveryplanning/5676590_sys_gh14881_add_export_Process_to_quickActions.sql
https://github.com/metasfresh/metasfresh/issues/14481
> #gh14881: add to quickActions export

- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningCreateRequest.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/GenerateIncomingDeliveryPlanningCommand.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/GenerateOutgoingDeliveryPlanningCommand.java
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/DeliveryPlanningGenerateProcessesHelper.java
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/M_Delivery_Planning_GenerateReceipt.java
https://github.com/metasfresh/metasfresh/issues/14541
> Adorable badger uat issue receipt precondition

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getCreditLimitForSectionGroupPartner.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getDeliveryCreditUsedPercentForSectionGroupPartner.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getSOCreditUsedPercentForSectionGroupPartner.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676630_sys_gh14408_Section_Group_BPartner_CreditLimit_WithoutDepartment.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676650_sys_gh14408_Section_Group_BPartner_CreditLimit_VirtualColumns.sql
https://github.com/metasfresh/metasfresh/issues/14408
> Adorable badger uat section group partner credit limit indicators 

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/translation/api/IElementTranslationBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/translation/api/impl/ElementTranslationBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/QueryLimit.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/validator/sql_migration_context_info/interceptor/AD_Process_Para.java
- backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_OverrideDueDate.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceDAO.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceDAO.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5676789_sys_gh14552_create_C_Invoice_DueDate.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5676790_sys_gh14552_create_DueDateOverride_process.sql
https://github.com/metasfresh/metasfresh/issues/14552
> #14552 create C_Invoice_OverrideDueDate process

- backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_OverrideDueDate.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5677020_sys_gh14552_add_to_quickActions_reword_error_msg.sql
https://github.com/metasfresh/metasfresh/issues/14552
> #14552 C_Invoice_OverrideDueDate allow only single selection, reword error message to reflect that, add process to quickactions

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5677020_sys_gh14552_add_to_quickActions_reword_error_msg.sql
https://github.com/metasfresh/metasfresh/issues/14552
> #14552 fix typo

- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceDAO.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5677060_sys_gh14458_UC_invoice_externalId.sql
> make sure to prevent payable invoices with duplicated externalIds

- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
https://github.com/metasfresh/metasfresh/issues/14408
>  only apply delivery credit limit to outgoing delivery instructions 

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_PaymentTerm.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_PaymentTerm.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/C_Invoice_v.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676920_sys_gh14569_AddDueDateInInvoice.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676925_sys_gh14569_Adjust_c_invoice_v.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5676927_sys_gh14569_MigrateDueDate.sql
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/IPaymentTermRepository.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/api/impl/InvoiceSourceBL.java
- backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/model/validator/C_Invoice.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceHeader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/process/params/InvoicingParams.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestFixedDateInvoicedAndDateAcct.java
#14569 Generate Invoice with Allowing Override Due Date
> #14569 Generate Invoice with Allowing Override Due Date

- backend/de.metas.business/src/main/sql/postgresql/ddl/views/Creditlimit_Usage_V.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5677180_sys_gh14500_cl_usage_adj.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5677190_gh14500_update_cl_usage_view.sql
> #14500 cl usage feedback fixes

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5670900_add_M_Locator_ID_to_WEBUI_M_HU_MoveToAnotherWarehouse_processes.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse_ExclQuarantined.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse_InclQuarantined.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse_Template.java
- backend/de.metas.util/src/main/java/de/metas/util/collections/CollectionUtils.java
> add M_Locator_ID to WEBUI_M_HU_MoveToAnotherWarehouse processes

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Locator.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Locator.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessor.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessorsHub.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/DeviceConfig.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/SysConfigDeviceConfigPool.java
- backend/de.metas.device.api/pom.xml
- backend/de.metas.device.api/src/main/java/de/metas/device/api/hook/RunParameters.java
- backend/de.metas.device.scales/src/main/java/de/metas/device/scales/impl/soehenle/SendTargetWeightHook.java
- backend/de.metas.device.scales/src/main/java/de/metas/device/scales/impl/soehenle/SoehenleSendTargetWeightRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/sourcehu/interceptor/M_HU.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5677150_sys_gh14582_OnlyClearedHUs_DeviceScale_Config.sql
- backend/de.metas.util/src/main/java/de/metas/util/collections/CollectionUtils.java
refs: https://github.com/metasfresh/metasfresh/issues/14582
> Hus in zur Prüfung können in Produktion benutzt werden

- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/interceptor/M_ShipperTransportation.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5677860_sys_gh14632_add_C_Invoice_Candidate_ActualLoadingDate.sql
https://github.com/metasfresh/metasfresh/issues/14632
> #14632 add C_Invoice_Candidate.ActualLoadingDate and populate from earliest M_ShipmentTransportation.LoadingDate

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getOverdueInvoicesWithOpenOrders.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5678060_sys_gh14500_Adjust_getOverdueInvoicesWithOpenOrders.sql
> Gh14500 fix overdue with open orders

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/activity/C_Activity_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/activity/C_Activity_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/dataImport/C_DataImport_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/iinvoicecandidate/I_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/dataImport/importInvoiceCandidate.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_I_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_I_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/NewManualInvoiceCandidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/CInvoiceCandidateImportTableSqlUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/ImportInvoiceCandidatesService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5678630_sys_gh14652_I_Invoice_Candidate_C_Activity_columns.sql
Import Data File with ActivityValue
https://github.com/metasfresh/metasfresh/issues/14652
> Import Data File with C_Activity

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLineRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataLoader.java
> Sort by HuId

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/CreateDraftIssuesCommand.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5675270_sys_gh14493_cleanup_M_Source_HU.sql
> make sure that HUs are removed from sourceHU when draft-issued

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5679120_sys_gh14645_UseDefaultBillToLocationAsOrderDefaultLocation_sys_config.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
automatically mark order as DropShip if dropShip warehouse was selected
> Order Window Ivict adaptions (Billto Default, Drop Shipment)

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5679120_sys_gh14645_UseDefaultBillToLocationAsOrderDefaultLocation_sys_config.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
* refs: https://github.com/metasfresh/metasfresh/issues/14645 automatically mark order as DropShip if dropShip warehouse was selected & use BillToDefaultLocation as order default loc based on sys config
> Order Window Ivict adaptions (Billto Default, Drop Shipment) (#14646)

- backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice_All.sql
- backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice_PerTax.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5679140_sys_gh14679 _fix_counterpart_links_RV_DATEV_Export_Fact_Acct_Invoice.sql
in fact, not all fact_acct have Counterpart_Fact_Acct_ID set at all (see comments in the SQL)
#14679
> not all fact_acct counterparts are joined in both directions

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5679210_sys_gh14446_set_IsReplicationTrxFinished_column.sql
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5679190_sys_gh14446_C_OLCand_ReplicationTrx_filter_columns_mf.sql
> refs https://github.com/metasfresh/metasfresh/issues/14446 filter columns (#14681)

- backend/de.metas.async/src/main/sql/postgresql/ddl/view/de.metas.async/C_Queue_Processing_Stats_V.sql
- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5678180_sys_gh14647_create_view_c_queue_processing_stats_v.sql
https://github.com/metasfresh/metasfresh/issues/14647
> Create diagnostic view for c_queue_workpackage

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/impl/JsonInvoiceService.java
make sure that invoice type matches provided trx
> Make sure that invoice type matches trx

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/impl/JsonInvoiceService.java
make sure that invoice type matches provided trx
> Integrate adorable_badger_uat to master

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5679420_sys_gh14683_C_BPartner_BlockStatus_fix_trl.sql
refs: https://github.com/metasfresh/metasfresh/issues/14683
> Fix Order with blocked partner trl

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/QueryHelper.java
https://github.com/metasfresh/metasfresh/issues/14706
> Gh12478 api call fix (#14695)

- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/ordersimport/ecosio/EcosioOrdersRoute.java
https://github.com/metasfresh/metasfresh/issues/14731
> ignore the incoming DeliveryRule, see comment

- backend/de.metas.business/src/main/java/de/metas/bpartner/blockstatus/interceptor/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/blockstatus/interceptor/C_Order.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/blockstatus/interceptor/M_InOut.java
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/DeliveryPlanningGenerateProcessesHelper.java
refs: https://github.com/metasfresh/metasfresh/issues/14683
> fix block b partner

- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
use billToDefault location as default location, no matter if SO is dropship or not
> use billToDefault location no matter if SO is dropShip or not

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/adapter/IDocumentBillLocationAdapter.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
* #14686
* Do not set Rendered address if is null; This shall be rendered.
---------
> #14686 (#14687)

- backend/de.metas.business/src/main/java/de/metas/bpartner/blockstatus/interceptor/C_Order.java
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/DeliveryPlanningGenerateProcessesHelper.java
refs: https://github.com/metasfresh/metasfresh/issues/14683
> fix ProcessPreconditionsResolution reject

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOut.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5680490_sys_gh14764_reverse_not_possible.sql
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/customerreturns/interceptor/M_InOut.java
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/model/ServiceRepairProjectInfo.java
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/ServiceRepairProjectService.java
https://github.com/metasfresh/metasfresh/issues/14764
> reverse not possible is project still active

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5680730_sys_gh631_updated_reverse_msg.sql
https://github.com/metasfresh/td156/issues/631
> fix message when reversing

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5680550_sys_gh14709_MBankStatement_Import.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaymentRequestBL.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MPayment.java
- backend/de.metas.business/src/main/java/de/metas/allocation/api/IAllocationDAO.java
- backend/de.metas.business/src/main/java/de/metas/allocation/api/impl/AllocationDAO.java
- backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_MassDiscountOrWriteOff.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceDAO.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceDAO.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
- backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/api/impl/ESRImportBLTest.java
refs: https://github.com/metasfresh/metasfresh/issues/14709
> CR042 mbank (Poland bank data)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/processing/ImportRecordsSelection.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/blockstatus/BPartnerBlockStatusImportProcess.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/blockstatus/impl/IBPartnerBlockStatusDAO.java
propagated the changes around updated/inserted row to UI
> refs: https://github.com/metasfresh/metasfresh/issues/14721

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/processing/ImportRecordsSelection.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/blockstatus/BPartnerBlockStatusImportProcess.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/blockstatus/impl/IBPartnerBlockStatusDAO.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/MovingAverageInvoiceCostingMethodHandler.java
propagate the changes around updated/inserted failed rows to UI
> Integrate adorable_badger_uat 

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankStatementBL.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentBL.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentDAO.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java
refs: https://github.com/metasfresh/metasfresh/issues/14709
> fix currency conversion type id

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
> Mi intensive care hotfix

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5681540_sys_gh14835_ConsiderAttributes.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationService.java
https://github.com/metasfresh/metasfresh/issues/14835
> Manage filtering with attributes in HU reservation screen

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
https://github.com/metasfresh/metasfresh/issues/14837
> Fix failing cucumber test

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/tax_accounting_report_details.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/tax_accounting_report_details_sum.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/taxaccountsonly_details.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5681690_sys_gh14753_AddTaxbaseAmtColumn.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_details_sum.jrxml
> #14753 Fix Tax accounting v3  

- .mergify.yml
- .testspace.yml
This change has been made by @metas-ts from Mergify config editor.
> ci(Mergify): configuration update

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5681590_sys_gh14843_PreventReciptIfMissingDeliveryInstructions_sysConfig.sql
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/DeliveryPlanningGenerateProcessesHelper.java
https://github.com/metasfresh/metasfresh/issues/14843
> Do not prevent Goods Receipt if missing delivery instructions

- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/export/ExportToExternalSystemService.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/other/export/project/budget/ExportBudgetProjectToOtherService.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/other/export/project/workorder/ExportWorkOrderProjectToOtherService.java
- misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/error/ErrorProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/common/src/test/java/de/metas/camel/externalsystems/common/error/ErrorProcessorTest.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/ErrorReportRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/test/resources/de/metas/camel/externalsystems/core/to_mf/0_LogMessageRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/restapi/GRSRestAPIRouteBuilder.java
create AD_Issue if API call for exporting WOSteps fails
> Change /SaveSollData requestBody and create AD_Issue if call fails

- backend/de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java/de/metas/server/config/SwaggerConfig.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/config/SwaggerConfig.java
- backend/de.metas.util.web/src/main/java/de/metas/util/web/SwaggerUtil.java
- backend/de.metas.vertical.pharma.msv3.server/src/main/java/de/metas/vertical/pharma/msv3/server/SwaggerConfig.java
- backend/metasfresh-webui-api/src/main/resources/application.properties
- misc/dev-support/application.properties/metasfresh/backend/metasfresh-dist/serverRoot/application.properties
- misc/dev-support/application.properties/metasfresh/backend/metasfresh-webui-api/application.properties
https://github.com/metasfresh/metasfresh/issues/14856
> Springdoc authorisation and visualisation adjustemnts

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5681880_fix_Fact_Acct_reference_for_other_baselang.sql
https://github.com/metasfresh/metasfresh/pull/14636
> fix Fact_Acct reference for other baselanguages

- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
https://github.com/metasfresh/he132/issues/797
> fixed npe 

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5681890_sys_gh14718_C_BankStatement_MSectionCode.sql
refs https://github.com/metasfresh/metasfresh/issues/14718
> add section code to c_bankstatement

- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
https://github.com/metasfresh/ic114/issues/1662
> cherry pick npe fix

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/paymentAllocatedAmt.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/paymentAvailable.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/ddl/functions/getopenpayments.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5681940_gh14909_avoid_having_payment_with_0_openamt.sql
> Gh14909 avoid having payment with 0 openamt when allocating

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/paymentAllocatedAmt.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/paymentAvailable.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5681940_gh14909_avoid_having_payment_with_0_openamt.sql
* #14909 avoid  having payment with  0 open amount when allocating
* #14909 avoid  having payment with  0 open amount when allocating
* #14909 review fixes
* #14909 review fixes
* #14909 review fixes
> Gh14909 avoid having payment with 0 openamt when allocating (#14910)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/purchaseOrder/purchaseOrderQty.feature
refs: https://github.com/metasfresh/metasfresh/issues/14847
> Fix cucumber-errors in the master branch

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pporder/PP_Order_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaProduction.feature
https://github.com/metasfresh/metasfresh/issues/14856
> Master java14 fix cucumber

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/ReverseDraftIssues.java
https://github.com/metasfresh/metasfresh/issues/14954
> isHuOrAnyParentSourceHu test

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/dao/selection/QuerySelectionHelper.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/IQueryInsertExecutor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/GuaranteedPOBufferedIterator.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/IQueryInsertFromColumn.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/POBufferedIterator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandidatesChangesChecker.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/NullInvoiceCandidatesChangesChecker.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidatesChangesChecker.java
Reverts metasfresh/metasfresh#14703
These fixes are in the `_uat` branch but were never deployed to prod.
Planned next steps: 
- integrate this PR
- merge `_hotfix` into `_uat` using `git merge -s ours hard_encoded_hotfix` (thx to https://stackoverflow.com/questions/71864916/git-merge-completely-ignore-one-branch-changes)
> Revert "Make sure that ICs are always enqueued in their intended order (_hotfix)"

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/strategy/UniformAllocationStrategy.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/strategy/UniformAllocationStrategyTest.java
https://github.com/metasfresh/metasfresh/issues/14542
> #14542 prevent overallocation when using UniformAllocationStrategy

- misc/services/procurement-webui/procurement-webui-backend/src/main/java/de/metas/procurement/webui/Application.java
https://github.com/metasfresh/metasfresh/issues/14856
> fix procurement webui swagger

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5682510_sys_gh14980_set_invoice_duedate_as_defualt_for_set_overdue_process_parameter.sql
> #14980 set invoice due date as default value for Override Due Date Process parameter

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/view_source/ViewSourceCacheInvalidateRequestFactoryGroup.java
QA for
* https://github.com/metasfresh/metasfresh/pull/14998
> hotfix Reports server not starting (QA)

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/ProductRestService.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/product/ProductsRestControllerTest.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/product/qualityattribute/M_Quality_Attribute_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/productRestController.feature
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5682160_sys_gh14971_AgricultureOrigin_QualityAttributes.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/org/compiere/model/I_M_Quality.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/org/compiere/model/I_M_Quality_Attribute.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/org/compiere/model/X_M_Quality.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/org/compiere/model/X_M_Quality_Attribute.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/quality/attribute/ProductQualityAttributeLabels.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/quality/attribute/ProductQualityAttributeRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/quality/attribute/QualityAttributeLabel.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/quality/attribute/QualityAttributeService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/quality/attribute/SaveQualityAttributeRequest.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/JsonQualityAttribute.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestProduct.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestUpsertQualityAttribute.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/GRSSignumConstants.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/bom/processor/PushProductProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/helper/JsonRequestHelper.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/product/processor/PushRawMaterialsProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBOM.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBOMAdditionalInfo.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonProduct.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBOMTest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/bom/0_JsonBOM.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/bom/10_ProductUpsertCamelRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/product/10_ProductUpsertCamelRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/product/1_JsonProduct.json
* link QualityAttributes sent from GRS to product (both BOMs & RawMaterials) refs: https://github.com/metasfresh/metasfresh/issues/14971
> GRS Interface - Transfer Bio Label (#14977)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/OpenItems_Excel_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5683080_sys_gh14891_OpenItems_Excel_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5683090_sys_gh14891_OpenItems_Excel_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5683160_sys_gh14891_OpenItems_Excel_Report.sql
https://github.com/metasfresh/metasfresh/issues/15013
> Adding new process Offene Posten (Excel)

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/menu/datatypes/json/JSONMenuNode.java
follow-up of 
* https://github.com/metasfresh/metasfresh/pull/15033
> webui menu: hide empty groups (part 2)

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc.java
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5683380_sys_gh15046_BankAccount_GainLoss.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5683680_sys_gh15046_UpdateExistingBankAccounts.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5683690_sys_gh15046_BankAccount_GainLoss_Mandatory.sql
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BP_BankAccount_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BP_BankAccount_Acct.java
- backend/de.metas.business/src/main/java/de/metas/banking/accounting/BankAccountAcct.java
- backend/de.metas.business/src/main/java/de/metas/banking/accounting/BankAccountAcctRepository.java
- backend/de.metas.business/src/main/java/de/metas/banking/accounting/BankAccountAcctType.java
refs: https://github.com/metasfresh/metasfresh/issues/15046
> CR042 mbank (Poland bank data) - AC4

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
refs: https://github.com/metasfresh/metasfresh/issues/15007
> update currency rate

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5684130_sys_gh14602_fix_calculationmethod_column_length.sql
> #14602 fix column length

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/ConversionTypeMethod.java
https://github.com/metasfresh/metasfresh/issues/15049
> fix ConversionTypeMethod not found

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5684510_sys_gh15086_JobRouter_Instance_ID.sql
https://github.com/metasfresh/metasfresh/issues/15086
> Add `Externe ID` in PO-SO invoices

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684700_sys_gh15049_adjust_desc.sql
https://github.com/metasfresh/metasfresh/issues/15049
> adjust descriptions

- backend/de.metas.business/src/main/java/de/metas/order/location/adapter/OrderHandOverLocationAdapter.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOFromSOsAggregator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/document/counterDoc/C_Order_CounterDocHandler.java
https://github.com/metasfresh/metasfresh/issues/15095
> When creating a Counter Doc for C_Order, take into account the HandOver informations

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Allocation.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/sap/export/AcctDocumentInfoProvider.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/sap/export/interceptor/C_AllocationHdr.java
refs https://github.com/metasfresh/metasfresh/issues/14718
> payment & payment allocation

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5684980_sys_gh15095_HandOver_Element_Trl.sql
https://github.com/metasfresh/metasfresh/issues/15095
> Translate the `Übergabe` checkbox in the en_US

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5685040_sys_gh15049_romania_currency_rol_to_ron.sql
https://github.com/metasfresh/metasfresh/issues/15049
> romania currency ROL to RON

- backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStepService.java
refs https://github.com/metasfresh/metasfresh/issues/15056
> skip already processed simulation plans

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5684730_sys_gh15100_Handle_Multiple_SalesRep.sql
refs https://github.com/metasfresh/metasfresh/issues/15100
> adapt to existing column from private repo

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5684730_sys_gh15100_Handle_Multiple_SalesRep.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5685670_sys_gh15100_Handle_Multiple_SalesRep.sql
refs https://github.com/metasfresh/metasfresh/issues/15100
> fix SalesRep_ID ColumnSQL

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5685690_sys_gh15163_display_incoterm_incotermlocation_so_window.sql
> #15163 display Incoterm/Incoterm Location in SO window

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5685790_sys_gh15163_fix_incoterm_location_translation.sql
> #15163 fix Incoterm Location translation

- misc/services/camel/de-metas-camel-externalsystems/core/src/main/resources/application.properties
https://github.com/metasfresh/metasfresh/issues/14856
> fix external systems

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5686060_sys_gh15116_ReversePostingSign.sql
https://github.com/metasfresh/metasfresh/issues/15116
> Update the Copy GLJournal process

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5686100_sys_gh15163_fix_incoterm_location_translation.sql
> #15163 display IncotermLocation in PO window too

- frontend/src/assets/css/letter.css
https://github.com/metasfresh/metasfresh/issues/15184
> Increase field length for letter selection

- backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/MainValidator.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/printing/impl/FlatrateTermPrintingQueueHandler.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/spi/impl/DocumentPrintingQueueHandler.java
> #15201 Set Drop ship partner and location from from flatrate term when creating printing queue 

- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java
https://github.com/metasfresh/metasfresh/issues/15208
> `Remit-To Address` is set to `N` after api/v2/forum-datenaustausch.ch/importInvoiceXML

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/ICurrencyBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/ICurrencyDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/impl/CurrencyBL.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/callout/C_BankStatementLine.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.business/src/main/java/de/metas/money/MoneyService.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
...if it's not specified.
(currently, Spot is hardcoded used in that case)
> When converting currencies, use the default conversion-type

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/CreateInvoiceCandidatesService.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/invoicecandidates/impl/JsonInsertInvoiceCandidateServiceTest.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/IPaymentTermRepository.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermQuery.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_Review_StepDef.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/NewManualInvoiceCandidate.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inout/invoicecandidate/M_InOutLine_HandlerTest.java
- might be bugs - mostly not taken into account that C_Invoice_Candidte.PaymentTerm_ID is not mandatory
- might tests that still need to be fixed/adopted
> Fix remaining test problems

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/IUserBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/IUserDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/impl/UserBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/impl/UserDAO.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderMapper.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/project/CreateWOProjectRequest.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/project/WOProjectRepository.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/project/workorder/JsonWorkOrderProjectUpsertRequest.java
refs: https://github.com/metasfresh/metasfresh/issues/15274
> Prüfauftrag - Fachberater wird nicht angezeigt

- misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/WorkOrderProjectRouteBuilder.java
...to be in line with the API's expected method
> Fix the REST-API method to PUT

- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- misc/dev-support/docker/infrastructure/env-files/mad_orange_uat.env
added reference and invoiceid to the error msg
https://github.com/metasfresh/metasfresh/issues/15319
> Adding reference and invoiceid to the error msg

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/impl/JsonInvoiceService.java
- backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/v2/invoice/JsonCreateInvoiceRequestItemHeader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/ManualInvoiceRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/ManualInvoiceService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/request/CreateInvoiceRequestHeader.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/request/CreateManualInvoiceRequest.java
refs: https://github.com/metasfresh/metasfresh/issues/15260
> SAP FI interface: GL entries to be NOT interfaced into SAP

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/process/M_ShipmentSchedule_Unpick.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5688160_sys_gh15331_UnpickHU_process.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5688210_sys_gh15331_AD_Message_Unpick.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ShipmentScheduleQtyPickedId.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
refs: https://github.com/metasfresh/metasfresh/issues/15331
> B2b: Kommisionierung rückgängig machen

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5688420_sys_Increase_Product_Name_TRL_Length.sql
make m_product.name & m_product_trl.name have the same length once again
> mad_orange_uat_fix_mproduct_name_size

- backend/de.metas.business/src/main/sql/postgresql/ddl/functions/end_of_quarter.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5688560_cli_gh15355_end_of_quarter.sql
> provide end of quarter db function

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/customerreturns/RepairCustomerReturnsService.java
#15360 Set the proper locator in HU when doing customer return - service repair
> #15360 Set Proper locator for service Repair HUs

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Requisition.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_RequisitionLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Requisition.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_RequisitionLine.java
- backend/de.metas.business/src/main/java/de/metas/requisition/interceptor/M_RequisitionLine.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/request/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Request_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Request_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Request_Root.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5688520_sys_gh15370_Purchase_Requisition_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5688600_sys_gh15370_Purchase_Requisition_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5688620_sys_gh15370_Purchase_Requisition_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5688780_sys_gh15370_Purchase_Requisition_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5689210_sys_gh15370_Docs_Purchase_Request_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5689220_sys_gh15370_Docs_Purchase_Request_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5689230_sys_gh15370_Docs_Purchase_Request_Root.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5689250_sys_gh15370_Purchase_Requisition_Report.sql
https://github.com/metasfresh/metasfresh/issues/15370
> Gh15370 purchase requisition window

- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/DocLine_CostCollector.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/Doc_PPCostCollector.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderCost.java
#15414 When cost collector is component issue type, the qty shall be negative
> #15414 Fix Cost detail when Issuing 

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/remote/RabbitMQEventBusConfiguration.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5684990_sys_gh15086_JobRouter_Instance_ID.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5684991_sys_gh15086_Fix_Existing_AD_InputDataSource_IDs.sql
I think this might solve our occasional ordering problem
> remove code that binds also a DirectExchange to one queue

- backend/de.metas.business/src/main/java/de/metas/letters/model/MADBoilerPlate.java
refs https://github.com/metasfresh/metasfresh/issues/15403
> Option to create letters from different windows

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5689960_sys_gh15414_deactivate_avg_rolling_costElement.sql
It was implemented for a project that did not use production #15414
> Deactivate the moving average cost element

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/IHUPickingSlotDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/impl/HUPickingSlotBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/impl/HUPickingSlotDAO.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5690030_sys_gh15450_HUAlreadyOnPickingSlot_Custom_Error_Message.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5690035_sys_gh15450_M_PickingSlot_HU_unique_index.sql
refs https://github.com/metasfresh/metasfresh/issues/15450
> Enforce one picking slot assignment per HU

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/OnOverDelivery.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/requests/ProcessPickingRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/PickingConfig.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Pick_ReceivedHUs.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/util/ProcessPickingRequest.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/util/WEBUI_PP_Order_ProcessHelper.java
refs: https://github.com/metasfresh/metasfresh/issues/15445
> B1: picking of complete quantity in prod-order not possible

- backend/de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5690050_sys_gh15445_OverDeliveryErrorMessage.sql
refs https://github.com/metasfresh/metasfresh/issues/15445
> over delivery not allowed error message

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentSchedule.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_ShipmentSchedule.java
Also in shipmentSchedule.feature
- extend the existing scenario to cover disposal
- change identifier names to be clearer and avoid collisions
> Update shipment schedules also when DeliveryDate_Override is changed

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5690300_sys_gh15447_role_access_add_process_recursively.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5690310_sys_gh15447_role_access_add_window_recursively.sql
https://github.com/metasfresh/metasfresh/issues/15447
> Add access to menu recursively for a Role

- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/model/interceptor/M_Product.java
- backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5690420_sys_gh15452_add_product_used_message.sql
> #15452 prevent changing UOM of a used product

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5690570_sys_gh15471_fix_tax_code_translation.sql
> fix tax code translation

- .github/workflows/cicd.yaml
(cherry picked from commit 2de89b4a98054b0089a6dbca4ceb285045cd6936)
> attempt to fix failing cucumber build

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5690790_sys_gh15516_Is_Dunning_Candidate_Flag_Business_Partner_Contact.sql
- backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DefaultDunningCandidateProducer.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15516
> Dunning Mails to seperate Mail address

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/Fact_Acct_Transactions_View.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5690960_sys_gh15471_remove_taxcode_Fact_Acct_Transactions_View.sql
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_Fact_Acct_Transactions_View.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_Fact_Acct_Transactions_View.java
> regenerate model and fix script

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_Contract_Module_Log.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_Contract_Module_Log.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5690840_sys_gh15549_add_data_structure_contract_module_log.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5691010_sys_gh15549_add_window_contract_module_log.sql
> Gh15549 new window vertragsbaustein log

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5691250_sys_gh15565_ModularContractSettings.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5691330_sys_gh15565_ModulSettings_ModuleType.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5691350_sys_gh15565_FlatrateConditions_ModularContractSettings_ID.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5691610_sys_gh15565_C_ModuleSettings_InvoicingGroup_Values.sql
refs: https://github.com/metasfresh/metasfresh/issues/15565
> New Window: Modular contract settings

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
small fix on bpartner location upsert via api
> small jasonpersisterservice fix

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Saldobilanz_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5691740_sys_gh15531_ImproveSaldobilanzReport.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5691750_sys_gh15531_UpdateParametersTrl.sql
#15531 Add a generic name, "NA" when there is no activity, or product
> #15531 Add a generic name, "NA" when there is no activity, or product

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5691540_sys_gh15576_Add_Relation_Type_Links.sql
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15576
> [Purchase_housekeeping 2] reference additional documents

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/compiere/util/CtxNames.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/M_Product_Lookup_V.sql
- backend/de.metas.business/src/main/java/de/metas/invoice/callout/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5691390_sys_gh15545_Create_Do_Not_Display_Availability_Info_Sys_Config.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5691460_sys_gh15545_Create_Filter_Products_Without_Section_Code_Sys_Config.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5691465_sys_gh15545_UpdateProduct_V.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15545
> [Purchase_housekeeping 1] Purchase order

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5691075_sys_gh_15528_add_translations_for_AllocateToFEC_process.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5691075_sys_gh15528_add_translations_for_AllocateToFEC_process.sql
https://github.com/metasfresh/metasfresh/issues/15528
> [Sales_housekeeping 4] Allocating FEC: fix base language TRL on AD_Process_Para

- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
- backend/de.metas.deliveryplanning.base/src/main/sql/postgresql/system/43-de.metas.deliveryplanning/5691980_sys_generate_goods_issue_adjustments.sql
- backend/de.metas.deliveryplanning.base/src/main/sql/postgresql/system/43-de.metas.deliveryplanning/5692040_sys_deliveryplanning_releaseno_readonly.sql
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/DeliveryPlanningGenerateProcessesHelper.java
- backend/de.metas.deliveryplanning.webui/src/main/java/de/metas/deliveryplanning/webui/process/M_Delivery_Planning_GenerateShipment.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleEffectiveBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleEffectiveBL.java
- Limit goods issue by qtyonhand instead of qtytodeliver
- new format for releaseno
- releaseno readonly
> goods issue and release no changes

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5692210_sys_gh15653_UserElementDate1_UserElementDate2.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5692450_sys_gh15653_Fact_Acct_Transactions_View.sql
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_AcctSchema_Element.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_InvoiceLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_ValidCombination.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_Fact_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_AcctSchema_Element.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_InvoiceLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_ValidCombination.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_Fact_Acct.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MAccount.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AccountDimension.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AcctSchemaElementType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AccountDimensionValidator.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AcctSegmentType.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/expression/api/impl/LogicExpressionsDatabase.java
- backend/de.metas.business/src/main/java/de/metas/document/dimension/Dimension.java
- backend/de.metas.business/src/main/java/de/metas/document/dimension/InvoiceLineDimensionFactory.java
- backend/de.metas.business/src/main/java/org/adempiere/acct/api/impl/FactAcctBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/document/dimension/InvoiceCandidateDimensionFactory.java
refs: https://github.com/metasfresh/metasfresh/issues/15653
> Datefields in InvoiceCandidates

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692750_sys_gh15662_Update_IsBetaFunctionality_Flag_To_N_For_Dunning_Window_540155.sql
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15662
> Dunning windows - set IsBetaFunctionality=NO

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerBankAccountImportHelper.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerLocationImportHelper.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692590_sys_bpgroup_name_and_value_length_to_120.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692660_sys_extend_i_bpartner.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692700_sys_bpartner_name_length_to_120.sql
- add accountno, accountowner, lacationBPartnerName, locationName to BPartner Import
> extend bpartner import

- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerLocationImportHelper.java
- fix location name not set on on location update https://github.com/metasfresh/metasfresh/pull/15664
> fix bpartner import

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692920_sys_gh15672_Housekeeping_References_Iteration_3.sql
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15672
> Housekeeping references - Iteration 3

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5693080_sys_gh15690_it_IT_SystemLanguage.sql
refs: https://github.com/metasfresh/metasfresh/issues/15690
> Add/ Prepare language it_IT as system language

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5693270_sys_doc_type_sequence_desc.sql
- backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/sequence/InvoiceCountryIdProvider.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_Sequence_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_Sequence_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/seqNo/AD_Sequence_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/seqNo/AD_Sequence_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/docNo/countryBasedDocTypeSequence.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.invoice/5692900_sys_invoice_add_c_tax_departure_country_id.sql
- Sales Invoice window tax departure country
- country based docNo tax departure country instead of billTo country
- country based docNo cucumber
> country based docno tax departure country

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5693270_sys_doc_type_sequence_desc.sql
- backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/sequence/InvoiceCountryIdProvider.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_Sequence_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_Sequence_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/seqNo/AD_Sequence_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/seqNo/AD_Sequence_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/docNo/countryBasedDocTypeSequence.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.invoice/5692900_sys_invoice_add_c_tax_departure_country_id.sql
https://github.com/metasfresh/metasfresh/pull/15697
- Sales Invoice window tax departure country
- country based docNo tax departure country instead of billTo country
- country based docNo cucumber
> country based docno tax departure country (#15697)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTab.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IProcessPreconditionsContext.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/process/ui/AProcessModelTest.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/mailrecipient/process/C_Doc_Outbound_Log_SendPDFMails.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/storage/attachments/process/C_Doc_Outbound_Log_StoreAttachments.java
- backend/de.metas.edi/src/main/java/de/metas/edi/process/EDIExportDocOutboundLog.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/process/M_ShipmentSchedule_EnqueueSelection.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipping/process/PrintAllShipmentDocuments.java
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/process/MD_Candidate_Request_MaterialDocument.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/process/C_PurchaseCandiate_Create_PurchaseOrders.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/process/C_PurchaseCandiate_Mark_Processed.java
- backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/process/M_ShipperTransportation_SendDerKurierEMail.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_Close.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_ReOpen.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ShipmentSchedule_OpenProcessed.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveCUs.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/DocumentPreconditionsAsContext.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/ViewAsPreconditionsContext.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/DefaultView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IViewDataRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
refs: https://github.com/metasfresh/metasfresh/issues/15736
> Avoid OOME

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/gplr/report_lines.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/gplr/report_purchaseorders.jrxml
Show delivery terms and replace header field
> Adjust report

- backend/de.metas.business/src/main/java/de/metas/requisition/RequisitionId.java
- backend/de.metas.business/src/main/java/de/metas/requisition/RequisitionRepository.java
- backend/de.metas.business/src/main/java/de/metas/requisition/RequisitionService.java
- backend/de.metas.business/src/main/java/de/metas/requisition/callout/M_Requisition.java
- backend/de.metas.business/src/main/java/de/metas/requisition/callout/M_RequisitionLine.java
- backend/de.metas.business/src/main/java/de/metas/requisition/interceptor/M_RequisitionLine.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692770_sys_gh15694_adjust_purchase_request_window_iteration_2.sql
> 15694 fenster bestellanforderung iteration 2

- backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/util/lang/All_RepoIdAware_Classes_Test.java
https://github.com/metasfresh/metasfresh/pull/15695
https://github.com/metasfresh/metasfresh/issues/15694
> fix junit requisition

- backend/de.metas.acct.base/src/main/java-gen/de/metas/acct/model/I_SAP_GLJournalLine.java
- backend/de.metas.acct.base/src/main/java-gen/de/metas/acct/model/X_SAP_GLJournalLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/gljournal_sap/interceptor/SAP_GLJournalLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/elementvalue/ElementValue.java
- backend/de.metas.acct.base/src/main/java/de/metas/elementvalue/ElementValueRepository.java
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5694600_sys_gh15802_Account_Open_Items_Flag.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5694640_sys_gh15802_Account_Open_Items_Flag.sql
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_ElementValue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_ElementValue.java
https://github.com/metasfresh/metasfresh/issues/15802
> Account Open Items flag

- backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Order.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/IModularContractTypeHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/ModularContractService.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/PurchaseOrderLineModularContractHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/modular/settings/ModularContractSettingsDAOTest.java
refs: https://github.com/metasfresh/metasfresh/issues/15783
> small refactor contract terms

- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
- backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/invoicecandidate/DeliveryPlanningICHandlerExtension.java
DeliveryPlanningICHandlerExtension: consider delivery plannings without instructions in case of soTrx = Purchase
> DeliveryPlanningICHandlerExtension: ActLoadDate from Planning docs with no Instructions

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5693850_sys_gh15693_Introduce_C_Tax_Departure_Country_ID_Column_For_Order_And_Invoice_Candidate.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Order.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15693
> [CR068] VAT code in header, tax reporting country (SO & SIC) => fix invalidate invoice candidate on order complete

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5693850_sys_gh15693_Introduce_C_Tax_Departure_Country_ID_Column_For_Order_And_Invoice_Candidate.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Order.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15693
> [CR068] VAT code in header, tax reporting country (SO & SIC) => revert

- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
refs: https://github.com/metasfresh/metasfresh/issues/15783
> allow overlapping modular contracts

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/C_Flatrate_Term_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Module_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Settings_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Type_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogInventory.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogPurchaseOrder.feature
refs: https://github.com/metasfresh/metasfresh/issues/15848
> (Bestellung -> Vertragsbaustein Log) - Create cucumbers 

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/C_Flatrate_Term_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Module_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Settings_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Type_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/createbpartner/CreateBPartnerV2_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogInventory.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogPurchaseOrder.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/interceptor/C_BPartner_Location.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/interceptor/MakeUniqueNameCommand.java
https://github.com/metasfresh/metasfresh/pull/15801 bpartner api generate location name on update if set to null
https://github.com/metasfresh/metasfresh/issues/15848 Modular Contract: PO Cucumber
> Master merge inner silence uat

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5695190_sys_gh15861_GLJournal_Description.sql
refs: https://github.com/metasfresh/metasfresh/issues/15861
> Hauptbuch Journal Anpassung Beschreibung

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Get_Section_Code_Department.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/Open_Items_Managed_V.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5695250_sys_gh15864_Get_Section_Code_Department.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5695260_sys_gh15864_Open_Items_Managed_View.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5695300_sys_gh15864_Open_Items_Managed_Table.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5695330_sys_gh15864_Open_Items_Managed_Window.sql
https://github.com/metasfresh/metasfresh/issues/15864
> Open Items (managed) window

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5694520_sys_gh16205_add_extension_not_allowed_list_value.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5694830_sys_gh16205_add_process_extend_flatrate_conditions.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5694840_cli_gh16205_add_unique_index_on_modCntr_settings.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695070_sys_gh16205_add_extension_not_alloawed_message.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695340_sys_gh16205_filter_years_by_settings_calendar.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695450_sys_gh16205_rename_process_and_fix_trls.sql
- backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Conditions.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Conditions_Extend.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Conditions_ModularContract_Clone.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/SubscriptionTermEventListener.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Conditions.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsQuery.java
> Inner silence uat gh15856 extend c flatrate conditions

- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeCommand.java
🍒 - picked from https://github.com/metasfresh/metasfresh/pull/15872
> create request for source org on bpartner org change (#15872)

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695730_sys_gh15863_remove_processAvailability_from_FEC_window.sql
refs: https://github.com/metasfresh/metasfresh/issues/15863
> remove process `C_Order_UnallocateFromForexContract` from FEC window

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/payment_allocation/InvoiceRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewBasedProcess.java
refs: https://github.com/metasfresh/metasfresh/issues/15889
> Invoices to Allocate - optimization

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695584_sys_gh15892_SectionCode_Doesnt_Match_AD_Message.sql
refs: https://github.com/metasfresh/metasfresh/issues/15892
> remove "'" from ad_message as it messes up with the parameters

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice_Rejection_Detail.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice_Rejection_Detail.java
- backend/de.metas.invoice_gateway.spi/src/main/java/de/metas/invoice_gateway/spi/model/imp/ImportedInvoiceResponse.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_440_response/src/main/java-xjc/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_440/response/PayloadType.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_440_response/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_440/response/Invoice440ToCrossVersionModelTool.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_440_response/src/test/resources/Cancelation_KV_12345.xml
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_440_response/src/test/resources/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_440/response/Invoice440ToCrossVersionModelToolTest.snap
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_response/src/main/java-xjc/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/response/PayloadType.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_response/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/response/Invoice450ToCrossVersionModelTool.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_response/src/test/resources/Cancelation_KV_12345.xml
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_response/src/test/resources/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/response/Invoice450ToCrossVersionModelToolTest.snap
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/export/invoice/InvoiceImportClientImpl.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/imp/InvoiceRejectionDetailRepo.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/sql/postgresql/system/75-vertical-healthcare_ch/5695640_sys_gh15886_Invoice_Rejection_Detail.sql
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_xversion/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_xversion/response/model/XmlPayload.java
https://github.com/metasfresh/metasfresh/issues/15886
> Gh15886 show response timestamp

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5695840_sys_gh15897_drop_C_Year_ID_from_C_Order.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
- frontend/src/api/window.js
refs: https://github.com/metasfresh/metasfresh/issues/15897
> Overview and test the entire feature - fixes

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/warehouseassignment/ProductWarehouseAssignmentRestService.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v1/payment/PaymentRestEndpointTest.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/product/ProductsRestControllerTest.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
- backend/de.metas.business/src/main/java/de/metas/warehouseassignment/ProductWarehouseAssignmentRepository.java
- backend/de.metas.business/src/main/java/de/metas/warehouseassignment/ProductWarehouseAssignmentService.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5696240_sys_gh15894_ForbidProductWithNoWarehouseAssignment_SysConfig.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5696390_sys_gh15894_ProductNoWarehouseAssigned_AdMessage.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/warehouseassignment/M_Product_Warehouse_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/productRestController.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/salesOrder.feature
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/order/interceptor/OrderTest.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
refs: https://github.com/metasfresh/metasfresh/issues/15894
> [CR070] Link material to warehouse - iteration 2

- backend/de.metas.business/src/main/java-legacy/org/compiere/process/RequisitionPOCreate.java
https://github.com/metasfresh/metasfresh/issues/15920
> Trx name problem

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5697010_sys_gh15938_Mark_As_Fully_Delivered.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_MarkAsFullyDelivered.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15938
> [CR058] Closed status for PO/SO

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5697460_sys_gh15049_Docs_Sales_Invoice_local_currency_conversion_tax_departure_country.sql
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/15980
> local currency conversion needs to look at tax departure country

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/interceptors/AD_Workflow.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_Workflow_POCopyRecordSupport.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_WF_Node_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_WF_Node_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_Workflow_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflow.feature
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5697600_sys_gh15992_AD_Workflow_Name_IsCalculated.sql
refs: https://github.com/metasfresh/metasfresh/issues/15992
> Cloning of workflows

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocTax.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocTaxUpdater.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocTaxesList.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Invoice.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/factacct_userchanges/FactAcctChangesApplier.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/factacct_userchanges/FactAcctChangesList.java
- backend/de.metas.acct.webui/src/main/java/de/metas/acct/acct_simulation/AcctSimulationViewDataService.java
- backend/de.metas.acct.webui/src/main/java/de/metas/acct/acct_simulation/AcctSimulationViewFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewCloseAction.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5697880_msg_webui_modal_actions_close.sql
* recompute tax lines
* modal: show Close button instead of Cancel
> Purchase Invoice GL Simulation (part 2)

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogSalesOrder.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogShipment.feature
https://github.com/metasfresh/metasfresh/issues/15975
> Shipment-> contract module log relation implementation

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/interceptors/AD_Workflow.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_WF_Node_POCopyRecordSupport.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_WF_Node_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/PP_WF_Node_Product_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/PP_WF_Node_Product_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflow.feature
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/16028
> Follow Up - Cloning of workflows / workflows with work steps and manufacturing products

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Auction.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Locator.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Auction.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Locator.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698330_sys_gh16032_C_Order_Locator.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698370_sys_gh16032_Locator_BPartner_Location.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698430_sys_gh16032_InternalDescription.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698570_sys_gh16032_C_Auction.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698590_sys_gh16032_C_Auction.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698660_sys_gh16032_Locator_Warehouse.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698730_sys_gh16032_update_Locator_BPartnerLocation_Order_Locator.sql
refs: https://github.com/metasfresh/metasfresh/issues/16032
> Sammelstellen/ Verladeorte/ Annahmestellen

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_TabularView.jrxml
https://github.com/metasfresh/metasfresh/issues/16042
> Show Product and activity details in Balance Excel Export

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/saldobilanz/report_TabularView.jrxml
https://github.com/metasfresh/metasfresh/issues/16042
> Gh16042 `inner_silence_uat`-> `master` merge

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationDAO.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/16048
> duplicate key in headeraggregation

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationDAO.java
* refs : https://github.com/metasfresh/metasfresh/issues/16048
* refactor
* refactor 2
* refactor 3
> duplicate key in headeraggregation (#16049)

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_Aggregation_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_Aggregation_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleInvoiceAggregation.feature
- adding cucumber scenarios
- refs: https://github.com/metasfresh/metasfresh/issues/16027
> SubTask 1 (Debitoren Rechnung -> Vertragsbaustein Log) - adding fields in files

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_ModCntr_InvoicingGroup.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_ModCntr_InvoicingGroup_Product.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_ModCntr_InvoicingGroup.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_ModCntr_InvoicingGroup_Product.java
- backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5699300_sys_gh16059_ModCntr_InvoicingGroup.sql
- backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5699320_sys_gh16059_ModCntr_InvoicingGroup_GridView.sql
refs: https://github.com/metasfresh/metasfresh/issues/16059
> New tables ModCntr_InvoicingGroup and ModCntr_InvoicingGroup_Product

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_WF_Node_POCopyRecordSupport.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/GeneralCopyRecordSupport.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflow.feature
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/16088
> Follow Up - Cloning of workflows - Change name and search key

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectStepRestService.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStep.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStepRepository.java
refs: https://github.com/metasfresh/metasfresh/issues/16082
> skip validation for endDate when startDate is provided

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5700280_sys_gh16110_Erntekalender_Calendar.sql
refs: https://github.com/metasfresh/metasfresh/issues/16110
> Create calendar July - June

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_WF_Node_POCopyRecordSupport.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_Workflow_POCopyRecordSupport.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/ClonedWFNodesInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/IInterfaceWrapperHelper.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/GeneralCopyRecordSupport.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698890_gh16028_extend_field_length_for_name_and_value_on_ad_workflow_and_ad_wf_node_tables.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_Workflow_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflow.feature
…(#16037)
* refs : https://github.com/metasfresh/metasfresh/issues/16028
* cucumber updates
* cucumber fixes
* Extend field length for name and value on AD_Workflow and AD_WF_Node
> Merge `magic_oak_uat` to `master`

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/modular/issueReceipt.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/impl/PPCostCollectorModularContractHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/interceptor/PP_Cost_Collector.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5700330_gh_16116_update_and_add_ad_message_for_issue_and_receipt_of_production_order.sql
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/16116
> Modular contract logs for manufacturing: Positive/negative quantity for receipt/issue (resp.)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_BOMLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_BOMLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_BOMLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_BOMLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/persistence/BooleanGetterMethodInfo.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5700470_AddIsAllowIssuingAnyProductToBomLine.sql
- backend/de.metas.contracts/pom.xml
- backend/de.metas.dunning/pom.xml
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/HUPPOrderIssueReceiptCandidatesProcessor.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderBOMLineProductStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/CreateDraftIssuesCommand.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/ComponentIssueCreateRequest.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPCostCollectorBL.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPOrderBOMBL.java
- backend/de.metas.printing.rest-api-impl/pom.xml
- backend/de.metas.printing/de.metas.printing.base/pom.xml
- backend/de.metas.shipper.gateway.commons/pom.xml
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLineRowId.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLineRowType.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_HUEditor_IssueTUs.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_HUEditor_IssueTopLevelHUs.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_HUEditor_ProcessBase.java
Allow any product to be issued
> Merge intensive_care_uat to master

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/JsonRetrieverService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v1/bpartner/BpartnerRestControllerTest.snap
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v1/bpartner/bpartnercomposite/JsonRetrieverServiceTest.snap
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/BpartnerRestControllerTest.snap
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/bpartnercomposite/JsonRetrieverServiceTest.snap
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartner.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/ChangeLogUtil.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5701420_sys_gh16150_Fresh_Urproduzent.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/createbpartner/CreateBPartnerV2_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
- misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/request/JsonRequestBPartner.java
- misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/response/JsonResponseBPartner.java
refs: https://github.com/metasfresh/metasfresh/issues/16150
> Add "Urproduzent" property to BPartner-API

- backend/de.metas.report/metasfresh-report-service/pom.xml
> Gh16134 add open sans font

- backend/de.metas.business/src/main/java/de/metas/pricing/service/ProductPriceQuery.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/MProductImportTableSqlUpdater.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcess.java
> Do not count as duplicates when we have different taxes or price list versions

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/hasEUTaxes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5701710_sys_gh16164_hasEUTaxes.sql
https://github.com/metasfresh/metasfresh/issues/16164
> Gh16164 ic master merge

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/PurchaseModularContractLogsHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/SalesModularContractLogsHandler.java
refs: https://github.com/metasfresh/metasfresh/issues/16177
> split handler into PO/SO handlers

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report.jrxml
> check for isCreditMemo when printing report_esr and report_qr sub-reports

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report.jrxml
> Mi soft panda uat gh16189

- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interceptor/C_Flatrate_Term.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettings.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsQuery.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5702490_sys_modCntr_settings_unique_index_adjustment.sql
- modCntrSettings isSOTrx adjustments
- add it to unique index and functionality where it wasn't considered
- don't auto create interim contracts for sales modular contracts
> modCntrSettings isSOTrx adjustments and don't create interim contract on sales side

- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/DocLine_CostCollector.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/Doc_PPCostCollector.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderCost.java
- backend/de.metas.material/planning/src/test/java/de/metas/material/planning/pporder/impl/PPOrderBOMBL_computeQtyToIssueBasedOnFinishedGoodReceipt_more_Test.java
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/16203
> merge Costing Fixes from tasty ham to tenacious d

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Log_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogRecompute.feature
refs: https://github.com/metasfresh/metasfresh/issues/16180
> cucumber scenario for covering recomputation of processed logs

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5703140_sys_gh16202_ModularContractLog_References.sql
https://github.com/metasfresh/metasfresh/issues/16202
> fix field's links to windows

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shipping_notification/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5703570_sys_gh16226_Shipping_Notification_Report_Process.sql
https://github.com/metasfresh/metasfresh/issues/16226
> Create Jasper reports for shipping-notifications

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/ModularContractService.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ContractInfoParameter.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/IModularContractLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ModularContractLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ModularLogsWorkPackageProcessor.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ProcessModularLogsEnqueuer.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractMaterialReceiptLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/InterimContractLogsHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/InventoryLineLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/PurchaseInvoiceLineInterimLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/PurchaseModularContractLogsHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/PurchaseOrderLineLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/SalesInvoiceLineLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/SalesModularContractLogsHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/SalesOrderLineLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/ShipmentLineLogHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/workpackage/PPCostCollectorLogHandler.java
refs: https://github.com/metasfresh/metasfresh/issues/16207
> improve logs creation on async

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/SOLineForPOLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/SOLineForSOLogHandler.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5703520_sys_gh16258_SOLineForSOLogHandler_OnCompleteDescription.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Log_Status_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Settings_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogSalesOrder.feature
> Sales Order -> Modular Contract Log (Sales)

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ModularLogsWorkPackageProcessor.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ProcessModularLogAggRequest.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ProcessModularLogsEnqueuer.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogSalesOrder.feature
> make workpackage creation more robust

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ModularLogsWorkPackageProcessor.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ProcessModularLogAggRequest.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ProcessModularLogsEnqueuer.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogSalesOrder.feature
> make workpackage creation more robust (#16266)

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5703640_sys_gh16181_fix_isIncludedTax_translation.sql
> #16181 : fix IsIncludedTax translation

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5703850_sys_gh16258_C_Order_ModCntr_Log_RelationTypes.sql
> fix C_Order -> ModCntr_Log relation types

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5703850_sys_gh16258_C_Order_ModCntr_Log_RelationTypes.sql
> fix C_Order -> ModCntr_Log relation types (#16273)

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5703910_sys_gh16181_fix_sap_gl_journal_trls.sql
> #16181 : fix  SAP GL Journal translation

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_NotificationLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_NotificationLine_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_Notification_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_Notification_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shippingNotification/shippingNotification.feature
metasfresh issue : https://github.com/metasfresh/metasfresh/issues/16274
> Creating Cucumber Tests for shipping notification (`M_Shipping_Notification`, `M_Shipping_NotificationLines`)

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/ShipmentLineForPOModularContractHandler.java
https://github.com/metasfresh/metasfresh/issues/16207
> Shipment -> Modular Contract Log (Sales)

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5704340_sys_gh16294_ModCntr_Log_Customization.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5704340_sys_gh16294_ModCntr_Log_Customization.sql
https://github.com/metasfresh/metasfresh/issues/16294
> Modular contract log customization and corrections

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5704450_sys_gh16306_add_missing_trls.sql
> add missing translations

- frontend/src/components/login/RoleSelectView.js
bug introduced by
* https://github.com/metasfresh/metasfresh/pull/16293
> Fix error on login role selection

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5704320_sys_gh16306_add_missing_trls.sql
> #16306 add missing translation

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_WF_Approval_Request.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_WF_Approval_Request.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/execution/approval/strategy/impl/RequestorHierarcyProjectManagerPlusCTO_ApprovalStrategy.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5704690_sys_gh16328_My_Approvals_Window.sql
https://github.com/metasfresh/metasfresh/issues/16328
> New `My Approvals` window

- .github/workflows/cicd.yaml
https://github.com/metasfresh/metasfresh/pull/16320
> timeout of 5 mins hit

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5704840_sys_gh16328_Status_Translations.sql
https://github.com/metasfresh/metasfresh/issues/16328
> New My Approvals window

- .github/workflows/cicd.yaml
timeout of 5 mins hit https://github.com/metasfresh/metasfresh/pull/16320
> increase timeout in build pipeline

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5703500_sys_add_proFormaSO_doc_type.sql
(cherry picked from commit 0a5c3a55bc5e63d4fb5c5bf9b42d5e482e93b006)
> fix c_docType_ID not from idServer

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/generic/GenericRelatedDocumentDescriptor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/generic/GenericRelatedDocumentsProvider.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/generic/GenericTargetColumnInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/generic/GenericTargetWindowInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/relation_type/SpecificRelationTypeRelatedDocumentsProvider.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/document/references/related_documents/generic/GenericRelatedDocumentsProviderTest.java
- backend/de.metas.util/src/main/java/de/metas/util/collections/CollectionUtils.java
- backend/de.metas.util/src/test/java/de/metas/util/collections/CollectionUtilsTest.java
follow-up of https://github.com/metasfresh/metasfresh/pull/16335
> Discover dynamic references (AD_Table_ID/Record_ID) - part 2

- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Change_BillPartner_For_FlatrateData.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Change_For_FlatrateData.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5705120_sys_gh16347_Change_Subscription_Partner_Window.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5705150_sys_gh16347_Terminate_Subscription_Partner_Window.sql
https://github.com/metasfresh/metasfresh/issues/16347
> Make Flatrate data processes work in partner window

- frontend/src/assets/css/header.css
Reverts metasfresh/metasfresh#16382
> Revert "Fix webui logo CSS - set max-width:130px, drop height: 31px"

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5705790_sys_gh16353_Modular_Interim_Contract_OnFlatrateTermExtend.sql
refs: https://github.com/metasfresh/metasfresh/issues/16353
> Modular_Interim_Contract_OnFlatrateTermExtend

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5705790_sys_gh16353_Modular_Interim_Contract_OnFlatrateTermExtend.sql
refs: https://github.com/metasfresh/metasfresh/issues/16353
> Modular_Interim_Contract_OnFlatrateTermExtend (#16426)

- .mergify.yml
- .testspace.yml
> metas ts/master/trivial change

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5705850_sys_gh16430_Missing_Base_PLV_Msg.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_ShowProductsToAddFromBasePriceList.java
https://github.com/metasfresh/metasfresh/issues/16430
> Products Proposal modal update

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/accountingShippingNotification.feature
refs: https://github.com/metasfresh/metasfresh/issues/16337
> Accouting for shipping notification

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/ManufacturingOrderQuery.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
https://github.com/metasfresh/metasfresh/issues/16435 suggested changes + return only PP_Order with planning status = Planning
> Mobile UI - Manufacturing orders are not sorted by sequence

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/accountingShippingNotification.feature
refs: https://github.com/metasfresh/metasfresh/issues/16337
> adding missing scenario

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5707050_sys_gh16451_ AD_Client_ID_AD_Org_ID_display.sql
refs: https://github.com/metasfresh/metasfresh/issues/16451
> Feature to hide AD_Client_ID/AD_Org_ID from all windows

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impexp/ModularContractLogImportProcess.java
> fix compile error on classname property in ModCntr_Type

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking_BPartner.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobQuery.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5707370_sys_gh16471_PickingProfile.sql
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfile.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfileRepository.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingJobRestService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingWorkflowLaunchersProvider.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.java
refs: https://github.com/metasfresh/metasfresh/issues/16471
> Introduce Mobile UI Picking Profile

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobQuery.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingWorkflowLaunchersProvider.java
refs: https://github.com/metasfresh/metasfresh/issues/16471
> enforce picking profile BPartners when fetching the filtering facets

- backend/de.metas.business/src/main/java/de/metas/uom/UomId.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IPPOrderReceiptHUProducer.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/CostCollectorCandidateCoProductHUProducer.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/CostCollectorCandidateFinishedGoodsHUProducer.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_BOM.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5707710_sys_gh16484_IssueIndividualCUs.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLineRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/PackingInfoProcessParams.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Receipt.java
https://github.com/metasfresh/metasfresh/issues/16484
> refs Serial Number Production Automation - Implementation #16484

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5707780_sys_gh16471_PickingProfile_GridView.sql
refs: https://github.com/metasfresh/metasfresh/issues/16471
> Fix Picking Profile Window

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5707780_sys_gh16471_PickingProfile_GridView.sql
refs: https://github.com/metasfresh/metasfresh/issues/16471
> fix window (#16492)

- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5707715_sys_gh16484_IssueIndividualCUs_fix_trl.sql
https://github.com/metasfresh/metasfresh/issues/16484
> fix trls, ref

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impexp/ModCntrLogImportTableSqlUpdater.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impexp/ModularContractLogImportProcess.java
> Gh16344 import contract log fix

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5707790_sys_gh16496_Cleanup_HU_Label_Processes.sql
https://github.com/metasfresh/metasfresh/issues/16496
> Cleanup HU label related processes

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708090_sys_gh16496_Cleanup_HU_Label_Processes.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
> Cleanup HU(-label) related processes - gh16496

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interceptor/C_Order.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5708100_sys_gh16510_Flatrate_Conditions_Modular_Settings.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5708260_sys_gh16510_Purchase_Order_Year_Msg.sql
https://github.com/metasfresh/metasfresh/issues/16510
> Include crop year & crop calendar in Purchase Order

- backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_I_ModCntr_Log.java
- backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_I_ModCntr_Log.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impexp/ModCntrLogImportTableSqlUpdater.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impexp/ModularContractLogImportProcess.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interceptor/C_Order.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5706838_sys_gh16344_import_format_adjustments.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5708100_sys_gh16510_Flatrate_Conditions_Modular_Settings.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5708260_sys_gh16510_Purchase_Order_Year_Msg.sql
https://github.com/metasfresh/metasfresh/issues/16510
> merging inner_silence_uat -> master

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Candidate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Candidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/agg/key/impl/PPOrderCandidateKeyValueHandler.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/produce/PPOrderAllocatorService.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5708300_sys_gh16516_CapacityPerCycleOverride_.sql
refs: https://github.com/metasfresh/metasfresh/issues/16516
> Add Max Lot Size override in Manufacturing Candidate

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Workplace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Workplace_User_Assign.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Workplace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Workplace_User_Assign.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5707830_sys_gh16498_New_C_Workplace_Table.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5707840_sys_gh16498_New_Workplace_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5707850_sys_gh16498_New_C_Workplace_User_Assign_Table.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5707860_sys_gh16498_New_Users_Assigned_Workplace_Window.sql
https://github.com/metasfresh/metasfresh/issues/16498
> Adding C_Workplace and C_Workplace_User_Assign tables

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Receipt.java
refs: https://github.com/metasfresh/metasfresh/issues/16484
> add mandatory field error message for NumberOfCUs

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708680_sys_gh16498_Workplace_Unique_Name.sql
> The workplace name must be unique

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5708740_sys_gh16545_Index_Table.sql
refs: https://github.com/metasfresh/metasfresh/issues/16545
> Create Index window for AD_Index_Table

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Invoice_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Invoice_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Order_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Order_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Invoice_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Invoice_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Order_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getPricePatternForJasper.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708910_sys_gh16558_getPricePatternForJasper.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708920_sys_gh16558_Docs_Purchase_Order_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708940_sys_gh16558_Docs_Purchase_Order_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708950_sys_gh16558_Docs_Purchase_Invoice_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708960_sys_gh16558_Docs_Purchase_Invoice_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708980_sys_gh16558_Docs_Sales_Order_Details_HU.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5708990_sys_gh16558_Docs_Sales_Invoice_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5709000_sys_gh16558_Docs_Sales_Invoice_Details_HU.sql
https://github.com/metasfresh/metasfresh/issues/16558
> Use the price precision in jasper reports

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/Workplace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceId.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceRepository.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceUserAssignRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobReferenceQuery.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingJobRestService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingWorkflowLaunchersProvider.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.java
…place
refs: https://github.com/metasfresh/metasfresh/issues/16564
> When picking, filter for the warehouse of the currently assigned workplace

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5709170_sys_gh16561_AD_Printer_Config_UC_Workspace_HostKey.sql
https://github.com/metasfresh/metasfresh/issues/16561
> Support the mapping of printers to C_Workplace

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceAssignmentCreateRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceRepository.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceUserAssignRepository.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/workplace/WorkplaceController.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonApplicationParametersMapper.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonMobileApplication.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkplace.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkplaceSettings.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/CustomApplicationParameter.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/MobileApplicationInfo.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WorkplaceSettings.java
- misc/services/mobile-webui/mobile-webui-frontend/src/api/workplace.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/BarcodeScannerComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/constants/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/WorkplaceScanner.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/applications.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/workplaceQRCodes.js
refs: https://github.com/metasfresh/metasfresh/issues/16577
> MobileUI - select workplace before picking

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5709110_sys_gh16561_AD_Printer_Config_UC_Workspace_HostKey.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5709170_sys_gh16561_AD_Printer_Config_UC_Workspace_HostKey.sql
https://github.com/metasfresh/metasfresh/issues/16561
> Only one record is permitted per Workplace

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5709170_sys_gh16561_AD_Printer_Config_UC_Workspace_HostKey.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5709340_sys_gh16561_AD_Printer_Config_UC_Workspace_HostKey.sql
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/AbstractPrintingDAO.java
- backend/de.metas.printing/de.metas.printing.base/src/test/java/de/metas/printing/test/integration/RetrievePrinterConfigTest.java
https://github.com/metasfresh/metasfresh/issues/16561
> The routing logic is covered by unit tests

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/command/ContractLocationReplaceCommand.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/interceptor/C_BPartner_Location.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5709300_sys_gh16574_UpdateFlatrateTermLocationsBasedOnDefaultAddresses_sysConfig.sql
refs: https://github.com/metasfresh/metasfresh/issues/16574
> Automatic update of contract periods based on checkbox default addresses

- backend/de-metas-salesorder/src/main/sql/postgresql/system/5611420_sys_gh11947_entity_de_metas_salesorder.sql
- backend/de-metas-salesorder/src/main/sql/postgresql/system/5611430_sys_gh11947_wp_CompleteShipAndInvoiceWorkpackageProcessor.sql
- backend/de-metas-salesorder/src/main/sql/postgresql/system/5612270_sys_gh11947_wp_ProcessOLCandsWorkpackageProcessor.sql
refs: https://github.com/metasfresh/metasfresh/issues/16592
> Applying SQLs from of 5.176 onwards fails on older DBs

- backend/de-metas-salesorder/src/main/sql/postgresql/system/5611420_sys_gh11947_entity_de_metas_salesorder.sql
- backend/de-metas-salesorder/src/main/sql/postgresql/system/5611430_sys_gh11947_wp_CompleteShipAndInvoiceWorkpackageProcessor.sql
- backend/de-metas-salesorder/src/main/sql/postgresql/system/5612270_sys_gh11947_wp_ProcessOLCandsWorkpackageProcessor.sql
refs: https://github.com/metasfresh/metasfresh/issues/16592 (cherry picked from commit 5d0492f4f13b77f17b407d7f1ba1016baefff17a)
> Applying SQLs from of 5.176 onwards fails on older DBs (#16593)

- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
refs: https://github.com/metasfresh/metasfresh/issues/16645
> Exception in DHL Shipper Gateway

- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5710310_sys_gh16660_Deactivate_Queue_Processors.sql
refs: https://github.com/metasfresh/metasfresh/issues/16660
> Deactivate unnecessary queue processors

- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5710310_sys_gh16660_Deactivate_Queue_Processors.sql
refs: https://github.com/metasfresh/metasfresh/issues/16660
> Deactivate unnecessary queue processors (#16661)

- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5710470_sys_gh16660_Reactivate_Queue_Processors.sql
refs: https://github.com/metasfresh/metasfresh/issues/16660
> Reactivate queue processors (#16669)

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5710250_sys_gh16688_Lieferdisposition_Trls.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5710370_sys_gh16688_Process_Trl.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5710590_sys_gh16688_Process_trls.sql
refs: https://github.com/metasfresh/metasfresh/issues/16688
> Missing translation in Shipment Disposition

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5710250_sys_gh16688_Lieferdisposition_Trls.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5710370_sys_gh16688_Process_Trl.sql
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5710590_sys_gh16688_Process_trls.sql
refs: https://github.com/metasfresh/metasfresh/issues/16688
> Missing translation in Shipment Disposition (#16689)

- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5710570_sys_gh16660_Deactivate_Queue_Processors.sql
refs: https://github.com/metasfresh/metasfresh/issues/16660
> Deactivate unnecessary queue processors (#16690)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5603820_sys_gh11709_CostEstimateDocument.sql
> Merge to master from origin/tenacious_d_uat

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
https://github.com/metasfresh/metasfresh/issues/16687
> Jasper reports corrections

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobStepPickedTo.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/util/CatchWeightHelper.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJob_Scenarios_Test.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobLine.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobStep.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobStepPickFrom.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JsonQuantity.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepButton.jsx
https://github.com/metasfresh/metasfresh/issues/16644
> Intensive care uat gh16646 fix weight source

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Order.java
* Invalidate invoice candidates for Order on complete and re-activate
> Invalidate invoice candidates for Order (#16718)

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5709450_sys_add_I_ModCntr_Log_CalendarName.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/dataImport/C_DataImport_StepDef.java
https://github.com/metasfresh/metasfresh/issues/16344
> Fix migration script

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Order_Details_Sum.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5710940_sys_gh16687_Docs_Sales_Order_Details_Sum.sql
> change total line for SO from `Endsumme €` into `Endsummer EUR`

- frontend/src/actions/GenericActions.js
- frontend/src/actions/TableActions.js
- frontend/src/actions/ViewActions.js
- frontend/src/actions/WindowActions.js
- frontend/src/api/view.js
- frontend/src/components/table/Table.js
- frontend/src/components/table/TableCell.js
- frontend/src/components/table/TableRow.js
- frontend/src/components/widget/Lookup/Lookup.js
- frontend/src/components/widget/Lookup/RawLookup.js
- frontend/src/constants/ActionTypes.js
- frontend/src/constants/actions/TableTypes.js
- frontend/src/constants/actions/ViewTypes.js
- frontend/src/reducers/tables.js
basically I've copied the fixes from master
> webui frontend: Fix modal view patching

- .github/merge_to_master
- frontend/src/components/table/TableFilter.js
- misc/dev-support/docker/infrastructure/env-files/koala_yawn_uat.env
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/16730
*  https://github.com/metasfresh/metasfresh/pull/16707
*  https://github.com/metasfresh/metasfresh/pull/16666
*  https://github.com/metasfresh/metasfresh/pull/16400
*  https://github.com/metasfresh/metasfresh/pull/16331
*  https://github.com/metasfresh/metasfresh/pull/16329
*  https://github.com/metasfresh/metasfresh/pull/16308
*  https://github.com/metasfresh/metasfresh/pull/16295
> Merge koala_yawn_uat -> master

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production.feature
see
* https://metasfresh.testspace.com/spaces/241729/current/361910/cucumber/profile6
* https://metasfresh.testspace.com/spaces/241729/current/361910/cucumber/profile4
> Ignore some flaky tests

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5710330_sys_AD_WF_Approval_Files_Tabs.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5710810_sys_AD_WF_Approval_Open_Processes.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5710990_sys_AD_WF_Approval_Related_Translations.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/workflow/process/AD_WF_Approval_Request_Download_File.java
* koala_yawn_uat env file
* update docker-compose
* koala_yawn_uat env file
* Add "Files" tabs in approval windows
* Add "Files" tabs in approval windows
* translations
* small correction regardint process availability
* cleanup
> merge koala_yawn_uat to master

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5711140_sys_gh16743_Product_Costs_Date_Excel_Export.sql
https://github.com/metasfresh/metasfresh/issues/16743
> Excel output for cost prices report

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5711140_sys_gh16743_Product_Costs_Date_Excel_Export.sql
https://github.com/metasfresh/metasfresh/issues/16743
> merging `intensive_care_uat` -> `master`

- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessor.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/DeviceConfig.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/SysConfigDeviceConfigPool.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/manufacturing/issue/plan/PPOrderIssuePlanCreateCommand.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ScaleDevice.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/issue/json/JsonScaleDevice.java
- backend/de.metas.manufacturing/pom.xml
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/MPPCostCollector.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/MPPOrder.java
- backend/de.metas.material/planning/pom.xml
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/IPPOrderBOMBL.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/OrderBOMLineQtyChangeRequest.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/OrderBOMLineQuantities.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPOrderBOMBL.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JsonQuantity.java
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/NumberUtils.java
- misc/de-metas-common/de-metas-common-util/src/test/java/de/metas/common/util/NumberUtilsTest.java
- misc/services/mobile-webui/mobile-webui-frontend/package.json
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/index.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/toast.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qtys.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
refs: https://github.com/metasfresh/metasfresh/issues/16779
> MobileUI - TargetWeight rounding, ignore non-stocked components

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5711040_sys_gh16727_DefaultStoringFileServerPath.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5711580_sys_gh16727_DefaultStoringFileServerPath.sql
> Default path corrected

- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/freshQtyOnHand/FreshQtyOnHandId.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/freshQtyOnHand/api/IFreshQtyOnHandDAO.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/freshQtyOnHand/api/impl/FreshQtyOnHandDAO.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/material/interceptor/Fresh_QtyOnHand_Line.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5711650_sys_gh16791_Process_Trls.sql
refs: https://github.com/metasfresh/metasfresh/issues/16791
> Zählbestand Reihenfolge is not transferred to Material Cockpit

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5710980_sys_gh16727_PRINTER_OPTS_IsAlsoSendToBrowser.sql
> PRINTER_OPTS_IsAlsoSendToBrowser DE Translation

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5711760_sys_gh16779_temp_storage.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/toast.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/components/QtyInputField.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
refs: https://github.com/metasfresh/metasfresh/issues/16802
> add qty to funnel

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/JavaProcess.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ReportResultDataTarget.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ReportResultDataTargetType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ReportResultData.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5710850_sys_gh16727_StoreProcessResultFilePath.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5710980_sys_gh16727_PRINTER_OPTS_IsAlsoSendToBrowser.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5711000_sys_gh16727_StoreProcessResultFileOn.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5711580_sys_gh16727_DefaultStoringFileServerPath.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/print/DocumentPrintRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/print/WebuiDocumentPrintService.java
- backend/de.metas.util/src/main/java/de/metas/util/FileUtil.java
- backend/de.metas.util/src/test/java/de/metas/util/FileUtilTest.java
- frontend/src/actions/GenericActions.js
- frontend/src/actions/WindowActions.js
- frontend/src/api/window.js
- frontend/src/components/app/Modal.js
- frontend/src/components/header/Attachments.js
- frontend/src/components/header/Header.js
> merging `modified_carbon_uat` -> `master`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5712150_sys_gh16830_Discontinued_Columns_Filters_Product.sql
> Set Discontinued and Discontinued From columns as filters in the Product window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5712150_sys_gh16830_Discontinued_Columns_Filters_Product.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5712320_sys_gh16830_Discontinued_Columns_Filters_Product.sql
> Ic master gh16830

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/RV_AccountSheet.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5711960_RV_AccountSheet.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5711980_C_ElementValue_for_C_AcctSchema_ID_val_rule.sql
Included PRs:
* https://github.com/metasfresh/metasfresh/pull/16819
> Merge mad_orange_uat -> master

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Tab.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Tab.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_tab_v.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_tab_vt.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712530_AD_Tab_NotFound_Message_and_Detail.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712550_ad_tab_v.sql
- backend/de.metas.payment.esr/src/main/sql/postgresql/system/5712570_ESR_Import_NotFound_messages.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutSingleRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/NotFoundMessages.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5711700_msgs_webui_window_notFound.sql
- frontend/package.json
- frontend/src/__tests__/actions/WindowActions.test.js
- frontend/src/__tests__/components/BlankPage.test.js
- frontend/src/__tests__/components/__snapshots__/BlankPage.test.js.snap
- frontend/src/actions/WindowActions.js
- frontend/src/api/window.js
- frontend/src/components/BlankPage.js
- frontend/src/components/app/DocumentList.js
- frontend/src/components/app/MasterWindow.js
- frontend/src/containers/Board.js
- frontend/src/reducers/windowHandler.js
- frontend/test_setup/jestSetupAfterEnv.js
- webui Document not found customizable messages
- fix standard trl
- BlankPage.js: hide empty-ish message/detail
- set ESR_Import not found messages
> Customizable Document Not Found messages; set/improve ESR_Import not found message

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/ColumnSqlCacheInvalidateRequestFactories.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/ColumnSqlSourceDescriptor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/ADTableDAO.java
- minor QA
- Fix not working cache invalidation on source column changed (part 2)
Follow-up of
* https://github.com/metasfresh/metasfresh/pull/16794
> intensive care uat fixCacheInvalidationOnSourceColumnChange 2

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/MacAddressGenerator.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/MacAddressGeneratorTest.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/PasswordGeneratorTest.java
https://github.com/metasfresh/metasfresh/issues/16856
> Handel product production with 8 MAC addresses

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/kpi/data/KPIDataProvider.java
Fixes issue introduced by
* https://github.com/metasfresh/metasfresh/pull/16852
Reported NPE:
```
{timestamp: 1701850533.316, status: 500, error: "Internal Server Error",…}
error
: 
"Internal Server Error"
exception
: 
"java.lang.NullPointerException"
message
: 
"permissionsProvider is marked non-null but is null"
path
: 
"/rest//api/dashboard/targetIndicators/1000036/details"
status
: 
500
timestamp
: 
1701850533.316
trace
: 
["java.lang.NullPointerException: permissionsProvider is marked non-null but is null",…]
0
: 
"java.lang.NullPointerException: permissionsProvider is marked non-null but is null"
1
: 
"\tat de.metas.ui.web.kpi.data.sql.SQLKPIDataLoader.<init>(SQLKPIDataLoader.java:67)"
2
: 
"\tat de.metas.ui.web.kpi.data.sql.SQLKPIDataLoader.<init>(SQLKPIDataLoader.java:55)"
3
: …
```
> Fix NPE when clicking on KPI Indicator Details

- frontend/src/components/header/Actions.js
- frontend/src/components/header/Attachments.js
- frontend/src/reducers/windowHandler.js
- INIT_DATA_SUCCESS: preserve already exising layout
- header actions: don't call backend if document not found
- attachments: stop spinner fail on error, don't call backend if document not found
> webui: when document suddenly disappears make sure we preserve the layout not found messages + other document not found fixes

- backend/de.metas.business/src/main/java/org/eevolution/api/IProductBOMDAO.java
- backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java
- backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMBL.java
- backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
- backend/de.metas.business/src/test/java/org/eevolution/api/PPOrderDocBaseTypeTests.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/CreateOrderCommand.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/callout/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/costing/BatchProcessBOMCostCalculatorRepository.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_BOMVersions.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_Planning.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/model/interceptor/PP_Product_BOM.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateOrderCandidateCommand.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/event/PPOrderRequestedEventHandlerTests.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/ppordercandidate/PPOrderCandidatePojoSupplier.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/picking_bom/PickingBOMService.java
refs https://github.com/metasfresh/metasfresh/issues/16873
> Product planning data is being ignored when manufacturing orders are generated automatically

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Tab.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Tab.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_tab_v.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_tab_vt.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712530_AD_Tab_NotFound_Message_and_Detail.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712550_ad_tab_v.sql
- backend/de.metas.payment.esr/src/main/sql/postgresql/system/5712570_ESR_Import_NotFound_messages.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayout.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutSingleRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/NotFoundMessages.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5711700_msgs_webui_window_notFound.sql
- frontend/package.json
- frontend/src/__tests__/actions/WindowActions.test.js
- frontend/src/__tests__/components/BlankPage.test.js
- frontend/src/__tests__/components/__snapshots__/BlankPage.test.js.snap
- frontend/src/actions/WindowActions.js
- frontend/src/api/window.js
- frontend/src/components/BlankPage.js
- frontend/src/components/app/DocumentList.js
- frontend/src/components/app/MasterWindow.js
- frontend/src/components/header/Actions.js
- frontend/src/components/header/Attachments.js
- frontend/src/containers/Board.js
- frontend/src/reducers/windowHandler.js
- frontend/test_setup/jestSetupAfterEnv.js
- Customizable Document Not Found messages; set/improve ESR_Import not found message (#16863)
- fix after cherry-pick
- webui: when document suddenly disappears make sure we preserve the layout not found messages + other document not found fixes (#16871)
- fix after cherry-pick
> Customizable Document Not Found messages; set/improve ESR_Import not found message (hard_encoded_uat)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712550_ad_tab_v.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/16882
> Merge hard_encoded_uat -> master

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5712850_sys_gh16879_Base_PLV_ValRule_Update.sql.sql
https://github.com/metasfresh/metasfresh/issues/16879
> Improve Base Price List Validation

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/Database.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/compiere/db/DatabaseTest.java
refs: https://github.com/metasfresh/metasfresh/issues/16791
> fix date's timezone (#16883)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/Database.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/compiere/db/DatabaseTest.java
refs: https://github.com/metasfresh/metasfresh/issues/16791
> fix date's timezone (#16883) (#16892)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/process/AD_AttachmentEntry_ReferencedRecord_v_Download.java
https://github.com/metasfresh/metasfresh/issues/16900
> Add `Files` Tab in a window with an `Open Attachement` processe

- backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
https://github.com/metasfresh/metasfresh/issues/16915
> Get products in trx

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/execution/approval/strategy/DocApprovalStrategyService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/execution/approval/strategy/type_handlers/DocApprovalStrategyTypeHandlers.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/execution/approval/strategy/type_handlers/JobHandler.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workflow/execution/approval/WFActivityApprovalCommandTest.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workflow/execution/approval/strategy/DocApprovalStrategyServiceTest.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5713460_msg_DocApprovalStrategyTypeHandler.NoUsersFoundForJob.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5713470_C_Doc_Approval_Strategy_trls.sql
- throw exception if no users found for job
- trls
- junit tests
> Document Approval Workflow improvements - iteration 2 (part 2)

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/ExtractCounterAttributesCommand.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsRestController.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/LoadJsonHURequest.java
- backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/handlingunits/rest_api/ExtractCounterAttributesCommandTest.java
refs: https://github.com/metasfresh/metasfresh/issues/16944
> Dynamic output of Mac addresses in REST API

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrderLine.java
refs: https://github.com/metasfresh/metasfresh/issues/16949
> Compute order tax for the date promised

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ExecuteReportStrategy.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/customColumns/setCustomColumns.feature
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IAggregationBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLineAggregator.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/16932
> Merge inner_silence_uat -> master
