metasfresh/metasfresh

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463050_sys_gh97_update_to_latest_version_Docs_Sales_InOut_Root.sql

https://github.com/metasfresh/metasfresh-sp80/issues/97

#97 update docs_sales_inout_root to the latest version

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463180_sys_gh1591_enable_password_field.sql

enabling field and set to isdisplayed

#1591 Password Field missing in window user

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463190_cli_gh1595_translating_doctypes.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463190_sys_gh1595-translating-invoice-disposition-en-us.sql

translating important doctypes and also the invoice disposition window

Gh1595 translating doctypes to en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463300_sys_gh1574-organisation-window-webui.sql

Creating the new Window Organisation in WebUI. Adding the 2-column Layout, advanced edit, GridView and Sidelist Layout.
FRESH-2321 https://github.com/metasfresh/metasfresh/issues/1584

#1584 New Window for Org in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463310_sys_gh1585-client-window-webui.sql

Adding the Client Window to WebUI, including 2-column Layout, advanced edit, Sidelist adn Gridview Layout.
FRESH-2323 https://github.com/metasfresh/metasfresh/issues/1585

#1585 New Client Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463320_sys_gh1612-bpartnergroup-window-webui.sql

Adding the 2-column Layout of Business Partner Group window in WebUI, including Advanced Edit Section, grid View and Sidelist definition.
FRESH-2351 https://github.com/metasfresh/metasfresh/issues/1612

#1612 New Window for Business Partner Group in WebUI

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeDAO.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUTrxBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/empties/impl/EmptiesInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUTrxBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUInOutBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/AbstractReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/MultiVendorHUReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/VendorReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/IHUInventoryBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/HUInternalUseInventoryProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/HUInventoryBL.java
de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/editor/model/impl/HUEditorModel.java
de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/editor/view/HUEditorPanel.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/form/terminal/TerminalException.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5463350_sys_gh396webui_more_processes.sql

https://github.com/metasfresh/metasfresh-webui-api/issues/396

Gh396webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463340_sys_gh1621-pricelist-window-adjustment-webui.sql

Adding Adjustments of Pricelist window in WebUI. Renaming Fields and System Elements. Adjusting Order by of Subtab infomatio. German Translation of Fields. Adding Client to Main View.
FRESH-2360 https://github.com/metasfresh/metasfresh/issues/1621

#1621 Adding Adjustments of Pricelist window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463370_sys_gh1614-attribute-set-window-webui.sql

Creating a new Window Attribute Set in WebUI. Including 2-column Layout, Advanced Edit, Grid View, Sidelist. Adding missing Fieldnames and System Elements. Adding Menu entry for webui.
FRESH-2353 https://github.com/metasfresh/metasfresh/issues/1614

#1614 New Window Attribute Set Instance in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463330_sys_gh1602_add_documentno_gridview.sql

adding field to grid view as first column
#1602

#1602 Show manufactoring order documentno in production order overview

---

de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRImportBL.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/process/ESR_Import_LoadFromFile.java
de.metas.payment.esr/src/main/sql/postgresql/system/5455810_sys_gh1611_sys_AddMessage.sql

Add logic for checking if the imported file is v11 file. If not, do not
import it.
#1617

#1617 Check if imported esr file is v11 file

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463450_sys_gh1642-salesorder-resize-grid.sql

Resizing different UI Field Elements for better distribution in Grid
View, e.g. BPartner Field set to large, currency to small and so on.
FRESH-2384 https://github.com/metasfresh/metasfresh/issues/1642

#1642 Column Resizing in Sales Order Grid View

---

de.metas.util/pom.xml
de.metas.util/src/main/java/org/adempiere/util/email/EmailValidator.java

Add email validator syntax #1644

#1644 Add email validator

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463460_sys_gh1627-bpartner-window-adjustments-webui.sql

Adding new Fields to Subtab Layouts of Business Partner Window. Including Grid View and Advanced Edit.
FRESH-2367 https://github.com/metasfresh/metasfresh/issues/1627

#1627 Adjustments of Business Partner window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463500_sys_gh1650-pricelist-field-resize-webui.sql

Resize Fields in Pricelist Window and Field and Layout adjustments. Adding Windget Sizes for better UX in Grid View. Adding Advanced Edit Display and more.
FRESH-2392 https://github.com/metasfresh/metasfresh/issues/1650

#1650 Resize Fields in Pricelist Window and Field and Layout adjustments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463610_sys_gh1665-subtab-adv-edit-config.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463611_sys_gh1665-subtab-adv-edit-config.sql

Adding Migration Scripts to update all Subtabs w/ their display logic and uistyle, that should'nt be primary per default.
FRESH-2404 https://github.com/metasfresh/metasfresh/issues/1665

#1665 Subtab Advanced Edit Configurations

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463670_sys_gh1647-empties-return-window-de_DE-webui.sql

Adding the de_DE Name Translation to empties Return window, tab and menu
in webui
FRESH-2387 https://github.com/metasfresh/metasfresh/issues/1647

#1647 Adding the de_DE Name Translation to empties Return window, tab and menu in webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463680_sys_gh1641-tax-rate-window-webui.sql

New Tax Rate Window in WebUI. Adding the 2-column Main Layout, Advanced Edit, Sidelist and Grid View. Incluiding Menu entrue for WebUI menu.
FRESH-2383 https://github.com/metasfresh/metasfresh/issues/1641

#1641 New Tax Rate window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463690_sys_gh1672-tax-category-window-webui.sql

Creating the new Tax Category Window Layout for the Web User Interface. Includung 2-column Layout, Siedlist and Grid View.
FRESH-2410 https://github.com/metasfresh/metasfresh/issues/1672

#1672 Adding the New Tax Category Window to WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463700_sys_gh1564-packing-material-window-webui.sql

Adding the Layout for Packing Material Window in WebUI inluding 2-column Layout, Sidelist, GridView and Advanced Edit.
FRESH-2288 https://github.com/metasfresh/metasfresh/issues/1564

#1564 New Window for Packing Material in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463800_sys_gh1679-country-window-webui.sql

Adding 2-column Layour, Sidelist, Gridview and Advanced Edit Definition. Adding the new Window to WebUI Menue.
FRESH-2417 https://github.com/metasfresh/metasfresh/issues/1679

#1679 New Window for Country in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463820_sys_gh1680-request-type-window-webui.sql

Adding the Layout Definition of Request Type Window to WebUI, including 2-column Layout, Sidelist, GridView and Advanced Edit.
FRESH-2419 https://github.com/metasfresh/metasfresh/issues/1680

#1680 New Window or Request Type in WebUI

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/inout/report_details_v2.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report_details_v2.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_details_v2.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_details_v2.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_v2.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details_v2.jrxml

https://github.com/metasfresh/metasfresh/issues/1559

#1559 update layout for order, inout and invoice jaspers

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463330_sys_gh1636_production_trl_de_de.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463330_sys_gh1636_production_trl_de_de_2sql

changing processes and a few messages
https://github.com/metasfresh/metasfresh/issues/1636

#1636 Translate Actions in Production Issue/Receive Window to de_DE

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463580_sys_gh1659_adding_verify_bom_product_table.sql

adding process to table product
https://github.com/metasfresh/metasfresh/issues/1659

#1659 Make verify BOM available in webUI

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/basic_inout/report_details.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/basic_inout_quality/report_details.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/carrot_invoice/report_details.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_InOut_Details_ConcreteADR.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Order_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/Fresh_InOutLine_PI_V.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463729_sys_gh1656_update_fresh_InOutLine_PI_V.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463750_sys_gh1656_update_rv_fresh_pricelist_comparison.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463751_sys_gh1656_update_fresh_pricelist_details_report.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463752_sys_gh1656_update_docs_sales_order_details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463753_sys_gh1656_update_docs_sales_invoice_details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463754_sys_gh1656_update_docs_sales_inout_details_concrete_adr.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463755_sys_gh1656_update_docs_sales_inout_details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463756_sys_gh1656_update_docs_purchase_order_details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463757_sys_gh1656_update_Docs_Purchase_Invoice_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463758_sys_gh1656_update_Docs_Purchase_InOut_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5463759_sys_gh1656_update_Docs_Purchase_InOut_Vendor_Returns_Details.sql

https://github.com/metasfresh/metasfresh/issues/1656
FRESH-2398 No Packing Item in jaspers

#1656 update reports to hide no packing item

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463660_sys_gh1669_translating_planning_status.sql

https://github.com/metasfresh/metasfresh/issues/1669

#1669 Translating Manufacturing Order Field and List Values of Planning Status to de_DE

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464040_sys_gh1701-customer-return-fields-webui.sql

Adding new Fields (QtyTU, Packing Material Product) to Customer Return
Window.
FRESH-2448 https://github.com/metasfresh/metasfresh/issues/1701

#1701 Adding new Fields to Customer Return Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463810_sys_gh1687_refactor_request_tab_bpartner_window.sql

disabled old tab request, added new one with a minimum set of fields,
used widget sizes
IMPACT: Dropped showing other documents than r_request! (before we were also showing orders, inout, invoice)
https://github.com/metasfresh/metasfresh/issues/1687

#1687 Refactor Request Tab in Partner Window to allow zoom and advanced edit

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464180_sys_gh1681-response-schema-webui.sql

New Window in WebUI for Std. Response/ Result Schema maintenance in requests. 2-column Main View Layout, Sidelist and Grid View. Added the window in Menu in CRM/Settings.
FRESH-2420 https://github.com/metasfresh/metasfresh/issues/1681

#1681 New Window for Standard Response in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464190_sys_gh1677-adjustments-product-window-webui.sql

Adding different adjustments to Product Window in WebUI. Adding missing Fields, adjusting the 
Layout to our current default Layout, adjusting Advanced Edit Layout harmonizing Look & Feel to our current best practice aproach.
FRESH-2416 https://github.com/metasfresh/metasfresh/issues/1677

#1677 Adjustments to Product Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464210_sys_gh1709-my-profile-window-webui.sql

Adding the User Profile Window to WebUI menu. Creating the 2-column Layout including Advanced Edit, Grid View, Sidelist Layout.
FRESH-2465 https://github.com/metasfresh/metasfresh/issues/1709

#1709 Pimp the old "My Profile" window to be used in webui as User settings

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464250_sys_gh1723-request-adjustments-webui.sql

Rearranging work in Request Window. Harmonizing Look & Feel of  current Layout default. Recreated the Grid View, Advanced Edit Mode.
FRESH-2481 https://github.com/metasfresh/metasfresh/issues/1723

#1723 Adjustments to Request Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464260_sys_gh1722-request-status-window-webui.sql

Adding the new Window for Request Status Maintenance to WebUI. Adding the Menu entry, 2-column main view Layout, Sidelist, Grid View.
FRESH-2480 https://github.com/metasfresh/metasfresh/issues/1722

#1722 New Window for Request Status in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464270_sys_gh1729-misc-webui-window-adjustments.sql

Misc Adjustments to window Product Category and others in WebUI.
FRESH-2487 https://github.com/metasfresh/metasfresh/issues/1729

#1729 Adjustments to window Product Category and others in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464200_sys_gh1711_adding_product_search.sql

making m_product search field
https://github.com/metasfresh/metasfresh/issues/1711

#1711 Support Product Search in window BOM

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_de_CH.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_de_DE.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_details.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_en_GB.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_fr_CH.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_it_CH.properties
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5464350_sys_gh1518_add_currency_in_RV_fresh_PriceList_Comparison.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5464351_sys_gh1518_add_currency_in_fresh_PriceList_Details_Report.sql

https://github.com/metasfresh/metasfresh/issues/1518

#1518 add currency in pricelist jasper

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464370_sys_gh1739-menu-entry-product-category-webui.sql

Adjusting the menu entry for Product Category window in WebUI
FRESH-2506 https://github.com/metasfresh/metasfresh/issues/1739

#1739 Menu entry for M_ProductCategory window wrong

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5463180_sys_gh1590-translating-user-window-to-en-us.sql

#1590 Translate User Window to en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464580_sys_gh1746-user-window-optimization-webui.sql

Adding a few optimizations to User window in WebUI.
FRESH-2516 https://github.com/metasfresh/metasfresh/issues/1746

#1746 Layout Optimization of User Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464600_sys_gh1754-transport-dispo-window-webui.sql

Creating 2 new Windows in WebUI (Transport Disposition, Transport  Shipment) and adding to WebUI menu in Logistics. Created the 2-column Layout, Sidelist and GridViews.
FRESH-2526 https://github.com/metasfresh/metasfresh/issues/1754

#1754 New Window for Transport Disposition in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464540_sys_gh1742_default_fields_en_US.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464540_sys_gh1742_doc_outbound_windows_trl.sql

https://github.com/metasfresh/metasfresh/issues/1742

#1742 Translate to en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464620_sys_gh1765-doctype-adjustment-advanced-edit.sql

Adding the Advanced Edit section into Doctype Window w/ 1 column Layout.
FRESH-2536 https://github.com/metasfresh/metasfresh/issues/1765

#1765 Adjustment of advanced edit in Doctype Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464700_sys_gh1753-material-transactions-window-webui.sql

Creating a new Window in WebUI to allow to filter/ search for Material Transaktions. Creating the 2-column Layout, Sidelist, GridView and Advanced Edit.
FRESH-2525 https://github.com/metasfresh/metasfresh/issues/1753

#1753 New Window for Material Transactions in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464770_sys_gh1769-user-dashboard-window-webui.sql

Adding the Layout for Window User Dashboard in WebUI. Including Main View w/ 2.-column Layout, Grid View, Sidelist and Advanced Edit.
FRESH-2548 https://github.com/metasfresh/metasfresh/issues/1769

#1769 Window Adjustments for Dashboard Configuration

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464690_sys_gh1742_add_outbound_documents_browse_name_en_US_.sql

add_outbound_documents_browse_name_en_US
https://github.com/metasfresh/metasfresh/issues/1742

#1742  Translation for en_US in WebUI - Document Outbound

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464940_sys_gh1782-password-field-out-myProfile.sql

Taking out the Password Field from myProfile and minor Advanced Edit
Adjustments.
FRESH-2563 https://github.com/metasfresh/metasfresh/issues/1782

#1782 Taking out the Password Field from myProfile

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464970_sys_gh1798-board-prototype-sales-opportunity-webui.sql

Adding an initial prototype Dashboard for Testing purpose.
FRESH-2575 https://github.com/metasfresh/metasfresh/issues/1798

#1798 Prototype Dashboard for Board frontend development

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5464950_sys_gh1794-adv-edit-bpartner-customer-webui.sql

Adding the first Prototype of Advanced Edit Layout to Businesspartner
Window and Customer Subtab.
FRESH-2573 https://github.com/metasfresh/metasfresh/issues/1794

#1794 Advanced Edit: Business Partner Main View and Customer

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465120_sys_gh1801-my-profile-trl-en-us.sql

Adding the Translation of Fiels, System Elements to en_US for window May Profile.
FRESH-2584 https://github.com/metasfresh/metasfresh/issues/1801

#1801 Translation of My Profile Window to en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465140_sys_gh1805-picking-window-webui.sql

Adding the Picking Window Grid View for Packages to WebUI Menu.
FRESH-2597 https://github.com/metasfresh/metasfresh/issues/1805

#1805 Add the Picking Window Grid View for Packages to WebUI Menu

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465250_sys_gh1823-procurement-windows-webui.sql

Adding the Procurement Window Definitions to WebUI, 2-column Layout, Sidelist, Grid View and Advanced Edit for
a) PMM_week
b) PMM_weekReport_Event (Reports)
c) PMM_Product
d) PMM_QtyReport_Event (Reports)
e) PMM_Message
FRESH-2624 https://github.com/metasfresh/metasfresh/issues/1823

#1823 New Procurement Windows in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465240_sys_gh1819_pricelist_issotrx.sql

setting issotrx to Y in window pricelist

#1819 make new pricelist a sales pricelist by default

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465240_sys_gh1830_search_field_hu_status.sql

enabling HUstatus and value as search fields

#1830 add filter for HU window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465460_sys_gh1816-vendor-returns-window-webui.sql

Adding the Main and Subtab Layout, 2-column Layout Sidelist and Grid View.
FRESH-2615 https://github.com/metasfresh/metasfresh/issues/1816

#1816 Fix the webui layout for Vendor returns (Lieferanten Rücklieferung) window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465480_sys_gh1845-customer-return-adjustments-webui.sql

Adding adjustments to customer returns main view and subtab layout
FRESH-2635 https://github.com/metasfresh/metasfresh/issues/1845

#1845 Adding adjustments to customer returns main view and subtab layout

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465470_sys_gh1836-empties-receive-window-adjustments.sql

Adding adjustments to empties receive window in webui, Main View and
Subtab changed.
FRESH-2635 https://github.com/metasfresh/metasfresh/issues/1836

#1836 Adjustments for Empties Receive Window WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465550_sys_gh1839-period-control-window-webui.sql

New window for Period and Period Control in WebUI, allowing the maintenance oaf calender Periods in WebUI.
FRESH- 2637 https://github.com/metasfresh/metasfresh/issues/1839

#1839 New Window for Period & Period Control in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465605_sys_gh1857-ui-components-message-translation-webui.sql

Adding the ad_messages in de_DE for different static webui elements
FRESH-2666 https://github.com/metasfresh/metasfresh/issues/1857

#1857 Adding the ad_messages for different static webui elements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465930_sys_gh1865_add_field_webui_role.sql

https://github.com/metasfresh/metasfresh/issues/1865

#1865 add is webui role to advanced edit of role window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5465950_sys_gh1877-action-trl-hu-editor-webui.sql

Adding the Translations for Cuistomer and Vendor Returns Quickaction names.
FRESH-2703 https://github.com/metasfresh/metasfresh/issues/1877

#1877 Translations de_DE for Handling Unit QuickActions

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466060_sys_gh1884_delete_bookmark.sql

deletes bookmark menu for user metasfresh allowing fallback to full menu
https://github.com/metasfresh/metasfresh/issues/1884

#1884 make sure no bookmarks for user metasfresh so fallback menu is displayed

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466060_sys_gh1882_add_role_webui.sql

addressing the case when the record already exists. thx @metas-ts
https://github.com/metasfresh/metasfresh/issues/1882

#1882 assign role webui to IT

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466110_sys_gh1786-flatrate-conditions-window-webui.sql

Creating the new Window for Flatrate Terms/ Conditions in WebUI. Adding the 2-column Layout, GridView, Sidelist and Advanced Edit. Done for Main Viw and Subtabs.
FRESH-2564 https://github.com/metasfresh/metasfresh/issues/1786

#1786 New Window for Flatrate Conditions in Webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466120_sys_gh1788-flatrate-transition-window-webui.sql

Creating a new Window for Flatrate Transition in WebUI. Includes 2-column Layout, Advanced Edit, Sidelist, Grid View.
FRESH-2567 https://github.com/metasfresh/metasfresh/issues/1788

#1788 New Window for Flatrate Transition in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466130_sys_gh1890-shipment-window-webui.sql

Adjustment to the Shipment Window Main View, Advanced Edit and Grid View.
FRESH-2724 https://github.com/metasfresh/metasfresh/issues/1890

#1890 Harmonize the Shipment Window to our current Look&Feel concept

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466210_sys_gh1900-select-all-lines-bugfix-webui.sql

Adjusting the Translation of the select all lines caption to avoid Bug
in Frontend
FRESH-2734 https://github.com/metasfresh/metasfresh/issues/1900

#1900 Migration Script for "Select all lines count"

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466260_sys_gh1896-adjustment_product-planning-window-webui.sql

Adjustments to the Product Planning Window, Main View and Subtabs
FRESH-2734 https://github.com/metasfresh/metasfresh/issues/1896

#1896 Adjustments to the Product Planning Window, Main View and Subtabs

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466130_sys_gh1890-shipment-window-webui.sql

Minor Bugfix because of failed SQL rollout.
FRESH-2724 https://github.com/metasfresh/metasfresh/issues/1890

#1890 Minor Bugfix because of failes SQL rollout

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_description.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_details.jrxml

https://github.com/metasfresh/metasfresh/issues/1875

#1875 make fields fit in the page on ordercheckup

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/HUReportExecutor.java

1905: "Wareneingangsetikett LU (Jasper)" prints >200 pages 
Task-Url: https://github.com/metasfresh/metasfresh/issues/1905

#1905 Collect all HU-IDs within one trx and discard duplicates

---

de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/terminal/FreshProductKey.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUInOutBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/CustomerReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/ManualCustomerReturnInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/MultiCustomerHUReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/MultiVendorHUReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/HUPackingMaterialsCollector.java

https://github.com/metasfresh/metasfresh/issues/1869
https://metasfresh.atlassian.net/browse/FRESH-2690

Gh1869 Customer returns created from HUs

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466430_sys_gh449-key-field-kpi-translation-webui.sql

Adding the ,missing Key Field to KPI Translation window in WebUI
FRESH-2561 https://github.com/metasfresh/metasfresh-webui-api/issues/449

https://github.com/metasfresh/metasfresh-webui-api/issues/449 Adding the Key Field to KPI Translation window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466460_sys_gh1919-static-elements-translations-webui.sql

Adding new Translations for static element captions in WebUI.
FRESH-2766 https://github.com/metasfresh/metasfresh/issues/1919

#1919 Additional static element Translations

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466531_sys_gh1925-window-allotment-webui.sql

Adding a new Window for Allotmant Maintenance in Webui. Creating the 2-column Layout, Grid View and Sidelist for Main View and Subtabs.
FRESH-2779 https://github.com/metasfresh/metasfresh/issues/1925

#1925 Window for C_Allotment in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466630_sys_gh1854-seqno-qtyreceived-ordered-materialreceipt.sql

Adjustment of Sequence for Fields QtyReceived/ QtyOrdered for TU/CU
FRESH-2662 https://github.com/metasfresh/metasfresh/issues/1854

#1854 Adjustment of Sequence for Fields QtyReceived/ QtyOrdered for TU/CU

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466650_sys_gh1787-quality-inspection-conference-webui.sql

New Window for Quality Inspection Conference Results in WebUI. Main View Layout, SUbtabs Layout, Sidelist and Grid View. Adding Window to WebUI menu.
FRESH-2565 https://github.com/metasfresh/metasfresh/issues/1787

#1787 New Window for Quality Inspection Conference Results in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466660_sys_gh1933-menu-trl-en-us-webui.sql

Translating Menu Entries and Window/ Tab Names for en_US Language included in WebUI Menu.
FRESH-2788 https://github.com/metasfresh/metasfresh/issues/1933

#1933 Menu Translations for Language en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5466770_sys_gh1949-inventory-valuation-report-webui.sql

Adding the Inventory Valuation Report to WebUI menu
FRESH-2815 https://github.com/metasfresh/metasfresh/issues/1949

#1949 Adding Inventory Valuation Report to WebUI menu

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467180_sys_gh1951-esr-window-webui.sql

Adding the Window Configuration for Swiss ESR Payment Import in WebUI. Main View with 2-column Layout, GridView, Sidlist and Advanced Edit for Subtabs.
FRESH-2818 https://github.com/metasfresh/metasfresh/issues/1951

#1951 Window for Swiss ESR Payment Import in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467250_sys_gh1954-contract-window-webui.sql

Adding the Layout for Contract Window in WebUI. Including the 2-column Layout, Grid View, Siede List and Advanced Edit.
FRESH-2822 https://github.com/metasfresh/metasfresh/issues/1954

#1954 Different adjustments for Contract Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467400_sys_gh1960-async-workpackage-window-webui.sql

Add window asynchronous workpackage queue to webui. 2-column Main View Layout, Grid View, Sidelist.
FRESH-2835 https://github.com/metasfresh/metasfresh/issues/1960

#1960 Add window asynchronous workpackage queue to webui

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/JavaProcess.java
de.metas.adempiere.adempiere/base/src/test/java/de/metas/process/ProcessClassInfoTests.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_Close.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_ReOpen.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ShipmentSchedule_CloseShipmentSchedules.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5467430_sys_gh1874_ad_messages_and_stuff.sql

adapt processes for multi-line; AD_Messages etc; test RunOutOfTrx logic
#1874: Material Receipt multiselect Close Lines 
Task-Url: https://github.com/metasfresh/metasfresh/issues/1874

#1874: Material Receipt multiselect Close Lines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467500_sys_gh1943-bpgroup-window-webui.sql

Adding the Layout for Business Partner Group Advanced edit and Main View. Adding Translations. Improving Grid View and Sidelist Layout.
FRESH-2802 https://github.com/metasfresh/metasfresh/issues/1943

#1943 Window Business Partner Group Advanced Edit

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467530_sys_gh1938-greeting-window-webui.sql

Adding 2-column MainView, GridView and Sidelist to Greeting Window in WebUI. Adding Translations for en_US and renaming Fields for de_DE.
FRESH-2793 https://github.com/metasfresh/metasfresh/issues/1938

#1938 Adjust Window Greeting in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467550_sys_gh1786-flatrate-term-window-webui.sql

Adding a Fix for a Bug in Flatrate Term Window in Webui, that prevented
saving of new Flatrate Terms.
FRESH-2564 https://github.com/metasfresh/metasfresh/issues/1786

#1786 Fix for reported Bug in Integration Test

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467560_sys_gh1939-partner-relation-window-webui.sql

Adding 2-column Main View, Grid View, Sidelist to the Business Partner Relations Window in WebUI.
FRESH-2794 https://github.com/metasfresh/metasfresh/issues/1939

#1939 Adjust the Business Partner Relations Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467590_sys_gh1944-request-type-window-webui.sql

Minor Request Type Window adjustments. Renaming Field Names,
Translations, Grid View Layout.
FRESH-2803 https://github.com/metasfresh/metasfresh/issues/1944

#1944 Request Type Window adjustments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467620_sys_gh1941-outbound-log-window-layout-webui.sql

Adjusting the Layout of the Document Outbound Window. Adjusting Translations and renaming Fields.
FRESH-2799 https://github.com/metasfresh/metasfresh/issues/1941

#1941 Subtab Layout for Window Outbound Document

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467630_sys_gh1942-payment-term-window-webui.sql

Adjusting the Payment Terms Window to the current concept. New Sequence, chcinign Fieldnames and adding Translations. Main view and Subtab Layout.
FRESH-2801 https://github.com/metasfresh/metasfresh/issues/1942

#1942 Payment Terms Window in WebUI

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Average_Product_Prices.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5467520_sys_gh1969_add_average_product_prices_function.sql

https://github.com/metasfresh/metasfresh/issues/1969

#1969 add average_product_prices function

---

de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Inventory.java
de.metas.acct.base/src/main/java-legacy/org/compiere/process/FactAcctReset.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Inventory.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Inventory.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/minventory/api/IInventoryDAO.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/minventory/api/impl/InventoryDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/InventoryAllocationDestination.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/model/I_M_InventoryLine.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/IInventoryLine_HandlerDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/InventoryLine_HandlerDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_InventoryLine_Handler.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_Inventory_Handler.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLineAggregator.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5467340_sys_gh1604_Add_POReference_In_Inventory.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5467380_sys_gh1604_AddIsInvoiceCand_In_InventoryLine.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5467450_sys_gh1604_Add_InventoryLine_ICHandler.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5467510_sys_gh1604_Add_Inventory_ICHandler.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5467610_sys_gh1604_Relation_Garbage_InvoiceCandidate.sql

https://metasfresh.atlassian.net/browse/FRESH-2346
https://github.com/metasfresh/metasfresh/issues/1604

Gh1604 Invoice candidates for material disposal

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467640_sys_gh1929-WEBUI_AD_Message_Import_Before.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467641_sys_gh1929-WEBUI_AD_Message_dump.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467642_sys_gh1929-WEBUI_AD_Message_Trl_dump.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467643_sys_gh1929-WEBUI_AD_Message_Import_After.sql

Translate & export webui messages. Adding Migration Scripts to Update the static elements in webui.
FRESH-2781 https://github.com/metasfresh/metasfresh/issues/1929

#1929 Translate & export webui messages

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467650_sys_gh1940-bpartner-subtabs-adjustment-webui.sql

Adding different Adjustments to Business Partrner Window and Subtabs in WebUI. Harmonized the Look and Feel of Advanced Edit and Grid View in all Subtabs (vendor, location, contact, bank account, print format, status). Added Translations, renamed Fields.
FRESH-2800 https://github.com/metasfresh/metasfresh/issues/1940

#1940 Subtabs Layout for Business Partner Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467660_sys_gh1886-internal-use-hu-action-webui.sql

Add the Internal Use Action to Handling Unit Editor in WebUI
FRESH-2876 https://github.com/metasfresh/metasfresh/issues/1986

#1986 Add the Internal Use Action to Handling Unit Editor in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467740_sys_gh1993-widget-width-S-M-L-webui.sql

Initializing and setting all Element Widget Sizes that don't fiot to the generic st width bases on widget type.
FRESH-2897 https://github.com/metasfresh/metasfresh/issues/1993

#1993 Set default Widget width for certain Columns

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467750_sys_gh1996-remove-client-from-gridview-webui.sql

Removing all AD_Client_ID from GridView and SideList in WebUI Elements
FRESH-2902 https://github.com/metasfresh/metasfresh/issues/1996

#1996 Take out all AD_Client_ID from GridView in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467770_sys_gh2001-selectioncolumn-filter-webui.sql

Adding additional default filters to all windows and removing filters
that make no sense.
FRESH-2904 https://github.com/metasfresh/metasfresh/issues/2001

#2001 Adding additional default filters to all windows

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467860_sys_gh2007-crm-adjustments-webui.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467861_sys_gh2007-widget-width-S-M-L-webui.sql

Adding diverse Adjustments from User Feedback to various CRM Windows.
FRESH-2916 https://github.com/metasfresh/metasfresh/issues/2007

#2007 Feedback WebUI CRM

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5467880_sys_gh2009-price-adjustments-webui.sql

Adding Adjustments for Product Price and Pricelist Window
FRESH-2917 https://github.com/metasfresh/metasfresh/issues/2009

#2009 Adding Adjustments for Product Price and Pricelist Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468010_sys_gh2013-fix-broken-included-tabs-webui.sql

Recreating a broken Tab in Manufacturing Order.
FRESH-2934 https://github.com/metasfresh/metasfresh/issues/2013

#2013 Broken Included Tabs to be redone

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468020_sys_gh2015-pricelist-schema-window-webui.sql

Creating the Price List Schema WIndow in WebUI. Adding the 2-column Layout, Sidelist, gridView and Subtab Layout.
FRESH-2935 https://github.com/metasfresh/metasfresh/issues/2015

#2015 Create Window Price List Schema in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468060_sys_gh2017-pricing-rule-window-webui.sql

Adding the 2-column Layout for Main View and Configuration of Sidelist and Grid View for Pricing Rule Window.
FRESH-2936 https://github.com/metasfresh/metasfresh/issues/2017

#2017 Create Window Pricing Rule in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468080_sys-gh2020-system-conf-window-webui.sql

Adding the new Window for System Configuration to WebUI. Includuing Main View, Grid View, Sidelist.
FRESH-2938 https://github.com/metasfresh/metasfresh/issues/2020

#2020 Add System Configuration Window to WebUI

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IADProcessDAO.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessPreconditionsResolution.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/impl/ADProcessDAO.java
de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/form/IFreshPackingItem.java
de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/service/IPackingContext.java
de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/service/impl/HU2PackingItemsAllocator.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPickingSlotBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/AbstractShipmentScheduleQtyPickedBuilder.java
de.metas.handlingunits.base/src/main/sql/postgresql/system/5467850_sys_gh503webui_M_Picking_Candidate_add_Processed.sql
de.metas.parent/pom.xml
de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/picking/model/I_M_Picking_Candidate.java
de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/picking/model/X_M_Picking_Candidate.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/form/PackingItemsMap.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5467850_sys_gh503webui_WEBUI_Picking_M_Pricking_Candidate_Processed.sql
de.metas.util/src/main/java/de/metas/i18n/ITranslatableString.java

https://github.com/metasfresh/metasfresh-webui-api/issues/503

Gh503 webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468160_sys_gh2027-bank-account-finetuning-webui.sql

Finetuning the Window for Bankaccount. Adjusting missing Fields, Translations. Rearranging Advanced Edit. Rearranging Subtab Layout and Grid View. Adding Primary Key to Subtab Table.
FRESH-2945 https://github.com/metasfresh/metasfresh/issues/2027

#2027 Fine Tuning of Window Bankaccount in WebU

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468170_sys_gh2028-valid-combination-webui.sql

Adding a new Window to Webui: Account Combination.
Included in menu under Financials. Main View, Grid View, Sidelist and Advanced Edit created.
FRESH-2946 https://github.com/metasfresh/metasfresh/issues/2028

#2028 New Window for Validcombination in WebUI

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/OrderBL.java

* It was just a typo
https://metasfresh.atlassian.net/browse/FRESH-2912
https://github.com/metasfresh/metasfresh/issues/2005

#2005 invoiced and delivered status in order

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5468150_sys_gh2022_Add_boilerPlateEval_PrimaryKey.sql
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5468110_sys_gh2022webui_Textvariablen_Window.sql

https://github.com/metasfresh/metasfresh/issues/2022
https://metasfresh.atlassian.net/browse/FRESH-2939

Gh2022 window Textvariablen in webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468420_sys_gh2038-bpartner-b2c-webui.sql

Creating a new Window for Businesspartner B2C Companies. Adding new Menu for Extended Windows.
FRESH-2955 https://github.com/metasfresh/metasfresh/issues/2038

#2038 Adjusted Business Partner Window for Small Companies

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468460_sys_gh1994-sales-invoice-window-improvement-webui.sql

Adjustments for the Sales Invoice Window, rearranging elemets to achieve a haronized Look and Feel as Document Window. Adding Translations for en_US Locale.
FRESH-2900 https://github.com/metasfresh/metasfresh/issues/1994

#1994 Window Design WebUI: Adjust Sales Invoice Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468590_sys_gh2029-account-elements-window-webui.sql

Adding a New Window for Accounts and Elements in WebUI. 2-column Layout for Main View. Also Grid View and Sidelist for Main View and Subtabs. Additional Field Translations.
FRESH-2947 https://github.com/metasfresh/metasfresh/issues/2029

#2029 New Window for Accounts and Elements in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468770_sys_gh2021-payment-window-webui.sql

Adding Layout Adjustments to the Payment Window in WebUI. 2-column Layout and now considering the latest Design Guidelines for WebUI.
FRESH-2996 https://github.com/metasfresh/metasfresh/issues/2071

#2071 Window Design WebUI: Payment Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468820_sys_gh2077-payment-allocation-window-webui.sql

Window Design WebUI: Payment Allocation Window. Refining the Layout Concept of the Payment Allocation Window in WebUI
FRESH-3000 https://github.com/metasfresh/metasfresh/issues/2077

#2077 Window Design WebUI: Payment Allocation Window

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468910_sys_gh2080-payment-allocation-trl-webui.sql

Adding missing Translations for en_US in Payment Allocation Window in WebUI
FRESH-3002 https://github.com/metasfresh/metasfresh/issues/2080

#2080 Window Design WebUI: Payment Allocation Translation en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468960_gh2096-businesspartner-b2c-location-webui.sql

Adjusting the Window Businesspartner B2C. Adding the missing Location Editor. Further Adjustment on Layout for new Document List Tab.
FRESH-3022 https://github.com/metasfresh/metasfresh/issues/2096

#2096 Businesspartner B2C Location Editor missing

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468961_sys_gh2086-sales-order-window-webui.sql

Adding adjustments to sales order window in webui according to main view
advanvced edit
FRESH-3008 https://github.com/metasfresh/metasfresh/issues/2086

#2086 Adding adjustments to sales order window in webui according to main view advanvced edit

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5468962_sys_gh2087-purchase-order-webui.sql

Adjusting the primary Layout in Main View. 
Rearranging Advanced Edit in Purchase Order Window. Adding Translations for de_DE
FRESH-3009 https://github.com/metasfresh/metasfresh/issues/2087

#2087 Purchase Order Advanced Edit Window in main View

---

de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/camt54/ESRDataImporterCamt54.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/impl/camt54/ReferenceStringHelper.java
de.metas.payment.esr/src/main/sql/postgresql/system/5469180_sys_gh2118_sysconfig_skip_unsupported_lines.sql
de.metas.payment.esr/src/main/sql/postgresql/system/5469180_sys_gh2119_ESR_Import_add_sql_col.sql
de.metas.payment.esr/src/test/java/de/metas/payment/esr/dataimporter/impl/camt54/ESRDataImporterCamt54Tests.java

ESR - add sysconfig to ignore non-credit lines
https://github.com/metasfresh/metasfresh/issues/2118
ESR - Show actual number of transactions
https://github.com/metasfresh/metasfresh/issues/2119

ESR tasks 2118 and 2119

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469270_sys_gh2132_add_readonly_logic.sql

make tab readonly if user is not a systemuser

#2132 add readonly logic to assign role to user

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469360_sys_gh2134-WEBUI_AD_Message_Import_Before.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469361_sys_gh2134-WEBUI_AD_Message_dump.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469362_sys_gh2134-WEBUI_AD_Message_Trl_dump.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469363_sys_gh1929-WEBUI_AD_Message_Import_After.sql

Migrating all AD_Messages from w101 to make sure that none are missing
after development.
FRESH-3087 https://github.com/metasfresh/metasfresh/issues/2134

#2134 Export all webui AD_Messages from w101

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469370_sys_gh2084-vendor-returns-window-adjustments-webui.sql

Adding Adjustments to vendor Returns Window to harmonize the look and feel to our current WebUI Window Guidelines.
FRESH-3006 https://github.com/metasfresh/metasfresh/issues/2084

#2084 Window Design WebUI: Vendor Returns

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469390_sys_gh2048-sales-order-candidates-window-webui.sql

Configuration of the Sales Order Candidates Window in Webui including Main View, grid View, Sidelist and Advanced Edit.
FRESH-2963 https://github.com/metasfresh/metasfresh/issues/2048

#2048 Window Design WebUI: Sales Order Candidates

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469410_sys_gh2051-material-tracking-window-webui.sql

Adjustment to the Material Tracking Window in WebUI. Adopting the current Window Design/ look & Feel Concept. Adding Translations for en_US.
FRESH-2966 https://github.com/metasfresh/metasfresh/issues/2051

#2051 Window Design WebUI: Material Tracking

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469440_sys_gh2140-shipment-schedule-adjustments-webui.sql

Adjusting the Shipment Schedule Window to current Design Concept for Transaction Data Windows. Changing Grid View, Main View, Advanced Edit and Subtab for Shipment & Picking.
FRESH-3092 https://github.com/metasfresh/metasfresh/issues/2140

#2140 Window Design WebUI: Shipment Schedule

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469460_sys_gh2150-shipment-window-webui.sql

Adopting the Shipment Window to our current Concept for Document Windows. Adden Translations. Rearranged Fields in GridView, Main View and Subtab.
FRESH-3104 https://github.com/metasfresh/metasfresh/issues/2150

#2150 Window Design WebUI: Shipment

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469500_sys_gh2163_disabling_insert_new_record_b2c_window.sql

#2163 Do not show new button in B2C Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469520_sys_gh2161-business-partner-group-webui.sql

Adopting Business Partner group to current Design Concept for Master Data Windows
FRESH-3117 https://github.com/metasfresh/metasfresh/issues/2161

#2161 Window Design WebUI : Business Partner Group

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469540_sys_gh2162-doc-outbound-config-webui.sql

Adopting the Window Layout & Translations to current Design Concept
FRESH-3118 https://github.com/metasfresh/metasfresh/issues/2162

#2162 Adopting the Window Layout & Translations to current Design Concept

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469560_sys_gh2167-product-window-adjustments-webui.sql

Adjustments in product window adopting to current design concept
FRESH-3120 https://github.com/metasfresh/metasfresh/issues/2167

#2167 Adjustments in product window adopting to current design concept

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469600_sys_gh2169-attribute-window-adjustments-webui.sql

Adopting the Window Attributes to the current Design Guidelines.
FRESH-3122 https://github.com/metasfresh/metasfresh/issues/2169

#2169 Window Design WebUI : Attributes

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469610_sys_gh2170-bom-window-adjustments-webui.sql

Adopting Bom Window to Design Guidelines.
FRESH-3123 https://github.com/metasfresh/metasfresh/issues/2170

#2170 Window Design WebUI : Bill of Materials

---

de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5469550_sys_gh2142_SelectHUs_For_Shipment.sql

https://github.com/metasfresh/metasfresh/issues/2142

#2142 Process for HU Selection in shipment

---

de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRLineHandlersService.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRLineHandlersService.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRDataLoaderUtil.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/spi/impl/DefaultESRLineHandler.java

#2116 Use handler when matching partner in ESR import

Improve handler

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469630_sys_gh2174_uom-window-adjustments-webui.sql

Adoption of UOM window to current design Guidelines
FRESH-3125 https://github.com/metasfresh/metasfresh/issues/2174

#2174 Adoption of UOM window to current design Guidelines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469640_sys-gh2173-discount-window-adjustments-webui.sql

Adopting the Discount Window in WebUI to the current Design Guidelines. Adding missing Translations for de_DE.
FRESH-3126 https://github.com/metasfresh/metasfresh/issues/2173

#2173 Window Design WebUI : Discount Schema

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469650_sys_gh2183-sales-order-window-adjustments-webui.sql

Adopting the Sales Order Window to current Design guidlines including Main View, Enhanced Edit mode, included Tabs. Adding missing Translations to de_DE.
FRESH-3134 https://github.com/metasfresh/metasfresh/issues/2183

#2184 Window Design WebUI : Sales Order

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469500_sys_gh2136_adding_file_view.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469500_sys_gh2136_adding_history_to_b2c.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469500_sys_gh2136_adding_history_to_b2c_view.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469500_sys_gh2136_setting_sort_order.sql

#2136 add history to b2b window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469680_sys-gh2194-vendor-dropship-webui.sql

Adding Vendor ID for Drop Shimnet to Shipment Candidates
FRESH-3143 https://github.com/metasfresh/metasfresh/issues/2194

#2194 Adding Vendor ID for Drop Shimnet to Shipment Candidates

---

de.metas.acct.base/src/main/java/de/metas/acct/process/GL_Journal_GenerateYearEnding.java

https://github.com/metasfresh/metasfresh/issues/2141

#2141 filter account by org

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469690_gh2196-bank-statement-window-adjustments-webui.sql

Adopting the Bank Statement Widnow to the current design Guidelines. Adding missing Translations for de_DE.
FRESH-3145 https://github.com/metasfresh/metasfresh/issues/2196

#2196 Window Design WebUI : Bank Statement

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469710_sys_gh2207-product-window-adjustments-webui.sql

Adding detail Adjustments in Subtabs for guidelines adoption. Adding
missing Translations for de_DE.
FRESH-3157 https://github.com/metasfresh/metasfresh/issues/2207

#2207 Window Design WebUI : Product

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469720_sys_gh2202-tourversion-window-adjustments-webui.sql

Adjustments to Tour Version Window in WebUI adopting to guidelines.
Adding Translations for de_DE and adding missing Fields in Grid and Main
Window.
FRESH-3151 https://github.com/metasfresh/metasfresh/issues/2202

#2202 Window Design WebUI : Tour Version

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469730_sys_gh2203-deliverydays-window-adjustments-webui.sql

Design Adjustments, adding missing Fields and Translations to Grid View,
Main View and Subtabs.
FRESH-3153 https://github.com/metasfresh/metasfresh/issues/2203

#2203 Window Design WebUI : Delivery Days

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_v2.jrxml

https://github.com/metasfresh/metasfresh/issues/2097

#2097 update pattern for sum fields

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469670_sys_gh2050-purchase-order-window-adjustment-webui.sql

Adjustments because design guidelines for transactional data
FRESH-2965 https://github.com/metasfresh/metasfresh/issues/2050

#2050 Adjustments because design guidelines for transactional data

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469800_sys_gh2198-bankstatement-reference-webui.sql

Creates a new Window for Bank Statement Line References. Adding the Window Layout for Webui, includuing Sidelist and Grid View.
FRESH-3147 https://github.com/metasfresh/metasfresh/issues/2198

#2198 New Window for filtered Bank Statement Line References

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469850_sys_gh2226-new-gl-journal-window-wo-batch-webui.sql

Creating the new Window for GL_Journal in WebUI. This new Window shall avoid the Batch Level, used before. Added Main View, Grid View and Sidelist.
FRESH-3175 https://github.com/metasfresh/metasfresh/issues/2226

#2226 New Window for GL Journal in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469945_sys_gh2217-vendor-returns-window-adjustments-webui.sql

Adopting the Vendor Returns Window to WebUI design Guidelines
FRESH-3162 https://github.com/metasfresh/metasfresh/issues/2217

#2217 Adopting the Vendor Returns Window to WebUI design Guidelines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469950_sys_gh2193-tour-version-window-webui-adoption.sql

Adopting the Tour Version Window to WebUI Guidelines
FRESH-3162 https://github.com/metasfresh/metasfresh/issues/2193

#2193 Adopting the Tour Version Window to WebUI Guidelines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469960_sys_gh2193-order-by-date-vendor-return.sql

Adding the OrderBy desc for Date in Grid View.
FRESH-3162 https://github.com/metasfresh/metasfresh/issues/2193

#2193 Adding OrderBy desc for Date

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5469960_sys_gh2154-customer-returns-window-improvements-webui.sql

Adding improvements to customer returns window in webui
FRESH-3108 https://github.com/metasfresh/metasfresh/issues/2154

#2154 Adding improvements to customer returns window in webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470040_sys_gh2192-bp-group-window adjustments-webui.sql

Adjustments to the Business Partner Window in Webui.
FRESH-3140 https://github.com/metasfresh/metasfresh/issues/2192

#2192 Window Design WebUI : Business Partner Group Improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470050_sys_gh2255-validvombination-adjustments-webui.sql

Adapting Validcombination Window to current Design Guidelines. Adding
Translations for de_DE
FRESH-3200 https://github.com/metasfresh/metasfresh/issues/2255

#2255 Adapting Validcombination Window to current Design Guidelines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470070_sys_gh2258_add_due_date_request.sql

#2258 add due date to request grid view

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470060_sys_gh2229-productcosts-window-webui.sql

Adding a new Window for ProductCosts to WebUI. Adapting the Layout to out current design Guidelines. Main View, Grid View, Sidelist for Main Window and included Subtabs. Adding Translations where missing for de_DE.
FRESH-3179 https://github.com/metasfresh/metasfresh/issues/2229

#2229 New Window for Product Costs in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470090_sys_gh2232-activity-doc-window-webui.sql

Adding a new Window for Activity Docs Maintenance in WebUI. Main View, grid View and Sidelist added.
FRESH-3176 https://github.com/metasfresh/metasfresh/issues/2232

#2232 New Window for c_activity in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470100_sys_gh2230-cost-center-window-webui.sql

Adding a new Window to WebUI Menu and creating the Main View, Grid View and Advanced Edit.
FRESH-3178 https://github.com/metasfresh/metasfresh/issues/2230

#2230 New Window for Fact_Acct_ActivityChangeRequest

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470110_sys_gh2235-shipper-window-webui.sql

Adding the Layout for the new Shipper Window in WebUI. Main View, Grid View, Sidelist and Advanced Edit.
FRESH-3181 https://github.com/metasfresh/metasfresh/issues/2235

#2235 New window for Shipper in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470130_sys_gh2234-payment-selection-window-webui.sql

Adding new Window for Payment Selection in WebUI. Added Menu entry. Main View, Sidelist, grid View and Included tabs Layout done. Added some missing Translations for en_US.
FRESH-3182 https://github.com/metasfresh/metasfresh/issues/2234

#2234 New Window for Payment Selection in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470190_sys_gh2267-hardware-printer-window-webui.sql

Adding the new Window Printer to WebUI and WebUI Menu. Created the 2-column Main View Layout and Grid View, Advanced Edit and Sidelist configuration.
FRESH-3209 https://github.com/metasfresh/metasfresh/issues/2267

#2267 New Window for Hardware drucker in WebUI

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_OrderCheckup_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5470000_sys_gh2237_add_label_in_ordercheckup_jasper.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5470001_sys_gh2237_add_label_in_ordercheckup_barcode_jasper.sql

https://github.com/metasfresh/metasfresh/issues/2237

#2237 add label on rdercheckup jasper

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470290_sys_gh2270-async-batch-type-window-webui.sql

Adding the new Window for Async Batch Type in WebUI. Main View w/ 2-column Layout, Grid View, Sidelist and Field Translations.
FRESH-3207 https://github.com/metasfresh/metasfresh/issues/2270

#2270 New Window for Async Batch Type in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470320_sys_gh2289-ad-pinstance-window-webui.sql

Adding a new Window for Process Audit Maintenance to WebUI menu. Created the 2-column Main View and Grid View, Sidelist, Layout for Included Tabs and Advanced edit.
FRESH-3240 https://github.com/metasfresh/metasfresh/issues/2289

#2289 New Window for Async Batch Parameters/ Process Audit

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470420_sys_gh2294-picking-window-webui.sql

Adding the initial Window Layout for the Picking Window in WebUI, Grid View, order By, Filter Criteria
FRESH-3244 https://github.com/metasfresh/metasfresh/issues/2294

#2294 Window Layout for Picking Window in WebUI

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/InArrayQueryFilter.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/POJOWrapper.java
de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/form/swing/FreshSwingPackageItems.java
de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/terminal/FreshProductKey.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HUIteratorListenerAdapter.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUIteratorListener.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPickingSlotBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUQueryBuilder.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPickingSlotBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQueryBuilder.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageEngine.java
de.metas.handlingunits.base/src/main/sql/postgresql/system/5470370_gh557-api_M_Picking_Candidate_perf.sql
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUPickingSlotBL_RetrieveAvailableHUsToPickTests.java
de.metas.storage/src/main/java/de/metas/storage/IStorageEngine.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5470260_gh557-api_remove_process_WEBUI_Picking_AddHUToPickingSlot.sql

Picking Window: Open HU Selection window filtering

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUContext.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPackingMaterialsCollector.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IMutableHUContext.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/InventoryAllocationDestination.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/MutableHUContext.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/CustomerReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentPackingMaterialLinesBuilder.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/VendorReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/api/impl/HUPackingMaterialMovementLineBuilder.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/HUPackingMaterialCollectorSourceFactory.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/HUPackingMaterialDocumentLineCandidate.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/HUPackingMaterialsCollector.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/IHUPackingMaterialCollectorSource.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/InOutLineHUPackingMaterialCollectorSource.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/InOutProducerFromReceiptScheduleHU.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/MovementLineHUPackingMaterialCollectorSource.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/HUTestHelper.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformServiceTests.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformTestsBase.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/HUTransformTracingTests.java
de.metas.handlingunits.base/src/test/java/de/metas/inoutcandidate/spi/impl/HUPackingMaterialsCollectorTest.java

https://github.com/metasfresh/metasfresh/issues/2112

Gh2112 Enhancements in returns reversal and movements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470510_sys_gh2300-doc-outbound-adjustments-webui.sql

Rearranging the Doc Outbound window. Adapting to current design Guidelines. Adding missing Fields and Translations. Adding SelectionColumns for Filtering.
FRESH-3249 https://github.com/metasfresh/metasfresh/issues/2300

#2300 Doc Outbound missing Columns

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470520_sys_gh2307-period-window-adjustments-webui.sql

Adding Adjustments to Main View, grid View and Advanced edit, also in Included tabes. Adding Translations for en_US Language/ Locale and also for de_DE.
FRESH-3262 https://github.com/metasfresh/metasfresh/issues/2307

#2307 Window Period adjustments, add missing Translations

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470560_sys_gh2314-sales-order-feedback-adjustments.sql

Adding Sales Order detail adjustments from User Feedback
FRESH-3266 https://github.com/metasfresh/metasfresh/issues/2314

#2314 Sales Order detail adjustments from User Feedback

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470570_sys_gh2317-deliverydays-improvements-webui_.sql

Adding minor improvements to Deliverdays Window in WebUI. New Column for
Location in grid View, Adjusted Filter Criteria. Arranging Column
widths.
FRESH-3267 https://github.com/metasfresh/metasfresh/issues/2317

#2317 Adding minor improvements to Deliverdays Window in WebUI

---

de.metas.handlingunits.base/src/main/sql/postgresql/system/5470700_gh2112_Process_CustomerReturn_For_Swing_Version.sql

https://github.com/metasfresh/metasfresh/issues/2112

Gh2112 Old process for Customer return needed in swing version

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/IncludedHUsLocalCache.java

https://github.com/metasfresh/metasfresh-webui-api/issues/567

Shipped HUs are not displayed correctly #567

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/MultiCustomerHUReturnsInOutProducer.java

https://github.com/metasfresh/metasfresh/issues/2112

Gh2112 HU Children IsActive value only from parents

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470710_sys_gh2304-pricelist-window-action-webui.sql

Modifying the Pricelist Window in WebUI. Adding the Process for PLV Generation. Adjusting Fields and adding Translations.
FRESH-3259 https://github.com/metasfresh/metasfresh/issues/2304

#2304 New Action: Create new Product Prices from selected Pricelist Version

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470720_sys_gh2334-default-filter-criteria-webui.sql

Adding default Filter to a selection of WebUI Windows
FRESH-3282 https://github.com/metasfresh/metasfresh/issues/2334

#2334 Default Filter Criteria for selected Windows

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470720_sys_gh2337-purchase-order-detail-adjustments-webui.sql

Adding detail changes to Purchase Order Window in WebUI (Dropshipment,
Dropship BPartner in Grid View).
FRESH-3284 https://github.com/metasfresh/metasfresh/issues/2337

#2337 Adding detail changes to Purchase Order Window in WebUI

---

ReleaseNotes.md
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Column.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Column.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/impexp/ImpFormat.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/ad_field_v.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470760_sys_gh564webui_AD_Column_SelectionColumnSeqNo.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470761_sys_gh564webui_AD_Column_SelectionColumnSeqNo_DDL.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470762_sys_gh564webui_AD_Field_views.sql
de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java

https://github.com/metasfresh/metasfresh-webui-api/issues/564

introduce AD_Column.SelectionColumnSeqNo

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/receiptlabel/label.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5470850_sys_gh2348_update_receipt_label_function.sql

https://github.com/metasfresh/metasfresh/issues/2348

#2348 add vendor and producer value in receipt label

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java

https://github.com/metasfresh/metasfresh/issues/2354

#2354 Set the LU's HU_Status Picked after picking

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470880_sys_gh2352-invoice-window-detail-improvements-webui.sql

Adding detail improvements to Customer Invoice Window in WebUI, Column
Widths in Grid View, Adding Missing Actions (former Buttons) and more.
FRESH-3304 https://github.com/metasfresh/metasfresh/issues/2352

#2352 Adding detail improvements to Customer Invoice Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470910_sys_gh2353-invoice-candidates-improvements-webui.sql

Adding Improvementrs to the Invoice Candidates Window in WebUI.
FRESH-3305 https://github.com/metasfresh/metasfresh/issues/2353

#2353 nvoice Candidates Window in WebUI detail improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5470930_sys_gh2362-default-reports-webui.sql

Adding default reports to webui
FRESH-3310 https://github.com/metasfresh/metasfresh/issues/2362

#2362 Adding default reports to webui

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471000_sys_gh2365-dispo-window-names-adjustments.sql

Adjusting some Window Names, now "Disposition" for de_DE Candidates
Windows
FRESH-3312 https://github.com/metasfresh/metasfresh/issues/2365

#2365 Adjusting some WIndow Names, now "Disposition" for de_DE Candidates Windows

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471060_sys_gh2372-finance-detail-improvements-webui.sql

Adding detail improvements to various finance windows in webui, mostly
adding actions and translations
FRESH-3320 https://github.com/metasfresh/metasfresh/issues/2372

#2372 Adding detail improvements to various finance windows in webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471090_sys_gh2374-shipment-candidates-window-improvement.sql

Adding detail improvements to shipment candidates window in webui
FRESH-3321 https://github.com/metasfresh/metasfresh/issues/2374

#2374 Detail adjustments to Shipment Candidates Window

---

Jenkinsfile

https://github.com/metasfresh/metasfresh/issues/2343

Add code coverage metrics to our builds #2343

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471120_sys_gh2378-procurement-candidates-details-webui.sql

Improving the Visibility in Procurements Candidates Window. Renaming Fields and adding Translations for en_US and de_DE.
FRESH-3326 https://github.com/metasfresh/metasfresh/issues/2378

#2378 Procurement candidates detail Improvements

---

de.metas.edi/src/main/java/de/metas/edi/model/validator/M_InOut.java

https://github.com/metasfresh/metasfresh/issues/2389

edi problem for customer returns #2389

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_de_CH.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_de_DE.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_fr_CH.properties
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_it_CH.properties

#2393 report property "summary" is defined twice in purchase order

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471170_sys_gh2385-picking-slot-window-webui.sql

Creating the new Window for Picking Slot in WebUI, 2-column Layout, Grid View, Sidelist and Translations.
FRESH-3338 https://github.com/metasfresh/metasfresh/issues/2385

#2385 New Window for M_PickingSlot in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471210_sys_gh2386-picking-slot-trx-window-webui_.sql

Creates a new Window in WebUI for Picking Slot Transactions. Added the 2-column Layout, Grid View and Sidelist Layout. Improved field Translations for en_US, de_DE.
FRESH-3340 https://github.com/metasfresh/metasfresh/issues/2386

#2386 New Window for M_PickingSlot_Trx in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471230_sys_gh2381-new-contract-window-webui.sql

Detailed Improvement of Flatrate Term window in WebUI. Created a new Window without Top Level stuff. Added the next Level of Subtabs. Main view w/ 2-column Layout, Sidelist and grid View and Advanced edit. Added Translations for Main View. Subtab translatins in sep. issues following.
FRESH-3336 https://github.com/metasfresh/metasfresh/issues/2381

#2381 New Window for Contract

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471250_sys_gh2406-subscription-history-webui.sql

Creates the new Window for Subscription Prograss in WebUI, as substitute of sub-sub-included-tab for Contract partner window. Adding 2-column Layout, Sidelist and Grid View. Adding Translations for en_US, de_DE.
FRESH-3365 https://github.com/metasfresh/metasfresh/issues/2406

#2406 New Window for C_SubscriptionProgress in WebUI

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/RV_C_Order_MFGWarehouse_Report_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5471271_sys_gh2412_fix_productname_RV_C_Order_MFGWarehouse_Report_Details.sql

https://github.com/metasfresh/metasfresh/issues/2412

#2412 ordercheckup product name function update

---

de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/AbstractQualityReturnsInOutLinesBuilder.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/CustomerReturnsInOutProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/VendorReturnsInOutProducer.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/model/validator/M_InOut.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java

https://github.com/metasfresh/metasfresh/issues/2401

Gh2401 quality issue lines in vendor return

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471280_sys_gh2146-quality-insp-conf-webui.sql

Creates the new Window for LagerKonf Version in WebUI. Adding 2-column Main View, Sidelist and Grid View. Also Included Tab Layout.
FRESH-3373 https://github.com/metasfresh/metasfresh/issues/2416

#2416 New Window for M_QualityInsp_LagerKonf_Version in WebUI

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/InventoryAllocationDestination.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/AbstractQualityReturnsInOutLinesBuilder.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/I_M_InventoryLine.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5471330_sys_gh2401_Add_QualityColumns_In_InventoryLine.sql

https://github.com/metasfresh/metasfresh/issues/2401

Gh2401 invoice candidates for material disposals with issues

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471350_sys_gh2218_ModifyImportFormat.sql

#2218  User would like to import default values for contact and address

#2218 Modify import format

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471380_sys_gh2426-rfq-window-adjustments-webui.sql

Refining Field Layout in RfQ Window. Adding Translations for de_DE and en_US Locale/ Language.
FRESH-3382 https://github.com/metasfresh/metasfresh/issues/2426

#2426 Translation for window "Ausschreibung" in WebUI #2426

---

de.metas.contracts/src/main/java/de/metas/flatrate/api/impl/FlatrateBL.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5471470_sys_gh2434_Make_ad_user_incharge_id_optional.sql

#2434 Make field ad_user_incharge_id from C_Flatrate_Term optional

#2434 ad_user_incharge_id optional

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/impexp/BPartnerImportProcess.java

#2436 Use default values for IsShipTo and isBillTo when importing
bpartner

#2436 Use default values for IsShipTo and isBillTo when importing bpartner

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471500_sys-gh2442-gl-category-webui.sql

Adding new Window for GL Category in WebUI. Adding to WebUI Menu in Finance/Settings. 2-Column Layout created, Sidelist and Grid View too. Adding Translations for de_DE, en_US.
FRESH-3397 https://github.com/metasfresh/metasfresh/issues/2442

#2442 New Window for GL Journal Category in WebUI

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/InventoryAllocationDestination.java

https://github.com/metasfresh/metasfresh/issues/2342

#2342 Collect TUs correctly in garbage

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471550_sys_gh2449-procurement-product-window-adjustment-webui.sql

Adjusting the window Product for Procurement Contracts in WebUI. Removing/ Rearranging Fields. Adding Translations for de_DE, en_US.
FRESH-3406 https://github.com/metasfresh/metasfresh/issues/2449

#2449 Adjust the window Product for Procurement Contracts

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471560_sys_gh2421-flatrateterm-masterdates-webui.sql

Adding new Fields for Masterdates to WebUI FlatrateTerm Window in WebUI
and further adjustments. Adding Translations for en_US and renaming
Fields in de_DE.
FRESH-3378 https://github.com/metasfresh/metasfresh/issues/2421

#2421 Adding new Fields for Masterdates to WebUI FlatrateTerm Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471590_sys_gh2453-reports-missing-webui.sql

Adding missing Reports into WebUI menu (Purchase Trace, Sales Trace,
Movements Statitic and more).
FRESH-3409 https://github.com/metasfresh/metasfresh/issues/2453

#2453 Adding missing Reports into WebUI menu

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/hostkey/api/impl/HostKeyBL.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/user/process/AD_User_ChangePassword.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471640_sys_gh2459_AddBillTo_ShipTo.sql

#2459 shipto and billto contact / user

#2459 AddShipTo and billto

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471681_sys_gh2450-translation-en-packing-instruction.sql

Adding Field Translations for en_US Language
FRESH-3407 https://github.com/metasfresh/metasfresh/issues/2450

#2450 Adding Field Translations for en_US Language

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_BPartner.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/impexp/BPartnerImportProcess.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5471720_sys_gh2474_Add_Language.sql

#2474 Extend Partner Import with ad_language

#2474 Extend Partner Import with ad_language 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472060_sys_gh2503-contract-terms-typo-webui.sql

Minor Typo Fix.
FRESH-3457 https://github.com/metasfresh/metasfresh/issues/2503

#2503 Typo in German Translation of Contract Terms menu Entry

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472070_sys_gh2376-order-candidates-window-adjustment-webui.sql

Adding detail improvements to order Candidates Window in WebUI. Allowing the user to manipulate the Fields completely via Main View.
FRESH-3322 https://github.com/metasfresh/metasfresh/issues/2376

#2376 Detail Improvements to Order Candidates Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472120_sys_gh2090-textsnippets-textvariable-window-webui.sql

Improving the Textvariable and Textsnippet window in WebUI. Rearranging the GridView. Adding Translations for de_DE and en_US.
FRESH-3012 https://github.com/metasfresh/metasfresh/issues/2090

#2090 Improve text Variable Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472160_sys_gh2222-sales-order-adjustments-window-webui.sql

Adding detailed adjustments to Sales Order Window in WebUI, adapting webui design guidelines.
FRESH-3165 https://github.com/metasfresh/metasfresh/issues/2222

#2222 Window Design WebUI : Sales Order Improvements

---

de.metas.business/src/main/java/org/adempiere/impexp/RequestImportProcess.java

#2501 Clean code

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472190_sys_gh2498-returns-windows-improvements-webui.sql

Adding improvements to customer returns window in WebUI. Creating an own
advanced edit section. Adding Filter criteria. Adding Order by on
DocumentNo.
FRESH-3447 https://github.com/metasfresh/metasfresh/issues/2498

#2498 Window Design WebUI: Returns Improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472200_sys_gh2516-picking-preview-list-webui.sql

Adding Picking Preview List to WebUI Menu in Shipping Section
FRESH-3466 https://github.com/metasfresh/metasfresh/issues/2516

#2516 Adding Picking Preview List to WebUI Menu in Shipping Section

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472240_sys_gh2509-picking-windows-trl-webui.sql

Adding Translations for diff. Picking Windows in WebUI.
https://github.com/metasfresh/metasfresh/issues/2509

#2509 Window Design WebUI : Translate Picking Slot Window name in en

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_User.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_User.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/process/ImportUser.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472280_sys_gh2529_AddImporUsers.sql
de.metas.business/src/main/java/org/adempiere/impexp/ADUserImportProcess.java
de.metas.business/src/main/java/org/adempiere/impexp/impl/ImportProcessFactory.java

#2529 Import System users 

---

de.metas.contracts.ait/src/main/java/test/integration/contracts/ContractsHelper.java
de.metas.contracts.ait/src/main/java/test/integration/contracts/flatrate/FlatFeeScenario.java
de.metas.contracts.ait/src/main/java/test/integration/contracts/pricing/ContractPricingUtilTests.java
de.metas.contracts.ait/src/main/java/test/integration/contracts/subscription/SubscriptionTestDriver.java
de.metas.contracts/src/main/java-gen/de/metas/flatrate/model/I_C_Flatrate_Conditions.java
de.metas.contracts/src/main/java-gen/de/metas/flatrate/model/I_C_Flatrate_Term.java
de.metas.contracts/src/main/java-gen/de/metas/flatrate/model/X_C_Flatrate_Conditions.java
de.metas.contracts/src/main/java-gen/de/metas/flatrate/model/X_C_Flatrate_Term.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/inoutcandidate/spi/impl/SubscriptionInOutCandHandler.java
de.metas.contracts/src/main/java/de/metas/flatrate/api/IFlatrateBL.java
de.metas.contracts/src/main/java/de/metas/flatrate/api/impl/FlatrateBL.java
de.metas.contracts/src/main/java/de/metas/flatrate/modelvalidator/C_Flatrate_Conditions.java
de.metas.contracts/src/main/java/de/metas/flatrate/modelvalidator/C_Flatrate_Term.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5472260_sys_gh2395-app_remove_IsNewTermCreatesOrder.sql

remove the column, AD records and code
Drop C_Flatrate_Conditions.IsNewTermCreatesOrder together with java code
#2395

Drop C_Flatrate_Conditions.IsNewTermCreatesOrder together with java code #2395

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472300_sys_gh2583-contract-period-adjustments-webui.sql

Adjust Contract Period Window in WebUI for Subscriptions. Adding Fields and Translations for en_US. Rearranging Layout for Main View and Grid View.
FRESH-3480 https://github.com/metasfresh/metasfresh/issues/2533

#2533 Adjust Contract Period Window in WebUI for Subscriptions

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472340_sys_gh2541_make_product_category_search_field.sql

https://github.com/metasfresh/metasfresh/issues/2541

#2541 Allow filtering by product group in window product

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472450_sys_gh2286-discount-schema-window-webui.sql

Minor Layout Adjustments added to discount window in webUI
FRESH-3237 https://github.com/metasfresh/metasfresh/issues/2286

#2286 Minor Layout Adjustments added to discount window in webUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472460_sys_gh2288-product-category-window-webui.sql

Adding Primary Key for Product Category Accounting Table. Minor Layout Improvements with included Tab primary view and subtab grid view/ advanced edit improvements.
FRESH-3238 https://github.com/metasfresh/metasfresh/issues/2288

#2288 Window Design WebUI : Product Category Improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472480_sys_gh2285-uom-window-layout-adjust-webui.sql

Adding Layout Improvement for UOM Included Tabs
FRESH-3236 https://github.com/metasfresh/metasfresh/issues/2285

#2285 Adding Layout Improvement for UOM Included Tabs

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472500_sys_gh2280-cost-center-translation-en_US-webui.sql

Minor Translation adjustment for en_US
FRESH-3231 https://github.com/metasfresh/metasfresh/issues/2280

#2280 Minor Translation adjustment for en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472510_sys_gh2468-webui-window-client-grid.sql

Adding Improvements to WebUI Windopws in Grid View.
FRESH-3416 https://github.com/metasfresh/metasfresh/issues/2468

#2468 Window Design WebUI: gridview with client

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472830_sys-gh2190-shipment-window-improvements-webui.sql

Adding Improvements to Shipment Window in WebUI. Adding missing Layout Configurations for included Subtabs.
FRESH-3139 https://github.com/metasfresh/metasfresh/issues/2190

#2190 Window Design WebUI: Shipment Improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472860_sys_gh2221-bankstatement-window-improvement-webui.sql

Adding minor improvements to Bank Statement window in WebUI.
FRESH-3164 https://github.com/metasfresh/metasfresh/issues/2221

#2221 Window Design WebUI : Bank Statement Improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5472940_sys_gh2580-subscription-history-included-tab-contract-webui.sql

Adding the Subscription History Window to WebUI Contract Window as included Subtab. Refined the Sidelist, GridView and Main View.
FRESH-3514 https://github.com/metasfresh/metasfresh/issues/2580

#2580 Add Subscription history in Contract window WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473010_sys_gh2271-sales-invoice-layout-improvements-webui.sql

Adjustments to Layout of Sales Invoice window in WebUI.
FRESH-3211 https://github.com/metasfresh/metasfresh/issues/2271

#2271 Window Design WebUI: Adjust Sales Invoice Window Improvements

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473150_sys_gh2590_adding_documentno_product_window.sql

#2590 adding documentnote to product window advanced edit

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Category.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Category.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/CalloutProductCategory.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MProductCategory.java

https://github.com/metasfresh/metasfresh/issues/2598

Gh2598 Callout for product category comply with webui

---

de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/5473240_sys_gh2604-app_perf_indexes_and_view.sql

Printing via standalone client takes too long #2604

---

de.metas.contracts/src/main/java/de/metas/contracts/flatrate/callout/C_Flatrate_Matching.java

https://github.com/metasfresh/metasfresh/issues/2615

#2615 Make flatrate matching callouts webui compliant

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473370_sys_gh2271-sales-order-invoice-default-filter-fix.sql

Fix for the Sales Order default Filter (Doctype, Dateordered)
FRESH-3524 https://github.com/metasfresh/metasfresh/issues/2271

#2271 Fix for the Sales Order and Invoice default Filter

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473400_sys_gh2517-default-filter-invoice-cand.sql

Adding Default Filter to Invoice Candidates Window.
FRESH-3467 https://github.com/metasfresh/metasfresh/issues/2517

#2517 Adding Default Filter to Invoice Candidates Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473470_sys_gh2152-retraceability-window-defauklt-filter-webui.sql

Adding Default Filters, Renamining Fields, Translations en_US/ de_DE,
Sorting to Retraceability Window in WebUI.
FRESH-2152 https://github.com/metasfresh/metasfresh/issues/2152

#2152 Adding Default Filters, Renamining Fields, Translations, Sorting

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473500_sys_gh2628-contract-window-adjustment.sql

Added Fields to Main View, Grid View. Added Translations for en_US.
FRESH-3559 https://github.com/metasfresh/metasfresh/issues/2628

#2628 Show fields product, qty, price and contractstatus in window contracts

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473540_sys_gh2212-passwort-process-user-window-webui.sql

Take out password field from user window and use process instead.
FRESH-3159 https://github.com/metasfresh/metasfresh/issues/2212

#2212 Take out password field from user window and use process instead

---

de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5473490_sys_gh2627_AddReferenceFromFlatrateTermToInvoiceCandidate.sql

#2627 Create Zoom Across Reference between Flatrate Term and Invoice
Candidate

#2627 Add Zoom across reference

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details_v2.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5473530_sys_gh2590_update_Docs_Sales_Order_Details_add_documentnote.sql

https://github.com/metasfresh/metasfresh/issues/2590

#2590 add documentnote in sales order details

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473590_sys_gh2635-bank-statement-ref-trl-webui.sql

Adding Translations for en_US Language/ Locale to Bank Statement Ref
widnow in WebUI
FRESH-3568 https://github.com/metasfresh/metasfresh/issues/2635

#2635 Adding Translations to Bank Statement Ref widnow in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473620_sys_gh2632-tourversion-trl-webui.sql

Adding Translations to Tour Version Window in WebUI. Now comleting the Language/ Locale en_US in that window.
FRESH-3561 https://github.com/metasfresh/metasfresh/issues/2632

#2632 Window Design Webui: Translations for Tourversion window

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5473710_sys_gh2657_update_hu_costprice_function_isactive_hu.sql

https://github.com/metasfresh/metasfresh/issues/2657

#2657 don't show inactive HUs

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473860_sys_gh2639-default-acct-values-adjustment.sql

Rename default Account Values to be sorted last
FRESH-3570 https://github.com/metasfresh/metasfresh/issues/2639

#2639 Rename default Account Values to be sorted last

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473870_sys_gh2665-url-attachment-message-trl.sql

Add Translation de_DE for URL Attachment Message
FRESH-3601 https://github.com/metasfresh/metasfresh/issues/2665

#2665 Add Translation de_DE for URL Attachment Message

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473880_sys_gh2666-contract-window-translation-webui.sql

Adding Translations for the Contract Window including all Subtabs for Language de_DE
FRESH-3604 https://github.com/metasfresh/metasfresh/issues/2666

#2666 Window Design Webui: Tanslations for the window Contract

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473890_sys_gh2667-contract-partner-trl.sql

Adding Translations in en_US Language/ Locale for Contractpartner Window.
FRESH-3605 https://github.com/metasfresh/metasfresh/issues/2667

#2667 Window Design Webui: Tanslations for the window Contractpartner

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473910_sys_gh2655-product-price-trl-en.sql

Adding Translations in Main View and Subtab Records for Language/ Locale en_US
FRESH-3583 https://github.com/metasfresh/metasfresh/issues/2655

#2655 Window Design Webui: Translations and Improvements for Product Prices

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473930_sys_gh2644-esr-payment-import-adjustments.sql

Adding Layout Adjustments to ESR Import Window. Adding Translations for Language/ Locale en_US. Adding Sorting and Filter Criteria.
FRESH-3573 https://github.com/metasfresh/metasfresh/issues/2644

#2644 Window Design Webui: Improvements to ESR window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473970_sys_gh2636-picklist-process-trl.sql

Adding Translations for en_US Language/ Locale to Pick List Process
FRESH-3567 https://github.com/metasfresh/metasfresh/issues/2636

#2636 Adding Translations to Pick List Process

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5473980_sys_gh2609-bank-statement-adjustment-webui.sql

Adding Translations for en_US and Layout Adjustments. Adding Sorting
Criteria.
FRESH-3537 https://github.com/metasfresh/metasfresh/issues/2609

#2609 Adding Translations and Layout Adjustments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474000_sys_gh2608-paymentalloc-improvement-webui.sql

Adapting WebUI Guidelines, adding Filter and Sorting Criteria
FRESH-3536 https://github.com/metasfresh/metasfresh/issues/2608

#2608 Adapting WebUI Guidelines, adding Filter and Sorting Criteria

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474010_sys_gh2607-internal-use-improvement-webui.sql

Adapting WebUI Guidelines for Internal Use Window. Adding additional
Filter and Sorting Criteria.
FRESH-3535 https://github.com/metasfresh/metasfresh/issues/2607

#2607 Adapting WebUI Guidelines for Internal Use Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474040_sys_gh2606-gljournal-translation-webui.sql

Adding Translations for Language en_US in Main View and Subtab Data. Adding Sorting Criteria and adapting Layout.
FRESH-3534 https://github.com/metasfresh/metasfresh/issues/2606

#2606 Window Design Webui: Translate GL Journal window in English

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474100_sys_gh2691-materialdispo-adj-webui.sql

Adding Adjustments to Material Dispo Window in WebUI. Adapating Guidelines. Adding Translations for de_DE, en_US Locale/ Language. Readonly ad_client_id.
FRESH-3618 https://github.com/metasfresh/metasfresh/issues/2691

#2691 Adjustments in Materialdispo Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474170_sys_gh2696-shipmentdispo-adj-webui.sql

Adding Fields to Shipment Dispo window (shipment constraint, shipping
stop from subscriptions). Adding Translations de_DE.
FRESH-3628 https://github.com/metasfresh/metasfresh/issues/2696

#2696 Adding Fields to Shipment Dispo window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474140_sys_gh2694-dunningtype-window-adj-webui.sql

Adding Improvements to Dunning Type Window in WebUI. Adding Translations for en_US on Process Names and Reference Lists.
FRESH-3627 https://github.com/metasfresh/metasfresh/issues/2694

#2694 Window Design Webui: Improvements in Dunning Type window

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/callout/C_InvoiceLine.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/InvoiceLineBL.java

#2400 discount in manual sales invoice

#2400 fix discount

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474330_sys_gh2603-purchasecand-trl.sql

Adding Translations for de_DE, en_US in Purchase Order Candidates Window.
FRESH-3531 https://github.com/metasfresh/metasfresh/issues/2603

#2603 Window Design Webui : Translate fields of Purchase Candidates

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474360_sys_gh2655-product-price-trl-fix.sql

Fix in Translation of Product Prices Window
FRESH-3583 https://github.com/metasfresh/metasfresh/issues/2655

#2655 Fix in Translation of Product Prices Window

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5474280_sys_gh2240_AddWindowIdToTable.sql

#2240 npe on zoom into header aggregation

#2240 Add script for fixing zoom into

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474410_sys_gh2729-tourversion-ext-month-week-webui.sql

Adding missing Fields to Tourversion window in WebUI. Adding Translations for de_DE, en_US.
FRESH-3668 https://github.com/metasfresh/metasfresh/issues/2729

#2729 Window Design Webui: Add missing fields to window Tourversion

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474440_sys_gh2653-bpartner-do-impr-webui.sql

Adding Translations for en_US Language/ Locale. Adjusting Field and Grid View Layout. Adding Missing Fields to Subscription Subtab Data.
FRESH-3581 https://github.com/metasfresh/metasfresh/issues/2653

#2653 Window Design Webui: Improve Businesspartner Dist-Orgs window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474480_sys_gh2728-bpartner-adj-trl.sql

Adjusting BPartner Window. Adding Tarnslations for en_US
FRESH-3665 https://github.com/metasfresh/metasfresh/issues/2728

#2728 Adjusting BPartner Window. Adding Tarnslations for en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474490_sys_gh2725-esr-paymentImport-adj-trl.sql

Adding Translations for en_US to ESR Payment Window, Subtabs and
Processes. Minor Layout improvements.
FRESH-3662 https://github.com/metasfresh/metasfresh/issues/2725

#2725 Adding Translations for en_US to ESR Payment Window, Subtabs and Processes

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474500_sys_gh2732-salesorder-adj-webui.sql

Minor improvement of Salesorderline. Adding Description Field in Main View and GridView
FRESH-3671 https://github.com/metasfresh/metasfresh/issues/2732

#2732 Minor improvement of Salesorderline. Adding Description Field in Main View and GridView

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474510_sys_gh2731-ship-restrict-adj-webui.sql

Minor adjustments to Shipment Restriction window in WebUI. Adding
Filter, Sorting and Translation.
FRESH-3670 https://github.com/metasfresh/metasfresh/issues/2731

#2731 Minor adjustments to Shipment Restriction window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474540_sys2730-purchaseorder-actions-trl.sql

Adding Translations for Action Menu in Purchase order Window. Also for
Action Parms.
FRESH-3669 https://github.com/metasfresh/metasfresh/issues/2730

#2730 Adding Translation for Action Menu in Purchase order Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474610_sys_gh2623-shipment-schedule-new-field.sql

Adding isClosed Field to Shipment Schedule
FRESH-3553 https://github.com/metasfresh/metasfresh/issues/2623

#2623 Adding isClosed Field to Shipment Schedule

---

de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/SubscriptionTermEventListener.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java

#2752  Inherit C_Taxcategory_ID and IsTaxIncluded from orderline to FT

#2752 Inherit C_Taxcategory_ID and IsTaxIncluded

---

de.metas.contracts/src/main/java/de/metas/contracts/flatrate/impexp/FlatrateTermImporter.java
de.metas.contracts/src/test/java/de/metas/contracts/flatrate/impexp/FlatrateTermImportProcess_SimpleCase_Test.java
de.metas.contracts/src/test/java/de/metas/contracts/impl/AbstractFlatrateTermTest.java
de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermTestHelper.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/CountryAreaBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tax/api/impl/TaxBL.java

#2750 Flatrate Import: Support tax category

#2750 Flatrate Import: Support tax category 

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474810_sys_gh2768-change-password-parms-trl.sql

Adding the Translation of Password Change Parms to en_US
FRESH-3711 https://github.com/metasfresh/metasfresh/issues/2768

#2768 Adding the Translation of Password Change Parms to en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474860_sys_gh2311-invoice-window-adj-trl-webui.sql

Adjusting the Invoice Candidates and Customer invoice Window Layout. Adding Translations for de_DE and en_EN in Main View, Advanced Edit and Subtabs.
FRESH-3265 https://github.com/metasfresh/metasfresh/issues/2311

#2311 Customer Invoices and Invoice Candidates adjustments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474890_sys_gh2774-vendor-invoice-adj-webui.sql

Adjustments to the vendor Invoice Window in WebUI. Adapting the latest WebUI Guidelines. Translating Tabs and Fields to en_US.
FRESH-3717 https://github.com/metasfresh/metasfresh/issues/2774

#2774 Vendor Invoice Layout and Translations in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474930_sys_gh2763-picking-tray-clearing-webui.sql

Adding new Picking Tray Clearing Window to WebUI Menu. Adding System Element Translations for Fields in Window.
FRESH-3697 https://github.com/metasfresh/metasfresh/issues/2763

#2763 New Window Picking Tray Clearing

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_BPartner.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475010_sys_gh2784_AddAddress3AndAddress4ToImportBpartners.sql
de.metas.business/src/main/java/org/adempiere/impexp/bpartner/BPartnerLocationImportHelper.java
de.metas.business/src/test/java/org/adempiere/impexp/bpartner/BPartnerImportProcess_SimpleCase_Test.java
de.metas.business/src/test/java/org/adempiere/impexp/bpartner/BPartnerImportTestHelper.java
de.metas.business/src/test/java/org/adempiere/impexp/bpartner/IBPartnerFactory.java

#2784 Partner Import : Add fields address3 and address4

#2784 Add fields address3 and address4 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474780_sys_gh2766_AddDescription.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474781_sys_gh2766_UpdateDescription.sql

#2766 add description in c_doctype_trl

#2766 Add description in C_DocType_Trl

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475040_sys_gh2764-material-receipt-adj-webui.sql

Adapting Window and Fields to current Design Guidelines for WebUI. Adding missing Translations for en_US, de_DE.
FRESH-3699 https://github.com/metasfresh/metasfresh/issues/2764

#2764 Window Design Webui : Material receipt

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475050_sys_gh2724-contractterms-adj-trl.sql

Adjusting Contract Terms Window Layout in WebUI. Adding Translations for en_US, de_DE Language/ Locale. Adding missing Fields Org/ Client in Allocaton Subtab.
FRESH-3661 https://github.com/metasfresh/metasfresh/issues/2724

#2724 Window Design Webui: Please, add translations to the window Contract Term

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5474890_sys_gh2781_change_address_layout_ch.sql

#2781 adding contact to displaysequence

#2781 Change Default Address Layout for B2C Partners for country CH

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475190_sys_gh2783-invoice-cand-trl-adj.sql

Adjusting a Field Translation in Invoice Candidates Window
FRESH-3726 https://github.com/metasfresh/metasfresh/issues/2783

#2783 Adjusting a Field Translation in Invoice Candidates Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475210_sys_gh2719-scheduler-window-adjustments-webui.sql

Adjusting the Scheduler window. Adding Translations, removing Fields.
FRESH-3655 https://github.com/metasfresh/metasfresh/issues/2719

#2719 Adjusting the Scheduler window. Adding Translations, removing Fields.

---

de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/process/ExportArchivePDF.java

#2800  Make de.metas.document.archive.process.ExportArchivePDF work in webui

#2800  Make de.metas.document.archive.process.ExportArchivePDF work in webui 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475230_sys_gh2723-internal-use-adj-webui.sql

Adjusting the window Internal Useage for WebUI
FRESH-3660 https://github.com/metasfresh/metasfresh/issues/2723

#2723 Adjusting the window Internal Useage for WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475240_sys_gh2758-missing-static-elements-trl.sql

Adding Translation en_US for missing/ new static Elements
FRESH-3690 https://github.com/metasfresh/metasfresh/issues/2758

#2758 Adding Translation en_US for missing/ new static Elements

---

de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5475310_sys_gh2818_AddRelationSalesOrderToInvoiceCandidateForFTs.sql

#2818 Flatrate: Have relation from Sales Order to invoice candidate

#2818 Add Relation from Sales Order ToInvoice Candidates for contracts

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475520_sys_gh2838-linenet-flatrate-workaround.sql

Adding Workaround Read-Only logic to Orderlines for Flatrate Terms
FRESH-3783 https://github.com/metasfresh/metasfresh/issues/2838

#2838 Adding Workaround Read-Only logic to Orderlines for Flatrate Terms

---

de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5475500_sys_gh76_Add_PrintName_c_flatrate_conditions.sql
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5475501_sys_gh76_Add_PrintName_c_flatrate_conditions_db.sql

https://github.com/metasfresh/metasfresh-dist-orgs/issues/76

#76 add printname in flatrate conditions

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Column.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Column.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/Callout_AD_Column.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/IColumnBL.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/impl/ColumnBL.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/callout/AD_Column.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/547560_sys_gh2546_MakevalueAndDocumentNoIsCalculatedY.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475610_sys_gh2546_ChangeEnittyTypeToDictionaryForIsCalculated.sql

#2546 Mark all Value and DocumentNo columns as IsCalculated=Y

#2546 Mark all Value and DocumentNo columns as IsCalculated=Y 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475590_sys_gh2723-internal-use-posted.sql

Fix for Posted Field when New
FRESH-3660 https://github.com/metasfresh/metasfresh/issues/2723

#2723 Fix for Posted Field when New

---

de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/setup/process/ClientSetup.java

#2836 Touching Setup wizard inactivates esr

#2836 Don't touch esr module in the wizard

---

de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java

#2357 exception when using process quotation to sales order with
parameter complete order

#2357 Fix exception

---

de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_Flatrate_Term.java
de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Term.java
de.metas.contracts/src/main/java/de/metas/contracts/ContractChangeParameters.java
de.metas.contracts/src/main/java/de/metas/contracts/IContractChangeBL.java
de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Change.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5475770_sys_gh2854_AddNoteField.sql
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5475800_sys_gh2854_AddTerminationFields.sql
de.metas.contracts/src/test/java/de/metas/contracts/impl/ContractChangeBLTest.java

#2854 Save Termination Reason when terminating subscription

#2854 Save Termination Reason when terminating subscription 

---

de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5475770_sys_gh_2676_AddNewTabFoForecast.sql
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/547578_sys_gh_2676_AddSysConfigForDaysInPast.sql

#2676 flatrate: make subscription progress reflecting progress

#2676 Implement minimum past event date

---

de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java

#2859 Pre-enddate termination of flatrate created compensation sales
order

#2859 Don't create compesation order if the Contract change has not have defined a product

---

de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java

#2862 Set MasterStartDate for a contract when creating from order

#2862 Set MasterStartDate

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/process/TabCreateFields.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/ICompositeQueryFilter.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/IInSubQueryFilterClause.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/IQueryBuilder.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/ActiveRecordQueryFilter.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/CompositeQueryFilter.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/InSubQueryFilter.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/InSubQueryFilterClause.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/QueryBuilder.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/POJOLookupMap.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/POJOLookupMapRestorePoint.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentAssignmentBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_invoicecandidate/views/C_Invoice_Candidate_SelectionIncompleteGroups.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5475700_sys_gh2564_C_Invoice_Candidate_SelectionIncompleteGroups.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5475820_sys_gh2564_msg.sql
de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainInvoiceCandDAO.java

https://github.com/metasfresh/metasfresh/issues/2564

order compensation groups

---

de.metas.business/src/main/java-legacy/org/compiere/process/BOMValidate.java
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5475660_sys_gh2113_MoveBOMValidation.sql

#2113 Move verify BOM process to BOM window

#2113 Move process to BOM window

---

de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/Printing_Constants.java
de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/async/spi/impl/PDFPrintingAsyncBatchListener.java
de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/Main.java
de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/AbstractPrintJobCreate.java

#2866  Make sure that 'Print All' is working in webui

#2866  Make sure that 'Print All' is working in webui 

---

de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/547593_sys_gh2874_AddIsForeginCustomerVirtualColumn.sql
de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/547594_sys_gh2874_AddFilters.sql

#2874 Create special filters in printing queue

#2874 Create special filters in printing queue 

---

de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Printing_Queue_ReEnqueue.java

#2876 Fix Recreate printing queue for webui

#2876 Fix Recreate printing queue for webui 

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_QuickInput.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_QuickInput.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/impl/BPartnerBL.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5475990_sys_gh_2880_AddGreeting.sql

#2880 Add greeting to partner quick creation from order

#2880 Implement greeting in New partner quick input

---

de.metas.document.refid/src/main/java/de/metas/document/refid/api/IReferenceNoGeneratorInstance.java
de.metas.document.refid/src/main/java/de/metas/document/refid/api/impl/ReferenceNoGeneratorInstance.java
de.metas.document.refid/src/main/java/de/metas/document/refid/spi/IReferenceNoGenerator.java
de.metas.document.refid/src/test/java/de/metas/document/refid/api/impl/ReferenceNoDAOTests.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRBL.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRBL.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/document/refid/spi/impl/InvoiceReferenceNoGenerator.java
de.metas.payment.esr/src/main/java/de/metas/payment/esr/document/refid/spi/impl/RenderedCodeLineGenerator.java
de.metas.payment.esr/src/test/java/de/metas/payment/esr/document/refid/spi/impl/InvoiceReferenceNoGeneratorTest.java

https://github.com/metasfresh/metasfresh/issues/2878

Gh2878 accountNo in ReferenceNo rpadZero

---

de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5476040_sys_gh2887_M_ShipmentSchedule_ReferenceSearch_In_SubscriptionProgress.sql

https://github.com/metasfresh/metasfresh/issues/2887

#2887 Make ShipmentSchedule column reference search in C_SubscriptionProgress

---

de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateDAO.java
de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Extend.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java

#2885 Test canceling extended contracts and fix if needed

#2885 Test canceling extended contracts and fix if needed 

---

de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java

#2907 set masterenddate correctly when extending contracts

#2907 set masterenddate correctly when extending contracts

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTab.java
de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/grid/GridController.java
de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
de.metas.contracts/src/main/java/de/metas/contracts/interceptor/MainValidator.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5476370_sys_gh2917-app_SysConfig_allow_reactivate_Flatrate_Terms.sql
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5476390_sys_gh2917-app_Message_reactivate_not_supported.sql
de.metas.contracts/src/test/java/de/metas/contracts/interceptor/C_Flatrate_TermTest.java

https://github.com/metasfresh/metasfresh/issues/2917

Allow reactivating procurement contracts #2917

---

de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5476250_sys_gh2901_AddRelationFrom_IC_to_FT.sql

#2901 Releation from Invoice Candidate to flatrate term

#2901 Relation from Invoice Candidate to flatrate term 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5476910_sys_gh2947_adapt-role-window-webui.sql

Adapting the Roles Window Layout and Translations to our current WebUI Guidelines.  Including Subtabs/ Grid View/ Advanced Edit.
FRESH-3988 https://github.com/metasfresh/metasfresh/issues/2947

#2947 Adapt Window Role to WebUI Guidelines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5476920_sys_gh2407-contract-window-adj-webui.sql

Translating the Contract Window Subtabs for Subscription History and
Forecast
FRESH-3368 https://github.com/metasfresh/metasfresh/issues/2407

#2407 Translating the Contract Window Subtabs for Subscription History and Forecast

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5476930_sys_gh2934-locator-additional-dimension.sql

Adding System Element, Column, Field and UI Element for an additional Locator Dimension called (Storage) Rack.
FRESH-3952 https://github.com/metasfresh/metasfresh/issues/2934

#2934 Additional Locator Dimensions

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5476970_sys_gh2871-posted-default-value.sql

Adding missing default value for posted column in different Table &
Column definitions
FRESH-3837 https://github.com/metasfresh/metasfresh/issues/2871

#2871 Adding missing default value for posted column

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5476990_sys_gh2872-distribution-order-window-webui.sql

Adding various adjustments to Distribution order Window adapting the current WebUI guidelines. Adding Translations for en_US and de_DE.
FRESH-3839 https://github.com/metasfresh/metasfresh/issues/2872

#2872 Window Design Webui : Improve Distribution Order window

---

de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java

#2963 flatrate: use datepromised instead of order data for master and
startdate

#2963 Use datePromised

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477030_sys_gh2969-filter-warehouse-distribution-editor.sql

Adding Warehouse as SQL Column in DD Orderlines
FRESH-4023 https://github.com/metasfresh/metasfresh/issues/2969

#2969 Adding Warehouse as SQL Column in DD Orderlines

---

ReleaseNotes.md
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477150_sys_gh2985-distribution-editor-refining-webui.sql

Adjusting the Distributions Editor Window in WebUI. Addien new Fields, Filter and Order criteria. Adding Translations for en_US, de_DE.
FRESH-4042 https://github.com/metasfresh/metasfresh/issues/2985

#2985 Refining Distribution Editor Window in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477230_sys_gh2989-gap-filter-businesspartner-window.sql

Adding GAP No to Businesspartner Window Filter
FRESH-4049 https://github.com/metasfresh/metasfresh/issues/2989

#2898 Adding GAP No to Businesspartner Window Filter

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477270_sys_gh2980-created-order-control.sql

Adding new Filter and adjusting Filter order
FRESH-4037 https://github.com/metasfresh/metasfresh/issues/2980

#2980 Adding new Filter and adjusting Filter order

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5477110_sys_gh2937_update_Docs_Sales_Invoice_Details_HU.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5477111_sys_gh2937_update_Docs_Sales_Invoice_Details_Sum.sql

https://github.com/metasfresh/metasfresh/issues/2975

sales invoice jasper: group products by product category 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477300_sys_gh2981-approval-process-ic-translation-de.sql

Add Translation for Approval Process in invoice Candidates
FRESH-4038 https://github.com/metasfresh/metasfresh/issues/2981

#2981 Add Translation for Approval Process in invoice Candidates

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477290_sys_gh2992-shipment-packingitem-trl-webui.sql

Adding Translations, renamining and rearranging Fields.
FRESH-4077 https://github.com/metasfresh/metasfresh/issues/2992

#2992 WebUI: Window Shipment Packing Item

---

de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/547740_sys_gh2942_CorrectMessage.sql

#2942 Fix the message for PrintJob_Done

#2942 Correct AD_Message

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477450_sys_gh3002-hu-trx-window-webui.sql

New Window for handling Unit Transaktion. Creating Main View, Grid View and Sidelist Layout. Adding Translation for de_DE and en_US. Adding Window to WebUI Menu.
FRESH-4091 https://github.com/metasfresh/metasfresh/issues/3002

#3002 WebUI: New Window for HU Transaction

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477490_gh3003-hu-trace-window-adjustments-webui.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477490_sys_gh3003-hu-trace-window-adjustments-webui.sql

Finetuning the HU Trace WIndow. Rearranging Main View, Grid View and Sidelist. Adding Identifier to HU Trace Table.
FRESH-4092 https://github.com/metasfresh/metasfresh/issues/3003

#3003 WebUI: Adjustments on HU Trace Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477500_sys_gh3005-planstatus-filter-pporder.sql

Adding Planstatus to Filter criteria and other Fields too.
FRESH-4099 https://github.com/metasfresh/metasfresh/issues/3005

#3005 Adding Planstatus to Filter criteria

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477510_sys_gh2982-docstatus-shipment-window-filter.sql

Adding docstatus to filter in Shipment window
FRESH-4040 https://github.com/metasfresh/metasfresh/issues/2982

#2982 Adding docstatus to filter in Shipment window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477520_sys_gh2976-procurement-planning-adjustments.sql

Adding translations, renaming windowname
FRESH-4029 https://github.com/metasfresh/metasfresh/issues/2976

#2976 Adding translations, renaming windowname

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477550_sys_gh2987-warehouse-locator-name-ext.sql

Extending warehouse name schema to
warehousename-wareheousevalue-locatorvalue-x-x1-y-z
FRESH-4045 https://github.com/metasfresh/metasfresh/issues/2987

#2987 Extending warehouse name schema

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5477720_sys_gh3023_FilterProductPergOrgInSalesOrder.sql

#3023 ad_org is ignored when doing quick order entry

#3023 Filter products per org in Sales order

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/label.jrxml

https://github.com/metasfresh/metasfresh/issues/3032

SSCC Product description Field cut off 

---

de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Order.java

#3043 A contract shall not be created when a completing a quotation

#3043 A contract shall not be created when a completing a quotation 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478020_sys_gh3039-forecast-window-adjustments.sql

Adding new Fields to Forecast Header and Line. Refining Layout, adapting current WebUI Guidelines.
FRESH-4201 https://github.com/metasfresh/metasfresh/issues/3039

#3039 Forecast Window adjustments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478090_sys_gh3048-date-name-filter-materialreceiptcand-webui.sql

Adding date filter to material receipt dispo. renaming field.
https://github.com/metasfresh/metasfresh/issues/3048

#3048 Adding date filter to material receipt dispo. renaming field.

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478200_sys_gh611-hueditor-wo-destroyed.sql

Adding default filtering and validation rule overwrite in window
https://github.com/metasfresh/metasfresh-webui-api/issues/611

#611 Adding default filtering and validation rule overwrite in window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478400_sys_gh3082-stock-ctrl-purchase-window-webui.sql

New Window for manual OnHand Qty in WebUI. Adding 2-column Layout foor main view and advanced edit. Adding layout for grid view and sidelist.
https://github.com/metasfresh/metasfresh/issues/3082

#3082 New Window for manual OnHand Qty in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478410_sys_gh3066-manufacturing-order-window-adj.sql

Adapted the window manufacturing order to our current webui guidelines. Improving translations.
https://github.com/metasfresh/metasfresh/issues/3066

#3066 WebUI: Adapt Manufacturing Order window to current guidelines

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478420_sys_gh2946-customer-label-name.sql

Adding a new Field for CustomerLabelName. Adding a translationtable for Product BPartner and that name.
https://github.com/metasfresh/metasfresh/issues/2946

#2946 Product: New Field Endcustomer productname and translation

---

de.metas.purchasecandidate.base/src/main/sql/postgresql/ddl/C_PurchaseCandidate_Enqueued.sql
de.metas.purchasecandidate.base/src/main/sql/postgresql/ddl/t_lock_diag_c_purchasecandidate.sql
de.metas.purchasecandidate.base/src/main/sql/postgresql/system/5478660_sys_gh3072_PurchaseCandidate_Schema.sql
de.metas.purchasecandidate.base/src/main/sql/postgresql/system/5478670_sys_gh3072_t_lock_diag_c_purchasecandidate_view.sql
de.metas.purchasecandidate.base/src/main/sql/postgresql/system/5478680_sys_gh3072_C_PurchaseCandidate_Enqueued.sql

https://github.com/metasfresh/metasfresh/issues/3072

Gh3072 Create schema and diagnostic views for purchase candidate

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478780_sys_gh3094-activity-in-purchaseorderline-webui.sql

Add activity fields to purchase orderline
https://github.com/metasfresh/metasfresh/issues/3094

#3094 Add activity fields to purchase orderline

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Forecast.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_ForecastLine.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Forecast.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_ForecastLine.java
de.metas.business/src/main/java/de/metas/mforecast/interceptors/M_ForecastLine.java
de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/IHUPackingAwareBL.java
de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/impl/ForecastLineHUPackingAware.java
de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/impl/HUPackingAwareBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/spi/impl/ForecastLineHUDocumentHandler.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/I_M_ForecastLine.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_ForecastLine.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/Main.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/order/api/IHUOrderBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/order/api/impl/HUOrderBL.java

Implement Batch entry in Forecast Window 
https://github.com/metasfresh/metasfresh-webui-api/issues/699

#699 Implement Batch entry in Forecast Window 

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/model/interceptor/MForecastPOCopyRecordSupport.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/model/interceptor/M_Forecast.java

#3040 Implement Clone/ Copy for Forecast Window WebUI

#3040 Implement Clone/ Copy for Forecast Window WebUI 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478960_sys_gh2977-orgaccess-primkey-webui.sql

Adding Primary Key to Orgaccess Table and Tab in User Window
https://github.com/metasfresh/metasfresh/issues/2977

#2977 Adding Primary Key to Orgaccess Table and Tab in User Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478965_sys_gh937-isallowstatistics-system-no.sql

Switching off the statistics info in AD_System
https://github.com/metasfresh/metasfresh/issues/937

#937 Increase Performance by disabling statistics info

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5478970_sys_gh1767-board-config-window-webui.sql

Creating a new Window for the Kanban Board Configuraiton in WebUI. Main, View, Grid View, Included Tabs. Adding Translations for de_DE, en_US
https://github.com/metasfresh/metasfresh/issues/1767

#1767 New Window Board in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479010_sys_gh1809-user-query-window-webui.sql

New window for user query in webui. Added 2-column layout, grid view, advanced edit, sidelist. Addes to webui menu. Added Translations for en_US, de_DE.
https://github.com/metasfresh/metasfresh/issues/1809

#1809 New User Query Window on WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479040_sys_gh2177-attribute-search-window-webui.sql

New Window for Attribute Search in WebUI. 2-column layout in main view. Added to WebUI menu. Sidelist and Grid View.
https://github.com/metasfresh/metasfresh/issues/2177

#2177 New Window for Attribute Search in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479050_sys_gh3120-adding-netsum-sales-invoice-webui.sql

Add Netsum to Customer Invoice Document Grid View.
https://github.com/metasfresh/metasfresh/issues/3120

#3120 Add Netsum to Customer Invoice Document Grid View

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479060_sys_gh3122-vendor-invoice-netsum-webui.sql

Adding Net Sum to Vendor invoice Grid View
https://github.com/metasfresh/metasfresh/issues/3122

#3122 Add Netsum to Vendor Invoice Document Grid View

---

de.metas.report/report-service/src/main/configs/metasfresh-report.conf
de.metas.report/report-service/src/main/docker/Dockerfile
de.metas.report/report-service/src/main/docker/start_report_docker.sh

standalone report / jasper service #2932

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479260_sys_gh3124-picking-profile-configuration-window-webui.sql

Adding the Picking Profile Configuration Window to WebUI. Layout created for main view, grid view, sidelist. Added Translations for en_US, de_DE.
https://github.com/metasfresh/metasfresh/issues/3124

#3124 Picking terminal: pimp Picking Configuration window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479600_sys_gh3138_FixBPartnerImportWindow.sql
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/Main.java
de.metas.vertical.pharma/src/main/java/org/adempiere/impexp/impl/PharmaImportPartnerInterceptor.java

#3138  Import BPartner window: cannot see data

#3138  Import BPartner window: cannot see data 

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/GenericZoomProvider.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/RelationTypeZoomProvider.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/MetasInfoContributor.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/zoom/process/ZoomInfoFactoryExecute.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479720_sys_gh3151-app_add_procees_ZoomInfoFactoryExecute.sql

ZoomTo-Performance Issues #3151

ZoomTo-Performance Issues #3151 Diag process

---

de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/editor/model/impl/MovementsAnyWarehouseModel.java

https://github.com/metasfresh/metasfresh/issues/2144

#2144 Make the warehouse excluding logic rely on IDs

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479820_sys_gh3107-warehouse-picking-group.sql

Createing a new Window for Warehouse picking group. Adding 2-column Layout, Grid View and Sidelist. New Translations for de_DE and en_US.
https://github.com/metasfresh/metasfresh/issues/3107

#3107 Warehouse picking group window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5479900_sys_gh3166-pharma-fields-businesspartner-window.sql

Moving Fields to Advanced edit and adding Translations for en_US, de_DE
https://github.com/metasfresh/metasfresh/issues/3166

#3166 Moving Fields to Advanced edit and adding Translations

---

de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/subscriptioncommands/RemovePauses.java

https://github.com/metasfresh/metasfresh/issues/2881

gh2881 Reopen The Shipment Schedules after the pauses were removed

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480080_sys_gh3176-salsesorder-actions-trl.sql

Adding Translations for de_DE to sales order actions
https://github.com/metasfresh/metasfresh/issues/3176

#3176 Translate Sales Order Actions

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480090_sys_gh2715-aggregation-ic-window-webui.sql

New Window for Create webui window for C_Invoice_Candidate_Agg. Adding to WebUI menu. Adding 2-column layout, sidelist and gridview. Adding translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/2715

#2715 Create webui window for C_Invoice_Candidate_Agg

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480100_sys_gh3164-import-bpartner.sql

Addign Translations for en_SU and renaming Fields in de_DE. Adjusting Advanced Edit Layout. Removing Process Button for import.
https://github.com/metasfresh/metasfresh/issues/3164

#3164 WebUI: Import BPartner Translations

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480160_sys_gh3140-picking-wh-group-trl.sql

Adding translations for en_US to picking wh group config window
https://github.com/metasfresh/metasfresh/issues/3140

#3140 Adding translations for en_US to picking wh group config window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480180_sys_gh3134-purchase-dispo-readonly.sql

Making some Fields readonly in Purchase Disposition Window in WebUI
https://github.com/metasfresh/metasfresh/issues/3134

#3134 Making some Fields readonly in Purchase Disposition Window in WebUI

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Attribute.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Attribute.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480190_sys_gh727webui_M_Attribute_IsHighVolume.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480191_cli_gh727webui_M_Attribute_IsHighVolume_migrate.sql
de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
de.metas.business/src/test/java/org/adempiere/mm/attributes/api/impl/AttributesTestHelper.java
de.metas.fresh/de.metas.fresh.base/src/test/java/org/adempiere/mm/attributes/listeners/adr/ADR_ModelAttributeSetInstanceListenerTest.java
de.metas.handlingunits.base/src/main/sql/postgresql/system/5480192_cli_gh727webui_mark_SubProducerBPartner_attribute_as_IsHighVolume.sql
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/attributes/impl/AttributeValueTest.java
de.metas.swat/de.metas.swat.base/src/test/java/org/adempiere/mm/attributes/countryattribute/impl/CountryModelAttributeSetInstanceListenerTest.java

https://github.com/metasfresh/metasfresh-webui-api/issues/727

Support Lookup view attributes

---

de.metas.procurement.base/src/main/sql/postgresql/system/50-de.metas.procurement/5480050_sys_gh3169_PMM_Week_pmm_week_uq.sql
de.metas.procurement.base/src/main/sql/postgresql/system/50-de.metas.procurement/5480060_sys_gh3169_PMM_Week_pmm_week_uq_DB.sql

https://github.com/metasfresh/metasfresh/issues/3169

#3169 PMM_Week unique constraint including ASI

---

de.metas.procurement.base/src/main/sql/postgresql/system/50-de.metas.procurement/5480060_sys_gh3169_PMM_Week_pmm_week_uq_DB.sql
de.metas.procurement.base/src/main/sql/postgresql/system/50-de.metas.procurement/5480270_sys_gh3169_PMM_Week_pmm_week_uq_UpdateNull.sql
de.metas.procurement.base/src/main/sql/postgresql/system/50-de.metas.procurement/5480280_sys_gh3169_PMM_Week_pmm_week_uq_withCoalesce.sql
de.metas.procurement.base/src/main/sql/postgresql/system/50-de.metas.procurement/5480290_sys_gh3169_PMM_Week_pmm_week_uq_withCoalesce_DB.sql

https://github.com/metasfresh/metasfresh/issues/3169

Gh3169 PMM_Week unique index repaired

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480370_sys_gh3193-manual-on-hand-qty-improvement.sql

Adding additional Fields to window subtab. Rearranging Gridview and
advanced edit
https://github.com/metasfresh/metasfresh/issues/3193

#3193 Adding additional Fields to window subtab

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openpayments/report.jrxml

https://github.com/metasfresh/metasfresh/issues/3202

#3202 take out payselectioncheck and payment

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480940_sys_gh3229-activity-purchase-orderline-webui.sql

Adding Activity to Purchase orderline in WebUI
https://github.com/metasfresh/metasfresh/issues/3229

#3229 Adding Activity to Purchase orderline in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5480960_sys_gh3234-material-tracking-lookup-invoicecand.sql

Adjusting Material Tracking widget in Invoice Candidates (from table
direct to search)
https://github.com/metasfresh/metasfresh/issues/3234

#3234 Adjusting Material Tracking widget in Invoice Candidates

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/impl/PlainProductPA.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/impl/ProductPA.java
de.metas.swat/de.metas.swat.base/src/test/java/de/metas/product/impl/ProductPATest.java

#2822 Empty Country in Price List not working

#2822 Empty Country in Price List not working 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481170_sys_gh3242-bpartner-acct-window-webui.sql

Creating a new Window for Customer Accounts in WebUI, allowing the user to maintain these via automatic reference fom Businesspartner Window. Created 2-column layout, grid view and sidelist.
https://github.com/metasfresh/metasfresh/issues/3242

#3242 WebUI: Create new Customer Accounts Window

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_sales_source_of_supply.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5481120_sys_gh3237_sys_add_IsSourceSupplyCert_column.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5481121_sys_gh3237_sys_add_IsSourceSupplyCert_column.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5481123_sys_gh3237_sys_add_IsSourceSupplyCert_field.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5481124_sys_gh3237_sys_add_docs_sales_source_of_supply_function.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5481125_sys_gh3237_sys_add_issourcesupplycert_in_docs_sales_inout_root.sql

https://github.com/metasfresh/metasfresh/issues/3237
add IsSourceSupplyCert column and field
add dourse of supply function and update inout root function

#3237 add source of supply field and functions

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481310_sys_gh3257-vendor-acct-window-webui.sql

New WIndow for vendor accounts in WebUI. Added 2-column Layout, Grid View and Sidelist. Added Translation for en_US. Rearranges Window customer accounts and vendor accounts to finance section.
https://github.com/metasfresh/metasfresh/issues/3257

#3257 WebUI: Window for Vendor Accounting

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481320_sys_gh3256-warehouse-acct-window-webui.sql

New Window for Warehouse Accounts. Adding 2-column Layout, Sidelist and Grid View. Adding Translations for en_US. Added to webui menu under Finance. Adjusted the Table Window reference to new Window.
https://github.com/metasfresh/metasfresh/issues/3256

#3256 WebUI: Window for Warehouse Accounting

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481360_sys_gh3261-businesspartner-group-acct-window-webui.sql

New Window for Businesspartner group Accounts. Added to WebUI Menu in Finance. 2-column Layout, Sidelist and grid View added, Window reference in Table definition. Added Translation for en_US.
https://github.com/metasfresh/metasfresh/issues/3261

#3261 WebUI: New Window for BPartner Group Accounts

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481420_sys_gh3267-period-action-calendar-webui.sql

Adding the Period create action to Calendar Window in Subtab Year
https://github.com/metasfresh/metasfresh/issues/3267

#3267 Adding the Period create action to Calendar Window in Subtab Year

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481440_sys_gh3269-doc-reference-calendar-period.sql

Adding a Window Reference to Table C_Period
https://github.com/metasfresh/metasfresh/issues/3269

#3269 Adding a Window Reference to Table C_Period

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481470_cli_gh3272_add_year_2018_and_periods.sql

#3272 provide year and periods for 2018

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481660_sys_gh3275-filter-datepromised-order-windows-webui.sql

Adding datepromised to Order windows in WebUI
https://github.com/metasfresh/metasfresh/issues/3275

#3275 Adding datepromised to Order windows in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481800_sys_gh3284-email-editor-translations-de-webui.sql

Adding Translations for WebUI eMail Editor in de_DE
https://github.com/metasfresh/metasfresh/issues/3284

#3284 Adding Translations for WebUI eMail Editor in de_DE

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5481950_sys_gh3293-webui-translation-messages.sql

Adding static messages and Translations to metasfresh for WebUI DateRange Picker
https://github.com/metasfresh/metasfresh/issues/3293

#3293 Webui: Add Translation Messages for Daterangepicker

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5481260_sys_gh3232_deactivate_inventory_invoiceCandidate_handlers.sql

https://github.com/metasfresh/metasfresh/issues/3232

Gh3232 1 deactivate invoice candidate handlers for inventory

---

de.metas.ui.web.base/src/main/java/de/metas/ui/web/base/model/I_T_WEBUI_ViewSelection_ToDelete.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5482450_sys_gh737webui_T_WEBUI_ViewSelection_ToDelete.sql

https://github.com/metasfresh/metasfresh-webui-api/issues/737

T_WEBUI_ViewSelection_ToDelete

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5482580_sys_gh3309-event-store-window-webui.sql

Adding a new Window for Event Store Messages tp WebUI. the window can be accessed with Role System Admin. Adding 2-column, Grid View and Sidelist Layout for main view and subrecords.
https://github.com/metasfresh/metasfresh/issues/3309

#3309 Webui Window Design: Improve window Event store 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483050_sys_gh3319-message-window-webui.sql

Adding the Window Layout for message window in WebUI. 2-column Layout, Grid View and Sidelist. Adding Translation for de_DE Language.
https://github.com/metasfresh/metasfresh/issues/3319

#3319 Webui Window Design: Improve window Message

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483110_sys_gh3322-validation-rule-window-webui.sql

Creating a new Window in WebUI for Validation Rules. 2-column Layout added. Grid View and Sidelist. Added Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3322

#3322 Webui Window Design: Improve window Validation Rule

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483000_sys_gh3338_harmonize_fields_description_descriptionbottom.sql

c_doctype.description, c_invoice.description, c_order.descriptionbottom,
c_invoice.descriptionbottom

#3338 make description fields type text and 1024 long

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483240_sys_gh3349-add-bpartner-to-user-main-view-webui.sql

Adding the BPartner to User Window main View and Grid View.
https://github.com/metasfresh/metasfresh/issues/3349

.#3349 Adding BPartner to User Window main View

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483310_sys_gh3330-entity-type-window-webui.sql

Creates the Entity Type Window in WebUI. 2-column Layout added. Grid View, Advanced edit. Added Translation for de_DE Language.
https://github.com/metasfresh/metasfresh/issues/3330

#3330 Webui Window Design: Improve window Entity Type

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483390_sys_gh3359-account-unlock-action-user-window.sql

Removes the unlock Button from main view and adds the unlock account
action to window action menu
https://github.com/metasfresh/metasfresh/issues/3359

#3359 Removes Button and adds unlock action to window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483380_sys_gh3318-reference-window-webui.sql

New Window for Reference Maintenance. Adds 2-column Layout, Sidelist, Advances edit and Grid View. Adds Translation for de_DE and en_US.
https://github.com/metasfresh/metasfresh/issues/3318

#3318 Webui Window Design: Improve window Reference

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483420_sys_gh3317-report-window-webui.sql

Adds new Window for Report & Process in WebUI. Usable as Sysadmin. Adds 2-column Layout for Main View. Adds Grid View, Sidelist and Advanced edit for Main View and Subtabs. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3317

#3317 Webui Window Design: Improve window Report & Process

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483490_sys_gh3329-event-log-window-trl.sql

Adds Translations for de_DE, en_US in main View and Subtabs. Also adds Translations for Menu entries and Folders.
https://github.com/metasfresh/metasfresh/issues/3329

#3329 Webui Window Design: Translate all in window Event store

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483560_sys_gh3313-field-group-window-webui.sql

Adds new Window Layout for Field Group Window in WebUI. 2-column Layout, Grid View, and Advanced Edit. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3313

#3313 Webui Window Design: Improve window Field Group

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483650_sys_gh3366-reference-no-window-webui.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483680_sys_gh3366-reference-no-type-window-webui.sql

Adds new Windows in WebUI - Reference No and Reference No Type. Adds 2-column Layout, Grid View, Advanced edit for Main View and Subtabs. Adds Translations for de_DE, en_US Language.
https://github.com/metasfresh/metasfresh/issues/3366

#3366 Webui Window: Create window for ReferenceNo and Reference Type #3366

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483790_sys_gh3366-reference-no-windows-menu-trl.sql

Adds minor Translation Fix
https://github.com/metasfresh/metasfresh/issues/3366

#3366 Webui Window: Create window for ReferenceNo and Reference Type

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483800_sys_gh3377-refno-table-primary-key.sql

adds Primary Key to Refno_Table table
https://github.com/metasfresh/metasfresh/issues/3377

#3377 Add an ID to C_ReferenceNo_Type_Table

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5482510_cli_increase_ad_sequence_for_product_value_on_fresh_system.sql

#1196 fix ad_sequence for product on fresh systems

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483690_sys_gh3338_DescriptionBottom_Length2048.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483700_sys_gh3338_DescriptionBottom_Length2048_DDL.sql

https://github.com/metasfresh/metasfresh/issues/3338

#3338 Make the DescriptionBottom columns with FieldLength 2048

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5483880_sys_gh3387-msv3-window-webui.sql

Add new MSV3 Config to WebUI, Adds 2-column Layout, Grid View and Sidelist. Adds Translation for de_DE, en_US Language/ Locale.
https://github.com/metasfresh/metasfresh/issues/3387

#3387 WebUI New Window for MSV3 Config

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/0000010_sys_gh3391-app_AD_MigrationScript_add_durationMillis.sql
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/IScript.java
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/applier/impl/ScriptsApplier.java
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/executor/impl/NullScriptExecutor.java
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/impl/CreateDBFromTemplateScript.java
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/impl/LocalScript.java
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/impl/SQLDatabaseScriptsRegistry.java
de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/impl/SQLHelper.java

Migration - record apply-duration for each script https://github.com/metasfresh/metasfresh/issues/3391

#3391 Migration - record apply-duration for each script

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_InOut_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5483954_sys_gh3394_fix_huname_Docs_Sales_InOut_Details.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5483955_sys_gh3394_fix_huname_Docs_Sales_InOut_Details_ConcreteADR.sql

https://github.com/metasfresh/metasfresh/issues/3394

#3394 update docs sales inout details sqls

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentPackingMaterialLinesBuilder.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java

#3302 Payment Discount on Orderline, Invoice Candidate

#3302 Fix payment term and corect link to package material line

---

de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/CreditMemoInvoiceCopyHandler.java

#3402 Can't credit memo a partially paid invoice

#3402 Make sure that old grandtotal id mattching to the new computed values

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5484270_sys_gh3245-material-cockpit-details-overlay.sql

Renaming Fields, Adding Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3245

#3245 Material Cockpit Details modal overlay

---

de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_Flatrate_Term.java
de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Term.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5484380_sys_gh3416_AddTerminationDate.sql
de.metas.contracts/src/test/java/de/metas/contracts/impl/ContractChangeBLTest.java

#3416 Save termination date explicitly

#3416 Save termination date explicitly 

---

de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningBL.java
de.metas.dunning/src/main/java/de/metas/dunning/invoice/model/validator/C_Dunning_Candidate.java

#3426 Dunning Level is not set in invoice after generating dunning doc

#3426 Set dunning level in invoice

---

de.metas.contracts/src/main/java/de/metas/contracts/IContractChangeBL.java
de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateDAO.java
de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Change.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5484100_sys_3355_AddIsCreditOpenInvoices.sql
de.metas.swat.ait/src/main/java/test/integration/swat/sales/invoice/InvoiceTests.java
de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/process/CreateCreditMemoFromInvoice.java
de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/InvoiceCreditContext.java

#3355 Add option to automatically credit open invoice for terminated contract / subscription

#3355 Add option to automatically credit open invoice for terminated contract / subscription 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5484230_cli_taxrate_change_ch_switzerland_20180101.sql

#3417 adding tax config for CH and 2018

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5484250_sys_gh3278_AddInternalNameInPriceList.sql
de.metas.vertical.pharma/src/main/java/de/metas/impexp/product/PharmaProductImportProcess.java

#3279 Pharma: Copy missing product prices after import

#3279 Fix updating product and setting base price list version

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5484600_sys_gh3440-shipper-window-subtab-layout-webui.sql

Adds the Subtab Layout for GO! Configuration in WebUI for Shipper Window. Adds Grid View and Advanced Edit Layout. Adds Translations for de_DE and en_US.

#3440 Improvement of Shipper Window in WebUI

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/ConfigValidator.java

https://github.com/metasfresh/metasfresh-webui-api/issues/807

enable remote cache invalidation for C_Invoice_Candidate

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/HUShippingFacade.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromHU.java

i.e. fixed typo issue
https://github.com/metasfresh/metasfresh-webui-api/issues/806

#806-api Add to Transportation Order, Ship and Invoice action in Picking Clearing Tray shall respect the invoice schedule

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5484700_sys_gh3445_fix_huqty_Docs_Purchase_Invoice_Details.sql

https://github.com/metasfresh/metasfresh/issues/3445

#3445 purchase invoice: take qtyEnteredTU from inout

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/server/rpl/api/impl/ImportHelper.java
de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PriceListDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandBL.java

#3449 ImportHelper doesn't switch ctx => master

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/movements/report.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_title.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/openitems_report.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5484750_sys_gh2571_fix_missing_payselectionline_processed_OpenItems_Report.sql

https://github.com/metasfresh/metasfresh/issues/2571

#2571 Report Translations to en_US: menu reports

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485120_sys_gh3468-message-translation-daterange-hint.sql

Adds a Translation to ad_message for daterange filter
https://github.com/metasfresh/metasfresh/issues/3468

#3468 Adds Translation for daterange hint

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485090_sys_setting_reference_ad_user_systemuser.sql

#3465 setting reference ad_user systemuser

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/model/interceptor/C_BPartner_Stats.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/impl/BPartnerStatsDAO.java

#3481 Force refreshing virtual column CreditLimitIndicator from C_BPartner

#3481 Force refreshing virtual column CreditLimitIndicator from C_BPartner 

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/translation/api/IElementTranslationBL.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/translation/api/impl/ElementTranslationBL.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/field/model/interceptor/AD_Field.java
de.metas.business/src/main/java/org/adempiere/model/validator/AdempiereBaseValidator.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/update_FieldTranslation_From_AD_Name_Element.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5485330_sys_gh3457_UpdateTranslations_Indexes.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5485350_sys_gh3457_Update_Translation_Update_function.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5485360_sys_gh3457_Update_FieldTranslation_From_AD_Name_Element.sql

https://github.com/metasfresh/metasfresh/issues/3457

Gh3457 Improve translation updates

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485440_sys_gh3495-product-price-grid-view-adjustment.sql

Improves the usability of the Product Price Window. Removing Field
Matching Order from grid View. Adding Active Flag to grid View.
https://github.com/metasfresh/metasfresh/issues/3495

#3495 Improves the Product Price Window

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/CalloutInvoiceBatch.java
de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java

#3499 Cannot create manual invoice

#3499 fix old code in callout

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485570_sys_gh3505-procurement-planning-improvements-webui.sql

Adjusting the grid view, main view and advanced edit of procurement planning window in webUI.
https://github.com/metasfresh/metasfresh/issues/3505

#3505 Improvement of Procurement Candidates

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485730_sys_gh3357-deactivate-system-mod-subtab-entity-type.sql

Decativating the ad_modificaiton subtab in entity type window.
https://github.com/metasfresh/metasfresh/issues/3357

#3357 Deactivating the ad_modification subtab

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485950_sys_gh3515-compensation-group-window-webui.sql

New Window in WebUI Compensation group Schema. Adds 2-column Layout for Main View, grid View and Advanced edit. Adds Subtab Layout. Adds Translations for de_DE, en_US Language.
https://github.com/metasfresh/metasfresh/issues/3515

#3515 Webui: Pimp Compensation Group Schema window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5485970_sys_gh3502-filter-improvement-purchase-order-trl.sql

Adds the translation for en_US for column CreatedBy
https://github.com/metasfresh/metasfresh/issues/3502

#3502 Adds Translation for en_US

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5486130_sys_gh3513-accounting-export-windows-webui.sql

Adds window accounting export to webui menu. Creates the webui layout for main view, grid view and advanced edit. Adds translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3513

#3513 Webui: Pimp DATEV windows

---

Jenkinsfile

Use nexus.metasfresh.com as docker repo metasfresh/metasfresh-jenkins-pipeline#4

Gh4 jenkins

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/interceptor/Main.java
de.metas.material/dispo-commons/src/main/java-gen/de/metas/material/dispo/model/I_MD_Candidate.java
de.metas.material/dispo-commons/src/main/java-gen/de/metas/material/dispo/model/X_MD_Candidate.java
de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/DemandDetail.java
de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/CandidateRepositoryWriteService.java
de.metas.material/dispo-commons/src/test/java/de/metas/material/dispo/commons/candidate/DemandDetailTest.java
de.metas.material/dispo-commons/src/test/java/de/metas/material/dispo/commons/repository/CandiateRepositoryRetrievalTests.java
de.metas.material/dispo-commons/src/test/java/de/metas/material/dispo/commons/repository/CandidateRepositoryWriteServiceTests.java
de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ForecastCreatedHandler.java
de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/TransactionEventHandler.java
de.metas.material/dispo-service/src/main/sql/postgresql/system/5486390_sys_gh3541-app_MD_Candidate_mk_sql_columns_physical.sql
de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/candidatechange/CandidateChangeHandlerTests.java
de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/TransactionCreatedHandlerTests.java
de.metas.material/event/src/main/java/de/metas/material/event/commons/MaterialDescriptor.java
de.metas.material/event/src/main/java/de/metas/material/event/forecast/Forecast.java
de.metas.material/event/src/main/java/de/metas/material/event/forecast/ForecastCreatedEvent.java
de.metas.material/event/src/main/java/de/metas/material/event/forecast/ForecastLine.java

Div material dispo issues #3541

#3541 Div material dispo issues

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5486720_sys_gh3534-picking-configuration-window-webui.sql

Adds the window ID in table definition to allow the zoom to
https://github.com/metasfresh/metasfresh/issues/3534

#3534 Webui Window Design: Create window for Picking Config

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5486810_sys_gh3540-guarantee-days-product.sql

Adds the Min. guarantee Days Field to Product and Product Category
Windows in WebUI.
https://github.com/metasfresh/metasfresh/issues/3540

#3540 Adds Field to diff. WIndows in webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5486830_sys_gh3562_product-planning-subtab-primary.sql

Adds the primary layout to subtabs in Product planning window.
https://github.com/metasfresh/metasfresh/issues/3562

#3562 Adds primary layout to subtabs

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5487010_sys_gh3570_sys_add_CustomerLabelName_in_M_Product.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5487011_sys_gh3570_sys_add_CustomerLabelName_in_M_Product_ddl.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5487012_sys_gh3570_sys_add_CustomerLabelName_in_M_Product_Trl.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5487013_sys_gh3570_sys_add_CustomerLabelName_in_M_Product_Trl_ddl.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5487014_sys_gh3570_sys_add_CustomerLabelName_field_in_M_Product_window.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5487015_sys_gh3570_sys_add_CustomerLabelName_field_in_M_Product_trl_window.sql

https://github.com/metasfresh/metasfresh/issues/3570

#3570 add customerlabelname in product and trl

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.invoice/5486900_sys_gh3561_Relation_Between_Invoice_And_ShipmentRestriction.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.invoice/5486960_sys_gh3561_Relation_Between_ShipmentRestriction_And_Invoice.sql

https://github.com/metasfresh/metasfresh/issues/3561

#3561 Relation type Invoice <-> Shipment Restriction

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487020_sys_gh3556-compensation-group-window-improvement.sql

Adds new Fields to Compensation group Schema Window in webui and
rearranges the layout for main view, davanced edit and grid view.
https://github.com/metasfresh/metasfresh/issues/3556

#3556 Adds adjustments to webui window

---

de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_SubscriptionProgress.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/process/C_SubscriptionProgress_Evaluate.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/CreateMissingShipmentSchedulesWorkpackageProcessor.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_Order_ShipmentSchedule.java
de.metas.util/src/main/java/org/adempiere/util/lang/IAutoCloseable.java

Add api methods to enable one schedule invokaction at the end
SubscriptionBL: minor
Avoid mass-creation of "MissingShipmentSchedulesWorkpackages" https://github.com/metasfresh/metasfresh/issues/3582

#3582-app - Avoid mass-creation of "MissingShipmentSchedulesWorkpackages" 

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupFactory.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupInfo.java
de.metas.adempiere.adempiere/client/src/main/java/org/compiere/grid/ed/VLookupAutoCompleter.java

https://github.com/metasfresh/metasfresh/issues/3571

Gh3571 get rid of erro ron new column

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5487190_sys_gh3592_Invoice_And_Ispaid_In_ShipmentRestrictions.sql

https://github.com/metasfresh/metasfresh/issues/3592

#3592  Invoice and IsPaid in Shipment Restrictions

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/picking_tu_label/label.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/picking_tu_label.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5487130_sys_gh3576_add_picking_tu_label_function.sql

https://github.com/metasfresh/metasfresh/issues/3576
add jasper and function

#3576 add new picking tu label

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487320_sys_gh3513-accounting-export-window-menu-trl.sql

Adds Translations for en_US and a Layout adjustment to the accounting export an accounting export format window and corresponding window actions.
https://github.com/metasfresh/metasfresh/issues/3513

#3513 Adds Translations and Layout adjustment

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487320_sys_gh3513-accounting-export-window-menu-trl.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487340_sys_gh3540a-min-guarantee-days-trl.sql

https://github.com/metasfresh/metasfresh/issues/3540

#3540 webui: Show GuaranteeDaysMin on Product and Product Category windows

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/CompositeAttributeStorageFactory.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHU.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/HUShipmentProcess_2LU_1ShipTrans_1InOut_IntegrationTest.java

make shipment HU aggregation configurable #3575

#3575 - bugfix in make shipment HU aggregation configurable

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487500_sys_gh882-data-import-window.sql

New Data Import Window in WebUI. 2-column Layout.
https://github.com/metasfresh/metasfresh-webui-api/issues/882

#882 Data Import window

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_ImpFormat.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/impexp/ImpFormat.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487560_sys_gh3621_SupportSemicolon.sql

#3621 Allow semikolon delimiter for Import Format

#3621 Support semicolon when importing files

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487600_sys_gh3515-product-category-compensation-group-schema-trl.sql

Adds Translation for Field Compensation group Schema in de_DE Language
https://github.com/metasfresh/metasfresh/issues/3515

#3515 Adds Field Translation

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487610_sys_gh3029-import-format-window-webui.sql

New Window for Import Formats in WebUI. 2-column Layout, Advanced edit, Grid View, Sidelist for Main Tab and Subtabs. Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3029

#3029 WebUI: New Window for Import Formats

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/LookupDisplayColumn.java
de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfoColumn.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/impl/HUPickingSlotDAO.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5487590_sys_gh3634-app_picking_slot_display_logic.sql

* add display logic for picking slot parameter
* also minor code changes (unrelated)
Pick in manufacturing Order: Picking Slot Filter on selected BPartner from Shipment Schedule #3634

#3634-app - Pick in manufacturing Order: Picking Slot Filter on selected BPartner from Shipment Schedule

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487650_sys_gh3637-standalone-product-trl-window.sql

Create a Standalone Product translation window in webui.
https://github.com/metasfresh/metasfresh/issues/3637

#3637 Standalone Product Translation Window

---

de.metas.business/src/main/java/de/metas/order/OrderFactory.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilder.java
de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactory.java
de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemsAggregator.java
de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remoteorder/VendorGatewayInvoker.java
de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remotepurchaseitem/PurchaseItemRepository.java
de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemsAggregatorTest.java
de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/purchaseordercreation/remoteorder/NullVendorGatewayInvokerTest.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderBL.java
de.metas.util/src/main/java/org/adempiere/util/collections/MapReduceAggregator.java

Purchase order from purchase candidate not working #3569

#3569-app - Purchase order from purchase candidate not working

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487830_sys_gh3652-inventory-window-webui.sql

New Window in WebUI for Inventory Maintenance. 2-column Layout, Grid View, Advanced edit. Translation added for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3652

#3652 WebUI: New Inventory Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487880_sys_gh3591-shipment-stats-trl.sql

Adds translations of menu, window, tabs, and fields for de_DE, en_US Languages.
https://github.com/metasfresh/metasfresh/issues/3591

#3591 Add translations for headers in shipment statistics

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5487890_sys_gh773-package-window-webui.sql

Adds new Window for Package maintenance. Adds to webui menu. 2-column layout, grid view, and sidelist added. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh-webui-api/issues/773

#773 Add name and menu entry for WebUI window Package

---

de.metas.business/src/main/java/de/metas/order/IOrderBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderBL.java

https://github.com/metasfresh/metasfresh/issues/3667

Gh3667 Logic for transforming prospect into customer

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5488070_sys_gh3240_Drop_IsCentrallyMentained_Column_From_AD_Field.sql

https://github.com/metasfresh/metasfresh/issues/3240

#3240 Dropping this column finally.

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.payment/5488080_sys_gh1860_C_Payment_DocumentNo_UniqueIndex.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.payment/5488090_sys_gh1860_C_Payment_DocumentNo_UniqueIndex_DDL.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.payment/5488100_sys_gh1860_DocumentNo_NotUpdatable_In_C_Payment.sql

* unique index
* not updateble
https://github.com/metasfresh/metasfresh/issues/1860

Gh1860 documentno in payment

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5488150_sys_gh3658_InventoryLine_Index_Repaired.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5488160_sys_gh3658_InventoryLine_Index_Repaired_DDL.sql

https://github.com/metasfresh/metasfresh/issues/3659

Gh3659 Improve inventory line unique index

---

de.metas.printing.client/config.properties
de.metas.printing.client/pom.xml
de.metas.printing.client/src/main/java/de/metas/printing/client/ConfigFileContext.java
de.metas.printing.client/src/main/java/de/metas/printing/client/Context.java
de.metas.printing.client/src/main/java/de/metas/printing/client/endpoint/RestHttpPrintConnectionEndpoint.java
de.metas.printing.client/src/main/java/de/metas/printing/client/engine/PrintingClientDaemon.java
de.metas.printing.client/src/main/resources/sample-standalone-client-config.properties
de.metas.printing.common/de.metas.printing.api/src/main/java/de/metas/printing/esb/api/LoginRequest.java
de.metas.printing.common/de.metas.printing.api/src/main/java/de/metas/printing/esb/api/PrinterHWList.java
de.metas.printing.rest-api-impl/pom.xml
de.metas.printing.rest-api-impl/src/main/java/de/metas/printing/rest/PrinterHWRepo.java
de.metas.printing.rest-api-impl/src/main/java/de/metas/printing/rest/PrintingRestController.java
de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/Main.java

Port Printing REST endpoint from SMX to metasfresh 
also add an API-token config to printing client
Port Printing REST endpoint from SMX to metasfresh #3688

#3688-app - port the printing service endpoint from the camel bundle to metasfresh

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/report.properties

#3050 add missing label in property file

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_title.jrxml

https://github.com/metasfresh/metasfresh/issues/3497

#3497 take out default value

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5488390_sys_gh3701_fix_duplicates_fresh_ADR_umsatzliste_bpartner_report_function.sql

#3701 update fresh_ADR_umsatzliste_bpartner_report function

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/DB.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/InArrayQueryFilter.java
de.metas.ui.web.base/src/main/java/de/metas/ui/web/base/model/I_T_WEBUI_ViewSelection.java
de.metas.ui.web.base/src/main/java/de/metas/ui/web/base/model/I_T_WEBUI_ViewSelectionLine.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5488320_sys_gh894webui_T_WEBUI_ViewSelection_more_keys.sql

https://github.com/metasfresh/metasfresh-webui-api/issues/894

New Composed Primary Keys

---

de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
de.metas.contracts/src/test/java/de/metas/contracts/impl/ContractChangeBLTest.java

#3706 Terminating a Contract that was extended ahead of schedule leaves
stumb

#3706 set Void contract status if the change date is in past

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5488450_sys_gh3703-material-receipt-candidates-mediasize-restriction-columns.sql

Adds media size restrictions to different ui elements.
https://github.com/metasfresh/metasfresh/issues/3703

#3703 Material Receipt Candidates Window, add media types for mobile/ tablet

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5489070_sys_gh3585-bpartner-creditlimit-improvements.sql

Renames Fields, Subtabs and adds translations of Fields, Actions for de_DE.
https://github.com/metasfresh/metasfresh/issues/3585

#3585 WebUI window design: Business Partner Credit Limit

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5489100_sys_gh3743-distribution-editor-action-trl.sql

Renaming/ Translation the Move HU Action in Distribution Editor
https://github.com/metasfresh/metasfresh/issues/3743

#3743 Translation of Distribution Editor Quickaction

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5489240_sys_gh3755-businesspartner-virtual-column-max.sql

https://github.com/metasfresh/metasfresh/issues/3755

#3755 Adds Max() to Virtual Column sql

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5489200_sys_gh3749_sys_add_isPrintPrice_in_c_orderline.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5489201_sys_gh3749_sys_add_isPrintPrice_in_c_orderline_ddl.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5489202_sys_gh3749_sys_add_isPrintPrice_in_c_orderline_window_undisplayed.sql

#3749 add isPrintPrice in c_orderline

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5489640_sys_gh3784-product-bpartner-trl.sql

New WIndow for Business partner Product translation Maintenance.
https://github.com/metasfresh/metasfresh/issues/3784

#3784 Standalone BPartner Product Translation Window

---

de.metas.business/src/main/java/org/adempiere/impexp/product/ProductPriceImporter.java
de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5489610_sys_gh3748_AddMessageForInvalidProductPriceList.sql

#3748 Pharma: Regular import does not fail if prices aren't imported

#3748 Pharma: Regular import does not fail if prices aren't imported 

---

de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5489690_sys_gh3580_PickingLabel_Report_Process_Improvements.sql

https://github.com/metasfresh/metasfresh/issues/3580

Gh3580 Improvements in the Picking Label process

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5490130_sys_gh3585_bpartner-credit-limit.sql

https://github.com/metasfresh/metasfresh/issues/3585

#3585 Adds Translations

---

ReleaseNotes.md
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/QueryBuilder.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/persistence/ModelClassIntrospector.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHU.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleInvalidateBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentScheduleQtyPickedProductStorage.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/expectations/ShipmentScheduleQtyPickedExpectations.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_InOutLine_Shipment.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_InOut_Shipment.java
de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/inout/util/ShipmentScheduleQtyOnHandStorage.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5490150_sys_gh3822-app_update_M_ShipmentSchedule_QtyPicked_Processed.sql
de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAOTest.java
de.metas.swat/de.metas.swat.base/src/test/java/org/adempiere/inout/shipment/impl/ShipmentSchedule_QtyPicked_Test.java

ShipmentSchedule.QtyPickList not updated from drafted shipments #3822

#3822-app - ShipmentSchedule.QtyPickList not updated from drafted shipments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5490160_sys_gh902-api-auth-token.sql

https://github.com/metasfresh/metasfresh-webui-api/issues/902

#902api API token is not shown in the webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5490600_sys_gh3844-context-menu-trl-webui.sql

Adds Translations for de_DE to Context Menu in WebUI.
https://github.com/metasfresh/metasfresh/issues/3844

#3844 Adds new Translations for de_DE

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/util/IColorRepository.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/util/impl/ColorRepository.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5490390_sys_gh3835_C_OrderLine_NoPriceConditionsColor_ID.sql
de.metas.business/src/main/java/de/metas/order/IOrderLineBL.java
de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
de.metas.business/src/main/java/org/adempiere/pricing/api/DiscountResult.java
de.metas.business/src/main/java/org/adempiere/pricing/api/IPricingResult.java
de.metas.business/src/main/java/org/adempiere/pricing/api/impl/CalculateDiscountCommand.java
de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PricingBL.java
de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PricingResult.java
de.metas.business/src/main/java/org/adempiere/pricing/spi/impl/rules/Discount.java
de.metas.contracts/src/main/java/de/metas/contracts/flatrate/interfaces/IFlatrateConditionsAware.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderLineBL.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.pricing/5490490_gh3835_C_OrderLine_M_DiscountSchemaBreak.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.pricing/5490500_gh3835_C_OrderLine_M_DiscountSchemaBreak_DDL.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.pricing/5490520_gh3835_NoPriceConditionsColorName_SysConfig.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.pricing/5490520_gh3835_NoPriceConditionsColor_ID_SysConfig.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.pricing/5490530_gh3835_AD_Color_UniqueIndex_Name.sql

https://github.com/metasfresh/metasfresh/issues/3835

Gh3835 logic for NoPriceConditionsColor_ID  in orderline

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/picking/report_details.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/picking/report_details_name_over_attributes.jrxml

#2525 update barcode parameter

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491060_sys_gh3866-lot-control-window-webui-trl.sql

Add Translations for de_DE, en_US to Lot No. Control Window, Actions and Menu entries. Adds Layout for Single View, Grid View.
https://github.com/metasfresh/metasfresh/issues/3866

#3866 WebUI: Translation for Product LotNo Lock Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491200_sys_gh3749-businesspartner-pharma-layout-trl.sql

Adds Translations for de_DE, en_US. Adjustment for Subtab Layouts.
https://github.com/metasfresh/metasfresh/issues/3479

#3479 Window design: Business Partner Pharma

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/impl/AbstractTrxManager.java
de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
de.metas.contracts/src/main/java/de/metas/contracts/spi/FallbackFlatrateTermEventListener.java
de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/validator/PP_Order.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_OrderLine.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/ConfigValidator.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/M_InOutLine.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/M_InventoryLine.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_InventoryLine_Handler.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_invoicecandidate/views/c_invoice_candidate_missing_c_invoice_candidate_agg_id_v.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_invoicecandidate/views/c_invoice_candidate_missing_headeraggregation_effective_id_v.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_invoicecandidate/views/c_invoice_candidate_stale_qtyinvoiced_v.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_invoicecandidate/views/c_invoice_candidate_wrong_qty_ol_v.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_invoicecandidate/views/c_invoice_candidate_wrong_qtytoinvoice_v.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5491220_sys_gh3876-app_deactivate_ICs_with_dangling_references.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5491220_sys_gh3876-app_update_ic_troubleshoot_views.sql

(also see commit messages)
#3876

#3876-app - Different issues around invoice candidate updating

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491380_sys_gh3888-bpartner-pharma-adjustments.sql

Pharma Business Partner Window adjustments. New columns in DB Table c_bpartner. New Fields, WebUI Elements. Adjusted Layout for Main View, and Subtab Main and grid View for customer and vendor Subtab.
https://github.com/metasfresh/metasfresh/issues/3888

#3888 Pharma Business Partner Window adjustments

---

de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaCustomerPermission.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaCustomerPermissions.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaVendorPermission.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaVendorPermissions.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/I_C_BPartner.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/interceptor/C_BPartner.java

https://github.com/metasfresh/metasfresh/issues/3887

Gh3887 pharma permissions 

---

ReleaseNotes.md
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/BPartnerStats.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/IBPartnerStatsBL.java
de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/bpartner/service/IBPartnerStatsBLTest.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Order.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/I_C_BPartner.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/interceptor/C_BPartner.java
de.metas.vertical.pharma/src/main/sql/postgresql/system/5491480_sys_gh3890_UpdateCustomerPharmaPermissions_Process.sql
de.metas.vertical.pharma/src/main/sql/postgresql/system/5491490_sys_gh3890_UpdateVendorPharmaPermissions_Process.sql

https://github.com/metasfresh/metasfresh/issues/3890

Gh3890 update pharma permissions

---

de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_C_POS_HUEditor_Filter.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Item.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Item_Storage.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Item_Storage_Snapshot.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_LUTU_Configuration.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_PI_Attribute.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_PI_Item_Product.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_PackingMaterial.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Process.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Storage.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Storage_Snapshot.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Trx_Line.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_Picking_Candidate.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_PP_Order_Qty.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_RV_HU_Quantities.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_RV_M_Material_Tracking_HU_Details.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_C_POS_HUEditor_Filter.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU_Process.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_PP_Order_Qty.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/process/api/HUProcessDescriptor.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/process/api/IMHUProcessDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/process/api/impl/MHUProcessDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/HUReportService.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/HUToReport.java
de.metas.handlingunits.base/src/main/sql/postgresql/system/5491430_sys_gh3895-app_extend_M_HU_Process.sql
de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/report/model/HUReportModel.java

add two new flags for "provide as user" action and "only top-level-HU"
* IsProvideAsUserAction allows to configure a process to be available to be called via code, but not by users
* IsApplyToTopLevelHUsOnly replaces hardcoded filtering in some processed
* re-add Picking TU Label (Jasper)_Picking TU Label to M_HU_PRocess
* also some minor renamings and javadoc
* also recreated model classes
extend M_HU_Process #3895

#3895-app - extend M_HU_Process

---

de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/MailWorkpackageProcessor.java

https://github.com/metasfresh/metasfresh/issues/3909

Gh3909 Support html message in mail

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/product/callout/C_BPartner_Product.java
de.metas.business/src/main/java/org/adempiere/model/validator/AdempiereBaseValidator.java

https://github.com/metasfresh/metasfresh-webui-api/issues/949

#949-webui C_BPartner_Product org from Product's org

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/model/I_C_InvoiceLine.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491840_sys_gh3929_BasePricingSystem_OrderLine.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491850_sys_gh3929_BasePricingSystem_OrderLine_DDL.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491860_sys_gh3929_BasePricingSystem_InvoiceLine.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5491870_sys_gh3929_BasePricingSystem_InvoiceLine_DDL.sql
de.metas.business/src/main/java/org/adempiere/pricing/api/DiscountResult.java
de.metas.business/src/main/java/org/adempiere/pricing/api/IPricingResult.java
de.metas.business/src/main/java/org/adempiere/pricing/api/impl/CalculateDiscountCommand.java
de.metas.business/src/main/java/org/adempiere/pricing/api/impl/PricingResult.java
de.metas.business/src/main/java/org/adempiere/pricing/spi/impl/rules/Discount.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/InvoiceLineBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderLineBL.java

https://github.com/metasfresh/metasfresh/issues/3929

Gh3929 base pricing system in orderline and invoiceline

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5492000_sys_gh3923_DisplayNewFields_M_Packageable_V.sql

https://github.com/metasfresh/metasfresh/issues/3923

Gh3923 display the new fields in Packageable view

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Invoice_Candidate.java

#3933 Credit limit: Credit used does not update when you reverse/void
order

#3933 Update statistics when voiding and order or an invoice

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492150_sys_gh3137-payment-selection-trl.sql

Adds Translations for en_US. Adds missing Actions in Action menu.
https://github.com/metasfresh/metasfresh/issues/3137

#3137 Clean C_PaySelection

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492165_sys_gh3814-myprofile-notifications.sql

https://github.com/metasfresh/metasfresh/issues/3814

#3814 Adds Fields to Main View in WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492200_gh3899-handling-unit-process-webui.sql

Adds a new Window for Handling Unit Processes Configuration to WebUI. 2-column Main View, Grid View, Sidelist. Adds Translations for en_US.

#3899 Webui window for M_HU_Process

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492210_sys_gh3740-orginfo-warehousepo.sql

New Field, translations fir de_DE. Added to Grid View.
https://github.com/metasfresh/metasfresh/issues/3740

#3740 WebUI: add Warehouse PO column to Organization/Org Info window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492230_sys_gh3812-copy-acct-records-product-category.sql

Adds copy acct action to product category window
https://github.com/metasfresh/metasfresh/issues/3812

#3812 Add process for creating missing M_Product_acct records to WebUI

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492240_sys_gh3965-pharma-permissions-action-trl.sql

Adds translations for de_DE
https://github.com/metasfresh/metasfresh/issues/3965

 #3965 Translate Actions Update Pharma Conditions

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492250_sys_gh3967-action-update-pharma-permissions-parms-trl.sql

Adds Translations to Action Parms for Vendor and Customer in Languages de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3967

#3967 Translate Process Parm in Update Pharma Conditions for Customers

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492300_sys_gh3971-pp-workflow-adjustments-webui.sql

https://github.com/metasfresh/metasfresh/issues/3971

#3971 Adds mandatory Field AccessLevel

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492310_sys_gh3873-pp-workflow-adjustments-webui.sql

Window, Fields and Layout adjustments for Manufacturing Workflow Window in WebUI.
https://github.com/metasfresh/metasfresh/issues/3973

#3973 Manufacturing Workflow adjustments in WebUI

---

de.metas.vertical.pharma/src/main/sql/postgresql/system/5492360_sys_gh3969_AddPharmaPermissionsInOrder.sql

#3969 Pharma: If Shipment Auth Type B then show in Order Header

#3969 Add pharma permission fields in order header

---

de.metas.handlingunits.base/src/main/sql/postgresql/system/5492410_sys_gh2558_LUTU_Config_Valrule_PP_Order.sql

https://github.com/metasfresh/metasfresh/issues/2558

#2558 In PP_Order, only allow LUTU configs that are suitable for the product

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492510_sys_gh3312-window-table-column-webui.sql

New Window for Table and Columns Window in WebUI. Main View, Grid View, Sidelist, Subtabs. Added Actions, removed Button Fields.
https://github.com/metasfresh/metasfresh/issues/3312

#3312 Webui Window Design: Improve window Table and Column

---

de.metas.business/src/main/java/org/adempiere/impexp/product/ProductPriceImporter.java
de.metas.vertical.pharma/src/main/sql/postgresql/system/5492570_sys_gh3977_Fix ImportFormatForIFAIMport.sql

#3977  Pharma: Prices from IFA import are in cents

#3977  Pharma: Prices from IFA import are in cents 

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/Adempiere.java
de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSet.java
de.metas.business/src/main/java/org/adempiere/mm/attributes/api/ImmutableAttributeSet.java
de.metas.business/src/main/java/org/adempiere/mm/attributes/spi/IAttributeValueCallout.java
de.metas.business/src/main/java/org/adempiere/mm/attributes/spi/NullAttributeValueCallout.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/IAttributeStorage.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/AbstractAttributeStorage.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/NullAttributeStorage.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/IHUToReceiveValidator.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/CompositeHUToReceiveValidator.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleBL.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/util/HUTopLevel.java
de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/InOutProducerFromReceiptScheduleHU.java
de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/receiptschedule/impl/InOutProducerFromReceiptScheduleHUTest.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/InOutProducer.java
de.metas.swat/de.metas.swat.base/src/test/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBLTest.java
de.metas.vertical.pharma/pom.xml
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/attributes/RepackNumberAttributeCallout.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/attributes/RepackNumberHUToReceiveValidator.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/attributes/RepackNumberUtils.java
de.metas.vertical.pharma/src/main/sql/postgresql/system/5492550_sys_gh3989_RepackNumber_support.sql

https://github.com/metasfresh/metasfresh/issues/3989

pharma: repack number attributes

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5492740_sys_gh4004-pharma-discount-window-webui.sql

Adds adjustment to the new Window Discount Schema Pharma. Adds Translations for de_DE and en_US.
https://github.com/metasfresh/metasfresh/issues/4004

#4004 WebUI: Adjust new Window Discount Schema Pharma

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5492840_sys_gh3993_Drop_Ampersand_From_Messages.sql

https://github.com/metasfresh/metasfresh/issues/3993

#3993 Drop '&' before words in ad_messages

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/der_kurier/report.jrxml

Gh3926 app

---

de.metas.vertical.pharma/src/main/sql/postgresql/system/5492940_sys_gh3982_Repair_PharmaDiscountSchema_Window.sql

https://github.com/metasfresh/metasfresh/issues/3982

Gh3982 improve window pharma discount schema

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/api/IHUDDOrderDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/api/QuarantineInOutLine.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/api/impl/HUDDOrderDAO.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/api/impl/HUs2DDOrderProducer.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/DistributeAndMoveReceiptHandler.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/LotNumberLock.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/LotNumberLockRepository.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5493070_sys_gh4013_LotNoLock_Unique_Index.sql

https://github.com/metasfresh/metasfresh/issues/4013

Gh4013 refactoring around lot no lock

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5493160_sys_gh4003-derkurier-delivery-order-webui.sql

New Window for Der Kurier Transportation Orders. Adds 2-column Main View, Grid View, and Sidelist Layout. Adds Subtab Layout. Adds Translations for en_US.
https://github.com/metasfresh/metasfresh/issues/4003

#4003 Adjust Window "Der Kurier Versandauftrag"

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5493239_sys_gh4015-app_add_yesNoUnknown.sql
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/I_MKTG_Campaign.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/I_MKTG_Campaign_ContactPerson.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/I_MKTG_ContactPerson.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/X_MKTG_Campaign.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/X_MKTG_Campaign_ContactPerson.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/X_MKTG_ContactPerson.java
de.metas.marketing/base/src/main/java/de/metas/marketing/base/interceptor/MKTG_ContactPerson.java
de.metas.marketing/base/src/main/sql/postgresql/system/90-de.metas.marketing.base/5493240_sys_gh4015-app_add_new_Stuff_for_sync_and_Remote_status.sql
de.metas.marketing/base/src/main/sql/postgresql/system/90-de.metas.marketing.base/5493245_sys_gh4015-app_migrate_and_make_mandatory.sql
de.metas.marketing/cleverreach/src/main/sql/postgresql/system/92-de.metas.marketing.cleverreach/5493242_sys_gh4015-app_add_cleverreach_platform.sql

#4015-app CleverReach Interface - generic data model extended

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/process/M_Inventory_CreateCountLinesFromHU.java

#3754 Inventory: Allow only "Active" and "Issued" HUs in inventorylines

#3754 Exclude HUs with Planning Status

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5493710_sys_gh4056-puchase-schedule-tab-bpartner-pharma-webui.sql

Adds Layout in WebUI for the new Purchase Schedule Datastructure in Pharma Businesspartner Window.
https://github.com/metasfresh/metasfresh/issues/4056

#4056 Webui: pimp Partner Pharma - Purchase schedule tab

---

de.metas.business/src/main/java/org/adempiere/impexp/inventory/InventoryImportProcess.java
de.metas.business/src/main/java/org/adempiere/impexp/inventory/MInventoryImportTableSqlUpdater.java

#3800 Improve inventory import

#3800 Improve inventory import

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/spi/impl/DDOrderLineHUDocumentHandler.java
de.metas.handlingunits.base/src/main/sql/postgresql/system/5493530_sys_gh4018_SYSConfig_Enforce_DDOrderline_M_HU_PI_Item_Product.sql
de.metas.handlingunits.base/src/main/sql/postgresql/system/5493720_sys_gh4018_SYSConfig_Enforce_DDOrderline_M_HU_PI_Item_Product_Docu.sql

https://github.com/metasfresh/metasfresh/issues/4018

Gh4018 option to not enforce M_HU_PI_Item_Product in DD_OrderLine

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/process/M_Inventory_CreateCountLinesFromHU.java

#3753 Inventory: Prepare Inventorylines shall update existing lines

#3753 Inventory: Prepare Inventorylines shall update existing lines 

---

de.metas.business/src/main/java/de/metas/order/OrderId.java
de.metas.business/src/main/java/de/metas/order/OrderLineId.java
de.metas.business/src/main/java/de/metas/order/grossprofit/GrossProfitComponent.java
de.metas.business/src/main/java/de/metas/order/grossprofit/GrossProfitComponentProvider.java
de.metas.business/src/main/java/de/metas/order/grossprofit/GrossProfitPrice.java
de.metas.business/src/main/java/de/metas/order/grossprofit/GrossProfitPriceFactory.java
de.metas.business/src/main/java/de/metas/order/grossprofit/interceptor/C_OrderLine.java
de.metas.business/src/main/java/de/metas/order/grossprofit/model/I_C_OrderLine.java
de.metas.business/src/main/java/de/metas/order/package-info.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/InvoiceCandidateAssignmentService.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/RefundContractQuery.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/RefundContractRepository.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/grossprofit/OrderLine.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/grossprofit/OrderLineRepository.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/grossprofit/RefundGrossProfitComponent.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/grossprofit/RefundGrossProfitComponentProvider.java
de.metas.contracts/src/test/java/de/metas/contracts/refund/InvoiceCandidateAssignmentServiceTest.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.order/5493950_sys_gh4001-app_add_C_OrderLine_PriceGrossProfit.sql

WIP for purchase invoice lines
#4001

#4001-app - Calculate Purchase price with yearly Bonus

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494030_sys_gh4070-flatrate-terms-bonus-refund-webui.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494040_sys_gh4070-invoicecand-bonus-refund-webui.sql

Adds new Tabs for Refund Bonus to Flatrate Conditions and Invoice Candidates. Adds Translations for de_DE, en_US. Adds Gris Layout and Advanced edit.
https://github.com/metasfresh/metasfresh/issues/4070

#4070 WebUI Windows for new contract Type "Yearly Bonus from vendors"

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5493940_sys_gh4079_CopyAD_User_ID_Bill_User_ID.sql

#4079 Contact is not set when order is cloned

#4079 Contact is not set when order is cloned 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494170_sys_gh3323-invoicecand-handler-webui.sql

Adds Window Layout for WebUI. 2-column Layout, Grid View, Advanced edit, Sidelist. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3323

#3323 Webui Window Design: Improve window Rechnungskandidaten - Handler

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494390_sys_gh4094-contracttype-bonus-mandatory-logic.sql

https://github.com/metasfresh/metasfresh/issues/4094

#4094 Create Mandatory Logic in Contract terms

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494420_sys_gh4089-missing-refund-fields-webui.sql

Adds new Fields for Refund Contracts in Purchase Orderlines, Invoice Candidates Refund Subtab. Adds Translations.
https://github.com/metasfresh/metasfresh/issues/4089

#4089 Create missing fields for Bonus in WebUI

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report_details_footer.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_details_footer.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_footer.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details_footer.jrxml

#3307 take out documentnote from doctype

#3307 update report details footer for order and invoice

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494530_sys_gh3263-bom-translation-window-webui.sql

New Window for BOM & Formula Translation. 2-column Layout, Grid View, Advanced Edit, Sidelist. Adds Menu entry. Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/3263

#3263 WebUI: Translation Window for Bill of Materials and Formula

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494540_sys_gh4102-purchase-schedule-adjustments.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494550_sys_gh3996-client-window-email-adjustments.sql

Adjustments for Client window in webui. Rearranging/ Grouping eMail Fields. Adds Translations/ Name adjustments for de_DE.
https://github.com/metasfresh/metasfresh/issues/3996

#3996 Webui: Client window: EMail fields layout

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494540_sys_gh4102-purchase-schedule-adjustments.sql

Adds Translations to Business Partner Pharma Window Purchase Schedule. Adds Display Logic for Day of month.
https://github.com/metasfresh/metasfresh/issues/4102

#4102 webui: Purchase schedule tab - trl and display

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494590_sys_gh4117-product-window-field-trl.sql

https://github.com/metasfresh/metasfresh/issues/4117

#4117 WebUI: Add missing Translations in Product Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494600_sys_gh4119-tax-category-trl-window-webui.sql

New Translation Window for Tax Category in WebUI. Adds 2-column Layout, Grid View, Sidelist. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/4119

#4119 WebUI: Translation Window for Tax Category

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494610_sys_gh4116-tax-translation-window-webui.sql

New Window for Tax Rate Translations. 2-column Layout, Grid View, Sidelist. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/4116

#4116 WebUI: Translation Window for Tax Rates

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494860_sys_gh4138-paymentterm-trl-window-webui.sql

New Window for Payment term Translations. Adds 2-column layout, Grid View, sidelist. Adds document reference from payment term masterdata window.
https://github.com/metasfresh/metasfresh/issues/4138

#4138 WebUI: Translation Window for Paymentterm

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5494960_sys_gh4165-invoicecand-filter-webui.sql

Adds new Filter criteria to Billing Candidates window so that the user can search for contract data explicitly.
https://github.com/metasfresh/metasfresh/issues/4165

#4165 Extend Billing Candidates Filtering for contracts

---

de.metas.shipper.gateway.derkurier/src/main/sql/postgresql/system/99-de.metas.shipper.gateway.derkurier/5494900_cli_gh41-dist_DerKurierShipper_SetPartnerId.sql

https://github.com/metasfresh/metasfresh-dist/issues/41

#41-dist set the org bpartner to the dummy Der Kurier Shipper

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5495110_sys_gh4173-purchasedispo-fields-trl.sql

Adds Fieldnames in de__DE and Translations for en_US.
https://github.com/metasfresh/metasfresh/issues/4173

#4173 Translations for Purchase Dispo modal Overlay Fields

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5495230_sys_gh4178-pricing-cond-action-trl.sql

https://github.com/metasfresh/metasfresh/issues/4178

#4178 Pricing Conditions Cockpit Translations in Material Cockpit

---

de.metas.marketing/base/src/main/sql/postgresql/system/90-de.metas.marketing.base/5495520_sys_gh4031_DefaultMarketingCampaign_Flag_Webui.sql

https://github.com/metasfresh/metasfresh/issues/4031

#4031 add the default marketing campaign flag in webui

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5495540_sys_gh4143-message-trl-webui.sql

New Window for Message translations in WebUI. Adds 2-column Menu, Grid View and Sidelist. Adds Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/4143

#4143 WebUI: Translation Window for Messages

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Average_Product_Prices.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Average_Product_Prices_Old.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5495510_sys_gh4188_fix_average_product_prices.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5495511_sys_gh4188_average_product_prices_backup.sql

#4188 update average_product_prices function and create backup

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5495690_sys_gh4201-deliveryrule-partner-salesorder-webui.sql

Adds the Field DeliveryRule to Business Partner, Business Partner Pharma and Sales Order Window in WebUI.
https://github.com/metasfresh/metasfresh/issues/4201

#4201 WebUI: Show DeliveryRule in Businesspartner Customer and Sales Order

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5495730_sys_gh3028-window-import-coa-webui.sql

New Window for Chart of Accounts in WebUI. Adds 2-column Layout, Grid View, Sidelist.
https://github.com/metasfresh/metasfresh/issues/3028

#3028 WebUI: New Window for Import COA

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/IBPartnerDAO.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartner/service/impl/BPartnerDAO.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartnerlocation/BPartnerLocation.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartnerlocation/BPartnerLocationId.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/bpartnerlocation/BPartnerLocationRepository.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/location/LocationRepository.java
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/SerialLetter/report.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Generic_BPartner_Report.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5495740_sys_gh4153_.docs_generics_bpartner_report.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5495740_sys_gh4153_Docs_generics_bpartner_report.sql
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/I_MKTG_Campaign_ContactPerson.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/I_MKTG_ContactPerson.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/X_MKTG_Campaign_ContactPerson.java
de.metas.marketing/base/src/main/java-gen/de/metas/marketing/base/model/X_MKTG_ContactPerson.java
de.metas.marketing/base/src/main/java/de/metas/marketing/base/CampaignService.java
de.metas.marketing/base/src/main/java/de/metas/marketing/base/interceptor/C_BPartner_Location.java
de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/ContactPerson.java
de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/ContactPersonRepository.java
de.metas.marketing/base/src/main/sql/postgresql/system/90-de.metas.marketing.base/5495760_sys_gh4153_AddC_BPartner_Location_ID.sql
de.metas.marketing/base/src/main/sql/postgresql/system/90-de.metas.marketing.base/5495761_sys_gh4153_UpdatePlatform.sql
de.metas.marketing/serialletter/src/main/java/de/metas/letter/service/async/spi/impl/C_Letter_CreateFromMKTG_ContactPerson_Async.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/letters/model/LetterRepository.java

#4153 Serial Letter Feature 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496030_sys_gh4242-eventlog-window-webui.sql

Adds eventlog window to webUI menu 
https://github.com/metasfresh/metasfresh/issues/4242

#4242 WebUI: Window Event Log

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496040_sys_gh4244-purchase-cand-adjustments-webui.sql

Adds additional Fields to Purchase candidates. Ads Translations for de_DE, enUS. Adjusts widget sized for Grid View.
https://github.com/metasfresh/metasfresh/issues/4244

#4244 Purchase Candidates adjustments

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496070_sys_gh4140-country-translation-webui-window.sql

New Window in WebUI for Country Maintenance. Added to WebUI Menu. 2-column Layout, Grid View, Sidelist Layout. Translations added for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/4140

#4140 WebUI: Translation Window for Country

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496100_sys_gh4240-repack-nr-trl.sql

Adds Translations for different Attributes in de_DE.
https://github.com/metasfresh/metasfresh/issues/4240

#4240 Translate new Repack Attributes

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496170_sys_gh4255-contract-user-in-charge-systemuser.sql

Adds new ValRule
https://github.com/metasfresh/metasfresh/issues/4255

#4255 Contract Person in Charge not filtered by Systemuser

---

de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5495390_sys_gh4146_ConsiderAttributes_Message.sql

https://github.com/metasfresh/metasfresh/issues/4146

#4146-app Picking: Show HU Products with not exact Attribute matching

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496570_sys_gh4224-pharma-certificate-fields.sql

New Certification Fields in Business Partner Window for Customer and Vendor.
- GDP Certificate
- QMS Certificate
- Certificate of Registry
- Self Disclosure
- Contact and Status Info
https://github.com/metasfresh/metasfresh/issues/4224

#4224 Pharma: Additional Document/ Certificate Fields

---

de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_details.jrxml
de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_details_v2.jrxml

#4270 take price from purchase order as it is

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_BOMLine.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_BOMLine.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_BOMLine.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_BOMLine.java
de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/grid/ed/VLookup.java
de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPOrderBOMBL.java

#4273 Copy BOM Consumer Label Fields to PP Order BOMLine

#4273 Copy BOM Consumer Label Fields to PP Order BOMLine 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496790_sys_gh4293-msv3-customer-config.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5496880_sys_gh4293-msv3-customer-config.sql

New MSV3 Windows in WebUI für Customer Config and Server Configuration
https://github.com/metasfresh/metasfresh/issues/4293

#4293 WebUI: New Window for MSV3 Customer Window

---

de.metas.business/src/main/java/org/adempiere/mm/attributes/api/ImmutableAttributeSet.java

https://github.com/metasfresh/metasfresh/issues/4276

#4276 avoid npe in picking terminal

---

de.metas.material/dispo-service/src/main/sql/postgresql/system/5497020_sys_gh4308-app_C_OrderSO_zoomto_MD_Candidate.sql

#4308 Zoom from sales order to material dispo should open all referencing records

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5497110_sys_gh4318_add_CreateMissingShipmentSchedulesWorkpackageProcessor_and_UpdateInvalidShipmentSchedulesWorkpackageProcessor.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5497111_sys_gh4318_delete_M_ShipmentSchedule_Update_processor.sql

#4318 add new shipment schedules processors

---

de.metas.business/src/main/java/org/adempiere/mm/attributes/api/ImmutableAttributeSet.java
de.metas.business/src/test/java/org/adempiere/mm/attributes/api/ImmutableAttributeSetTest.java

https://github.com/metasfresh/metasfresh/issues/4276

#4276 small unit test for null attribute in immutableAttributeSet

---

de.metas.vertical.pharma/src/main/sql/postgresql/system/5497160_sys_gh4217_MakeIFAFieldReadOnly.sql

#4217 A Product Fields in Pharma Product readonly

#4217 Make IFA fields read only

---

de.metas.business/src/main/java/de/metas/order/IOrderLineInputValidator.java
de.metas.business/src/main/java/de/metas/order/OrderLine.java
de.metas.business/src/main/java/de/metas/order/OrderLineInputValidatorResults.java
de.metas.business/src/main/java/de/metas/order/OrderLineRepository.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaOrderLineInputValidator.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/interceptor/C_OrderLine.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/interceptor/C_OrderLine_PharmaInterceptor.java

https://github.com/metasfresh/metasfresh/issues/4218

Gh4218 Sales orders for prescription meds using Add New

---

de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/LotNumberLock.java

https://github.com/metasfresh/metasfresh/issues/4220

#4220  Repair bug

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java

https://github.com/metasfresh/metasfresh/issues/4349

#4349 repair quickentry bpartner bug

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5497670_sys_gh4336-docoutbound-email-fields-webui.sql

Adds new eMail Fields to Doc Outbound Window. Adjusts the Grid View. Adds new Filter Criterial. Adds missing Translations for de_DE, en_US.
https://github.com/metasfresh/metasfresh/issues/4336

#4336 WebUI: add email fields to C_Doc_OutBound

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5497680_sys_gh4292-hu-reservation-window-webui.sql

New Window for HU Reservation in WebUI
https://github.com/metasfresh/metasfresh/issues/4292

#4292 Make a Webui-Window for HU Reservation

---

de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
de.metas.business/src/main/java/org/adempiere/invoice/service/IInvoiceBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/callout/C_Invoice.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/AbstractInvoiceBL.java

https://github.com/metasfresh/metasfresh/issues/4185

Gh4185 Copy description and documentnote from doctype to invoice, if they exist

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5497590_sys_gh2558_Available_LUTUConfig_In_PPOrder.sql

* Note: Only covers the lutu configs that already exist.
https://github.com/metasfresh/metasfresh/issues/2558

#2558 Available LUTU Configs in PP_Order

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/HUReportExecutor.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/HUReportService.java

..also use ILoggable in HUReportService to log to AD_Pinstqance what's going on, e.g. why a particular job was not printed
Notification if automatic TU label print failed https://github.com/metasfresh/metasfresh/issues/4395

#4395-app - send notification from HUReportExecutor;

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5497770_sys_gh3790_fix_fresh_IL_To_IOL_V.sql

#3790 avoid duplicates

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/C_OrderLine.java

https://github.com/metasfresh/metasfresh/issues/4405

#4405 bug repair: don't change priceEntered for copy orderlines

---

de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/interceptor/AD_User.java

* On new is not a valid option because a user can't have contat persons if it doesn't exist.
https://github.com/metasfresh/metasfresh/issues/4216

#4216 change the AD_User callout to only work on change.

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Product.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Product.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498150_sys_gh4417_Ingredients_In_BPartnerProduct.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498160_sys_gh4417_Ingredients_In_BPartnerProduct_DDL.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498170_sys_gh4417_Ingredients_In_BPartnerProduct_Trl.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498180_sys_gh4417_Ingredients_In_BPartnerProduct_Trl_DDL.sql

https://github.com/metasfresh/metasfresh/issues/4417

Gh4417 Ingredients in BP Product + translation + repair the translation table

---

de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5498350_sys_gh4303-app_add_payment_discount_fields_to_webui.sql

#4303-app - Extend webui for PaymentDiscount

---

de.metas.business/src/main/java/de/metas/payment/paymentterm/interceptor/C_OrderLine.java
de.metas.business/src/main/java/de/metas/pricing/rules/Discount.java
de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Order.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/order/restart/RelatedSubscriptionsForOrdersProvider.java
de.metas.contracts/src/main/java/de/metas/contracts/subscription/order/restart/VoidSubscriptionRelatedToOrderHandler.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5498650_sys_gh4434-app_c_flatrate_term_orderline_id.sql
de.metas.contracts/src/test/java/de/metas/contracts/subscription/order/restart/RelatedSubscriptionsForOrderProviderTest.java

#4434-app - Process to void order and revert flatrate terms should void not terminate

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498590_sys_gh4437_ShowDescriptionAndDescriptionBottomInOurchaseOrder.sql

#4437 Purchase order: Show description and description bottom

#4437 Add description and description bottom in Purchase order

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Order_Details_Sum.sql
de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5498290_sys_gh4423_Docs_Purchase_Order_Details_Sum.sql

#4423 Add vattaxid in Docs_Purchase_Order_Details_Sum function

#4423 add vattaxid

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/process/AD_Tab_CreateFields.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/process/TablePrimaryKeyGenerator.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498520_sys_gh4426-app_AD_Tab_Create_fields_add_IsDisplayed_param.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498530_sys_gh4426-app_add_missing_sales_purchase_order_fields.sql

add missing fields for sales&purchase order; extend AD_Tab_CreateFields
and rename it from TabCreateFields; it can now directly create fields with IsDisplayed='N'
Error on new purchase order #4426

#4426-app - Error on new purchase order

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498670_sys_gh4417_Make_Sure_Ingredients_Is_Translated.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498690_sys_gh4417_Make_Sure_Ingredients_Is_Translated_DDL.sql

https://github.com/metasfresh/metasfresh/issues/4417

Gh4417 Make sure Ingredients field is correctly translated

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498700_sys_gh4416_Make_Sure_NutritionAndAlergens_Are_Translated_DDL.sql

https://github.com/metasfresh/metasfresh/pull/4416

Gh4416 Make sure all is translated

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498850_sys_gh1017-api_add_missing_product_subtab_fields.sql

also add missing fields for C_BPartner_Product
Adding a new price for a product not possible https://github.com/metasfresh/metasfresh-webui-api/issues/1017

#1017 - Adding a new price for a product problem; add missing AD_Fields

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498770_sys_gh4417_Product_And_BPartnerProduct_Trl_Repairments.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498780_sys_gh4417_Product_And_BPartnerProduct_Trl_Repairments_DDL.sql
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5498790_sys_gh4416_Nutrition_And_Allergen_Improvements.sql

https://github.com/metasfresh/metasfresh/issues/4417

#4417 Improve translations again

---

de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java
de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/AbstractQueryBuilderDAO.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/SqlQueryUnion.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/LocatorId.java
de.metas.dimension/src/main/java/de/metas/dimension/DimensionSpec.java
de.metas.dimension/src/main/java/de/metas/dimension/DimensionSpecGroup.java
de.metas.dimension/src/test/java/de/metas/dimension/DimensionSpecTest.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_Stock_Detail_V.java
de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU_Stock_Detail_V.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/stock/HUStockInfo.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/stock/HUStockInfoQuery.java
de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/stock/HUStockInfoRepository.java
de.metas.handlingunits.base/src/main/sql/postgresql/ddl/views/M_HU_Stock_Detail_V.sql
de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5498830_sys_gh4459-app_migration_2018-08-03_postgresql.sql

* add M_HU_Stock_Detail_V to list individual top level HUs for particular material cockpit rows
* add repository and stuff
* DimensionSpecGroup now also contains the attributeIds (if any) of the included attributes
Material Cockpit - show stock details https://github.com/metasfresh/metasfresh/issues/4459

#4459-app - Material Cockpit - show stock details

---

de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/event/FlatrateUserNotificationsProducer.java
de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Extend.java
de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Extend_And_Notify_User.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Order.java
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5498860_sys_gh4444_Contracts_Notification_Group.sql
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5498890_sys_gh4444_c_flatrate_term_table_link_to_right_window.sql
de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5498900_sys_gh4444_Flatrate_Term_Change_Process_Name.sql
de.metas.contracts/src/test/java/de/metas/contracts/impl/ContractChangeBLTest.java
de.metas.contracts/src/test/java/de/metas/contracts/impl/ExtendContractTest.java
de.metas.contracts/src/test/java/de/metas/contracts/impl/TerminateSingleContractTest.java

*  and make sure the user in charged is informed if a contract is about to expire
https://github.com/metasfresh/metasfresh/issues/4444

Gh4444 Use new notifications api for flatrate notifications

---

de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java

#4464 Report Business Partner revenue is not working anymore in swing

#4464 Don't filter out if availbaletrx is null

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5498940_sys_gh4462_add_missing_fields_in_user.sql

#4462 add missing fields in user

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5498960_sys_gh4461-app_add_missing_fields.sql

Cannot create a new request https://github.com/metasfresh/metasfresh/issues/4461

#4461-app - Cannot create a new request - add/activate missing fields

---

de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/ContactPersonRepository.java

…ct person then none is taken
https://github.com/metasfresh/metasfresh/issues/4216

#4216 make sure if an empty location fits for the MKTG campaign contact person then none is taken

---

de.metas.contracts/src/main/java/de/metas/contracts/Contracts_Constants.java
de.metas.contracts/src/main/java/de/metas/contracts/event/FlatrateUserNotificationsProducer.java
de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/interceptor/C_Flatrate_Term.java
de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5499160_sys_gh4444_Contract_Table_Window_Revert.sql

https://github.com/metasfresh/metasfresh/issues/4444

Gh4444 improvements and repairments

---

de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
de.metas.swat/de.metas.swat.base/src/test/java/de/metas/order/interceptor/OrderTest.java

https://github.com/metasfresh/metasfresh/issues/4482

Gh4482 doc type description repairment

---

de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5499590_sys_gh4504_FixMandatoryLogicForC_FlatrateTerm_C_Currency_ID.sql

#4504 Mandatory logic broken for C_FlatrateTerm.C_Currency_ID

#4504 Fix mandatory logic

---

de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java

https://github.com/metasfresh/metasfresh/issues/4509

#4509 repair language selection in process context

---

de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5499630_sys_gh4483_Fix_getopeninvoices.sql

#4483 Payment allocation form does not show invoices

#4483 Fix getopeninvoices

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5500060_sys_gh4530-country-postal-city-adjustments.sql

https://github.com/metasfresh/metasfresh/issues/4530

#4530 WebUI Adjustments for Country, Postal and City Window

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5500480_sys_gh4538-requesttype-trl-window-webui.sql

New Window for Request Type Translation in WebUI.
https://github.com/metasfresh/metasfresh/issues/4538

#4538 WebUI: New Translation Window for R_RequestType

---

de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/process/M_Inventory_CreateCountLinesFromHU.java

#4448 Advanced BLs to create inventory lines

#4448  Fix NOK Process "Prepare Inventorylines" is not working

---

de.metas.business/src/main/java/de/metas/order/PriceAndDiscount.java
de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTermService.java
de.metas.business/src/main/java/de/metas/pricing/conditions/service/impl/PricingConditionsRepository.java
de.metas.contracts/src/main/java/de/metas/contracts/refund/RefundConfigRepository.java
de.metas.contracts/src/test/java/de/metas/contracts/refund/CandidateAssignServiceTest.java
de.metas.contracts/src/test/java/de/metas/contracts/refund/RefundInvoiceCandidateServiceTest.java
de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/InvoiceCandidateWriter.java
de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/InvoiceDetailWriter.java
de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/interceptor/C_PurchaseCandidate.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/InvoiceLineBL.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandInvalidUpdater.java
de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5500820_sys_gh4550-app_add_purchase_aorder_fields_tweak_processes.sql
de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5500820_sys_gh4550-app_add_purchase_order_fields_tweak_processes.sql
de.metas.util/src/main/java/de/metas/lang/Percent.java
de.metas.util/src/test/java/de/metas/lang/PercentTest.java
de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/pricing/PharmaPriceLimitRuleInstance.java

* add the respective fields to the purchase order window
* also translate process names, improve AD_SysConfig help and add a helpful process reject-AD_Message
* rename Percent.getValueAsBigDecimal() to Percent.getValueOrNull() and add a static convenience method Percent.getValueOrNull
metasfresh/metasfresh#4550

#4550-app - Show Pricing Condition Indicator in Purchase Orders

---

de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java

#4552 AD_user is wrong in shipment schedule when using isDropShip

#4552 Trigger the validator also when the drop ship user is changed

---

de.metas.dunning/src/main/java/de/metas/dunning/DunningDocId.java
de.metas.dunning/src/main/java/de/metas/dunning/invoice/DunningService.java
de.metas.dunning/src/main/java/de/metas/dunning/process/ConcatenateDunningAndInvoicesPDFs.java
de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5500910_sys_gh4554_AddConcatenateProcess.sql

#4554 process to create dunning-PDF with concatenated invoice-PDFs

#4554 process to create dunning-PDF with concatenated invoice-PDFs 

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_UI_ElementField.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_UI_ElementField.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5500900_sys_gh1037-api_tootip_ui_elements.sql
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5500901_sys_gh1037-api_tootip_ui_elements_ddl.sql

https://github.com/metasfresh/metasfresh-webui-api/issues/1037

#1037-api - Advanced tooltip support

---

de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_BPartner.java
de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5501080_sys_gh4557_RenameMemoFieldsInI_BPartner.sql
de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerContactImportHelper.java
de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerImportHelper.java

#4557 Improve BPartner Memo-Import

#4557 Rename fields and add one more

---

de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5501110_sys_gh4568-app_C_Invoice_candidate_add_Note.sql

#4568-app Add note field to invoice candidates 

---

de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Average_Product_Prices.sql

https://github.com/metasfresh/metasfresh/issues/4188

Adjustment of SQL Function #4188

---

de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/CompositeInterfaceWrapperHelper.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/GridTabInterfaceWrapperHelper.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/IInterfaceWrapperHelper.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/POInterfaceWrapperHelper.java
de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java

#4572 Texts missing in cloned sales quotation

#4572 Texts missing in cloned sales quotation 

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5501530_sys_gh4594-outbound-email-server-webui.sql

New Window in WebUI for WebUI: Outbound EMail Server (SMTP). 2-Column Layout, Sidelist, Grid View and Translations for en_US added.
https://github.com/metasfresh/metasfresh/issues/4594

#4594 WebUI: Outbound EMail Server (SMTP)

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5501510_sys_gh4595-email-server-routing-webui.sql

New Window for eMail Routing in WebUI. Adds 2-Column Layout, Grid View, Sidelist and Translations for en_US.
https://github.com/metasfresh/metasfresh/issues/4595

#4595 WebUI: Window EMail Server Routing

---

de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5501720_sys_gh4605-hide-ad-org-from-org-window.sql

https://github.com/metasfresh/metasfresh/issues/4605

Removes ad_org from org-window in webui #4605
