metasfresh/metasfresh

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5713920_sys_gh16964_Warehouse_Search_Field.sql
refs: https://github.com/metasfresh/metasfresh/issues/16964
> Warehouse in Shipment Disposition as search field

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5713920_sys_gh16964_Warehouse_Search_Field.sql
* Warehouse in Shipment Disposition as search field refs: https://github.com/metasfresh/metasfresh/issues/16964
> Warehouse in Shipment Disposition as search field (#16965)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5713750_sys_gh16954_IsCompletelyDeliveredORInvoiced.sql
https://github.com/metasfresh/metasfresh/issues/16954
> Add new column `Fully delivered or invoiced` in `C_Order`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_footer.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_hu.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_sum.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_esr.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_page_header.jrxml
https://github.com/metasfresh/metasfresh/issues/16995
> Update the font in jasper report to Arial

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java
- remove IInvoiceCandBL.setAsyncBatch
- QA/cleanup, preparing the ground for changes
- attempt to fix the deadlock
> fix RecreateInvoiceWorkpackageProcessor DB deadlock

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridWindowVO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupFactory.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ui/ProcessParameterPanelModel.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/IADWindowDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JsonWindowsHealthResponse.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/exceptions/DocumentLayoutBuildException.java
- IADWindowDAO.retrieveAllActiveAdWindowIds
- cleanup
- cleanup
- GridWindowVO->GridFieldVO: small improvements to error reporting
- LayoutFactory: small improvements to error reporting
- /rest/api/window/health endpoint
> /rest/api/window/health endpoint

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/board/BoardRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/geo_location/ViewGeoLocationsRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/menu/MenuTreeRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IViewsRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewHealthRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewsRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JsonWindowsHealthResponse.java
- IViewsRepository.getViewLayout introduce permissions as param
- /rest/api/view/health
> /rest/api/view/health webui endpoint

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/impl/PlainMsgBL.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/compiere/util/TimeUtilTest.java
- backend/de.metas.business/src/main/java/org/eevolution/api/IProductBOMDAO.java
- backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
- backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMService.java
- backend/de.metas.business/src/test/java/org/eevolution/api/impl/ProductBOMServiceTest.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_BOM.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714220_sys_gh17000_Prevent_BOM_Versions_Overlapping_MSG.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714350_sys_gh17004_IsVoided_PP_Order.sql
> Prevent BOM Versions Overlapping

- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714570_sys_gh17000_Product_BOM_ValidTo_VAL_Rule.sql
> Adding new VAL rule to PP_Product_BOM_ID od the PP_Order

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
> Merge to release from origin/release_5.175

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
> Merge to hard_encoded_uat from origin/hard_encoded_hotfix

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
> Merge to yoyo_uat from origin/yoyo_hotfix

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/ColumnSqlCacheInvalidateRequestFactories.java
> Merge to intensive_care_uat from origin/intensive_care_hotfix

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
> Merge to secondary_opinion_uat from origin/secondary_opinion_hotfix

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
> Merge to tasty_ham_uat from origin/tasty_ham_hotfix

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
> Merge to mad_orange_uat from origin/mad_orange_hotfix

- frontend/src/__tests__/components/table/TableFilter.test.js
- frontend/src/actions/Actions.js
- frontend/src/components/SectionGroup.js
- frontend/src/components/table/TableFilter.js
- frontend/src/components/widget/ActionButton.js
- frontend/src/constants/actions/Actions.js
- frontend/src/containers/MasterWindow.js
- frontend/src/reducers/tables.js
- frontend/src/reducers/windowHandler.js
- TableFilter.js: copy changes from master
- TableFilter.js: refactor/cleanup/fixes
- TableFilter.js: convert to functional component; fixes
- TableFilter.js: fix fullscreen toggle button
- minor
- refresh top actions on tab refresh
- performance improvements/fixes
- store top actions per tabId; QA/refactor
- useSelectedRowIds: use shallowEqual
- ActionButton.js: don't call fetchTopActions from here because we are refreshing the actions when the tab is refreshed; jsdoc
> Fetch included tab top actions on tab refresh

- backend/de.metas.manufacturing/src/main/sql/postgresql/ddl/functions/PP_Product_BOM_Recursive.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/ddl/functions/PP_Product_BOM_Recursive_Report.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714830_sys_gh17066_pp_product_bom_recursive_and_pp_product_bom_recursive_report_f.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714840_sys_gh17066_add_referencedate_parameter_to_pp_product_bom_recursive_report_process.sql
refs: https://github.com/metasfresh/metasfresh/issues/17066
thx to @arljba
> Port the fix for PP_Product_Bom_Recursive to release

- backend/de.metas.manufacturing/src/main/sql/postgresql/ddl/functions/PP_Product_BOM_Recursive_Report.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714830_sys_gh17066_pp_product_bom_recursive_and_pp_product_bom_recursive_report_f.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5714840_sys_gh17066_add_referencedate_parameter_to_pp_product_bom_recursive_report_process.sql
* Port the fix for PP_Product_Bom_Recursive to release refs: https://github.com/metasfresh/metasfresh/issues/17066
* format code for comparability
* format code for comparability
* Fix PP_Product_Bom_Recursive refs: https://github.com/metasfresh/metasfresh/issues/17066
---------
> Port the fix for PP_Product_Bom_Recursive to release (#17067)

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/shipmentschedule/process/M_ShipmentSchedule_EnqueueSelection.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5714960_sy_gh17088_M_ShipmentSchedule_EnqueueSelection_ShipmentDate.sql
refs: https://github.com/metasfresh/metasfresh/issues/17088
> Bewegungsdatum shall be current date in shipment (#17089)

- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/ManufacturingOrderQuery.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PPOrderChangedEventFactory.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/order/PP_Order.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/order/PP_Product_BOM.java
refs: https://github.com/metasfresh/metasfresh/issues/17096
> Error when deleting production orders or changing products in po

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5714655_sys_gh17013_delete_QtySupplu_QtyDemand_V.sql
refs: https://github.com/metasfresh/metasfresh/issues/17013
> remove QtyDemand_QtySupply_V from AD_Table

- backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5715160_sys_idx_C_Queue_Workpackage_C_Queue_PackageProcessor_ID.sql
> Merge to master from origin/hard_encoded_uat

- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
(cherry picked from commit 4f9b2c55d6280ca1234870b973a684ff3eaa0c81)
> fix bug with inactive bpartner location

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_L.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_S.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist_todate/report.jrxml
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/ddl/functions/hu_label.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5715280_sys_gh17131_hu_label.sql
https://github.com/metasfresh/metasfresh/issues/17131
> hu_label: optionally return more attributes

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributesKeys.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributesBL.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/AbstractAttributeStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/HUAttributeStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/strategy/impl/CopyHUAttributeTransferStrategy.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQtyService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/HuForInventoryLineFactory.java
- frontend/src/__tests__/components/widget/Attributes/Attributes.test.js
- frontend/src/assets/css/attributes.scss
- frontend/src/components/widget/Attributes/Attributes.js
- frontend/src/components/widget/Attributes/AttributesDropdown.js
- frontend/src/utils/settings.js
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/toast.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
refs: https://github.com/metasfresh/metasfresh/issues/17094
> MobileUI - Change CU Qty of a TU - Fix losing attributes

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5715350_sys_gh17136_Missing_Translation_Role_Window.sql
https://github.com/metasfresh/metasfresh/issues/17136
> Set the missing translations in `Role` window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5715350_sys_gh17136_Missing_Translation_Role_Window.sql
https://github.com/metasfresh/metasfresh/issues/17136
> merging `inner_silence_uat`

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5715575_sys_gh17145_fix_atribute_type.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/containers/HUManagerScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/i18n/de.json
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/i18n/en.json
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
refs: https://github.com/metasfresh/metasfresh/issues/17145
> fix attr type & error message trl

- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
refs: https://github.com/metasfresh/metasfresh/issues/17145
> fix formatting

- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/containers/HUPrintingOptionsScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/buttons.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/components/buttons/ButtonWithIndicator.jsx
refs: https://github.com/metasfresh/metasfresh/issues/17145
> fix for printing options with long descriptions

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/weightable/Weightables.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQtyService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/HuForInventoryLineFactory.java
refs: https://github.com/metasfresh/metasfresh/issues/17094
> fix weight calculation on inventory complete

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_CreateReceipt_MovementDateParam.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5715780_sys_gh17176_CreateReceipt_MovementDateParam.sql
refs: https://github.com/metasfresh/metasfresh/issues/17176
> Allow date in the past for Material Receipt

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_CreateReceipt_MovementDateParam.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5715780_sys_gh17176_CreateReceipt_MovementDateParam.sql
* Allow date in the past for Material Receipt refs: https://github.com/metasfresh/metasfresh/issues/17176
> Allow date in the past for Material Receipt (#17178)

- backend/de.metas.business/src/main/java/de/metas/letters/model/MADBoilerPlate.java
- backend/de.metas.business/src/main/java/de/metas/letters/model/MADBoilerPlateRef.java
* handle missing boiler plate reference refs: https://github.com/metasfresh/metasfresh/issues/17183\
> Handle missing boiler plate reference (#17184)

- backend/de.metas.business/src/main/java/de/metas/material/maturing/MaturingConfigLine.java
- backend/de.metas.business/src/main/java/de/metas/material/maturing/MaturingConfigMap.java
- backend/de.metas.business/src/main/java/de/metas/material/maturing/MaturingConfigRepository.java
- backend/de.metas.business/src/main/java/de/metas/material/planning/IProductPlanningDAO.java
- backend/de.metas.business/src/main/java/de/metas/material/planning/impl/ProductPlanningDAO.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IHUPPOrderBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/async/HUMaturingWorkpackageProcessor.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/interceptor/PP_Order.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/storage/IHUStorageFactory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/storage/impl/DefaultHUStorageFactory.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/async/EnqueuePPOrderCandidateRequest.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/async/GeneratePPOrderFromPPOrderCandidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/async/PPOrderCandidateEnqueuer.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/model/dao/PPOrderCandidateDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/model/interceptor/PP_Order_Candidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_AlreadyMaturedForOrdering.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_EnqueuePastForOrdering.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_EnqueueSelectionForOrdering.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/PPOrderCandidateProcessRequest.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/PPOrderCandidateService.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/produce/PPOrderProducerFromCandidate.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5716000_sys_gh17194_PP_Order_Maturing.sql
refs: https://github.com/metasfresh/metasfresh/issues/17194
> Product Maturing - 4 - Maturing order process

- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_AlreadyMaturedForOrdering.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/process/PP_Order_Candidate_EnqueueSelectionForOrdering.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5716040_sys_gh17194_Update_Maturing_Scheduler.sql
https://github.com/metasfresh/metasfresh/issues/17194
> fix scheduler

- backend/de.metas.business/src/test/java/org/eevolution/api/impl/ProductBOMDescriptionBuilderTest.java
https://github.com/metasfresh/metasfresh/issues/17205
> Only consider `CO` BOMs fix

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/picking/model/I_PickingProfile_Filter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/picking/model/X_PickingProfile_Filter.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5716240_sys_gh17214_fine_tuning_2.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobReference.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfile.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfileRepository.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/PickingFilter.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/DisplayValueProvider.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingJobFacetsUtils.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingWorkflowLaunchersProvider.java
- misc/services/mobile-webui/mobile-webui-frontend/src/actions/LauncherActions.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersFilters.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/stringUtils.js
refs: https://github.com/metasfresh/metasfresh/issues/17214
> Mobile UI: Picking configs - fine tuning

- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCandEnqueueForSalesOrderCreation.java
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5716270_sys_gh17219_NoValidRecordSelected_Msg.sql
https://github.com/metasfresh/metasfresh/issues/17219
> Make sure only active Sales Order Candidates are processed

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5714680_sys_Add_Next_3_Years.sql
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCandEnqueueForSalesOrderCreation.java
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5716270_sys_gh17219_NoValidRecordSelected_Msg.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/picking/pickingslot/PickingHURowsRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataLoader.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataSupplier.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
https://github.com/metasfresh/metasfresh/issues/17219
> merging `soft_panda_hotfix` -> `uat`

- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingJobFacetsUtils.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersFacet.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersFacetGroup.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/facets/WorkflowLaunchersFacet.java
- backend/de.metas.workflow.rest-api/src/test/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersFacetGroupTest.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersFilters.jsx
- fix typo
- Sort delivery days by date and not by caption
> mobile UI: Sort delivery days facets by date and not by caption

- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/huQRCodes.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
refs: https://github.com/metasfresh/metasfresh/issues/17214
> make sure the catch UOM matches

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeParser.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeTest.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfileRepository.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingJobFacetsUtils.java
- backend/de.metas.picking.rest-api/src/test/resources/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.snap
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersFacet.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersFacetGroup.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/facets/WorkflowLaunchersFacet.java
- backend/de.metas.workflow.rest-api/src/test/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersFacetGroupTest.java
- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/huQRCodes.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersFilters.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/huQRCodes.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17233
*  https://github.com/metasfresh/metasfresh/pull/17225
*  https://github.com/metasfresh/metasfresh/pull/17223
> Merge intensive_care_uat -> master

- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCandEnqueueForSalesOrderCreation.java
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5716270_sys_gh17219_NoValidRecordSelected_Msg.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
https://github.com/metasfresh/metasfresh/issues/17219
> merging `soft_panda_hotfix`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_badge.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/security/AuthBadge_2cm.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5716340_sys_gh17242_New_Authentication_Badge_Report.sql
- backend/de.metas.global_qrcode.services/src/main/java/de/metas/global_qrcodes/service/GlobalQRCodeService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/security/process/AuthTokenPrintQrCode.java
https://github.com/metasfresh/metasfresh/issues/17242
> New QR Code authentication badge report

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
refs: https://github.com/metasfresh/metasfresh/issues/17214
> include not locked picking jobs when fetch drafted

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSet.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
> Merge to soft_panda_uat from origin/soft_panda_hotfix

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSet.java
> Merge to master from origin/soft_panda_uat

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5716150_sys_gh17214_fine_tunning.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5716245_sys_gh17214_fix_translation.sql
refs: https://github.com/metasfresh/metasfresh/issues/17214
> fix translations

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/execution/approval/strategy/check_superior_strategy/AllMatchingSupervisorsStrategy.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workflow/execution/approval/WFActivityApprovalCommandTest.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workflow/execution/approval/strategy/DocApprovalStrategyServiceTest.java
…m acceptance test
refs: https://github.com/metasfresh/metasfresh/issues/17285
> Implementation: Purchase Request (M_Requisition) Workflow

- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepScreen.jsx
AIM: solve:
* AC2. Pick Qty from header shall be updated after Unpick
* AC7. No white screen when unpicking
> PickingStepScreen: go back on unpick (AC2, AC7)

- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestProduct.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestProductUpsert.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestProductUpsertItem.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/attachment/JsonAttachment.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/attachment/JsonAttachmentRequest.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/attachment/JsonExternalReferenceTarget.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/bom/JsonBOMCreateRequest.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/bom/JsonCreateBOMLine.java
> Merge to master from origin/koala_yawn_uat

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/execution/approval/strategy/check_superior_strategy/AllMatchingSupervisorsStrategy.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workflow/execution/approval/WFActivityApprovalCommandTest.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workflow/execution/approval/strategy/DocApprovalStrategyServiceTest.java
* Implementation: Purchase Request (M_Requisition) Workflow: errors from acceptance test
refs: https://github.com/metasfresh/metasfresh/issues/17285
> Implementation: Purchase Request (M_Requisition) Workflow (#17286)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJob.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobHeader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/RenderedAddressProvider.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/DefaultPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/repository/MockedPickingJobLoaderSupportingServices.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfile.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/DisplayValueProvider.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/DisplayValueProviderService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingWorkflowLaunchersProvider.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.java
- improve overall picking job launchers loading
- improve picking launchers caption computing
> Improve mobile UI picking launchers and facets loading

- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
refs https://github.com/metasfresh/metasfresh/issues/17186
> Enter CatchWeight from QR improvements

- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/DisplayValueProvider.java
bug introduced by
* https://github.com/metasfresh/metasfresh/pull/17298
> mobile UI: Fix NPE when fetching picking launchers

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5716780_picking_CreateShipmentPolicy_CREATE_COMPLETE_CLOSE.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/CreateShipmentPolicy.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCompleteCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/GenerateShipmentsForSchedulesRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/GenerateShipmentsRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleEnqueuer.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java
- ShipmentService: cleanup/prepare code for changes
- Mobile UI Picking Profile - Create Shipment Policy - Create, Complete and Close dispo option
> Mobile UI Picking Profile - Create Shipment Policy - Create, Complete and Close dispo option 

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/MoveHUCommand.java
https://github.com/metasfresh/metasfresh/issues/17310
> update weight to zero when reactivating a destroyed HU

- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/hu.js
follow-up of
* https://github.com/metasfresh/metasfresh/pull/17341
> mobile UI: Use the Best Before Date & LotNo from HU QR Code if possible

- misc/services/mobile-webui/mobile-webui-frontend/src/apps/workplaceManager/i18n/de.json
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/workplaceManager/i18n/en.json
fixes
* https://github.com/metasfresh/metasfresh/pull/17352
> mobile UI: Scan Anything - fix trls

- backend/de.metas.business/src/main/java/de/metas/invoice/callout/C_Invoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_OverrideDueDate.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5717590_sys_gh17393_Invoice_DueDate.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/49-de.metas.invoice/5717480_sys_gh17393_Invoice_Display_DueDate.sql
refs: https://github.com/metasfresh/metasfresh/issues/17393
> Display due date in sales invoice window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5717690_sys_gh17426_GL_Journal_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/17426
> Update `GL Journal` window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5717690_sys_gh17426_GL_Journal_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/17426
> mergin `soft_panda_hotfix`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5717690_sys_gh17426_GL_Journal_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/17426
> merging `soft_panda_uat`

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
> merging `hard_encoded_uat`

- backend/de.metas.acct.base/src/main/java/de/metas/acct/process/ExportAccountInfos.java
- backend/de.metas.acct.base/src/main/java/de/metas/elementvalue/ElementValueService.java
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/AccountSheet_Report.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5717860_sys_Add_AccountSheet_Report_function.sql
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IAccountDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IFactAcctDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AccountDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/FactAcctDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/spreadsheet/excel/AbstractExcelExporter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/spreadsheet/excel/JdbcExcelExporter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ReportResultData.java
- backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/acct/AcctViewer.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5717830_sys_Add_Account_info_all_process.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5717840_AddMissingElements.sql
- backend/de.metas.util/src/main/java/de/metas/util/FileUtil.java
* POC- export all accounts
* Fix imports
* Clean imports
* Add process and format file names
* Filter all accounts
* Add report.AccountSheet_Report
* Move logic to elementvalue repo and service
* Move method to retrieveAccountsForTimeFrame to FacctAcctDAO
* Return direclty the list
* Rename variable to be more approiate: fileNamePrefix
* Refactor code to make it prettier
* Fix sql
* Add zone when getting LocalDate
* Merge branch 'mad_orange_uat' into mad_orange_uat_ExortAllAccounts
* Add elements and add general trls for report.AccountSheet_Report
* Fix script
(cherry picked from commit 17f25c32dfe7f2e6e213e2faf8428f2841dbaa5f)
backend/de.metas.acct.base/src/main/java/de/metas/elementvalue/ElementValueRepository.java …
> Export all accounts (#17430)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Document_Action_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Form_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Task_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Window_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Workflow_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Document_Action_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Form_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Task_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Window_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Workflow_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/interceptor/C_DocType.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712650_drop_AD_Document_Action_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712680_drop_AD_Window_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712690_drop_AD_Form_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712710_drop_AD_Process_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712740_drop_AD_Task_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712770_drop_AD_Workflow_Access_ID.sql
#16878
* drop AD_Document_Action_Access_ID
* drop AD_Window_Access_ID
* drop AD_From_Access_ID
* drop AD_Process_Access_ID
* drop AD_Task_Access_ID
* drop AD_Workflow_Access_ID
> Drop single primary key column on some of the AD_*Access tables

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Document_Action_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Form_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Task_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Window_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Workflow_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Document_Action_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Form_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Task_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Window_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Workflow_Access.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/interceptor/C_DocType.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712650_drop_AD_Document_Action_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712680_drop_AD_Window_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712690_drop_AD_Form_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712710_drop_AD_Process_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712740_drop_AD_Task_Access_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5712770_drop_AD_Workflow_Access_ID.sql
> Merging `release_5.175` -> `release`

- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/qtyInfos.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/QtyInputField.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qtyInfos.js
- QtyInputField.jsx: hotfix - always call useEffect outside of "if"
- QtyInputField.jsx: minor improvement for readability
- QtyInputField.jsx: while typing preserve trailing zero decimals (e.g. 0.00000)
> mobile UI - number input: while typing preserve trailing zero decimals (e.g. 0.00000)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/TranslatableStrings.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionWorkflowLaunchersProvider.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingWorkflowLaunchersProvider.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/DisplayValueProvider.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingWorkflowLaunchersProvider.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWorkflowLaunchersList.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WorkflowLauncher.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WorkflowLauncherCaption.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WorkflowLaunchersList.java
- TranslatableStrings.quantity
- introduce WorkflowLauncherCaption to better delay and control how we order the captions
> Improve how we order mobile UI launchers

- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionMobileApplication.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/activity_handlers/CompleteDistributionWFActivityHandler.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/activity_handlers/MoveWFActivityHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJob.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobProgress.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobSlotService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingMobileApplication.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingRestService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/callExternalSystem/CallExternalSystemActivityHandler.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/confirmation/ConfirmationActivityHandler.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/generateHUQRCodes/GenerateHUQRCodesActivityHandler.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/issue/RawMaterialsIssueActivityHandler.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/receive/MaterialReceiptActivityHandler.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/scanScaleDevice/ScanScaleDeviceActivityHandler.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/CompletePickingWFActivityHandler.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/PickingWFActivityHelper.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/SetPickingSlotWFActivityHandler.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.java
- backend/de.metas.picking.rest-api/src/test/resources/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.snap
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/activity_features/user_confirmation/UserConfirmationRequest.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWFProcess.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WFProcess.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WFProcessStatus.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfProcessScreen/WFProcessScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/utils.js
- remove WFProcess.caption because it's not used
- minor
- WFProcess.isAllowAbort
- remove WFProcess.mapDocument; cleanup
> mobile UI: show Abort button if nothing picked, even if picking slot is selected

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaymentRequestBL.java
If the invoice has a payment-request (coming from the creditor), then we shall still subtract the payment-discount that is implied in our C_PaymentTerms
(cherry picked from commit 540e6f367e15cea0c4be96186fede42b7fc4d126)
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaymentRequestBL.java
> Fix paySelectionLine's payamount in case of payment-discount (#17451)

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/MaterialCockpitFilters.java
refs: https://github.com/metasfresh/metasfresh/issues/17521
> Order MD_Cockpit by QtyStockEstimateSeqNo_AtDate

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/MaterialCockpitFilters.java
* order MD_Cockpit by QtyStockEstimateSeqNo_AtDate refs: https://github.com/metasfresh/metasfresh/issues/17521
> Order MD_Cockpit by QtyStockEstimateSeqNo_AtDate (#17522)

- frontend/src/assets/css/inputs.css
- frontend/src/components/widget/CostPrice.js
- **webui: improve readability of disabled fields by making text color more black**
- **CostPrice.js: use disabled prop**
> webui: improve readability of disabled fields by making text color more darker

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ManufacturingJobFacetGroup.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ManufacturingJobFacets.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobDefaultFilterCollection.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaverSupportingServices.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobReferenceQuery.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingMobileApplication.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingRestService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingWorkflowLaunchersProvider.java
- backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/manufacturing/job/service/ManufacturingJobServiceTest.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/IResourceDAO.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/ResourceType.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/impl/ResourceDAO.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/validator/PP_Order_CopyTemplateCustomizer.java
- backend/de.metas.util/src/main/java/de/metas/util/InSetPredicate.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/facets/WorkflowLaunchersFacet.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/facets/WorkflowLaunchersFacetGroup.java
- **InSetPredicate.intersectWith**
- **mobile UI manufacturing: resource type facets**
- **hotfix PP_Order_CopyTemplateCustomizer**
- **cleanup**
> mobile UI manufacturing: resource type facets

- backend/de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5665370_sys_gh13968_include_inactive_HUs_in_MD_stock.sql
which might happen depending on custom views
> Fix rollout-SQL error

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
- backend/de.metas.acct.base/src/test/java/de/metas/acct/PostDocumentNow_ManualTest.java
- **Doc_AllocationHdr: fix posting in case of Credit Memo invoices and WriteOff**
- **PostDocumentNow_ManualTest: re-post multiple docs**
> intensive care hotfix fixAllocPosting creditMemoWriteOff

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621041_sys_gh12296_C_BPartner_ChangeColumnLegths.sql
- backend/de.metas.async/src/main/sql/postgresql/system/80-async-dlm/5624381_sys_gh12591_migrate_c_queue_package_processor_ID.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- misc/dev-support/docker/infrastructure/env-files/yoyo_uat.env
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/excelimport/Excel_OLCand_Row.java
- misc/services/camel/de-metas-camel-externalsystems/alberta/alberta-article-api/pom.xml
> Merge to master from origin/yoyo_uat

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
> Merge to master from origin/science_vessel_uat

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621041_sys_gh12296_C_BPartner_ChangeColumnLegths.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5718540_sys_ShowDefaultContactFieldsAndUpdateTrl.sql
- backend/de.metas.async/src/main/sql/postgresql/system/80-async-dlm/5624381_sys_gh12591_migrate_c_queue_package_processor_ID.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- misc/dev-support/docker/infrastructure/env-files/pink_rooster_uat.env
- misc/dev-support/docker/infrastructure/env-files/yoyo_uat.env
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/excelimport/Excel_OLCand_Row.java
- misc/services/camel/de-metas-camel-externalsystems/alberta/alberta-article-api/pom.xml
> Merge to master from origin/pink_rooster_uat

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/housekeeping/HouseKeepingService.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5718830_sys_gh17549_SkipHouseKeeping_SysConfig.sql
https://github.com/metasfresh/metasfresh/issues/17549
> Reverting the `SkipHouseKeeping` SysConfig name

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/housekeeping/HouseKeepingService.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5718830_sys_gh17549_SkipHouseKeeping_SysConfig.sql
https://github.com/metasfresh/metasfresh/issues/17549
> merging `intensive_care_hotfix`

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/housekeeping/HouseKeepingService.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5718900_PP_Order_Candidate_SetWorkstation_fix_trl.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5718830_sys_gh17549_SkipHouseKeeping_SysConfig.sql
https://github.com/metasfresh/metasfresh/issues/17549
> Merging `intensive_care_uat`

- frontend/src/components/widget/WidgetRenderer.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17558
*  https://github.com/metasfresh/metasfresh/pull/17529
*  https://github.com/metasfresh/metasfresh/pull/17375
*  https://github.com/metasfresh/metasfresh/pull/17374
*  https://github.com/metasfresh/metasfresh/pull/17372
> Merge pink_rooster_uat -> master

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobReferenceQuery.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingMobileApplication.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingWorkflowLaunchersProvider.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/ManufacturingOrderQuery.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
fixes / add lost parts of
* https://github.com/metasfresh/metasfresh/pull/17548
> mobile UI - manufacturing - filter by current workstation

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/SyncInventoryQtyToHUsCommand.java
If qty book is negative and qty count is zero, that means that we do not need to create any HU or to distribute any quantity
> Do not do anything if there is not HU needed to be created

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719010_C_Order_AddDiscountCompensationLine_refreshAllAfterExecution.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719030_C_OrderLine_ManualCompensationLinePosition.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719040_sysconfig_ManualCompensationLinePosition.sql
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/Group.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLine.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLineCreateRequest.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCreator.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/ManualCompensationLinePosition.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupCompensationUtils.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
- backend/de.metas.business/src/main/java/de/metas/order/process/C_Order_AddDiscountCompensationLine.java
- **Introduce ManualCompensationLinePosition**
- **C_Order_AddDiscountCompensationLine: RefreshAllAfterExecution='Y'**
> C_Order_AddDiscountCompensationLine: add manual compensation lines before all generated compensation lines (configurable via sysconfig)

- frontend/src/__tests__/utils/dateHelpers.test.js
- frontend/src/components/widget/DateTime/DatePicker.js
- frontend/src/components/widget/DateTime/TetheredDateTime.js
- frontend/src/components/widget/WidgetRenderer.js
- frontend/src/utils/dateHelpers.js
https://github.com/metasfresh/metasfresh/issues/17581
> webui: Port Date/Time widget fixes from master (#17558)

- frontend/src/components/widget/WidgetRenderer.js
fixes
* https://github.com/metasfresh/metasfresh/pull/17558
> Revert code that mas mistakenly merged/introduced by https://github.com/metasfresh/metasfresh/pull/17558

- frontend/src/components/widget/WidgetRenderer.js
fixes
* https://github.com/metasfresh/metasfresh/pull/17558
cherry-pick of
* https://github.com/metasfresh/metasfresh/pull/17590
> Revert code that mas mistakenly merged/introduced by https://github.com/metasfresh/metasfresh/pull/17558 (pink_rooster_uat)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/JUnitBeansMap.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/IHUPickingSlotBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingSlotConnectedComponent.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingSlotService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/RemoveHUFromPickingSlotCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/impl/HUPickingSlotBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobSlotService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/process/ClearPickingSlot.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/process/PickingSlot_ChangeIsDynamic.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/requests/ReleasePickingSlotRequest.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719120_sys_gh17594_ClearPickingSlot.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUPickingSlotTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/PickingJobSlotServiceTest.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/IPickingSlotBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/IPickingSlotDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/Packageable.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/impl/PickingSlotBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/impl/PickingSlotDAO.java
refs: https://github.com/metasfresh/metasfresh/issues/17594
> Picking slots are blocked

- backend/de.metas.business/src/main/java/de/metas/order/IOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupCompensationChangesHandler.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
- backend/de.metas.business/src/main/java/de/metas/order/process/C_Order_CreateCompensationGroup.java
- **IOrderDAO.retrieveOrderLinesByOrderIds(Set<OrderId> orderIds, Class<T> type)**
- **collect all orderIds for whom we need order line reordering and do it once at the end**
> secondary opinion uat groupRenumberingFixes

- backend/de.metas.business/src/main/java/de/metas/order/IOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupCompensationChangesHandler.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
- backend/de.metas.business/src/main/java/de/metas/order/process/C_Order_CreateCompensationGroup.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17613
*  https://github.com/metasfresh/metasfresh/pull/17544
*  https://github.com/metasfresh/metasfresh/pull/17348
*  https://github.com/metasfresh/metasfresh/pull/17054
*  https://github.com/metasfresh/metasfresh/pull/16677
*  https://github.com/metasfresh/metasfresh/pull/16415
*  https://github.com/metasfresh/metasfresh/pull/14752
*  https://github.com/metasfresh/metasfresh/pull/14333
> Merge secondary_opinion_uat -> master

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Util.java
- backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_Picking_Job_Line.java
- backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_Picking_Job_Line.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobLine.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobLineId.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719240_M_Picking_Job_Line.IsManuallyClosed.sql
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/repository/PickingJobRepositoryTest.snap
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/service/PickingJobService_UsingTUs_Test.snap
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/PickingRestController.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobLine.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingLineCloseRequest.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingLineOpenRequest.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingJobRestService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.picking.rest-api/src/test/resources/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.snap
- misc/services/mobile-webui/mobile-webui-frontend/src/api/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickAlternatives.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepButton.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/picking.js
- **rename functions to make them more specific and make room for others**
- **mobile UI - picking line - show QtyToPick and QtyPicked**
> mobile UI - picking line - show QtyToPick and QtyPicked; Manually close/open a picking job line

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5719270_sys_gh17619_DocumentFieldReadonlyException_Error_Msg.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/exceptions/DocumentFieldReadonlyException.java
https://github.com/metasfresh/metasfresh/issues/17619
> Adding `DocumentFieldReadonlyException` error message

- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickConfig.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickProductsActivity.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickProductsScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfProcessScreen/WFProcessScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/hooks/useSearchParams.js
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/routes/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/picking.js
- **handle scanning HU for any picking line**
- **when scanning the qrcode, just find out what's the matching line and forward to line scanner of that line**
> mobile UI - Picking Job - scan any HU

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/GLNLoadingCache.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/CreateWarehouseRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/Warehouse.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/warehouse/DeprecatedWarehouseRestController.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/warehouse/WarehouseRestController.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/warehouse/WarehouseRestService.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/SwaggerDocConstants.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/warehouse/JsonRequestWarehouse.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/warehouse/JsonRequestWarehouseUpsert.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/warehouse/JsonRequestWarehouseUpsertItem.java
refs: https://github.com/metasfresh/metasfresh/issues/17614
> Warehouse upsert endpoint

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobLockService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719120_sys_gh17594_ClearPickingSlot.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719125_sys_gh17594_ClearPickingSlot_fix_typo.sql
refs https://github.com/metasfresh/metasfresh/issues/17594
> Picking slots are blocked - fix lockedBy NPE

- backend/de.metas.business/src/main/java/de/metas/project/budget/BudgetProjectQuery.java
- backend/de.metas.business/src/main/java/de/metas/project/budget/BudgetProjectRepository.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/interceptor/C_Project.java
- backend/de.metas.business/src/main/java/de/metas/project/workorder/project/BudgetParentLinkResolver.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5719540_sys_gh_add_BudgetParentExternalId_SysConfig.sql
refs: https://github.com/metasfresh/metasfresh/issues/17604
> Setting the parent project when transferring the test order

- .github/integrate
- .gitignore
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Issue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Issue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/AdIssueFactory.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/InsertRemoteIssueRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/IssueCategory.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/impl/ErrorManager.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/ADSystemInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/SystemBL.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5718140_AD_Issue_more_fields.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobLockService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719120_sys_gh17594_ClearPickingSlot.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719125_sys_gh17594_ClearPickingSlot_fix_typo.sql
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/WorkflowRestController.java
- misc/services/mobile-webui/mobile-webui-frontend/package.json
- misc/services/mobile-webui/mobile-webui-frontend/src/api/applications.js
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/error-screen.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/index.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ErrorScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/routes/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17659
*  https://github.com/metasfresh/metasfresh/pull/17657
*  https://github.com/metasfresh/metasfresh/pull/17656
*  https://github.com/metasfresh/metasfresh/pull/17653
*  https://github.com/metasfresh/metasfresh/pull/17652
*  https://github.com/metasfresh/metasfresh/pull/17650
*  https://github.com/metasfresh/metasfresh/pull/17616
*  https://github.com/metasfresh/metasfresh/pull/17595
*  https://github.com/metasfresh/metasfresh/pull/17495
> Merge intensive_care_hotfix -> intensive_care_uat

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719580_sys_gh17663_add_IsAlwaysSplitHUsEnabled.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/picking/MobileUIPickingUserProfile_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_QtyPicked_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/picking_alwaysSplitHUs.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/picking_validatePickedHU.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/plan/generator/CreatePickingPlanCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/plan/generator/pickFromHUs/PickFromHUsGetRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/plan/generator/pickFromHUs/PickFromHUsSupplier.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5719780_sys_gh17663_add_translations.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJobTestHelper.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/reservation/HUReservationRepositoryTests.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfile.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/config/MobileUIPickingUserProfileRepository.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
https://github.com/metasfresh/metasfresh/issues/17663
> Shipment is not created, already shipped HU assigned

- misc/services/mobile-webui/mobile-webui-frontend/src/actions/HeaderActions.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/picking/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickProductsActivity.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickProductsScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/scan/ScanActivity.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/scan/ScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/applicationRoot/ApplicationLayout.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfProcessScreen/WFProcessScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/applications.js
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/headers.js
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/routes/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/picking.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17669
*  https://github.com/metasfresh/metasfresh/pull/17660
> Merge intensive_care_uat -> master (2024-03-21)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHU.java
Respect packing instructions when picking via Mobile-UI
> Respect packing instructions when picking via Mobile-UI

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/shipping/ShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentServiceTestImpl.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/PackageableList.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScreen.jsx
- **PackageableList: keep items ordered by shipmentScheduleId which usually are created in same order as order lines**
- **make sure we are closing shipment schedules even if nothing was picked**
- **Picking Line: after pressing Close, go back to picking job**
- **minor QA**
> mobile UI picking: make sure we are closing shipment schedules even if nothing was picked

- misc/services/mobile-webui/mobile-webui-frontend/src/api/applications.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/picking.js
Fixes
* https://github.com/metasfresh/metasfresh/pull/17660
* https://github.com/metasfresh/metasfresh/pull/17495
> mobile UI picking flow fixes

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/shipping/ShipmentService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/JsonShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPIItemProductBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/AllocationRequestBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/AttributeSetAggregator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/HULoader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/LULoader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/LULoaderInstance.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/TULoader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/TULoaderInstance.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/TUProducerDestination.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCompleteCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentSchedulesCUsToTUsAggregator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentScheduleHUTrxListener.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/util/CatchWeightHelper.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5720150_sys_PackHUToCU_on_the_fly.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJobTestHelper.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingslotsClearing/process/WEBUI_PickingSlotsClearingView_TakeOutTUsAndAddToNewLUs.java
- **remove unused service**
- **HULoader.unloadAllFromSource convenient method**
- **TUProducerDestination: minor cleanup/QA**
- **aggregate picked CUs to LU/TU on pick complete**
> mobile UI: Aggregate picked CUs to LU/TU on pick complete

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/picking_alwaysSplitHUs.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/picking_validatePickedHU.feature
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17690
*  https://github.com/metasfresh/metasfresh/pull/17687
*  https://github.com/metasfresh/metasfresh/pull/17682
*  https://github.com/metasfresh/metasfresh/pull/17677
> Merge intensive_care_hotfix -> intensive_care_uat (2024-03-25)

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/shipping/ShipmentService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/JsonShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPIItemProductBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/AllocationRequestBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/AttributeSetAggregator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/HULoader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/LULoader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/LULoaderInstance.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/TULoader.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/TULoaderInstance.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/TUProducerDestination.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCompleteCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentSchedulesCUsToTUsAggregator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentScheduleHUTrxListener.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/util/CatchWeightHelper.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5720150_sys_PackHUToCU_on_the_fly.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingslotsClearing/process/WEBUI_PickingSlotsClearingView_TakeOutTUsAndAddToNewLUs.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17696
> Merge intensive_care_hotfix -> intensive_care_uat (2024-03-26)

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/ImportConstants.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/LocalFilePurchaseOrderSyncServiceRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/PurchaseOrderUpsertProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/model/PurchaseOrderRow.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilderTest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/0_JsonStartExternalSystemRequestPurchaseOrder_LocalFile.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/0_JsonStopExternalSystemRequestPurchaseOrder_LocalFile.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/10_PurchaseOrder_ImportFile.csv
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/20_CamelUpsertPurchaseOrderRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/30_CamelUpsertPurchaseOrderRequest.json
rfs: https://github.com/metasfresh/metasfresh/issues/17735
> import purchase orders

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/warehouse/WarehouseRestService.java
- backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5720450_sys_gh17740_S_ExternalReference.sql
- backend/de.metas.externalreference/src/main/java/de/metas/externalreference/rest/v2/ExternalReferenceRestControllerService.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/bpartner/BPartnerUpsertProcessor.java
https://github.com/metasfresh/metasfresh/issues/17614
> Fix orgBPartnerLocationId

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
https://github.com/metasfresh/metasfresh/issues/17614
> Get warehouse in trx fix

- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config_ProCareManagement_LocalFile.java
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5719900_sys_gh17680_Processed_And_Errored_Directory.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5719930_sys_gh17680_PCM_ExternalSystem.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5720460_sys_gh17680_ExternalSystem_Config_ProCareManagement_LocalFile.sql
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5720480_sys_gh17680_ProCareManagementLocalFile.sql
https://github.com/metasfresh/metasfresh/issues/17680
> Fix merge to master

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/HUQRCodeGenerateForExistingHUsResult.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/HUQRCodesService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaver.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaverSupportingServices.java
refs: https://github.com/metasfresh/metasfresh/issues/17685
> mobile-ui: Aggregated TUs with no QR can be issued

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/pom.xml
https://github.com/metasfresh/metasfresh/issues/17680
> Refactoring

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5720500_sys_gh17755_ProductPrices_PLV_SearchField.sql
refs: https://github.com/metasfresh/metasfresh/issues/17755
> Field Pricelist Version with alphabetical sorting and text search

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5692500_sys_gh15661_AttributesDropDown_Configurable_MaxHeight.sql
- frontend/src/__tests__/components/widget/Attributes/Attributes.test.js
- frontend/src/assets/css/attributes.scss
- frontend/src/components/widget/Attributes/Attributes.js
- frontend/src/components/widget/Attributes/AttributesDropdown.js
- frontend/src/utils/settings.js
- **fix attributes dropdown (#15651)**
- **copy utils/settings.js from master**
> webui: Fix attributes dropdown layout (soft_panda_uat)

- misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/PInstanceUtil.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/bpartner/GetBPartnerFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/GetProductFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/warehouse/GetWarehouseFromFileRouteBuilder.java
rfs: https://github.com/metasfresh/metasfresh/issues/17735
> fix error propagation for routes started on demand

- misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/PInstanceUtil.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/bpartner/GetBPartnerFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/GetProductFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/warehouse/GetWarehouseFromFileRouteBuilder.java
rfs: https://github.com/metasfresh/metasfresh/issues/17735
> fix error propagation for routes started on demand (#17769)

- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/containers/activities/picking/PickLineScanScreen.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/setupTests.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/audio.js
- **fix typo**
- **PickingLineScanScreen.test.js**
- **document why the key of ScanHUAndGetQtyComponent is so important**
- **make sure the initialization from qrCode url param is performed after the initialization from component params**
- **GetQuantityDialog.onDialogYes: display error if any**
> mobile UI picking - scan HU fixes

- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/containers/activities/picking/PickLineScanScreen.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/setupTests.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/audio.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17772
> Merge intensive_care_hotfix -> intensive_care_uat (2024-04-04)

- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/validator/PP_Order_CopyTemplateCustomizer.java
Basically, I've cherry-picked the fix from 
* PR https://github.com/metasfresh/metasfresh/pull/17530
*  commit https://github.com/metasfresh/metasfresh/pull/17530/commits/b476cc29ff99916d9ee7012276108baf81861cb9
> hotfix error when cloning a manufacturing order

- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/containers/activities/picking/PickLineScanScreen.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/setupTests.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/audio.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17776
*  https://github.com/metasfresh/metasfresh/pull/17775
*  https://github.com/metasfresh/metasfresh/pull/17773
*  https://github.com/metasfresh/metasfresh/pull/17772
> Merge intensive_care_uat -> master (2024-04-05)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5720990_sys_gh17779_fine_tunning.sql
https://github.com/metasfresh/metasfresh/issues/17779
> remove access for all roles except admin

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5721030_sys_gh17779_add_sqlcolumn_source_column.sql
https://github.com/metasfresh/metasfresh/issues/17779
> add sql source column

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5721030_sys_gh17779_add_trls.sql
https://github.com/metasfresh/metasfresh/issues/17779
> Feature Project Time Tracking: add trl

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/exp/RabbitMqExportProcessor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/imp/RabbitMqListener.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5720360_sys_cli_fix_and_cleanup_rpl_processors.sql
- misc/services/camel/de-metas-camel-edi/src/main/resources/application.properties
> Merge to master from 647473ca13402ad4d9c47a30922e0ad1f0beacf9

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5721034_sys_gh17779_add_createdBy_toGridView.sql
https://github.com/metasfresh/metasfresh/issues/17779
> Feature Project Time Tracking

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/PurchaseOrderUpsertProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/20_CamelUpsertPurchaseOrderRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/30_CamelUpsertPurchaseOrderRequest.json
https://github.com/metasfresh/metasfresh/issues/17801
> Pro Care Management - Fix process Create purchase orders to work

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/ExtractCounterAttributesCommand.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsRestController.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/LoadJsonHURequest.java
- backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/handlingunits/rest_api/ExtractCounterAttributesCommandTest.java
refs: https://github.com/metasfresh/metasfresh/issues/16944 (cherry picked from commit ae4daea525da8dbb447539582fb33a81fc9a8bb0)
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsRestController.java
> Dynamic output of Mac addresses in REST API (#16947)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Issue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Issue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/InsertRemoteIssueRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/impl/ErrorManager.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5721120_AD_Issue_improvements.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5721160_SetLargeLabelAsDefault.sql
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/WorkflowRestController.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JsonErrorItem.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/test/resources/de/metas/camel/externalsystems/core/to_mf/0_LogMessageRequest.json
- misc/services/mobile-webui/mobile-webui-frontend/src/api/applications.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17795
*  https://github.com/metasfresh/metasfresh/pull/17794
> Merge intensive_care_hotfix -> intensive_care_uat (2024-04-09)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Issue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Issue.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/InsertRemoteIssueRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/impl/ErrorManager.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5721120_AD_Issue_improvements.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5721160_SetLargeLabelAsDefault.sql
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/WorkflowRestController.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JsonErrorItem.java
- misc/services/camel/de-metas-camel-externalsystems/core/src/test/resources/de/metas/camel/externalsystems/core/to_mf/0_LogMessageRequest.json
- misc/services/mobile-webui/mobile-webui-frontend/package.json
- misc/services/mobile-webui/mobile-webui-frontend/src/api/applications.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17796
*  https://github.com/metasfresh/metasfresh/pull/17795
*  https://github.com/metasfresh/metasfresh/pull/17794
*  https://github.com/metasfresh/metasfresh/pull/17778
> Merge intensive_care_uat -> master (2024-04-10)

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/picking/PickingSlot_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/picking_abortPickingJobAfterShipment.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/interceptor/M_InOut.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
refs: https://github.com/metasfresh/metasfresh/issues/17813
> Not all picking slots are released

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/picking/PickingSlot_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/picking_abortPickingJobAfterShipment.feature
refs: https://github.com/metasfresh/metasfresh/issues/17813
> fix flakyness

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5721310_sys_skipPickedHU_Validation.sql
refs https://github.com/metasfresh/metasfresh/issues/17820
> MobileUI - HU cannot be picked: Revert

- misc/services/mobile-webui/mobile-webui-frontend/package.json
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17816
> Merge intensive_care_uat -> master (2024-04-11)

- backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5721510_M_ShipmentSchedule_Split_ID_trl.sql
- backend/de.metas.swat/de.metas.swat.webui/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5721520_SplitShipmentView_processes_trl.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRows.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentViewFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentView_ProcessTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentView_RemoveRows.java
- **trl**
- **hide Remove button for processed rows**
- **Protein and Hl are mandatory**
- **TaxDAO: improve exception message**
Follow-up of 
* https://github.com/metasfresh/metasfresh/pull/17807
> Split Shipment fixes & improvements

- backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5721510_M_ShipmentSchedule_Split_ID_trl.sql
- backend/de.metas.swat/de.metas.swat.webui/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5721520_SplitShipmentView_processes_trl.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRows.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentViewFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentView_ProcessTemplate.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentView_RemoveRows.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17839
> Merge inner_silence_uat -> master (2024-04-12)

- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/PP_Order_MaterialTracking_HandlerDAO.java
- frontend/src/assets/css/filtersitem.scss
- frontend/src/components/widget/MultiSelect.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17844
*  https://github.com/metasfresh/metasfresh/pull/17843
*  https://github.com/metasfresh/metasfresh/pull/17842
*  https://github.com/metasfresh/metasfresh/pull/17837
*  https://github.com/metasfresh/metasfresh/pull/15925
*  https://github.com/metasfresh/metasfresh/pull/15901
*  https://github.com/metasfresh/metasfresh/pull/15410
*  https://github.com/metasfresh/metasfresh/pull/15407
*  https://github.com/metasfresh/metasfresh/pull/14993
*  https://github.com/metasfresh/metasfresh/pull/14986
*  https://github.com/metasfresh/metasfresh/pull/14972
*  https://github.com/metasfresh/metasfresh/pull/14750
> Merge soft_panda_uat -> master (2024-04-12)

- backend/de.metas.adempiere.adempiere/base/pom.xml
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_R_Request.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_R_Request.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/pdf/Document.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Trace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ExecuteReportStrategyUtil.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MRequest.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/BPartnerBL.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Previous_Pricelist_Comparison_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5721390_sys_gh2819_Current_Vs_Previous_Pricelist_Comparison_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5721400_sys_gh2819_Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
- backend/de.metas.inbound.mail/src/main/java/de/metas/inbound/mail/request/RequestFromInboundEMailListener.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/spi/impl/ESRCreaLogixStringParser.java
- backend/de.metas.printing/de.metas.printing.base/pom.xml
- backend/de.metas.procurement.base/src/main/java/de/metas/procurement/base/order/impl/PMMPricingAware_C_OrderLine.java
- backend/de.metas.report/de.metas.report.jasper.client/pom.xml
- backend/de.metas.report/de.metas.report.jasper.commons/pom.xml
- backend/de.metas.report/metasfresh-report-service/pom.xml
- backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/misc/ParcelNumberGenerator.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/crm/interceptor/R_Request.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java
- misc/parent-pom/pom.xml
https://github.com/metasfresh/mf15/issues/2819
> Update Jasper to latest version `6.21.2`

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/DB.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/RecordChangeLog.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/RecordChangeLogLoader.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentChangeLog.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentChangeLogService.java
- frontend/src/components/ChangeLogModal.js
- **DB.forFirstRowIfAny**
- **RecordChangeLog: QA/refactor**
- **JSONDocumentChangeLog: QA/refactor**
- **/changeLog endpoint: send timestamps to frontend using ISO-8601 format and let the frontend to properly format it**
> webui Record Change Log - display timestamps using frontend locale/timezone

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/board/BoardRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/provider/standard/FacetFilterViewCache.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/provider/standard/FacetsFilterLookupDescriptor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingslotsClearing/PickingSlotsClearingView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/DefaultView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/template/AbstractCustomView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/LookupValuesPage.java
- frontend/src/components/widget/List/List.js
- frontend/src/components/widget/List/RawList.js
- frontend/src/components/widget/MultiSelect.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17849
> Merge soft_panda_uat -> master (2024-04-13)

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5721530_ModCntr_Log_fixes.sql
...using logic:
- modcntr_module.name
- m_product.name
- '-' (hardcoded, *should* not happen)
> default modcntr_log.productname

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/model/ProductRow.java
- change decimal point to comma (for DE) in article items
- change date format in purchase order items
> PCM - two more format-changes

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5721270_sys_M_AttributeValue_Value_RO.sql
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/interceptor/M_AttributeValue.java
https://github.com/metasfresh/metasfresh/issues/17864
> Prevent users from changing `M_AttributeValue.Value` of existing records.

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/CConnection.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobLine.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/DefaultPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeParser.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/repository/MockedPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeTest.java
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/repository/PickingJobRepositoryTest.snap
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/service/PickingJobService_UsingTUs_Test.snap
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobLine.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/rest_api/json/JsonPickingJobTest.java
- backend/de.metas.picking.rest-api/src/test/resources/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.snap
- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/reducers/wfProcesses/utils.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/qrCode/hu.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/hu.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
- **JsonPickingJobLine.productNo**
- **toastError: console print provided context if any**
- **introduce productNo to L&M QR Code**
- **JsonPickingJobLine.productNo**
- **assert L&M QR Code productNo is matching picking line productNo**
- **GetQuantityDialog: fix typo**
- **fix failing jest tests**
- **CConnection: in case the connection is down use current settings; in case of new connection populate the UI with our current standard values**
> L&M QR Code: introduce productNo

- docker-builds/Dockerfile.camel
- docker-builds/Dockerfile.camel.externalsystems
- docker-builds/Dockerfile.camel.junit
- misc/de-metas-common/de-metas-common-externalreference/pom.xml
- misc/de-metas-common/de-metas-common-externalsystem/pom.xml
- misc/services/camel/de-metas-camel-edi/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/alberta/alberta-article-api/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/alberta/alberta-patient-api/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/processor/AttachmentProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/common/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/core/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilderTest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/20_CamelUpsertPurchaseOrderRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/30_CamelUpsertPurchaseOrderRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-rabbitmq/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-woocommerce/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/dist/pom.xml
- misc/services/camel/de-metas-camel-externalsystems/pom.xml
- it was green locally, with the later camel-version green
- maybe we'll need to combine this with PR https://github.com/metasfresh/metasfresh/pull/17867
> fix camel-pcm unittest

- backend/de.metas.adempiere.adempiere/base/pom.xml
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/pdf/Document.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ExecuteReportStrategyUtil.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/BPartnerBL.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5721390_sys_gh2819_Current_Vs_Previous_Pricelist_Comparison_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5721400_sys_gh2819_Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/AddQtyToHUCommand.java
- backend/de.metas.payment.esr/src/main/java/de/metas/payment/spi/impl/ESRCreaLogixStringParser.java
- backend/de.metas.printing/de.metas.printing.base/pom.xml
- backend/de.metas.procurement.base/src/main/java/de/metas/procurement/base/order/impl/PMMPricingAware_C_OrderLine.java
- backend/de.metas.report/de.metas.report.jasper.client/pom.xml
- backend/de.metas.report/de.metas.report.jasper.commons/pom.xml
- backend/de.metas.report/metasfresh-report-service/pom.xml
- backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/misc/ParcelNumberGenerator.java
- misc/parent-pom/pom.xml
https://github.com/metasfresh/mf15/issues/2819
> Update Jasper to latest version 6.21.2

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/CConnection.java
- backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_v_view.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobLine.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/DefaultPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeParser.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/repository/MockedPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeTest.java
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/repository/PickingJobRepositoryTest.snap
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/service/PickingJobService_UsingTUs_Test.snap
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobLine.java
- backend/de.metas.picking.rest-api/src/test/java/de/metas/picking/rest_api/json/JsonPickingJobTest.java
- backend/de.metas.picking.rest-api/src/test/resources/de/metas/picking/workflow/handlers/PickingMobileApplicationTest.snap
- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/reducers/wfProcesses/utils.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/qrCode/hu.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/hu.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17883
*  https://github.com/metasfresh/metasfresh/pull/17882
*  https://github.com/metasfresh/metasfresh/pull/17858
> Merge intensive_care_uat -> master (2024-04-18)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/DateTimeTranslatableString.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/TranslatableStrings.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5722360_LotNo_fix_trl.sql
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsRestController.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/JsonHUQtyChangeRequest.java
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/containers/HUManagerScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/ChangeHUQtyDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/constants/HUAttributes.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/hu.js
- **fix LotNo trl**
- **mark `/byId/{M_HU_ID}/qty` as deprecated**
- **read best before date and lot no when creating a new HU**
- **fix TranslatableStrings**
- **DateTimeTranslatableString.ofDateTime(LocalDateTIme)**
- **JsonHU: nicely format dates**
> mobile UI: HU Manager: Change Qty - fixes & improvements

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5722410_GenerateHUQRCodes_trls.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5722420_GenerateHUQRCodes_trls_2.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17910
*  https://github.com/metasfresh/metasfresh/pull/17908
> Merge intensive_care_hotfix -> intensive_care_uat (2024-04-22)

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/JsonHUAttributeConverters.java
- misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/handlingunits/JsonHUAttribute.java
- misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/handlingunits/JsonHUAttributeCodeAndValues.java
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/components/HUInfoComponent.jsx
- **Introduced JsonHUAttribute.valueDisplay to improve/fix how we sent HU attributes to frontend**
- **changeQty: don't send bestBeforeDate and lotNo to backend if not needed**
> HUManager: change HU Qty - don't send BestBeforeDate and LotNo to backend

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/interim/InterimInvoiceLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/receipt/PurchaseOrderLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/inventory/InventoryLineLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/salesorderline/SOLineForPOLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/shipment/ShipmentLineForPOLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/salescontract/invoice/SalesInvoiceLineLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/salescontract/shipment/ShipmentLineForSOLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/LogEntryReverseRequest.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettings.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractMaterialReceiptLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractShippingNotificationLogHandler.java
https://github.com/metasfresh/metasfresh/issues/17902
> fix reverse log logic

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5722650_sys_gh17938_ProductCost_Details_Tab_Order.sql
https://github.com/metasfresh/metasfresh/issues/17938
> The latest records are displyed first in Cost details tab of the Product Cost window

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/ModularContractLogHandlerRegistry.java
https://github.com/metasfresh/metasfresh/issues/17902
> remove new line

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IViewRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRowFieldNameAndJsonValues.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRowsOrderBy.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/17953
*  https://github.com/metasfresh/metasfresh/pull/17920
*  https://github.com/metasfresh/metasfresh/pull/17901
*  https://github.com/metasfresh/metasfresh/pull/17798
> Merge soft_panda_uat -> master (2024-04-26)

- backend/de.metas.business/src/main/java/de/metas/product/ProductPrice.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/rawproduct/AVRawComputingMethod.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/rawproduct/AVRawMaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/interim/InterimInvoiceLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/interim/MaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/receipt/MaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/raw/RawSalesMaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/storagecost/ShipmentLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/pp/PPCostCollectorLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModuleConfig.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/IModularContractLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractMaterialReceiptLogHandler.java
refs: https://github.com/metasfresh/metasfresh/issues/17951
> Add value on raw product Computing Method

- backend/de.metas.business/src/main/java/de/metas/product/ProductPrice.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/rawproduct/AVRawComputingMethod.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/rawproduct/AVRawMaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/interim/InterimInvoiceLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/interim/MaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/receipt/MaterialReceiptLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/storagecost/ShipmentLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/pp/PPCostCollectorLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModuleConfig.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/IModularContractLogHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractMaterialReceiptLogHandler.java
* Add value on raw product Computing Method refs: https://github.com/metasfresh/metasfresh/issues/17951
> Add value on raw product Computing Method (#17952)

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5723000_sys_gh17962_UI_Changes.sql
refs: https://github.com/metasfresh/metasfresh/issues/17962
> UI Changes

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5723010_sys_gh17962_Flatrate_Term_Product_Search_Field.sql
refs: https://github.com/metasfresh/metasfresh/issues/17962
> Make product on flatrate_term as search field

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5723030_sys_gh17970_BOM_Version_Window_Trl.sql
https://github.com/metasfresh/metasfresh/issues/17970
> Updating missing DE translations

- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/callout/C_Flatrate_Term.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5723120_sys_gh17977_Contracts_Window_Adjustments.sql
https://github.com/metasfresh/metasfresh/issues/17977
> Contracts window adjustments

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MAlertRule.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Ini.java
- backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/Attachment.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/OutputType.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingData.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingDataFactory.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingDataToPDFFileStorer.java
- backend/de.metas.printing/de.metas.printing.base/src/test/java/de/metas/printing/api/impl/Helper.java
- backend/de.metas.printing/de.metas.printing.base/src/test/java/de/metas/printing/printingdata/PrintingDataToPDFFileStorerTest.java
- backend/de.metas.util/src/main/java/de/metas/util/FileUtil.java
- backend/de.metas.util/src/main/java/de/metas/util/io/CompositeOutputStream.java
- **introduce and use FileUtil.getTempDir**
- **OutputType.equals(type1, type2)**
- **PrintingData.additionalCopies; QA**
- **CompositeOutputStream**
- **PrintingDataToPDFFileStorer: create one file for each copy**
- **QA**
> PDF printer shall create one file for each copy

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/processedproduct/AVProcessedComputingMethod.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/processedproduct/AVProcessedManufacturingOrderLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ManufacturingFacadeService.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ManufacturingOrder.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ManufacturingReceipt.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ProcessedSalesManufacturingOrderLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractManufacturingOrderLogHandler.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5723490_sys_gh17996_Update_ModCntr_Type_For_Processed_Product_ValRule.sql
refs: https://github.com/metasfresh/metasfresh/issues/17996
> Add Value on Processed Product Computing Method

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/processedproduct/AVProcessedComputingMethod.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/processedproduct/AVProcessedManufacturingOrderLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ManufacturingFacadeService.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ManufacturingOrder.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/sales/processed/ManufacturingReceipt.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractManufacturingOrderLogHandler.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5723490_sys_gh17996_Update_ModCntr_Type_For_Processed_Product_ValRule.sql
* Add Value on Processed Product Computing Method refs: https://github.com/metasfresh/metasfresh/issues/17996
> Add Value on Processed Product Computing Method (#17997)

- backend/de.metas.contracts/src/main/java/de/metas/contracts/invoicecandidate/FlatrateDataEntryHandler.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/invoicecandidate/FlatrateTerm_Handler.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/PP_Order_MaterialTracking_Handler.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOut_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandidateHandlerBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/IInvoiceCandidateHandler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_InventoryLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_Inventory_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/ManualCandidateHandler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_OrderLine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_Order_Handler.java
QAs of https://github.com/metasfresh/metasfresh/pull/17999
> QAs of https://github.com/metasfresh/metasfresh/pull/17999

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
This comes from PR https://github.com/metasfresh/metasfresh/pull/15101 
Also add some simple improvements to make merging easier
> Port small part of PR-15101 so solve a concrete invoicing problem

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/ForwardingEventBus.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/IEventBus.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/impl/EventBus.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/ILocationDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/LocationCreateRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/GeocodingService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/asynchandler/LocationGeocodeEventRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/interceptor/C_Location.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/LocationDAO.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/location/impl/LocationDAOTest.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v1/bpartner/BPartnerRecordsUtil.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/bpartner/BPartnerRecordsUtil.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerLocation.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerLocationAddressPart.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerLocationImportHelper.java
- backend/de.metas.business/src/test/java/de/metas/bpartner/composite/repository/BPartnerCompositeRepositoryTest.java
- **IEventBus.enqueueObjectsCollection**
- **make sure a new C_Location is created only if there is any real change**
- **on C_Location save, send LocationGeocodeEventRequest only if we have any provider configured. Else we would get an imminent exception.**
- **cleanup some warnings**
> Create new C_Location records only if there is a real change; Fire LocationGeocodeEventRequest events only if we have a provider configured

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5723850_sys_gh18004_ComputingMethod_Trls.sql
refs: https://github.com/metasfresh/metasfresh/issues/18004
> Computing method trl

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5722700_sys_ModCntr_added_interest_columns.sql
refs https://github.com/metasfresh/metasfresh/issues/18016
> Add value/ Subtract value on Interim ( fix rollout )

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5722700_sys_ModCntr_added_interest_columns.sql
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5723591_sys_ModCntr_InvoicingGroup_currency_process_rework.sql
> rollout fix 2

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5723660_sys_gh17998_Product_Order_IC_Update.sql
- backend/de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5665370_sys_gh13968_include_inactive_HUs_in_MD_stock.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_OrderLine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_OrderLine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
> Merging modus_operandi_uat

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataLoader.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Clearance.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18031
*  https://github.com/metasfresh/metasfresh/pull/18029
> Merge tasty_ham_uat -> master (2024-05-21)

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/addedvalue/interim/ShipmentNotificationLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/subtractedvalue/interim/ShipmentNotificationLineLog.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/interceptor/ModCntr_Module.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5724030_sys_added_invoiceGroupNotFound_error_message.sql
> Add validation for invoicing group being present if creating modular contract settings with add/subtract value on interm modules

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/workpackage/impl/AbstractShippingNotificationLogHandler.java
> use raw product for invoicing group lookup

- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interest/BonusComputationDetails.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interest/InvoiceAllocations.java
refs: https://github.com/metasfresh/metasfresh/issues/18016
> fix days between

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup/legacy/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_old/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Generic_BPartner_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5723890_sys_gh_Docs_Generics_BPartner_Report_comment.sql
..and not the customer-masterdata address
> OderCheckup-Jasper - Make sure that the order's address is used if available

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5723970_sys_gh18032_Missing_Trl_Delivery_Planning.sql
https://github.com/metasfresh/metasfresh/issues/18032
> Add missing translations for Delivery Planning and Delivey Instructions windows

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5724250_sys_gh18042_Fix_PPOrder_ModCntrLog_RelationType.sql
refs: https://github.com/metasfresh/metasfresh/issues/18042
> Manufacturing ModCntr_Log Fix relation type

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5724250_sys_gh18042_Fix_PPOrder_ModCntrLog_RelationType.sql
refs: https://github.com/metasfresh/metasfresh/issues/18042
> Manufacturing ModCntr_Log Fix relation type (#18052)

- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/MainValidator.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interest/InterestComputationCommand.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interest/InterestComputationNotificationsProducer.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interest/InterestService.java
> fix notification logic

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5724300_purchase_order_highestprice_per_day_mv$update_fix_adprocess.sql
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5724290_sysconfig_de.metas.ui.web.material.cockpit.field.HighestPurchasePrice_AtDate.LastDays.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18058
*  https://github.com/metasfresh/metasfresh/pull/18055
> Merge soft_panda_uat -> master (2024-05-23)

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
issue was introduced by
* https://github.com/metasfresh/metasfresh/pull/10600
* https://github.com/metasfresh/metasfresh/pull/10603
> Payment Allocation accounting: hotfix how the currency conversion gain/loss is computed (basically copied from master)

- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/command/CreatePurchaseOrderFromRequisitionCommand.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18053
*  https://github.com/metasfresh/metasfresh/pull/17999
> Merge modus_operandi_uat -> master (2024-05-24)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5724340_sys_gh18073_Add_Display_Fonts_Process_Menu.sql
> Add missing Display Font process menu

- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5724032_sys_added_ModCntr_Interest_V.sql
> fix modCntr_Interest_v to only consider completed invoices

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Balance.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Invoice.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_MatchInv.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Fact.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/doc/DocLine_Invoice.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/tax/impl/TaxAcctBL.java
- backend/de.metas.acct.base/src/test/java/de/metas/acct/PostDocumentNow_ManualTest.java
- backend/de.metas.acct.base/src/test/java/org/compiere/acct/BalanceTest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IAcctSchemaDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AcctSchemaDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5689480_C_AcctSchema_IsAllowMultiDebitAndCredit.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/InventoryRepositoryTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.java
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/InventoryRepositoryTest.snap
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.snap
- **TaxAcctBL.retrieveTaxAcctRecord: avoid using query.addOnlyContextClient()**
- **C_AcctSchema.IsAllowMultiDebitAndCredit - copy from master**
- **Doc_Invoice: minor refactoring to make it callable from PostDocumentNow_ManualTest**
- **copy Fact and FactLine changes from master (will be needed in next commits)**
- **Balance.isDebit, computeDiffToBalance**
- **FactLine.setAmtAcct(Balance)**
- **FactLine.isDrSourceBalance: use Balance.isDrSourceBalance**
- **Fact.balanceAccounting fixes**
- **Doc_MatchInv: fix compile error**
> C_AcctSchema.IsAllowMultiDebitAndCredit - copy from master; Currency balancing fixes

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.jrxml
https://github.com/metasfresh/metasfresh/issues/18084
> Pagination correction

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Balance.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Invoice.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_MatchInv.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Fact.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLine.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/doc/DocLine_Invoice.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/tax/impl/TaxAcctBL.java
- backend/de.metas.acct.base/src/test/java/de/metas/acct/PostDocumentNow_ManualTest.java
- backend/de.metas.acct.base/src/test/java/org/compiere/acct/BalanceTest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IAcctSchemaDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AcctSchemaDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5689480_C_AcctSchema_IsAllowMultiDebitAndCredit.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/InventoryRepositoryTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.java
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/InventoryRepositoryTest.snap
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.snap
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18080
> Merge intensive_care_hotfix -> intensive_care_uat (2024-05-28)

- backend/de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java
- backend/de.metas.business/src/main/java/de/metas/invoice/sequence/InvoiceCountryIdProvider.java
https://github.com/metasfresh/metasfresh/issues/18081
> Customs Invoice cannot be created 

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/product/ResourceId.java
- backend/de.metas.manufacturing/src/main/java/de/metas/costing/methods/ManufacturingAveragePOCostingMethodHandler.java
- backend/de.metas.manufacturing/src/main/java/de/metas/costing/methods/ManufacturingStandardCostingMethodHandler.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/CreatePPOrderCostsCommand.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18096
> Merge intensive_care_hotfix -> intensive_care_uat (2024-05-29)

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5724740_sys_gh18095_Trls.sql
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5724790_sys_gh18095_Process_Param_Trl.sql
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5724850_sys_gh18095_Manufacturing_Issue_Receipt_Trls.sql
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5724860_sys_gh18095_Trls.sql
…OM Version windows
refs: https://github.com/metasfresh/metasfresh/issues/18095
> Add DE translations

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5724980_sys_gh18095_additional_trls.sql
refs: https://github.com/metasfresh/metasfresh/issues/18095
> Additional translations

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5724990_sys_gh18105_Add_POReference_ReceiptSchedule_Table.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5725020_sys_gh18105_Add_POReference_ReceiptSchedule_Win.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/I_M_ReceiptSchedule.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/X_M_ReceiptSchedule.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/InOutProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/ReceiptScheduleValidator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/impl/OrderLineReceiptScheduleProducer.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/OrderReceiptScheduleProducerTest.java
> Copy `PO reference` from `Purchase Order` to `Material Receipt`

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/plan/model/PickingPlan.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/HUsToPickOnTheFly.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5725055_sys_gh18110_alter_pickHUsOnTheFly_SysConfig_Description.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/PackageableQuery.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/impl/PackagingDAO.java
https://github.com/metasfresh/metasfresh/issues/18110
> Auto pick the HUs on shipment and create inventories if HUs are not covering the qty 

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.jrxml
> pagination update: 1space/space1

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5725330_sys_gh18095_de_ch_translation.sql
refs: https://github.com/metasfresh/metasfresh/issues/18095
> DE_CH translation of qty required ad_element

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5725330_sys_gh18095_de_ch_translation.sql
refs: https://github.com/metasfresh/metasfresh/issues/18095
> de_ch translation of qty required ad_element (#18130)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.jrxml
https://github.com/metasfresh/metasfresh/issues/18084
> pagination update: 1space/space1 (#18124)

- backend/de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java
- backend/de.metas.business/src/main/java/de/metas/invoice/sequence/InvoiceCountryIdProvider.java
> Release to master merge

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/accounting/filters/FactAcctFilterDescriptorsProviderFactory.java
https://github.com/metasfresh/metasfresh/issues/18137
> operator is marked non-null but is null

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5725740_PP_Cost_Collector_windowTab_make_not_readonly.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18157
> Merge intensive_care_hotfix -> intensive_care_uat (2024-06-05)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5725740_PP_Cost_Collector_windowTab_make_not_readonly.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18158
> Merge intensive_care_uat -> master (2024-06-05)

- frontend/src/components/widget/List/RawList.js
> Replace the newline characters (\n) with a space in input

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/geo_location/GeoLocationDocumentService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/ViewLayoutFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/json/JSONViewLayout.java
- frontend/src/components/maps/GeoMap.js
- frontend/src/containers/DocumentList.js
- frontend/src/utils/documentListHelper.js
* JSONViewLayout: cleanup
* ViewLayoutFactory: consider geoLocationSupport=true whenever we have a area search filter
* fix google maps/osm integration
(cherry picked from commit 7efcf4f42a97b1a65584cdd8671d78233e76b413)
> Fix geocoding integration (#13398)

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5725840_sys_gh18173_drop_and_recreate_c_doc_responsible_table_record_ref_name_index.sql
* Mahndisposition - keine Mahnung erstellt refs: https://github.com/metasfresh/metasfresh/issues/18173
> Mahndisposition - keine Mahnung erstellt (#18175)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5725850_sys_gh18143_C_BPartner_Update_Memo_Process.sql
> Partner Update Memo Process - memo default value

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/process/C_BPartner_Update_Memo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/process/CBPartnerUpdateMemoTest.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5725420_sys_gh18143_C_BPartner_Update_Memo_Process.sql
> merging `intensive_care_ua`

- frontend/src/components/app/Modal.js
- frontend/src/components/keyshortcuts/ModalContextShortcuts.js
- frontend/src/components/keyshortcuts/ShortcutProvider.js
- **ModalContextShortcuts.js: forward the return of the done handler to called of doneAction**
- **ModalContextShortcuts.cancel: stop propagation**
- **Modal.js: close printing dialog after print**
- **handle the print hot key (alt-p) only if we are in printing modal (and not other modales like process dialog)**
> webui frontend: when pressing ALT-P and printing dialog is already open then it shall just do the printing and close the dialog

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
https://github.com/metasfresh/metasfresh/issues/18143
> Partner Update Memo Process - memo can be null

- frontend/src/assets/css/inputs.scss
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18191
*  https://github.com/metasfresh/metasfresh/pull/16990
> Merge release -> master (2024-06-07)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
I.e. it prefers a bill-relation partner if there is one
#17995
> FlatrateBL.createTerm now gets billto location like order does

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/automaticlinksharing/RecordToReferenceProviderService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/AttachmentInvoiceCandidateListener.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/attachment/JsonAttachmentRequest.java
..also do minor improvements elsewhere
> JsonPersisterService: Fix bug when IBAN is updated

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/automaticlinksharing/RecordToReferenceProviderService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/ModularContractProvider.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/AttachmentInvoiceCandidateListener.java
> Merge to master from origin/inner_silence_uat

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
> Merge to master from origin/intensive_care_uat

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
…payment rule cash
refs: https://github.com/metasfresh/metasfresh/issues/18233
> take cash_as_payment sysconfig into consideration when invoicing

- backend/de.metas.business/src/main/java/de/metas/pricing/service/IPriceListBL.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListBL.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/dataEntry/invoice/FlatrateDataEntryToICService.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/QualityInspectionHandlerDAO.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18224
*  https://github.com/metasfresh/metasfresh/pull/18146
*  https://github.com/metasfresh/metasfresh/pull/18138
*  https://github.com/metasfresh/metasfresh/pull/18067
> Merge soft_panda_uat -> master (2024-06-13)

- backend/de.metas.business/src/main/java/de/metas/pricing/service/IPriceListBL.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListBL.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/QualityInspectionHandlerDAO.java
…(#18224)
See the change in PricingBL.setupPriceListAndDate .
(cherry picked from commit 159eabc4a285f2de77e3118d4e051375b327d0fd)
> If the pricing-engine is handed a pricelist-ID, then it shall use it

- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/dataEntry/invoice/FlatrateDataEntryHandler.java
> Fix bug where ICs attributes were not taken into account when computing the price

- backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/dataEntry/invoice/FlatrateDataEntryHandler.java
> Merge to master from origin/middle_ages_uat

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUQueryBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQueryBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_Product.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageEngine.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageQuery.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5726520_sys_gh18254_Inactive_Products_With_Stock_AD_Message.sql
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/process/DD_Order_GenerateRawMaterialsReturn.java
- backend/de.metas.storage/src/main/java/de/metas/storage/IStorageEngine.java
- backend/de.metas.storage/src/main/java/de/metas/storage/IStorageQuery.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterList.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/MaterialCockpitFilters.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/ProductFilterUtil.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/ProductFilterVO.java
refs: https://github.com/metasfresh/metasfresh/issues/18254
> Inactive products with qty in warehouse

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5726650_sys_gh17995_tweak_view_fresh_Attributes.sql
❗ Please make sure not to break the existing view when merging totards master
> Tweak jasper-view fresh_Attributes

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5726970_sys_gh18291_User_BPartner_Filter.sql
refs: https://github.com/metasfresh/metasfresh/issues/18291
> Filter Nutzer

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5726970_sys_gh18291_User_BPartner_Filter.sql
refs: https://github.com/metasfresh/metasfresh/issues/18291
> Filter Nutzer (#18295)

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/json/JSONViewOrderBy.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentList.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/OrderedDocumentsList.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentQueryBuilder.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java
- frontend/.gitignore
- frontend/LICENSE.md
- frontend/src/actions/TableActions.js
- frontend/src/actions/WindowActions.js
- frontend/src/api/view.js
- frontend/src/api/window.js
- frontend/src/components/window/Tab.js
- frontend/src/constants/Constants.js
- frontend/src/containers/MasterWindow.js
- frontend/src/reducers/tables.js
- frontend/src/store/configureStore.js
- frontend/src/utils/index.js
- frontend/webpack.config.js
- **SqlDocumentsRepository.retrieveDocuments: result shall have the effective order by used**
- **GET /window/{windowId}/{documentId}/{tabId} shall return the effective order by used too**
- **enable devtools tracing**
- **update .gitignore**
- **update LICENSE.md from master**
> webui frontend: included tabs: rows notified via websockets shall be added respecting order bys

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5727040_sys_gh18288_update_sysconfig_mobileuiDefaultFilters.sql
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobDefaultFilter.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/manufacturing/job/service/ManufacturingJobServiceTest.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/ManufacturingOrderQuery.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
refs: https://github.com/metasfresh/metasfresh/issues/18288
> mobile UI: Production - Switch to DateStartSchedule

- misc/services/mobile-webui/mobile-webui-frontend/src/assets/index.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/toast.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
refs: https://github.com/metasfresh/metasfresh/issues/18301
this PR is copying the feature from master
> Error message on scanner can be acknowledged

- backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvDAO.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvDAO.java
- backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/EDI_Desadv.java
- backend/de.metas.edi/src/main/java/de/metas/edi/process/EDI_Desadv_InOut_EnqueueForExport.java
refs: https://github.com/metasfresh/metasfresh/issues/18259
> propagate edi status to shipment

- .github/workflows/cicd.yaml
- docker-builds/cucumber/run.cmd
- docker-builds/cucumber/stop.cmd
- docker-builds/health/containerHealthCheck.sh
* pipeline update 0.3.7 - replace docker-compose with docker compose
* adjust container names
(cherry picked from commit f0188860338c87c03552aad317f097de40dc3d53)
> pipeline update 0.3.7 - replace deprecated docker-compose with docker compose

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ManufacturingJob.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ManufacturingJobReference.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingMobileApplication.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingWorkflowLaunchersProvider.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5727220_sys_gh18288_EffProdDate.sql
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WFProcessHeaderProperty.java
refs: https://github.com/metasfresh/metasfresh/issues/18288
> DateStartSchedule without time

- backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/impl/OLCandHUPackingAware.java
- backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/I_C_OLCand.java
- backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandBL.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandEffectiveValuesBL.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCand.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandBL.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandEffectiveValuesBL.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/modelvalidator/C_OLCand.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/DefaultOLCandValidator.java
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5727280_sys_gh18320_OLCand_QtyEntered_Override.sql
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5727320_sys_gh18320_OLCand_QtyEntered_Override.sql
refs: https://github.com/metasfresh/metasfresh/issues/18320
> Introduce QtyEntered_Override into C_olcand to override Qty

- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
refs: https://github.com/metasfresh/metasfresh/issues/18259
> fix cucumber

- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Invoice.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogService.java
https://github.com/metasfresh/metasfresh/issues/18331
> CR fixes for https://github.com/metasfresh/metasfresh/pull/18322

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5727410_sys_gh18336_C_Order_Bill_Location_ID.sql
refs: https://github.com/metasfresh/metasfresh/issues/18336
> BPartner-Location not set in purchase order

- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5727410_sys_gh18336_C_Order_Bill_Location_ID.sql
refs: https://github.com/metasfresh/metasfresh/issues/18336
> BPartner-Location not set in purchase order (#18337)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5726940_sys_gh18285_Use_Lookup_Instead_Listview.sql
https://github.com/metasfresh/metasfresh/issues/18285
> Use Lookup widget (Search) instead of listview for all windows

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/ProductRestService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/uomconversion/UomConversionRestService.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/product/ProductsRestControllerTest.java
- backend/de.metas.business/src/main/java/de/metas/uom/IUOMConversionDAO.java
- backend/de.metas.business/src/main/java/de/metas/uom/IUOMDAO.java
- backend/de.metas.business/src/main/java/de/metas/uom/UpdateUOMConversionRequest.java
- backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMConversionDAO.java
- backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMDAO.java
- backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5727690_sys_gh18349_c_uom_conversion_product.sql
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/C_UOM_Conversion_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/product/M_Product_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/productRestController.feature
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestProduct.java
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/JsonRequestUOMConversionUpsert.java
- misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/CamelProcessorUtil.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/ProductUpsertProcessor.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/UOMCodeEnum.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/model/ProductRow.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/java/de/metas/camel/externalsystems/pcm/product/GetProductsFromFileRouteBuilderTest.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/product/10_Product_ImportFile.csv
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/product/20_CamelUpsertProductRequest.json
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/product/40_CamelUpsertProductRequest.json
refs: https://github.com/metasfresh/metasfresh/issues/18349
> Create UOM-Conversions while importing article-csv

- backend/de.metas.materialtracking/src/main/sql/postgresql/system/50-de.metas.materialtracking/5727590_sys_18347_M_Material_Tracking_FlatrateTerm_Valrule_Fixed.sql
https://github.com/metasfresh/metasfresh/issues/18347
> Update `C_Flatrate_Term for M_Material_Tracking` validation rule

- frontend/src/actions/WindowActions.js
issue introduced by 
* https://github.com/metasfresh/metasfresh/pull/18310
> FE Don't fail when editing included tab rows in advanced mode

- frontend/src/actions/WindowActions.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18354
> Merge intensive_care_uat -> master (2024-07-03)

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/UOMCodeEnum.java
refs: https://github.com/metasfresh/metasfresh/issues/18349
> add ml - ML mapping

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/UOMCodeEnum.java
refs: https://github.com/metasfresh/metasfresh/issues/18349
> add ml - ML mapping (#18397)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Dunning_Report_details_sum.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5728060_sys_gh18411_DunningLevel_FeeAmt_Field.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5728070_sys_gh18411_Docs_Sales_Dunning_Report_details_sum.sql
https://github.com/metasfresh/metasfresh/issues/18411
> Dunning fee amount update

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5728060_sys_gh18411_DunningLevel_FeeAmt_Field.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5728070_sys_gh18411_Docs_Sales_Dunning_Report_details_sum.sql
https://github.com/metasfresh/metasfresh/issues/18411
> mergin `modified_carbon_uat`

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestination.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
Fixes
* https://github.com/metasfresh/metasfresh/pull/18353
> Fix how we determine which LU PI item to be used

- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
(cherry picked from commit 4429ef1ba831db217928ca5d70d418281dfffb61)
> CP - App startup fix

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Workplace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Workplace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/picking/api/PickingSlotId.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/Workplace.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workplace/WorkplaceRepository.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/workplace/qrcode/WorkplaceQRCodeTest.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5728940_sys_gh18476_Workplace_PickingSlot.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/DefaultPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/DefaultPickingJobLoaderSupportingServicesFactory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobAllocatePickingSlotCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCreateCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationRepository.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/repository/MockedPickingJobLoaderSupportingServices.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJobTestHelper.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/IPickingSlotBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/api/impl/PickingSlotBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/workplace/interceptor/C_Workplace.java
refs: https://github.com/metasfresh/metasfresh/issues/18476
> Default Picking Slot Set by Workstation

- backend/de.metas.business/src/main/java/de/metas/inout/IInOutBL.java
- backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUServiceTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplit.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitService.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitServiceTest.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRows.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentView_Launcher.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5729250_sys_gh18473_SplitShipmentView_Launcher.OnlyOpenedStatusSelection_Msg.sql
https://github.com/metasfresh/metasfresh/issues/18473
> `Split Shipment View` update

- backend/de.metas.business/src/main/java/de/metas/inout/IInOutBL.java
- backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUServiceTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplit.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitService.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/split/ShipmentScheduleSplitServiceTest.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRows.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentView_Launcher.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5729250_sys_gh18473_SplitShipmentView_Launcher.OnlyOpenedStatusSelection_Msg.sql
https://github.com/metasfresh/metasfresh/issues/18473
> mergin `inner_silence_uat`

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/report/HUReportAwareViewRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/report/HUReportProcessInstancesRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/receiptSchedule/HUsToReceiveViewFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IViewRow.java
refs: https://github.com/metasfresh/metasfresh/issues/18502
> Show Process M_HU_Report_QRCode in HU Editor only on active HUs

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_EXP_FormatLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_EXP_FormatLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/server/rpl/api/impl/ImportHelper.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/process/rpl/requesthandler/spi/IReplRequestHandler.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/api/IIMPProcessorBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/api/IImportHelper.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/api/impl/IMPProcessorBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/exceptions/DuplicateLookupObjectException.java
- backend/de.metas.edi/src/main/sql/postgresql/ddl/views/EDI_C_BPartner_Lookup_BPL_GLN_v.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5727930_sys_gh18408_C_BPartner_Lookup_Label.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5727980_sys_gh18408_Exp_FormatLine_add_Operator.sql
- misc/dev-support/docker/infrastructure/env-files/soft_panda_uat.env
- misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
> Add C_BPartner.Lookup_Label as additional lookup-criterion when selecing BPartners during EDI-ORDERS import

- frontend/src/utils/dateHelpers.js
https://github.com/metasfresh/metasfresh/issues/18512
> Editing DatePromised and DatePreparation causes white screen

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5729910_sys_gh18512_UI_Improvements.sql
https://github.com/metasfresh/metasfresh/issues/18512
> UI improvements and doc type trls

- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/manufacturing_issue.js
refs: https://github.com/metasfresh/metasfresh/commit/ffc5eff9bc8a90ae910f7dcaca9ddbe81baf41e0
> fix string qty on manufacturing state

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/server/rpl/api/impl/ImportHelper.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MEXPFormat.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730050_sys_gh18408_fix_Exp_Format.sql
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
> fix mistake in the changed exp_format and add missing caching for export-format-lines

- backend/de.metas.manufacturing/src/main/java/de/metas/costing/methods/ManufacturingAveragePOCostingMethodHandler.java
- backend/de.metas.manufacturing/src/main/java/de/metas/costing/methods/ManufacturingStandardCostingMethodHandler.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/acct/Doc_PPCostCollectorTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
- **cost collector posting: check if we already have the cost detail created**
- **Doc_PPCostCollectorTest.java**
> hotfix PP_Cost_Collector posting - creck if M_CostDetail already exist before deciding to create a new one

- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/acct/Doc_PPCostCollectorTest.java
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/manufacturing_issue.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18541
*  https://github.com/metasfresh/metasfresh/pull/18536
*  https://github.com/metasfresh/metasfresh/pull/18480
*  https://github.com/metasfresh/metasfresh/pull/18468
*  https://github.com/metasfresh/metasfresh/pull/18467
*  https://github.com/metasfresh/metasfresh/pull/18384
*  https://github.com/metasfresh/metasfresh/pull/18201
> Merge intensive_care_uat -> master (2024-07-25)

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/process/AbstractProcessDocumentsTemplate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/process/ProcessDocuments.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/process/ProcessDocumentsBySelection.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
refs: https://github.com/metasfresh/metasfresh/issues/18498
> Process documents by selection

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/callExternalSystem/CallExternalSystemActivityHandler.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5730140_sys_gh18479_update_msg_trl.sql
refs: https://github.com/metasfresh/metasfresh/issues/18479
> Mobile UI: Production process - update trl messages

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/edi/EDI_Desadv_Pack_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_TU_UOM.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_normal_UOM.feature
- backend/de.metas.edi/src/main/java-gen/de/metas/esb/edi/model/I_EDI_Desadv_Pack.java
- backend/de.metas.edi/src/main/java-gen/de/metas/esb/edi/model/X_EDI_Desadv_Pack.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvDAO.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvDAO.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/CreateEDIDesadvPackRequest.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackRepository.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java
- backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730220_sys_gh18558_EDI_Desadv_Pack_Line_addColumn.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730222_sys_gh18558_EDI_Desadv_Pack_Line_setMandatory.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730224_sys_gh18558_EDI_Desadv_Pack_Line_migrate.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730230_sys_gh18558_EDI_Desadv_Pack_Line_addFields.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730270_sys_gh18558_EDI_Desadv_Pack_Line_addUC.sql
- misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/SimpleSequence.java
- misc/de-metas-common/de-metas-common-util/src/test/java/de/metas/common/util/SimpleSequenceTest.java
- misc/dev-support/docker/infrastructure/env-files/intensive_care_uat.env
- misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
> Add EDI_Desadv_Pack.Line column for DESADV export

- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
(cherry picked from commit 03d92433a519944ca39a4f18c3f8bc3a539fef22)
> port unit test fix from master (#18570) (#18582)

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/process/AbstractProcessDocumentsTemplate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/process/ProcessDocumentsBySelection.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5730640_sys_gh18572_Void_Selected_Invoices.sql
* process documents by selection refs: https://github.com/metasfresh/metasfresh/issues/18498
(cherry picked from commit ffd83032058ad1aadd431fb5ba4df1644ad9827b)
> Process documents by selection (#18499)

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
refs: https://github.com/metasfresh/metasfresh/issues/18554
> fix old NPE in master

- misc/services/mobile-webui/mobile-webui-frontend/package.json
- misc/services/procurement-webui/procurement-webui-frontend/package.json
> Fix js builds (mobileUI and procurementUI)

- backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_140_v_view.sql
- backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_901_991_v_view.sql
- backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_500_v_view.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730520_sys_gh18532_invoic_include_pmtDiscount_as_surchargeAmt_DDL.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730780_sys_gh18532_further_extend_INVOIC_export.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730900_sys_gh18532_further_extend_INVOIC_views_DDL.sql
- misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/constants/SwaggerDocConstants.java
- misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
> Merge to master from origin/vampire_textbook_uat

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5726916_sys_gh18259_activatePOReference_InDesadvExport.sql
refs: https://github.com/metasfresh/metasfresh/issues/18583
> activate POReference export format line

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/CalculateCustom_InvoiceLine_BruttoWeight.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5731250_sys_gh18641_temporary_drop_functions_and_views.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5731251_sys_gh18641_migrate_data.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5731252_sys_gh18641_rename_column.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5731253_sys_gh18641_reconstruct_views_functions.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5731254_sys_gh18641_add_ad_element.sql
refs: https://github.com/metasfresh/metasfresh/issues/18641
> Rename M_Product weight columns

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/model/validator/M_InOut.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inout/5731140_sys_gh18645_PreventVoidingShipmentsWhenInvoiceExists.sql
refs: https://github.com/metasfresh/metasfresh/issues/18645
> Prevent voiding shipments when invoice exists

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPIItemProductBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPIItemProductDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/QtyConvertor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/QtyConvertorService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/QtyTUConvertor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/rowfactory/CountingSubRowBucket.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/rowfactory/DimensionGroupSubRowBucket.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/rowfactory/MainRowWithSubRows.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5731360_sys_gh18671_add_new_sys_config.sql
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5731360_sys_gh_add_new_sys_config.sql
- backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/material/cockpit/rowfactory/MaterialCockpitRowFactoryTest.java
https://github.com/metasfresh/metasfresh/issues/18671
> Show Qty in TU UOM in Material Cockpit (based on default packing capacity

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5731270_sys_gh18656_BOM_Name_Optional.sql
refs: https://github.com/metasfresh/metasfresh/issues/18656
> BOM Name optional

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/QtyTUConvertor.java
https://github.com/metasfresh/metasfresh/issues/18671
> Show Qty in TU UOM in Material Cockpit (always go up)

- .github/workflows/cicd.yaml
- docker-builds/cucumber/run.cmd
- docker-builds/cucumber/stop.cmd
- docker-builds/health/containerHealthCheck.sh
merging after pink_rooster_uat_7 into pink_rooster_hotfix
> merging after rollout pink_rooster_uat_7 into pink_rooster_hotfix

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/tree/spi/impl/MenuTreeSupport.java
(cherry picked from commit 846a7a8f6cc0ddf9c806b2e2dbbef26ae60fa73b)
> Fix SQL syntax problem loading menu tree (#15470)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IProcessPrecondition.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessPreconditionChecker.java
- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731790_sys_gh18716_C_Invoice_Schedule_revamp.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/invoice/process/C_InvoiceSchedule_CreateOrUpdate.java
https://github.com/metasfresh/metasfresh/issues/18716
> Display C_InvoiceSchedule.InvoiceDistance because it's used in the BL - Do different UI-related fixes

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
https://github.com/metasfresh/metasfresh/issues/18737
> MobileUI Picking - TU with Catch Weight

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732170_sys_gh18737_updatetrl.sql
refs: MobileUI Picking - TU with Catch Weight
https://github.com/metasfresh/metasfresh/issues/18737
> Update Mobile UI Picking Profile translations

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/MobileUIPickingUserProfile.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/MobileUIPickingUserProfileRepository.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732250_sys_gh18737_renameAllowNewLU.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732255_sys_gh18737_migrateValues.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732256_sys_gh18737_dropOldColumn.sql
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingJobRestService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/ActualPickingWFActivityHandler.java
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/picking/index.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickProductsActivity.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/picking.js
refs: MobileUI Picking - TU with Catch Weight
https://github.com/metasfresh/metasfresh/issues/18737
> Change behaviour of IsAllowNewLU

- backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
> Merge to master from origin/release

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/AbstractProducerDestination.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUTrxAttributesCollector.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/PackToHUsProducer.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732470_sys_gh18770_add_mobile_ui_sys_configs.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
refs: MobileUI Picking (F0230) - Introducing new TUs 
https://github.com/metasfresh/metasfresh/issues/18770
> Destroy dangling aggregated hu item & mobile ui sys configs

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
- backend/de.metas.util.web/src/main/java/de/metas/rest_api/utils/JsonErrors.java
- backend/de.metas.util.web/src/main/java/de/metas/rest_api/utils/v2/JsonErrors.java
- backend/de.metas.util.web/src/test/java/de/metas/rest_api/utils/JsonErrorsTest.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickProductsActivity.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/applicationRoot/ApplicationRoot.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
refs: MobileUI Picking (F0230) - Introducing new TUs https://github.com/metasfresh/metasfresh/issues/18770
> Use global variable for 'showAllErrorMessages'

- backend/de.metas.business/src/main/java/de/metas/inout/IInOutBL.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java-gen/de/metas/document/archive/model/I_C_Doc_Outbound_Log.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java-gen/de/metas/document/archive/model/X_C_Doc_Outbound_Log.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/IDocOutboundDAO.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/DocOutboundDAO.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/DocOutboundService.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/C_Invoice.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/M_InOut.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/sql/postgresql/system/5732530_sys_gh18801_C_Doc_Outbound_Log_POReference.sql
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/sql/postgresql/system/5732560_sys_gh18801_update_C_Doc_Outbound_Log_POReference.sql
refs: https://github.com/metasfresh/metasfresh/issues/18801
> Make docOutboundLog.POReference normal column

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Archive.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Archive.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportResult.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/ArchiveInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/ArchiveRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/IArchiveDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/InOutDocumentReportAdvisor.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/InvoiceDocumentReportAdvisor.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/AD_Archive.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/C_Invoice.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/sql/postgresql/system/5732580_sys_gh18801_AD_Archive_POReference.sql
refs: https://github.com/metasfresh/metasfresh/issues/18801
> add AD_Archive.POReference

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidationEngine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/DocTimingType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/annotations/Interceptor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/annotations/Validator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/C_Order.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/Main.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/handleordervoid/DefaultOrderUnProcessHandler.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/handleordervoid/HUReservationAfterOrderUnProcessService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/handleordervoid/HandlerResult.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/handleordervoid/IUReservationAfterOrderUnProcessHandler.java
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/sales_order/RepairSalesOrderService.java
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/sales_order/handleordervoid/RepairOrderUnProcessHandler.java
- backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/sales_order/interceptor/C_Order.java
Add a little framework so that different modules can register own logic.
Also
- convert the existing code in service-repair-order module accordingly
- create a default-handler which covers void or reversal of "normal" order
> HU-Unreserve on order void or reverse (or reactivate)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/ShipperTransportationQuery.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/ShipperTransportationRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/interceptor/M_InOut.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/shippertransportation/ShipperDeliveryService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732800_sys_gh_18770_add_to_shipper_transportation.sql
refs: MobileUI Picking (F0230) - Introducing new TUs https://github.com/metasfresh/metasfresh/issues/18770
> Add to daily shipper transportation order

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
refs: https://github.com/metasfresh/metasfresh/issues/18820
> Adjust for partial deliveries with individual invoices

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
* Adjust for partial deliveries with individual invoices refs: https://github.com/metasfresh/metasfresh/issues/18820
> Adjust for partial deliveries with individual invoices (#18821)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/ShipperTransportationQuery.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/ShipperTransportationRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/interceptor/M_InOut.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/shippertransportation/ShipperDeliveryService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732800_sys_gh_18770_add_to_shipper_transportation.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18826
*  https://github.com/metasfresh/metasfresh/pull/18805
> Merge intensive_care_uat -> master (2024-09-10)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/fresh_HU_SSCC_Label_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5732820_sys_gh18823_fresh_HU_SSCC_Label_Report.sql
https://github.com/metasfresh/metasfresh/issues/18823
> Correcting the `TU_per_LU` calculation

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/label.jrxml
https://github.com/metasfresh/metasfresh/issues/18841
> Fix Band height validation build error in `de/metas/docs/label/sscc/label.jrxml`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/label.jrxml
https://github.com/metasfresh/metasfresh/issues/18841
> Fix page overflow

- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/DDOrderLowLevelDAO.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateAlloc.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateAllocList.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/material_dispo/PPOrderCandidateListeners.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5733040_DD_Order_Candidate_EnqueueToProcess_trl.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18843
> Merge intensive_care_uat -> master (2024-09-11)

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730700_sys_gh18583_add_new_aggregation_oneInvoicePerShip.sql
refs: https://github.com/metasfresh/metasfresh/issues/18857
> add new aggregation one invoice per shipment

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
https://github.com/metasfresh/metasfresh/issues/18863
> MobileUI: Fix multiple TUs picked from source LU

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_DD_Order_Candidate.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_DD_Order_Candidate.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderLineBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderLineBL.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/ddordercandidate/DD_Order_Candidate_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_Order_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production_and_distribution.feature
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidate.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateProcessCommand.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateRepository.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5733140_enable_zooming_from_pporder_to_ddorder.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5733150_DD_Order_Candidate.C_OrderSO_ID.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5733151_cli_DD_Order_Candidate.C_OrderSO_ID_migrate.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5733180_hide_DD_Order_Candidate_Forward_PP_OrderBOMLine_ID_if_not_set.sql
- backend/de.metas.manufacturing/src/test/java/de/metas/distribution/ddordercandidate/DDOrderCandidateRepositoryTest.java
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/RequestMaterialOrderService.java
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/Candidate.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddordercandidate/DDOrderCandidateAdvisedHandler.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/ddordercandidate/DDOrderCandidateData.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/18854
*  https://github.com/metasfresh/metasfresh/pull/18853
> Merge intensive_care_uat -> master (2024-09-12)

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/exp/RabbitMqExportProcessor.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/imp/RabbitMqListener.java
- misc/services/camel/de-metas-camel-edi/src/main/resources/application.properties
https://github.com/metasfresh/metasfresh/pull/18632
> Fix camel EDI ORDERS message ordering

- frontend/src/pages/calendar/Calendar.scss
https://github.com/metasfresh/metasfresh/issues/18885
> Change the font to black of the items in calendar view

- frontend/src/pages/calendar/Calendar.scss
https://github.com/metasfresh/metasfresh/issues/18885
> Improve Readability of items in calendar view

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/product/model/I_M_Product_PlanningSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/product/model/X_M_Product_PlanningSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_Planning.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_Planning.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5733450_sys_gh18887_C_Manufacturing_Aggregation_ID.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5733460_sys_gh18887_update_ad_reference.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5733470_sys_gh_18887_add_default_aggregation.sql
- backend/de.metas.business/src/main/java/de/metas/material/planning/ProductPlanning.java
- backend/de.metas.business/src/main/java/de/metas/material/planning/impl/ProductPlanningDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/ProductPlanningSchema.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductPlanningSchemaBL.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductPlanningSchemaDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
- backend/de.metas.manufacturing/pom.xml
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderCreateRequestBuilder.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/agg/key/impl/PPOrderCandidateAggregationFactory.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/agg/key/impl/PPOrderCandidateHeaderAggregationKeyBuilder.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/agg/key/impl/PPOrderCandidateHeaderAggregationKeyHelper.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/agg/key/impl/PPOrderCandidateKeyValueHandler.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/async/GeneratePPOrderFromPPOrderCandidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/produce/PPOrderAllocator.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/produce/PPOrderAllocatorService.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/produce/PPOrderCandidateToAllocate.java
https://github.com/metasfresh/metasfresh/issues/18887
> Aggregate PP Order Candidates via C_Aggregation

- backend/de.metas.materialtracking/src/main/java-gen/de/metas/materialtracking/ch/lagerkonf/model/I_M_QualityInsp_LagerKonf_AdditionalFee.java
- backend/de.metas.materialtracking/src/main/java-gen/de/metas/materialtracking/ch/lagerkonf/model/X_M_QualityInsp_LagerKonf_AdditionalFee.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/ILagerKonfQualityBasedConfig.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/impl/HardCodedQualityBasedConfig.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/impl/RecordBackedQualityBasedConfig.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/invoicing/impl/QualityInvoiceLineGroupsBuilder.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/QualityInspectionLineType.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/spi/IQualityBasedConfig.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5733510_sys_gh18910_QualityInsp_AdditionalFee_ApplyFeeTo.sql
refs: https://github.com/metasfresh/metasfresh/issues/18910
> Waschproben Additional Fee Raw Material

- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/InvoiceCandidateWriter.java
refs: https://github.com/metasfresh/metasfresh/issues/18910
> fix Abrechnung Waschproben BIO paymentterm_ID

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
https://github.com/metasfresh/metasfresh/issues/18770
> use existing HUContext when copying attributes

- frontend/src/__tests__/components/widget/Lookup/RawLookup.test.js
- frontend/src/components/widget/Lookup/RawLookup.js
https://github.com/metasfresh/metasfresh/issues/18905
> Lookup widget (Search) update

- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5734170_C_POSOrder_CreateInvoiceAndShipment_package_processor.sql
Fixes 
* https://github.com/metasfresh/metasfresh/pull/18881
> mobile POS prototype (iteration 1)  - fixes - 5734170_C_POSOrder_CreateInvoiceAndShipment_package_processor.sql

- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/containers/HUManagerScreen.jsx
https://github.com/metasfresh/metasfresh/issues/18936
> MobileUI App HU Manager - allow moving all HUs

- misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/containers/HUManagerScreen.jsx
https://github.com/metasfresh/metasfresh/issues/18936
> MobileUI App HU Manager - allow moving all HUs (#18937)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_logo.jrxml
https://github.com/metasfresh/mf15/issues/3030
> Update logo Position

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5641230_sys_gh13064_Shipment_window_adjustments.sql
(cherry picked from commit e35e0409ab638a50819a41886ab942cafa820555)
> Shipment window adjustments (#13067)

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5734550_sys_gh18966_EDI_DESADV_Customizations.sql
refs: https://github.com/metasfresh/metasfresh/issues/18966
> Allow Users to find Shipments that need to be sent by DESADV

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5734550_sys_gh18966_EDI_DESADV_Customizations.sql
refs: https://github.com/metasfresh/metasfresh/issues/18966
> Fix EDI_ExportStatus

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/MobileUIPickingUserProfile.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/MobileUIPickingUserProfileRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobSaver.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5734890_sys_gh_isShowPromptOnOverPick.sql
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingJobRestService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/ActualPickingWFActivityHandler.java
- misc/services/mobile-webui/mobile-webui-frontend/package.json
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScreenToaster.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/picking.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/numberUtils.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
- misc/services/mobile-webui/mobile-webui-frontend/yarn.lock
refs:
https://github.com/metasfresh/metasfresh/issues/18962 
https://github.com/metasfresh/metasfresh/issues/18963 
https://github.com/metasfresh/metasfresh/issues/18964
> Mobile UI: clear picking slots, prompt on overpick & fix toast notications

- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/toast.jsx
refs:
https://github.com/metasfresh/metasfresh/issues/18962 https://github.com/metasfresh/metasfresh/issues/18964
> Mobile UI: prompt on overpick & toast notifications improvements

- backend/de.metas.business/src/main/java/de/metas/uom/IUOMDAO.java
- backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMDAO.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRow.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefDataIdentifier.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/billofmaterial/PP_Product_Bom_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/voidOrder.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/productionCandidate.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/productionCandidate_with_BOM_recursion.feature
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5735040_sys_gh18935_tweaks.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5735080_sys_gh18935_tweaks.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_ShipmentSchedule_PostMaterialEvent.java
- extend the test to cover scenario with UOM-conversions
- correctly handle MD_Candidates if an order is voided
- add relationtype for PP_Order_candidate-parent and tweak display-columns
> Intensive care uat materialdispo tweaks

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
refs: https://github.com/metasfresh/metasfresh/issues/18963
> Picking slot clearing improvements

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5735230_sys_gh18964_adjust_trl.sql
refs: https://github.com/metasfresh/metasfresh/issues/18963
> Adjust process translation

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5735230_sys_gh18964_adjust_trl.sql
refs: https://github.com/metasfresh/metasfresh/issues/18963
> Adjust process translation (#19003)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/Constants.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/EDIDesadvQuery.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvDAO.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/MatchOrderIdShipmentScheduleConsolidatePredicate.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvDAO.java
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5735250_sys_gh19009_MatchUsingC_Order_ID_Sysconfig.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/AbstractHUShipmentProcessIntegrationTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHUTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllowConsolidatePredicate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/ShipmentScheduleAllowConsolidatePredicateComposite.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
refs: https://github.com/metasfresh/metasfresh/issues/19009
> EDI DESADV MatchUsingC_Order_ID

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719010_C_Order_AddDiscountCompensationLine_refreshAllAfterExecution.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719030_C_OrderLine_ManualCompensationLinePosition.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719040_sysconfig_ManualCompensationLinePosition.sql
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/Group.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLine.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLineCreateRequest.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLineCreateRequestFactory.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCreator.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/ManualCompensationLinePosition.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupCompensationUtils.java
- backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
- backend/de.metas.business/src/main/java/de/metas/order/process/C_Order_AddDiscountCompensationLine.java
https://github.com/metasfresh/metasfresh/issues/19018
> C_Order_AddDiscountCompensationLine: add manual compensation lines before all generated compensation lines

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5735620_AddPOSReport.sql
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/interceptor/DocOutboundProducerValidator.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_orgblock_small.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_payments.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pos/report_taxes.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_POS.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_POS_Payments.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5735530_sys_add_Docs_Sales_POS.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5735535_sys_add_Docs_Sales_POS_Payments.sql
- backend/de.metas.pos.base/src/main/java-gen/de/metas/pos/repository/model/I_C_POS_Order.java
- backend/de.metas.pos.base/src/main/java-gen/de/metas/pos/repository/model/X_C_POS_Order.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSOrderStatus.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSOrdersLoaderAndSaver.java
- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5735640_C_POS_Order_Processed.sql
- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5735641_C_POS_Order_Processed_migrate.sql
- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5735650_POS_PrintFormat.sql
- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5735651_C_POS_Order_docOutboundConfig.sql
Includes PRs:
* https://github.com/metasfresh/metasfresh/pull/19036
> Merge gray_knight_uat -> master

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/AccountSheet_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5735550_sys_gh19028_AccountSheet_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5735560_sys_gh19028_RV_AccountSheet_Report.sql
https://github.com/metasfresh/metasfresh/issues/19028
> Adding `Account Sheet` report (Kontenauszug)

- backend/de.metas.async/src/main/java/de/metas/async/service/AsyncBatchObserver.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSCashJournal.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSOrder.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSOrderProcessingServices.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSOrdersLoaderAndSaver.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSPayment.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSPaymentProcessingStatus.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/async/C_POSOrder_CreateInvoiceAndShipment.java
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/actionTypes.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/actions/orders.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/api/orders.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/api/products.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/CurrentOrderActions.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/reducers.js
- **AsyncBatchObserver: lower the logging level**
- **generate payments async**
- **frontend QA/cleanup**
- **FE: delete order line button**
> mobile POS: generate C_Payments async, button to delete POS order line, QA/cleanup

- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5735980_sys_gh19069_CallOrder_ContractTerms.sql
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/order/interceptor/OrderTest.java
https://github.com/metasfresh/metasfresh/issues/19069
> Set `Flatrate Conditions` to `NULL` for both `Purchase` and `Sales Order`

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/tree/spi/impl/MenuTreeSupport.java
(cherry picked from commit 846a7a8f6cc0ddf9c806b2e2dbbef26ae60fa73b) (cherry picked from commit fabfcea28e05870de29030765dfaee758f8c7d1e)
> Fix SQL syntax problem loading menu tree (#15470) (#18719)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_S.jrxml
> Update the layout of `HU QR Barcode Label`

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5736690_sys_gh19102_Invoice_IsEdiEnabled.sql
refs: https://github.com/metasfresh/metasfresh/issues/19102
> Show Checkbox "IsEdiEnabled" in Invoice Window

- backend/de-metas-salesorder/src/main/sql/postgresql/system/5736900_sys_gh19110_Error_Messages.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJob.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobCreateRepoHelper.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobAbortCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCompleteCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCreateCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/model/json/HUQRCodeJsonConverter.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingWFProcessStartParams.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWFProcess.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WFProcess.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/service/WorkflowRestAPIService.java
refs: https://github.com/metasfresh/metasfresh/issues/19110
> MobileUI Picking - User Error Handling

- backend/de-metas-salesorder/src/main/sql/postgresql/system/5736900_sys_gh19110_Error_Messages.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJob.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobCreateRepoHelper.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobAbortCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCompleteCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobCreateCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/model/json/HUQRCodeJsonConverter.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationService.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/PickingWFProcessStartParams.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWFProcess.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/WFProcess.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/service/WorkflowRestAPIService.java
refs: https://github.com/metasfresh/metasfresh/issues/19110
(cherry picked from commit 78e0a68347bfa397f0bc0d99ab133a062838814f)
https://github.com/metasfresh/metasfresh/pull/19112
> MobileUI Picking - User Error Handling (#19112)

- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/cash_journal/POSCashJournalClosingModal.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/CurrentOrder.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/CurrentOrder.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/GetCatchWeightModal.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/OrderLine.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/ProductButton.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/ProductButton.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/ProductSearchBar.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/ProductSearchBar.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/Products.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_summary/OrderSummary.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/payment_panel/CardPaymentDetailsModal.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/payment_panel/PaymentLine.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/select_order/SelectOrderModal.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/select_terminal/POSTerminalSelectModal.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/i18n/de.json
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/i18n/en.json
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/reducers/orders.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/reducers/posTerminal.js
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/utils/payments.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19156
*  https://github.com/metasfresh/metasfresh/pull/19144
*  https://github.com/metasfresh/metasfresh/pull/19139
*  https://github.com/metasfresh/metasfresh/pull/19121
*  https://github.com/metasfresh/metasfresh/pull/19109
*  https://github.com/metasfresh/metasfresh/pull/19099
> Merge gray_knight_uat -> master (2024-10-16)

- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5737240_trls.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/Header.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/GetCatchWeightModal.jsx
- **fix weight dialog**
- **logout header button**
- **trls**
> mobile POS - fix get weight dialog, logout button, trls

- backend/de.metas.pos.base/src/main/sql/postgresql/system/43-de.metas.pos/5737240_trls.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/Header.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/GetCatchWeightModal.jsx
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19178
> Merge gray_knight_uat -> master (2024-10-17)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Archive.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Doc_Outbound_Config_CC.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Archive.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Doc_Outbound_Config_CC.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocOutboundConfig.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocOutboundConfigCC.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocOutboundConfigRepository.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocOutboundConfigService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportResult.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/PrintFormatId.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/ArchiveRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/IArchiveBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/IArchiveDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5737120_Add_OverrideDocType.sql
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/DocOutboundUtils.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/DocOutboundCCWorkpackageProcessor.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/test/java/de/metas/document/archive/spi/impl/DefaultModelArchiverTest.java
- backend/de.metas.dunning/src/test/java/de/metas/document/archive/spi/impl/Dunning_DefaultModelArchiverTest.java
- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingDataFactory.java
PRs:
* https://github.com/metasfresh/metasfresh/pull/19152
* https://github.com/metasfresh/metasfresh/pull/19174
> Merge inner_silence_uat to master

- backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
- backend/de.metas.edi/src/main/java/de/metas/edi/process/EDI_Desadv_GenerateSSCCLabels.java
- backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
- backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/IPrintableDesadvLineSSCC18Labels.java
- backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/PrintableDesadvLineSSCC18Labels.java
> EDI_Desadv_GenerateSSCCLabels creates DESADV-Pack with Packagin-GTINs and -Codes

- backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/printingdata/PrintingData.java
refs: https://github.com/metasfresh/metasfresh/issues/19186
> fix duplicate printing

- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/OrderBOMLineQuantities.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPOrderBOMBL.java
refs: https://github.com/metasfresh/metasfresh/issues/19186
> don't update qtyPlan on pporder close

- backend/de.metas.business/src/main/java/de/metas/gs1/GS1Element.java
- backend/de.metas.business/src/main/java/de/metas/gs1/GS1Elements.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/mobileui/picking/MobileUI_Picking_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/picking/Pick_mixed_lines.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/picking/Pick_single_catch_weight_product.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/gs1/GS1HUQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/model/HUQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/model/HUQRCodeAttribute.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/model/IHUQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/HUQRCodesService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5737500_msg_QR_CODE_PRODUCT_ERROR_MSG.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJob_Scenarios_Test.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/gs1/GS1HUQRCodeTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/leich_und_mehl/LMQRCodeTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/service/HUQRCodesServiceTest.java
- misc/services/mobile-webui/mobile-webui-frontend/package.json
- misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/qrCode/hu.test.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/common.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/gs1.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/qrCode/hu.js
- misc/services/mobile-webui/mobile-webui-frontend/yarn.lock
* GS1 backend support
* hu.js: sync from master
* QA
* GS1 mobile UI frontend support
* fix cucumber tests
* fix cucumber tests
* PickingJobPickCommand: make sure GS1's product is matching
* cucumber test for picking using GS1 code
* improve unit tests
* QA/cleanup
* more unit tests
Fixed Conflicts:
backend/de.metas.business/src/main/java/de/metas/gs1/GS1Element.java
backend/de.metas.business/src/main/java/de/metas/gs1/GS1Elements.java
backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java …
> GS1 mobile UI support (#19192)

- misc/services/mobile-webui/mobile-webui-frontend/src/assets/index.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/assets/spinner.scss
- misc/services/mobile-webui/mobile-webui-frontend/src/components/Spinner.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
refs https://github.com/metasfresh/metasfresh/issues/19210
> prevent issue twice

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Product.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Product.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5737530_Improve_Import_Products.sql
- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/MProductImportTableSqlUpdater.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportContext.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportHelper.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcess.java
- backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductsCache.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
PRs:
* https://github.com/metasfresh/metasfresh/pull/19205
> Merging feisty_sloth_uat

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_details_v2.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5737820_sys_gh19231_Docs_Sales_InOut_Details.sql
https://github.com/metasfresh/metasfresh/issues/19231
> Show `LotNo` and `Best before date` on `Shipment Note`

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5737830_sys_gh19240_ScaleDeviceInvalidLocator.sql
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessor.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessorsList.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/DeviceConfig.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/SysConfigDeviceConfigPool.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ManufacturingJob.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaver.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaverSupportingServices.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
refs: https://github.com/metasfresh/metasfresh/issues/19240
> MobileUI Ensure correct scale

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_PaymentTerm.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_PaymentTerm.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Env.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5737840_sys_remove_IsAllowOverrideDueDate.sql
- backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_OverrideDueDate.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/IPaymentTermRepository.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestFixedDateInvoicedAndDateAcct.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestPaymentTermIdPriority.java
- backend/de.metas.util/pom.xml
- backend/de.metas.util/src/main/java/de/metas/util/Check.java
- misc/parent-pom/pom.xml
If there are two different overrideDueDates, take the later one. 
Also add a bit of `@Contract` and get rid of some annoying warnings
> Fix the invoicing problem related to override due date

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HURepository.java
refs: https://github.com/metasfresh/metasfresh/issues/19252
> weightNet aggregated TUs

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/ITrxManager.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/api/impl/IMPProcessorBL.java
- misc/dev-support/docker/infrastructure/env-files/intensive_care_uat.env
The fix is in `IMPProcessorBL.java` line 108.
I tested it locally
> Fix that IMP_ProcessorLogs were created with AD_Client_ID=0 so there was an ex when open ing detail view

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_details_footer.jrxml
https://github.com/metasfresh/metasfresh/issues/19250
> Add Incoterms to `Purchase Order` report footer

- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_I_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_I_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/InvoiceCandidateUpsertRequest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ManualCandidateService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/CInvoiceCandidateImportTableSqlUpdater.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/impexp/ImportInvoiceCandidatesService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5738200_sys_gh19262_I_Invoice_Candidate_M_PriceList_Version_Name.sql
refs: https://github.com/metasfresh/metasfresh/issues/19262
> Import Invoice Candidate External Reference Price List Version Name

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5737830_sys_gh19240_ScaleDeviceInvalidLocator.sql
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessor.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessorsList.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/DeviceConfig.java
- backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/SysConfigDeviceConfigPool.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/ManufacturingJob.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaver.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaverSupportingServices.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
refs: https://github.com/metasfresh/metasfresh/issues/19240 (cherry picked from commit e93994e1173fe70e7224b402392346451e144b0e)
> MobileUI Ensure correct scale (#19241)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_it_CH.properties
https://github.com/metasfresh/metasfresh/issues/19250
> Display incoterm in all report footer

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Ingredients.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Ingredients.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Ingredients.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Ingredients.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/product/M_Product_CopyTemplateCustomizer.java
> Merge to intensive_care_uat_update from other branches

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridField.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/Lookup.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookup.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupFactory.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/SupportInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/validationRule/IValidationRuleFactory.java
- backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/grid/ed/VLookup.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5738580_A_Depreciation_Entry_AD_Client_ID.sql
- **Preference: avoid throwing exception**
- **avoid mutating cached MLookupInfo instances**
- ** IValidationRuleFactory fix annotations (minor)**
- **make MLookupInfo completely immutable; remove GridFieldVO.InfoFactoryClass**
- **remove GridFieldVO.InfoFactoryClass (2) + cleanup around**
> Fix Swing Lookup showing nothing issue

- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobLoader.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobLoaderSupportingServices.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionRestService.java
refs: https://github.com/metasfresh/metasfresh/issues/19300
> distribution improvements

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
refs: https://github.com/metasfresh/metasfresh/issues/19306
> add support for unpicking to a destroyed CU

- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidate.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateProcessCommand.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateQuery.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateRepository.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/LiberoValidator.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order_BOMLine.java
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5738790_sys_gh19306_fix_referenced_column.sql
- backend/de.metas.manufacturing/src/test/java/org/eevolution/mrp/api/impl/MRPTestHelper.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/SupplyProposalEvaluator.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddordercandidate/DDOrderCandidateAdvisedHandler.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/ddordercandidate/DDOrderCandidateData.java
refs: https://github.com/metasfresh/metasfresh/issues/19306
> various distribution candidate fixes

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MProduct.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Order_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_InOut_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Invoice_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/updateM_Product_Acct.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5738640_FixZoomToForPakincgMaterial.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5738660_sys_Add_updateM_Product_Acct.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5738650_sys_AdjustPurchaseFunctions.sql
🍒 https://github.com/metasfresh/metasfresh/commit/43c71656cd6ce83702f3b8e45f8536070088adbe
* Add Vencodr Cusotymer no and fix updating accounting
* Update product accr from it's own product category acct
* Implement a way to update accouting all over
* CLean comments
* Fix script
* Fix update
* Update only the given product acct
* Add missing ")"
> Add Vendor Customer no and fix updating accounting (#19310)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MProduct.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/inout/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Order_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_InOut_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Invoice_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/updateM_Product_Acct.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5738640_FixZoomToForPakincgMaterial.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5738660_sys_Add_updateM_Product_Acct.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5738650_sys_AdjustPurchaseFunctions.sql
🍒 https://github.com/metasfresh/metasfresh/commit/43c71656cd6ce83702f3b8e45f8536070088adbe
> Various fixed to release

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/InvoiceCandidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/InvoiceCandidateRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ManualCandidateService.java
refs: https://github.com/metasfresh/metasfresh/issues/19320
> Import Invoice Candidate External Reference

- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/SepaUtils.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPACustomerDirectDebitMarshaler_Pain_008_003_02.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAMarshaler.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
* PRs:
- https://github.com/metasfresh/metasfresh/pull/19313
> Master merge inner silence uat 11 11 2024

- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobAbortCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/DDOrderService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderMoveScheduleService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/plan/DDOrderMovePlanCreateCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/plan/DDOrderMovePlanStep.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUQueryBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQueryBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/plan/generator/pickFromHUs/PickFromHUsGetRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/plan/generator/pickFromHUs/PickFromHUsSupplier.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/distribution/ddorder/movement/schedule/plan/DDOrderMovePlanCreateCommandTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUQueryBuilderTest.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/DDOrderLowLevelDAO.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/interceptor/DDOrderLowLevelInterceptors.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/interceptor/DD_OrderLine.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/interceptor/DD_OrderLine_PostMaterialEvent.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateAllocRepository.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateQuery.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateRepository.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DeleteDDOrderCandidateAllocQuery.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/material_dispo/interceptor/DD_Order_Candidate.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/LiberoValidator.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order_BOMLine.java
- backend/de.metas.manufacturing/src/test/java/org/eevolution/mrp/api/impl/MRPTestHelper.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/SupplyProposalEvaluator.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddorder/DDOrderDeletedEventHandler.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddordercandidate/DDOrderCandidateAdvisedHandler.java
- backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/SupplyProposalEvaluatorTests.java
refs: https://github.com/metasfresh/metasfresh/issues/19306
> various fixes in distribution order workflow

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/AdvancedSearchBPartnerProcessor.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/Document.java
* Error when searching PostFinance Partner refs: https://github.com/metasfresh/metasfresh/issues/19351
> Error when searching PostFinance Partner (#19352)

- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandDAO.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandDAO.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/ordercandidate/process/OLCandDeleteSelectedRecords.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5739690_sys_gh19370_Process_OLCandDeleteSelectedRecords.sql
refs: https://github.com/metasfresh/metasfresh/issues/19370
> Deletion of several lines in sales order disposition

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740160_sys_gh19387_BestBefore_ShipmentSchedule.sql
refs: https://github.com/metasfresh/metasfresh/issues/19387
> Show BestBefore in Shipment Schedule

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740240_sys_AddParametersToPaySelectionProcess.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/IPaySelectionUpdater.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/C_PaySelection_CreateFrom.java
* Add 2 new parameters to process C_PaySelection_CreateFrom
* Set validation rule for invoices
* Filter by org bank if was set
* Fix date to filter
> Add 2 new parameters to process C_PaySelection_CreateFrom (#19386)

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
PR:  https://github.com/metasfresh/metasfresh/pull/19408
> Merge inner_silence_hotfix

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_L_A4.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5740400_sys_gh19407_HU_QR_Barcode_Label_A4.sql
https://github.com/metasfresh/metasfresh/issues/19407
> HU QR Barcode Label in A4 format

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_L_A4.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5740400_sys_gh19407_HU_QR_Barcode_Label_A4.sql
https://github.com/metasfresh/metasfresh/issues/19407
> HU-Label in A4-Format

- frontend/src/__tests__/utils/dateHelpers.test.js
- frontend/src/components/widget/DateTime/DatePicker.js
- frontend/src/utils/dateHelpers.js
copied fixes from master, basically it contains
* https://github.com/metasfresh/metasfresh/pull/17287
* https://github.com/metasfresh/metasfresh/pull/17293
> webui: Fix DatePicker component (inner_silence_uat)

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19420
*  https://github.com/metasfresh/metasfresh/pull/19354
*  https://github.com/metasfresh/metasfresh/pull/19302
*  https://github.com/metasfresh/metasfresh/pull/19260
*  https://github.com/metasfresh/metasfresh/pull/19085
*  https://github.com/metasfresh/metasfresh/pull/19053
*  https://github.com/metasfresh/metasfresh/pull/19029
*  https://github.com/metasfresh/metasfresh/pull/18960
*  https://github.com/metasfresh/metasfresh/pull/18956
*  https://github.com/metasfresh/metasfresh/pull/18787
*  https://github.com/metasfresh/metasfresh/pull/18784
*  https://github.com/metasfresh/metasfresh/pull/18781
*  https://github.com/metasfresh/metasfresh/pull/18768
*  https://github.com/metasfresh/metasfresh/pull/18754
* …
> Merge inner_silence_uat -> master (2024-11-23)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingSlotService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJob.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobAbortCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/process/ClearPickingSlot.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/requests/ReleasePickingSlotRequest.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5740410_sys_gh19417_fix_release_slot_process.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5740440_sys_gh19417_add_error_message.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJobTestHelper.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJob_Scenarios_Test.java
refs: https://github.com/metasfresh/metasfresh/issues/19417
> MobileUI Picking does not show all products once the picking process was interrupted

- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5740500_sys_gh19433_Automatic_Modules_Tab.sql
refs: https://github.com/metasfresh/metasfresh/issues/19433
> Move the automatically created modular setting lines to a separate tab

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflowRestController.feature
https://github.com/metasfresh/metasfresh/issues/19417
> fix cucumber tests

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Order_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5740390_sys_gh19365_Docs_Sales_Order_Description.sql
https://github.com/metasfresh/metasfresh/issues/19365
> Update generic reports

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceReview.feature
..it also needs to work with not-yet-completed invoices
> Fix problem for API invoice review

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740640_Extend_Index_c_invoice_uc_externalId_org.sql
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/payment/JsonPaymentService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
- backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/v2/invoice/JsonInvoiceReviewUpsertItem.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceReview.feature
- backend/de.metas.util/src/main/java/de/metas/util/Check.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/SwaggerDocConstants.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonInvoicePaymentCreateRequest.java
- misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonPaymentAllocationLine.java
merging after inner_silence_hotfix_06 into inner_silence_uat
> merging after rollout inner_silence_hotfix_06 into inner_silence_uat

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5740770_sys_gh19476_UOMSymbol_Mandatory.sql
https://github.com/metasfresh/metasfresh/issues/19476
> Make UOM Symbol Field Mandatory

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/ExternalSystem_Config_LeichMehl_ProductMapping_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/ExternalSystem_Config_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pporder/PP_Order_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/pporder/exportPPOrderLeichMehl.feature
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config_LeichMehl.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config_LeichMehl_ProductMapping.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_LeichMehl.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_LeichMehl_ProductMapping.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemLeichConfigProductMappingQuery.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemLeichMehlConfigProductMappingRepository.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/leichmehl/ExportPPOrderToLeichMehlService.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/leichmehl/ExternalSystemLeichMehlConfig.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/leichmehl/PLUType.java
- backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5740740_sys_gh19473_CU_TU_PLU.sql
- backend/de.metas.externalsystem/src/test/java/de/metas/externalsystem/ExternalSystemConfigRepoTest.java
- backend/de.metas.externalsystem/src/test/java/de/metas/externalsystem/ExternalSystemLeichMehlConfigProductMappingRepositoryTest.java
- backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/ExternalSystemConfigRepoTest.snap
- backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/ExternalSystemLeichMehlConfigProductMappingRepositoryTest.snap
* PLU - Support TU Label and Scales refs: https://github.com/metasfresh/metasfresh/issues/19473
* PLU - Support TU Label and Scales refs: https://github.com/metasfresh/metasfresh/issues/19473
> PLU - Support TU Label and Scales (#19474)

- backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperEngine.java
refs: https://github.com/metasfresh/metasfresh/issues/19481
> Anpassung der Namen von PDF-Dateien

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_details.jrxml
https://github.com/metasfresh/metasfresh/issues/19483
> Adding `POReference` to `Open Items` Report

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ReportStarter.java
- backend/de.metas.global_qrcode.services/src/main/java/de/metas/global_qrcodes/service/CreatePDFCommand.java
- backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperEngine.java
refs: https://github.com/metasfresh/metasfresh/issues/19505
> Print Picking Slot QR Codes throws a NPE

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/shipping/model/I_M_ShippingPackage.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/shipping/model/X_M_ShippingPackage.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740950_sys_AddProcess_M_ShipperTransportation_AddShipments.sql
- backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_it_CH.properties
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipping/process/M_ShipperTransportation_AddShipments.java
PRs:
* https://github.com/metasfresh/metasfresh/pull/19494
* https://github.com/metasfresh/metasfresh/pull/19517
> Add Shipments in M_ShipperTransportation

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_footer.jrxml
> Add optional language parameter to `report.TaxNote` and `report.TextSnippet`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_footer.jrxml
> Add optional language parameter to `report.TaxNote` and `report.TextSnippet` functions

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_footer.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/TaxNote.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/TextSnippet.sql
> Update `report.TaxNote` and `report.TextSnippet` functions

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderIssueServiceProductCommand.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/PasswordGenerator.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/PasswordGeneratorTest.java
…r Line
refs: https://github.com/metasfresh/metasfresh/issues/19523
> Support RouterPassword without 1 in PP Order

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5741310_sys_gh19566_EDI_C_BPartner_Lookup_BPL_GLN_v.sql
refs: https://github.com/metasfresh/metasfresh/issues/19566
> fix EDI_C_BPartner_Lookup_BPL_GLN_v

- misc/services/mobile-webui/mobile-webui-frontend/src/assets/view-header.scss
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19555
> Merge gray_knight_uat -> master (2024-12-09)

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/autoapplyvalrule/ValRuleAutoApplier.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveBL.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19576
*  https://github.com/metasfresh/metasfresh/pull/19572
*  https://github.com/metasfresh/metasfresh/pull/19559
*  https://github.com/metasfresh/metasfresh/pull/19550
*  https://github.com/metasfresh/metasfresh/pull/19521
*  https://github.com/metasfresh/metasfresh/pull/19503
*  https://github.com/metasfresh/metasfresh/pull/19498
*  https://github.com/metasfresh/metasfresh/pull/19493
*  https://github.com/metasfresh/metasfresh/pull/19488
*  https://github.com/metasfresh/metasfresh/pull/19479
*  https://github.com/metasfresh/metasfresh/pull/19472
*  https://github.com/metasfresh/metasfresh/pull/19439
*  https://github.com/metasfresh/metasfresh/pull/19437
*  https://github.com/metasfresh/metasfresh/pull/19432
* …
> Merge new_dawn_uat -> master (2024-12-10)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5741410_sys_gh19584_Delete_Outdated_Period_Controls.sql
refs: https://github.com/metasfresh/metasfresh/issues/19566
> Delete Outdated Period Controls

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/product/M_Product_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/picking/Pick_single_catch_weight_product.feature
follow-up of 
* https://github.com/metasfresh/metasfresh/pull/19586
> cucumber test: Pick single catch weight product (EAN13)

- backend/de-metas-salesorder/src/main/sql/postgresql/system/5736900_sys_gh19110_Error_Messages.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5732810_sys_C_AcctSchema_GL_CashRounding_Acct_Masterdata.sql
- **fix failing migration script**
- **fix failing migration script**
> new dawn uat fixMigrationScripts

- backend/de.metas.acct.base/src/main/java/de/metas/acct/open_items/handlers/PaymentOIHandler.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/ICompositeQueryFilter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/IQueryBuilder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/CompositeQueryFilter.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/QueryBuilder.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/StringStartsWithFilter.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/dao/impl/StringStartsWithFilterTest.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/ean13/EAN13HUQRCode.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSProductsSearchCommand.java
- **IQueryBuilder.addStringStartsWith**
- **IProductBL.getProductIdByValueStartsWith**
- **POSProductsSearchCommand: handle EAN13**
> EAN 13 support in POS

- backend/de.metas.acct.base/src/main/java/de/metas/acct/open_items/handlers/PaymentOIHandler.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/ICompositeQueryFilterProxy.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/StringStartsWithFilter.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/dao/impl/StringStartsWithFilterTest.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/ean13/EAN13HUQRCode.java
- backend/de.metas.pos.base/src/main/java/de/metas/pos/POSProductsSearchCommand.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19608
*  https://github.com/metasfresh/metasfresh/pull/19606
*  https://github.com/metasfresh/metasfresh/pull/19605
*  https://github.com/metasfresh/metasfresh/pull/19602
*  https://github.com/metasfresh/metasfresh/pull/19599
*  https://github.com/metasfresh/metasfresh/pull/19597
*  https://github.com/metasfresh/metasfresh/pull/19586
*  https://github.com/metasfresh/metasfresh/pull/19581
> Merge new_dawn_uat -> master (2024-12-12)

- frontend/src/components/widget/List/RawList.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19612
*  https://github.com/metasfresh/metasfresh/pull/19275
*  https://github.com/metasfresh/metasfresh/pull/18170
*  https://github.com/metasfresh/metasfresh/pull/17607
*  https://github.com/metasfresh/metasfresh/pull/17584
*  https://github.com/metasfresh/metasfresh/pull/17583
*  https://github.com/metasfresh/metasfresh/pull/17420
*  https://github.com/metasfresh/metasfresh/pull/17413
*  https://github.com/metasfresh/metasfresh/pull/17130
*  https://github.com/metasfresh/metasfresh/pull/17109
> Merge hard_encoded_uat -> master (2024-12-12)

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5741780_M_ShipmentSchedule_Log_Created_fix_type.sql
fixes
* https://github.com/metasfresh/metasfresh/pull/19610
> M_ShipmentScheduleLog.Created: fix type (from time to timestamp)

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_inoutcandidate/M_ShipmentSchedule_logging_triggers.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5741560_M_ShipmentSchedule_logging.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19610
*  https://github.com/metasfresh/metasfresh/pull/19287
*  https://github.com/metasfresh/metasfresh/pull/19151
*  https://github.com/metasfresh/metasfresh/pull/19039
*  https://github.com/metasfresh/metasfresh/pull/19024
*  https://github.com/metasfresh/metasfresh/pull/19023
*  https://github.com/metasfresh/metasfresh/pull/19005
*  https://github.com/metasfresh/metasfresh/pull/18980
*  https://github.com/metasfresh/metasfresh/pull/18938
*  https://github.com/metasfresh/metasfresh/pull/18921
*  https://github.com/metasfresh/metasfresh/pull/18898
*  https://github.com/metasfresh/metasfresh/pull/18865
*  https://github.com/metasfresh/metasfresh/pull/18830
*  https://github.com/metasfresh/metasfresh/pull/18653
* …
> Merge vampire_textbook_uat -> master (2024-12-13)

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5741780_M_ShipmentSchedule_Log_Created_fix_type.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19646
> Merge vampire_textbook_uat -> master (2024-12-16)

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/ExplainedOptional.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/JavaProcess.java
- backend/de.metas.postfinance.base/src/main/java/de/metas/postfinance/docoutboundlog/PostFinanceLogRepository.java
- backend/de.metas.postfinance.base/src/main/java/de/metas/postfinance/document/export/PostFinanceExportException.java
- backend/de.metas.postfinance.base/src/main/java/de/metas/postfinance/document/export/PostFinanceYbInvoiceHandlerFactory.java
- backend/de.metas.postfinance.base/src/main/java/de/metas/postfinance/document/export/PostFinanceYbInvoiceService.java
- backend/de.metas.postfinance.base/src/main/java/de/metas/postfinance/document/export/impl/DunningPostFinanceYbInvoiceHandler.java
- backend/de.metas.postfinance.base/src/main/java/de/metas/postfinance/document/export/process/C_Doc_Outbound_Log_Export_To_Post_Finance.java
- backend/de.metas.postfinance.base/src/main/sql/postgresql/system/90-postfinance/5741600_sys_config_postFinanceInvoiceBatchSize_update.sql
- backend/de.metas.postfinance.base/src/main/sql/postgresql/system/90-postfinance/5741650_postfinance_org_config_unique_biller_id.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/invalidation/DocumentCacheInvalidationDispatcher.java
- backend/de.metas.util/src/main/java/de/metas/util/StreamUtils.java
- backend/de.metas.util/src/main/java/de/metas/util/collections/PeekIteratorWrapper.java
- backend/de.metas.util/src/test/java/de/metas/util/StreamUtilsTests.java
(cherry picked from commit de339ff2c68ad81e3c7de1fb2414b464c9d417aa)
> PostFinance Export reduce memory usage (#19613)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5741860_sys_gh19653_IsInvoiceEmailEnabled_Bpartner_Win.sql
https://github.com/metasfresh/metasfresh/issues/19653
> Shown `Invoice-Mail-Enabled` field in `BPartner` window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5741820_sys_gh19649_PackingMaterial_Win_Update.sql
> Make `Product` field Mandatory in `Packing Instruction` level

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5741860_sys_gh19653_IsInvoiceEmailEnabled_Bpartner_Win.sql
> Merging `vampire_textbook_uat`

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684560_sys_gh14602_MigrateInvoiceCandidates.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684561_sys_gh14602_MakePaymentTermMandatoryInInvoiceCandidates.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/IPaymentTermRepository.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTerm.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTermService.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermQuery.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
- backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/interceptor/C_OrderLine.java
- backend/de.metas.business/src/test/java/de/metas/payment/grossprofit/PaymentTermGrossProfitComponentTest.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeShopware6Action.java
- backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeShopwareService.java
- backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/PurchaseDemandWithCandidatesServiceTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inout/invoicecandidate/M_InOutLine_HandlerTest.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/AbstractICTestSupport.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/C_Invoice_Candidate_Builder.java
refs: https://github.com/metasfresh/metasfresh/issues/19648
> Port fix where C_Invoice_Candidate.C_Payment_Term_ID is made mandatory

- backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_Mass.java
Inspired by org.adempiere.ad.process.ProcessDocuments
> Run each org-change in its own trx

- backend/de.metas.edi/src/main/java/de/metas/edi/api/EDIDocOutBoundLogService.java
- backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Doc_Outbound_Log.java
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5741890_sys_C_Doc_Outbound_Log_EDI_Fields_Changes.sql
* C_Doc_Outbound_Log EDI Fields changes
* C_Doc_Outbound_Log EDI Fields changes
* change interceptor
* refactoring
* refactoring
* refactoring
* refactoring
> C_Doc_Outbound_Log EDI Fields changes (#19655)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUShipmentAssignmentBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentAssignmentBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOut.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_ShipmentSchedule.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/HUWithPickOnTheFlyStatus.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/PickingJobService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/ReopenPickingJobRequest.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobReopenCommand.java
https://github.com/metasfresh/metasfresh/issues/19686
> Reopen picking job on shipment void

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/commission/mediatedCommissionContract.feature
https://github.com/metasfresh/metasfresh/issues/19699
> Temporatily ignore cucumber due to missing C_Year 2026

- .mergify.yml
Reverts metasfresh/metasfresh#19379
> Revert "ci(mergify): upgrade configuration to current format"

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_qr.jrxml
https://github.com/metasfresh/metasfresh/issues/19714
> Update `report_qr.jrxml` (#19715)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742650_sys_gh19735_Next_Vs_AfterNext_Pricelist_Comparison_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742660_sys_gh19735_Next_Vs_AfterNext_Pricelist_Comparison_Report_With_PP_PI.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742670_sys_gh19735_Current_Vs_Next_Pricelist_Comparison_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742680_sys_gh19735_Current_Vs_Next_Pricelist_Comparison_Report_With_PP_PI.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742690_sys_gh19735_Current_Vs_Previous_Pricelist_Comparison_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742700_sys_gh19735_Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
https://github.com/metasfresh/metasfresh/issues/19735
> Make sure pricelist-comparison DB-functions are fixed

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742780_sys_gh19754_Imp_ProcessorLog_TextMsg_Filter.sql
https://github.com/metasfresh/metasfresh/issues/19754
> Allow to filter by `Imp_ProcessorLog.TextMsg` in `Import Prozessor Log` window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742790_sys_gh19760_Payment_Rule_Trl.sql
https://github.com/metasfresh/metasfresh/issues/19760
> Update Payment Rule Trl

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_CurrentVsLastPricelistComparison.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_CurrentVsNextPricelistComparison.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_NextVsAfterNextPricelistComparison.jrxml
https://github.com/metasfresh/metasfresh/issues/19735
> Update price list comparison reports

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5742840_sys_gh19769_fix_not_sent_yet_filter.sql
refs: https://github.com/metasfresh/metasfresh/issues/19769
> Not yet sent filter in EDI DESADV not working

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_description_bottom.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_details_footer.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_details_sum.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5742780_sys_gh19754_Imp_ProcessorLog_TextMsg_Filter.sql
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-leichundmehl/src/main/java/de/metas/camel/externalsystems/leichundmehl/to_leichundmehl/pporder/processor/file/FileUpdater.java
https://github.com/metasfresh/metasfresh/issues/19754
> Merging `new_dawn_uat`

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/order/CreatePurchaseCandidatesService.java
- backend/de.metas.business/src/main/java/de/metas/order/OrderLineBuilder.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java
- backend/de.metas.purchasecandidate.base/src/main/java-gen/de/metas/purchasecandidate/model/I_C_PurchaseCandidate.java
- backend/de.metas.purchasecandidate.base/src/main/java-gen/de/metas/purchasecandidate/model/X_C_PurchaseCandidate.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidate.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidateRepository.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/impl/PurchaseCandidateBL.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/PurchaseOrderPriceCalculator.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/PurchaseOrderPricingInfo.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactory.java
- backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remotepurchaseitem/PurchaseOrderItem.java
- backend/de.metas.purchasecandidate.base/src/main/sql/postgresql/system/5742770_sys_gh19759_C_PurchaseCandidate_Price_UOM_ID.sql
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
refs: https://github.com/metasfresh/metasfresh/issues/19759
> Bestelldispo: UOM conversion not used correctly for products where stock UOM != price UOM

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5742980_sys_gh19778_Periods_For_2026.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743100_sys_gh19778_Periods_For_2027.sql
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/mediatedCommissionContract.feature
refs: https://github.com/metasfresh/metasfresh/issues/19778
> Periods for 2026 and 2027

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5743170_sys_gh19784_C_Dunning_Candidate_POReference.sql
https://github.com/metasfresh/metasfresh/issues/19784
> Add SQL-Column `POReference` to `C_Dunning_Candidate` and filter by it

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Invoice.java
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5743240_sys_Adjust_taxaccounts_details.sql
PRs:
* https://github.com/metasfresh/metasfresh/pull/19774
* https://github.com/metasfresh/metasfresh/pull/19791
> Merging inner_silence_uat

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/sales_invoice_excel_report.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/rv_sales_invoice_report.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5741150_sys_Invoice_Report_ElementsAndTRLs.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743160_sys_Invoice_Report_Update_ReportAndFunction.sql
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/mediatedCommissionContract.feature
* additional column in sales invoice report
* qa
* Temporatily ignore failing cucumber (#19700)
https://github.com/metasfresh/metasfresh/issues/19699 (cherry picked from commit 97fc1ba6049fb6309818f54d773e0441853a0e9c) (cherry picked from commit 2eb851249d3edce6d4028c3661f6064684067c73)
---------
> additional columns in sales invoice report (#19786)

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5743240_sys_Adjust_taxaccounts_details.sql
PRs:
* https://github.com/metasfresh/metasfresh/pull/19774
* https://github.com/metasfresh/metasfresh/pull/19791
> Improve taxaccounts_details (#19791)

- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/remadvimport/ecosio/EcosioRemadvConstants.java
- misc/services/camel/de-metas-camel-edi/src/main/resources/application.properties
> change camel-EDI to use the v2-API when sending REMADVs

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/helper/BPartnerNameConsolidationHelper.java
- backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5743270_sys_gh19800_add_error_messages.sql
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/bpartner/BpartnerRestControllerTest.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/bpartner/MockedDataUtil.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/helper/BPartnerNameConsolidationHelperTest.java
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/BpartnerRestControllerTest.snap
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/REST_API_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV1.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2ErrorHandling.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/export/bpartnerExport.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/dataExportAudit.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/dataImport/importInvoiceCandidateExternalReference.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/externalsystem/rabbitmq/exportBPartnerToRabbitMQ.feature
refs: https://github.com/metasfresh/metasfresh/issues/19800
> Make sure Partner API enforces consistent company + partner names

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743330_sys_gh19807_DocType_Window.sql
refs: https://github.com/metasfresh/metasfresh/issues/19807
> Window Doctype - bring fields from advanced edit to first page

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743330_sys_gh19807_DocType_Window.sql
* Window Doctype - bring fields from advanced edit to first page refs: https://github.com/metasfresh/metasfresh/issues/19807
> Window Doctype - bring fields from advanced edit to first page (#19808)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/RemoveHUFromPickingSlotCommand.java
refs: https://github.com/metasfresh/metasfresh/issues/19830
> Fix release picking slot process

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743740_sys_gh19834_C_Invoice_OpenAmt_IsPartiallyPaid.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743850_sys_gh19834_C_Invoice_OpenAmt_IsPartiallyPaid.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
refs: https://github.com/metasfresh/metasfresh/issues/19834
> Add C_Invoice IsPartiallyPaid and OpenAmt

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743740_sys_gh19834_C_Invoice_OpenAmt_IsPartiallyPaid.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743850_sys_gh19834_C_Invoice_OpenAmt_IsPartiallyPaid.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
* Add C_Invoice IsPartiallyPaid and OpenAmt refs: https://github.com/metasfresh/metasfresh/issues/19834
> Add C_Invoice IsPartiallyPaid and OpenAmt (#19835)

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoicePaymentStatus.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
follow-up of https://github.com/metasfresh/metasfresh/pull/19835
> Invoice Partially Paid QA (iteration 2)

- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoicePaymentStatus.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
* Invoice Partially Paid QA (iteration 2)
> Invoice Partially Paid QA (iteration 2) (#19842)

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/M_CostDetail_v.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5743950_M_CostDetail_v.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5743980_M_CostDetail_v.sql
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/commission/mediatedCommissionContract.feature
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5743940_LagerwertReport_fixes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5743960_M_Cost_CostPrice_Function.sql
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19849
*  https://github.com/metasfresh/metasfresh/pull/19844
*  https://github.com/metasfresh/metasfresh/pull/19568
*  https://github.com/metasfresh/metasfresh/pull/19409
*  https://github.com/metasfresh/metasfresh/pull/18800
*  https://github.com/metasfresh/metasfresh/pull/18767
*  https://github.com/metasfresh/metasfresh/pull/18696
*  https://github.com/metasfresh/metasfresh/pull/18684
*  https://github.com/metasfresh/metasfresh/pull/18670
*  https://github.com/metasfresh/metasfresh/pull/18669
*  https://github.com/metasfresh/metasfresh/pull/18665
*  https://github.com/metasfresh/metasfresh/pull/18664
*  https://github.com/metasfresh/metasfresh/pull/18662
*  https://github.com/metasfresh/metasfresh/pull/18661
> Merge intensive_care_uat -> master (2025-01-19)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/RemoveHUFromPickingSlotCommand.java
refs: https://github.com/metasfresh/metasfresh/issues/19830
> Fix release picking slot process (#19831)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_L.jrxml
https://github.com/metasfresh/metasfresh/issues/19855
> Rename `Käserei-Nr` to `Lieferant-Nr.`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_it_CH.properties
https://github.com/metasfresh/metasfresh/issues/19867
> Update `fr_CH` `it_CH` for `Dunning` report

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/M_CostDetail_v.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5743950_M_CostDetail_v.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5744220_fix_trl.sql
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReference.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReferenceCollector.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReferenceQuery.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionMobileApplication.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionOrderCollector.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionRestService.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionWorkflowLaunchersProvider.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacet.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetGroupType.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetId.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetIdsCollection.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetsCollection.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetsCollector.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/QR_Label_L.jrxml
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/DDOrderService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/DDOrderQuery.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/DDOrderLowLevelDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
- backend/de.metas.util/src/main/java/org/adempiere/util/lang/ExtendedMemorizingSupplier.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/model/facets/WorkflowLaunchersFacetId.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersScreen.jsx
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19871
*  https://github.com/metasfresh/metasfresh/pull/19869
*  https://github.com/metasfresh/metasfresh/pull/19864
> Merge new_dawn_uat -> master (2025-01-21)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_InOut_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/fresh_Attributes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5744440_sys_gh19899_fresh_attributes_function.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5744450_sys_gh19899_Docs_Sales_InOut_Details_with_attributes_function.sql
- backend/de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/client/ReportsClient.java
This prevents the DB from doing a sequential scan on M_AttributeInstance
Refs https://github.com/metasfresh/metasfresh/issues/19899
> Improve performance by using attribute-DB-function instead of view

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/fresh_Attributes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/fresh_Attributes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5744440_sys_gh19899_fresh_attributes_function.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5744450_sys_gh19899_Docs_Sales_InOut_Details_with_attributes_function.sql
- backend/de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/client/ReportsClient.java
> Merge to master from origin/new_dawn_uat

- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersFilters.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/hooks/useQuery.js
follow-up of
* https://github.com/metasfresh/metasfresh/pull/19902
> bugfix/make sure mobile ui filter count is consistent (2)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/generate/HUMovementGenerator.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5744540_msg_HULocatorNotMatchingPickFromLocator.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/distribution/DistributionLinePickFromScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/distribution/DistributionLineScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
- **AdempiereException(AdMessageKey): consider userValidationError=true**
- **user friendly error message when scanned HU's locator does not match**
- **user friendly error message when scanned HU's product does not match**
> mobile UI distribution: improve error messages

- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersFilters.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/hooks/useQuery.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19908
*  https://github.com/metasfresh/metasfresh/pull/19900
*  https://github.com/metasfresh/metasfresh/pull/19898
> Merge new_dawn_uat -> master (2025-01-23)

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/APIRequest.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/APIResponse.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/RESTUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/REST_API_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Request_Audit_Log_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Request_Audit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Response_Audit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/ApiAuditFilter_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/context/TestContext.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/MobileDistribution_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/distribution/mobileDistribution.feature
follow-up of
* https://github.com/metasfresh/metasfresh/pull/19903
> Minimal mobile distribution cucumber testing (2)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details_hu.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details_hu_v2.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_details_v2.jrxml
PRs:
* https://github.com/metasfresh/metasfresh/pull/19912
> Merging vampire_textbook_uat

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5744570_sys_Fix_EDI_Cctop_INVOIC_v.sql
Also incorporate the version from new_dawn_uat into 5744570_sys_Fix_EDI_Cctop_INVOIC_v.sql
(cherry picked from commit 11d91962e7653c500864e720b42d76a9251be12a)
backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_v_view.sql
> Fix retrieving invoice's shipent_documentno (#19915)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/APIRequest.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/APIResponse.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/RESTUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/REST_API_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Request_Audit_Log_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Request_Audit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Response_Audit_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/ApiAuditFilter_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/context/TestContext.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/MobileDistribution_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/distribution/mobileDistribution.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/generate/HUMovementGenerator.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5744540_msg_HULocatorNotMatchingPickFromLocator.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/distribution/DistributionLinePickFromScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/distribution/DistributionLineScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_de.js
- misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations_en.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19910
*  https://github.com/metasfresh/metasfresh/pull/19906
> Merge new_dawn_uat -> master (2025-01-24)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_it_CH.properties
https://github.com/metasfresh/metasfresh/issues/19883
> Update `customerno` Trl like in metasfresh

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_it_CH.properties
https://github.com/metasfresh/metasfresh/issues/19883
> Update customerno Trl like in metasfresh

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5745040_sys_gh19940_Display_Destroyed_HUs.sql
refs: https://github.com/metasfresh/metasfresh/issues/19940
> Display Destroyed HUs

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report_it_CH.properties
https://github.com/metasfresh/metasfresh/issues/19883
> Update BP_Value DE Trl to `Kunde-Nr.`

- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/issue/RawMaterialsIssueOnlyWhatWasReceivedActivityHandler.java
refs: https://github.com/metasfresh/metasfresh/issues/19923
> Support issue only what was received together with manual issue

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IHUPPOrderQtyBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderQtyBL.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/issue/RawMaterialsIssueOnlyWhatWasReceivedActivityHandler.java
- backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/DraftPPOrderQuantities.java
https://github.com/metasfresh/metasfresh/issues/19960
> MobileUI: Issue only what was received adjustments

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/ITaxBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/TaxId.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxBL.java
> Remove old&faulty tax-lookup code (#19967)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745210_sys_gh19964_Update_AD_User_Fresh_xmas_Gift_List.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745230_sys_gh19964_BPartner_MaterialReceiptInfo.sql
https://github.com/metasfresh/metasfresh/issues/19964
> Update `AD_User` `C_BPartner` tables

- backend/de.metas.datev/src/main/java-gen/de/metas/datev/model/I_DATEV_Export.java
- backend/de.metas.datev/src/main/java-gen/de/metas/datev/model/X_DATEV_Export.java
- backend/de.metas.datev/src/main/java/de/metas/datev/DATEVExportLinesRepository.java
- backend/de.metas.datev/src/main/java/de/metas/datev/process/DATEV_ExportFile.java
- backend/de.metas.datev/src/main/sql/postgresql/system/5745220_sys_DATEV_ExportLine_Active_Editable.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5745250_sys_DATEV_Export_IsSOTrx.sql
- backend/de.metas.datev/src/main/sql/postgresql/system/5745280_sys_RV_DATEV_Export_Fact_Acct_Invoice_IsSOTrx.sql
* Datev Export Line IsActive Updateable
* Datev Export IsSOTrx
* Datev Export IsSOTrx
* Move IsActive field
* attempt to fix bean init failure
---------
> Accounting Export Extension (#19968)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745230_sys_gh19964_BPartner_MaterialReceiptInfo.sql
https://github.com/metasfresh/metasfresh/issues/19964
> Add SQL column to `M_ReceiptSchedule` table bring the bpartner's `MaterialReceiptInfo` value

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5745350_sys_gh18801_unaccent_string_function_fix_db_restore.sql
- frontend/src/assets/css/panel.scss
- frontend/src/assets/css/window-indicator.scss
- frontend/src/components/app/Modal.js
- frontend/start_dev.sh
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/confirmButton/ConfirmActivity.jsx
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/19995
*  https://github.com/metasfresh/metasfresh/pull/19993
*  https://github.com/metasfresh/metasfresh/pull/19977
*  https://github.com/metasfresh/metasfresh/pull/19974
*  https://github.com/metasfresh/metasfresh/pull/19907
> Merge new_dawn_uat -> master (2025-02-03)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745470_sys_gh19964_BPartner_MaterialReceiptInfo.sql
> `MaterialReceiptInfo` shall only be in the detail view and only displayed if not empty

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Field.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Field.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/compiere/grid/CTableColumns2GridTabSynchronizer.java
- backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/search/FindPanelSearchField.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_field_vt.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5745480_AD_Field.IsHideGridColumnIfEmpty.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5745500_ad_field_v.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/DefaultView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/IViewRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewResult.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewResultColumn.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewRowFieldNameAndJsonValues.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewBindingFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewGroupingBinding.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewRowFieldBinding.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/json/JSONViewResultColumn.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldWidgetType.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/sql/SqlDocumentFieldDataBindingDescriptor.java
- backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/window/descriptor/DocumentFieldWidgetTypeTest.java
- frontend/src/actions/TableActions.js
- frontend/src/utils/tableHelpers.js
- **use `@Getter`**
- **QA/cleanup**
- **implement**
> AD_Field.IsHideGridColumnIfEmpty

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/spreadsheet/excel/AbstractExcelExporter.java
- backend/de.metas.report/metasfresh-report-service/pom.xml
- backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/xls/engine/JXlsExporter.java
- backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/xls/engine/JexlCustomFunctions.java
- backend/pom.xml
- misc/services/camel/de-metas-camel-edi/pom.xml
- misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/excelimport/ExcelToMapListConverter.java
refs: https://github.com/metasfresh/metasfresh/issues/19990
> Upgrade POI from 3.15 to 4.1.2

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BP_Group.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_QuickInput.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_PaySelectionLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Payment_Reservation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/payment/PaymentRule.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Ebay_Mapping.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Shopware6Mapping.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745460_sys_gh19992_Update_PaymentRule_list.sql
- backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
- backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCandProcessor.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- backend/de.metas.vertical.creditscore/creditpass/src/main/java-gen/de/metas/vertical/creditscore/creditpass/model/X_CS_Creditpass_CP_Fallback.java
https://github.com/metasfresh/metasfresh/issues/19992
> Add `Reimbursement` `Settlement` options to `PaymentRule` list

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup/legacy/report.jrxml
- backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JRParametersCollector.java
- backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperEngine.java
refs: https://github.com/metasfresh/metasfresh/issues/20002
> Fix process "Bestellkontrolle zum Kunden Drucken"

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745820_sys_gh20015_Update_PP_Product_BOM_Name.sql
https://github.com/metasfresh/metasfresh/issues/20015
> Increase `Product BOM` name length

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BP_Group.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_QuickInput.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_PaySelectionLine.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Payment_Reservation.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/payment/PaymentRule.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Ebay_Mapping.java
- backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Shopware6Mapping.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5745460_sys_gh19992_Update_PaymentRule_list.sql
- backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
- backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCandProcessor.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- backend/de.metas.vertical.creditscore/creditpass/src/main/java-gen/de/metas/vertical/creditscore/creditpass/model/X_CS_Creditpass_CP_Fallback.java
> Merging `inner_silence_hotfix`

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746070_sys_gh20022_add_de_trls.sql
… de_DE
refs: https://github.com/metasfresh/metasfresh/issues/20022
> Add missing translations for Import/export price list schema line

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/ITaxBL.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/TaxNotFoundException.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxBL.java
CP of https://github.com/metasfresh/metasfresh/pull/20021
> Fix order callout

- backend/de.metas.manufacturing/src/main/java/org/eevolution/callout/PP_Product_Planning.java
refs: https://github.com/metasfresh/metasfresh/issues/20037
> Product planning - Set default value for product

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746200_sys_gh20002_Process_Trls.sql
refs: https://github.com/metasfresh/metasfresh/issues/20002
> Process trls

- backend/de.metas.manufacturing.webui/src/main/java/de/metas/manufacturing/webui/process/PP_Order_Candidate_SetStartDate.java
- backend/de.metas.manufacturing.webui/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5746320_sys_gh20048_PP_Order_Candidate_SetStartDate_Params.sql
- backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/ResourcePlanningPrecision.java
refs: https://github.com/metasfresh/metasfresh/issues/20048
> Manufacturing candidate set start date process parameters

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5746600_sys_gh20065_ShipmentDocumentNo_Exp_FormatLine.sql
refs: https://github.com/metasfresh/metasfresh/issues/20065
> Missing ShipmentDocumentNo for Desadv

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceAmtMultiplier.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceLine.java
- backend/de.metas.business/src/test/java/de/metas/remittanceadvice/RemittanceAdviceServiceTest.java
> Probable fix in C_RemittanceAdvice_CreateAndAllocatePayment#createPaymentAllocationPayableItem

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746790_sys_gh20059_DD_Order_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/20059
> `Distribution Order` window update

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_ShippingOrder_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_ShippingOrder_Root.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746980_sys_gh20089_Docs_Sales_ShippingOrder_Root.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746990_sys_gh20089_Docs_Sales_ShippingOrder_Details.sql
https://github.com/metasfresh/metasfresh/issues/20089
> Update `Transportation Order` report

- backend/de.metas.edi/src/main/java/de/metas/edi/process/export/impl/EDI_DESADVExport.java
CP of https://github.com/metasfresh/metasfresh/pull/20099
> propagate edi export status to shipments EDI_Exp_Desadv (#20099)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5747240_sys_gh20120_isActive_default_filter_WindowType_M.sql
refs: https://github.com/metasfresh/metasfresh/issues/20120
> Make isactive default filter in all windows of type M

- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5747230_sys_gh20125_showDemandDate_in_DDOrderCandidate.sql
- backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5747250_sys_gh20125_showDemandDate_In_DDOrder_And_ADMessage.sql
refs: https://github.com/metasfresh/metasfresh/issues/20125
> DD_Order Candidate: Inherit manufacturing start date & time

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/BasePLVProductsProposalViewFactory.java
(cherry picked from commit 11d339c79d06cae9067266e3f7d79f24be3da5dd)
> Add mandatory param LookupDataSourceFactory to ProductsProposalRowsLoader builder (#20135)

- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5747380_sys_gh20149_delete_C_OLCand_IsImportedWithIssues.sql
refs: https://github.com/metasfresh/metasfresh/issues/20149
> Also take care of the private repos

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_v2.jrxml
https://github.com/metasfresh/metasfresh/issues/20159
> Fix `Product name` in `Sales invoice` report

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceAmtMultiplier.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceLine.java
- backend/de.metas.business/src/test/java/de/metas/remittanceadvice/RemittanceAdviceServiceTest.java
Reverts metasfresh/metasfresh#20067
This was not the fix
> Revert "Probable fix in C_RemittanceAdvice_CreateAndAllocatePayment#createPaymentAllocationPayableItem"

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5747700_sys_gh20163_Replenishment_Window.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5747770_sys_gh20163_Replenishment_Window.sql
- backend/de.metas.business/src/main/java/de/metas/material/replenish/ReplenishInfo.java
- backend/de.metas.business/src/main/java/de/metas/material/replenish/ReplenishInfoRepository.java
- backend/de.metas.business/src/main/java/de/metas/replenishment/I_M_Material_Needs_Planner_V.java
- backend/de.metas.business/src/main/java/de/metas/replenishment/X_M_Material_Needs_Planner_V.java
- backend/de.metas.business/src/main/sql/postgresql/ddl/views/M_Material_Needs_Planner_V.sql
- backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5747700_sys_gh20163_M_Material_Needs_Planner_V.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/process/WEBUI_M_Replenish_Add_Update_Demand.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5747940_sys_gh20163_M_Replenish_Add_Update_Demand.sql
refs: https://github.com/metasfresh/metasfresh/issues/20163
> Replenishment window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_fr_FR.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Dunning_Report_description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getPartnerExternalID.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5747530_sys_gh20161_getPartnerExternalID.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5747540_sys_gh20161_Docs_Sales_Dunning_Report_description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5747820_sys_gh20167_Update_SalesOrder_Window.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5747840_sys_gh20167_Update_SalesInvoice_Window.sql
- https://github.com/metasfresh/metasfresh/issues/20161
- https://github.com/metasfresh/metasfresh/issues/20167
> `Dunning` report, `Sales Order` and `Sales Invoice` windows update

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterParam.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/sql/SqlDefaultDocumentFilterConverter.java
- backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/document/filter/sql/SqlDefaultDocumentFilterConverterTest.java
fixes
* https://github.com/metasfresh/metasfresh/pull/20177
> Fix between filtering when value is null and valueTo is not null

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_details_sum.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5747540_sys_gh20161_Docs_Sales_Dunning_Report_description.sql
https://github.com/metasfresh/metasfresh/issues/20161
> Add `External references` to `Dunning Report`

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidateSaver.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocumentNotAllocatedException.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationService.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationServiceTest.java
- backend/de.metas.business/src/main/java/de/metas/allocation/api/C_AllocationLine_Builder.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceAmtMultiplier.java
- backend/de.metas.business/src/main/java/de/metas/payment/PaymentId.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceLine.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceRepository.java
- backend/de.metas.business/src/test/java/de/metas/remittanceadvice/RemittanceAdviceServiceTest.java
❗ sorry about the branch name ❗ 
It's branched from `intensive_care_hotfix`
> fix REMADV-Allocation Bug

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5748070_sys_gh20199_SalesInvoice_Window.sql
ref: https://github.com/metasfresh/metasfresh/issues/20199
> Sales invoice window - remove white stripe from header

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediExport.feature
- backend/de.metas.edi/src/main/java/de/metas/edi/process/export/impl/EDI_DESADVExport.java
- backend/de.metas.edi/src/main/java/de/metas/edi/process/export/impl/EDI_DESADV_InOut_Export.java
refs: https://github.com/metasfresh/metasfresh/issues/20183
> Don't set SendingStarted for desadv edi exports.

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidateSaver.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocumentNotAllocatedException.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationService.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationServiceTest.java
- backend/de.metas.business/src/main/java/de/metas/allocation/api/C_AllocationLine_Builder.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceAmtMultiplier.java
- backend/de.metas.business/src/main/java/de/metas/payment/PaymentId.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceLine.java
- backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceRepository.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/inoutcandidate/OrderLineShipmentScheduleHandler.java
> Merge to new_dawn_uat from origin/intensive_care_hotfix

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_commission_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_commission_sum.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/commission/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Commission_Calculation.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748200_sys_gh20195_Docs_Purchase_Commission_Calculation.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748230_sys_gh20195_Commission_Calculation_Process.sql
https://github.com/metasfresh/metasfresh/issues/20195
> New `Commission Calculation - Provisionsberechnung` Report

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748250_sys_gh20167_Update_SalesInvoiceCandidates_Window.sql
https://github.com/metasfresh/metasfresh/issues/20167
> Add `Sales partner` to `Sales Invoice Candidates` grid view

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediExport.feature
- backend/de.metas.edi/src/main/java/de/metas/edi/process/export/impl/EDI_DESADVExport.java
- backend/de.metas.edi/src/main/java/de/metas/edi/process/export/impl/EDI_DESADV_InOut_Export.java
This reverts commit 727401972ffe4995c48234b367e101dda608e1cf.
> Revert "Don't set SendingStarted for desadv edi exports. (#20182)"

- backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5747720_cli_C_Order_C_DocType_ProformaInvoice.sql
> Add a a doctype for C_Order that is a non-binding proposal, but spells `Proforma-Invoice`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_it_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getPartnerExternalID.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5747530_sys_gh20161_getPartnerExternalID.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748310_sys_gh20218_OpenItems_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748320_sys_gh20218_OpenItems_Report_Details.sql
> Update `Open Items` Report

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748420_sys_gh20232_Job_Positions_Windows.sql
https://github.com/metasfresh/metasfresh/issues/20232
> `Position` and `Position Category` windows

- frontend/src/components/widget/WidgetRenderer.js
issue introduced by
* https://github.com/metasfresh/metasfresh/commit/020f8b6858c92dca67c00048579ea30dda9cd609
> Fix editing Amount not working

- frontend/src/components/widget/WidgetRenderer.js
cherry-pick
* https://github.com/metasfresh/metasfresh/pull/20237
> Fix editing Amount not working (cherry-pick to inner_silence_uat)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_description.jrxml
https://github.com/metasfresh/metasfresh/issues/20253
> Manage display `Billing Address` in `Purchase Invoice` report

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_description.jrxml
https://github.com/metasfresh/metasfresh/issues/20253
> Manage display `Billing Address` in `Purchase Order` report

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/notification/UserNotificationDetailMessageFormat.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openitems/report_it_CH.properties
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/Document.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentSaveStatus.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20264
*  https://github.com/metasfresh/metasfresh/pull/20261
*  https://github.com/metasfresh/metasfresh/pull/20265
> Merge new_dawn_uat -> master (2025-03-06)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748710_sys_gh20280_BPartner_CustomerNoAtVendor.sql
https://github.com/metasfresh/metasfresh/issues/20280
> Add `Customer No At Vendor` to `Business Partner` window

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/qrcode/LocatorQRCode.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderMoveScheduleService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderUnpickCommand.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/dialogs/UnpickDialog.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/distribution/DistributionStepScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/picking/PickingJobStepScreen.js
https://github.com/metasfresh/metasfresh/issues/20262
> Reuse MoveHUCommand for putting back HUs to initial locator

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/composite/BPartnerBankAccount.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPBankAccountDAO.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/JsonRetrieverService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/ChangeLogUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BP_BankAccount_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/dataImport/importBusinessPartner.feature
- misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/request/JsonRequestBankAccountUpsertItem.java
- misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/response/JsonResponseBPBankAccount.java
refs: https://github.com/metasfresh/metasfresh/issues/20286
> Expose Partner Bank Account Address via API

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/qrcode/LocatorQRCode.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5748750_mobileUI_picking_trls.sql
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/rest_api/JsonDistributionEvent.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionEventProcessCommand.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJob.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobLine.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5748710_sys_gh20280_BPartner_CustomerNoAtVendor.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderMoveSchedule.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderMoveScheduleRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderMoveScheduleService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/distribution/ddorder/movement/schedule/DDOrderUnpickCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/MoveHUCommand.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5748740_sys_gh20262_only_tus_on_lus_err_msg.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/HUTestHelper.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUAssignmentBLTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inout/impl/DistributeAndMoveReceiptCreatorTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/receiptschedule/impl/InOutProducerFromReceiptScheduleHUTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/tourplanning/integrationtest/HU_TourInstance_DeliveryDay_ShipmentSchedule_IntegrationTest.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/PickingMobileApplication.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/distribution.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/dialogs/UnpickDialog.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/distribution/DistributionLineScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/distribution/DistributionStepScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/picking/PickingJobStepScreen.js
- misc/services/mobile-webui/mobile-webui-frontend/src/api/distribution.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/distribution/DistributionStepScreen.jsx
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20291
*  https://github.com/metasfresh/metasfresh/pull/20285
*  https://github.com/metasfresh/metasfresh/pull/20281
*  https://github.com/metasfresh/metasfresh/pull/20263
> Merge new_dawn_uat -> master (2025-03-07)

- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
> Merge to new_dawn_uat from origin/soft_panda_hotfix

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_en_US.properties
https://github.com/metasfresh/metasfresh/issues/20304
> Missing `en_US` support in `Transport Order` report

- frontend/src/components/table/TableWrapper.js
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20303
*  https://github.com/metasfresh/metasfresh/pull/20296
*  https://github.com/metasfresh/metasfresh/pull/20247
*  https://github.com/metasfresh/metasfresh/pull/20231
*  https://github.com/metasfresh/metasfresh/pull/20222
> Merge inner_silence_uat -> master (2025-03-10)

- frontend/src/containers/DocumentList.js
fix issue introduced by
* https://github.com/metasfresh/metasfresh/pull/20164
> webui: View is not displayed if we are browsing a view and from menu we try to open another one

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5748940_sys_gh20320_EDI_Desadv_Window_Update.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5748950_sys_gh20320_EDI_DesadvLine_BKP.sql
- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5748960_sys_gh20320_EDI_DesadvLine_Update.sql
https://github.com/metasfresh/metasfresh/issues/20320
> `EDI_DesadvLine` table update

- backend/de.metas.business/src/main/java/de/metas/mforecast/ForecastDocumentHandler.java
- backend/de.metas.business/src/main/java/de/metas/mforecast/ForecastDocumentHandlerProvider.java
- backend/de.metas.business/src/main/java/de/metas/mforecast/IForecastDAO.java
- backend/de.metas.business/src/main/java/de/metas/mforecast/impl/ForecastDAO.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/forecast.feature
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/CandidateType.java
- backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/CandidateRepositoryWriteService.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/candidatechange/handler/CandidateHandlerUtil.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/foreacast/ForecastCreatedHandler.java
- backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/foreacast/ForecastDeletedHandler.java
- backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/MaterialEventHandlerRegistryTests.java
- backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/forecast/ForecastCreatedHandlerTest.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/MaterialEvent.java
- backend/de.metas.material/event/src/main/java/de/metas/material/event/forecast/ForecastDeletedEvent.java
- backend/de.metas.material/event/src/test/java/de/metas/material/event/MaterialEventSerializerTests.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_Forecast.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_ForecastEventCreator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_Forecast_PostMaterialEvent.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/material/interceptor/M_ForecastPostMaterialEventEventCreatorTest.java
https://github.com/metasfresh/metasfresh/issues/20344
> Support Reactivating, updating and Voiding a Forecast

- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReference.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReferenceCollector.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJob.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobLoader.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobLoaderSupportingServices.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionLauncherCaptionProvider.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionMobileApplication.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionRestService.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/ResourceInfo.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetGroupType.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetId.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetIdsCollection.java
- backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/facets/DistributionFacetsCollector.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/CreateMasterdataCommand.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/JsonCreateMasterdataRequest.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/JsonCreateMasterdataResponse.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/MasterdataContext.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/dd_order/DDOrderCommand.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/dd_order/JsonDDOrderRequest.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/dd_order/JsonDDOrderResponse.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/resource/JsonResourceRequest.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/resource/JsonResourceResponse.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/resource/ResourceCommand.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/DDOrderQuery.java
- backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/DDOrderLowLevelDAO.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
- backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/distribution.spec.js
https://github.com/metasfresh/metasfresh/issues/20335
> MobileUI: Show Plant & enable filers

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749240_sys_gh20325_Docs_Purchase_Commission_Forecast.sql
https://github.com/metasfresh/metasfresh/issues/20325
> New `Commission Forecast` Report

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Purchase_Commission_Forecast.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749000_sys_gh20325_Docs_Purchase_Commission_Forecast.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749020_sys_gh20325_Commission_Forecast_Process.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749190_sys_gh20325_Commission_Forecast_Elements.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749200_sys_gh20325_Commission_Forecast_Process.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749240_sys_gh20325_Docs_Purchase_Commission_Forecast.sql
https://github.com/metasfresh/metasfresh/issues/20325
> New `Commission Forecast - Provision Prognose` Excel export

- backend/de.metas.business/src/main/java/de/metas/banking/BankAccount.java
- backend/de.metas.business/src/main/java/de/metas/banking/api/BankAccountService.java
- backend/de.metas.business/src/main/java/de/metas/banking/api/impl/BPBankAccountDAO.java
- backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/AllAvailableSingletonServicesTest.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/impl/SEPADocumentBL.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPACustomerDirectDebitMarshaler_Pain_008_003_02.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPACustomerDirectDebitMarshaler_Pain_008_003_02Test.java
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
refs: https://github.com/metasfresh/metasfresh/issues/20353
> Bring Bank Account Address to SEPA File

- backend/de.metas.business/src/main/java/de/metas/banking/BankAccount.java
- backend/de.metas.business/src/main/java/de/metas/banking/api/BankAccountService.java
- backend/de.metas.business/src/main/java/de/metas/banking/api/impl/BPBankAccountDAO.java
- backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/AllAvailableSingletonServicesTest.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/SepaUtils.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/impl/SEPADocumentBL.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPACustomerDirectDebitMarshaler_Pain_008_003_02.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPACustomerDirectDebitMarshaler_Pain_008_003_02Test.java
- backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
* Bring Bank Account Address to SEPA File refs: https://github.com/metasfresh/metasfresh/issues/20353
> Bring Bank Account Address to SEPA File (#20356)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Generics_Org_Report.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/203670_sys_gh20367_Docs_Generics_Org_Report.sql
https://github.com/metasfresh/metasfresh/issues/20367
> Update `Docs_Generics_Org_Report` function

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_footer.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_de_DE.properties
https://github.com/metasfresh/metasfresh/issues/20370
> Report fixes

- backend/de.metas.acct.base/src/main/java/de/metas/acct/accounts/AccountProviderFactory.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/accounts/ProductAccountsRepository.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/accounts/ProductCategoryAccountsRepository.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/housekeeping/AddMissingAcctRecords.java
- backend/de.metas.acct.base/src/main/java/de/metas/acct/interceptor/C_AcctSchema.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/persistence/ModelDynAttributeAccessor.java
- backend/de.metas.business/src/main/java/de/metas/costing/CostingDocumentRef.java
- backend/de.metas.business/src/main/java/de/metas/costing/CurrentCost.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_Location_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_OrderLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRow.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/ItemFetcherExecutor.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefUtil.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/AccountingCucumberHelper.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/acctschema/C_AcctSchema_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/acctschema/C_AcctSchema_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/costing/M_CostDetail_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/costing/M_Cost_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/inventory/M_Inventory_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/match_po/M_MatchPO_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/match_po/M_MatchPO_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_Line_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/reverseMaterialReceipt.feature
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20341
*  https://github.com/metasfresh/metasfresh/pull/20336
*  https://github.com/metasfresh/metasfresh/pull/20329
> Merge new_dawn_uat -> master (2025-03-18)

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5749740_sys_Fix_AccountSheetReport.sql
PR:
- https://github.com/metasfresh/metasfresh/pull/20398
> Merge  soft_panda_hotfix

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5749740_sys_Fix_AccountSheetReport.sql
PR: https://github.com/metasfresh/metasfresh/pull/20398
> Merge new_daw_uat

- backend/de.metas.business/src/main/java/de/metas/quantity/StockQtyAndUOMQty.java
- backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java
- backend/de.metas.edi/src/test/java/de/metas/edi/api/impl/DesadvBL_addToDesadvCreateForInOutIfNotExist_Test.java
refs: https://github.com/metasfresh/metasfresh/issues/20411
> Fix min quantity for qtyCUsPerTopLevelHU

- backend/de-metas-salesorder/src/main/java/de/metas/salesorder/candidate/AutoProcessingOLCandService.java
- backend/de-metas-salesorder/src/main/java/de/metas/salesorder/service/AutoProcessingOrderService.java
- backend/de.metas.async/src/main/java/de/metas/async/AsyncBatchId.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/JsonShipmentService.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_TransportOrder_Details.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746990_sys_gh20089_Docs_Sales_TransportOrder_Details.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/InvoiceService.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java
* remove IInvoiceCandBL.setAsyncBatch
* QA/cleanup, preparing the ground for changes
* attempt to fix the deadlock
* fix typo
(cherry picked from commit d1d5f141b028b44fdb05e682054ac2f94b89ebd4)
Co-authored-by: Teo Sarca <teo.sarca@metasfresh.com>
(cherry picked from commit 90bf5bc4a0f7e32c5be13046159ae891e6c71d64)
backend/de-metas-salesorder/src/main/java/de/metas/salesorder/candidate/AutoProcessingOLCandService.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
> fix RecreateInvoiceWorkpackageProcessor DB deadlock (#16997) (#19271)

- backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5749850_sys_gh20419_EXP_Format_Update.sql
https://github.com/metasfresh/metasfresh/issues/20419
> `EDI Export Format` update

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749890_sys_gh20427_Update_HU_Editor_Window.sql
https://github.com/metasfresh/metasfresh/issues/20427
> Allow users to filter for `Destroyed` HUs in `Handling Unit Editor` Window

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeBL.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/DefaultPaymentBuilder.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/Accounting_Config.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/activity/C_Activity_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/activity/C_Activity_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/AllocatePayments_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/C_AllocationLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/payment/C_Payment_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/paymentterm/C_PaymentTerm_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/paymentterm/C_PaymentTerm_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/C_TaxCategory_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/project/C_Project_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/accounting/report_InventoryValue.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/paymentRules.feature
Retrofits 
* https://github.com/metasfresh/metasfresh/pull/20424
* after it was integrated to master: https://github.com/metasfresh/metasfresh/pull/20430
> Retrofit invoicePaymentAllocation.feature after integrating it to master

- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/format/ImpFormatColumnTest.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749980_sys_gh20456_Update_ImpFormat_Row_Date_Format.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749990_sys_gh20456_Update_ImpFormat_Row_Date_Format.sql
https://github.com/metasfresh/metasfresh/issues/20456
> Update all `AD_ImpFormat_Row.DataFormat` from `yyyy` to `yy`

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5750020_M_AttributeSet_IncludedTab.AD_Table_ID_reduce_eligible_values.sql
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20467
*  https://github.com/metasfresh/metasfresh/pull/20460
> Merge new_dawn_uat -> master (2025-03-27)

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/taxaccounts_perVATCode.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/taxaccountsonly_details.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5750300_ImproveTaxAccounting_v3_Functions.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting_v3/report_recap.jrxml
* Make sure we show transactions with no vat code
* Rewrite the where clause
* Show Text for no vat code
* Add total amount and tax amt in recep
* Improve tax accounting reports
> Improve tax accounting report v3 (#20477)

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/Workflow_RestController_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mobileui/manufacturing/Receive_with_CatchWeight.feature
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/model/FinishedGoodsReceiveLine.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaver.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobLoaderAndSaverSupportingServices.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/ManufacturingJobService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsCommand.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsRequest.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsResult.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/ManufacturingRestService.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/receive/MaterialReceiptActivityHandler.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/receive/json/JsonFinishedGoodsReceiveLine.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/rest_api/json/JsonManufacturingOrderEvent.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/manufacturing.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/receipt/MaterialReceiptLineScreen.js
- misc/services/mobile-webui/mobile-webui-frontend/src/actions/ManufacturingActions.js
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/manufacturing/receipt/MaterialReceiptLineScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/manufacturing/receipt/PickQuantityButton.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/manufacturing_receipt.js
refs: https://github.com/metasfresh/metasfresh/issues/20469
> MobileUI-Manufacturing: Receive with EAN-128 barcode

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750370_sys_gh20485_AD_Table_IsChangeLog_Y.sql
https://github.com/metasfresh/metasfresh/issues/20485
> Set `AD_Table.IsChangeLog` value as `Y` by default

- backend/de.metas.business/src/main/java/de/metas/mforecast/impl/ForecastService.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/process/WEBUI_M_Replenish_Generate_Forecasts.java
- backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5750350_sys_add_ForecastDocumentCompleted_AdMessage.sql
https://github.com/metasfresh/metasfresh/issues/20482
> Improvements for Forecast (Name & Notification)

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroup.feature
The imported cucumbers are linked to  https://github.com/metasfresh/metasfresh/commit/c9f090841159721f20f9cea335d06ec41376303e
> Added & adjusted missing cucumbers commented out in master previously

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5750870_sys_gh20518_Order_SalesRep_Filtering.sql
refs: https://github.com/metasfresh/metasfresh/issues/20518
> Order Sales Rep Filtering

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5750870_sys_gh20518_Order_SalesRep_Filtering.sql
refs: https://github.com/metasfresh/metasfresh/issues/20518
> Order Sales Rep Filtering (#20519)

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Attribute.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Attribute.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5750790_AddPrintValue_Override_to_M_attribute.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5750795_AddPrintValue_Override_to_Fresh_Attributes.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/fresh_Attributes.sql
* Add PrintValue_Override  to M_Attribute
* Add Print value Override in Fresh_attributes
* Treat blank case
* Use printvalue_override in general, not onlfor AdR
> Add print value override for fresh_attribute view (#20517)

- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
Reverts metasfresh/metasfresh#20484
> Revert "use the new method "Fact_Acct records are matching" in the cucumber"

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Allocation.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocBaseAndSubType.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/PaymentAllocationCriteria.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/PaymentAllocationPayableItem.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationAmounts.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidate.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidateSaver.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationService.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/AllocationAmountsTest.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceDocBaseType.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/AllocatePayments_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
Reverts metasfresh/metasfresh#20395
> Revert "Fix accounting for the case of API-ARC allocation"

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/shippingorder/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_TransportOrder_Description.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750810_sys_gh20515_Docs_Sales_TransportOrder_Description.sql
https://github.com/metasfresh/metasfresh/issues/20515
> Jasper Fixes

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5750990_Fact_Acct_EndingBalance_RebuildAll.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5751000_Fact_Acct_Summary_RebuildAll.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/compare_tables.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5751010_compare_tables.sql
- **de_metas_acct.Fact_Acct_EndingBalance_RebuildAll: do a backup before and after**
- **Fact_Acct_Summary_RebuildAll: do a backup before and after**
- **compare_tables: helper function to deep compare to tables (i.e. table snapshots)**
> Fact_Acct_Summary_RebuildAll, Fact_Acct_EndingBalance_RebuildAll: take a backup before and after to be able to compare the changes

- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/Document.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentSaveStatus.java
merging after soft_panda_hotfix_39 into new_dawn_uat
> merging after rollout soft_panda_hotfix_39 into new_dawn_uat

- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/DisplayValueProvider.java
PRs:
* https://github.com/metasfresh/metasfresh/pull/20532
> Merge intensive_care_release to new_dawn_uat

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/C_Invoice_Candidate_DeliveryStatus_Color_ID_Compute.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/C_Invoice_Candidate_InvoicingStatus_Color_ID_Compute.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750710_sys_gh20510_Invoice_Candidate_DeliveryStatusColor.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750740_sys_gh20510_Invoice_Candidate_InvoicingStatusColor.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750830_sys_gh20510_C_Invoice_Candidate_DeliveryStatus_Color_ID_Compute.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750840_sys_gh20510_SysConfig_Colors.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5750880_sys_gh20510_C_Invoice_Candidate_InvoicingStatus_Color_ID_Compute.sql
* https://github.com/metasfresh/metasfresh/issues/20510
* Introduce two `Color` Fields indicating the `Delivery Status` and the `Invoice Status` (#20511)
> Introduce two `Color` Fields indicating the `Delivery Status` and the `Invoice Status`

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking_Job.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking_Job.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/mobileui/MobileUIPickingUserProfileRepository.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5750575_sys_update_picking_job_warning_msg.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5751120_sys_add_AllowPartialJobsToBeCompleted_on_PickingOptions.sql
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/CompletePickingWFActivityHandler.java
https://github.com/metasfresh/metasfresh/issues/20479
> MobileUI Picking - fix picking line stauts

- backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/shippertransportation/ShipperDeliveryService.java
- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDraftDeliveryOrderCreator.java
- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
Also minor improvements in
- ShipperDeliveryService: get rid of warning
- DhlShipperGatewayClient: trimg address-strings
> DhlDraftDeliveryOrderCreator needs to create DeliveryPosition because that's what the repo can store

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Allocation.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRow.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRows.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefConstants.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefDataIdentifier.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/FactAcctLineMatcher.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/FactAcctMatchersFactory.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/FactAcctToTabularStringConverter.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/Fact_Acct_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/AllocatePayments_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/C_AllocationHdr_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PricingSystem_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
- backend/de.metas.util/src/main/java/de/metas/util/text/tabular/Row.java
- **fix/improve cucumber tests**
- **fix/improve cucumber tests**
- **fix accounting (wip)**
> API-ARC accounting (REMADV case)

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/util/lang/impl/TableRecordReference.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/AbstractProducerDestination.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/HUQRCodesService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/QRCodeConfigurationRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/QRCodeConfigurationService.java
https://github.com/metasfresh/metasfresh/issues/20563
> Bring One QR Code Feature to new dawn - Fix Issues

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5751660_sys_gh20566_FilterBy_Bpartner_Description.sql
https://github.com/metasfresh/metasfresh/issues/20566
> Search by `BPartner Description`

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Allocation.java
- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocBaseAndSubType.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/PaymentAllocationPayableItem.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidateSaver.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceDocBaseType.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java
- backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRow.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRows.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefConstants.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefDataIdentifier.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/FactAcctLineMatcher.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/FactAcctMatchersFactory.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/FactAcctToTabularStringConverter.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/accounting/Fact_Acct_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/AllocatePayments_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/C_AllocationHdr_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/allocation/C_AllocationLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PricingSystem_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/groupInvoiceCandidates.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoicePaymentAllocation.feature
- backend/de.metas.util/src/main/java/de/metas/util/text/tabular/Row.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20573
*  https://github.com/metasfresh/metasfresh/pull/20552
*  https://github.com/metasfresh/metasfresh/pull/20548
*  https://github.com/metasfresh/metasfresh/pull/20529
*  https://github.com/metasfresh/metasfresh/pull/20528
*  https://github.com/metasfresh/metasfresh/pull/20484
*  https://github.com/metasfresh/metasfresh/pull/20466
*  https://github.com/metasfresh/metasfresh/pull/20458
*  https://github.com/metasfresh/metasfresh/pull/20457
*  https://github.com/metasfresh/metasfresh/pull/20436
*  https://github.com/metasfresh/metasfresh/pull/20425
*  https://github.com/metasfresh/metasfresh/pull/20413
*  https://github.com/metasfresh/metasfresh/pull/20412
*  https://github.com/metasfresh/metasfresh/pull/20395
* …
> Merge intensive_care_hotfix -> intensive_care_release (2025-04-11)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5751970_sys_gh20592_Update_Weight_Fields_Product_Window.sql
https://github.com/metasfresh/metasfresh/issues/20592
> Update `Weight` fields in `Product` window

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/mm/attributes/AttributeCode.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeDAO.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
- backend/de.metas.business/src/test/java/org/adempiere/mm/attributes/api/impl/AttributeDAOTest.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/mediatedCommissionContract.feature
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/ExtractCounterAttributesCommand.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
- backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/MacAddressGenerator.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/MacAddressGeneratorTest.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/PasswordGeneratorTest.java
- backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/TestConstants.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
* Support Any Number of MAC Addresses refs: https://github.com/metasfresh/metasfresh/issues/20542
* https://github.com/metasfresh/metasfresh/pull/20579
> Support Any Number of MAC Addresses (#20543)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5752000_fix_AD_Element_Name_size.sql
Fixes issue introduced by 
* https://github.com/metasfresh/metasfresh/pull/20535
> Fix AD_Element's Name and PrintName size

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5752040_sys_gh20592_Update_Weight_Fields_Product_Window.sql
> Set `GrossWeight_UOM_ID` Default Value to `Kilogram`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5752070_sys_gh20614_GL_Distribution_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/20614
> `GL Distribution` window update

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5752100_sys_gh20618_EAN13_ProductCode_Filter.sql
refs: https://github.com/metasfresh/metasfresh/issues/20618
> Get Rid of EAN13 Facet Filter

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactGLDistributor.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5752070_sys_gh20614_GL_Distribution_Window_Update.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5752010_Packing_Instruction_Item_valRule.sql
https://github.com/metasfresh/metasfresh/issues/20614
> merge `soft_panda_hotfix` -> `new_dawn_uat`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5752130_sys_gh20592_Update_Weight_Fields_Product_Window.sql
> Rename `GrossWeight_UOM_ID` and adding weight validation rule

- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/MovingAverageInvoiceCostingMethodHandler.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/costing/inventory.feature
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20620
*  https://github.com/metasfresh/metasfresh/pull/20609
*  https://github.com/metasfresh/metasfresh/pull/20067
*  https://github.com/metasfresh/metasfresh/pull/20045
*  https://github.com/metasfresh/metasfresh/pull/19844
*  https://github.com/metasfresh/metasfresh/pull/19651
*  https://github.com/metasfresh/metasfresh/pull/19456
*  https://github.com/metasfresh/metasfresh/pull/19388
*  https://github.com/metasfresh/metasfresh/pull/19177
*  https://github.com/metasfresh/metasfresh/pull/19084
*  https://github.com/metasfresh/metasfresh/pull/18969
*  https://github.com/metasfresh/metasfresh/pull/18800
*  https://github.com/metasfresh/metasfresh/pull/18799
*  https://github.com/metasfresh/metasfresh/pull/18795
* …
> Merge intensive_care_hotfix -> intensive_care_release (2025-04-16)

- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/IDocOutboundDAO.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/DocOutboundDAO.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/sql/postgresql/system/5752170_sys_gh20632_DocOutbound_Log_Lines_DocStatus.sql
refs: https://github.com/metasfresh/metasfresh/issues/20632
> DocOutboundLog fix DocStatus of Voided/Reversed Documents

- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/IDocOutboundDAO.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/DocOutboundDAO.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java
- backend/de.metas.document.archive/de.metas.document.archive.base/src/main/sql/postgresql/system/5752170_sys_gh20632_DocOutbound_Log_Lines_DocStatus.sql
refs: https://github.com/metasfresh/metasfresh/issues/20632
> doc outbound log fix DocStatus of Voided/Reversed documents (#20633)

- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/MovingAverageInvoiceCostingMethodHandler.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/costing/inventory.feature
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20630
*  https://github.com/metasfresh/metasfresh/pull/20620
*  https://github.com/metasfresh/metasfresh/pull/20619
*  https://github.com/metasfresh/metasfresh/pull/20609
*  https://github.com/metasfresh/metasfresh/pull/20602
*  https://github.com/metasfresh/metasfresh/pull/20601
*  https://github.com/metasfresh/metasfresh/pull/20568
*  https://github.com/metasfresh/metasfresh/pull/20564
*  https://github.com/metasfresh/metasfresh/pull/20539
> Merge intensive_care_release -> new_dawn_uat (2025-04-16)

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidator.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IFactAcctListener.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IFactAcctListenersService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/FactAcctDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/FactAcctListenersService.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/DocTimingType.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20641
*  https://github.com/metasfresh/metasfresh/pull/20615
*  https://github.com/metasfresh/metasfresh/pull/20600
*  https://github.com/metasfresh/metasfresh/pull/20599
*  https://github.com/metasfresh/metasfresh/pull/20596
*  https://github.com/metasfresh/metasfresh/pull/20536
*  https://github.com/metasfresh/metasfresh/pull/20506
*  https://github.com/metasfresh/metasfresh/pull/20387
*  https://github.com/metasfresh/metasfresh/pull/20328
*  https://github.com/metasfresh/metasfresh/pull/20228
*  https://github.com/metasfresh/metasfresh/pull/20070
*  https://github.com/metasfresh/metasfresh/pull/19978
*  https://github.com/metasfresh/metasfresh/pull/19915
*  https://github.com/metasfresh/metasfresh/pull/19751
* …
> Merge soft_panda_hotfix -> new_dawn_uat (2025-04-17)

- backend/de.metas.shipper.gateway.dhl/src/main/sql/postgresql/system/99-de.metas.shipper.gateway.dhl/5752210_sys_gh20631_Dhl_ShipmentOrder_Log_Window.sql
https://github.com/metasfresh/metasfresh/issues/20631
> Enhance `DHL Delivery Order` Window - Reference related `DHL Delivery Order Log`

- backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDraftDeliveryOrderCreator.java
* DHL use a max weight
* DHL instead of summing up weights, use the last package's weight
> DHL use a max weight (#20622)

- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/picking/GetQuantityDialog.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
- **mobile UI - GetQuantityDialog: bugfix/make sure user is not able to press multiple times on the button**
- **mobile UI - GetQuantityDialog: bugfix/make sure user is not able to press multiple times on the button - playwright test**
> mobile UI - GetQuantityDialog: bugfix/make sure user is not able to press multiple times on the button - playwright test

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5752570_report_IventoryValue.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20666
*  https://github.com/metasfresh/metasfresh/pull/20662
*  https://github.com/metasfresh/metasfresh/pull/20654
*  https://github.com/metasfresh/metasfresh/pull/20653
*  https://github.com/metasfresh/metasfresh/pull/20652
*  https://github.com/metasfresh/metasfresh/pull/20651
*  https://github.com/metasfresh/metasfresh/pull/20650
*  https://github.com/metasfresh/metasfresh/pull/18624
*  https://github.com/metasfresh/metasfresh/pull/18596
*  https://github.com/metasfresh/metasfresh/pull/18595
*  https://github.com/metasfresh/metasfresh/pull/18561
*  https://github.com/metasfresh/metasfresh/pull/18559
*  https://github.com/metasfresh/metasfresh/pull/18536
*  https://github.com/metasfresh/metasfresh/pull/18490
* …
> Merge intensive_care_hotfix -> intensive_care_release (2025-04-23)

- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5752570_report_IventoryValue.sql
- misc/services/mobile-webui/mobile-webui-frontend/src/components/dialogs/GetQuantityDialog.jsx
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/20667
*  https://github.com/metasfresh/metasfresh/pull/20666
*  https://github.com/metasfresh/metasfresh/pull/20662
*  https://github.com/metasfresh/metasfresh/pull/20654
*  https://github.com/metasfresh/metasfresh/pull/20653
*  https://github.com/metasfresh/metasfresh/pull/20652
*  https://github.com/metasfresh/metasfresh/pull/20651
*  https://github.com/metasfresh/metasfresh/pull/20650
*  https://github.com/metasfresh/metasfresh/pull/18303
*  https://github.com/metasfresh/metasfresh/pull/18263
*  https://github.com/metasfresh/metasfresh/pull/18201
*  https://github.com/metasfresh/metasfresh/pull/18188
*  https://github.com/metasfresh/metasfresh/pull/18157
*  https://github.com/metasfresh/metasfresh/pull/18096
* …
> Merge intensive_care_release -> new_dawn_uat (2025-04-23)

- .github/workflows/cicd.yaml
added a map of branch names where we trigger the dispatch
> changed the secret for the CICD dispatch to a matching name

- .github/workflows/cicd.yaml
* changed the secret for the CICD dispatch to a matching name added a map of branch names where we trigger the dispatch
* added variables for cicd dispatch workflow file and repo
(cherry picked from commit 37e2d0f4be5225e69e639f49ae03474f282c5033)
> changed the secret for the CICD dispatch to a matching name (#20674)

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobQuery.java
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersScreen.jsx
- **Avoid NPE when picking job reference's delivery date is not available**
- **QA/cleanup**
> Avoid NPE when picking job reference's delivery date is not available

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5753410_sys_gh1282_Invoice_Table_Update.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5753420_sys_gh1282_Invoice_Candidate_Import_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/20746
> Update `Project` column in `Invoices` tables

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5753410_sys_gh1282_Invoice_Table_Update.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5753420_sys_gh1282_Invoice_Candidate_Import_Window_Update.sql
https://github.com/metasfresh/metasfresh/issues/20746
> merging `inner_silence_hotfix` -> `inner silence uat`

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/ICountryDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/CountryDAO.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/interfaces/I_C_BP_BankAccount.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/model/validator/C_BP_BankAccount.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPACustomerDirectDebitMarshaler_Pain_008_003_02.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
- backend/de.metas.payment.sepa/base/src/main/sql/postgresql/system/70-de.metas.payment.sepa/5753180_AddA_Country_ID_to_BankAccount.sql
* Don't use the bankAccount's A_Country, because we need an ISO-3166 in this field
* Test address
* Introduce A_Country_ID and validate A_Country to be a country code
* Set proper column name
* Take out country stuff from tests
* Take out wrong column
* Add new field to window
* Minor refactoring
* Minor: add some Nullable/NonNull declarations
* UPDATE cucumber and set country if was found
* Change label for A_Country
---------
> Make SURE c_bp_bankaccount.a_country contains all the time a valid country code

- backend/de.metas.business/src/main/java/org/eevolution/api/BOMComponentType.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/product/CreateProductCommand.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/product/JsonCreateProductRequest.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsCommand.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/playwright.config.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/manufacturing/manufacturing.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/manufacturing/receiving_by_products.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/ManufacturingJobScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/generateHUQRCodes/GenerateHUQRCodesConfirmScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/generateHUQRCodes/GenerateHUQRCodesScreen.js
- **introduce JsonCreateProductRequest.componentType**
- **ReceiveGoodsCommand: allow receiving to existing TU (needed at least for by-products)**
- **playwright: enable creating videos**
- **playwright: receiving_by_products.spec.js**
> mobile UI manufacturing: receive in same TU + playwright test

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5753690_err_MIXING_DIFFERENT_PRODUCTS_NOT_ALLOWED.sql
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/FrontendTestingRestController.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/AssertExpectationsCommand.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/AssertExpectationsCommandServices.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonExpectations.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonExpectationsResponse.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonHUExpectation.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonPickingExpectation.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonShipmentScheduleExpectation.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonShipmentScheduleQtyPickedExpectation.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/QtyAndUOMString.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/Identifier.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/MasterdataContext.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/storage/IHUStorage.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/storage/impl/HUStorage.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsCommand.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/manufacturing/receiving_by_products.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/Backend.js
follow-up of
* https://github.com/metasfresh/metasfresh/pull/20764
> mobile UI manufacturing: receive in same TU + playwright test (part 2)

- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/AssertExpectationsCommand.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/AssertExpectationsCommandServices.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonExpectations.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/expectations/request/JsonHUExpectation.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/job/service/commands/ReceiveGoodsCommand.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/manufacturing/receiving_by_products.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/manufacturing/receiving_by_products_catchweght.spec.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/ManufacturingJobScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/generateHUQRCodes/GenerateHUQRCodesConfirmScreen.js
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/manufacturing/receipt/MaterialReceiptLineScreen.js
- **ReceiveGoodsCommand: don't fail when receiving a co/by-product to a new TU with catch weight**
- **improve playwright testing**
- **receiving_by_products_catchweght.spec.js**
> mobile UI manufacturing: receive in same TU + playwright test (part 3)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/account_info/report.jrxml
https://github.com/metasfresh/metasfresh/issues/20749
> `Konten Information` report: Layout Adaptation

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5754400_sys_gh23356_Sales_Order_Window_Update.sql
https://github.com/metasfresh/me03/issues/23356
> `Sales Order` window update: Remove `Lieferberechtigung` field

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5754300_AddMessageForExportingSEPA.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5754540_sys_UpdatePaySelectionLineBankAccoount.sql
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/IPaySelectionBL.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/PaySelectionLineType.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionBL.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
- backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/api/impl/CreateSEPAExportFromPaySelectionCommand.java
PR: 
* https://github.com/metasfresh/metasfresh/pull/20807
* https://github.com/metasfresh/metasfresh/pull/20818
> Merge inner_silence_hotfix to uat

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5754820_sys_gh23380_Analysis_Report_Window_Update.sql
https://github.com/metasfresh/me03/issues/23380
> `Analysis Report` window update

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/backup_table.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/cleanup_backup_tables.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5754960_Adjust_Backup_Table_function_and_create_Cleanup_backup_Table_function.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5754990_sys_FindBackupTablesAndLogThem.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5754995_sys_SetUpASchedulerForCleaning_Fact_Acct_BackupTables.sql
PRs:
* https://github.com/metasfresh/metasfresh/pull/20831
> Merge soft_panda_hotfix -> new_dawn_uat

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Invoice.java
- backend/de.metas.acct.base/src/test/java/de/metas/acct/PostDocumentNow_ManualTest.java
- backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceDocBaseType.java
- **hotfix Vendor Credit Memo accounting**
- **PostDocumentNow_ManualTest: make it work**
> Hotfix vendor return invoice accounting

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/openpayments/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Report_PaySelection.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5756100_sys_AddFunction_Report_PaySelection.sql
PRs:
* https://github.com/metasfresh/metasfresh/pull/20881
> Merge inner_silence_hotfix to inner_silence_uat

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5756290_sys_gh23585_BankAccount_Update.sql
https://github.com/metasfresh/me03/issues/23585
> Make Bank account `QR-IBAN` mandatory when it's `ESR-Account`

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_QM_Analysis_Report.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_QM_Analysis_Report.java
- backend/de.metas.handlingunits.base/pom.xml
- backend/de.metas.qualitymgmt/pom.xml
- backend/de.metas.qualitymgmt/src/main/java/de/metas/qm/analysis/QMAnalysisReportDocumentHandler.java
- backend/de.metas.qualitymgmt/src/main/java/de/metas/qm/analysis/QMAnalysisReportDocumentHandlerProvider.java
- backend/de.metas.qualitymgmt/src/main/java/de/metas/qualitymgmt/analysis/QMAnalysisReportDocumentHandler.java
- backend/de.metas.qualitymgmt/src/main/java/de/metas/qualitymgmt/analysis/QMAnalysisReportDocumentHandlerProvider.java
- backend/metasfresh-dist/dist/pom.xml
- backend/pom.xml
https://github.com/metasfresh/me03/issues/23488
> `Analysis Report` to `Material Tracking Reference` link implementation

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5756680_sys_gh23619_Docs_Generic_BPartner_Report.sql
https://github.com/metasfresh/me03/issues/23619
> Update `de_metas_endcustomer_fresh_reports.Docs_Generics_BPartner_Report` function

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5757280_sys_gh23737_New_Forecast_Line_Window.sql
https://github.com/metasfresh/me03/issues/23737
> New `Forecast Line` window

- backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/product/CreateProductCommand.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/product/JsonCreateProductRequest.java
- backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/product/RandomProductValueGenerator.java
- backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/workflows_api/activity_handlers/receive/MaterialReceiptActivityHandler.java
- backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/ActualPickingWFActivityHandler.java
- backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/service/WFActivityHandler.java
- misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/picking/picking_catchWeight.spec.js
- misc/services/mobile-webui/mobile-webui-frontend/src/components/ScanHUAndGetQtyComponent.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
- misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses/picking.js
- **pick using custom QR code**
- **playwright test**
> mobile UI picking: pick using custom QR code format

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5757860_sys_gh23830_Sales_Order_Window_Update.sql
https://github.com/metasfresh/me03/issues/23830
> `Sales Order` Window update

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5641590_sys_gh13082_add_foodadvice_to_product.sql
File missing that causes science_vessel_uat_update to fail, file has been adapted to new_dawn_uat
> File missing that causes science_vessel_uat_update to fail

- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/OrderLineQuery.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderDAO.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/IContractChangeBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractChangeBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/ModularContractService.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/process/C_Order_OpenModularOrder.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5757910_add_modular_order_open_process.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_Order_ReceiptSchedule.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_Order_ShipmentSchedule.java
( Closing was mostly done in first iteration https://github.com/metasfresh/metasfresh/pull/20942 )
> Closing and Opening of modular contracts

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/get_table_id.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5758000_sys_gh23796_get_table_id_immutable.sql
* Make get_table_id DB function immutable
> Make get_table_id DB function immutable (#20972)

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5758550_M_Material_Needs_Planner_V_make_it_editable.sql
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/attributes_included_tab/AttributesIncludedTabDocumentsRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/adprocess/ADProcessParametersRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/process/MaterialNeedsPlannerRow.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/process/WEBUI_M_Replenish_Add_Update_Demand.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/process/WEBUI_M_Replenish_Generate_Forecasts.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/repository/MaterialNeedsRepositorySaver.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/DataTypes.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/decorator/IDocumentDecorator.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactorySupportingServices.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentsRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/IDocumentFieldView.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/save/CompositeSaveHandlers.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/save/DefaultSaveHandler.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/save/SaveHandler.java
- **implement support for plugable document save handlers**
- **Implement save support for M_Material_Needs_Planner_V**
> new dawn uat editableMaterialNeedsView

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/apirequest/request/ApiRequestAuditRepository.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5758490_t_query_selection_indices.sql
* Improve API_Audit_DeleteOldRecords
* Adjust t_query_selection indices
* QA
(cherry picked from commit 901d1b5e8d971700ed7e33820634dae8181d331b)
> CP - Improve API_Audit_DeleteOldRecords - Check oldest entries first (#20993)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5759350_sys_gh24065_Material_Tracking_Update.sql
https://github.com/metasfresh/me03/issues/24065
> `Material Tracking` window update

- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributesBL.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributesBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/materialtracking/spi/impl/attribute/MaterialTrackingAttributeValuesProvider.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/materialtracking/spi/impl/attribute/MaterialTrackingAttributeValuesProviderFactory.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/materialtracking/spi/impl/attribute/MaterialTrackingAttributeValuesProviderTest.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pattribute/ASIDescriptorFactory.java
- **IAttributesBL: QA**
- **IAttributesBL: QA**
- **ASIDescriptorFactory: if high-volume attribute use Lookup widget type**
> webui: High volume attributes shall pe rendered as Lookups; fixes for M_Material_Tracking_ID attribute

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5759830_sys_gh24135_SAP_GLJournal_Project.sql
https://github.com/metasfresh/me03/issues/24135
> Adding `Project` to `SAP GLJournal`

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
Included PRs:
*  https://github.com/metasfresh/metasfresh/pull/21047
*  https://github.com/metasfresh/metasfresh/pull/21046
*  https://github.com/metasfresh/metasfresh/pull/21044
*  https://github.com/metasfresh/metasfresh/pull/21010
*  https://github.com/metasfresh/metasfresh/pull/21004
*  https://github.com/metasfresh/metasfresh/pull/17660
*  https://github.com/metasfresh/metasfresh/pull/17659
*  https://github.com/metasfresh/metasfresh/pull/17657
*  https://github.com/metasfresh/metasfresh/pull/17656
*  https://github.com/metasfresh/metasfresh/pull/17653
*  https://github.com/metasfresh/metasfresh/pull/17652
*  https://github.com/metasfresh/metasfresh/pull/17650
*  https://github.com/metasfresh/metasfresh/pull/17616
*  https://github.com/metasfresh/metasfresh/pull/17600
* …
> Merge intensive_care_hotfix -> new_dawn_uat (2025-07-07)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5760200_sys_gh24127_C_Invoice_DocStatus.sql
https://github.com/metasfresh/me03/issues/24127
> Adding `DocStatus` as filter to `C_Invoice`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5760340_sys_gh24218_GLJournalLine_Project.sql
https://github.com/metasfresh/me03/issues/24218
> Adding `Project` to `SAP GLJournal Line`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_bp_org_block_left.jrxml
https://github.com/metasfresh/me03/issues/24273
> Increase org address width

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5760670_sys_gh24287_C_Order_CreatedBy_Update.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5760680_sys_gh24287_AD_User_CreatedBy_IsSystemUser_Index.sql
https://github.com/metasfresh/me03/issues/24287
> `Sales Order - Created By` update

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5760850_sys_gh24276_Purchase_Invoice_Window_Update.sql
https://github.com/metasfresh/me03/issues/24276
> Adding `View account` to `Purchase Invoice Line`

- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/restapi/GRSRestAPIRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-scriptedadapter/src/main/java/de/metas/camel/externalsystems/scriptedadapter/JavaScriptRepo.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-scriptedadapter/src/main/java/de/metas/camel/externalsystems/scriptedadapter/convertmsg/from_mf/MsgFromMfContext.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-scriptedadapter/src/main/java/de/metas/camel/externalsystems/scriptedadapter/convertmsg/from_mf/ScriptedAdapterConvertMsgFromMFRouteBuilder.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-scriptedadapter/src/test/java/de/metas/camel/externalsystems/scriptedadapter/convertmsg/from_mf/ScriptedAdapterConvertMsgFromMFRouteBuilderTests.java
- misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-scriptedadapter/src/test/resources/application.properties
Minor improvements done while concepting further issues
> externalsystems scriptedAdapter minor improvements

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5762660_sys_gh24697_Add_Costs_Process_Update.sql
https://github.com/metasfresh/me03/issues/24697
> `Add Costs` process update

- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_normal_UOM.feature
- backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Order.java
- backend/de.metas.edi/src/test/java/de/metas/edi/model/validator/C_Order_SetEdiEnabledForNewOrderTest.java
- misc/dev-support/docker/infrastructure/env-files/vampire_textbook_uat.env
> Merge to new_dawn_uat from origin/vampire_textbook_hotfix

- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/delivery/deliveryRules.feature
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/hu/huClearance/cleared/pick.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/process/M_ShipmentSchedule_EnqueueSelection.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_inoutcandidate/M_Packageable_v.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5770650_sys_gh25383_M_Packageable_v.sql
Fix M_Packageable_v and use the same EnqueuerQueryFilters
> Allow shipment-scheds with reverted shipment to be shipped again

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/picking/api/ShipmentScheduleAndJobScheduleIdSet.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/picking/M_Picking_Job_Schedule_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/picking/M_Picking_Job_Schedule_StepDefData.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workplace/C_Workplace_StepDef.java
- backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workplace/C_Workplace_StepDefData.java
- backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/jobSchedule.feature
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job_schedule/service/PickingJobScheduleService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/job_schedule/model/PickingJobScheduleCollection.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/picking/job_schedule/repository/PickingJobScheduleRepository.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingJobSchedule/process/PickingJobScheduleView_RemoveSchedule.java
- backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingJobSchedule/process/PickingJobScheduleView_Schedule.java
- **Invalidate shipment schedules on job schedules delete**
- **improve schedule/delete schedule processes**
- **cucumber test**
> Invalidate shipment schedules on job schedules delete; improve schedule/delete schedule processes; cucumber test

- backend/de.metas.report/metasfresh-report-service/pom.xml
merging after tenacious_d_hotfix_20 into tenacious_d_uat
> merging after rollout tenacious_d_hotfix_20 into tenacious_d_uat
