metasfresh/metasfresh

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java
https://github.com/metasfresh/metasfresh/issues/4507
> #4507 another bug repair

- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5501730_sys_gh4610_AddBillLocationAndUserOverride.sql
#4610 Billto Location and contact override in invoicecandidates
> #4610 Billto Location and contact override in invoicecandidates 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5501820_sys_gh4557_ShowMemoFields.sql
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerContactImportHelper.java
#4557 Improve BPartner Memo-Import
> #4557 Improve BPartner Memo-Import 

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5502130_sys_gh4625_FixReportOpenItems.sql
#4625 Open Items List Reference Date wrong parm
> #4625 Set the correct name

- de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/Candidate.java
- de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/TransactionDetail.java
- de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/candidate/businesscase/Flag.java
- de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/CandidateRepositoryRetrieval.java
- de.metas.material/dispo-commons/src/test/java/de/metas/material/dispo/commons/repository/CandidateRepositoryWriteServiceTests.java
- de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/TransactionEventHandler.java
- de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/TransactionCreatedHandlerTests.java
> #4628-app - Split material dispo for M_Transaction with different attributes

- de.metas.handlingunits.base/src/main/sql/postgresql/system/5502270_sys_gh4609_HUSysConfigs.sql
- de.metas.handlingunits.base/src/main/sql/postgresql/system/5502280_sys_gh4609_M_HU_LotNo_ColumnSQL.sql
https://github.com/metasfresh/metasfresh/issues/4609
> Gh4609  HUEditor-Tweaks

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5502630_sys_gh4665_AddvendorproductNo.sql
#4665 Show the Product No of Vendor in Purchase Order
> #4665 Add vendor product no

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/MimeType.java
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/product/process/ExportProductSpecifications.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5504100_sys_gh4582_ShowFields.sql
#4582 Excel Export and SQL for Product Specifications
> #4582 Excel Export and SQL for Product Specifications 

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java
#4696 Follow up #4552 AD_User is wrong in shipment schedule when using isDropShip
> #4696 Trigger validator when changing the contact

- de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5504470_sys_gh4640_MaterialCockpit_DisplayIncludedRows_sysconfing.sql
https://github.com/metasfresh/metasfresh/issues/4640
> #4640 option to not see included rows in material cockpit

- de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
https://github.com/metasfresh/metasfresh/issues/4644
> #4644 Repair docno update bug in order

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_container_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_details.jrxml
#4685 Order checkup with barcode report - add containers as separate fields
> #4685 Order checkup with barcode report - add containers as separate fields 

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java
#4696 Follow up #4552 AD_User is wrong in shipment schedule when using isDropShip
> #4696 Recreate delivery address also for sales orders and trigger validator also when location is changing

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5505080_sys_gh4662_MaterialCockpit_ProductCategorySysConfig_Name.sql
https://github.com/metasfresh/metasfresh/issues/4640
> #4640 Product category sys config had the wrong name

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/ADTableDAO.java
> #4719-app Allow AD_Val_Rule to be auto-applied on new record

- de.metas.business/src/main/java/de/metas/order/OrderLineRepository.java
#4732 Can not create a new order line using 'Add new'
> #4732 Can not create a new order line using 'Add new' 

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order.java
- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/api/IPPOrderDAO.java
- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/model/validator/PP_Order.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IPPOrderProductAttributeBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/PPOrderProductAttributeBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/maintenance/process/Fresh_08412_ProcessHUs.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/PP_Cost_Collector.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/HUPPOrderIssueReceiptCandidatesProcessor.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IHUPPOrderBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IHUPPOrderIssueProducer.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IHUPPOrderQtyDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/PPOrderPlanningStatus.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/CostCollectorCandidateCoProductHUProducer.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/CostCollectorCandidateFinishedGoodsHUProducer.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderIssueProducer.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderQtyDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/CreateDraftIssues.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/ReverseDraftIssues.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderIssueProducerTest.java
- de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/pporder/model/HUIssueModel.java
- de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/IPPOrderBOMDAO.java
- de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPOrderId.java
- de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPOrderBOMDAO.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1097
> metasfresh: "Issue only for what was received" method: Issued HUs remain issued and don't get destroyed 

- de.metas.business/src/main/java/de/metas/invoice/export/InvoiceExportService.java
- de.metas.business/src/main/java/de/metas/invoice/export/InvoiceToExportFactory.java
- de.metas.util/src/main/java/de/metas/util/Check.java
...with most "normal" invoices.
Instead of flagging the WP-processor as error, we just log the problem.
https://github.com/metasfresh/metasfresh/issues/4743
> #4743-app - C_Invoice_CreateExportData async WP processor has error..

- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/AbstractExcelExporter.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/ArrayExcelExporter.java
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/product/process/ExportProductSpecifications.java
#4582 Excel Export and SQL for Product Specifications
> #4582 Implemented exporting product specifications to excel file

- de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDescriptionBuilder.java
#4766 C_OrderLine: ProductDescription - don't add qty from BOM if is one
> #4766 Return empty string if qty is one

- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5506780_sys_gh4775-app_webui_orderline_show_dates.sql
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IPackingMaterialDocumentLine.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/AbstractPackingMaterialDocumentLine.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/AbstractPackingMaterialDocumentLinesBuilder.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUPackingMaterialDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUPackingMaterialDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/order/api/impl/OrderPackingMaterialDocumentLinesBuilder.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/order/api/impl/OrderPackingMaterialDocumentLinesBuilderTest.java
* the actual fix is in OrderPackingMaterialDocumentLinesBuilder
* add two unit tests
* also modernize HUPackingMaterialDAO
https://github.com/metasfresh/metasfresh/issues/4775
> package order line out of sync when order is reactivated and completed

- de.metas.adempiere.adempiere/base/src/test/java/de/metas/cache/interceptor/ClasspathCachedMethodsTester.java
- de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/modelvalidator/ClasspathAnnotatedModelInterceptorTester.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/AbstractAttributeValue.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/AbstractHUTest.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/attribute/storage/impl/HUAttributeStorage_generateInitialAttributes_Integration_Test.java
- de.metas.util/src/test/java/de/metas/util/AvailableSingletonServicesTester.java
because for sure there is a config issue.
In this way we will find out if some of the tests are not working correctly.
https://github.com/metasfresh/metasfresh/issues/4773
> if no classess found throw exception

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506640_sys_gh4764_Greetings_Trl_Window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506680_sys_gh4764_Greetings_Trl_Window_Improvements.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506690_sys_gh4764_Greetings_Trl_Translate_Client.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506710_sys_gh4764_Greetings_Trl_Delete_Greetings_Medium_Org.sql
https://github.com/metasfresh/metasfresh/issues/4764
> #4764 greetings trl window

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUStatusBL.java
- de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5506790_sys_gh4779-app_MD_Stock_From_HUs_V_consider_hu_status.sql
fix the view MD_Stock_From_HUs_V
https://github.com/metasfresh/metasfresh/issues/4779
> MD_Stock_Reset process includes planned HUs

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_BPartner.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506750_sys_gh4777_GLN_IN_I_BPartner.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506760_sys_gh4777_GLN_IN_I_BPartner_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506770_sys_gh4777_GLN_IN_I_BPartner_Window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506820_sys_gh4777_ExternalIds_In_BPartnerImport.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506830_sys_gh4777_ExternalIds_In_BPartnerImport_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506840_sys_gh4777_ExternalIds_In_BPartnerImport_Window.sql
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerContactImportHelper.java
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerImportHelper.java
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerImportTableSqlUpdater.java
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerLocationImportHelper.java
- de.metas.business/src/test/java/de/metas/bpartner/impexp/BPartnerImportTestHelper.java
https://github.com/metasfresh/metasfresh/issues/4777
> #4777 GLN in BPartner Import

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/FactAcctZoomProvider.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/GenericZoomProvider.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/RelationTypeZoomProvider.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/ZoomInfoFactory.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/IADWindowDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
* add internal names to our ZoomProviders
https://github.com/metasfresh/metasfresh-webui-api/issues/1111
> #1111-api - Include internalName in JSONReference

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507020_sys_gh4787_DocumentNote_Text_ProductTranslation.sql
https://github.com/metasfresh/metasfresh/issues/4787
> #4787 Document Note Text in Product Translation

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507040_sys_gh4789_C_BPartner_Filter_IsActive.sql
https://github.com/metasfresh/metasfresh/issues/4789
> #4789 IsActive filter in C_BPartner

- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributesKeys.java
- de.metas.material/cockpit/src/main/sql/postgresql/ddl/functions/GenerateHUAttributesKey.sql
- de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5507250_sys_gh4763-app_fix_GenerateHUAttributesKey.sql
solve two bugs:
1. in attributes key generation from M_HUs
2. in creating records when the MD_Stock record is missing
https://github.com/metasfresh/metasfresh/issues/4763
> Update material dispo correction from StockChangedEvents

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/process/rpl/exp/ExportHelper.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/NamePair.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/log/impl/EventLogLoggable.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/JavaProcess.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5506930_sys_AD_Scheduler_log_ordering.sql
- de.metas.async/src/main/java/de/metas/async/api/impl/WorkPackageBL.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_RefundConfig.java
- de.metas.contracts/src/main/java/de/metas/contracts/refund/CandidateAssignmentService.java
- de.metas.contracts/src/main/java/de/metas/contracts/refund/RefundConfig.java
- de.metas.contracts/src/main/java/de/metas/contracts/refund/RefundConfigRepository.java
- de.metas.contracts/src/main/java/de/metas/contracts/refund/interceptor/C_Invoice_Candidate_Manage_Refund_Candidates.java
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5507110_sys_gh4475_tweak_IC_webui_window.sql
- de.metas.contracts/src/test/java/de/metas/contracts/refund/RefundInvoiceCandidateServiceTest.java
- de.metas.util/src/main/java/de/metas/util/ConsoleLoggable.java
- de.metas.util/src/main/java/de/metas/util/ILoggable.java
- de.metas.util/src/main/java/de/metas/util/LoggableWithLogger.java
- de.metas.util/src/main/java/de/metas/util/NullLoggable.java
- de.metas.util/src/main/java/de/metas/util/PlainStringLoggable.java
- de.metas.util/src/main/java/org/adempiere/util/logging/LogbackLoggable.java
https://github.com/metasfresh/metasfresh/issues/4475
> Refund contract - add further options - fixes&tweaks

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/IQueryBuilder.java
- de.metas.order.rest-api/src/main/java/de/metas/order/rest/controller/SalesOrderRestController.java
- de.metas.ordercandidate.rest-api-impl/src/main/java/de/metas/ordercandidate/rest/BPartnerMasterDataProvider.java
https://github.com/metasfresh/metasfresh/issues/4802
> Required IfExists parameter 'ifBPartnersExist' is not present

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/GenericZoomProvider.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_sales_invoice_details_compensation_subgroup.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5507130_sys_gh4793_FixFunctionDocs_sales_invoice_details_compensation_subgroup.sql
#4793 View docs_sales_invoice_details_compensation_subgroup: the invoice detail shall be taken from invoice
> #4793 Take the details from invoice

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507430_sys_gh4787_Update_C_OrderLine_DocumentNote.sql
https://github.com/metasfresh/metasfresh/issues/4787
> #4787 update existing order lines with the document notes from products

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5507510_sys_gh4787_UseproperDocumentNote.sql
#4787 Product Document Note Translation
> #4787 Use M_Product_DocumentNote in sales order report

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/location/LocationId.java
- de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/AbstractDocOutboundDAO.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/ContactPerson.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/ContactPersonRepository.java
- de.metas.marketing/serialletter/src/main/java/de/metas/letter/interceptor/MKTG_ContactPerson.java
- de.metas.marketing/serialletter/src/main/java/de/metas/letter/process/C_Letter_CreateFrom_MKTG_ContactPerson.java
- de.metas.marketing/serialletter/src/main/java/de/metas/letter/service/async/spi/impl/C_Letter_CreateFromMKTG_ContactPerson_Async.java
- de.metas.marketing/serialletter/src/main/sql/postgresql/system/92-de.metas.marketing.serialletter/5507320_sys_gh4659-app_migration_2018-11-29_postgresql.sql
- de.metas.marketing/serialletter/src/main/sql/postgresql/system/92-de.metas.marketing.serialletter/5507350_sys_gh4659-app_migration_2018-11-29_postgresql.sql
* MKTG_ContactPerson's C_Location is now editable *if* there is no C_BPartner set
* MKTG_ContactPerson.AD_Language is editable via WebUI
* AD_User.AD_Language is also editable in the bpartner window (adv edit)
https://github.com/metasfresh/metasfresh/issues/4659#issuecomment-442050655
> #4659-app - Configurable Mailtext for Documents in DocOutbound

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_BPartner.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_BPartner.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507780_sys_gh4823_I_BPartner_URL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507790_sys_gh4823_I_BPartner_URL_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507800_sys_gh4823_I_BPartner_URL_Window.sql
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerImportHelper.java
https://github.com/metasfresh/metasfresh/issues/4823
> Gh4823 URL in Business Partner Import

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5507600_sys_gh4829_AddUQIndexForInternalNameInPriceList.sql
#4829 Add UQ index for InternalName and Price systme in Price list
> #4829 add uq index for InternalName in price list

- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5508490_cli_gh4837-app_add_C_Year_2019.sql
..if it doesn't yet exist
https://github.com/metasfresh/metasfresh/issues/4837
> Add fiscal year 2019 to our standard calendar

- de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
#4846  Contract extension does not set date correctly
> #4846  Contract extension does not set date correctly 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5509020_sys_gh4225-vendor-category-fix.sql
https://github.com/metasfresh/metasfresh/issues/4225
> Adjusts the vendor category field and translation #4225

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_OrgInfo.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_OrgInfo.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MOrg.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5509290_sys_gh4857-app_add_AD_OrgInfo_ID.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/OrgInfo.java
https://github.com/metasfresh/metasfresh/issues/4857
> 4857-app - Add PK column AD_OrgInfo_ID

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5509360_sys_gh4863-created-asynch-queue-filter.sql
Adds new Fields to asynch queue window. Adds new Filter for created filtering. New order by created desc.
https://github.com/metasfresh/metasfresh/issues/4863
> Add created/ updated to asynch workpackage and filter for created #4863

- de.metas.contracts/src/main/java/de/metas/contracts/refund/AssignmentToRefundCandidate.java
- de.metas.contracts/src/main/java/de/metas/contracts/refund/CandidateAssignmentService.java
- de.metas.contracts/src/main/java/de/metas/contracts/refund/RefundInvoiceCandidate.java
- de.metas.contracts/src/test/java/de/metas/contracts/refund/CandidateAssignmentServiceTest.java
solve a bug regarding aggregated refund candidates updating
https://github.com/metasfresh/metasfresh/issues/4475
> 4475-app - Refund contract - add further options

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5509740_sys_gh4873_Enlarge_Warehouse_Temperature_Field.sql
#4873  Product: The Temperature Field is too short
> #4873 Increase size for Warehouse_temperature column

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5509030_sys_gh4556-document-note-product.sql
https://github.com/metasfresh/metasfresh/issues/4556
> Adds the Documentnote to Product Pharma Window #4556

- de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5509900_sys_gh1945-frontend_add_about_messages.sql
add AD_Messages
* webui.window.about.caption
* webui.view.about.created
* webui.view.about.createdBy
* webui.view.about.updated
* webui.view.about.updatedBy
to be served by the i18n API endpoint
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1945
> 1945-frontend - "About" action in webui

- de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Order.java
https://github.com/metasfresh/metasfresh/issues/4820
> #4820 Repair bug

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5510050_sys_gh4764_Greetings_Translation_Reference.sql
https://github.com/metasfresh/metasfresh/issues/4764
> #4764  Reference Greetings Translations window  from Greetings

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/erptest.xml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5510590_sys_gh4896_Fix_tax_accounting_report.sql
#4896 Errors in Tax Codes Report
> #4896 Repair function

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/util/lang/impl/TableRecordReference.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5510880_sys_gh1134webui_WEBUI_BPartner_ProductsProposal_Launcher.sql
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1132
> gh1132webui_2

- de.metas.vertical.pharma/src/main/java-gen/de/metas/vertical/pharma/model/I_I_Pharma_Product.java
- de.metas.vertical.pharma/src/main/java-gen/de/metas/vertical/pharma/model/X_I_Pharma_Product.java
- de.metas.vertical.pharma/src/main/java/de/metas/impexp/product/PharmaProductImportProcess.java
#4909 Fix list values for IFA Product import
> #4909 Fix list values for IFA Product import 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5511030_sys_gh4911_BPartner_Labels_German.sql
https://github.com/metasfresh/metasfresh/issues/4911
> Gh4911 Name the bpartner label fields in German

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_PriceList_Version.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_PriceList_Version.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/DB.java
- de.metas.adempiere.adempiere/base/src/test/java/org/compiere/util/DBTest.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getPriceListVersionsUpToBase.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5510970_gh4906_M_PriceList_Version_FallbackToBasePriceListPrices.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5511480_sys_gh4908_adapt_val_rules.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5511489_sys_gh4908_getPriceListVersionsUpToBase.sql
- de.metas.business/src/main/java-legacy/org/compiere/process/M_PriceList_Create.java
- de.metas.business/src/main/java/de/metas/pricing/attributebased/impl/AttributePricing.java
- de.metas.business/src/main/java/de/metas/pricing/interceptor/M_ProductPrice.java
- de.metas.business/src/main/java/de/metas/pricing/rules/IPricingRule.java
- de.metas.business/src/main/java/de/metas/pricing/rules/PriceListVersion.java
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/ProductPriceQuery.java
- de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HUPIItemProductId.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pricing/spi/impl/HUPricing.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pricing/spi/impl/OrderLinePricingHUDocumentHandler.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pricing/spi/impl/OrderPricingHUDocumentHandler.java
- de.metas.util/src/main/java/de/metas/util/NumberUtils.java
https://github.com/metasfresh/metasfresh/issues/4906
> Pricing: fallback to base price list version if any

- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/model/MPPCostCollector.java
https://github.com/metasfresh/metasfresh/issues/4935
> MPPCostCollector: create M_Transaction on complete

- de.metas.adempiere.adempiere/base/pom.xml
https://github.com/metasfresh/metasfresh/issues/4936
> 4936-app - Use latest c3p0 and postgres driver

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/ArrayExcelExporter.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/process/ExportToExcelProcess.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512210_sys_gh4941_AD_Process_IsTranslateExcelHeaders.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512260_sys_gh4941_AD_Process_IsTranslateExcelHeaders_Description.sql
https://github.com/metasfresh/metasfresh/issues/4941
> AD_Process.IsTranslateExcelHeaders

- de.metas.adempiere.adempiere/base/src/test/java/de/metas/currency/AmountTest.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512310_sys_gh1132webui_processes.sql
- de.metas.business/src/main/java/de/metas/pricing/PriceListVersionId.java
- de.metas.business/src/main/java/de/metas/pricing/ProductPriceId.java
- de.metas.business/src/main/java/de/metas/pricing/interceptor/M_PriceList_Version.java
- de.metas.business/src/main/java/de/metas/pricing/service/CopyProductPriceRequest.java
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/PriceListsCollection.java
- de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/callout/OrderFastInput.java
- de.metas.util/src/main/java/de/metas/util/GuavaCollectors.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1132
> Gh1132webui 3

- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/api/PPOrderCost.java
- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/api/impl/CreatePPOrderCostsCommand.java
- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/costing/BOMLine.java
#1142 Make Issue CUs/TUs from Source HU work for Multi Select
> #1142 WIP: Comment out in order to complete manufactoring order

- de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5512460_sys_gh1142webui_HideParmeterWhenMultipleSelectionForIssueCUs.sql
Make Issue CUs from Source HU work for Multi Select
https://github.com/metasfresh/metasfresh-webui-api/issues/1142
> Hide parameter when multi select

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Tab.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Tab.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MTab.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/callout/AD_Column.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/ad_tab_v.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512600_sys_gh1146webui_AD_Tab_AllowQuickInput.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512601_sys_gh1146webui_AD_Tab_v.sql
- de.metas.adempiere.libero.libero/src/main/java/org/eevolution/form/VOrderPlanning.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1146
> Gh1146webui

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512820_sys_gh4859_Avg_Prices_With_PriceActual.sql
https://github.com/metasfresh/metasfresh/issues/4859
> #4859 Use PriceActual is AveragePrices

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513310_sys_gh1150webui_WEBUI_ProductsProposal_Delete.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513400_sys_gh1150webui_AD_Process_ShowHelp_default_N.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513401_sys_gh1150webui_AD_Process_ShowHelp_default_N_migrate.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513430_sys_gh1150webui_WEBUI_ProductsProposal_Delete_trls.sql
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1150
> Gh1150webui

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_DiscountSchemaBreak.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_DiscountSchemaBreak.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513440_sys_gh4976_M_DiscountSchemaBreak_PriceBase_not_mandatory.sql
https://github.com/metasfresh/metasfresh/issues/4976
> M_DiscountSchemaBreak.PriceBase shall be nullable

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5512240_sys_gh4922-user-job-filter.sql
https://github.com/metasfresh/metasfresh/issues/4922
> Adds new Filter for Job #4922

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/Amount.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/currency/AmountTest.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513470_sys_gh1152webui_IsCampaignPrice.sql
- de.metas.business/src/main/java/de/metas/money/Money.java
- de.metas.business/src/main/java/de/metas/money/MoneyService.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceService.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1152
> Gh1152webui

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513480_sys_gh976_FixMandatoryLogicForCurrencyAndBasePricingSystem_in_M_DiscountSchemaBreak.sql
#4976 M_DiscountSchemaBreak.PriceBase shall be nullable
> #4976 Fix mandatory logic for currency and basepricingsystem

- de.metas.contracts/src/main/java/de/metas/contracts/IContractsDAO.java
- de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractsDAO.java
- de.metas.contracts/src/main/java/de/metas/contracts/order/UpdateContractOrderStatus.java
- de.metas.contracts/src/main/java/de/metas/contracts/subscription/ISubscriptionBL.java
- de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
- de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/subscriptioncommands/ExtendContractOrder.java
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5513480_sys_gh4966_AddMesageForNotExtendingAnExtendedContract.sql
- de.metas.contracts/src/test/java/de/metas/contracts/order/ContractOrderTest.java
#4966 Prolonging contract does not working anymore
> #4966 Fix date

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MAttributeInstance.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/M_AttributeSetInstance_ID_AttributeInstances.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getC_BPartner_Product_Details.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5513740_sys_gh4987_RepairAttributeValueWhenValueTypeIsNumber.sql
#4987 M_Atribute_Value is not saved correctly
> #4987 M_Atribute_Value is not saved correctly 

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Label.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Certificate.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Label.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Certificate.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5510580_sys_gh5001_M_Product_Certificate_Table.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5510600_sys_gh5001_M_Product_Certificate_Table_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5513920_sys_gh5001_TransformLabelToTableM_Label.sql
#5001 Create a table for storing product certificate informations
> #5001 Create a table for storing product certificate informations 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5515060_sys_gh4959-app_AD_Message_Description.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/14.de.metas.dataentry/5515060_sys_gh4959-app_message.sql
* add generic AD_MEssage help text
* minor change to the CreatedUpdated AD_Message
https://github.com/metasfresh/metasfresh/issues/4959
> 4959-app - data entry implementation

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/impl/ModelCacheService.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/IModelTranslationMap.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/impl/ModelTranslation.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/impl/NullModelTranslationMap.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/po/POModelTranslationMap.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/po/POTrlRepository.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/IADTableDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/ADTableDAO.java
- de.metas.adempiere.adempiere/client/src/main/java/org/compiere/grid/ed/VAccountAutoCompleter.java
- de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5516190_sys_gh1167webui_DisableFullTextSearch_sysconfig.sql
- de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5516310_sys_gh1167webui_DefaultLookupSearchStartDelayMillis_sysconfig.sql
https://github.com/metasfresh/metasfresh-webui-api/issues/1167
> Gh1167webui

- de.metas.vertical.pharma/src/main/sql/postgresql/system/5516510_sys_gh5055_IFA_Fields_RO.sql
#5055 IFA fields shall be Readonly in Pharma Product window
> #5055 set RO proper fields

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/14.de.metas.dataentry/5516660_sys_gh5059-app_change_terminology.sql
Rename "Gruppe" => "Register, "Untergruppe" => "Unterregister", "Sektion" => "Feldgruppe" (same for en_US)
https://github.com/metasfresh/metasfresh/issues/5059
(cherry picked from commit 6bfab0cdfedf55d2f3c13f2eccb83d7004baec0e)
> 5059-app - DataEntry - change terminology

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Tab.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Tab.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/ad_tab_v.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517000_sys_gh1178webui_AD_Tab_IsRefreshViewOnChangeEvents.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517001_sys_gh1178webui_AD_Tab_v.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517020_sys_gh1178webui_C_Phonecall_Schedule_refreshViewOnChangeEvents.sql
https://github.com/metasfresh/metasfresh-webui-api/issues/1178
> Gh1178webui

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517230_sys_gh4951_Rename_Process_TRL_de_DE.sql
https://github.com/metasfresh/metasfresh/issues/4951
> #4951 make sure the right translations for processes are set for de_DE

- de.metas.vertical.pharma/pom.xml
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaOrderLineInputValidator.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaProduct.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaProductRepository.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaShipmentPermission.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/I_C_BPartner.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/interceptor/C_OrderLine.java
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5516830_sys_gh5071_ShipmentPermissionPharma_TypeC .sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517090_sys_gh5071_Add_ReceiptPermissionPharma_TypeC.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517130_sys_gh5071_Shipment-ReceiptPermissionPharma_TypeC_Translations.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517150_sys_gh5071_NoNarcoticsPermissionMessage 1.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517180_sys_gh5071_NoNarcoticsPermissionMessage 2.sql
- de.metas.vertical.pharma/src/test/java/de/metas/vertical/pharma/PharmaOrderLineInputValidatorTest.java
Implements:  https://github.com/metasfresh/metasfresh/issues/5071
> Gh5071: Don't allow narcotics in Trade Sales

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MScheduler.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517540_sys_gh5089-app_div_trl_descr_fixes.sql
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandCreateRequest.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceGenerator.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/InvoiceCandRecomputeTag.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/ICNetAmtToInvoiceChecker.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/DefaultAggregator.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLine.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLineAggregator.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoicesTest.java
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/sql/postgresql/system/75-vertical-healthcare_ch/5517490_sys_gh5089-app_DocSubType_Rechnung_Kanton.sql
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/sql/postgresql/system/75-vertical-healthcare_ch/5517500_cli_gh5089-app_DocType_Rechnung_Kanton.sql
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsService.java
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/resources/public_examples/md_440_tp_kvg_de.xml
> 5089-app - XML import/export for Kanton

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517710_sys_gh4951_PhonecallSchedule_WindowChanges.sql
- de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schedule_CreateSalesOrder.java
- de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schedule_MarkAsCalled.java
- de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schema_GenerateSchedules.java
https://github.com/metasfresh/metasfresh/issues/4951
> Gh4951 5 Phonecall Improvements

- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaCustomerPermission.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaCustomerPermissions.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaVendorPermission.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/PharmaVendorPermissions.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/I_C_BPartner.java
- de.metas.vertical.pharma/src/main/java/de/metas/vertical/pharma/model/interceptor/C_BPartner.java
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517670_sys_gh5095_AddBpartnerNarcoticsEditPermission_1.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517700_sys_gh5095_AddBpartnerNarcoticsEditPermission_2.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517760_sys_gh5095_AddBpartnerNarcoticsEditPermission_3.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517810_sys_gh5095_AddBpartnerNarcoticsEditPermission_4.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5517830_sys_gh5095_AddBpartnerNarcoticsEditPermission_5.sql
https://github.com/metasfresh/metasfresh/issues/5095
> Enable set/unset of BPartner narcotics pharma permission

- de.metas.vertical.pharma/src/main/sql/postgresql/system/5518680_sys_gh5095_ChangeAgainReceiptPermissionPharma.sql
https://github.com/metasfresh/metasfresh/issues/5095
> Change (again) ReceiptPermissionPharma TypeC DE translation

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Postal.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Postal.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/postal/impexp/PostalCodeImportProcess.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/postal/impexp/process/ImportPostalCode.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5517880_sys_gh5100_AustrianPostalCode_1.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518030_sys_gh5100_AustrianPostalCode_2.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518190_sys_gh5100_AustrianPostalCode_3.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518260_sys_gh5100_Deactivate_2_Duplicate_Postal_Codes.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518270_sys_gh5100_Create_UC_C_Postal.sql
- de.metas.business/src/main/java/org/adempiere/impexp/impl/ImportProcessFactory.java
Add the following
- process
- staging table
- webui window
- fix missing US translations
https://github.com/metasfresh/metasfresh/issues/5100
> Add importer for Austria postal code data

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518200_sys_gh5121_AddCompanyPhoneBookWindow.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518490_sys_gh5121_DoNotShowSystemRecords.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518491_sys_gh5121_AddCompanyPhoneBookFilter.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518492_sys_gh5121_AddTrlForCompanyPhoneBook.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518770_sys_gh5121_AddDescriptionForElemenIsActivePartner.sql
#5121 Create Company Phone Book window
> #5121 Create Company Phone Book window 

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Manufacturing_Order_Description.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Manufacturing_Order_Details.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/get_hu_attributes_value_for_pp_order_bomline.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getc_bpartner_product_vendor.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5518790_sys_gh5125_AddFunction_getc_bpartner_product_vendor.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5518790_sys_gh5125_AddFunction_get_hu_attributes_value_for_pp_order_bomline.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5518791_sys_gh5125_AddFunction_Docs_Manufacturing_Order_Description.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5518792_sys_gh5125_AddFunction_Docs_Manufacturing_Order_Details.sql
#5125 Add several functions for getting manufacturing order details
> #5125 Add several functions for getting manufacturing order details 

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/umsatzreport_bpartner_week/report_TabularView.jrxml
https://github.com/metasfresh/metasfresh/issues/5134
> #5134 repair tabular week report

- de.metas.vertical.creditscore/creditpass/src/main/java/de/metas/vertical/creditscore/creditpass/interceptor/C_Order.java
- de.metas.vertical.creditscore/creditpass/src/main/sql/postgresql/system/76-de.metas.vertical.creditscore.creditpass/5519390_sys_gh5016_update_process_window_and_result_price_column.sql
> Gh5016 Purchase order window fixes

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5519440_sys_gh5141_SeqNo_In_Product_Nutrition.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5519450_sys_gh5141_SeqNo_In_Product_Nutrition_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5519470_sys_gh5141_SeqNo_In_Product_Nutrition_window.sql
https://github.com/metasfresh/metasfresh/issues/5141
> #5141 SeqNo in Product Nutrition

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/impexp/AbstractImportProcess.java
#5148 Process of importing products is not working anymore
> #5148 Use Optional

- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/product/process/ExportProductSpecifications.java
https://github.com/metasfresh/metasfresh/issues/5143
> #5143 Product Specification process only for selected Product

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Shipment_Declaration.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Shipment_Declaration_Config.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Shipment_Declaration.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Shipment_Declaration_Config.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5520380_sys_gh5150_M_Shipment_Declaration_Config_DoctypeCorrection.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5520390_sys_gh5150_M_Shipment_Declaration_Config_DoctypeCorrection_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5520400_sys_gh5150_Changes_For_ShipmentDeliveryCorrection_Doctype.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5520430_sys_gh5150_Shipment_Declaration_Linking_Columns.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5520440_sys_gh5150_Shipment_Declaration_Linking_Columns_DDL.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5520460_sys_gh5150_Display_Readonly_And_Validation_Improvements.sql
- de.metas.business/src/main/java/de/metas/shipment/ShipmentDeclaration.java
- de.metas.business/src/main/java/de/metas/shipment/ShipmentDeclarationConfig.java
- de.metas.business/src/main/java/de/metas/shipment/ShipmentDeclarationId.java
- de.metas.business/src/main/java/de/metas/shipment/repo/ShipmentDeclarationConfigRepository.java
- de.metas.business/src/main/java/de/metas/shipment/repo/ShipmentDeclarationRepository.java
- de.metas.business/src/main/java/de/metas/shipment/service/ShipmentDeclarationCreator.java
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5520410_sys_gh5150_ShipmentDeclarationCorrection_Doctype.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5520490_sys_gh5150_NarcoticsShipmentDeclaration_Config.sql
https://github.com/metasfresh/metasfresh/issues/5150
> Gh5150 2 shipment declaration correction

- de.metas.business/src/main/java/de/metas/shipment/ShipmentDeclaration.java
- de.metas.business/src/main/java/de/metas/shipment/ShipmentDeclarationLine.java
- de.metas.business/src/main/java/de/metas/shipment/repo/ShipmentDeclarationRepository.java
- de.metas.business/src/main/java/de/metas/shipment/service/ShipmentDeclarationCreator.java
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5520530_sys_gh5150_ShipmentDeclarationCorrectionDoctype_Correct_Sequence.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5520540_sys_gh5150_ShipmentDeclarationCorrectionDoctype_noSequence.sql
- de.metas.vertical.pharma/src/main/sql/postgresql/system/5520550_sys_gh5150_ShipmentDeclaration_Translations.sql
https://github.com/metasfresh/metasfresh/issues/5150
> Gh5150 2  repair Narcotics Shipment Declaration doctype sequence

- de.metas.vertical.pharma/src/main/sql/postgresql/system/5520580_sys_gh5150_Small_Fixes_And_TRL.sql
https://github.com/metasfresh/metasfresh/issues/5150
> #5150  small changes after review

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CCache.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/IDCache.java
https://github.com/metasfresh/metasfresh/issues/5162
https://github.com/metasfresh/metasfresh/issues/5183 Enable selective cache invalidation
> 5183-app - Enable selective cache invalidation

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5521330_sys_gh5150_ShipmentDeclaration_Lines_Readonly.sql
https://github.com/metasfresh/metasfresh/issues/5150
> #150 make the shipment declaration lines always readonly

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/log/process/AD_EventLog_DeleteOldRecords.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/12-de.metas.event/5521140_C_DocOutBoundLog_fields_readonly.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/12-de.metas.event/5521380_gh5189-app_AD_EventLog_add_cleanup_scheduler.sql
- de.metas.dlm/base/src/main/sql/postgresql/ddl/dlm/functions/archive_r_request_data.sql
- de.metas.dlm/base/src/main/sql/postgresql/ddl/dlm/views/r_request_archivable_v.sql
- de.metas.dlm/base/src/main/sql/postgresql/system/5521370_sys_gh5189-app_add_functions_and_view.sql
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/export/invoice/InvoiceImportClientImpl.java
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/imp/process/C_Invoice_ImportInvoiceResponse.java
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/sql/postgresql/system/75-vertical-healthcare_ch/5521390_sys_gh5190-app_AD_Message.sql
#5189 - accidentally had this stuff in this PR, together with 
#5190 - forum-datenaustausch.ch XML notify on invoice rejection
> #5190-app - forum-datenaustausch.ch XML notify on invoice rejection

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_bp_org_block_left.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_de_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_de_DE.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_details_v2.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_en_GB.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_en_US.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_fr_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_it_CH.properties
#5195 Updates to Purchase order document
> #5195 Update header in purchase order

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5521860_sys_gh5181_Age_And_ProductionDate_InGerman.sql
https://github.com/metasfresh/metasfresh/issues/5181
> #5181  translate the attributes to german

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_bpblock_unbold.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_description.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_OrderCheckup_Description.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/RV_C_Order_MFGWarehouse_Report_Description.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5522230_sys_gh5229_AddReportProductionOrderFunctions.sql
#5229 Adjust production order report
> #5229 Adjust production order report 

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/ICompositeQueryFilter.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/InArrayQueryFilter.java
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/mrp_productinfo/impl/MRPProductInfoBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUQueryBuilder.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQueryBuilder.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/LocatorAndProductStrategy.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/HUPPOrderBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageEngine.java
- de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageQuery.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUPickingSlotBL_RetrieveAvailableHUsToPickTests.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUQueryBuilderTest.java
- de.metas.handlingunits.base/src/test/java/de/metas/storage/spi/hu/impl/HUStorageQueryTest.java
- de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/inventory/model/InventoryHUSelectModel.java
- de.metas.storage/src/main/java/de/metas/storage/IStorageQuery.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
> 5204-app - On-the-fly auto-allocate available HUs while creating shipments

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/age/AgeAttributeStorageListener.java
Fix swing client
https://github.com/metasfresh/metasfresh/issues/5208
> Attribute Age automatism

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/process/C_Location_Geocoding_ScheduleUpdate.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5522670_sys_gh5238_Add_BPartnerWindow_AreaSearchProcess.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5522740_sys_gh5238_Add_BPartnerWindow_AreaSearchProcess_2.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5522760_sys_gh5238_Change_geographical_distance_FunctionParametersToNumberFromReal.sql
https://github.com/metasfresh/metasfresh/issues/5238
> Finetuning Area Search: Params from selected BPartner>>Location

- .gitignore
- de.metas.business/src/main/java/de/metas/location/interceptor/C_Country.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeDAO.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/countryattribute/ICountryAttributeDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/mm/attributes/countryattribute/impl/Country2CountryAwareAttributeService.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/mm/attributes/countryattribute/impl/CountryAttributeDAO.java
https://github.com/metasfresh/metasfresh/issues/5237
> 5237 Attribute "Herkunft" is not updated after country change

- .gitignore
- de.metas.business/src/main/java/de/metas/location/interceptor/C_Country.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeDAO.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/countryattribute/ICountryAttributeDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/mm/attributes/countryattribute/impl/Country2CountryAwareAttributeService.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/mm/attributes/countryattribute/impl/CountryAttributeDAO.java
> Cp gh5237 metasfresh to mf 2018 19

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Customs_Invoice.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Customs_Invoice.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/model/I_OrderOrInOut.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/BPartnerId.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/model/IDocumentLocation.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/model/impl/PlainDocumentLocation.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5522910_sys_gh5210_BPartnerAdress_In_CustomsInvoice.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5522920_sys_gh5210_BPartnerAdress_In_CustomsInvoice_DDL.sql
- de.metas.business/src/main/java/de/metas/customs/CustomsInvoice.java
- de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceRepository.java
- de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceRequest.java
- de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java
- de.metas.business/src/main/java/de/metas/customs/process/M_InOut_Create_CustomsInvoice.java
- de.metas.business/src/test/java/de/metas/customs/CustomsInvoiceServiceTest.java
- de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningDocDocumentLocationAdapter.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/document/impl/DocumentLocationBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/letters/model/LetterDocumentLocationAdapter.java
https://github.com/metasfresh/metasfresh/issues/5210
> Gh5210 2 Bpartner Address in Customs Invoice and refactoring

- de.metas.acct.base/src/main/java/de/metas/acct/posting/DocumentPostingBusService.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/Event.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/impl/EventBus.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/log/EventLogEntryCollector.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/log/EventLogService.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/event/jms/JacksonJsonEventSerializerTest.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/event/log/EventLogServiceTest.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/12-de.metas.event/5522950_sys_ad_eventlog_add_filter_columns.sql
- de.metas.business/src/main/java/de/metas/bpartner/product/stats/BPartnerProductStatsEventSender.java
- de.metas.dunning_gateway.spi/src/main/java/de/metas/dunning_gateway/spi/model/MetasfreshVersion.java
- de.metas.material/event/src/main/java/de/metas/material/event/eventbus/MaterialEventConverter.java
need to be a bit more sophisticated in terms of maintaining the event's having-been-logged status
https://github.com/metasfresh/metasfresh/issues/5199
> 5199-app - Avoid updating AD_EventLog records; fix event reposting

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IAttributeValue.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/AbstractAttributeValue.java
https://github.com/metasfresh/metasfresh/issues/5208
> Attribute.getEmptyValue can handle dates now

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5523120_sys_gh5265_AddNewJasperProcessAndPrintFormatForC_Order_MFGWarehouseReport.sql
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_combined/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_old/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_old/report_description.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_old/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_old/report_details_hu.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_container_details.jrxml
#5265 Show different Bestellkontrolle views in Jasper based on type
> #5265 Show different Bestellkontrolle views in Jasper based on type 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5523490_sys_gh5210_Translate_CustomsInvoice_DocType.sql
https://github.com/metasfresh/metasfresh/issues/5210
> #5210 translate customs invoice doctype

- de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5523600_sys_gh1957_download_selected_translated.sql
https://github.com/metasfresh/metasfresh/issues/5274
> 5274 Translate "Download selected"

- de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5523680_sys_gh5276_finetuning_dunning_window.sql
https://github.com/metasfresh/metasfresh/issues/5276
> 5276 Finetuning dunning window

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/ApplicationReadyListener.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/Orders.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/MetasfreshIssueAppender.java
> 5280-app - Enable MetasfreshIssueAppender only when the system is ready for it

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Location.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Location.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524170_sys_gh5293_Add_VisitorAddress_column_to_C_BPartner_Location.sql
https://github.com/metasfresh/metasfresh/issues/5293
> Add VisitorAddress column to C_BPartner_Location

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524180_sys_gh5259_Add_VisitorsAddress_to_process_C_BPartnerWindow_AreaSearchProcess.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524210_sys_gh5259_UpdateTrlFor_VisitorsAddress_Element.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524240_sys_gh5259_update_trl_for_failed_geocoding_error_message.sql
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/process/M_ShipmentSchedule_EnqueueSelection.java
https://github.com/metasfresh/metasfresh/issues/5259
> Area Search: New Param "Visit Address"

- de.metas.contracts/src/main/java/de/metas/contracts/impl/CustomerRetentionRepository.java
https://github.com/metasfresh/metasfresh/issues/5296
> 5296 Exception on invoicing an invoice candidate

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/InventoryAllocationDestination.java
https://github.com/metasfresh/metasfresh/issues/5198
> #5198: regression: support disposals with movements to HU warehouse

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524260_sys-gh5300_mark_age_attribute_as_Document_relevant.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524300_sys_gh5300_ageattribute_should_be_shown_in_ShipmentLine_and_InvoiceLine.sql
https://github.com/metasfresh/metasfresh/issues/5300
> Show Age Attribute in Shipment Line and Invoice Line

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524310_sys_gh5261_1_attachment_log_window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524320_sys_gh5261_1_adjustments_attachment_log_window.sql
https://github.com/metasfresh/metasfresh/issues/5261
> 5261 Prevent Users from Accidentally deleting attachment files

- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/AbstractExcelExporter.java
https://github.com/metasfresh/metasfresh/issues/5313
> Replace the hardcoded `DD.MM.YYYY` with the data formatting of the respective user's locale.

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/InventoryAllocationDestination.java
https://github.com/metasfresh/metasfresh/issues/5198
> #5198 small fix

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5524560_sys_gh5320_Delete_Price_Column_FromDiscountSchemaLine.sql
- de.metas.business/src/main/java/de/metas/pricing/DiscountSchemaPOCopyRecordSupport.java
- de.metas.business/src/main/java/de/metas/pricing/interceptor/M_DiscountSchema.java
https://github.com/metasfresh/metasfresh/issues/5320
> #5320 Support cloning for Discount Schema

- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5524700_sys_gh5233-app_C_BPartner_Window_add_AD_User_IsSubjectMatterContact.sql
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/imp/process/C_Invoice_ImportInvoiceResponse.java
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_base/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/base/imp/process/ImportInvoiceResponseService.java
sending notification to subject matter contacts as supposed to the defaul contact
https://github.com/metasfresh/metasfresh/issues/5233
(cherry picked from commit ec40218881a5faed2db5e2df1c9a29395be128b7)
> 5233-app - Separate eMail Text for Notifications

- de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/MailWorkpackageProcessor.java
use more information (if available!) to build a better attachment file name
https://github.com/metasfresh/metasfresh/issues/5316
> 5316-app - C_DocOutbound - improve mail attachment file name

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5525760_sys_gh5328_PP_Order_Delete_Reduntant_Field.sql
https://github.com/metasfresh/metasfresh/issues/5328
> #5328 delete redundant field

- de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
https://github.com/metasfresh/metasfresh/issues/5330
> #5330  Do not recalculate prices in case of order copying

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/552588_sys_gh2160_update_trl_for_tax_category.sql
https://github.com/metasfresh/me03/issues/2160
> 2160 Fix the en_US trl for tax category

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5526050_sys_gh5343_ModifyDocs_Sales_OrderCheckup_Root.sql
#5343 New Customer Layout for Produktionskontrolle
> #5343 Make usable Docs_Sales_OrderCheckup with additonal parameters: C_BPartner and DatePromised

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5526220_sys_gh5350_show_ReferencedInvoice_in_SalesOrder_advancedEdit.sql
- de.metas.business/src/main/java/org/adempiere/invoice/service/IInvoiceBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/AbstractInvoiceBL.java
https://github.com/metasfresh/metasfresh/issues/5350
> Show Referenced Invoice in sales invoice advanced dialog

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MClient.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Env.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Login.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/Language.java
- de.metas.adempiere.adempiere/base/src/test/resources/de/metas/dataentry/layout/DataEntryLayoutRepositoryTest.snap
- de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/ALogin.java
https://github.com/metasfresh/me03/issues/1692
> Make Language a little bit more Immutable

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5526630_sys_gh5353_BankStatementImport_Format.sql
https://github.com/metasfresh/metasfresh/issues/5353
> Gh5353 script Repair import format script

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5526630_sys_gh5353_BankStatementImport_Format.sql
https://github.com/metasfresh/metasfresh/issues/5353
> Gh5353 repair IDs

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5527010_sys_gh5374_Add_relation_SalesInvoice_DunningDocument.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5527070_sys_gh5374_AddMissingIndexes_FixWrongColumnUsedInJoin_for_SalesInvoice_DunningDocument_reference.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5527080_sys_gh5374_Cypress_doesnt_like_arrows_in_references.sql
https://github.com/metasfresh/metasfresh/issues/5374
> Add relation sales invoice - dunning document

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5527410_sys_gh5357_Shipper_mandatoryLogic_In_Order.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5527440_sys_gh5357_Drop_M_Freight.sql
https://github.com/metasfresh/metasfresh/issues/5357
> #5357 mandatory logic for shipper in order

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/552762_gh2401-isQualityIssueWarehouse.sql
https://github.com/metasfresh/me03/issues/2401
> #2401 Add Quality Issue warehouse filter in Warehouse list page

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridWindowVO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/UserRolePermissionsKey.java
- GridTabVO - the actual fix: avoid exception by calling the user/role dependending UIDisplayedEntityTypes.isEntityTypeDisplayedInUIOrTrueIfNull() only if rolled shall be applied
- UserRolePermissionsKey - thorw more informative error
https://github.com/metasfresh/metasfresh/issues/5346
> 5346-app - Pricing Condition fixes

- de.metas.business/src/main/java/de/metas/pricing/conditions/service/impl/PricingConditionsRepository.java
- de.metas.business/src/main/java/de/metas/pricing/process/M_DiscountSchemaBreak_CopyToOtherSchema.java
PricingConditionsId is not supported as param because it's not RepoIdAware
https://github.com/metasfresh/metasfresh/issues/5392
> #5392 repair parameter

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5528050_gh5405_CampaignPrice_Tab_In_Product_Window.sql
https://github.com/metasfresh/metasfresh/issues/5405
> #5405 add campaign price as subtab in product

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/UserAuthTokenRepository.java
- de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java/de/metas/server/housekeep/ResetJsonReportsAuthTokenHouseKeepingTask.java
> 5411-app - Reset auth token for Json Reports user on each app-server-start

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5528770_sys_gh5414_Rename_PriceListVersion__DiscountSchema_to_PriceListSchema.sql
https://github.com/metasfresh/metasfresh/issues/5414
> Rename PriceListVersion "Discount Schema" to " Price List Schema"

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5528970_sys_gh2538_warehouse_for_material_entnahme.sql
https://github.com/metasfresh/me03/issues/2538
> #2538 Warehouse for Materialentnahme

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process_Para.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process_Para.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/Msg.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/BarcodeScannerType.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/Param.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ParamBarcodeScannerType.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessClassInfo.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessClassParamInfo.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/process/BarcodeScannerTypeTest.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529060_sys_gh5139_BarcodeScannerType.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529080_sys_gh5139_set_BarcodeScannerType_for_existing_processes.sql
- de.metas.business/src/main/java/org/adempiere/mm/attributes/exceptions/AttributeNotFoundException.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/AbstractAttributeStorage.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/HUAttributeStorage.java
- de.metas.vertical.pharma.securpharm/src/main/java/de/metas/vertical/pharma/securpharm/client/SecurPharmClient.java
- de.metas.vertical.pharma.securpharm/src/main/sql/postgresql/system/86-de.metas.vertical.pharma.securpharm/5529070_sys_gh5139_SecurPharm_Barcode_use_Datamatrix.sql
https://github.com/metasfresh/metasfresh/issues/5139
> gh5139_3 - implement BarcodeScannerType support

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529150_sys_gh5070_discount-schema-lines-trl.sql
- metasfresh.code-workspace
https://github.com/metasfresh/metasfresh/issues/5070
> Discount Schema Lines in separate window #5070

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529130_sys_gh5439_Delete_Duplicate_element.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529140_sys_gh5439_Fix_DisplayLogic_Typo.sql
https://github.com/metasfresh/metasfresh/issues/5439
> Error `Field DropShip_BPartner_ID already exists in element` in Customer Return window #5439

- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
https://github.com/metasfresh/metasfresh/issues/5410
> #5410 do not allow campaign prices for a partner who is not allowed to

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/expression/api/LogicExpressionResult.java
- de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/grid/ed/VPAttributeDialog.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529270_sys_gh5440_drop_reference_WarehouseOfClient.sql
- de.metas.business/src/main/java/de/metas/product/IProductBL.java
- de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeDAO.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/util/ASIEditingInfo.java
- de.metas.handlingunits.base/src/main/sql/postgresql/system/5529260_sys_gh5440_M_ShipmentSchedule_M_HU_PI_Version_ID_dont_use_QtyProvided.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentSchedulePA.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/ShipmentScheduleUserChangeRequest.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/ShipmentScheduleUserChangeRequestsList.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5529120_sys_gh5440_ShipmentScheduleEditor_window.sql
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5529250_sys_gh5440_M_ShipmentSchedule_avoid_unknown_LockedBy_expression.sql
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5529280_sys_gh5440_ShipmentSchedule_tab_avoid_OrderBy_SQL_column.sql
https://github.com/metasfresh/metasfresh/issues/5440
> gh5440 - Easy shipment candidate recording

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVOsLoader.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTab.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/UIDisplayedEntityTypes.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/api/impl/ADColumnCalloutDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java
- de.metas.adempiere.adempiere/client/src/main/java/org/compiere/grid/VPanelFormFieldBuilder.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1248
> when loading GridFieldVOs consider GridTabVO.applyRolePermissions

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5529700_sys_gh5471-payment-date-range.sql
https://github.com/metasfresh/metasfresh/issues/5471
> Add Daterange to Payment Window #5471

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/productspecifications/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/productspecifications/report_component.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5529970_sys_gh5489_FixSpecificationsView.sql
> #5489 Some fixes to report specifications product

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/JsonConverters.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImpl.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/utils/InvalidIdentifierException.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/JsonOLCandCreateBulkResponse.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/utils/JsonError.java
- de.metas.business.rest-api/src/test/java/de/metas/rest_api/ordercandidates/model/JsonOLCandModelTest.java
https://github.com/metasfresh/metasfresh/issues/5365
> Gh5365 2 - improve error handling

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_PriceList.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_PriceList.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/TaxCategoryId.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5530060_sys_gh5500_M_PriceList_Default_TaxCategory_ID.sql
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- de.metas.business/src/main/java/org/adempiere/pricing/exceptions/ProductNotOnPriceListException.java
- de.metas.business/src/test/java/de/metas/pricing/service/impl/PriceListDAOTest.java
- de.metas.business/src/test/java/de/metas/pricing/service/impl/PricingTestHelper.java
- de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
- de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/MaterialTrackingDocumentsPricingInfo.java
- de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/PricingContextBuilder.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/pricing/callout/M_ProductPrice.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/pricing/callout/M_ProductPrice_TabCallout.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/pricing/modelvalidator/M_ProductPrice.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/AbstractICTestSupport.java
https://github.com/metasfresh/metasfresh/issues/5500
> gh5500 - M_PriceList.Default_TaxCategory_ID

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/customs/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/customs/report_description.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getBPAddress.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5529920_sys_gh5503_AddC_BPartnerAsParameterInReportZolldokument.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5530150_sys_gh5503_AddNewFunctiongetBPAddress.sql
#5503 Adjustment to customs report from Material Receipts
> #5503 Adjustment to customs report from Material Receipts 

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Inventory.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Inventory.java
- de.metas.business/src/main/java/de/metas/impexp/processing/inventory/InventoryImportProcess.java
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5530200_sys_gh5453-app_tweak_i_inventory_and_minimal_format.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5530210_sys_gh5453-app_tweak_i_inventory_and_minimal_format.sql
* fix import-format:
* we don't want DateLastInventory, but the inventory document date to be in the import format
* fix the AD_ImpFormat_Row.StartNo for two rows
* rename I_Import.MovementDate to InventoryDate
https://github.com/metasfresh/metasfresh/issues/5453
> 5453-app - Data Import REST endpoints

- de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_SetDunningGrace.java
https://github.com/metasfresh/metasfresh/issues/5510
> #5510 dunning grace always updates via process

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/JsonConverters.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/MasterdataProvider.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImpl.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/ProductPriceCreateRequest.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/ProductPriceMasterDataProvider.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/TestMasterdata.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/JsonOLCand.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/JsonOLCandCreateRequest.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/JsonProductInfo.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCand.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandCreateRequest.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/DefaultGroupingProvider.java
- vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/resources/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsServiceTest.snap
https://github.com/metasfresh/metasfresh/issues/5365
> gh5365_4 - import C_OLCand.M_Warehouse_Dest_ID + product price import cosmetics

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5530390_sys_gh5450_Base_PLV_ValRule.sql
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
https://github.com/metasfresh/metasfresh/issues/5450
> #5450 base plv valrule

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5530680_sys_gh2799_pricesystem_search.sql
Pricesystem shall be search widget not dropdown
#5525
> Pricesystem shall be search widget not dropdown

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_details.jrxml
#5529 Bestellkontrolle (Barcode): Packing Instruction cut off
> #5529 Bestellkontrolle (Barcode): Packing Instruction cut off

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/callout/DatePromised.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/impl/OrderDeliveryDayBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/callout/C_Order.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/TourPlanningTestBase.java
- de.metas.util/src/main/java/de/metas/util/time/SystemTime.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1252
> Gh1252webui

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531050_sys_gh5542_Update_MoveToAnotherWarehouse_trl.sql
https://github.com/metasfresh/metasfresh-webui-api/issues/1259
> Update MoveToAnotherWarehouse trl

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531120_sys_gh2647_order_in_acc_transactions.sql
Windows default order by in grid view
> default ordering added in accounting transactions window

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/picking_tu_label/label.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5530900_sys_gh5536_ModifyPicking_tu_label.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5530740_sys_gh5536_AddC_BPartner_Location_Parameter.sql
#5536 Allow possibility to run TU Label from BPartner
> #5536 Add Bp location as param

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531160_sys_gh2853_unposted_documents_window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531240_sys_gh2853_renamed_ad_table_elem.sql
New Window: Unposted Documents
> window created

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5530920_sys_gh5552_AddDefaultEsrAccount.sql
#5552 ESR Import auto selection of default Bankaccount of Organisation
> #5552 Add default account

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531260_sys_gh2866_matched_invoices_window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531340_sys_gh2866_readonly_window.sql
New Window in WebUI for Matched Invoices
> new window created

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/c_bpartner_location/label.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/C_BPartner_Location_Label.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5531540_sys_gh5536_AddC_BPartner_Location_Label.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5531541_sys_gh5536_RemoveLocationParameterFromPicking_tu_label.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5531610_sys_gh5536_UseDifferentReport.sql
#5536 Allow possibility to run TU Label from BPartner
> #5536 Allow possibility to run TU Label from BPartner 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531270_sys_gh2518_Create_Process_WEBUI_Import_Payment_Request_For_Purchase_Invoice_1.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531420_sys_gh2518_Create_Process_WEBUI_Import_Payment_Request_For_Purchase_Invoice_2.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531450_sys_gh518_update_trl_1.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531470_sys_gh518_update_trl_2.sql
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/paymentdocumentform/AlmightyKeeperOfEverything.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/paymentdocumentform/PaymentStringProcessService.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/paymentdocumentform/WEBUI_Import_Payment_Request_For_Purchase_Invoice.java
- de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/bankstatement/match/form/BankStatementMatchForm.java
- de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/misc/ImportBankStatementModel.java
- de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/form/ReadPaymentDocumentForm.java
- de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/form/ReadPaymentDocumentPanel.java
https://github.com/metasfresh/metasfresh/issues/2518
> Purchase Invoice: Add "Read Payment String" action in WebUI

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531810_sys_gh2754update_warehouse_where_null.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531820_sys_gh2754_warehouse_mandatory_in_po.sql
https://github.com/metasfresh/metasfresh/issues/5569
> warehouse set as mandatory in purchase order

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531810_sys_gh2754update_warehouse_where_null.sql
https://github.com/metasfresh/metasfresh/issues/5569
> #5569 Mandatory Field in Purchase Order: Warehouse ID

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531815_sys_gh2754update_warehouse_where_null.sql
https://github.com/metasfresh/metasfresh/issues/5569
> Mandatory Field in Purchase Order: Warehouse ID #5569

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5532510_sys_gh2646_lager_in_grid_view.sql
https://github.com/metasfresh/metasfresh/issues/5592
> #2646 Show warehouse value in Grid View 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5532690_sys_gh2857_adjust_cu_tu_alllocation.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5532700_sys_gh2857_translation_cu_tu_allocation.sql
https://github.com/metasfresh/metasfresh/issues/5587
> #5587 New Window for Packvorschrift (CU-TU) Standalone 

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/model/interceptor/AD_Window.java
#5618 Can't create windows anymore
> #5618 Set data from element at before save

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/ui/model/interceptor/AD_UI_Element.java
#5620 Set automatically Name field from AD_UI_Element
> #5620 Set automatically Name field from AD_UI_Element

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/ModelChangeType.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java
#5628 Manor: Partner relations don't work properly in sales order
> #5628 Do not set addresses AFTER NEW/CHANGE

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/GeographicalCoordinatesWithBPartnerLocationId.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/GeographicalCoordinatesWithLocationId.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/GeocodingService.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/process/C_Location_Geocoding_ScheduleUpdate.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/LocationDAO.java
https://github.com/metasfresh/metasfresh/issues/5566
> gh5566_2 - implement geo coordinates support for webui views

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533160_sys_gh5631_redirect_manufacturer_bpartner.sql
https://github.com/metasfresh/metasfresh/issues/5631
> #5631 Product -> Manufacturer points to wrong window "BP Pharma")

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533210_sys_gh2965_manufacturer_bpartner_pharma.sql
https://github.com/metasfresh/metasfresh/issues/5631
> #5631 Product -> Manufacturer points to wrong window "BP Pharma"

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533220_sys_gh5564_Update_Boolean_ImportRows.sql
https://github.com/metasfresh/metasfresh/issues/5564
> #5564 update existing boolean import format rows to yes/no

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533290_sys_gh5612_country_lookup_field.sql
https://github.com/metasfresh/metasfresh/issues/5612
> #5612 Country Fields as Lookup widget

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_de_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_de_DE.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5533340_sys_gh5639_AddProcessForPrintingPicklist.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5533441_sys_gh5639_AddJavaProcessPrintPickList.sql
#5639 Print Picklist from Picking terminal v2
> #5639 Print Picklist from Picking terminal v2 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533570_adjustments_components_bom.sql
https://github.com/metasfresh/metasfresh/issues/5645
> #5645 BOM Components followup - Comment, Change notice and Expected result to be added 

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/format/ImpFormatColumn.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/parser/FlexImpDataLineParserTest.java
https://github.com/metasfresh/metasfresh/issues/5564
> #5564 Consider empty strings as null in imports

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533600_sys_gh5644_GenerateInvoice_IsUpdateLocationAndUserForInvoice_Parameter.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoicingParams.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoicingParams.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/PlainInvoicingParams.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/AbstractICTestSupport.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoicesTest.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractAggregationEngineTestBase.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestUpdatedLocationAndUser.java
https://github.com/metasfresh/metasfresh/issues/5644
> Gh5644 IsUpdateLocationAndUserForInvoice in Invoice Generate process

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533700_sys_gh5649_gtin_added.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5533720_sys_gh5649_gtin_in_advanced_edit.sql
https://github.com/metasfresh/metasfresh/issues/5649
> #5649 GTIN in Product window

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPLocationBuilder.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPartnerDAO_retrieveBPartnerLocationTests.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/BPartnerMasterDataProvider.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/MasterdataProvider.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImpl.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/ProductMasterDataProvider.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/BPartnerMasterDataProviderTest.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/request/JsonRequestLocation.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JsonOLCandCreateRequest.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandEffectiveValuesBL.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandEffectiveValuesBL.java
add fallback code and swagger documentation
#5652
> 5652-app - OLCand - support requests without BPartner-Location

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateService.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/CreatePickingCandidatesCommand.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/PickHUCommand.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/requests/PickHURequest.java
#5659 Picklist in Picking Terminal v2 automatically picks, but shall not
> #5659 Implement the possibility to just create picking candidates without really pick them

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/process/AD_Tab_CreateFields.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5534370_sys_gh1270webui_set_all_AD_Client_ID_fields_as_readonly.sql
https://github.com/metasfresh/metasfresh-webui-api/issues/1270
> gh1270webui_2: make AD_Client_ID fields readonly

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/IMsgBL.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/SqlQueryUnion.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/HUReservationService.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/picking/model/I_M_PickingSlot.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/picking/model/I_M_Picking_Config.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/picking/model/I_M_Picking_Config_V2.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/picking/model/X_M_Picking_Config_V2.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5534390_sys_gh5551_M_Picking_Config_V2_IsConsiderAttributes.sql
https://github.com/metasfresh/metasfresh/issues/5551
> gh5551_2: picking v2 shall consider shipment attributes (configurable)

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5534550_sys_gh5602_Cashbook_and _Payment_Repairments.sql
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/model/validator/C_BankStatementLine.java
https://github.com/metasfresh/metasfresh/issues/5602
> Gh5602 2 repairments regarding Payment and Cashbook

- de.metas.shipper.gateway.dhl/src/main/java-gen/de/metas/shipper/gateway/dhl/model/I_DHL_ShipmentOrder.java
- de.metas.shipper.gateway.dhl/src/main/java-gen/de/metas/shipper/gateway/dhl/model/I_DHL_ShipmentOrderRequest.java
- de.metas.shipper.gateway.dhl/src/main/java-gen/de/metas/shipper/gateway/dhl/model/I_DHL_Shipper_Config.java
- de.metas.shipper.gateway.dhl/src/main/java-gen/de/metas/shipper/gateway/dhl/model/I_Dhl_ShipmentOrder_Log.java
- de.metas.shipper.gateway.dhl/src/main/java-gen/de/metas/shipper/gateway/dhl/model/X_DHL_ShipmentOrder.java
- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDeliveryOrderRepository.java
- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/model/DhlClientConfig.java
- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/model/DhlClientConfigRepository.java
- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/model/DhlCustomDeliveryData.java
- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/model/DhlCustomDeliveryDataDetail.java
- de.metas.shipper.gateway.dhl/src/main/sql/postgresql/system/99-de.metas.shipper.gateway.dhl/5534640_sys_gh5611_AddTrackingURL.sql
https://github.com/metasfresh/metasfresh/issues/5611
>  Add DHL Shipper and DHL integration

- de.metas.shipper.gateway.dhl/src/main/sql/postgresql/system/99-de.metas.shipper.gateway.dhl/5534700_sys_gh5611_SetDefault_DhlConfigurationApiUrl.sql
https://github.com/metasfresh/metasfresh/issues/5611
> Set default value for DHL client configuration api url

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
https://github.com/metasfresh/metasfresh/issues/5666
> #5666 set qtyToInvoiceInUOM for freight cost invoice candidates

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5531390_sys_gh5556_link_organisation_make_org_mandatory.sql
> GH5556 Prevent Running Link Organisation Process if Organisation Field is empty

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report_de_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report_de_DE.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report_en_GB.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report_en_US.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report_fr_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/balance_empties/report_it_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getEmptiesBalance.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5534770_sys_gh5683_AddEmptiesBalanceReport.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5534771_sys_gh5683_AddFunction_getEmptiesBalance.sql
#5683 Empties Saldo report per Day
> #5683 Empties Saldo report per Day 

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5534871_sys_gh5689_FixMethod_cu_product_label.sql
#5689 Fix Method report.cu_product_label(IN M_HU_ID numeric)
> #5689 do not show duplicates

- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributesKeys.java
- de.metas.business/src/test/java/org/adempiere/mm/attributes/api/AttributesKeysTest.java
https://github.com/metasfresh/metasfresh/issues/5686
> avoid NPE + testing

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting/report_de_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting/report_de_DE.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/tax_accounting/report_recap.jrxml
> #5694 Adjust Taxcode Report 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5534930_sys_gh5690_IsRemoveAllExistingContactsFromCampaign.sql
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/CampaignService.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/CampaignRepository.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/interceptor/AD_User.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/process/MKTG_ContactPerson_CreateFrom_C_BPartner.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/process/MKTG_ContactPerson_CreateFrom_C_BPartner_WithAddress.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/process/MKTG_ContactPerson_ProcessBase.java
- de.metas.marketing/base/src/main/java/de/metas/marketing/base/process/MKTG_ContactPerson_ProcessParams.java
- de.metas.marketing/base/src/test/java/de/metas/marketing/base/CampaignServiceTest.java
https://github.com/metasfresh/metasfresh/issues/5690
> Gh5690 DeleteExistingContactPersons option in Export to Marketing Campaign process

- de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
https://github.com/metasfresh/metasfresh/issues/5699
> #5699  Fallback to standardauftrag when doctype not set in partner

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535020_sys_gh5702_Display_Description_And_BottomDescription_In_Orders.sql
https://github.com/metasfresh/metasfresh/issues/5702
> #5702 Display Description and BottomDescription in orders

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/PreliminaryDocumentNoBuilder.java
https://github.com/metasfresh/metasfresh/issues/5701
> #5701 repairment for creating new documentNo for different sequences

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/BPGroupId.java
- de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/I_C_CommissionSettingsLine.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/I_C_Commission_Instance.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/I_C_Commission_Share.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/I_C_HierarchyCommissionSettings.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/X_C_CommissionSettingsLine.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/X_C_Commission_Instance.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/X_C_Commission_Share.java
- de.metas.contracts/src/main/java-gen/de/metas/contracts/commission/model/X_C_HierarchyCommissionSettings.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionConfigFactory.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionConfigStagingDataService.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionHierarchyFactory.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionInstanceRequestFactory.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/repos/CommissionInstanceRepository.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/repos/CommissionRecordStagingService.java
- de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5535120_sys_gh5522-app_extend_commission_settings.sql
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5535220_sys_gh5522-app_extend_commission_settings.sql
- de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/services/CommissionConfigFactoryTest.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/services/CommissionHierarchyFactoryTest.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/services/repos/CommissionInstanceRepositoryTest.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/services/repos/CommissionSettlementShareRepositoryTest.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/testhelpers/CommissionInstanceTestRecord.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/testhelpers/ConfigLineTestRecord.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/testhelpers/ConfigTestRecord.java
- de.metas.contracts/src/test/java/de/metas/contracts/commission/testhelpers/ContractTestRecord.java
- de.metas.contracts/src/test/resources/de/metas/contracts/commission/commissioninstance/services/repos/CommissionInstanceRepositoryTest.snap
- de.metas.contracts/src/test/resources/de/metas/contracts/commission/commissioninstance/services/repos/CommissionSettlementShareRepositoryTest.snap
> 5522-app - Commission calculation ][

- de.metas.business/src/main/java/de/metas/uom/impl/UOMConversionBL.java
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5531369_cli_gh5522-app_prommission_product_add_category.sql
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5531370_cli_gh5522-app_commission_product.sql
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5535320_cli_gh5522-app_prommission_product_add_UOM_set_category.sql
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/AbstractInvoiceBL.java
- add dedicated product category and UOM for the commission product
- AbstractInvoiceBL and UOMConversionBL : minor
#5522
> 5522-app - Commission calculation

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535350_sys_gh5729_Show_StockUom_In_ShipmentSchedule.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
https://github.com/metasfresh/metasfresh/issues/5729
> Gh5729 CatchWeight logic

- de.metas.acct.base/src/main/java/de/metas/acct/impexp/AccountImportProcess.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/processing/ImportProcessTemplate.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/C_Element_Levels.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5535400_sys_gh5733_ModifyViewsToNotCheclInactiveC_Elements.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5535380_sys_gh5733_FixProcessClassName.sql
- de.metas.vertical.pharma/src/main/java/de/metas/impexp/product/IFAProductImportProcess.java
> #5733 Fix importing process 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535450_sys_gh5742_Unposted_Documents_Window_Changes.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535450_sys_gh5742_Unposted_Documents_Window_Changes_And_Process_TRL.sql
https://github.com/metasfresh/metasfresh/issues/5742
> #5742 unposted documents window changes

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535580_sys_gh5743_Shipper_Param_In_ProductsToPick_4EyesReview_ProcessAll.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/PackageableQuery.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/PackagingDAO.java
https://github.com/metasfresh/metasfresh/issues/5743
> Gh5743 shipper in ProductsToPick_4EyesReview_ProcessAll

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Campaign_Price.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Campaign_Price.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/pricing/PricingSystemId.java
- de.metas.business/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPrice.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceQuery.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceRepository.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/callout/C_Campaign_Price.java
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5535440_sys_gh5756_Add_M_PricingSystem_id.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5535445_sys_gh5756_Add_M_PricingSystem_id.sql
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/adempiere/service/impl/OrderLineBLTest.java
#5756 Allow Action Prices on Pricing System
> #5756 Allow Action Prices on Pricing System 

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/shipping/api/IShipperTransportationDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/shipping/api/impl/ShipperTransportationDAO.java
https://github.com/metasfresh/metasfresh/issues/5743
> #5743 next shipper transportation for the given shipper

- de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/shipping/model/I_M_ShipperTransportation.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/shipping/model/X_M_ShipperTransportation.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/shipping/api/impl/ShipperTransportationDAO.java
https://github.com/metasfresh/metasfresh/issues/5743
> #5743 order transportation orders by date to be fetched

- de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDraftDeliveryOrderCreator.java
https://github.com/metasfresh/metasfresh/issues/5611
> FIX: Dhl Shipper: Don't NPE in case there's no packing material

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535820_sys_gh5761_M_ShipperTransportation_DocumentNo_Sequence.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/shipping/callout/M_ShipperTransportation.java
https://github.com/metasfresh/metasfresh/issues/5761
> #5761 Automatically set the document no to Transportation Order

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/MonthsUntilExpiryAttributeStorageListener.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/UpdateMonthsUntilExpiryCommand.java
https://github.com/metasfresh/metasfresh/issues/5748
> fix for HU_BestBeforeDate

- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/callout/C_Campaign_Price.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5535840_sys_FixCampaignPrice_Trl.sql
#5770 Clone action for Campaign price
> #5770 Clone action for Campaign price 

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_Planning.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_Planning.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5535960_sys_gh5776_PP_ProductPlanning_M_Product_Not_Mandatory.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/55360800_sys_gh5776_PP_Product_Planning_Window_And_Changes.sql
- de.metas.adempiere.libero.libero/src/test/java/org/eevolution/util/PPProductPlanningBuilder.java
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/ordercheckup/impl/OrderCheckupDAO.java
- de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/fresh/ordercheckup/OrderCheckupTestHelper.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/InOutDDOrderBL.java
- de.metas.material/planning/src/main/java/de/metas/material/planning/IProductPlanningDAO.java
- de.metas.material/planning/src/main/java/de/metas/material/planning/ddorder/DDOrderPojoSupplier.java
- de.metas.material/planning/src/main/java/de/metas/material/planning/impl/ProductPlanningDAO.java
- de.metas.material/planning/src/test/java/de/metas/material/planning/impl/ProductPlanningDAO_findPlantTest.java
- de.metas.material/planning/src/test/java/de/metas/material/planning/impl/ProductPlanningDAO_findTest.java
https://github.com/metasfresh/metasfresh/issues/5776
> Gh5776 Default Product Planning

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/halbfabrikat/label.jrxml
> #5784 Make sure the entire text is show all the time

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/logger/impl/MigrationLogger.java
https://github.com/metasfresh/metasfresh/issues/5789
> Don't log migration scripts for AD_Attachment tables

- de.metas.shipper.gateway.dpd/src/main/java/de/metas/shipper/gateway/dpd/DpdDraftDeliveryOrderCreator.java
- de.metas.shipper.gateway.dpd/src/main/java/de/metas/shipper/gateway/dpd/DpdShipperGatewayClient.java
- de.metas.shipper.gateway.dpd/src/main/java/de/metas/shipper/gateway/dpd/model/DpdServiceType.java
- de.metas.shipper.gateway.dpd/src/test/java/de/metas/shipper/gateway/dpd/DpdTestHelper.java
- de.metas.shipper.gateway.dpd/src/test/java/de/metas/shipper/gateway/dpd/IntegrationDEtoATTest.java
- de.metas.shipper.gateway.dpd/src/test/java/de/metas/shipper/gateway/dpd/IntegrationDEtoCHTest.java
- de.metas.shipper.gateway.dpd/src/test/java/de/metas/shipper/gateway/dpd/IntegrationDEtoDETest.java
- de.metas.shipper.gateway.dpd/src/test/java/de/metas/shipper/gateway/dpd/IntegrationDEtoUSTest.java
- de.metas.shipper.gateway.dpd/src/test/resources/xml_examples/Dpd Classic -- DEtoDE.xml
- de.metas.shipper.gateway.dpd/src/test/resources/xml_examples/Dpd Express -- DEtoUS.xml
Dpd Products: Use E12 for same-country and CLASSIC for international shipping 
https://github.com/metasfresh/metasfresh/issues/5637
>  Add DPD Shipper and DPD integration

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/InvoicePDFService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/CheckInvoiceCandidatesStatusService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/InvoicesRestControllerImpl.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/IInvoicesRestEndpoint.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/response/JsonInvoiceStatus.java
https://github.com/metasfresh/metasfresh/issues/5786
> Gh5786 Invoice PDF Endpoint

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Location.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Location.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/AddressBuilder.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPartnerBL_RetrieveContactOrNullTests.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/SalesInvoicePaymentStatusRepository.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/bpartner/impl/BPartnerRecordsUtil.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/BPartnerMasterDataProviderTest.java
- de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
- de.metas.business/src/test/java/de/metas/pricing/service/impl/PriceListDAOTest.java
- de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
- de.metas.document.archive/de.metas.document.archive.base/src/test/java/de/metas/document/archive/spi/impl/InvoiceDocOutboundLogMailRecipientProviderTest.java
- de.metas.dunning/src/test/java/de/metas/dunning/document/archive/DunningDocOutboundLogMailRecipientProviderTest.java
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/setup/process/ClientSetup.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5536500_sys_gh5804_AddBPName_to_C_BPartner_Location.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5536520_sys_gh5804_MakeBPName_Identifier_in_BPLocation.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/document/impl/DocumentLocationBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tax/api/impl/TaxBL.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inout/invoicecandidate/M_InOutLine_HandlerTest.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/TourPlanningTestBase.java
- de.metas.vertical.pharma/src/main/java/de/metas/impexp/bpartner/IFABPartnerLocationImportHelper.java
#5804 BPartner Name overwrite in BPartner Location
> #5804 BPartner Name overwrite in BPartner Location 

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1305
> IShipmentScheduleBL getByIdsOutOfTrx(ids, modelType)

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPIItemProductBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductBL.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1307
> gh1307webui

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.business/src/main/java/de/metas/order/IOrderDAO.java
- de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
- de.metas.edi/src/main/java/de/metas/edi/api/impl/EDIOLCandBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/IHUPackingAwareBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/impl/HUPackingAwareBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HUPIItemProductId.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUPIItemProductBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductBL.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1309
> gh1309webui

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/POJOQuery.java
- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/model/IQuery.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getMatchingDiscountSchemaLine_ID.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5456410_sys_gh942_M_PriceList_Create_supporting_views.sql
- de.metas.business/src/main/java/de/metas/pricing/pricelistschema/PriceListSchemaRepository.java
- de.metas.business/src/main/java/de/metas/pricing/process/ImportPriceListSchemaLinesFromAttachment.java
- de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java
- de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
Fixes after review 
https://github.com/metasfresh/metasfresh/issues/5799
> Pricelist Schema export-import

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536760_sys_gh5799_updateProcessTrlforDE.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536770_sys_gh5799_Exclude_deactivated_PriceListSchemaLines.sql
Fix DE trl (swing is buggy and only shows DE trl page after swing is restarted :( )
https://github.com/metasfresh/metasfresh/issues/5799
> Pricelist Schema export-import for Basepricelists

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5536830_sys_gh5824_Add_LI_IBAN_Config.sql
#5824 IBAN Liechtenstein not accepted as Bank Account
> #5824 Add config for Liechtenstein

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5537090_sys_gh5802_M_Pricelist_BasePricelist_Search_Field.sql
https://github.com/metasfresh/metasfresh/issues/5802
> Gh5802 Make M_Pricelist.BasePricelist a search field

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5536980_sys_gh5840_Allow_manual_creation_of_Phonecall_Schedule.sql
https://github.com/metasfresh/metasfresh/issues/5840
> Allow manual creation of Phonecall Schedule

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Order_Root.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5537260_sys_gh5851_AddCurrency.sql
#5851 Add currency in doc_sales_invoice_root and in doc_sales_order_root functions
> #5851 Add currency

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/InvoiceService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/CheckInvoiceCandidatesStatusService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/InvoicesRestControllerImpl.java
https://github.com/metasfresh/metasfresh/issues/5845
> Invoice reversal via REST-EP

- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Inventory.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Inventory.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InventoryLine.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Inventory.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InventoryLine.java
- de.metas.business/src/main/java/de/metas/impexp/processing/inventory/InventoryImportProcess.java
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5537190_sys_gh5861_changes_for_cost_price_in_inventory_import.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5537430_sys_gh5861_add_CP_on_ImportInventory_window.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5537630_sys_gh5861_add_costprice_on_physicalInventory_window.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5537660_sys_gh5861_add_translations_for_costPrice.sql
https://github.com/metasfresh/metasfresh/issues/5861
> Add Cost Price in inventory import

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5537790_sys_gh5840_fix_ux_and_cosmetic.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5537800_sys_gh5840_properly_fix_references.sql
- add links to Phonecall Schema Version and Line
- split combo fields into own fields so that the user better understands what is mandatory
- fix trls
https://github.com/metasfresh/metasfresh/issues/5840
> [fix] Phonecall Schedule: UX and cosmetic fixes

- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5538020_sys_gh5861_change_translations_for_cost_price_on_physical_inventory_and_inventory_import.sql
https://github.com/metasfresh/metasfresh/issues/5861
> Changed translation for cost price element

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/AbstractTypedQuery.java
- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/model/IQuery.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538130_sys_gh5874-update-some-trl.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
https://github.com/metasfresh/metasfresh/issues/5874
> Reactivate Shipment, update Shipmentline delivery catch weight => does not update invoice candidate

- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSetInstanceBL.java
- de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java
https://github.com/metasfresh/metasfresh/issues/5880
> IAttributeSetInstanceBL.getImmutableAttributeSetById

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Phonecall_Schedule.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Phonecall_Schema_Version_Line.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Phonecall_Schedule.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Phonecall_Schema_Version_Line.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538460_sys_gh5891_C_Phonecall_Schedule_Description.sql
- de.metas.business/src/main/java/de/metas/phonecall/PhonecallSchedule.java
- de.metas.business/src/main/java/de/metas/phonecall/PhonecallSchemaVersionLine.java
- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallScheduleRepository.java
- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallScheduleService.java
- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallSchemaRepository.java
- de.metas.business/src/test/java/de/metas/phonecall/service/PhonecallScheduleServiceTest.java
https://github.com/metasfresh/metasfresh/issues/5891
> Phonecall Planning adjustments

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5537830_sys_gh3427_attribute_window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5537970_sys_gh3427_attribute_window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538030_sys_gh3427_attribute_window.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538120_sys_gh3427_attribute_window_changed_merkmal_field_position.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538180_sys_gh3427_attribute_window_filter.sql
Revert Teo's revert and removed destructive sql file
https://github.com/metasfresh/me03/issues/3427
> 3427 Attribute recording and filtering

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/provider/googlemaps/GoogleMapsGeocodingProviderImpl.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/payment/JsonPaymentService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/payment/PaymentRestEndpointImpl.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/payment/PaymentRestEndpointTest.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/payment/JsonInboundPaymentInfo.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/payment/PaymentRestEndpoint.java
- de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
https://github.com/metasfresh/metasfresh/issues/5856
>  Add payment rest endpoint

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/picking_list.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5538440_sys_gh5888_picking_list_view.sql
https://github.com/metasfresh/metasfresh/issues/5888
> 5888 Picklist ordered by locator name + dimensions

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/bpartnerProductDownload.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538750_sys_gh5908_DownloadPartnerProducts_SQL_Function.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538760_sys_gh5908_DownloadPartnerProducts_Process.sql
https://github.com/metasfresh/metasfresh/issues/5908
> @5908 Download Partner Product process

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Invoice_Root.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5538810_sys_gh5906_customer_invoice_creditmemo_report.sql
https://github.com/metasfresh/metasfresh/issues/5912
> #5912 Fixed overlaping text on customer invoice with credit memo

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/LocationDAO.java
https://github.com/metasfresh/metasfresh/issues/5800
> #5800 set the postal when creating a location

- de.metas.adempiere.adempiere/base/pom.xml
- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/AbstractExcelExporter.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538940_sys_gh5922_PricelistExcelProcess.sql
- de.metas.business/src/main/java/de/metas/pricing/process/M_Pricelist_Excel.java
- de.metas.report/report-service/pom.xml
- de.metas.util/pom.xml
- pom.xml
https://github.com/metasfresh/metasfresh/issues/5922
> Gh5922 Pricelist excel process

- de.metas.adempiere.adempiere/base/pom.xml
- de.metas.adempiere.adempiere/base/src/main/java-legacy/de/metas/impexp/excel/AbstractExcelExporter.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5538940_sys_gh5922_PricelistExcelProcess.sql
- de.metas.business/src/main/java/de/metas/pricing/process/M_Pricelist_Excel.java
- de.metas.report/report-service/pom.xml
- de.metas.util/pom.xml
- pom.xml
https://github.com/metasfresh/metasfresh/issues/5922
> Gh5922 2 pricelist excel process and updates needed for it

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/picking_list.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5538440_sys_gh5888_picking_list_view.sql
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/CreatePickingCandidatesCommand.java
https://github.com/metasfresh/metasfresh/issues/5888
> Gh5888_1 Fixed values displayed on quantity field 

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5539180_sys_gh5929_SetIsNaturalAccountTo_yes.sql
#5929 Set by default metasfresh C_Element to IsNaturalAccount ='Y'
> #5929 Set IsNaturalAccount to Yes

- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5539200_sys_gh5933_Add_Posted_To_Windows.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5539430_sys_gh5933_Add_Posted_To_Windows_2.sql
https://github.com/metasfresh/metasfresh/issues/5933
> #5933 add the Posted field to the document windows

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5539610_sys_gh5933_Translate_PostingStatus.sql
https://github.com/metasfresh/metasfresh/issues/5933
> Gh5933 Translate "Posting Status"

- de.metas.edi/src/main/sql/postgresql/ddl/views/EDI_DesadvPack_SSCC_Label.sql
- de.metas.edi/src/main/sql/postgresql/system/5539630_sys_gh5896_changed_loading_logic_for_address_name_columns.sql
refs:
https://github.com/metasfresh/metasfresh/issues/5896
> Changed loading logic for Business P. address name and HO address

- de.metas.edi/src/main/sql/postgresql/system/5539660_sys_gh5896_change_loading_logic_for_HOAddressStreet_and_BPAddressStreet.sql
refs: https://github.com/metasfresh/metasfresh/issues/5896
> Changed loading logic for BPartner address street and HO addr street.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5539870_sys_gh5947_Repair_DocAction_de_CH_Translations.sql
https://github.com/metasfresh/metasfresh/issues/5947
> #5947 use the right translations for DocAction, language 'de_CH'

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5539810_sys_gh5885_UpdateDpdTrackingURL.sql
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUShipperTransportationBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IInOutPackageDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUShipperTransportationBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/InOutPackageDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/ProcessPickingCandidatesCommand.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentScheduleHUTrxListener.java
- de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/I_M_ShipmentSchedule_QtyPicked.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/X_M_ShipmentSchedule_QtyPicked.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5539830_sys_gh5885_AddColumn_isAnonymousHuPickedOnTheFly.sql
https://github.com/metasfresh/metasfresh/issues/5885
> Add handling to process for adding InOut to ShipperTransportation when InOut has no HUs

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/process/C_Location_Geocoding_ScheduleUpdate.java
https://github.com/metasfresh/metasfresh/issues/5952
> Fix not all locations are scheduled for geocoding

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/MasterdataProvider.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JSONPaymentRule.java
https://github.com/metasfresh/metasfresh/issues/5800
> #5800 Support PaymentRule = DirectDebit in OLCand EndPoint

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/model/I_C_Order.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocumentLocationBL.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/model/IDocumentHandOverLocation.java
- de.metas.business/src/main/java/de/metas/order/OrderFactory.java
- de.metas.dunning/src/test/java/org/adempiere/document/service/impl/DummyDocumentLocationBL.java
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5539970_sys_gh5955_AddHandoverUser.sql
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/document/callout/DocumentLocation.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/document/impl/DocumentLocationBL.java
#5955 Display handoverlocation in sales order
> #5955 Implement handoverAddress

- de.metas.business/src/main/sql/postgresql/ddl/functions/AD_User_Record_Access_UpdateFrom_BPartnerHierarchy.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5540260_gh5970_AD_User_Record_Access_UpdateFrom_BPartnerHierarchy_process.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5540261_gh5970_AD_User_Record_Access_UpdateFrom_BPartnerHierarchy_DDL.sql
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5540270_sys_gh5970_AD_User_Record_Access_UpdateFrom_BPartnerHierarchy_scheduler_deactivated.sql
https://github.com/metasfresh/metasfresh/issues/5970
> AD_User_Record_Access_UpdateFrom_BPartnerHierarchy

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/jsonpersister/JsonPersisterService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/jsonpersister/ShortTermContactIndex.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/bpartner/impl/BPartnerRecordsUtil.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/bpartner/impl/BpartnerRestControllerTest.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/bpartner/impl/ContactRestControllerTest.java
- de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/bpartner/impl/BpartnerRestControllerTest.snap
- de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/bpartner/impl/ContactRestControllerTest.snap
- de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/bpartner/impl/bpartnercomposite/JsonRetrieverServiceTest.snap
* fix bug
* add additional tests and improve existing ones
https://github.com/metasfresh/metasfresh/issues/5973
> 5973-app - NPE when update Contact via BPartner-CreateOrUpdate EP

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5540360_sys_gh5980_MakeTourSearchable.sql
#5980 Tour Field as Search Field in Sales Order
> #5980 Make Tour searchable

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540380_sys_gh5982_AddColumn_HandoverLocation_to_GridView.sql
https://github.com/metasfresh/metasfresh/issues/5982
> Add column Handover Location to grid view for window "Sales Order Disposition" (540095).

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540390_sys_gh5985_AddTourToFilterAndGridviewInShipmentWindow.sql
https://github.com/metasfresh/metasfresh/issues/5985
> Add Tour to grid view and filter for Shipment window

- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandEffectiveValuesBL.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/DefaultOLCandValidator.java
* OLCandEffectiveValuesBL - try to use price-UOM before falling back to stock-UOM
* DefaultOLCandValidator - minor cohesion improvement
> make the effective UOM more reasonable if none was given from outside

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUShipperTransportationBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUShipperTransportationBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/ProcessPickingCandidatesCommand.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/ShipmentScheduleHUTrxListener.java
- de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
- de.metas.handlingunits.base/src/main/sql/postgresql/system/5539950_sys_gh5885_Fix_IsAnonymousHuPickedOnTheFly_Column_name.sql
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/I_M_ShipmentSchedule_QtyPicked.java
- de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/X_M_ShipmentSchedule_QtyPicked.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/process/M_Tour_Instance_CreateFromSelectedDeliveryDays.java
Followup of the review: https://github.com/metasfresh/metasfresh/pull/5945#pullrequestreview-334728891
Task: https://github.com/metasfresh/metasfresh/issues/5885
> Tour dependent adjustments: finetuning

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/shipmentDispositionExcelDownload.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540400_sys_gh160_fixedShipmentDispositionFunction.sql
https://github.com/metasfresh/ic114/issues/160
> #160 Fixed Shipment Disposition Export Function.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540510_sys_gh5995_UpdateFiltersForChangeLogWindow.sql
https://github.com/metasfresh/metasfresh/issues/5995
> Add Table filter to window Change Log

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/uom/UOMConstants.java
- de.metas.business/src/main/java/de/metas/customs/CustomsInvoiceService.java
https://github.com/metasfresh/metasfresh/issues/5999
> Gh5999 2 convert qtys of customs invoice to kg

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540700_sys_gh5931_UpdateBankAccountTrl.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540710_sys_gh5931_AddEsrErrorMessageTRL.sql
- de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRImportDAO.java
- de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRImportEnqueuer.java
- de.metas.payment.esr/src/main/sql/postgresql/system/5538710_sys_gh5931_ShowHashValueInTheEsrWindow.sql
https://github.com/metasfresh/metasfresh/issues/5931
> ESR Import Hashvalue after double upload

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5540900_sys_gh160_updatedPublicShipmentDispositionExportFunction.sql
https://github.com/metasfresh/ic114/issues/160
> #160 Updated Shipment Disposition Export Function.

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/customs_invoice/report_details_footer.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Dunning_Report_description.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getCustomsInvoiceShipmentAddressorNull.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getOrderAddressorNull.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5540960_sys_gh6014_RenameCustomsInvoiceFunctions.sql
#6014 Compute properly sum catch weight in customs invoice document
> #6014 Compute weight

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_details.jrxml
#6006 Picklist cannot be printed
> #6006 Fix picklist

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541030_sys_gh5895_AddedTranslationsForWorkflowTemplateMenuAndElements.sql
https://github.com/metasfresh/metasfresh/issues/5895
> #5895 Added Translations For Workflow Template Menu And Elements.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541070_sys_gh5940_Display_DefaultForProduct_Flag.sql
https://github.com/metasfresh/metasfresh/issues/5940
> #5940 display isDefaultForProduct flag in window Product, tab CU-TU

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/JsonRetrieverService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/jsonpersister/JsonPersisterService.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/BPartnerMasterDataProvider.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/request/JsonRequestLocation.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/response/JsonResponseLocation.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JsonOLCandCreateRequest.java
- de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerLocation.java
- de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
- de.metas.business/src/main/java/de/metas/bpartner/composite/repository/ChangeLogUtil.java
https://github.com/metasfresh/metasfresh/issues/6024
> Gh6024 bpartnerName in location olcand json

- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/model/IQuery.java
- de.metas.business/src/main/java/de/metas/inout/IInOutBL.java
- de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
- de.metas.business/src/main/java/de/metas/invoice/impl/InvoiceLineBL.java
- de.metas.business/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java
- de.metas.business/src/main/java/de/metas/pricing/IPricingResult.java
- de.metas.business/src/main/java/de/metas/pricing/rules/AggregatedPricingRule.java
- de.metas.business/src/main/java/de/metas/pricing/rules/BOMPriceCalculator.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingResult.java
- de.metas.contracts/src/main/java/de/metas/contracts/interceptor/M_ShipmentSchedule.java
- de.metas.contracts/src/main/java/de/metas/contracts/pricing/SubscriptionPricingRule.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inoutcandidate/callout/M_ShipmentSchedule.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_ShipmentSchedule.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandPIIPPriceValidator.java
- de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_HandlerDAO.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ManualCandidateService.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/views/C_OrderLine_ID_With_Missing_ShipmentSchedule_v.sql
- de.metas.util/src/main/java/de/metas/util/PlainStringLoggable.java
* enable pricing rule to provide audit information (e.g. why they did or did not apply)
* done in AggregatedPricingRule
* add the logs as parameter to ProductNotOnPriceListException
* also bunch of smaller cleanups
> support loggables in pricing rules

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Campaign_Price.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Campaign_Price.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541230_sys_gh5991_C_Campaign_Price_C_UOM_ID.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541231_cli_gh5991_C_Campaign_Price_C_UOM_ID_migate.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541250_sys_gh5991_C_Campaign_Price_C_UOM_ID_mandatory.sql
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPrice.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceRepository.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/callout/C_Campaign_Price.java
- de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
https://github.com/metasfresh/metasfresh/issues/5991
> C_Campaign_Price.C_UOM_ID

- de.metas.business/src/main/java/de/metas/phonecall/model/interceptor/C_Phonecall_Schema_Version.java
- de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schema_GenerateSchedules.java
- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallScheduleService.java
- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallSchemaRepository.java
https://github.com/metasfresh/metasfresh/issues/6031
> #6031 Handle Schema Modification in Version

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541410_sys_gh6035_UOM_Editable_CreditMemo_Lines.sql
https://github.com/metasfresh/metasfresh/issues/6035
> #6035 Make UOM editable in Invoice Line

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/shipmentDispositionExcelDownload.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541510_sys_gh160_MovedExportShipmentDispositionsActionToSitemap.sql
https://github.com/metasfresh/metasfresh/issues/6040
> #3507 Moved Export Shipments Action to Sitemap and Showing QTYCU now.

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Average_Product_Prices.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5541520_sys_gh6030_report_Average_Product_Prices_negate_il.PriceActual_WhenTheInvoiceHasDoctype_CreditMemo.sql
https://github.com/metasfresh/metasfresh/issues/6030
> Report Average Product Prices: Negate in case of Credit Memo

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/DB_PostgreSQL.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/dao/selection/QuerySelectionHelper.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/dao/selection/QuerySelectionHelperTest.java
- de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/dao/impl/TypedSqlQueryTests.java
- de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java-legacy/org/compiere/server/AdempiereServer.java
- de.metas.contracts/src/main/java/de/metas/contracts/interceptor/MainValidator.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandsProcessorExecutor.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/modelvalidator/OrderCandidate.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ShipmentSchedule_UpdateAsync.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/ConfigValidator.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/modelvalidator/SwatValidator.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5541430_sys_gh6013app_M_ShipmentSchedule_UpdateAsync_process.sql
https://github.com/metasfresh/metasfresh/pull/new/gh6013-app_2
> Gh6013-app_2

- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallSchemaRepository.java
https://github.com/metasfresh/metasfresh/issues/6031
> #6031 repairment: only update the lines with a  different schema

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/impl/ShipmentScheduleInvalidateRepository.java
https://github.com/metasfresh/metasfresh/issues/6013
> when invalidating a sched with ASI, make sure that also related scheds without ASI are invalidated

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidationEngine.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidator.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/AnnotatedModelInterceptor.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/DocTimingType.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/ModelChangeType.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/TimingType.java
- de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/modelvalidator/ModelChangeTypeTest.java
https://github.com/metasfresh/metasfresh/issues/6001
> measure and log how much each model interceptor took

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/exportSalesInvoicesInDateRange.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541200_sys_gh207_AddedExportSalesInvoicesAction.sql
https://github.com/metasfresh/metasfresh/issues/6032
> #3552 Added Action to export number of sales invoices in specific date range for business partners.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/priceSchemaExcel.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541620_sys_gh6048_PriceSchemaExcel_Process.sql
https://github.com/metasfresh/metasfresh/issues/6048
> #6048 Extract sql as process; add isSold parameter

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541680_sys_gh5987_TRL_And_Zoom_ShipmentLine_To_CustomsInvoiceLine.sql
https://github.com/metasfresh/metasfresh/issues/5987
> #5987 TRL and zoom in the Shipment Line to Customs Invoice Line window

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541720_sys_gh3699ClearerReportsParameterNames.sql
https://github.com/metasfresh/metasfresh/issues/6055
> #6055 Clearer Umsatzreport field names and search fields instead of dropdowns.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5541590_sys_gh3701_ShowingBomFormulaInStücklistenbestandteileWindow.sql
https://github.com/metasfresh/metasfresh/issues/6057
> #6057 Now showing BOM tab in Stucklistenbestandteile window.

- de.metas.business/src/main/java/de/metas/phonecall/model/interceptor/C_Phonecall_Schema_Version.java
- de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallSchemaRepository.java
https://github.com/metasfresh/metasfresh/issues/6031
> Gh6031 3 update existing schedules on schema change

- README.md
@metas-mk feel free to take a look when you have time
> suggesting furter shields - not all of them make sense

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550280_sys_gh160RemovedActionFromSingleView.sql
https://github.com/metasfresh/metasfresh/issues/6040
> #3507 Removed action from single view.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550270_sys_gh3699RemovedUnnecessaryTables.sql
https://github.com/metasfresh/metasfresh/issues/6055
> #3699 Removed unnecessary db tables.

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/CalloutEngine.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/TableRecordMDC.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/callout/api/impl/CalloutExecutor.java
- de.metas.async/src/main/java/de/metas/async/api/IWorkPackageParamsBuilder.java
- de.metas.async/src/main/java/de/metas/async/spi/WorkpackageProcessorAdapter.java
- de.metas.edi/src/main/java/de/metas/edi/api/impl/EDIDocumentBL.java
- de.metas.edi/src/main/java/de/metas/edi/callout/C_Invoice.java
- de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Invoice.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/ShipmentSchedulesMDC.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoicingParams.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/ICNetAmtToInvoiceChecker.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidate2WorkpackageAggregator.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoicingParams.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/InvoiceCandWorkpackageProcessor.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/C_Invoice_Candidate_Builder.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueueToInvoiceTestBase.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestFixedDateInvoicedAndDateAcct.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestUpdatedLocationAndUser.java
* AggregationEngine:
* give precedence to the dataAcct and dateInvoiced parameters, if specified
* if the resp date is not given as paremt, then give precedence to the ICs DateInvoiced resp DateAcct
* also enhance logging with MDCs here and there
* InvoiceCandidate2WorkpackageAggregator:
* when enqueing ICs for invoicing, then provide the process parameters to the respective workpackages
* (=> this is more or less the actual fix)
https://github.com/metasfresh/metasfresh/issues/6081
> 6081-app - Generate Invoices Action Parm "Invoicedate" is not taken

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/BPartnerContactId.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPartnerInfo.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/validationRule/impl/ValidationRuleFactory.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/BPartnerMasterDataProvider.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/JsonConverters.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/MasterdataProvider.java
- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImpl.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/TestMasterdata.java
- de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.snap
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JsonOLCandCreateRequest.java
- de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
- de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
- de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/storage/cc/api/impl/CCAbleDocumentFactoryService.java
- de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/I_C_OLCand.java
- de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
- de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandEffectiveValuesBL.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCand.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandBL.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandEffectiveValuesBL.java
- de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5550420_sys_gh6079-app_div_olcand_tweaks_and_fixes.sql
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/impex/api/impl/InputDataSourceDAO.java
WIP:
* don't return bpartner, locaiton and contact one by one, but return a bpartnerInfo instance
* return handover resp. dropship info a Optional, so the caller itself can decide whether to fallback in case there is no explicitly specified handover/dropship
https://github.com/metasfresh/metasfresh/issues/6079
> 6079-app - OLCand fix handover and dropship processing

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup/legacy/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup/legacy/report_description.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5550360_sys_gh923_AddWarehosueParameter.sql
#6077 Add grouping warehouse in Bestellkontrolle report
> #6077 adding warehouse filter

- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderDocumentLUTUConfigurationHandler.java
refs: https://github.com/metasfresh/metasfresh/issues/6085
> Presetting of Qty CU and default LU in action receipt

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/model/FactAcctZoomProvider.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ModelValidationEngine.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHU.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilderTest.java
https://github.com/metasfresh/metasfresh/issues/6087
> Shipment cannot be created with qtytodeliveroverride = 0/ NULL

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocTypeId.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/TableRecordMDC.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/organization/impl/OrgDAO.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/JavaProcess.java
- de.metas.async/src/main/java/de/metas/async/processor/impl/WorkpackageProcessorTask.java
- de.metas.edi/src/main/java/de/metas/edi/api/impl/EDIDocumentBL.java
- de.metas.edi/src/main/java/de/metas/edi/callout/C_Invoice.java
- de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Invoice.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/ShipmentSchedulesMDC.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceHeader.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/InvoiceCandidateQuery.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/callout/C_Invoice_Candidate.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/ManualCandidateHandler.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/AbstractICTestSupport.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/C_Invoice_Candidate_Builder.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainInvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractAggregationEngineTestBase.java
- de.metas.vertical.creditscore/creditpass/src/main/java/de/metas/vertical/creditscore/creditpass/model/CreditPassConfigPaymentRule.java
https://github.com/metasfresh/metasfresh/issues/6096
> Gh ic aggregation

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550500_sys_gh6091-phonecall-list-datagrid-sequence.sql
https://github.com/metasfresh/metasfresh/issues/6091
> Adjust seqence of columns in phonecall list #6091

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/print/ReportEngine.java
- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/print/ReportCtl.java
- de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/service/impl/PrinterRoutingDAO.java
https://github.com/metasfresh/metasfresh/issues/5949
> Gh5949 2 support printing with no print format

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550570_sys_gh3699AddedRightEnglishTranslations.sql
https://github.com/metasfresh/metasfresh/issues/6055
> #3699 Umsatzreport geschäftspartner Action Parm sync

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/dao/selection/pagination/PaginationService.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/impl/POBufferedIterator.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/processor/api/impl/TrxItemChunkProcessorExecutor.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/order/api/impl/HUOrderBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleWeightNetAdjuster.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleQtysHelper.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidate.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_BPartner.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainInvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateFixtureHelper.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidateTest.java
- de.metas.swat/de.metas.swat.base/src/test/resources/de/metas/invoicecandidate/internalbusinesslogic/invoiceCandidateTestFixtures/sales_immediate_catchWeight_qtyInvoicedOverride_less_than_qtyOrdered.json
* The bug happend when invoicableQtyBaseOn=CatchWeight and invoiceRule=Immediate and QtyToInvoiceOverride<QtyOrdered
* Now it's fixed in InvoiceCandidate
* Also add logging to the places that this time i had to remote-debug
* Also change "=>" to "->" in various log messages; proposing a common practice there
https://github.com/metasfresh/metasfresh/issues/6104
> Support: Product cannot be invoiced, why?

- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc.java
- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_MatchInv.java
- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Fact.java
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5550750_cli_dont_use_currency_balancing.sql
- de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java-legacy/org/adempiere/serverRoot/servlet/ServerMonitor.java
- de.metas.adempiere.libero.libero/src/main/java/de/metas/costing/methods/ManufacturingAveragePOCostingMethodHandler.java
- de.metas.adempiere.libero.libero/src/main/java/de/metas/costing/methods/ManufacturingStandardCostingMethodHandler.java
- de.metas.async/src/main/java/de/metas/async/model/validator/Main.java
- de.metas.business/src/main/java/de/metas/costing/CurrentCost.java
- de.metas.business/src/main/java/de/metas/costing/impl/CostingService.java
- de.metas.business/src/main/java/de/metas/costing/methods/AverageInvoiceCostingMethodHandler.java
- de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- de.metas.business/src/main/java/de/metas/costing/methods/CostingMethodHandlerUtils.java
- de.metas.business/src/main/java/de/metas/costing/methods/LastInvoiceCostingMethodHandler.java
- de.metas.business/src/main/java/de/metas/costing/methods/LastPOCostingMethodHandler.java
- de.metas.business/src/main/java/de/metas/costing/methods/StandardCostingMethodHandler.java
- de.metas.business/src/main/java/de/metas/quantity/QuantityUOMConverter.java
- de.metas.business/src/main/java/de/metas/quantity/QuantityUOMConverters.java
- de.metas.business/src/main/java/de/metas/uom/IUOMConversionBL.java
https://github.com/metasfresh/metasfresh/issues/6106
> Gh6106 accounting fixes

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550780_sys_gh3852_inactivate_PricelistExcel_process.sql
- de.metas.report/de.metas.report.jasper.commons/src/main/java/de/metas/report/server/OutputType.java
- de.metas.report/de.metas.report.jasper.commons/src/main/java/de/metas/report/server/ReportConstants.java
- de.metas.report/report-service/src/main/sql/postgresql/system/5550490_sys_gh3852_add_formatParam_for_report_processes.sql
https://github.com/metasfresh/metasfresh/issues/3852
> Export of Jasper Reports to Excel

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550800_sys_gh3699FixedEnglishTranslationsForComparisonYearAndWeek.sql
https://github.com/metasfresh/metasfresh/issues/6055
> #6055 Fixed english translations for comparison year and week.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5550980_sys_gh6065_Printing_Windows_Cosmetics.sql
https://github.com/metasfresh/metasfresh/issues/6065
> #6065 small details in printing windows

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551070_sys_gh6065_Display_Created_PrintPaket.sql
https://github.com/metasfresh/metasfresh/issues/6065
> #6065 display Created in Print Paket

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551150_sys_gh6065_Printing_Windows_Org_Active_Fields.sql
https://github.com/metasfresh/metasfresh/issues/6065
> #6065 more changes in printing windows

- de.metas.business/src/main/java/de/metas/shipment/model/interceptor/M_InOut.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/model/validator/M_InOut.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentSchedulePA.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_InOut_Shipment.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Invoice.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5551020_sys_gh6120-app_close_partiallyshipped_sysconfig.sql
- pom.xml
https://github.com/metasfresh/metasfresh/issues/6120
> Gh6120 app

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/LocationDAO.java
- de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerImportTableSqlUpdater.java
https://github.com/metasfresh/metasfresh/issues/6130
> Gh6130 bpartner import improvements

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/model/interceptor/AD_Document_Action_Access.java
https://github.com/metasfresh/metasfresh/issues/6125
> #6125 fixed cache resetion for existing documents.

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/IUserBL.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/impl/UserBL.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/impl/UserDAO.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551360_sys_gh6139-app_fix_misleading_message_add_mail_field_description.sql
* IUserBL remove an unused public method from the API
* UserBL improve logging
* SQL
* have specific description message for email field in the user window
* improve misleading AD_Message for NoEMailFoundForLoginName
https://github.com/metasfresh/metasfresh/issues/6139
> 6139-app - Soothe FUD regarding user login

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551440_sys_gh6072_Tour_In_Order_Grid.sql
https://github.com/metasfresh/metasfresh/issues/6072
> #6072 make sure tour is displayed in purchase order grid

- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/model/IQuery.java
- de.metas.business/src/main/java/de/metas/shipping/ShipperTransportationPOCopyRecordSupport.java
- de.metas.business/src/main/java/de/metas/shipping/model/validator/M_ShipperTransportation.java
- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5551620_sys_gh6156_transportationOrder_window_adjustments.sql
refs: https://github.com/metasfresh/metasfresh/issues/6156
> Transportation Order adjustments

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocTypeId.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/LoggableWithThrowableUtil.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/logging/TableRecordMDC.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/IQueryBuilder.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551770_sys_gh6159-app_process_executed_msg.sql
- de.metas.async/src/main/java-gen/de/metas/async/model/I_C_Queue_WorkPackage_Log.java
- de.metas.async/src/main/java-gen/de/metas/async/model/X_C_Queue_WorkPackage_Log.java
- de.metas.async/src/main/java/de/metas/async/api/WorkpackageLogEntry.java
- de.metas.async/src/main/java/de/metas/async/api/WorkpackageLogsRepository.java
- de.metas.async/src/main/java/de/metas/async/processor/impl/WorkpackageLoggable.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/interceptor/C_Invoice_Candidate.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/process/C_Invoice_Candidate_CreateOrUpdateCommissionInstance.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionInstanceRequestFactory.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/InvoiceCandidateFacadeService.java
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5551680_sys_gh6159-app_C_Invoice_Candidate_CreateOrUpdateCommissionInstance.sql
- de.metas.edi/src/main/java/de/metas/edi/callout/C_Invoice.java
- de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Invoice.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/ShipmentSchedulesMDC.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/UpdateInvalidShipmentSchedulesWorkpackageProcessor.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
* create process
* highlight: attempt to notify user with a link to AD_PInstance window
* refactor code from model interceptor/C_Invoice_Candidate.java into a service
metasfresh/metasfresh#6159
> 6159-app - Create commission data from existing invoice candidates

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/ProductsTopRevenue.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getProductCurrentStock.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getProductRevenue.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getTotalRevenue.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551560_sys_gh6150_getProductRevenue_Function.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551570_sys_gh6150_getProductCurrentStock_Function.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551580_sys_gh6150_getTotalRevenue_Function.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551600_sys_gh6150_ProductsTopRevenue_Function.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551610_sys_gh6150_ProductsTopRevenue_Process.sql
https://github.com/metasfresh/metasfresh/issues/6150
> #6150 top Revenue Products

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551850_sys_gh3936DropPublicTempTablesFromDatabaseSeed.sql
https://github.com/metasfresh/metasfresh/issues/6170
> #6170 Removing current public temp tables.

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/impl/DeliveryDayDAO.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/TourPlanningTestBase.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/api/impl/DeliveryDayBLTest.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/api/impl/DeliveryDayDAO_retrieveDeliveryDay_Test.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/integrationtest/TourInstance_DeliveryDay_ShipmentSchedule_IntegrationTest.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/integrationtest/TourPlanning_PreparationDate_IntergrationTest.java
https://github.com/metasfresh/metasfresh/issues/6174
> Gh6174 invalid delivery day if the partner doesn't match

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551870_sys_gh6175FixedSelectedItemsMessage.sql
https://github.com/metasfresh/metasfresh/issues/6175
> #6175 Fixed selected items message.

- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceRepository.java
refs: https://github.com/metasfresh/metasfresh/issues/6168
> Enhance campaign pricing to apply also based on pricing system

- de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
- de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentPackingMaterialLinesBuilder.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilder.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineNoInfo.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/AbstractAggregateShipmentHUShipmentProcessIntegrationTest.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/AbstractHUShipmentProcessIntegrationTest.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/HUShipmentProcess_1TUwith2VHU_splitTo_1LUwith1TU_IntegrationTest.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/HUShipmentProcess_LineNumberTests.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilderTest.java
- de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineNoInfoTest.java
* implement feature, WIP - still needs testing
* unrelated improvement: use timezone when converting from localdate to Timestamp
#6172
> 6172-app - Shipmentline LineNos from orderLine if feasible

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5552090_sys_gh6182_AddIBANStructureForDenmark.sql
#6182 Add IBAN structure for DK
> #6182 Add IBAN structure for DK

- de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5551890_sys_gh6156_mark_docStatus_as_calculated_column.sql
https://github.com/metasfresh/metasfresh/issues/6156
> Mark ShipperTransportation.docStatus as calculated column.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5552160_sys_gh6125UpdatedBankStatementDocType.sql
https://github.com/metasfresh/metasfresh/issues/6125
> #6125 updated bank statement doc type.

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/ITaxBL.java
- de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java
- de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/invoicecandidate/CommissionShareHandler.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tax/api/impl/TaxBL.java
https://github.com/metasfresh/metasfresh/issues/6186
> 6186-app - Support tax-exempt commission for small business sales reps

- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/form/FreshPackingMd.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/Packageable.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/PackagingDAO.java
https://github.com/metasfresh/metasfresh/issues/6116
> Packageable: use enums instread of strings

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5552240_sys_gh6167RenameVerrechnungBillcare.sql
https://github.com/metasfresh/metasfresh/issues/6167
> #6167 Rename Verrechnung Billcare Process to generic name.

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5552420_sys_gh6197_AddSysConfigVarsForTimeouts.sql
- de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/jasper/client/RemoteServletInvoker.java
#6197 Adjust timeout so that big report to be able to run
* Increase default values to 15 s for connection and 20 for reading timeout
* Add sys config variables in the DB
> #6197 Increase timeouts

- de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/impl/InvoiceLineHUPackingAware.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/callout/C_InvoiceLine.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.order/5552410_sys_gh6201_add_packing_item_validation_rule_for_invoiceLine.sql
https://github.com/metasfresh/metasfresh/issues/6201
> Support packing instructions for invoice line 'Batch entry'

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/customs_invoice/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/customs_invoice/report_details_footer.jrxml
#6207 Minor adjustments to customs invoice document
> #6207 Increase fields size

- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceRepository.java
refs: https://github.com/metasfresh/metasfresh/issues/6168
(cherry picked from commit 31ce35a50f17909c3840f2a386334620f67ed873)
> Enhance campaign pricing to apply also based on pricing system (#6169)

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Invoice_Candidate.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/IInvoiceCandidateHandler.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLSimpleTest.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLTest.java
* fix problem: if the non-item IC is a freight.cost-IC and it's *the only one of its sales order*..then stuff still needs to work
#6184
> Not-Item products not invoicable unless InvoiceRule is immediate

- de.metas.business/src/main/java/de/metas/pricing/rules/AggregatedPricingRule.java
- de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
- de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateBLTest.java
- de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandBL.java
> Gh5.132 last christmas 6210app

- de.metas.acct.base/src/main/sql/postgresql/ddl/functions/AccountSheetReport.sql
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5552590_sys_gh6121_UpdateProcessParamTypeToTableFromSearch.sql
https://github.com/metasfresh/metasfresh/issues/6121
> Jasper Report: `Account Sheet` - `Kontenblatt`

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5552760_sys_gh6219_Add_Surcharge_When_Price_Zero.sql
https://github.com/metasfresh/metasfresh/issues/6219
> #6219 add surcharge to prices that are zero

- de.metas.acct.base/src/main/sql/postgresql/ddl/functions/ProfitAndLossReport.sql
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5552600_sys_gh6148_Add_ExcludeEmptyLines_ParamToProcess.sql
https://github.com/metasfresh/metasfresh/issues/6148
> Jasper Report: Profit & Loss Report

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/JsonObjectMapperHolder.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/provider/openstreetmap/NominatimOSMGeocodingProviderImpl.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/provider/openstreetmap/NominatimOSMGeographicalCoordinatesJSON.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/location/geocoding/provider/openstreetmap/NominatimOSMGeocodingProviderImplTest.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/location/geocoding/provider/openstreetmap/TestDeserialisation.java
https://github.com/metasfresh/metasfresh/issues/6217
> Fix OSM/Nominatim Geocoding provider not working after lombok upgrade

- de.metas.materialtracking/src/main/java/de/metas/materialtracking/MaterialTrackingPOCopyRecordSupport.java
- de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/validator/M_Material_Tracking.java
- de.metas.materialtracking/src/main/sql/postgresql/system/50-de.metas.materialtracking/5552750_gh_mark_MaterialTracking_lot_column_as_calculated.sql
refs: https://github.com/metasfresh/metasfresh/issues/6223
> Material Tracking Copy action

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/customerItemStatistics.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5552780_sys_gh6133_Add_Language_CustomerItemStatistic_Process.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5552790_sys_gh6133_Add_Language_CustomerItemStatistic_SQL_Function.sql
https://github.com/metasfresh/metasfresh/issues/6133
> Gh6133 4 Add language to CustomerItemStatistics

- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/dba_seq_check_native.sql
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5552990_sys_gh6246_dba_seq_check_native_isSlowOnTBPsMachine.sql
https://github.com/metasfresh/metasfresh/issues/6246
> Function `dba_seq_check_native` takes 2.5 minutes to run on @TheBestPessimist's machine sometimes

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupFactory.java
https://github.com/metasfresh/metasfresh/issues/6154
> #3426 fixed duplicate 'value' name in sql select.

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/createC_BP_Group_Acct.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/createM_Product_Acct.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/createM_Product_Category_Acct.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5553110_sys_gh6255_AddFunctionForCreatingDefaultAccounts.sql
* createM_Product_Category_Acct()
* createM_Product_Acct()
* createC_BP_Group_Acct()
> #6255 Create functions for easily creating default accounts fro M_Produc_category, M_Product, C_BP_Group and C_Bpartner 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/ProductsTopRevenue.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getProductRevenue.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getTotalRevenue.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5553120_sys_gh6150_TopProducts_Improve_Efficiency.sql
https://github.com/metasfresh/metasfresh/issues/6150
> #6150 improve queries efficiency

- de.metas.acct.base/src/main/sql/postgresql/ddl/functions/BusinessPartnerAccountSheetReport.sql
- de.metas.acct.base/src/main/sql/postgresql/ddl/functions/gh6214.sql
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5552900_gh6214_Add_BusinessPartnerAccountSheetReport.sql
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5553020_sys_gh6214_AddFunctionMigrationScript.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/getBPOpenAmtToDate.sql
https://github.com/metasfresh/metasfresh/issues/6214
> Jasper Report: Customer/ Vendor Kontenblatt (Account details)

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5553260_sys_gh6264_MoveSomeReportsFromSwingToWebUi.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5553270_sys_gh6264_UpdateTRL.sql
https://github.com/metasfresh/metasfresh/issues/6264
> Add some reports to webui

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5553280_sys_gh6266_Make_GeocodingConfig_Unique_OnlyShowColumn_GeocodingProvider_InGridView.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5553340_sys_gh6266_AddWhereClauseToUniqueIndex.sql
https://github.com/metasfresh/metasfresh/issues/6266
> Only show the `Geocoding Provider` column in grid view in `Geocoding Config` window

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551870_sys_gh6175FixedSelectedItemsMessage.sql
https://github.com/metasfresh/metasfresh/issues/6175
> #6175 Also fixed 'Select All on this page' message as it's related to the one above it.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5551870_sys_gh6175FixedSelectedItemsMessage.sql
https://github.com/metasfresh/metasfresh/issues/6175
> #6175 Added new translations.

- de.metas.business/src/main/java/de/metas/quantity/StockQtyAndUOMQty.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5552970_sys_gh6231-app_tweak_IC_window.sql
* fix the actual bug
* display the error-flag much more prominently
#6231
> 6231-app - UOM related error in invoice candidate updates

- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_MatchPO.java
- de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_MatchPO.java
https://github.com/metasfresh/metasfresh/issues/6287
> Avoid MatchPO posting

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/parser/FileImportReader.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/parser/ImpDataParser.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/parser/FileImportReaderTest.java
- de.metas.adempiere.adempiere/base/src/test/resources/de/metas/impexp/parser/NumberOfEmptyLinesIsPreserved.csv
- de.metas.adempiere.adempiere/base/src/test/resources/de/metas/impexp/parser/OnlyAppendIfInQuotesPreserveFirstLine.csv
- de.metas.adempiere.adempiere/base/src/test/resources/de/metas/impexp/parser/regularlines.csv
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5553665_sys_gh6289_Add_DebitStmtAmt_And_CreditStmtAmt_ToBankStatementImport.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5553700_sys_gh6289_AddFieldsToWebUI.sql
- de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/I_I_BankStatement.java
- de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/X_I_BankStatement.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java
https://github.com/metasfresh/metasfresh/issues/6289
> Add `DebitStmtAmt` and  `CreditStmtAmt` to `I_BankStatement`

- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
https://github.com/metasfresh/metasfresh/issues/6295
> Pay Selection: Create from customer Direct Debit shall select only the invoices with PaymentRule=DirectDebit

- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5553740_sys_gh6190_SetDefaultParametersForReport_SummaryAndBalanceReport.sql
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5553750_sys_gh6190_Fix_SummaryAndBalanceReport.ExcludeEmptyLines_flag.sql
https://github.com/metasfresh/metasfresh/issues/6190
> Fix `SummaryAndBalanceReport.ExcludeEmptyLines` flag

- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionInstanceService.java
- de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/repos/InvoiceCandidateRecordHelper.java
- de.metas.contracts/src/main/java/de/metas/contracts/pricing/trade_margin/CustomerTradeMarginPricingRule.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tax/api/impl/TaxBL.java
> compute the base commission points always without tax

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5553820_gh566_BankStatementWindow_Improvements.sql
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java
https://github.com/metasfresh/metasfresh/issues/6301
> Bank Statement Window and Import Improvements

- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BP_BankAccount.java
- de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BP_BankAccount.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554000_gh6310_ChangeColumnTypesToDictionary.sql
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/api/impl/BPBankAccountDAO.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/exception/BankingException.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaymentRequestBL.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/modelvalidator/C_PaySelectionLine.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/paymentdocumentform/WEBUI_Import_Payment_Request_For_Purchase_Invoice.java
- de.metas.payment.esr/src/main/java/de/metas/payment/api/impl/ESRPaymentStringDataProvider.java
- de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRBPBankAccountDAO.java
- de.metas.payment.esr/src/main/java/de/metas/payment/spi/impl/ESRCreaLogixStringParser.java
- de.metas.payment.esr/src/test/java/de/metas/payment/esr/api/InvoiceReferenceNosTest.java
- de.metas.payment.esr/src/test/java/de/metas/payment/esr/api/impl/ESRBPBankAccountDAOTest.java
- de.metas.payment.esr/src/test/java/de/metas/payment/esr/api/impl/ESRRegularLineMatcherTest.java
https://github.com/metasfresh/metasfresh/issues/6310
> Read Payment String -> Payment Selection, Bancaccount not automatically selected for Reference

- de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRBPBankAccountDAO.java
Improve javadoc
Thanks tobi
https://github.com/metasfresh/metasfresh/issues/6310
> Read Payment String -> Payment Selection, Bankaccount not automatically selected for Reference

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/bpartner_changes/report.jrxml
> #6311 Rename jasper report `Revisionsstelle Geschäftspartner` to `Stammdaten Mutationsprotokoll` and its translations.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554200_sys_gh6311RenameRevisionstelleGeschaftspartner.sql
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/bpartner_changes/report.jrxml
> Rename Revisionstelle Geschaftspartner

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/geocoding/asynchandler/LocationGeocodeEventRequest.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/location/geocoding/asynchandler/LocationGeocodeEventRequestSerialisationTest.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/location/geocoding/provider/openstreetmap/NominatimOSMGeographicalCoordinatesJSONDeserialisationTest.java
Add workaround for jackson
https://github.com/metasfresh/metasfresh/issues/6217
> Add deserialisation test for LocationGeocodeEventRequest

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/impl/ColumnBL.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554310_sys_gh6329SetDefaultColumnsToIsCalculated.sql
> #6329 set Standard columns to iscalculated = 'Y';

- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportProcess.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/C_BankStatement_ImportAttachment.java
https://github.com/metasfresh/metasfresh/issues/6338
> Bugfix" Bank Statement Lines are sometimes added to another Bank Statement during import 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554220_sys_gh6298_Update_AD_Org_ID_InProcessesToSearch.sql
https://github.com/metasfresh/metasfresh/issues/6298
> Unconditionally migrate `AD_Org_ID` process parameter to `Search` from whatever it is now

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554390_gh6301_UpdateTrl.sql
https://github.com/metasfresh/metasfresh/issues/6301
> Update `BankStatementLine.StatementAmount` trl

- de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImpl.java
- de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JsonOLCandCreateRequest.java
- de.metas.monitoring/pom.xml
- de.metas.monitoring/src/main/java/de/metas/monitoring/adapter/NoopPerformanceMonitoringService.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/adapter/PerformanceMonitoringService.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/adapter/PerformanceMonitoringServiceUtil.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/adapter/apm/APMPerformanceMonitoringService.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/api/IMeter.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/api/IMonitoringBL.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/exception/MonitoringException.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/NewManualInvoiceCandidate.java
- pom.xml
* port parts of PR https://github.com/metasfresh/metasfresh/pull/6254
* add spans to OrderCandidatesRestControllerImpl
* also capture exceptions
* remove/deprecate some of de.metas.monitoring stuff
* also update to lombok 1.18.10
metasfresh/metasfresh#6334
> 6334-app - Instrument Sales order candidate endpoint for monitoring

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554450_sys_gh6343SetDefaultDocTypeToPurchaseOrder.sql
https://github.com/metasfresh/metasfresh/issues/6343
> #6343 Set Default value to purchase order doctype.

- de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
https://github.com/metasfresh/metasfresh/issues/6348
> #6348 avoid null qty in pricing context

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554580_sys_gh6346UpdateRequestWindowAndAddProcessToShipment.sql
https://github.com/metasfresh/metasfresh/issues/6346
> #6346 Added Create Request Process to Shipment Window and Customized it to create complaint from a shipment document.

- de.metas.acct.base/src/main/sql/postgresql/ddl/functions/ProfitAndLossBalanceForAccountInPeriod.sql
- de.metas.acct.base/src/main/sql/postgresql/ddl/functions/ProfitAndLossReport.sql
- de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5554590_sys_gh6148_UpdateProfitAndLossCalculationFormula.sql
https://github.com/metasfresh/metasfresh/issues/6148
> Update Profit & Loss Report Calculation Formula

- de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
https://github.com/metasfresh/metasfresh/issues/6359
> #6359 set the pricing system from the pricelist to the pricing context

- de.metas.acct.base/src/main/java/de/metas/acct/model/validator/GL_Journal.java
https://github.com/metasfresh/metasfresh/issues/6358
> #6358 Enable cloning for GL_Journal documents.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554910_sys_gh6346ShowingMovementDateInShipmentComplaints.sql
https://github.com/metasfresh/metasfresh/issues/6346
> #6346 Showing movement date field for shipment complaints and prefilling it.

- de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schedule_CreateSalesOrder.java
https://github.com/metasfresh/metasfresh/issues/6370
> Provide the payment term from partner to phonecall order 

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/product_specifications_v.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5555030_gh6376_FixEmptyTextInCustomerLabelName.sql
#6376 Avoid empty text for packing material in Product specifications
> #6376 Fix componentName

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_bpblock_deliveryto.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_de_CH.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_de_DE.properties
- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report_details.jrxml
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/docs_generics_org_details.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5555050_gh6378_addFunctoin_docs_generics_org_details.sql
#6378 Improve packing list report
> #6378 Improve packing list report 

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555100_sy_gh6382FixedBPartnerIdentifier.sql
> #6382 Fixed Business Partner table identifier.

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/ad/dao/impl/TypedSqlQuery.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/AdMessageKey.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554730_sys_gh6365_AddUSTrlFOrMaterialentnahme_MaterialWithdrawal.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554830_sys_gh6365_AddLocatorToHUEditorWindow.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5554850_sys_gh6365_SetFilterDefaultValueForHUPackingStatus.sql
- de.metas.banking/de.metas.banking.base/src/main/java-legacy/org/compiere/model/MBankStatement.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankingBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/LUTUCUPair.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/IHUTrxBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/impl/HUTrxBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQueryBuilder.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- de.metas.report/report-service/src/main/java/de/metas/report/rest/ReportRestController.java
- de.metas.util/src/main/java/de/metas/util/Check.java
https://github.com/metasfresh/metasfresh/issues/6365
> Check/ Fix Barcode Filtering and `Materialentnahme`=`Material Withdrawal` refresh

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/BPartner_PriceList_Version.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/Fresh_PriceList_Version_Val_Rule.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5555120_sys_gh6384_Split_PLV_Comparison_Processes.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5555130_sys_gh6384_Introduce_IsSOTrx_In_PLV_View_And_Function.sql
https://github.com/metasfresh/metasfresh/issues/6384
> Gh6384 Split Pricelist Comparison Process in Sales and Purchase

- de.metas.business/src/main/java/de/metas/invoice/impl/InvoiceLineBL.java
https://github.com/metasfresh/metasfresh/issues/6359
> Gh6359 2 Don't try to convert price if uom not set in invoice line

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/process/GenerateDeliveryDays.java
https://github.com/metasfresh/metasfresh/issues/6393
> #6393 only show the Generate Delivery Days action for single selection

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridField.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
https://github.com/metasfresh/metasfresh-webui-api/issues/1394
> GridFieldVO.getFieldLength()

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
https://github.com/metasfresh/metasfresh/issues/6405
> shipment dispo: cache invalidate when mass updating the records

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/sys_gh6364UpdateSQLandOnlyShowSOTRXpricelistversions.sql
> #6364 minor changes to sql and also added validation rule for displayed pricelist versions.

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/impl/ColumnBL.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555560_sys_gh6411_Set_IsCalculated_to_True_ForSomeColumns.sql
https://github.com/metasfresh/metasfresh/issues/6411
> Mark all `ExternalID` columns as `IsCalculated`

- de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5550810_sys_gh6061_AddProcessForImportingBankStatementLinesFromFile.sql
https://github.com/metasfresh/metasfresh/issues/6381
> Rename `todo5550810_sys_gh6061_AddProcessForImportingBankStatementLinesFromFile.sql` migration script name

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555625_sys_gh6302_AD_User_unique_index.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555630_cli_gh6302_C_Order_AD_User_ID_fix_data.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555631_sys_gh6302_C_Order_AD_User_ID_FK.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555640_cli_gh6302_C_Order_Bill_User_ID_fix_data.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555641_sys_gh6302_C_Order_Bill_User_ID_FK.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555650_cli_gh6302_C_Invoice_AD_User_ID_fix_data.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555651_sys_gh6302_C_Invoice_AD_User_ID_FK.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555660_cli_gh6302_M_InOut_AD_User_ID_fix_data.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555661_sys_gh6302_M_InOut_AD_User_ID_FK.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555680_cli_gh6302_C_Order_DropShip_User_ID_fix_data.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555681_sys_gh6302_C_Order_DropShip_User_ID_FK.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555690_cli_gh6302_C_Order_HandOver_User_ID_fix_data.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555691_sys_gh6302_C_Order_HandOver_User_ID_FK.sql
https://github.com/metasfresh/metasfresh/issues/6302
> fix c_bpartner_id/ad_user_id foreign keys

- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5555730_sys_gh6384FixExportPricelistAsExcelFunction.sql
- de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperEngine.java
> #6384 Fixed Reports!

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/service/ISysConfigBL.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/service/impl/SysConfigBL.java
https://github.com/metasfresh/metasfresh/issues/6416
> ISysConfigBL.getValuesForPrefix shall consider System Properties too

- de.metas.elasticsearch/src/main/java/de/metas/elasticsearch/impl/ESSystem.java
https://github.com/metasfresh/metasfresh/issues/6413
> Simplify code

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555860_sys_gh6364FixedExportSql.sql
- de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/fresh_PriceList_Details_Template_Report.sql
> Fixes/ adjustments: Excel Sales Order adjustments

- de.metas.contracts/src/main/java/de/metas/contracts/commission/invoicecandidate/CommissionShareHandler.java
- de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5556000_sys_gh6421_fix_c_flatrate_condition_mandatory_problem.sql
- de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/ordercheckup/impl/OrderCheckupBuilder.java
* CommissionShareHandler: solve metasfresh/metasfresh#6299 for non-item products
* note that by default the commission product is in fact such a non-item (i.e. service) product
*  5556000_sys_gh6421_fix_c_flatrate_condition_mandatory_problem.sql: solve metasfresh/metasfresh#6421 by updating the AD_Column's mandatory logic
* OrderCheckupBuilder: minor unrelated
> solve commission related problems

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5555980_sys_gh6426_FixPaymentWindow_TRL.sql
https://github.com/metasfresh/metasfresh/issues/6426
> Fix `Payment` window trls

- de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_CurrentVsLastPricelistComparison.jrxml
> #6394 Updated report jrxml!

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/BPartnerContactId.java
- de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
- de.metas.business/src/main/java/de/metas/order/impl/OrderLineBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
- de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/agg/key/impl/HUShipmentScheduleKeyValueHandler.java
- de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/spi/impl/DocumentPrintingQueueHandler.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/agg/key/impl/ReceiptScheduleKeyValueHandler.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/agg/key/impl/ShipmentScheduleKeyValueHandler.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleEffectiveBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleEffectiveBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/inoutcandidate/OrderLineShipmentScheduleHandler.java
- de.metas.util/src/main/java/org/adempiere/util/agg/key/IAggregationKeyValueHandler.java
- de.metas.util/src/main/java/org/adempiere/util/agg/key/impl/CompositeAggregationKeyValueHandler.java
https://github.com/metasfresh/metasfresh/issues/6302
> Fix using system user for contact in some places

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556340_sys_gh6426_Fix_Again_IsAllocated_trl.sql
https://github.com/metasfresh/metasfresh/issues/6426
> Fix IsAllocated trl again

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/model/IDocumentLocation.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/agg/key/impl/ReceiptScheduleKeyValueHandler.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/InOutProducer.java
- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBL.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleBLTest.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleTestBase.java
https://github.com/metasfresh/metasfresh/issues/6302
> Fix using system AD_User_ID for contact in some places instead of BPartnerContactId

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556350_sys_gh6449_AddReference_C_BankStatement_to_C_PaySelection.sql
https://github.com/metasfresh/metasfresh/issues/6449
> Add Referenced Documents Link from C_BankStatement to C_PaySelection

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556450_sys_gh6449_C_PaySelectionLine_C_BankStatementLine_Index.sql
https://github.com/metasfresh/metasfresh/issues/6449
> Add index `C_PaySelectionLine_C_BankStatementLine_Index`

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556580_sys_gh6446TranslatedOwnPaletteAndAddedItToSingleView.sql
https://github.com/metasfresh/metasfresh/issues/6446
> #6446 Made Transform action set flag to 'Y' in case of LU rows, translated column & added it to single view.

- de.metas.rfq/src/main/java/de/metas/rfq/RfQModuleInterceptor.java
- de.metas.rfq/src/main/java/de/metas/rfq/model/interceptor/C_RfQ_TabCallout.java
- de.metas.rfq/src/main/java/de/metas/rfq/model/interceptor/RfQModuleActivator.java
https://github.com/metasfresh/metasfresh/issues/6456
> #6456 Calculating document numbers for Request for Proposal window entries.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556660_sys_gh6432_Fact_Acct_Ordering_Index.sql
https://github.com/metasfresh/metasfresh/issues/6432
> #6432 Fact_Acct ordering index

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556570_sys_gh6458_Fix_C_InvoiceLines_With_Invalid_C_Uom_ID_or_Price_Uom_ID.sql
- de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
- de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
- de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
- de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
- de.metas.business/src/main/java/de/metas/product/IProductBL.java
- de.metas.business/src/main/java/org/adempiere/invoice/service/IInvoiceBL.java
- de.metas.business/src/main/java/org/adempiere/invoice/service/IInvoiceDAO.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/AbstractInvoiceBL.java
- de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/service/impl/AbstractInvoiceDAO.java
- de.metas.swat/de.metas.swat.base/src/test/java/org/adempiere/invoice/service/IInvoiceBLTest.java
https://github.com/metasfresh/metasfresh/issues/6458
> Make sure `C_InvoiceLine.Price_UOM_ID` and `C_UOM_ID` are always set

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
- de.metas.business/src/main/java/de/metas/order/OrderFactory.java
- de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schedule_CreateSalesOrder.java
https://github.com/metasfresh/metasfresh/issues/6464
> Wrong BillTo location and contact when Sales Order created from PhonecallSchedule

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556860_sys_gh375AddedWarehouseEffectiveFilterInMaterialReceiptCandidatesWindow.sql
https://github.com/metasfresh/metasfresh/issues/6466
> #6386 Added warehouse effective filter mechanism in material receipt candidates window.

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5556950_sys_gh749AddTourFilterToTourVersionWindow.sql
https://github.com/metasfresh/metasfresh/issues/6473
> #6473 Add Tour filter to tourversion window.

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/ColumnDisplayTypeProvider.java
- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfo.java
- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/apps/search/IUserQueryField.java
- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/apps/search/UserQueryFieldHelper.java
- de.metas.adempiere.adempiere/base/src/main/java/org/compiere/apps/search/UserQueryRepository.java
- de.metas.adempiere.adempiere/base/src/test/java/org/compiere/apps/search/UserQueryRepositoryTest.java
- de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/search/FindPanel.java
- de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/search/FindPanelSearchField.java
https://github.com/metasfresh/metasfresh/issues/6476
> User Query filters errors

- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/CopyRecordSupport.java
- de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/GeneralCopyRecordSupport.java
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5557210_sys_gh6482_Add_Error_Trl.sql
https://github.com/metasfresh/metasfresh/issues/6482
> Cloning with keyboard shortcut works even if action is hidden from menu

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5557420_sys_gh6466UpdatedWarehouseEffectiveFilterInMaterialReceiptCandidates.sql
> #6466 Updated Warehouse Effective Filter

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5557200_sys_gh6480_AddSysConfigFor_ViewExpirationTimeout.sql
- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5557220_sys_gh6480_ChangeSysconfigTimeoutToMinutesFromHour.sql
https://github.com/metasfresh/metasfresh/issues/6480
> webui views: sysconfig to configure how much time we keep the views before we expire them

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
- de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/I_S_ExternalReference.java
- de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/I_S_Issue.java
- de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_ExternalReference.java
- de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_Issue.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/external/issuedetails/ExternalIssueDetailsRepository.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/external/reference/S_ExternalReference.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueEffortService.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueEntity.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueRepository.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/S_Issue.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/hierarchy/IssueHierarchy.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/IssueImporterService.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/Effort.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/S_TimeBooking.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/importer/TimeBookingsImporterService.java
- de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5557370_sys_gh5816-app_milestone_dueDate_latestActivity.sql
- de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5557470_sys_gh5816-app_issue_window_adjustments.sql
- de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5557560_sys_gh5816-app_issue_window_adjustments_1.sql
- de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5557570_sys_gh5816-app_issue_window_adjustments_2.sql
- de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/TestConstants.java
- de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/issue/IssueEffortServiceTest.java
- de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/issue/IssueRepositoryTest.java
- de.metas.util/src/main/java/de/metas/util/Node.java
- de.metas.util/src/main/java/de/metas/util/time/HmmUtils.java
- de.metas.util/src/test/java/de/metas/util/NodeTests.java
> issue window adjustments

- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/BankStatementLineMultiPaymentLinkCommand.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/BankStatementLineRefCreateRequest.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankStatementDAO.java
- de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/service/impl/BankStatementPaymentBLTest.java
https://github.com/metasfresh/metasfresh/issues/6511
> Bank statement line reference not marked as processed

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/555782_sys_gh6302_Update_User_In_Shipment_And_Invoice_Candidates.sql
https://github.com/metasfresh/metasfresh/issues/6302
> #6302 update user in candidates and recompute

- de.metas.dlm/base/src/main/sql/postgresql/system/5557880_sys_switch_off_dlm.sql
- de.metas.issue.tracking.github/src/main/java/de/metas/issue/tracking/github/api/v3/GitHubApiConstants.java
- de.metas.issue.tracking.github/src/main/java/de/metas/issue/tracking/github/api/v3/model/RetrieveIssuesRequest.java
- de.metas.issue.tracking.github/src/main/java/de/metas/issue/tracking/github/api/v3/service/GithubClient.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/everhour/EverhourImportProcess.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/everhour/ScheduledEverhourImport.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/external/reference/ExternalReferenceRepository.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImportProcess.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImporterService.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/ScheduledGithubImport.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/IssueImporterService.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/info/ImportIssuesRequest.java
- de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/importer/TimeBookingsImporterService.java
- de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5557770_sys_gh5816-app_sub_issues_references.sql
- de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5557840_sys_gh5816-app_add_scheduler_for_Github_and_Everhour_imports.sql
- de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/everhour/EverhourImporterServiceTest.java
- de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/external/reference/ExternalReferenceRepositoryTest.java
> run GitHub & Everhour imports by a schedule

- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/PaymentAllocationRepository.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/PaymentToAllocate.java
- de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentDocument.java
- de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
- de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/model/AbstractAllocableDocRow.java
- de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/model/PaymentRow.java
- de.metas.business/src/main/java/de/metas/money/MoneyService.java
- de.metas.business/src/main/java/de/metas/payment/PaymentDirection.java
https://github.com/metasfresh/metasfresh/issues/6529
> Allow Invoice with Credit memo allocation

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558060_sys_gh6532_AddRefereceFromProductToBomLine.sql
https://github.com/metasfresh/metasfresh/issues/6532
> Add reference from Product to BomLine/Component

- de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558080_sys_gh6534_AddFiltersTo_StorageConferenceVersion_Lagerkonferenz.sql
https://github.com/metasfresh/metasfresh/issues/6534
> Add filters to Storage Conference Version (Lagerkonferenz)

- de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLHandlCompleteAndReversalTest.java
https://github.com/metasfresh/metasfresh/issues/6540
> #6540 reverse credit memos that are not based on an invoice

- de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLHandlCompleteAndReversalTest.java
https://github.com/metasfresh/metasfresh/issues/6540
> #6540 java doc for unit test

- de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/SpringContextHolder.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CCache.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheIndex.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheInvalidationRemoteHandler.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheMDC.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheMgt.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/CacheInvalidateMultiRequest.java
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/impl/EventBus.java
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/cache/CacheInvalidationRemoteHandlerTest.java
- de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/dao/cache/CacheInvalidateMultiRequestSerializerTest.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/adapter/NoopPerformanceMonitoringService.java
- de.metas.monitoring/src/main/java/de/metas/monitoring/adapter/PerformanceMonitoringService.java
...latest caching-observability improvements
https://github.com/metasfresh/metasfresh/issues/6245
> attempt to solve problem on yeast_overgrowth by synching..

- frontend/src/components/app/Prompt.js
- frontend/src/components/table/Table.js
Remove things that can cause unnecessary re-renders.
> Small frontend performance fixes

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558650_sys_gh6573SortingIngredientsInTab.sql
> #6573 Fixed wrong seqno generation in product ingredients sub-tab. Also ordering ingredients desc by seqno.

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558690_sys_gh6579_NoContactErrorMessage.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
- backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
- backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
https://github.com/metasfresh/metasfresh/issues/6579
> Sales order with Payment Rule PayPal and no contact: NPE

- Jenkinsfile
- backend/buildfile.groovy
- e2e/buildfile.groovy
- frontend/buildfile.groovy
- misc/services/admin/buildfile.groovy
- misc/services/edi/buildfile.groovy
- misc/services/procurement-webui/buildfile.groovy
https://github.com/metasfresh/metasfresh/issues/6588
> Update all jenkins files' diff

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/sql/SqlDefaultDocumentFilterConverter.java
> #6594 Trimming beggining and end white spaces from filter search queries.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558680_sys_gh6575AddedMissingFiltersAndColumnsToTranslationTabs.sql
> #6575 Added Missing Filters and columns.

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPLocationBuilder.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPartnerDAO_retrieveBPartnerLocationTests.java
- backend/de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/editor/model/impl/HUPropertiesModel.java
#6596 Do not fail on inactive partner locations on invoicing
> #6596 Do not fail on inactive partner locations on invoicing 

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558810_sys_gh6575ChangedFiltersFromTableDirectToSearch.sql
> #6575 Changed 2 filters from table direct to search.

- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/CustomerRetentionRepository.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/invoice/ContractInvoiceService.java
https://github.com/metasfresh/metasfresh/issues/6566
> #6566 improve comparator, formatting

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/RecordChangeLogEntryLoader.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/RecordRefWithLogEntryProcessor.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/table/RecordRefWithLogEntryProcessorTest.java
fix the problem and add a unit test
https://github.com/metasfresh/metasfresh/issues/6619
> Handle C_Location-AD_ChangeLog with ValueNew=NULL gracefully

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/IHUTrxBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/impl/HUTrxBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/api/IHUMovementBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/api/impl/HUMovementBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/api/impl/HUMovementBuilder.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/impl/LUTUConfigurationFactory_createLUTUProducerAllocationDestination_Test.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/movement/api/HUMovementBuilderTests.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/HUMoveToDirectWarehouseService.java
https://github.com/metasfresh/metasfresh/issues/6610
> Material Withdrawal cannot run because wrong locator is detected

- backend/buildfile.groovy
- e2e/buildfile.groovy
- frontend/buildfile.groovy
- misc/services/admin/buildfile.groovy
- misc/services/edi/buildfile.groovy
- misc/services/procurement-webui/buildfile.groovy
https://github.com/metasfresh/metasfresh/issues/6588
> Jenkins: Try catch for git diff

- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractsDAO.java
https://github.com/metasfresh/metasfresh/issues/6566
> Gh6566 3 repair sorting when retrieving contracts

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Table.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Table.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupFactory.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MLookupInfo.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/impl/ReferenceTooltipType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/impl/TooltipType.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/ConstantTranslatableString.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/TranslatableStrings.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/ILookupDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/IADTableDAO.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/ADTableDAO.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/document/references/RelationTypeZoomProviderFactoryTest.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558930_sys_gh6603_Add_RefList_TooltipType_to_AD_Table.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5558980_sys_gh6603_Set_M_PriceListVersion.Description_IsCalculated.sql
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributes.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributesHelper.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pattribute/ASILookupDescriptor.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/datatypes/LookupValue.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/datatypes/LookupValuesList.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/LookupDescriptor.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/lookup/GenericSqlLookupDataSourceFetcher.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceFetcher.java
https://github.com/metasfresh/metasfresh/issues/6603
> PriceList Version Description wrong

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5559060_sys_gh6634_C_BankStatementLine_HidePaidInvoicesFromUI.sql
https://github.com/metasfresh/metasfresh/issues/6634
> Don't suggest Paid Invoices in C_BankStatementLine

- frontend/package.json
- frontend/src/index.jsx
Replace why-did-you-update with why-did-you-render
> Replace with the latest lib

- backend/buildfile.groovy
https://github.com/metasfresh/metasfresh/issues/6588
> Jenkins stage `Test SQL-Migrationscripts` can be force-Built

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRow.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsLoader.java
https://github.com/metasfresh/metasfresh/issues/6648
> HOTFIX ShipmentCandidateRow shall display qtyOrdered_TU

- frontend/src/components/widget/Labels/Labels.js
- frontend/src/components/widget/RawWidget.js
https://github.com/metasfresh/metasfresh/issues/6647
> Send tabId and rowId to Labels component

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankStatementBL.java
- backend/de.metas.banking/de.metas.banking.swingui/src/main/java/de/metas/banking/payment/paymentallocation/service/impl/PaymentAllocationFormDAO.java
https://github.com/metasfresh/metasfresh/issues/6634
> Use Invoice OpenAmount instead of GrandTotal when filling BankStatementLine info

- frontend/src/reducers/tables.js
> Fix for initial tables state

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/I_M_ShipmentSchedule.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRow.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsLoader.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/shipment_candidates_editor/MockedLookupDataSource.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsLoaderTest.java
https://github.com/metasfresh/metasfresh/issues/6648
> ShipmentCandidateRow.qtyOrdered_CU_or_TU based on qtyOrdered

- backend/de.metas.business/src/main/java/de/metas/order/OrderLinePriceUpdateRequest.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderLineBL.java
- backend/de.metas.business/src/main/java/de/metas/order/impl/OrderLinePriceCalculator.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLinesFromProductProposalsProducer.java
https://github.com/metasfresh/metasfresh/issues/6662
> #6662 update prices on product proposal update

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5559400_sys_gh6667TranslatedForgottenPasswordMessages.sql
> #6667 Translated forgotten password messages.

- backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/I_S_Issue.java
- backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_Issue.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/external/project/ExternalProjectReference.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/external/project/ExternalProjectRepository.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImportProcess.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImportSingleSelection.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImporterService.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueEntity.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueRepository.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/IssueImporterService.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/info/ImportIssueInfo.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/info/ImportIssuesRequest.java
- backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5559350_sys_gh5816-app_add_sync_with_github_process.sql
- backend/de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/github/GithubImporterServiceTest.java
- backend/de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/issue/IssueRepositoryTest.java
> Effort issue/ Budget issue action "Import from GitHub"

- frontend/src/components/widget/Labels/Labels.js
https://github.com/metasfresh/metasfresh/issues/6647
> hotfix labels typeahead

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/service/impl/ColumnBL.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5559310_sys_gh6654_Mark_column_IsReconciled_as_IsCalculated.sql
https://github.com/metasfresh/metasfresh/issues/6654
> Mark column `IsReconciled` as `IsCalculated`

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_CurrentVsLastPricelistComparison.jrxml
> #6656 Small changes to margins.

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5559510_sys_gh5853_MakeMandatoryTabLabelAndFixValidationRule.sql
#5853 window copy process creates corrupt window when copying labels tabs
> #5853 window copy process creates corrupt window when copying labels tabs 

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_M_Picking_Candidate_Process.java
https://github.com/metasfresh/metasfresh/issues/6674
> Picking Window (v1) allow action Process Picks on Picking Slot selection

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/BankStatementDocumentHandler.java
https://github.com/metasfresh/metasfresh/issues/6511
> Gh6511 set bank statement lines and references processed on completion

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5559620_sys_gh6683RenameHandlingUnitTyp.sql
> 6683 Renamed Handling Unit Type Ad_Element.

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_orgblock_ic_text_color.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_CurrentVsLastPricelistComparison.jrxml
> #6656 Using intercheese text color + new page margin adjustments.

- backend/de.metas.issue.tracking.github/src/main/java/de/metas/issue/tracking/github/api/v3/GitHubApiConstants.java
- backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/I_S_Issue.java
- backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_Issue.java
- backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_IssueLabel.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImporterConstants.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImporterService.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueEntity.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueRepository.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueService.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/Status.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/IssueImporterService.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/info/ImportIssueInfo.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/interceptor/AddIssueProgressRequest.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/Effort.java
- backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/S_TimeBooking.java
- backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5559470_sys_gh5816-app_budget_window_adjustments.sql
- backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5559570_sys_gh5816-app_budget_window_grid_seq.sql
- backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5559600_sys_gh5816-app_S_issue_defaultFilters.sql
- backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5559630_sys_gh5816-app_enable_changeLog.sql
- backend/de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/issue/IssueRepositoryTest.java
- backend/de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/issue/IssueServiceTest.java
> Budget issue window adjustments

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/order/products_proposal/service/Order.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLine.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
https://github.com/metasfresh/metasfresh/issues/6662
> #6662 don't change the manually inserted price in productProposal

- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5559710_sys_gh6694_add_Picked_ad_element.sql
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/packageable/PackageableRow.java
https://github.com/metasfresh/metasfresh/issues/6694
> Add `Picked` flag on Picking Terminal window

- backend/de.metas.business/src/main/java/de/metas/project/interceptor/C_Project.java
> #6691 Enabled cloning of C_Project documents (Used in seminar window).

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5559770_sys_gh6701AddedMessageForInactiveAddress.sql
> #6701 Added error message when sales order cloning fails.

- frontend/src/containers/DocList.js
It should be less aggressive as it breaks modals. 
Related to #6666
> Disable `shouldComponentUpdate` optimization

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/sql/SqlDefaultDocumentFilterConverter.java
https://github.com/metasfresh/metasfresh/issues/6692
> SqlDefaultDocumentFilterConverter.buildSqlWhereClause_InArray

- e2e/cypress/integration/picking/pick_HUs_and_create_shipment.js
- e2e/cypress/support/commands/general.js
- e2e/cypress/support/commands/navigation.js
- e2e/cypress/support/index.d.ts
- e2e/cypress/support/utils/constants.js
- e2e/package.json
- frontend/src/components/documentReferences/DocumentReferenceGroup.js
- frontend/src/components/documentReferences/DocumentReferenceItem.js
- Fix the tests from the picking spec that were failing as a result of changes in the references area
- Ditched the endpoint check as it seems is not supported properly by Cypress (sse)
- Check the loading of references based by `reference-Field`
- upgraded Cypress to latest version
> E2e 6703 references

- frontend/src/components/filters/Filters.js
- frontend/src/components/table/Table.js
- frontend/src/components/table/TableCell.js
- frontend/src/components/table/TableItem.js
Moment should use the locale set
> Frontend 6712 fix dates

- e2e/cypress/integration/inventory/create_disposal_from_handling_unit_editor.js
- e2e/cypress/integration_defunct/picking/pick_HUs_and_create_shipment.js
https://github.com/metasfresh/metasfresh/issues/6725
> Reset filters after entering HU Editor

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
Other small fixes
https://github.com/metasfresh/metasfresh/issues/6722
> Skip LU creation when there is no LU Packing Instruction Version for this TU

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5559970_sys_gh6701UpdateMessageForInactiveAddress.sql
> #6701 Updated Message for inactive address translation.

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/print/ReportEngine.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5560130_sys_gh6713SetDistribOrderPrintFormatInPrintForm.sql
> #6713 Fixed Report Engine hardcoded tables & Added printFormatId to printform for distribution orders.

- backend/de.metas.business/src/main/java/de/metas/uom/IUOMConversionBL.java
- backend/de.metas.business/src/main/java/de/metas/uom/UOMPrecision.java
- backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMConversionBL.java
- backend/de.metas.business/src/test/java/de/metas/uom/impl/UOMConversionBLTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/pporder/api/HUPPOrderIssueProducerTest.java
https://github.com/metasfresh/metasfresh/issues/6743
> Gh6743 uom conversion with round UP

- frontend/src/components/filters/Filters.js
- frontend/src/components/table/Table.js
- frontend/src/components/table/TableCell.js
- frontend/src/components/table/TableItem.js
cherry-picked commit https://github.com/metasfresh/metasfresh/commit/c388007feb18de1c5084058a99a544b7c8d8ccf1
from PR https://github.com/metasfresh/metasfresh/pull/6715
..with conflixts that i *tried* to resolve
> Add fixes for dates depending on the locale #6712 (#6715)

- backend/de.metas.business/src/main/java/de/metas/request/api/IRequestDAO.java
- backend/de.metas.business/src/main/java/de/metas/request/api/impl/RequestDAO.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java
> #6738 Refactored CreateRequest process and added case for kontakt mobil.

- de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/AttachmentEntryService.java
- de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
- de.metas.business/src/main/java/de/metas/invoice/impl/InvoiceLineBL.java
- de.metas.business/src/main/java/de/metas/pricing/service/IPricingBL.java
* InvoiceLineBL: improve logging; fix the issue by telling the pricing engine to throw an exception on missing price
* before this, there was some secondary error which did not guide anyone to the real problem
* IPricingBL: minor javadoc fix
* AttachmentEntryService: only minor javadoc-addition
> show helpful error message on missing price

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_details.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_details_footer.jrxml
> #6713 Increased date field width, for text to fit.

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_description.jrxml
> #6713 Enlargen date field width

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java
#6777 Shall refresh even if is single document
> #6777 Shall refresh even if is single document

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
#6777 Repair process refresh - invalidate documents
> #6777 Repair process refresh - invalidate documents

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/InventoryLineRecordService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/InventoryRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/interceptor/M_InventoryLine.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/storage/impl/DefaultHUStorageFactory.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/InventoryRepositoryTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/InventoryTestHelper.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.java
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/InventoryRepositoryTest.snap
- backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.snap
https://github.com/metasfresh/metasfresh/issues/6745
> moved to callout

- frontend/src/components/table/TableContextMenu.js
> Fix zoom into

- frontend/src/api/view.js
Found out when checking tests for #6785 but not really related.
> Fix error when fetching tabs

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_de_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_de_DE.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_description.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_en_GB.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_en_US.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_fr_CH.properties
- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/distributionorder/report_it_CH.properties
> #6713 Fixed minor details.

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_bpblock_shorter_left_margin.jrxml
> #6794 Changed font size and unbolded it.

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationAmounts.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommand.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java
https://github.com/metasfresh/metasfresh/issues/6784
> gh6784_3_ic

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
- frontend/src/components/widget/MasterWidget.js
> #6779 Now sending 0 instead of null to frontend in the case we receive 0 for the qty to invoice override field.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5560500_sys_gh6782_PhysicalInventoryLine_SearchProductByValue.sql
- backend/de.metas.edi/src/test/java/de/metas/edi/api/impl/DesadvBLTest_addInOutLine.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/picking/form/AbstractHUTableRowSearchSelectionMatcher.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUContextFactory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUIterator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/HUSplitBuilder.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/UpdateMonthsUntilExpiryCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/AbstractHUIterator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUContextFactory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/MutableHUContext.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/CustomerReturnsInOutProducer.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/InventoryLineRecordService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/interceptor/M_Inventory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/materialtracking/spi/impl/HUDocumentLineLineMaterialTrackingListener.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_Generate_M_InOuts.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/generichumodel/HURepositoryTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HandlingUnitsBL_MoveHU_Test.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/AbstractAggregateShipmentHUShipmentProcessIntegrationTest.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/shipmentschedule/integrationtest/HUShipmentProcess_1TUwith2VHU_splitTo_1LUwith1TU_IntegrationTest.java
- backend/de.metas.handlingunits.client/src/main/java/de/metas/handlingunits/client/terminal/receipt/model/ReceiptScheduleCUKey.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveCUs.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveHUs_Base.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueCUQty.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/Document.java
https://github.com/metasfresh/metasfresh/issues/6782
> Wrong Organisation set to HUs when doing Inventory or Material Receipt

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561100_sys_gh6817TranslatedSystemElementAndRearrangedProductTrlGridView.sql
> #6817 Translated Additional Information column and moved organisation last in grid view.

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/ITaxBL.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceTax.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandidateHandlerBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tax/api/impl/TaxBL.java
also minor improvements in ITaxBL, MInvoiceTax and IInvoiceCandidateHandlerBL
> Allow wholeTax-taxes also if the document has IsTaxIncluded=N

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pattribute/ASIDescriptorFactory.java
https://github.com/metasfresh/me03/issues/4935
> use LocalDate instead of java.util.Date

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561070_sys_gh6822_FixTrlInTransportationOrderWindow.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561080__sys_gh6822_FixTrlInTransportationOrderWindow_2.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561130_sys_gh6822_FixTrlInTransportationOrderWindow_3.sql
https://github.com/metasfresh/metasfresh/issues/6822
> Translation: `Transportation Order` / `Bill of Lading`

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5560630_sys_gh6803AddedGenerateDeliveryDaysToTourVersion.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/IDeliveryDayGenerator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/ITourDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/impl/DeliveryDayGenerator.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/impl/TourDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/process/GenerateDeliveryDays.java
- backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/tourplanning/api/impl/TourDAOTest.java
- misc/services/edi/pom.xml
> #6803 Can now generate delivery days for a specific tour version.

- frontend/src/components/widget/DatePicker.js
Set the date string correctly once this is updated as a result of a patch (ex. when Enter is pressed).
> Set correctly the date according to locale 

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/InvoiceService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/CreateInvoiceCandidatesService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/InvoicesRestControllerImpl.java
- backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/response/JsonInvoiceCandidatesResponseItem.java
- backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/response/JsonReverseInvoiceResponse.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
https://github.com/metasfresh/metasfresh/issues/6827
> Extend Invoice reversal API to return affected ICs

- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsService.java
Goal: have the guarantor on the printed invoice if guarantor != patient
> set guarantor-name as company name to the guarantor-address

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/BankStatementPaymentBL.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/service/impl/BankStatementPaymentBLTest.java
https://github.com/metasfresh/metasfresh/issues/6769
> fix BankStatementPaymentBL.linkSinglePayment

- frontend/src/actions/AppActions.js
- frontend/src/components/table/Table.js
- frontend/src/components/widget/DatePicker.js
- frontend/src/constants/Constants.js
- frontend/src/containers/App.js
- frontend/src/utils/documentListHelper.js
- frontend/src/utils/locale.js
https://github.com/metasfresh/metasfresh/issues/6807
> refactor and introduced utils/locale.js to get/set current locale

- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5559900_sys_gh6713_add_warehouse_from_and_to_on_DD_Order.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5559905_sys_gh6713_fix_DD_Order.M_Warehouse_From_ID_values.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5559907_sys_gh6713_fix_DD_Order.M_Warehouse_From_ID_MakeNotNull_DropDefaultValue.sql
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5561310_sys_gh6713_Warehouse_From_Warehouse_To_moved_to_main.sql
Part 2 should be creating a Validation Rule in which the warehouse is set by taking into account AD_Org and other things
https://github.com/metasfresh/metasfresh/issues/6713
> Fix the case where warehouse `Std Warehouse` (`M_Warehouse_ID = 540008`) does not exist. Part 1

- backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5561340_sys_gh5816_disable_Github_Everhour_import_schedulers.sql
> disable schedulers

- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/IBankStatementPaymentBL.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/BankStatementPaymentBL.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/BankStatementDocumentHandler.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/BankStatementDocumentHandlerRequiredServicesFacade.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/BankStatementLineCreateRequest.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/service/impl/BankStatementDAO.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/service/BankStatementDocumentHandlerTest.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/service/impl/BankStatementPaymentBLTest.java
- backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/service/impl/C_BankStatementLine_MockedInterceptor.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/PaymentQuery.java
- backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
- backend/metasfresh-webui-api/src/main/java/de/metas/banking/process/C_BankStatement_ReconcileWithSinglePayment.java
https://github.com/metasfresh/metasfresh/issues/6769
> gh6769_4_uat

- backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/M_Element.java
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561270_sys_testWindowSandbox.sql
https://github.com/metasfresh/metasfresh/issues/6845
> test window sandbox

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561390_sys_gh6846AddedFiltersToProductPlanningWindow.sql
> #6846 Added Filters to the 'Product Planning' window.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561410_gh6848_RemoveAll_ASI.Description_WhichAreAn_ASI_ID.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/MAttributeSetInstance.java
https://github.com/metasfresh/metasfresh/issues/6848
> Attribute ID shall not be shown in Attribute Editor/ Attribute Button

- frontend/src/reducers/tables.js
> Fix showing 404 page when there is no data in the grid

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561480_gh6860_rearranging_marketing_platform_view.sql
> #6860 rearranging_marketing_platform_view

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java
> #6862 Now presetting request type when running 'Create Request' action.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561500_sys_gh6856NewBoilerplateTrlWindow.sql
> #6856 Created Boilerplate Translation Window.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5561450_sys_gh6850_One_Window_For_Resource.sql
https://github.com/metasfresh/metasfresh/issues/6850
> #6850 Keep only one window for Resource

- frontend/src/__tests__/components/table/Table.test.js
- frontend/src/__tests__/reducers/Tables.test.js
Test empty rows rendering/creating store entry.
Related to #6706
> Unit tests for Table component

- frontend/src/actions/WindowActions.js
- frontend/src/components/DataLayoutWrapper.js
- frontend/src/components/app/DocumentList.js
- frontend/src/components/app/SelectionAttributes.js
- frontend/src/components/app/SpinnerOverlay.js
- frontend/src/constants/ActionTypes.js
- frontend/src/containers/DocumentList.js
- frontend/src/reducers/tables.js
- frontend/src/reducers/windowHandler.js
Moved setting the attribute flag to redux too.
Related to #6873 & #6706
> Handle attributes in modal properly

- frontend/src/containers/DocumentList.js
The Pagination fix we discussed on Skype
> Get size of the table from table prosp

- frontend/src/__tests__/utils/widgetHelper.test.js
- frontend/src/components/widget/MasterWidget.js
- frontend/src/utils/widgetHelper.js
This is a PR that contains previously reverted code with the BUG fix in the widgetHelper function formatValueByWidget type (returning value)
> Fix bug in the MasterWidget helper fnct

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/bpartner_changes/report.jrxml
> #6883 tablename field stretching now on multiple lines to display full table name if needed.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562050_sys_gh6888ProductTableAndWindowAdjustments.sql
> #6888 Marked isBOM and isVerified columns of the m_product table as iscalculated.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562020_sys_gh6887_AddParam_IsComplete_toFlatrateTermProcess_1.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562040_sys_gh6887_AddParam_IsComplete_toFlatrateTermProcess_2.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562080_sys_gh6887_Fix_Message_trl.sql
- backend/de.metas.contracts/src/main/java/de/metas/contracts/CreateFlatrateTermRequest.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/process/C_Flatrate_Term_Create.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/process/C_Flatrate_Term_Create_For_BPartners.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/process/FlatrateTermCreator.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/process/C_Flatrate_Term_Create_For_MaterialTracking.java
https://github.com/metasfresh/metasfresh/issues/6887
> Allow create Contracts in draft (not completed)

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/procurement_conditions/report.jrxml
> #6892 made bpblock subreport work.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562180_sys_gh6894_PP_ProductPlanning_SeqNo_Default.sql
https://github.com/metasfresh/metasfresh/issues/6894
> #6894 PP_ProductPlanning seqNo default value

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/AddQtyToHUCommand.java
https://github.com/metasfresh/metasfresh/issues/6900
> fixed computation of pickingCandidate.qtyPicked

- frontend/src/actions/WindowActions.js
- frontend/src/components/Window.js
- frontend/src/components/app/MasterWindow.js
- frontend/src/containers/MasterWindow.js
- frontend/src/containers/Table.js
- frontend/src/reducers/windowHandler.js
Fixes updating fields in modals and removing unsaved rows. Related to #6873 & https://github.com/metasfresh/me03/issues/4362
> Improve updating/deleting data

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5562600_sys_gh6923_Add_SysconfigFor_PickingTerminalV2.RepackNumber.IsDisplayed.sql
- backend/de.metas.business/src/main/java/de/metas/uom/IUOMDAO.java
- backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMDAO.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickViewFactory.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/ProductInfo.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/ProductsToPickRow.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/factory/ProductInfoSupplier.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsDataFactoryTest.java
https://github.com/metasfresh/metasfresh/issues/6923
> Picking Terminal (V2) Changes

- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/ITrxListenerManager.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/ITrxManager.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/IPaySelectionDAO.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionDAO.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/modelvalidator/C_PaySelectionLine.java
> #6342 Invalidating cache after deleting a pay selection line.

- frontend/src/components/app/QuickActions.js
- frontend/src/components/app/RawModal.js
Fix for the actions dropdown that remain open. Plus some cleanup of the code to shrink the size.
> Fix for actions dropdown remaining opened

- frontend/src/actions/WindowActions.js
- frontend/src/containers/DocumentList.js
> Fix refreshing table with attributes

- frontend/src/actions/TableActions.js
- frontend/src/actions/ViewActions.js
- frontend/src/constants/actions/TableTypes.js
- frontend/src/containers/DocumentList.js
- frontend/src/containers/Table.js
- frontend/src/reducers/tables.js
Filtering in modals was borked and instead of deleting table when filtering, it's easier to just clear it.
Related to #6706
> Fix filtering data in tables

- backend/de.metas.business/src/main/java/de/metas/phonecall/PhonecallSchedule.java
- backend/de.metas.business/src/main/java/de/metas/phonecall/PhonecallSchemaVersionLine.java
- backend/de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schedule_CreateSalesOrder.java
- backend/de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallScheduleRepository.java
- backend/de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallScheduleService.java
- backend/de.metas.business/src/main/java/de/metas/phonecall/service/PhonecallSchemaRepository.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/impl/OrderDeliveryDayBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/model/validator/C_Order.java
- backend/de.metas.util/src/test/java/de/metas/util/time/SystemTimeTest.java
https://github.com/metasfresh/metasfresh/issues/6945
> #6945 Tour in Order:  improvements

- frontend/src/actions/WindowActions.js
> [Frontend] Fix advanced edit

- frontend/src/components/widget/MasterWidget.js
https://github.com/metasfresh/metasfresh-webui-frontend-legacy/issues/2649
> Fix date picker

- e2e/cypress/fixtures/picking/pick_HUs_and_create_shipment.json
- e2e/cypress/integration/serialletter/serialletter_spec.js
Looks like there were some changes in the API.
> Try to fix the remaining failing e2e tests

- frontend/src/components/table/Table.js
https://www.loom.com/share/92df6eb2b05a4f7fa085d3febf58c3b1
> Fix multiselect with ctrl/command key

- frontend/src/components/header/MenuOverlay.js
https://www.loom.com/share/02cee76e72d84d03bc9e7b49f1052599
> Fix breadcrumbs on accessing dashboard

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToNewHU.java
https://github.com/metasfresh/metasfresh/issues/6900
> disable `Pick to new HU` for multiple packageable rows selected

- backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report.jrxml
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/isShowQRBill.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5562680_sys_gh6956_AddSHowQRBIllSysCOnfig.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5562840_sys_gh6956_isShowQRBill.sql
> #6956 Implement possibility to easy switch from QR Bill to ESR 

- e2e/package.json
We have similar issue as in here https://github.com/meinaart/cypress-plugin-snapshots/issues/126 and we need to downgrade
> Downgrade js-base64

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickViewFactory.java
https://github.com/metasfresh/metasfresh/issues/6949
> ProductsToPickViewFactory: Inject the constructor via Spring instead of SpringContextHolder

- frontend/src/actions/TableActions.js
https://www.loom.com/share/c85b3c8781e34968bf6893c0499a925a
> Fix HU editor table after hitting browser Back btn

- frontend/src/components/widget/DatePicker.js
- frontend/src/components/widget/RawWidget.js
- removes a currently un-necessary patch
- preformats the time value passed for the Time type widget 
- time widget doesn't remain open
https://www.loom.com/share/a84554d5f3bf49598b0c7544e1d0ae41
> Preformat on passing value and remove patch

- frontend/src/assets/css/table.css
- frontend/src/assets/css/tabs.css
- frontend/src/components/table/TableWrapper.js
https://www.loom.com/share/134a21663af3492e9a09217c51ee2b1d
Fix for https://github.com/metasfresh/me03/issues/4362#issuecomment-655330236
> Fix fullscreen button positioning

- frontend/src/__tests__/components/table/TableHeader.test.js
- frontend/src/components/Window.js
- frontend/src/components/app/DocumentList.js
- frontend/src/components/app/MasterWindow.js
- frontend/src/components/table/Table.js
- frontend/src/components/table/TableHeader.js
- frontend/src/containers/MasterWindow.js
- frontend/src/utils/tableHelpers.js
> [Frontend] fix sorting in details view

- frontend/src/actions/TableActions.js
There is a function where we omitted to replace the logic with indentSupported.
https://www.loom.com/share/ec047bc109624f12bb34ba51cbd9e84f
> Fix picking shifting edge cases

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/tourplanning/api/impl/DeliveryDayDAO.java
https://github.com/metasfresh/metasfresh/issues/6945
> #6945 Always prefer delivery days that are for the partner and location

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563100_sys_gh6983_R_Request_SalesRep_ID_DefaultValue.sql
https://github.com/metasfresh/metasfresh/issues/6983
> #6983 R_Request.SalesRep_ID repair defaultValue

- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Warehouse.java
- backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Warehouse.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/ReceiptInOutLineHUAssignmentListener.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/InventoryService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/SyncInventoryQtyToHUsCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/sourcehu/SourceHUsService.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5563110_sys_gh6987_add_isReceiveAsSourceHU_on_M_Warehouse.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/impl/HUInternalUseInventoryProducerTests.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/materialtracking/spi/impl/PPOrderMInOutLineRetrievalServiceTest.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/picking/husToPick/process/WeightHUCommandTest.java
https://github.com/metasfresh/metasfresh/issues/6987
> Automatically mark received HUs carrying BOM components as source HUs.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563160_sys_gh6983_R_Request_SalesRep_ID_DefaultValue.sql
https://github.com/metasfresh/metasfresh/issues/6983
> #6983 migration is not needed

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563070_sys_gh6975_Update_TRLs.sql
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/impl/LUTUConfigurationFactory.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderDocumentLUTUConfigurationHandler.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/pporder/api/impl/PPOrderDocumentLUTUConfigurationHandlerTest.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pporder/process/PackingInfoProcessParams.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Receipt.java
https://github.com/metasfresh/metasfresh/issues/6975
> Default LU and Qty not proposed

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563220_sys_gh6997_AddSysconfig_ProductsToPick_4EyesReview_ProcessAll.AllowPartialDelivery.sql
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java
https://github.com/metasfresh/metasfresh/issues/6997
> Allow partial delivery from `Process` action in Picking Terminal V2

- frontend/src/containers/DocumentList.js
This is a contained change, so feel free to merge. I've checked all the filtering cases I could think of and everything seems to be running just fine.
https://recordit.co/QOEKJKT9mo
> [Frontend] Fix filtering with pagination

- frontend/src/components/widget/List/RawList.js
- frontend/src/components/widget/RawWidget.js
- frontend/src/reducers/tables.js
Fixes resetting selection when table data is reloaded and an annoying bug when setting/resetting widget value wouldn't sometimes work.
> [Frontend] Fix selections when whole table is updated

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563310_sys_gh7003_Only_Default_BillToContact_Valrule.sql
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
- backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoiceBatch.java
https://github.com/metasfresh/metasfresh/issues/7003
> #7003 support for DefaultBillTo_Contact only on Sales invoice

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/quickinput/QuickInput.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentList.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/Document.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/HighVolumeReadWriteIncludedDocumentsCollection.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/HighVolumeReadonlyIncludedDocumentsCollection.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/IIncludedDocumentsCollection.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/SingleRowDetailIncludedDocumentsCollection.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/window/datatypes/json/JSONDocumentListTest.java
- e2e/cypress/support/utils/sales_order_api.js
- e2e/cypress/support/utils/utils.js
- frontend/src/__tests__/containers/MasterWindow.test.js
- frontend/src/actions/TableActions.js
- frontend/src/api/window.js
- frontend/src/containers/MasterWindow.js
- frontend/test_setup/fixtures/master_window.json
- frontend/test_setup/fixtures/master_window/data.json
- frontend/test_setup/fixtures/master_window/layout.json
- frontend/test_setup/fixtures/master_window/row_data.json
https://github.com/metasfresh/metasfresh/issues/6838
> [WebUI] Support returning a 2xx status code for non-existing document rows

- frontend/src/components/header/Header.js
https://www.loom.com/share/21d83d4e22e346f0bbc0a080ac7dd683
> Fix breadcrumbs after clicking the logo

- frontend/src/assets/css/panel.css
- frontend/src/components/Container.js
https://www.loom.com/share/5e9c1f1bf77e415facf9a8438198a8b4
> Add vertical scroll on overflow

- frontend/src/utils/documentListHelper.js
> Refreshing page looses pagination #6967

- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/validator/PP_Order.java
- backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/model/validator/PP_OrderPOCopyRecordSupport.java
- backend/de.metas.materialtracking/src/main/sql/postgresql/system/50-de.metas.materialtracking/5563380_sys_gh7009_PP_Order_MarkColumnsAsIsCalculated.sql
- backend/de.metas.materialtracking/src/main/sql/postgresql/system/50-de.metas.materialtracking/5563470_sys_gh7009_PP_Order_MarkColumnsAsIsCalculated_2.sql
- backend/de.metas.materialtracking/src/main/sql/postgresql/system/50-de.metas.materialtracking/5563520_sys_gh7009_PP_Order_MarkColumnsAsIsCalculated_3.sql
https://github.com/metasfresh/metasfresh/issues/7009
> Copy w/ details for Manufacuring Order

- frontend/src/containers/Table.js
https://www.loom.com/share/02b6a51a59f54c69ad89b7398d121289
> Refresh after deletion the tab if in response we have the tabId

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/CacheInvalidateMultiRequest.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/CacheInvalidateRequest.java
- backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionUpdater.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/events/DocumentWebsocketPublisher.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/events/JSONDocumentChangedWebSocketEventCollector.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/invalidation/DocumentCacheInvalidationDispatcher.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
https://www.loom.com/share/ced0ff530da649688cb96f6b32828134
> Included tab web socket notification fixes

- frontend/src/__tests__/reducers/ViewHandler.test.js
- frontend/src/actions/TableActions.js
- frontend/src/actions/ViewActions.js
- frontend/src/containers/DocumentList.js
- frontend/src/reducers/viewHandler.js
- frontend/src/utils/documentListHelper.js
- frontend/test_setup/fixtures/grid/reducers.json
> Support refreshing viewId in modals properly

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563630_sys_gh7021_AddSysconfigFor_PackageableRow.warehouseTypeName.IsDisplayed.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5563650_sys_gh7021_AddSysconfigFor_PackageableRow.POReference.IsDisplayed.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/I_M_Packageable_V.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/X_M_Packageable_V.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/Packageable.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/PackagingDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/de_metas_inoutcandidate/M_Packageable_v.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5563640_sys_gh7021_Add_M_Packageable_V.POReference.sql
- backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.inoutcandidate/5563720_sys_gh7021_Add_M_Packageable_V.POReference.sql
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableRow.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableRowsRepository.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_PickAndPackSelected.java
https://github.com/metasfresh/metasfresh/issues/7021
> Picking Terminal V2: Pick&Pack: Skip rows with qty 0

- frontend/src/components/header/Breadcrumb.js
https://www.loom.com/share/8d9ec683a563434896e506a0c754ede8
> Add extra checks for clearing the filter

- frontend/src/components/widget/MasterWidget.js
https://www.loom.com/share/c89bad4fd26c46d9a9dfaacfa574a989
As agreed not doing the highlighting would at least not raise the expectation of it was saved
> Active field colour after patch only

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_InOut_Shipment_SelectHUs.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/CreateViewRequest.java
https://github.com/metasfresh/metasfresh/issues/6420
> Customer return not working bc HUs cannot be selected

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5564060_sys_gh7044_Fix_M_Product_to_BOMReference.sql
https://github.com/metasfresh/metasfresh/issues/7044
> Fix Document Reference Product -> BOM

- backend/de.metas.payment.esr/src/main/java-gen/de/metas/payment/esr/model/I_ESR_ImportLine.java
- backend/de.metas.payment.esr/src/main/java-gen/de/metas/payment/esr/model/X_ESR_ImportLine.java
https://github.com/metasfresh/metasfresh/issues/6714
> #6714 I didn't use these column in the end

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java
https://github.com/metasfresh/metasfresh/issues/6997
> Do not show action Picking Terminal V2 -> Picking -> Process if there are no rows available for processing

- frontend/src/components/DataLayoutWrapper.js
- frontend/src/components/app/DocumentList.js
- frontend/src/components/app/SelectionAttributes.js
- frontend/src/reducers/tables.js
Related to #7063 . Also did some small refactoring to get rid of unnecessary re-renders.
> Fetch selection attributes when component is constructed

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5564360_sys_gh7071ModifyLoginOrgColumnAdRoleTableReference.sql
> #7071 Made Login Org field lookup widget.

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/AddressBuilder.java
> #7077 Now rendering country in bpartner language in the location sub-tab of the bpartner window.

- frontend/src/actions/ViewActions.js
- frontend/src/components/table/Table.js
- frontend/src/components/table/TableWrapper.js
- frontend/src/containers/DocumentList.js
- frontend/src/containers/Table.js
- frontend/src/reducers/viewHandler.js
> Cleanup the redux state for views/tables

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5564260_sys_gh7064_Add_New_table_for_Traces.sql
#7064 Create a new structure for Allergen traces in the product as a new tab
> #7064 Add product traces structure

- misc/services/camel/de-metas-camel-shipping/src/main/java/de/metas/camel/shipping/shipment/ShipmentXmlToJsonRouteBuilder.java
- misc/services/camel/de-metas-camel-shipping/src/main/java/de/metas/camel/shipping/shipment/SiroShipmentConstants.java
- misc/services/camel/de-metas-camel-shipping/src/main/resources/shipping.properties
refs: https://github.com/metasfresh/metasfresh/issues/7052
> store files locally before processing

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/model/interceptor/C_BPartner.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/location/impl/AddressBuilder.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/process/UpdateAddresses.java
> #7091 Recalculate address in location sub-tab when bpartner language gets changed.

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/parser/FileImportReader.java
- backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/parser/FileImportReaderTest.java
- backend/de.metas.adempiere.adempiere/base/src/test/resources/de/metas/impexp/parser/evenNumberOfQuotes.csv
https://github.com/metasfresh/metasfresh/issues/7097
> Handle even number of quotes when reading a file in MultilineProcessor

- backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_Flatrate_Term.java
- backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Term.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
- backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
- backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5564650_sys_gh7093_C_Flatrate_Term_C_Order_Term_ID_Real_Column.sql
- backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/AbstractFlatrateTermTest.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/invoicecandidate/FlatrateTermHandlerTest.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/order/ContractOrderTest.java
- backend/de.metas.contracts/src/test/java/de/metas/contracts/subscription/order/restart/RelatedSubscriptionsForOrderProviderTest.java
* Make it a real column
* Propagate it on term extension
https://github.com/metasfresh/metasfresh/issues/7093
> #7093 C_Flatrate_Term_C_Order_Term_ID

- backend/de.metas.business/src/main/java/de/metas/request/api/IRequestTypeDAO.java
- backend/de.metas.business/src/main/java/de/metas/request/api/impl/RequestDAO.java
- backend/de.metas.business/src/main/java/de/metas/request/api/impl/RequestTypeDAO.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java
https://github.com/metasfresh/metasfresh/issues/7099
> #7099 Setting request type to default request type or first active.

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUAssignmentDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUInOutBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUInOutDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutDAO.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOut.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateRepository.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateService.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/AddQtyToHUCommand.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/IHUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleBL.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilder.java
- backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5564640_sys_gh7101_showAllPickingCandidates_sysConfig.sql
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/AbstractHandlingUnitsBLTest.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/PickingConstants.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/packageable/PackageableView.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/PickingHURowsRepository.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotRepoQuery.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotViewFactory.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotViewRepository.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotViewsIndexStorage.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToExistingHU.java
- backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/picking/pickingslot/PickingHUsRepositoryTests.java
refs: https://github.com/metasfresh/metasfresh/issues/7101
> picking terminal details

- backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_Order.java
https://github.com/metasfresh/metasfresh/issues/7012
> Also preventing closing of PO or SO Orders with exported shipment or material receipt schedules.

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5564880_sys_gh7062_UpdateAllTrlMigrationFunctions.sql
https://github.com/metasfresh/metasfresh/issues/7062
> Add migration script containing all our update_element to/from functions

- frontend/src/__tests__/components/table/TableQuickInput.test.js
- frontend/src/__tests__/components/widget/RawWidget.test.js
- frontend/src/__tests__/containers/MasterWindow.test.js
- frontend/src/actions/GenericActions.js
- frontend/src/actions/ViewActions.js
- frontend/src/actions/WindowActions.js
- frontend/src/api/window.js
- frontend/src/components/table/TableFilter.js
- frontend/src/components/table/TableHeader.js
- frontend/src/components/table/TableQuickInput.js
- frontend/test_setup/fixtures/table/table_quick_input.json
- frontend/test_setup/fixtures/table/table_quickinput.json
- frontend/test_setup/jestSetup.js
Reverts metasfresh/metasfresh#7095
> Revert "[frontend] Improving stability of unit tests"

- backend/de.metas.business/src/main/java/de/metas/costing/CostPrice.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.business/src/main/java/de/metas/product/ProductCategoryId.java
- backend/de.metas.business/src/test/java/de/metas/costing/methods/AveragePOCostingMethodHandlerTest.java
https://github.com/metasfresh/metasfresh/issues/6867
> AveragePOCostingMethodHandlerTest + hotfix for case3

- frontend/src/__tests__/components/app/Modal.test.js
- frontend/src/components/app/Modal.js
- Made Modal a connected component again
- It was initially made disconnected for the sole purpose of testing createProcess
- having it disconnected causes the issue from https://github.com/metasfresh/metasfresh/issues/7128
- skipped the createProcess test - following to add it back (most probable during refactoring, as having the component disconnected implies more fixes as there might be more corner cases where similar issues can occur)
Note: Having this functional is needed for this release!
> Made Modal a connected component again 

- backend/de.metas.business/src/main/java/de/metas/costing/ICostDetailService.java
- backend/de.metas.business/src/main/java/de/metas/costing/impl/CostDetailService.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/CostingMethodHandlerUtils.java
- backend/de.metas.business/src/main/java/de/metas/costing/methods/StandardCostingMethodHandler.java
https://github.com/metasfresh/metasfresh/issues/6867
> Gh6867 always capture prev costs

- backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
https://github.com/metasfresh/metasfresh/issues/6867
> #6867 convert currency of match invoice on cost creation

- frontend/src/utils/documentListHelper.js
> Use pagination info from the data store

- frontend/src/actions/AppActions.js
- frontend/src/containers/DocList.js
- frontend/src/containers/DocumentList.js
- frontend/src/reducers/viewHandler.js
- frontend/src/utils/documentListHelper.js
> Fix redirecting to view via link

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565300_sys_gh7155_current_costs_window_improvements.sql
https://github.com/metasfresh/metasfresh/issues/7155
> window layout improvements: current costs

- frontend/src/components/widget/MasterWidget.js
Special case for attributes. @petrican can you take it from here ?
Related to #7158
> [frontend] Update property in the store when widget is patched

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Order_Root.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5565340_sys_gh7159_AddPrepaymentChecks.sql
#7159 Add prepayment check in sales order functions
> #7159 Add prepayment check in sales order functions

- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/JsonRetrieverService.java
- backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/jsonpersister/JsonPersisterService.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/bpartner/impl/BPartnerRecordsUtil.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/bpartner/impl/MockedDataUtil.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImplTest.java
- backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/ordercandidates/impl/TestMasterdata.java
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/bpartner/impl/BpartnerRestControllerTest.snap
- backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/bpartner/impl/bpartnercomposite/JsonRetrieverServiceTest.snap
- backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/request/JsonRequestBPartner.java
- backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/response/JsonResponseBPartner.java
- backend/de.metas.business.rest-api/src/test/java/de/metas/rest_api/ordercandidates/model/JsonOLCandModelTest.java
- backend/de.metas.business.rest-api/src/test/resources/de/metas/rest_api/bpartner/JsonBPartnerUpsertRequest_1.json
- backend/de.metas.business.rest-api/src/test/resources/de/metas/rest_api/bpartner/request/JsonRequestBPartnerUpsertItemTest.snap
- backend/de.metas.business.rest-api/src/test/resources/de/metas/rest_api/bpartner/request/JsonRequestBPartnerUpsertTest.snap
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartner.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java
- backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/ChangeLogUtil.java
- backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/resources/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsServiceTest.snap
https://github.com/metasfresh/metasfresh/issues/7142
> OLCand/BPartner REST Endpoints: import C_BPartner.VATaxId

- backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/RV_Unposted.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5565370_sys_gh6867_RV_UnPosted_PostingError_Issue_ID.sql
- backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5565371_sys_gh6867_RV_UnPosted_DDL.sql
https://github.com/metasfresh/metasfresh/issues/6867
> RV_UnPosted.PostingError_Issue_ID

- backend/de.metas.util/src/main/java/org/adempiere/util/lang/SynchronizedMutable.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/CompositeViewHeaderPropertiesProvider.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/DefaultView.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/InvoiceCandidateViewHeaderPropertiesProvider.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/NullViewHeaderPropertiesProvider.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/ViewHeaderPropertiesIncrementalResult.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/ViewHeaderPropertiesProvider.java
https://github.com/metasfresh/metasfresh/issues/7152
> Flickering window after starting process on other machine

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandPIIPListener.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandPIIPPriceValidator.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandPIIPUtil.java
- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandProductFromPIIPvalidator.java
- backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandProductFromPIIPvalidatorTest.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandEffectiveValuesBL.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandEffectiveValuesBL.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/DefaultOLCandValidator.java
https://github.com/metasfresh/metasfresh/issues/7085
> Supplement C_OLCand.M_Product_ID from  M_HU_PI_Item_Product_ID if need

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/ProcessRestController.java
#9847 CU Label not working Error: Cannot convert HUReport_541195
(broken in https://github.com/metasfresh/metasfresh/issues/6771)
> #9847 Fix running reports from Handling unit

- backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_GLJournal.java
> 7073 kommch gl journal tax amount 0

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5565660_sys_gh9838_AddSeqNoInAD_Language.sql
#9838 Add SeqNo on AD_language
> #9838 Add SeqNo on AD_language

- frontend/.eslintrc
> Tune up eslint not to flag incorrectly the imports

- frontend/src/components/widget/DatePicker.js
- frontend/src/components/widget/TetheredDateTime.js
> Fix handling events in the datepicker

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565000_sys_gh7109AddUpdateOrderAndInvoiceIdProcess.sql
> #7109 Assign process to table

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565960_sys_gh9863_CreditMemo_For_Paid_Invoice_Messages.sql
- backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
* Ony if the invoice is not referenced
https://github.com/metasfresh/metasfresh/issues/9863
> # Allow creating credit memo for paid invoice

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565890_sys_gh9860_Fix_Product.IsVerifiedWhenBomIsMissing.sql
- backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
- backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
https://github.com/metasfresh/metasfresh/issues/9860
> BOM verified in product window show main grid + filter 

- misc/services/camel/de-metas-camel-shipping/src/main/java/de/metas/camel/shipping/RouteBuilderCommonUtil.java
- misc/services/camel/de-metas-camel-shipping/src/main/java/de/metas/camel/shipping/receiptcandidate/ReceiptCandidateJsonToXmlRouteBuilder.java
- misc/services/camel/de-metas-camel-shipping/src/main/java/de/metas/camel/shipping/shipmentcandidate/ShipmentCandidateJsonToXmlRouteBuilder.java
- misc/services/camel/de-metas-camel-shipping/src/main/resources/shipping.properties
- misc/services/camel/de-metas-camel-shipping/src/test/resources/shipping.properties
refs: https://github.com/metasfresh/metasfresh/issues/9868
> Enhance upload receipt and shipment candidates uri flexibility

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565900_sys_gh9862_AddSysconfigForHUEditorRow.SerialNo.IsDisplayed.sql
- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565920_sys_gh9862_AddVirtualColumn_M_HU.SerialNo.sql
- backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributesSupplier.java
https://github.com/metasfresh/metasfresh/issues/9862
> Show serial number in production HU selection window

- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/M_Cost_CostPrice_Function.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getCurrentCost.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5566100_sys_gh9878_Lagerwert_With_M_Cost.sql
https://github.com/metasfresh/metasfresh/issues/9878
> #9878 Lagerwert from M_Cost

- backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5566220_sys_gh9882_AddDummyTabTo_MaterialCockpit.sql
I think this fixes the permissions issue
https://github.com/metasfresh/metasfresh/issues/9882
> Add a dummy tab to Material Cockpit window

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/provider/standard/FacetsFilterLookupDescriptor.java
https://github.com/metasfresh/metasfresh/issues/9886
> Add support for String Facets

- frontend/src/components/table/TableWrapper.js
- frontend/src/utils/documentListHelper.js
> Fix pagination on refresh/back

- backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/interceptor/M_InventoryLine.java
> #9891 Now setting the Product's uom when selecting a product in the inventory line.

- backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
https://github.com/metasfresh/metasfresh/issues/9895
> #9895 Implement display logic for Labels 

- backend/de.metas.edi/src/main/sql/postgresql/system/5566640_sys_gh9908_OLcand_rename_existing_process_and_add_new_one.sql
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/org/adempiere/server/rpl/trx/process/C_OLCand_Update_IsImportedWithIssues_Base.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/org/adempiere/server/rpl/trx/process/C_OLCand_Update_IsImportedWithIssues_Selection.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/java/org/adempiere/server/rpl/trx/process/C_OLCand_Update_IsImportedWithIssues_SingleRplTrx.java
- backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandValidatorService.java
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5566640_sys_gh9908_OLCand_rename_existing_process_and_add_new_one.sql
- backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5566770_sys_gh9908_OLCand_new_process_description.sql
https://github.com/metasfresh/metasfresh/issues/9908
> split old table in base and concrete impl; add another concrete impl

- backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/po/POTrlRepository.java
> #9904 Also saving a product trl in the base language.

- backend/de.metas.adempiere.libero.libero/src/main/java/org/eevolution/api/impl/DD_Order_MovementBuilder.java
- backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5566930_sys_gh9919_AddErrorMessage.sql
Throw and error when there is not Transit Locator when completing a DD Order #9919
> #9919 Throw and error when there is not Transit Locator when completing a DD Order 
