backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5567040_sys_gh9924_Mark_Invoice.Alocation_AD_Tab.IsAdvancedTab_False.sql

https://github.com/metasfresh/metasfresh/issues/9924

Mark Invoice.Allocation AD_Tab as IsAdvancedTab='N'

---

backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_v_view.sql
backend/de.metas.edi/src/main/sql/postgresql/system/5567170_sys_gh7085_Migrate_DesadvLine_QtyItemCapacity.sql
backend/de.metas.edi/src/main/sql/postgresql/system/5567170_sys_gh7085_QtyToInvoiceBasedOn_info_in_DESADV_and_INVOIC.sql
backend/de.metas.edi/src/main/sql/postgresql/system/5567171_sys_gh7085_QtyToInvoiceBasedOn_info_in_DESADV_and_INVOIC_DDL.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/esb/util/CanonicalXSDGenerator.java
e2e/Dockerfile
misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd

* CanonicalXSDGenerator does not output minOccurs and maxOccurs=1 because it creates a bunch of warnings
https://github.com/metasfresh/metasfresh/issues/7085

add InvoicableQtyBasedOn info to INVOIC and DESADV-(hdr); also:

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/receipt/ReceiptService.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/InOutProducer.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleExternalInfo.java
misc/de-metas-common/de-metas-common-shipping/src/main/java/de/metas/common/receipt/JsonCreateReceiptInfo.java
misc/services/camel/de-metas-camel-shipping/src/main/java/de/metas/camel/shipping/receipt/ReceiptXmlToJsonProcessor.java
misc/services/camel/de-metas-camel-shipping/src/test/resources/de/metas/camel/shipping/receipt/JsonCreateReceiptsRequest.json
misc/services/camel/de-metas-camel-shipping/src/test/resources/de/metas/camel/shipping/receipt/SiroCreateReceipts.xml

refs: https://github.com/metasfresh/metasfresh/issues/9933

store externalResourceURL when creating Receipts via REST endpoint

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5567660_sys_gh9948UOMVirtualColumnToTransactionTableAndWindow.sql

Added UOM to 'Produkt transaktionen' window

---

frontend/src/components/table/Table.js
frontend/src/components/table/TableContextMenu.js
frontend/src/components/table/TableWrapper.js

https://www.loom.com/share/ce1fc7b9e179403e9aac4f28019d1214

9947 zoom links cut off

---

frontend/src/components/table/TableItem.js
frontend/src/components/widget/MasterWidget.js

This PR fixes the case for Enter key and when you click away.
https://www.loom.com/share/6cd70c895cda4b2494299dd494ef64e7

9940 qty decimals po - edge cases

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/getCurrentCost.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5567880_sys_gh9878_M_CostElement_CostingMethod_UniqueIndex.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5567910_sys_gh9878_Lagerwert_Functions_Modified.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5567920_sys_gh9878_Lagerwert_Process_And_Menu.sql

https://github.com/metasfresh/metasfresh/issues/9878

#9878 Lagerwert (Excel)

---

frontend/src/__tests__/actions/WindowActions.test.js
frontend/src/actions/WindowActions.js
frontend/src/components/app/RawModal.js
frontend/src/containers/DocumentList.js
frontend/test_setup/fixtures/window/actions.json

Fix included views in process modals with actions

---

frontend/src/assets/css/inputs.css
frontend/src/components/widget/DatetimeRange.js

https://www.loom.com/share/1d1fbae4fc2e46658c7b3c2f0fd7275b

Cancel btn for date in filters

---

frontend/src/components/table/TableContextMenu.js
frontend/src/constants/Constants.js

https://www.loom.com/share/e6e1a78abeed4dafa7e0c1f20ee0a849
Target branch master

Fix the issues found on QA testing

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5567930_sys_gh9935NewAd_Rel_Type_Entries.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5567950_sys_gh9935DisplayingProjectFieldInInOutLineAndInvoiceLine.sql
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/ShipmentLineBuilder.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java

#9935 C_project_id propagation and window adjustments

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5567990_sys_gh9969SideListReferenceBetweenQuotationAndOrderAndViceVersa.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/C_Order_CreateFromQuotation_Construction.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java

Order from offer (construction) reference to offer

---

frontend/src/containers/DocumentList.js

https://www.loom.com/share/c12177c5f21f4648a5efada9bc848eb0

Fix breadcrumbs content when we are on dashboard

---

frontend/src/actions/MenuActions.js

Removed some code that was added with the issue https://github.com/metasfresh/metasfresh-webui-frontend-legacy/issues/979

Removed some deprecated code

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568030_sys_gh9958_Update_EN_Trl.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568200_sys_gh9958_ChangeOrgOfProductPlanningSchema.sql
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MProduct.java
backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
backend/de.metas.business/src/main/java/de/metas/product/IProductPlanningSchemaBL.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductPlanningSchemaBL.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductPlanningSchemaDAO.java
backend/de.metas.business/src/main/java/de/metas/product/model/interceptor/M_Product.java
backend/de.metas.business/src/test/java/de/metas/product/impl/ProductPlanningSchemaBLTest.java
backend/de.metas.util/src/main/java/org/adempiere/util/lang/ImmutablePair.java

https://github.com/metasfresh/metasfresh/issues/9958

Fix wrong Org for ProductPlanning when created from ProductPlanningSchema

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/crm/interceptor/R_Request.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java

https://github.com/metasfresh/metasfresh/issues/9986

Kontakte Mobil Start date not initially set - regression

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568440_cli_gh9988_AD_TreeBar_delete_duplicates.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568450_sys_gh9988_AD_TreeBar_unique_index.sql

https://github.com/metasfresh/metasfresh/issues/9988

AD_TreeBar: delete duplicates, enforce unique index

---

frontend/src/components/widget/ActionButton.js

https://www.loom.com/share/95aaaee987274ac6a18b3a26f17c6e87

Add missing prompt from the state

---

frontend/src/assets/css/header.css
frontend/src/components/header/MenuOverlay.js
frontend/src/constants/Constants.js

https://www.loom.com/share/c5ce719dab3545a0973d358661a02edd
Notes: The functionality within the MenuOverlay component is done with DOM selectors. As much as I wanted to change that I cannot as this is beyond the scope or the budget allocated for the task. Also used the DOM selectors to comply with that code where is the case. @siemiatj

Automatically mark preselection for first entry in list

---

frontend/src/containers/DocumentList.js
frontend/src/store/customMiddlewares.js

https://www.loom.com/share/baa4cf8b760141feb8f224f6e98d4fe5

Fixes for Dashboard breadcrumbs path

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java

https://github.com/metasfresh/metasfresh/issues/10005

Set DEFAULT_PAYMENT_ROW where it was forgotten

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568580_sys_gh10001_C_Invoice_M_Warehouse_ID.sql
backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceLineBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceLineBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/InvoiceLine.java

https://github.com/metasfresh/metasfresh/issues/10001

Gh10001 Compute taxes based on C_Invoice.M_Warehouse_ID

---

backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/de.metas.business/src/test/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyServiceTest.java
backend/de.metas.business/src/test/java/de/metas/invoice/service/IInvoiceBLTest.java
backend/de.metas.business/src/test/java/de/metas/invoice/service/impl/InvoiceBLRenumberTests.java
backend/de.metas.business/src/test/java/de/metas/invoice/service/impl/InvoiceBLSortLinesTests.java
backend/de.metas.business/src/test/java/de/metas/invoice/service/impl/InvoiceBLTest.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/businesslogic/sales/commissiontrigger/salesinvoiceline/SalesInvoiceFactoryTest.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/interceptor/C_InvoiceFacadeServiceTest.java
backend/de.metas.contracts/src/test/resources/de/metas/contracts/commission/commissioninstance/businesslogic/sales/commissiontrigger/salesinvoiceline/SalesInvoiceFactoryTest.snap
backend/de.metas.document.archive/de.metas.document.archive.base/src/test/java/de/metas/document/archive/async/spi/impl/DocOutboundWorkpackageProcessorTest.java
backend/de.metas.dunning/src/test/java/de/metas/document/archive/async/spi/impl/DocOutboundWorkpackageProcessorTest.java
backend/de.metas.dunning/src/test/java/de/metas/dunning/DunningTestBase.java
backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/AllAvailableSingletonServicesTest.java
backend/de.metas.payment.esr/src/main/java-gen/de/metas/payment/esr/model/I_ESR_ImportLine.java
backend/de.metas.payment.esr/src/main/java-gen/de/metas/payment/esr/model/X_ESR_ImportLine.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/actionhandler/impl/DiscountESRActionHandler.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/model/validator/ESR_Main_Validator.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/validationRule/ESRPaymentActionValidationRule.java
backend/de.metas.payment.esr/src/main/sql/postgresql/system/5568410_sys_gh9987_AddNewESRPaymentAction.sql
backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/ESRTestBase.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/allocation/api/impl/AllocationBLTest.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoicesTest.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueueToInvoice_Locking_Test.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/payment/api/impl/PaymentBLTest.java
backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java

Enable a discount for ESR payments #9987

#9987 Enable a discount for ESR payments 

---

frontend/src/__tests__/components/table/Table.test.js
frontend/src/__tests__/components/table/TableHeader.test.js
frontend/src/actions/TableActions.js
frontend/src/actions/ViewActions.js
frontend/src/components/Window.js
frontend/src/components/table/TableHeader.js
frontend/src/constants/ActionTypes.js
frontend/src/containers/MasterWindow.js
frontend/src/reducers/tables.js

Alternative fix for ordering tables

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568770_sys_gh10010ShowOrgBpartnersInBpartnerWindowAndAddSidelistReferences.sql

#10010 Bpartner window and Org Masterdata reference and adjustments

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Cost_Collector_ImportAudit.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Cost_Collector_ImportAuditItem.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Cost_Collector_ImportAudit.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Cost_Collector_ImportAuditItem.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IPPOrderReceiptHUProducer.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrderAPIService.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrderExportAuditRepository.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrderReportAuditRepository.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrderReportProcessCommand.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrdersExportCommand.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrdersSetExportStatusCommand.java
backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/manufacturing/rest_api/ManufacturingOrderAPIServiceTest.java
backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/manufacturing/rest_api/ManufacturingOrderAuditRepositoryTest.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/exportaudit/APITransactionId.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/exportaudit/ManufacturingOrderExportAudit.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/importaudit/ManufacturingOrderReportAudit.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/order/importaudit/ManufacturingOrderReportAuditItem.java
backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5568800_sys_gh9877_PP_Cost_Collector_ImportAudit.sql
backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5568810_sys_gh9877_PP_Cost_Collector_ImportAudit_windows.sql
misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/manufacturing/JsonResponseIssueToManufacturingOrderDetail.java
misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/manufacturing/JsonResponseReceiveFromManufacturingOrder.java

https://github.com/metasfresh/metasfresh/issues/9877

manufacturing issue/receipt import audit

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569000_sys_gh10027_delete_R_Request.StartDate.sql

https://github.com/metasfresh/metasfresh/issues/10027

Drop column R_Request.StartDate and all depending AD elements

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5568990_sys_gh9937_remove_misleading_replenish_fields.sql
backend/de.metas.material/dispo-commons/src/main/java-gen/de/metas/material/dispo/model/I_MD_Candidate.java
backend/de.metas.material/dispo-commons/src/main/java-gen/de/metas/material/dispo/model/X_MD_Candidate.java
backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/CandidateRepositoryRetrieval.java
backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/CandidateRepositoryWriteService.java
backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/query/MaterialDescriptorQuery.java
backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/candidatechange/StockCandidateService.java
backend/de.metas.material/dispo-service/src/main/sql/postgresql/system/75-material-dispo/5568970_sys_gh9937_md_candidate_add_isReservedForCustomer.sql
backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/candidatechange/StockCandidateServiceTests.java
backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/shipmentschedule/ShipmentScheduleCreatedHandlerTests.java
backend/de.metas.material/event/src/main/java/de/metas/material/event/commons/MaterialDescriptor.java

Blonde monkey hotfix support no reservation

---

backend/de.metas.util/src/main/java/org/adempiere/util/lang/SynchronizedMutable.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/DocumentFilter.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/DefaultView.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/SqlViewFactory.java

https://github.com/metasfresh/metasfresh/issues/10030

Do not add duplicate filters to a View

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentOrderByBuilder.java

#10035 Can now sort by 'ID' type virtual columns. (i.e: columns that aren't a direct reference to a value from another table).

---

frontend/src/components/widget/Lookup/Lookup.js
frontend/src/reducers/windowHandler.js

Stop crashing when field data is missing

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569190_sys_gh10046ChangeColumnSqlOfFilteredItemsWithSameHeaderAggregationKeyColumn.sql

#10046 Changed columnsql of FilteredItemsWithSameHeaderAggregationKeyColumn.

---

backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/HUAttributeConstants.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/PPOrderProductAttributeBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/ExpiredAttributeStorageListener.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IPPOrderReceiptHUProducer.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/ReceiptScheduleHUGenerator.java
backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5569080_sys_gh10022_AddSysconfigs.sql
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/ReceiptScheduleBasedProcess.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveCUs.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveHUs_Base.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Receipt.java

https://github.com/metasfresh/metasfresh/issues/10022

Automatically set `HU.BestBeforeDate` and `HU.LotNr` attributes during Manfacturing

---

backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/C_Order.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandDAO.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/PoReferenceLookupKey.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandDAO.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/modelvalidator/C_OLCand.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/modelvalidator/M_ShipmentSchedule.java
backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5569180_sys_gh10046_nrOfOLCandsWithSamePOReference.sql
backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5569290_sys_gh10046_setPoReferenceToShipmentSchedule.sql
backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5569350_sys_gh10046_PoReference_Indexes.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/I_M_ShipmentSchedule.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/inoutcandidate/model/X_M_ShipmentSchedule.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ShipmentScheduleRepository.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentSchedulePA.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/OlAndSched.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java

refs: https://github.com/metasfresh/metasfresh/issues/10046

m_shipmentSchedule.nrOfOLCandsWithSamePOReference

---

frontend/src/assets/css/styles.css
frontend/src/assets/css/table.css

Move some table-related styles from styles.css

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java

https://github.com/metasfresh/metasfresh/issues/10051

#10051 Initialize the invoice with the org of the header

---

backend/de.metas.business/src/main/java/de/metas/bpartner/product/stats/BPartnerProductStatsEventHandler.java
backend/de.metas.business/src/main/java/de/metas/bpartner/product/stats/BPartnerProductStatsEventListener.java
backend/de.metas.business/src/main/java/de/metas/bpartner/product/stats/BPartnerProductStatsService.java

..and only on app.
to avoid the error "ERROR: duplicate key value violates unique constraint "c_bpartner_product_stats_uq""

make sure that just one thread at a time can create new bpartner-stats

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
backend/de.metas.issue.tracking.github/src/main/java/de/metas/issue/tracking/github/api/v3/service/GithubClient.java
backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/I_S_FailedTimeBooking.java
backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/I_S_Issue.java
backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_FailedTimeBooking.java
backend/de.metas.serviceprovider/src/main/java-gen/de/metas/serviceprovider/model/X_S_Issue.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/everhour/EverhourImporterService.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImporterConstants.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/GithubImporterService.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/label/LabelService.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/github/label/ProcessedLabel.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueEntity.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueRepository.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/IssueImporterService.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/info/ImportIssueInfo.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/interceptor/S_Issue.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/importer/TimeBookingsImporterService.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/timebooking/importer/failed/FailedTimeBookingRepository.java
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5569500_sys_gh10057_effort_budget_issue_showCreatedDate.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5569510_sys_gh10057_budgetIssue_dateDelivered.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5569520_sys_gh10057_s_issue_processedDate.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5569530_sys_gh10057_budgetIssue_gridViewAdjustments.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5569550_sys_gh10057_failedTimeBookingsAdjustments.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5569560_sys_gh10057_S_Issue_internalDeliveredDate.sql
backend/de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/github/GithubImporterServiceTest.java

refs: https://github.com/metasfresh/metasfresh/issues/10057

service provider platform enhancements

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569620_sys_gh10059_Invoice_Doctype_Only_From_InvoiceOrg_Or_0.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569660_sys_gh10059_Order_Doctype_Only_From_OrderOrg_Or_0.sql

https://github.com/metasfresh/metasfresh/issues/10059

#10059 Only allow doctypes of invoice org or * on manual invoices

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5569170_sys_gh10045_AddSysConfig.sql
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/quickinput/ddorderline/DDOrderLineQuickInputCallout.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/quickinput/field/DefaultPackingItemCriteria.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/quickinput/field/PackingItemProductFieldHelper.java

#10045 Packing instructions are no longer displayed when ordering

#10045 Packing instructions are no longer displayed when ordering 

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java

https://github.com/metasfresh/metasfresh/issues/10070

#10070 Unlink orderlines from compensation groups before deleting the order

---

backend/de.metas.material/commons/src/main/java/de/metas/material/commons/attributes/AttributesKeyPartPattern.java
backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/atp/AvailableToPromiseResultBuilder.java

refs: https://github.com/metasfresh/metasfresh/issues/10068

attribute matching fix

---

backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/repository/atp/AvailableToPromiseResultBucket.java
backend/de.metas.material/dispo-commons/src/test/java/de/metas/material/dispo/commons/repository/atp/AvailableToPromiseResultTest.java

refs: https://github.com/metasfresh/metasfresh/issues/10068

attribute group matching fix

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569960_sys_gh10083_ExportStatus_In_Windows.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569980_sys_gh10083_ExportStatus_Process_PP_Order.sql
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderDAO.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/process/M_ReceiptSchedule_ChangeExportStatus.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_ChangeExportStatus.java

https://github.com/metasfresh/metasfresh/issues/10083

#10083 Modify ExportStatus + windows changing + refactoring

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java

#10084 DatePromised and PreparationDate shall be copied From Offer when creating a sales order

#10084 Set DatePromised and PreparationDate from Offer

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryWebuiTools.java

https://github.com/metasfresh/metasfresh/issues/10103

#10103 display updatedBy in Dataentry Field

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
backend/de.metas.business/src/main/java/de/metas/phonecall/process/C_Phonecall_Schedule_CreateSalesOrder.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/ProcessInstanceResult.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/process/json/JSONProcessInstanceResult.java
frontend/src/actions/WindowActions.js
frontend/src/utils/index.js

https://github.com/metasfresh/metasfresh/issues/10101

Phonecall Schedule - Create Sales Order - open in new tab

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_UI_Section.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_UI_Section.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5570300_sys_gh10108_AD_UI_Section_UIStyle.sql
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayoutSection.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutSectionDescriptor.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java

https://github.com/metasfresh/metasfresh/issues/10108

introduce AD_UI_Section.UIStyle

---

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUAndItemsDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAndItemsDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/async/GenerateInOutFromShipmentSchedules.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventsService.java

HUAndItemsDAO don't assume it might have to be run in its own trx; caller needs to make sure the HU has the right trx

ShipmentScheduleWithHUService: make sure that new Hus have our trxName

---

frontend/src/components/app/OverlayField.js
frontend/src/components/table/EntryTable.js

Fix editing widgets in entry tables

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5569820_sys_gh10074_CreateWindow_PurchaseOrderCandidates.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5570220_sys_gh10074_AddFixAD_RelationTypes.sql

https://github.com/metasfresh/metasfresh/issues/10074

Create window `Purchase Order Candidates`

---

frontend/src/actions/WindowActions.js

https://www.loom.com/share/134c07dc3c954d948973bbd52a666c04

10116 two entries dbl clk 

---

backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/IssueEntity.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/IssueImporterService.java
backend/de.metas.serviceprovider/src/main/java/de/metas/serviceprovider/issue/importer/info/ImportIssueInfo.java
backend/de.metas.serviceprovider/src/test/java/de/metas/serviceprovider/issue/importer/IssueImporterServiceTest.java

https://github.com/metasfresh/metasfresh/issues/10118

avoid updating processed issues

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/mail/WebuiMailRepository.java
frontend/src/components/email/Attachments.js
frontend/src/components/email/AutocompleteTo.js

Does a patch for 'to' with the array of objects corresponding to destinations.

10096 multiple email sending

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/QtyTU.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5570590_sys_gh10122_WEBUI_PickingSlotsClearingView_TakeOutTUAndAddToLU_QtyTU_param.sql
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/pickingslotsClearing/process/WEBUI_PickingSlotsClearingView_TakeOutTUAndAddToLU.java

https://github.com/metasfresh/metasfresh/issues/10122

Picking Tray Cleaning: add QtyTU parameter to "Take out and add to LU" process

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
backend/de.metas.business/src/main/java/de/metas/product/impexp/MProductImportTableSqlUpdater.java
backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcess.java
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5570310_sys_gh10106_AddNetWeightAndRawMaterialOrigin.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5570311_sys_gh10106_AddNetWeightAndRawMaterialOrigin_DDL.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5570560_sys_gh10106_AddNewColumnIntoI_Product.sql

#10106 Add Raw Material Origin and NetWeight into Product

#10106 Add Raw Material Origin and NetWeight into Product 

---

e2e/cypress/integration/picking/pick_HUs_and_create_shipment.js
e2e/cypress/support/commands/general.js
e2e/cypress/support/commands/navigation.js
e2e/package.json

https://dashboard.cypress.io/projects/5yp4q1/runs/870/specs
Green build

Cypress picking fixes

---

frontend/src/components/widget/Labels/Label.js

https://www.loom.com/share/9f199ec4e13f465da13c6194e622f53b

Labels close

---

backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/test/AdempiereTestHelper.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreator.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/inventory/impexp/InventoryImportProcess.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.java
backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/inventory/draftlinescreator/DraftInventoryLinesCreatorTest.snap

..just log; and don't attempt to add them again
also
* AdempiereTestHelper: add method to create org with specific time zone
* InventoryImportProcess: minor improvements

DraftInventoryLinesCreator: don't fail if inventory already contains HUs

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/shipping/IShipperDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/shipping/impl/ShipperDAO.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShipmentRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShipmentService.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShippedCandidateKey.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/mpackage/ShippingPackageService.java
backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUShipperTransportationBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/AddTrackingInfosForInOutWithoutHUReq.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUShipperTransportationBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java
misc/de-metas-common/de-metas-common-shipping/src/main/java/de/metas/common/shipment/mpackage/JsonCreateShippingPackageInfo.java
misc/de-metas-common/de-metas-common-shipping/src/main/java/de/metas/common/shipment/mpackage/JsonCreateShippingPackagesRequest.java

refs: https://github.com/metasfresh/metasfresh/issues/10094

create shipping packages

---

frontend/src/components/widget/Labels/Label.js
frontend/src/components/widget/Labels/Labels.js
frontend/src/components/widget/RawWidget.js

https://www.loom.com/share/4722ea27178a48de942e046db61dfa17

Use the readonly flag and adapt logic

---

frontend/src/actions/TableActions.js
frontend/src/components/table/EntryTable.js

Merge DE changes with local state

---

frontend/src/actions/WindowActions.js
frontend/src/utils/index.js

https://www.loom.com/share/471bdafacd7c41cb910d6b7dc018e40b

Set also the processStatus when opening new tab

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShipmentCandidateAPIService.java
backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/shipping/ShipmentCandidateAPIServiceTest.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ShipmentScheduleRepository.java

https://github.com/metasfresh/metasfresh/issues/10127

Gh10127 export all shipment schedules for order

---

frontend/src/components/widget/Labels/Labels.js

https://www.loom.com/share/c692616e36634b0393a717590075e2ad

Dont show the dropdown if backspace is pressed

---

backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5570860_sys_gh10150_C_Queue_Processor_add_description.sql
backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5570861_sys_gh10150_reconfigure_C_Queue_Processor.sql
backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/dummy.sql

https://github.com/metasfresh/metasfresh/issues/10150

move shipment-sched related WP-processors into one queue

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5570710_sys_gh10130_DisableQYCodeBydefault.sql

#10130 QR Code disabled by default

#10130 QR Code disabled by default

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/document/counterDoc/C_Order_CounterDocHandler.java

https://github.com/metasfresh/metasfresh/issues/10157

#10157 set doctype target to the counter document

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/pickingv2/report.jrxml

#10159 Picking list issue - double/entries entries in some cases

#10159 Do not retrieve uom since could lead to multiple values

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/edi_desadv/ChangeEDI_ExportStatusHelper.java

Add handling for `EDIExportStatus.Error`
https://github.com/metasfresh/metasfresh/issues/10143

Status changes for DESADV #10152

---

backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommand.java
backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java

https://github.com/metasfresh/metasfresh/issues/10165

Payment allocation: outbound payment, vendor invoice, vendor CM not working

---

frontend/src/components/table/Table.js
frontend/src/utils/documentListHelper.js

Related to #10167 
Adding unit tests but this can come in a separate PR.

Allow deselecting rows

---

frontend/src/actions/FiltersActions.js
frontend/src/actions/ViewActions.js
frontend/src/reducers/filters.js
frontend/src/utils/filterHelpers.js
frontend/src/utils/index.js

Fix bug when applying date filters with initial value

---

frontend/src/assets/css/header.css
frontend/src/components/table/Table.js
frontend/src/components/table/TableRow.js

Related to #7126, #6854 , #7089

Small fixes to widgets in table and position of the notifications bell

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/exceptions/BPartnerException.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/exceptions/BPartnerNoAddressException.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/exceptions/BPartnerNoBillToAddressException.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/exceptions/BPartnerNoShipToAddressException.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/Amount.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/currency/AmountTest.java
backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfigRepository.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyService.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommand.java
backend/metasfresh-webui-api/src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java

https://github.com/metasfresh/metasfresh/issues/10023

Payment service providers also calculate fee on credit memos

---

frontend/src/__tests__/utils/widgetHelper.test.js

- fixes for widget helper getFormattedDate test to take into account the time zone
Without this fix if you run it for example on Europe/Bucharest the test will not pass.
https://www.loom.com/share/075e38e9787c42c2a4be3adfc9ea24e4

Take into account the tz

---

frontend/src/__tests__/components/app/Modal.test.js
frontend/src/components/app/Modal.js

https://github.com/metasfresh/metasfresh/issues/10174

10174 unskip modal test

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java

#10035 Can now sort by all types of virtual columns.

---

frontend/src/components/widget/Attributes/Attributes.js
frontend/src/components/widget/WidgetRenderer.js

https://www.loom.com/share/1b71ee0380264bf5b23d911091db30b3
https://github.com/metasfresh/metasfresh/issues/10201

Prevent dup PATCH request within attributes

---

frontend/src/components/notifications/Notification.js
frontend/src/constants/Constants.js

https://github.com/metasfresh/me03/issues/4324
https://www.loom.com/share/ffab0c7b224147f5ae6973441545e536

Strip header and show only the error

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java

https://github.com/metasfresh/metasfresh/issues/10204

#10204 respect the reference and valrule from AD_Field in the AD_UI_Element labels

---

frontend/src/components/widget/WidgetRenderer.js

https://www.loom.com/share/a974f51ce9d8474ba8445ddfd8b67a51
https://github.com/metasfresh/metasfresh/issues/10214

Fix the UI element labels patch

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java

https://github.com/metasfresh/metasfresh/issues/10204

#10204 handle IDs correctly

---

frontend/src/components/widget/ActionButton.js

https://www.loom.com/share/9b42d861eae54331ab3f4bfd413e0407

10210 DocAction disable while processing

---

frontend/src/actions/AppActions.js
frontend/src/containers/DocumentList.js

https://www.loom.com/share/0ce8d2b00c75468ca38f0cad54b8d919

Browser history on applying filters

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_Movement.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/api/IHUMovementBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/movement/api/impl/HUMovementBL.java

https://github.com/metasfresh/metasfresh/issues/10221

#10221 Allow HU movement from source Warehouse

---

frontend/src/components/table/TableContextMenu.js

https://loom.com/share/201bd068e1944d829fc0a07a2974184d
https://github.com/metasfresh/metasfresh/issues/10230

Dont scroll to the bottom

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5572300_gh10226_ValidationRuleForM_ProductPrice.M_PriceList_Version.sql

https://github.com/metasfresh/metasfresh/issues/10226

Create ValidationRule For M_ProductPrice.M_PriceList_Version

---

backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRBPBankAccountBL.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRImportBL.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRCheckDigitBuilder.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java
backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/model/validator/SEPA_Export_Line.java

More info if ESR-check-digit computation fails for SEPA_Export_Line

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/order/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5572480_sys_gh10242_Add_PrinterParametersToSalesOrderReport.sql

#10242 Report: Quotation: handle PRINTER_OPTS_IsPrintLogo, PRINTER_OPTS_IsPrintTotals parameters

#10242 Report: Quotation: handle PRINTER_OPTS_IsPrintLogo, PRINTER_OPTS_IsPrintTotals parameters 

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShipmentCandidateAPIService.java

also, avoid NPE is streetno is missing

On any RuntimeException flag shipmentCandidate as "error" an move on

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_Process_Trl.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Process_Trl.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IADProcessDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/impl/ADProcessDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/translation/interceptor/AD_Process_Trl.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5566740_sys_gh217SetBaseLanguageAsSystemLanguageToo.sql

https://github.com/metasfresh/metasfresh/issues/10232

Update `AD_Process.Name` when editing `AD_Process_Trl.Name` for base language

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5572540_sys_gh_10226_IncreaseValidationLimit.sql

https://github.com/metasfresh/ic114/issues/927

Change limit for ValidationRule For M_ProductPrice.M_PriceList_Version

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/print/ReportEngine.java

#10254 Fix Manufacturing Order printing

#10254 Fix Manufacturing Order printing

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/geo_location/GeoLocationDocumentService.java

#10252 Mark Country ID as mandatory in the area search filters.

---

backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/DocumentFilterParamDescriptor.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/SqlViewFactory.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDefaultFilterDescriptor.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java

https://github.com/metasfresh/metasfresh/issues/10264

#10264 support for using the login user in default filters

---

e2e/cypress/integration/customer/create_bpartner_api_spec.js

https://www.loom.com/share/9b8fa1241aca4fca8b5038730499a19e

Add test for the attributes dropdown in BP

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5572830_sys_gh10267AddedMovementTypeFilterToProductTransactionsWindow.sql

#10267 Added Movement Type Filter To Product Transactions window

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5572100_sys_gh10219_pimp_CostDetail_window.sql

https://github.com/metasfresh/metasfresh/issues/10219

pimp existing cost detail window

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5572850_sys_10266_ActivateChangeLogs.sql

https://github.com/metasfresh/metasfresh/issues/10266

Activate changelog

---

backend/de.metas.acct.base/src/main/java/de/metas/acct/impexp/GLJournalImportProcess.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_ImpFormat.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_ImpFormat.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/format/ImpFormat.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/format/ImpFormatRepository.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/parser/ImpDataParser.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/parser/ImpDataParserFactory.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/processing/SimpleImportProcessTemplate.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/request/impexp/RequestImportProcess.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/impexp/ADUserImportProcess.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/process/AD_ImpFormat_Row_Create_Based_OnTable.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/DataImportServiceTest.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/ImportFormatBuilder.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/parser/FlexImpDataLineParserTest.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5572860_sys_gh10270_BankStatementImportImprovements.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5572970_sys_gh10270_BankStatementImportImprovements2.sql
backend/de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/I_I_BankStatement.java
backend/de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/X_I_BankStatement.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportProcess.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java
backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/impexp/BankStatementImportProcessTest.java
backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerImportProcess.java
backend/de.metas.business/src/main/java/de/metas/globalid/impexp/BPartnerGlobalIDImportProcess.java
backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcess.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/impexp/FlatrateTermImportProcess.java

https://github.com/metasfresh/metasfresh/issues/10270

Bank Statement Import improvements

---

frontend/src/actions/AppActions.js
frontend/src/components/documentReferences/DocumentReferences.js
frontend/src/components/header/MenuOverlayItem.js
frontend/src/containers/DocumentList.js

https://www.loom.com/share/373d9a4f253f4b21baaeb8ccfdeee80e

Fixes access via dashboard when no view

---

frontend/src/containers/DocumentList.js

Possible fix for fixing the Picking tray
https://www.loom.com/share/50bc628cc8194a3ca198d50193b65471

Prevent multiple re-renderings

---

frontend/src/__tests__/actions/ViewActions.test.js
frontend/src/actions/ViewActions.js

https://www.loom.com/share/41b029126f354c32985d63a661d8bd29

dont trigger the pending

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/document/ICounterDocBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/document/spi/ICounterDocHandler.java
misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/commons/Util.java
misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/ordersimport/AbstractEDIOrdersBean.java
misc/services/camel/de-metas-camel-edi/src/test/java/de/metas/edi/esb/commons/UtilTest.java
misc/services/camel/de-metas-camel-edi/src/test/java/de/metas/edi/esb/commons/Util_createCalendarDate_Test.java

also
* add unit test
* unrelated minor improvements in ICounterDocBL, ICounterDocHandler

make sure that we specify if date-without-time shall be 00:00 or 23:59

---

backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5573130_sys_Router_Attributes.sql

https://github.com/metasfresh/metasfresh/issues/10293

#10293 Router Attributes

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/MPayment.java

https://github.com/metasfresh/bc107/issues/360

Invoice is not ispaid = Y although fully allocated

---

backend/de.metas.business/src/main/java/de/metas/password/PasswordGenerator.java
backend/de.metas.business/src/test/java/de/metas/password/PasswordGeneratorTest.java

https://github.com/metasfresh/metasfresh/issues/10289

Add Password Generator and test

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Evaluatee.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/IDocumentNoBuilder.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/DocumentNoBuilder.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/DocumentNoParts.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573090_sys_gh10282_Add_MAC_Address_Sequence.sql
backend/de.metas.business/src/main/java/de/metas/macaddress/MacAddress.java
backend/de.metas.business/src/main/java/de/metas/macaddress/MacAddressGenerator.java
backend/de.metas.business/src/test/java/de/metas/macaddress/MacAddressGeneratorTest.java
backend/de.metas.util/src/main/java/de/metas/util/StringUtils.java

https://github.com/metasfresh/metasfresh/issues/10282

Manufacturing extension: MAC Address Generator

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573320_sys_gh10307_FixPackingInstrunctionForSalesOrderBatchEntry.sql

https://github.com/metasfresh/sp80/issues/1163

Fix Wrong packing instruction in sales order batch entry

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/CConnection.java

Remove popup about missing app server when starting swing

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportResult.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/DocumentReportService.java
backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java

https://github.com/metasfresh/metasfresh/issues/10318

#10318 Use last archive when no other info for creating the report

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_PP_ComponentGenerator.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_PP_ComponentGenerator_Param.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_PP_ComponentGenerator.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_PP_ComponentGenerator_Param.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/javaclasses/IJavaClassBL.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573260_sys_gh10305_Add_PP_ComponentGenerator.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573350_sys_gh10305_WrongEntityType.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573530_sys_gh10305_Add_PP_ComponentGenerator.AD_Sequence_ID.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573540_sys_gh10305_Add_PP_ComponentGeneratorWindowAndFixes.sql
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/AttributeConstants.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeSet.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/ImmutableAttributeSet.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/IAttributeStorage.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/AbstractAttributeStorage.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/storage/impl/NullAttributeStorage.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorParam.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorParams.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorRepository.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorUtil.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/GeneratedComponentRequest.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/IComponentGenerator.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/MacAddress.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/MacAddressGenerator.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ManufacturingComponentGeneratorService.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/PP_ComponentGenerator.java
backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/PasswordGenerator.java
backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/MacAddressGeneratorTest.java
backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/ManufacturingComponentGeneratorServiceTest.java
backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/PasswordGeneratorTest.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBLTest.java

https://github.com/metasfresh/metasfresh/issues/10305

Add Service for autogenerated Attributes

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573370_sys_gh10316_leadtime_column.sql

https://github.com/metasfresh/metasfresh/issues/10316

creating leadtime column

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/salesrep/DocumentSalesRepDescriptor.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/salesrep/interceptor/C_Order.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java

Propagate the salespartner-ID to the C_Order

---

misc/services/camel/pom.xml

Remove `de-metas-camel-shipping` dependency from `de-metas-camel`

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573720_sys_gh10323AddSysConfigForNewsletterMarketingContactSync.sql
backend/de.metas.marketing/base/src/main/java/de/metas/marketing/base/model/interceptor/AD_User.java

#10323 Creating marketing contact only if sys config is activated when setting user's isnewsletter flag.

---

backend/de.metas.business/src/main/java/de/metas/order/OrderDocumentReportAdvisor.java

https://github.com/metasfresh/metasfresh/issues/10336

#10336 when printing orders, don't display the totals by default

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573550_sys_gh6310_CreateServiceHandlingUnitWindow.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573610_sys_gh6310_UpdateSysConfigForHUEditorViewFactoryLayout.sql
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/ServiceHUEditorViewFactory.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/WEBUI_HU_Constants.java

https://github.com/metasfresh/me03/issues/6257

Create Service Handling Units window

---

backend/de.metas.payment.esr/pom.xml
backend/de.metas.payment.sepa/schema-pain_001_01_03_ch_02/pom.xml
backend/de.metas.payment.sepa/schema-pain_008_003_02/pom.xml
backend/de.metas.printing.common/de.metas.printing.esb.base/pom.xml
misc/services/camel/de-metas-camel-edi/pom.xml

Possible workaround for Intellij IDEA bug https://youtrack.jetbrains.com/issue/IDEA-256661

Add `outputDirectory` configuration to jaxb2

---

backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java

https://github.com/metasfresh/me03/issues/6304
https://github.com/metasfresh/metasfresh/issues/10340

Unlinking Quotation/Order before deleting

---

frontend/src/containers/DocumentList.js

Related to #10276 
https://recordit.co/lGHmwiW19G

Batch together ws events to refresh the data grid

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573890_sys_gh6309_CreateServiceAnnahmeWindow.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573980_sys_gh6309_CreateSubTypeAndMenuForServiceAnnahme.sql

https://github.com/metasfresh/me03/issues/6257
Create new window and menu for "Service Annahme"
Create new document subtype SR

Guarantee/ Service Own Window for Customer returns "Service Annahme"

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573890_sys_gh6309_CreateServiceAnnahmeWindow.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573980_sys_gh6309_CreateSubTypeAndMenuForServiceAnnahme.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574090_sys_gh6309_AddFilterServiceAnnahmeWindow.sql

Filter Window to show only document  with c_doctype.docsubtype = ''SR''

Gh6309 create service Annahme window

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573950_sys_gh10348_AD_Scheduler.FrequencyType_IsNullable.sql
backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_DiscountAllocation_Process.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/payment/process/C_Payment_DiscountAllocation_Process.java

https://github.com/metasfresh/metasfresh/issues/10348

Create Scheduler for minus skonto

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/JsonConverters.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JsonOLCandCreateRequest.java
backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/I_C_OLCand.java
backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCand.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandCreateRequest.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5574060_sys_gh10357_add_M_Warehouse_ID_in_C_OLCand.sql
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/resources/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsServiceTest.snap

https://github.com/metasfresh/metasfresh/issues/10357

gh10357 Add warehouseCode in OLCand

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574210_sys_gh10279UpdateMarketingChannelsUiElementName.sql

#10279 Update marketing channel ad_ui_elements names.

---

frontend/src/__tests__/actions/ViewActions.test.js
frontend/src/actions/ViewActions.js
frontend/src/assets/css/styles.css
frontend/src/components/app/DocumentList.js
frontend/src/containers/DocumentList.js
frontend/src/reducers/viewHandler.js

Related to #10276 . Impact is limited to grid views only and only in reaction to a websocket event, so it's safe to merge anytime.
https://recordit.co/zfdKI8KD3p

Change how full grid refreshes from websockets work

---

frontend/src/__tests__/components/widget/MasterWidget.test.js
frontend/src/components/table/TableCell.js
frontend/src/components/widget/MasterWidget.js

Related to #10363 
Before: https://recordit.co/OBUIdLzpnF
After: https://recordit.co/Dpn9l0JoQS

Don't flash the row as if it updated when navigating around the table

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574220_sys_gh10371AddAttendeesColumnToRequestTable.sql

#10371 Added attendees column to request table.

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_R_Request.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeBL.java
backend/de.metas.business/src/main/java/de/metas/inout/IInOutBL.java
backend/de.metas.business/src/main/java/de/metas/inout/QualityNoteId.java
backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutBL.java
backend/de.metas.business/src/main/java/de/metas/request/api/impl/RequestDAO.java
backend/de.metas.business/src/main/java/de/metas/shipment/model/interceptor/M_InOut.java
backend/de.metas.business/src/test/java/org/adempiere/inout/service/impl/InOutBLTest.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/request/api/IRequestBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/request/api/impl/RequestBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/request/service/async/spi/impl/C_Request_CreateFromInout_Async.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/request/api/impl/RequestBLTest.java

#10377 Request creation from InOut

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrderLine.java

https://github.com/metasfresh/metasfresh/issues/10365

Always update `SalesOrderLine.Price*`

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574440_sys_gh10393AddShowMoreAndLessAdMessages.sql

#10393 Inserted Show More and Show Less Ad_Messages.

---

frontend/src/actions/Actions.js
frontend/src/actions/WindowActions.js
frontend/src/api/window.js
frontend/src/components/Container.js
frontend/src/components/app/Modal.js
frontend/src/components/app/QuickActions.js
frontend/src/components/header/Header.js
frontend/src/components/table/TableFilter.js
frontend/src/components/widget/Lookup/RawLookup.js
frontend/src/components/widget/MasterWidget.js
frontend/src/containers/NavigationTree.js
frontend/src/containers/Table.js
frontend/src/reducers/viewHandler.js
frontend/src/reducers/windowHandler.js

This was breaking the quickactions fetching. Also refactored some functions with multiple params to accept named properties.
Tests will follow soon but preparing the fixtures for the failing cases is a tedious work and we need to start testing this asap.
Related to #10195

Fix setting parent for the included view

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MElementValue.java
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5574380_sys_gh10388_UpdateIndexToConsiderOrg.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5574430_sys_gh10388_SetProperTableAccess.sql

#10388 Element value's org is rest to 0 at each change

#10388 Do not set org to 0

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574360_sys_gh10307_FixPackingInstrunctionForSalesOrderBatchEntry.sql

https://github.com/metasfresh/me03/issues/6313

Update validation rule to display the correct packing items

---

frontend/src/components/notifications/Notification.js

Add the close icon

---

frontend/src/__tests__/actions/WindowActions.test.js
frontend/src/components/table/TableWrapper.js
frontend/src/reducers/windowHandler.js
frontend/test_setup/fixtures/process/actions.json
frontend/test_setup/fixtures/process/parameters.json
frontend/test_setup/fixtures/process/requests.json
frontend/test_setup/fixtures/process/responses.json
frontend/test_setup/fixtures/process/store.json

Related to #10195 . Also changed how deselecting in tables works.
https://recordit.co/JTV08nxVCt

 Tests for quick actions/included views

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInOut.java

Error attaching Sales Order to Customer Return window (#6463)

---

backend/de.metas.adempiere.adempiere/base/src/main/java/org/compiere/model/IQuery.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/InvoiceService.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/JSONInvoiceInfoResponse.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/InvoicesRestControllerImpl.java
backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/invoice/impl/JSONInvoiceInfoResponseTest.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/IInvoicesRestEndpoint.java
backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
backend/de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java
backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxDAO.java
backend/de.metas.util/src/main/java/de/metas/util/lang/Percent.java

https://github.com/metasfresh/metasfresh/issues/10396

REST Endpoint for Invoice data Query by customer

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/process/OrderCreateNewFromProposal.java

https://github.com/metasfresh/me03/issues/6304

Adding filter for process Create new Order from proposal/quotation

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574530_sys_gh10348_AddParam_IsRunByScheduler.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/payment/process/C_Payment_DiscountAllocation_Process.java

https://github.com/metasfresh/metasfresh/issues/10348

Add param IsRunByScheduler

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574250_sys_gh6309CustomizeServiceAnnahmeWindowTabs.sql

https://github.com/metasfresh/me03/issues/6309

Customize Tabs for "Service Annahme" Window

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_R_Request.java
backend/de.metas.business/src/main/java/de/metas/request/api/impl/RequestDAO.java

#10377 Also setting request date

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574170_sys_gh6428_CreateActionForOpenServiceHandlingUnitEditor.sql
backend/metasfresh-webui-api/src/main/java/de/metas/servicerepair/customerreturns/process/CustomerReturns_OpenHUToReturn.java

https://github.com/metasfresh/me03/issues/6428

Action to open the Service HU Editor from Customer Returns window

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HuId.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/ICNetAmtToInvoiceChecker.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/ui/spi/impl/InvoiceCandidatesSelectionSummaryInfo.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/trace/HUTraceSqlConverterDecorator.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/trace/HuTraceQueryCreator.java
misc/services/camel/de-metas-camel-edi/src/test/java/de/metas/edi/esb/commons/UtilTest.java

* clean up javadocs
* add `@Nullable` annotations
* augment&rethrow AdempiereExceptions

misc small fixes; should be fine to integrate

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574290_sys_gh10389_AddAttributeWarrantyStartDateToPackingInstructionVersion.sql

https://github.com/metasfresh/metasfresh/issues/10389

Add `M_HU_PI_Attribute` `WarrantyStartDate`

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/isEUCountry.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5574800_sys_gh10419_AddFunction_isEUCountry.sql

#10419 Create a function that should say if a country in in EU or not

#10419 Add isEUCountry function

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/LeastRecentTransactionStrategy.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/LocatorAndProductStrategy.java

https://github.com/metasfresh/metasfresh/issues/10430

Only create inventory lines for active HUs

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IPPOrderProductAttributeBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/PPOrderProductAttributeBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/IPPOrderReceiptHUProducer.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/AbstractPPOrderReceiptHUProducer.java

https://github.com/metasfresh/metasfresh/issues/10426

Don't generate `SerialNo` attribute for anything except the MainProduct during Manufacturing

---

frontend/src/actions/MenuActions.js
frontend/src/constants/Constants.js

https://www.loom.com/share/e4354a88cbf545a3a46099835a03784d
issue: https://github.com/metasfresh/metasfresh/issues/10450

Increase the no of menu items fetched from the BE

---

frontend/src/components/widget/WidgetRenderer.js

https://www.loom.com/share/994491d29d4f409eb62ee55ea5403af9

Fix calling the onPatch

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Login.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/user/api/impl/UserDAO.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5575190_sys_gh4324_AddErrorMessageDBExceptionOnLogin.sql
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/login/LoginRestController.java

Create error message for LoginInternalError and show it when other then userValidation error happened

(#10457) Prevent weird errors on login

---

frontend/src/actions/InlineTabActions.js
frontend/src/components/widget/InlineTab.js
frontend/src/components/widget/InlineTabWrapper.js
frontend/src/reducers/windowHandler.js

https://www.loom.com/share/395530929041455d9b8d1baf5aa03730

10269 fix issues

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5575340_sys_gh10467_Add_OnlyStockedProductsElementAndUseIt.sql
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUQueryBuilder.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUQueryBuilder.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/LeastRecentTransactionStrategy.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/LocatorAndProductStrategy.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/process/M_Inventory_CreateLines_ForLocatorAndProduct.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/process/M_Inventory_CreateLines_RestrictBy_LocatorsAndValue.java

https://github.com/metasfresh/metasfresh/issues/10467

Add `OnlyStockedProducts` to HU Query Builder and use it for Inventory

---

backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5574590_sys_gh10448_add_missing_trl.sql

https://github.com/metasfresh/metasfresh/issues/10448 fix for de_DE translation

#gh10448 fixed translation

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/PPOrderIssueServiceProductCommand.java

https://github.com/metasfresh/metasfresh/issues/10491

* Update the attribute for the initial HU as well when issuing services

---

frontend/src/__tests__/components/app/Modal.test.js
frontend/src/components/app/Modal.js

Properly run quick actions from the modals

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/557561_sys_gh10302_SerialNo_TransferStrategy_Copy_Virtual_PackingVersion.sql

https://github.com/metasfresh/metasfresh/issues/10302

Let the SerialNo attribute have the transfer strategy = Copy when used in CUs

---

backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorContext.java

https://github.com/metasfresh/metasfresh/issues/10302

Generate Router Password if the attribute value is emtpy

---

backend/de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/X_I_BankStatement.java
backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5575650_sys_gh10497_ImportBankStatement_DebitOrCreditIdentifier_Interchange.sql
backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/impexp/BankStatementImportProcessTest.java

https://github.com/metasfresh/metasfresh/issues/10497

Interchange the DebitOrCreditIdentifier values in the Bank Statement Import

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report_de_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report_de_DE.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report_en_US.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report_summary.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intratrade/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intratrade/report.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intratrade/report_de_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intratrade/report_de_DE.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intratrade/report_en_US.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/hasEUTaxes.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/isEUCountry.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/isEUShippingFromInvoice.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/C_Invoice_V.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/M_InOut_V.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5575670_sys_gh10500_AddFunctionsAndViewsForCreatingIntra_InterCommunityReports.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5575670_sys_gh10500_AddIntracommunityShipmentsRerport.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5575671_sys_gh10500_AddIntratradeReport.sql

#10500 Create report for intratrade and intracomunity

 #10500 Create report for intratrade and intracomunity

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574610_sys_gh6257_AddTrlServiceContract.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574890_gh6257_AddTRLOpenServiceHandlingUnitWindow.sql
backend/metasfresh-webui-api/src/main/java/de/metas/servicerepair/customerreturns/process/CustomerReturns_OpenHUToReturn.java

https://github.com/metasfresh/metasfresh/issues/10415

Gh6257 service handling unit trl

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/AD_User.java

https://github.com/metasfresh/metasfresh/issues/10493

(10493) Clean Title Field When no Title Selected

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Login.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576300_sys_gh6127_AddLoginMsgTrl.sql

Add Trl for message.
https://github.com/metasfresh/mf15/issues/397

(6127)Prevent weird errors on login

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Login.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576060_sys_gh6127_AddLoginMsgTrl.sql

https://github.com/metasfresh/metasfresh/issues/10457
Add Trl for message.

(10457)Prevent weird errors on login

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/M_Cost_CostPrice_Function.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5576430_sys_gh10513_M_Cost_CostPrice_Function_repairments.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5576440_sys_gh10513_Lagerwert(Excel)_Process_Parameters_Default_Repairments.sql

https://github.com/metasfresh/metasfresh/issues/10513

Gh10513 lagerwert excel

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576630_sys_gh10524_CustomizeAuftragsdispositionWindow.sql

https://github.com/metasfresh/metasfresh/issues/10524

(6530) Customize Auftragsdisposition window

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/adempiere/model/I_AD_User.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576670_sys_gh10521_AddAD_User.IsAuthorizedSignatoryColumn.sql

https://github.com/metasfresh/metasfresh/issues/10521

(6452) Add Column AD_USER.IsAuthorizedSignatory

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5576710_sys_gh10531_DateInvoiceFrom_as_default_filter_InvoiceCand.sql

https://github.com/metasfresh/metasfresh/issues/10531

#gh10531 use DateInvoiceFrom as default date filter for Invoice Candidate window

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5576810_sys_gh10536_add_unique_index_on_C_Invoice_Reversal_ID.sql

https://github.com/metasfresh/metasfresh/issues/10536

#10536 add index on C_Invoice.Reversal_ID

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576940_gh10538_Drop_Haddex_Date_And_ControlNo_From_Product.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576950_gh10538_Haddex_Date_And_ControlNo_In_Partner.sql
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java

https://github.com/metasfresh/metasfresh/issues/10538

* Move haddex from product to partner

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576950_gh10538_Haddex_Date_And_ControlNo_In_Partner.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5576951_gh10538_IsHaddexChec_In_Partner_AddColumn.sql

https://github.com/metasfresh/metasfresh/issues/10538

Gh10538 corrections

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/StandardDocumentReportType.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5577180_sys_gh10539_AdPrintFormatForDunning.sql

https://github.com/metasfresh/metasfresh/issues/10539

Gh10539 dunning doc printing

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Invoice_Rejection_Detail.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/interceptor/InvoiceRejectionDetailTest.java

https://github.com/metasfresh/metasfresh/issues/10540

#10540 change c_invoice.isInDispute when updating c_invoice_rejection_detail.isDone

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/MainValidator.java

https://github.com/metasfresh/metasfresh/issues/10540

#gh10540 actually register new interceptor class

---

backend/de.metas.servicerepair.base/src/main/sql/postgresql/system/80-de.metas.servicerepair/5577430_sys_minor_trl.sql
backend/de.metas.servicerepair.webui/src/main/java/de/metas/servicerepair/customerreturns/HUsToReturnViewFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java

https://github.com/metasfresh/metasfresh/issues/10549

Service repair feature 2

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5577440_sys_gh10547_FixBankStatement.sql

https://github.com/metasfresh/metasfresh/issues/10547

#6545 Creating rows in subtab of Bank Statement via import not working

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5577490_sys_gh10556_RemoveProcessC_Payment_CreateFrom_BankStatement.sql

https://github.com/metasfresh/metasfresh/issues/10556

#6815 Remove de.metas.banking.payment.process.C_Payment_CreateFrom_BankStatement

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5577420_sys_gh10555_doc_outbound_mass_pdf_export_process.sql
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/AdArchive.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/IArchiveDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/IArchiveEventManager.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/api/impl/ArchiveEventManager.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/archive/spi/IArchiveEventListener.java
backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/process/MassConcatenateOutboundPdfs.java
backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DocOutboundArchiveEventListener.java
backend/de.metas.util/src/main/java/de/metas/util/FileUtil.java

https://github.com/metasfresh/metasfresh/issues/10555

#10555 added MassConcatenateOutboundPdfs process

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5577620_sys_gh10560_InventoryRevertErrorMessage.sql
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/IHUTransactionBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/impl/HUTransactionBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/interceptor/M_Inventory.java

https://github.com/metasfresh/metasfresh/issues/10560

#6650 Prevent Reverting Inventories if HU was already transformed

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5577780_sys_AD_Workflow_Value_DocumentNo_Name_extend_length.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5577800_sys_C_OrderLine_Detail_trl.sql
backend/de.metas.servicerepair.base/src/main/java-gen/de/metas/servicerepair/repository/model/I_C_Project_Repair_CostCollector.java
backend/de.metas.servicerepair.base/src/main/java-gen/de/metas/servicerepair/repository/model/X_C_Project_Repair_CostCollector.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/model/ServiceRepairProjectCostCollector.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/repository/ServiceRepairProjectCostCollectorRepository.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/repository/requests/CreateProjectCostCollectorRequest.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/ServiceRepairProjectService.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/CreateQuotationFromProjectCommand.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/createQuotationFromProjectCommand/QuotationAggregator.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/createQuotationFromProjectCommand/QuotationLineAggregator.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/createQuotationFromProjectCommand/QuotationLineKey.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/sales_order/RepairSalesOrderService.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/sales_order/interceptor/C_OrderLine.java
backend/de.metas.servicerepair.base/src/main/sql/postgresql/system/80-de.metas.servicerepair/5577720_C_Project_Repair_CostCollector_ASI.sql
backend/de.metas.servicerepair.base/src/main/sql/postgresql/system/80-de.metas.servicerepair/5577760_sys_HUsToIssueView_IssueHUs_Qty_param.sql
backend/de.metas.servicerepair.base/src/main/sql/postgresql/system/80-de.metas.servicerepair/5577770_sys_trls.sql
backend/de.metas.servicerepair.base/src/main/sql/postgresql/system/80-de.metas.servicerepair/5577790_cli_trls.sql
backend/de.metas.servicerepair.webui/src/main/java/de/metas/servicerepair/project/process/HUsToIssueView_IssueHUs.java

https://github.com/metasfresh/metasfresh/issues/10549

Service repair feature 4

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/pricing/SubscriptionPricingRule.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/callout/C_OrderLine.java

https://github.com/metasfresh/metasfresh/issues/10571

#6513 Pricesystem of contract term not considered correctly

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intracommunity/report_summary.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/intratrade/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/IntraTradeShipments.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/C_Invoice_V.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/M_InOut_V.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5577960_sys_gh10568_AddOrgFilter.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5577961_sys_gh10568_AdhustViewsAndFucntionforOrgFilter.sql

#10568 Add Org filter for intratrade and intracommunity reports

#10568 Add Org filter for intratrade and intracommunity reports 

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5577980_sys_gh10573_sales_candidate_increase_product_eff_size.sql

https://github.com/metasfresh/metasfresh/issues/10573

gh10573 - Increase Product eff. size, decrease Replication Transaction size

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5578000_sys_gh_10575_ChangeLiferanteDropDownIntoSearchFiled.sql

https://github.com/metasfresh/metasfresh/issues/10575

#6697 Lookup anstatt Dropdown bei bestellungen aus Auftrag generieren

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/customs/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/inout/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/inout/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5577640_sys_gh10582_AddPrintLogoParameter.sql

#10582 Allow user to choose of shall print logo or not when printing documents

#10582 Add Print logo option to sales and invoice reports

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5578120_sys_gh_105815_PackingMaterialName_Facet_InvoiceCandidate.sql
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/document/filter/provider/standard/FacetsFilterLookupDescriptor.java

https://github.com/metasfresh/metasfresh/issues/10581

Gh10581 packing material facet in invoice candidate

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/label_3_segment.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report_de_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report_de_DE.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report_en_GB.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report_fr_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report_it_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/manufacturingorder/report_label.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/dev.xml

#10591 CU label not available anymore in manufacturing order 

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_CreateFromProposal.java

https://github.com/metasfresh/metasfresh/issues/10589

gh10589 fixed JavaProcess parameter name

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5578340_sys_gh10594_CreateExternalSystemTableAndWindow.sql

https://github.com/metasfresh/metasfresh/issues/10594

#6951 Create an "external system" config table & window

---

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java

https://github.com/metasfresh/metasfresh/issues/10599

Repair bugs in allocation header accounting

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5577600_sys_gh10566_add_printformat_to_requisition_doctype.sql

https://github.com/metasfresh/metasfresh/issues/10566

#gh10566 added ad_printformat_id to Requisition doctype

---

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_AllocationHdr.java

https://github.com/metasfresh/metasfresh/issues/10599

Gh10599 allow zero in allocation posting

---

backend/de.metas.acct.base/src/main/java/de/metas/acct/model/validator/C_ElementValue.java

#10614 Valid combination not created after new element

#10614 Create valid combination for each accounting schema

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BP_Relation.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BP_Relation.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPRelation.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPRelationId.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPRelation.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPartnerDAO_retrieveBPartnerLocationTests.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5575619_sys_re_add_IsRangeFilter_for_now.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5578330_sys_gh10618_add_C_BP_Relation_externalId.sql
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/relation/BPRelationsService.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/relation/BpartnerRelationRestController.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/request/JsonRequestBPRelationTarget.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/request/JsonRequestBPRelationsUpsert.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/response/JsonResponseBPRelationComposite.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/bpartner/response/JsonResponseBPRelationItem.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/common/JsonBPRelationRole.java
backend/de.metas.business.rest-api/src/test/java/de/metas/rest_api/bpartner/request/JsonRequestBPRelationUpsertTest.java
backend/de.metas.business.rest-api/src/test/java/de/metas/rest_api/bpartner/response/JsonResponseBPRelationTest.java
backend/de.metas.business.rest-api/src/test/resources/de/metas/rest_api/bpartner/request/JsonRequestBPRelationUpsertTest.snap
backend/de.metas.business.rest-api/src/test/resources/de/metas/rest_api/bpartner/response/JsonResponseBPRelationTest.snap
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/api/IBPRelationDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/api/impl/BPRelationDAO.java
backend/de.metas.util/src/main/java/de/metas/util/Check.java

https://github.com/metasfresh/metasfresh/issues/10618

#gh10618 added C_BP_Relation endpoints

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/bpartner/api/impl/BPRelationDAO.java

https://github.com/metasfresh/metasfresh/issues/10618

#gh10618 fixed C_BP_Relation lookup logic

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5578950_sys_gh10590_FixBPartnerRelationLocationDisplayField.sql

https://github.com/metasfresh/metasfresh/issues/10590

#6915 Extend BPartner-Relation and add it as BPartner-Tab

---

e2e/cypress/integration/product/change_product_price_spec.js
e2e/package.json

Fixes for the change_product_price spec 
The test is not flaky anymore.
https://dashboard.cypress.io/projects/5yp4q1/runs?branches=%5B%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D

10630 e2e fixes feb

---

misc/services/camel/de-metas-camel-edi/src/test/java/de/metas/edi/esb/remadvimport/ecosio/EcosioRemadvRouteTest.java
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/remadvimport/ecosio/EcosioRemadvTestFile.xml
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/remadvimport/ecosio/JsonCreateREMADVRequest.json
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/remadvimport/ecosio/JsonCreateREMADVResponse.json

remadv route unit test

---

backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5579130_sys_gh10595_RemittanceAdvice_Trl_and_Enhancements.sql

refs: https://github.com/metasfresh/metasfresh/issues/10595

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5579160_sys_gh10642_DefaultValue_In_DD_Order_Processed.sql

https://github.com/metasfresh/metasfresh/issues/10642

Add a default value to DD_Order.Processed

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/inventory/impexp/InventoryImportProcess.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/inventory/impexp/InventoryImportProcessTest.java

https://github.com/metasfresh/metasfresh/issues/10656

inventory import without hu aggregation type : use multiple as default

---

backend/de.metas.printing/de.metas.printing.base/src/main/sql/postgresql/system/80-de.metas.printing/5579420_sys_gh10624_DocOutbound_Print_Process_NameInDE.sql

https://github.com/metasfresh/metasfresh/issues/10624

process name in de_DE (because of the translation problem we have with the processes)

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5579390_sys_gh10661_ProblemCodeDLL.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5579400_sys_gh10661_ProblemCodeList.sql

https://github.com/metasfresh/metasfresh/issues/10661

#6978 Problembereichscode Liste zur Info bereitstellen

---

frontend/src/components/header/Header.js
frontend/src/routes.js

Reset breadcrumbs on logout

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580040_sys_gh6105_CustomizeServiceAnnahmeWindow.sql

https://github.com/metasfresh/metasfresh/issues/10688

#7139 Pimp `Service Annahme` window

---

frontend/.eslintrc
frontend/buildfile.groovy
frontend/package.json

Fix for the builds due to deprecated package https://github.com/metasfresh/me03/issues/7165

Fix builds

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BP_Relation.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPRelation.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580130_sys_gh10693__BPRelation_PayerRole.sql
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/bpartnercomposite/jsonpersister/JsonPersisterService.java
backend/de.metas.externalreference/src/main/java/de/metas/externalreference/rest/ExternalReferenceRestControllerService.java
misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/request/JsonRequestComposite.java
misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bprelation/JsonBPRelationRole.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/alberta/BPartnerUpsertRequestProducer.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/alberta/processor/CreateBPartnerReqProcessor.java

refs: https://github.com/metasfresh/metasfresh/issues/10693

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5580220_sys_gh10670_always_show_dateAcct.sql
backend/de.metas.business/src/main/java/de/metas/invoice/callout/C_Invoice.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/callout/C_Invoice_Candidate.java

https://github.com/metasfresh/metasfresh/issues/10670

#gh10670 always show DateAcct field on UI, and let it be editable. Propagate via callout changes from DateInvoiced to DateAcct

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580350_sys_gh_10661_RenameProblemCodeValues.sql

https://github.com/metasfresh/metasfresh/issues/10661
Fix ProblemCode Elements to be displayed in German

 #6978 Problembereichscode Liste zur Info bereitstellen

---

frontend/src/actions/TableActions.js
frontend/src/containers/DocumentList.js
frontend/src/utils/documentListHelper.js
frontend/src/utils/index.js

Fix duplicated nested rows after updating a value

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580470_sys_gh10648_AddGuaranteeMontsColumn.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580480_sys_gh10648_CreateGuaranteeMonthsField.sql
backend/de.metas.business/src/main/java/de/metas/product/IProductBL.java
backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductBL.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
backend/de.metas.business/src/test/java/de/metas/product/impl/ProductDAOTest.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/expiry/ExpiredAttributeStorageListener.java

https://github.com/metasfresh/metasfresh/issues/10648

#6977 Garantie bei Produkten 

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580710_sys_gh10691_UpdateExternalSystem_Config_PInstance_Log_v.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580720_sys_gh10691_CreateReferenceToLogWiindow.sql

https://github.com/metasfresh/metasfresh/issues/10691
Update View and update the zoom from an external system record to log

Fenster für externe System-Meldungen

---

backend/de.metas.edi/src/main/java/de/metas/edi/process/EDI_DesadvLinePackGenerateCSV_FileForSSCC_Labels.java
backend/de.metas.edi/src/main/java/de/metas/edi/process/EDI_GenerateCSV_FileForSSCC_Labels.java

https://github.com/metasfresh/metasfresh/issues/10714

SSCC können nur einzeln pro Position gedruckt werden

---

frontend/.eslintrc
frontend/src/__tests__/reducers/Tables.test.js
frontend/src/actions/TableActions.js
frontend/src/components/table/Table.js
frontend/src/containers/Table.js
frontend/src/reducers/tables.js
frontend/src/utils/documentListHelper.js
frontend/src/utils/tableHelpers.js

Related to #10715 
Also fixes eslint.

Fix auto-collapsing of updated rows

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580850_sys_gh10736_AddM_Product_DietTypeColumn.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580860_sys_gh10736_AddDietTypeListAndField.sql

https://github.com/metasfresh/metasfresh/issues/10736

#6754 Feld Dropdown Produktfenster Vegan/Vegetarisch"

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLineRow.java

https://github.com/metasfresh/metasfresh/issues/10734

Gh10734 Manufacturing:  Issue/Receipt  improvements

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580920_sys_gh10741_CustomizePaymentSelectionWindow.sql

https://github.com/metasfresh/metasfresh/issues/10741

#7253 Zahlung anweisen - Darstellung

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/GuaranteeMonthsConversionFunction.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580960_sys_gh10648_GuaranteeMonthsConversionFunction.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/productspecifications/report.jrxml

https://github.com/metasfresh/metasfresh/issues/10648

#6977 Garantie bei Produkten

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5580990_sys_gh10718_added_frameAgreement_trl.sql

https://github.com/metasfresh/metasfresh/issues/10718

#gh10718 fixed missing translation

---

misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/excelimport/Excel_OLCand_Row_Builder.java
misc/services/camel/de-metas-camel-edi/src/test/java/de/metas/edi/esb/excelimport/Excel_OLCand_Row_BuilderTest.java

(with unit test)
https://github.com/metasfresh/metasfresh/issues/10754

Avoid returning numbers where the decimal separator is ignored

---

frontend/src/containers/DocumentList.js
frontend/src/reducers/viewHandler.js
frontend/src/utils/documentListHelper.js
frontend/test_setup/fixtures/doclist.json

Fix back button

---

frontend/src/api/index.js
frontend/src/api/login.js
frontend/src/routes.js

https://www.loom.com/share/0638e151837e41efa181a72dc84979e1
Adapt the MF app Frontend to allow also authentication with token

10757 token auth

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/ITaxBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/tax/api/TaxId.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/testsupport/AbstractTestSupport.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/common/JsonPrice.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrderLine.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceLineBL.java
backend/de.metas.business/src/main/java/de/metas/tax/api/ITaxDAO.java
backend/de.metas.business/src/main/java/de/metas/tax/api/impl/TaxBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/invoicecandidate/CommissionShareHandler.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/invoicecandidatehandler/FlatrateTermSubscription_Handler.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateBLTest.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/invoicecandidate/FlatrateTermHandlerTest.java
backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/InvoiceCandidateWriter.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactory.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemsAggregator.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ManualCandidateService.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/form/CreateInvoiceCandidateDialog.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/M_InventoryLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/C_OrderLine_Handler_Test.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/QtyDeliveredFromOrderToInvoiceTest.java

- ITaxBL now returns TaxId instead of int
- avoid NPE in MOrderLine

improvements while checking code to prepare a concept:

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/BpartnerRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/impl/ContactRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner/relation/BpartnerRelationRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner_pricelist/BpartnerPriceListRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/bpartner_product/impl/BpartnerProductRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/data_import/DataImportRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/dataentry/impl/DataEntryRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/externlasystem/ExternalSystemRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoice/impl/SalesInvoicePaymentStatusRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/InvoicesRestControllerImpl.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/SalesOrderRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/OrderCandidatesRestControllerImpl.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/payment/PaymentRestEndpointImpl.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/process/impl/ProcessRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/product/ProductCategoriesRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/product/ProductsRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/receipt/ReceiptRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/remittanceadvice/impl/RemittanceAdviceRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ReceiptCandidatesRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShipmentCandidatesRestController.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/shipping/ShipmentRestController.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/IInvoicesRestEndpoint.java
backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/OrderCandidatesRestEndpoint.java
backend/de.metas.externalreference/src/main/java/de/metas/externalreference/rest/ExternalReferenceRestController.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrderRestController.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/MetasfreshRestAPIConstants.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/security/UserAuthTokenFilter.java
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/HealthcareChInvoice440RestController.java
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/HealthcareChPdfAttachmentController.java
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/RestApiConstants.java

Note: 
* v1 shall remain as it is
* v2-pre shall be renamed to v2 after having finished the changes that are breaking from v1's POV
* after that, v2 shall only be extended with non-breaking changes (i.e. not-mandatory extensions)

introduce app-Server API v1 and v2-pre

---

frontend/src/__tests__/actions/Actions.test.js
frontend/src/actions/Actions.js
frontend/src/containers/DocumentList.js
frontend/test_setup/fixtures/grid/data.json
frontend/test_setup/fixtures/grid/layout.json
frontend/test_setup/fixtures/grid/row_data.json

Handle quickactions requests from websockets with modal correctly

---

frontend/src/__tests__/actions/Actions.test.js
frontend/src/actions/Actions.js
frontend/src/containers/DocumentList.js
frontend/test_setup/fixtures/grid/data.json
frontend/test_setup/fixtures/grid/layout.json
frontend/test_setup/fixtures/grid/row_data.json

Fix fetching quick actions

---

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/GeneralCopyRecordSupport.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MProduct.java
backend/de.metas.business/src/main/java/de/metas/product/ProductPOCopyRecordSupport.java

https://github.com/metasfresh/metasfresh/issues/10789

 #10789 Clone Product with M_Product_Acct records

---

backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5581640_sys_gh10549_CreateService AnnahmeDocType.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5581650_sys_gh10424_service_repair_project_type.sql
backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5581660_cli_gh10446_ServiceReturn_request_type.sql

https://github.com/metasfresh/metasfresh/issues/10790

Bring the service repair scripts to master

---

backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5581670_sys_gh10793_PP_Order_Attribute_OnlyIfInAttributeSet.sql

https://github.com/metasfresh/metasfresh/issues/10793

Display PP_Order attribute only if in attribute set

---

backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5581890_sys_gh10704_Support_Import_with_null_ID.sql

https://github.com/metasfresh/metasfresh/issues/10704

support import with ID null

---

backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5581960_sys_gh10805_Customs_Invoice_PrintFormat.sql

https://github.com/metasfresh/metasfresh/issues/10805

Customs Invoice print format

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
backend/de.metas.vertical.healthcare.alberta/pom.xml
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/I_M_Product_AlbertaArticle.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/I_M_Product_AlbertaBillableTherapy.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/I_M_Product_AlbertaPackagingUnit.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/I_M_Product_AlbertaTherapy.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/X_M_Product_AlbertaArticle.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/X_M_Product_AlbertaBillableTherapy.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/X_M_Product_AlbertaPackagingUnit.java
backend/de.metas.vertical.healthcare.alberta/src/main/java-gen/de/metas/vertical/healthcare/alberta/model/X_M_Product_AlbertaTherapy.java
backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5580600_sys_gh10796-app_alberta_related_m_product_data.sql
backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5582000_sys_gh10808_CustomizeProductWindow.sql
backend/metasfresh-dist/dist/pom.xml
backend/pom.xml

https://github.com/metasfresh/metasfresh/issues/10808

#10808 Additional Tabs To Product Window 

---

backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java

Avoid using Dropship Partner even if is available.

OrderBL: when fetching the Order PricingSystem use the order's BPartner

---

backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5582180_sys_gh108080_AddTrlForProductTabs.sql

add TRL for M_Product_Alberta tabs

#10808 Add Additional Tabs To Product Window

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5582110_sys_gh10811_manufacturing_product_windows.sql
backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/util/lang/All_RepoIdAware_Classes_Test.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderRouting.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderRoutingProduct.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderRoutingProductId.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/CreateOrderRoutingCommand.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderRoutingRepository.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPRouting.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPRoutingProduct.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPRoutingProductId.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPRoutingRepository.java

https://github.com/metasfresh/metasfresh/issues/10811

#gh10811 added logic for pp_wf_node_product to pp_order_node_product creation.

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntrySubTabBindingRepository.java

https://github.com/metasfresh/metasfresh/issues/10832

Avoid assumption on whether data-entry data exists

---

frontend/src/components/widget/CostPrice.js
frontend/src/components/widget/RawWidget.js

Fix focusing CostPrice widget

---

backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/salesrep/interceptor/C_Order.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java

creating sales orders: don't set salesrep if equal to buyer
setting salesrep in orders: don't update C_BPArtner masterdata if salesrep equal to buyer

When creating orders from OLcands and when settings sales rep in order

---

frontend/src/components/header/MenuOverlayContainer.js
frontend/src/containers/NavigationTree.js

https://github.com/metasfresh/metasfresh/issues/10851
Demo on local https://www.loom.com/share/027b8a483de54b26af40b0c91bf42413

Hide the top menu item

---

backend/de.metas.procurement.base/src/main/java/de/metas/procurement/base/order/async/PMM_GenerateOrdersEnqueuer.java
backend/de.metas.procurement.base/src/main/java/de/metas/procurement/base/order/impl/PMMPurchaseCandidateBL.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/procurement/process/PMM_Purchase_Candidate_CreatePurchaseOrder.java

https://github.com/metasfresh/metasfresh/issues/10861

Gh10861 corrections

---

frontend/src/containers/App.js

https://github.com/metasfresh/metasfresh/issues/9845
As suggested by @siemiatj we can comment out that code as it doesnt seem to be in use anywhere. If in the near future we will want the plugins feature to be active we can activate it anytime just by removing the comments.

Comment the plugins activate code

---

frontend/src/actions/FiltersActions.js
frontend/src/actions/TableActions.js
frontend/src/components/filters/Filters.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/filters/InlineFilterItem.js
frontend/src/containers/DocumentList.js
frontend/src/reducers/filters.js
frontend/src/reducers/viewHandler.js
frontend/src/utils/documentListHelper.js
frontend/src/utils/filterHelpers.js
frontend/src/utils/index.js
frontend/test_setup/fixtures/doclist.json

Also pulled some updated code that fixes errors in the console.
Related to #10871

Fix duplicated requests on changing filters

---

frontend/src/containers/DocumentList.js

https://github.com/metasfresh/metasfresh/issues/10864
https://www.loom.com/share/12198f3642984c06b4218d1c42f6d3fa
https://www.loom.com/share/09f5a162464c4b7ea70baa4f65479f51

Fix subsequent filters clearing

---

frontend/src/containers/NavigationTree.js

https://www.loom.com/share/fc8ed9822ae1449a84d99b70d32e3548
Urgent issue

Fix opening processes/actions from sitemap

---

frontend/src/actions/ViewActions.js
frontend/src/utils/filterHelpers.js

Cleanup inline filters more

---

frontend/src/actions/ViewActions.js
frontend/src/components/filters/Filters.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/filters/InlineFilterItem.js
frontend/src/utils/filterHelpers.js

Related to #10871 
Dev test:
https://recordit.co/3QXXxVx8NA

Merge inline filter changes to master

---

backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5583800_sys_gh7556_FixAlbertaTabGridElements.sql

https://github.com/metasfresh/metasfresh/issues/10891

#10891 Order of fields within the Alberta inlineTab element

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfo.java
backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfoColumn.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/impl/NullModelTranslation.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/po/POTrlRepository.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/ILookupDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/service/impl/LookupDAO.java

All POInfos are loading in ~8 seconds (over VPN).
Benefits of this approach: 
Load everything one time at server start (avoid SQL N+1).
That would also validate everything eagerly.

tenacious_d_uat: Improve POInfo loading

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/repository/OrgChangeRepository.java

https://github.com/metasfresh/metasfresh/issues/10700

correction: compare with enddate, not masterEndDate

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeCommand.java

Activate old BPartner https://github.com/metasfresh/metasfresh/issues/10700

---

backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/InvoiceToAllocateQuery.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/PaymentAllocationRepository.java
backend/de.metas.banking/de.metas.banking.base/src/main/sql/postgresql/system/5584480_sys_getopeninvoices.sql
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingFeeComputeRequest.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyService.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceDAO.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceDAO.java
backend/de.metas.business/src/test/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyServiceTest.java
backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java

fix and optimize payment allocation for huge number of invoices

---

misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/processor/GetOrdersProcessor.java

Get BPartners from shopware fix

---

backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_119_v_view.sql
backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5582790_sys_gh10921_cctop_119_v_add_setup_place_no.sql
misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/invoicexport/ecosio/INVOIC.xml
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/invoicexport/ecosio/INVOIC_expected_output.xml

https://github.com/metasfresh/metasfresh/pull/10922

Provide Setup_Place_No in INVOIC-XML

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_DeactivateAfterOrgChange.java

https://github.com/metasfresh/metasfresh/issues/10700

Deactivate BPartners process correction

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_PrintFormat.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_PrintFormat.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/PrintFormat.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/PrintFormatRepository.java
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5584630_sys_gh10924_AddProductPrintFormatTable.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5584710_sys_gh10924_UpdateProcess.sql
backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/AttachmentImageFileClassLoaderHook.java
backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/AttachmentImageFileLoader.java
backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/ImageFileLoader.java
backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperClassLoader.java
backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/OrgLogoLocalFileLoader.java
backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/server/AbstractReportEngine.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_PrintLabel.java

#10924 Implement dynamic product label

#10924 Implement dynamic product label 

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/order/model/I_C_CompensationGroup_Schema.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/de/metas/order/model/X_C_CompensationGroup_Schema.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order_CompensationGroup.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order_CompensationGroup.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5584520_sys_gh10902_C_CompensationGroup_Schema_C_Activity_Column.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5584720_sys_gh10902_C_Order_CompensationGroup_C_Activity_Column.sql
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/Group.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCreateRequest.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupTemplate.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupTemplateRepository.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
backend/de.metas.business/src/main/java/org/adempiere/model/MOrderLinePOCopyRecordSupport.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/invoicecandidate/HandlerTools.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/AbstractFlatrateTermTest.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/ContractsTestBase.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermTestHelper.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/activity/model/validator/C_OrderLine.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/10902
PLEASE, DO NOT INTEGRATE YET!

Propagate activity: C_CompensationGroup_Schema -> C_Orderline and beyond 

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/activity/model/validator/C_OrderLine.java

https://github.com/metasfresh/metasfresh/issues/10902

model interceptor correction

---

frontend/src/components/widget/Checkbox.js

-Add fixes to consider also the defaultValue in the Checkbox widget
-Also add some comments to the functions found in the widget
https://www.loom.com/share/8ad32369d764413995e543636df79203

Add fixes to consider also the defaultValue in the Checkbox widget

---

backend/de.metas.acct.base/src/main/java/de/metas/acct/api/PostingType.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_Fact_Acct.java

7185 fix(gl_journal): PostingType S/Y

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5584850_sys_gh10940_Location_In_BP_Relation_Tab.sql

https://github.com/metasfresh/metasfresh/issues/10940

Add location in BP Relation tab

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/order/CreatePurchaseCandidatesService.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/IPurchaseCandidateBL.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidate.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidateImmutableFields.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/impl/PurchaseCandidateBL.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/material/event/PurchaseCandidateRequestedHandler.java
backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/PurchaseOrderPriceCalculator.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsSaver.java

https://github.com/metasfresh/metasfresh/issues/10841

#gh10841 reworked mechanism to update purchaseCandidate pricing

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5585190_sys_gh10962_added_pp_wf_node_product_specification_column.sql
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Node_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_WF_Node_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Node_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_WF_Node_Product.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/PPOrderRoutingProduct.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/CreateOrderRoutingCommand.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderRoutingRepository.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/PPRoutingProduct.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPRoutingRepository.java

https://github.com/metasfresh/metasfresh/issues/10962

#gh10962 create pp_wf_node_product.specification column

---

frontend/src/assets/css/header.css
frontend/src/assets/css/styles.css
frontend/src/assets/css/variables.css
frontend/src/components/header/MenuOverlay.js
frontend/src/components/header/MenuOverlayContainer.js
frontend/src/containers/NavigationTree.js

Shape the sitemap with nicer boxes.
https://github.com/metasfresh/metasfresh/issues/10912

10912 pimpmenu for sitemap

---

backend/de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/resources/application.properties
backend/de.metas.async/src/main/java/de/metas/async/spi/WorkpackagesOnCommitSchedulerTemplate.java
backend/metasfresh-dist/base/src/main/resources/application.properties
backend/metasfresh-webui-api/src/main/resources/application.properties
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/application.properties

https://github.com/metasfresh/metasfresh/issues/10969

change default actuator EP mapping back to how it was in spring-boot-2

---

frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/Checkbox.js

https://www.loom.com/share/4c9d2bf6abac4575b75af9d93d11debf
https://github.com/metasfresh/metasfresh/issues/10931

10931 filters extra

---

backend/de.metas.adempiere.adempiere/base/pom.xml
backend/de.metas.dimension/src/main/java/de/metas/dimension/DimensionSpec.java
backend/de.metas.material/event/src/main/java/de/metas/material/event/commons/AttributesKey.java
backend/de.metas.ui.web.base/pom.xml
backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/material/cockpit/rowfactory/MaterialCockpitRowFactoryTest.java
backend/pom.xml
misc/parent-pom/pom.xml
misc/services/camel/de-metas-camel-edi/pom.xml
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/pom.xml
misc/services/camel/de-metas-camel-externalsystems/common/pom.xml
misc/services/camel/de-metas-camel-externalsystems/core/pom.xml
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/pom.xml

the older branch being https://github.com/metasfresh/metasfresh/tree/master_fix_old_dependencies

bump up guava version and remove obsolete log4j dependency

---

frontend/src/containers/MasterWindow.js

https://www.loom.com/share/d87541175f34405ca49e2c56272da638

Add catch for the updateTabLayout

---

frontend/src/api/view.js

https://www.loom.com/share/7e7710ea40e04877a2c961f0c208d84c

Fix patch for cases when the response comes as array

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5586210_sys_gh11008_RepairProcessTrls.sql

https://github.com/metasfresh/metasfresh/issues/11008

#11008 Add TRL for the Repair Workflows

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/impl/SyncInventoryQtyToHUsCommand.java

https://github.com/metasfresh/metasfresh/issues/9855

Correction: Mark the HUs to be destroyed after emptied.

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5586630_sys_gh11024_add_EDI_fields_to_Bpartner_window.sql

https://github.com/metasfresh/metasfresh/issues/11024

add EDI fields to bpartner screen

---

backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5586420_sys_gh11016_AlbertaPrescriptionTables.sql
backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5586530_sys_gh11016_AlbertaPrescriptionWindow.sql

https://github.com/metasfresh/metasfresh/issues/11016

#11016 Alberta_PrescriptionRequest Tables and Window

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/ordercandidates/impl/JsonConverters.java
misc/de-metas-common/de-metas-common-ordercandidates/src/main/java/de/metas/common/ordercandidates/v2/request/JsonOrderLineGroup.java

https://github.com/metasfresh/metasfresh/issues/10928

#gh10928 prevent creating olcands with stocked products that are flagged as main product in compensation group

---

frontend/src/components/app/SelectionAttributes.js

Fix wrong prop value for SelectionAttributes

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5586760_sys_gh11028_DefineDefaultInvoiceRuleConfig.sql

https://github.com/metasfresh/metasfresh/issues/11028

#11028 Create default invoiceRule Configuration

---

backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5587010_sys_gh11036_UniqueMyKeyCodeIndex.sql

https://github.com/metasfresh/metasfresh/issues/11036

#11036 Do not allow to create duplicate salespartnercode

---

misc/parent-pom/pom.xml
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/pom.xml
misc/services/camel/de-metas-camel-externalsystems/common/pom.xml
misc/services/camel/de-metas-camel-externalsystems/core/pom.xml
misc/services/camel/de-metas-camel-externalsystems/core/src/main/resources/application.properties
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/pom.xml

* externalsystems-maven: 
* add build-info 
* remove obsolete repackage
* bump up camel to 3.7.3
* externalsystems-camel now has actuator endpoints
* general: bump up commit-id plugin's version

build improvements:

---

frontend/src/__tests__/components/widget/Checkbox.test.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/Checkbox.js
frontend/src/components/widget/WidgetRenderer.js
frontend/src/utils/filterHelpers.js

https://www.loom.com/share/cba4c37f399c461aa22ab8c0f54ca9ce
Fixes the case when defaultValue is false.
https://github.com/metasfresh/metasfresh/issues/10931

Default filters extra fixes

---

frontend/src/actions/WindowActions.js

https://www.loom.com/share/19cdba844c6a48ceb0f288e63aa42575
https://github.com/metasfresh/metasfresh/issues/11050

Prevent recursion in merge

---

frontend/src/components/widget/Checkbox.js

Use updateItems as flag for the case of widget outside the filters.
https://github.com/metasfresh/metasfresh/issues/11049
https://github.com/metasfresh/metasfresh/issues/10931

Fix rendering checkbox val

---

backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_OrderLine.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/ISubscriptionBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/callout/C_OrderLine.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java

https://github.com/metasfresh/metasfresh/issues/10655

#gh10655 use contract term pricesystem if available when calculating Quantity in Price Unit and Line Amount

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5587270_sys_gh11048_AlterTableCTax_add_AD_BoilerPlate_ID.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5587340_sys_gh11048_TaxWindowChanges.sql

https://github.com/metasfresh/metasfresh/issues/11048

#11048 C_Tax window Changes

---

misc/services/procurement-webui/procurement-webui-frontend/src/components/BottomNav.tsx
misc/services/procurement-webui/procurement-webui-frontend/src/components/Header.tsx
misc/services/procurement-webui/procurement-webui-frontend/src/components/Login.tsx
misc/services/procurement-webui/procurement-webui-frontend/src/components/PasswordRecovery.tsx
misc/services/procurement-webui/procurement-webui-frontend/src/components/WeeklyProductList.tsx

https://www.loom.com/share/651279eff88b4111b018f3a07bc926ab
https://github.com/metasfresh/metasfresh/issues/11070
Fixed prettier issues from procurement. How these got in the master branch I dunno. Most probably from a merge from another branch that was not updated.

Fix prettier issues

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputDescriptorFactory.java

https://github.com/metasfresh/metasfresh/issues/11062

#gh11062 prevent error on Forecast window

---

frontend/src/utils/index.js

Related to #11080 
https://recordit.co/nmcPxXXla7

Fix DateRange filter

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5588160_sys_gh11082_BusinessPartnerWeekRevenueReportParams.sql

https://github.com/metasfresh/metasfresh/issues/11082

#11082 Umsatzreport Geschäftspartner Woche

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MImage.java

#11096 Organisation window is not working properly

#11096 Prevent NPE

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/ReturnsServiceFacade.java

https://github.com/metasfresh/metasfresh/issues/11099

#11099 Vendor Returns are not created

---

backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/ProductsWithoutInitialCost.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5588320_sys_gh11094_Products_Winthout_Initial_Cost_Function.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5588330_sys_gh11094_Products_Winthout_Initial_Cost_Process.sql

https://github.com/metasfresh/metasfresh/issues/11094

* Products witohut initial cost

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/label.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/report_lu.jrxml

#11101 Use EAN128/GS1-128 barcode in sscc label

#11101 Use EAN128/GS1-128 barcode in sscc label

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5588850_sys_gh11107_AddPOIncotermColumnToCBpartner.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5588860_sys_gh11107_DisplatPOIncotermFieldVendorTab.sql

https://github.com/metasfresh/metasfresh/issues/11107

#11107 Geschäftspartner: Dropdown Menü für Incoterms

---

backend/de.metas.material/cockpit/src/main/sql/postgresql/ddl/functions/de_metas_material/Retrieve_available_for_Sales.sql
backend/de.metas.material/cockpit/src/main/sql/postgresql/system/75-material-cockpit/5588821_sys_gh11062_retrieve_available_for_sales_fix_logic.sql

https://github.com/metasfresh/metasfresh/issues/11062

#gh11062 changed from JOIN to UNION to prevent cartesian issues

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5589160_sys_gh11119_CreateSalesPriceliste.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5589320_sys_gh11119_CreatePurchasePriceList.sql

https://github.com/metasfresh/metasfresh/issues/11119

#11119 Create Sales/Purchase Price List action

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5589510_sys_gh_11131_Article_Statistics_Excel.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5589520_sys_gh_11131_fresh_product_statistics_non0_report.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/article_statistics/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/fresh_Product_Statistics_Non0_Report.sql

* Article statistics jasper - improvements
https://github.com/metasfresh/metasfresh/issues/11131

* Article statistics excel process

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java

https://github.com/metasfresh/metasfresh/issues/11135

#gh11135 only consider candidates with ProductType=Item when checking if candidates in same aggregation group have been delivered

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/draftlinescreator/InventoryLineAggregatorFactory.java

https://github.com/metasfresh/metasfresh/issues/11137

UOM in inventory line aggregation

---

frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/Amount.js
frontend/src/components/widget/DatetimeRange.js
frontend/src/components/widget/Lookup/Lookup.js
frontend/src/components/widget/Lookup/RawLookup.js
frontend/src/components/widget/WidgetRenderer.js

https://www.loom.com/share/b92b964e361a4d69ab48ad1237d03459
Consider default values for Lookup, Datetimerange and Amount. If others will be needed they will be added in a sep issue.

11139 f default lookup

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/process/C_BPartner_AddRemoveCreditStopStatus.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerStatsDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5589490_sys_gh11129_ModifyAdd_RemoveCreditStopStatusProcess.sql

https://github.com/metasfresh/metasfresh/issues/11129

#11129 Make Add/ Remove Credit Stop Status be available from BPartner window

---

misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/request/JsonRequestContact.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/java/de/metas/camel/externalsystems/alberta/ordercandidate/AlbertaGetOrdersRouteBuilderTests.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/ordercandidate/50_BPartnerUpsertRequest.json

refs: https://github.com/metasfresh/metasfresh/issues/11134

unit test fix

---

frontend/src/assets/css/styles.css
frontend/src/containers/NavigationTree.js

https://www.loom.com/share/06ef4c0bc1ba496e93c5bca40915d45d

Fix sitemap alignment

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/document/counterDoc/C_Order_CounterDocHandler.java

https://github.com/metasfresh/hf134/issues/349

#gh11126 reference counter document in original document

---

backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeOtherAction.java
backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5589980_sys_gh11041_ExternalSystemOther_childConfigParam.sql

refs: https://github.com/metasfresh/metasfresh/issues/11041

Other external system scheduler support

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_OrderLine.java

https://github.com/metasfresh/metasfresh/issues/11144

Manual Discount Flag callout

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/QtyDeliveredFromOrderToInvoiceTest.java

https://github.com/metasfresh/metasfresh/issues/11153

#11153 SetInvoiceCandidateDocTypeId

---

frontend/src/components/hoc/WithRouterAndRef.js
frontend/src/components/table/TableQuickInput.js
frontend/src/components/widget/Lookup/Lookup.js
frontend/src/components/widget/Lookup/RawLookup.js
frontend/src/components/widget/WidgetRenderer.js
frontend/src/containers/WidgetWrapper.js

Change how refs are passed to widgets

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5589950_sys_gh11166_UpdatePaymentWindow.sql

https://github.com/metasfresh/metasfresh/issues/11166

#11166 Display field IsAutoAllocateAvailableAmt in Payment window

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590050_sys_gh_11164_CustomerRetention_Initial_Threshold.sql
backend/de.metas.contracts/src/main/java/de/metas/contracts/IContractsDAO.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/ContractsDAO.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/CustomerRetentionRepository.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/CustomerRetentionRepositoryTest.java

https://github.com/metasfresh/metasfresh/issues/11164

Introduce customer retention initial threshold

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5590040_sys_gh11171_sync_c_bpartner_id.sql

https://github.com/metasfresh/metasfresh/issues/11171

#gh11171 add bpartner_location_warehouse foreign key constraint

---

frontend/src/components/table/TableQuickInput.js
frontend/src/components/widget/RawWidget.js

Allow resetting widget's cachedValue

---

frontend/src/__tests__/components/widget/InlineTab/InlineTab.test.js
frontend/src/__tests__/components/widget/InlineTab/InlineTabWrapper.test.js
frontend/src/components/widget/InlineTab.js
frontend/src/components/widget/InlineTabWrapper.js

https://www.loom.com/share/92848fae790645e6b34daa4a52df3212
https://github.com/metasfresh/metasfresh/issues/11169

Consider allowCreateNew and allowDelete in inlinetabs

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590460_sys_gh11172_WriteOff_In_AllocationLines.sql

https://github.com/metasfresh/metasfresh/issues/11172

Display writeOff in alloc line

---

backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperReportFiller.java

Attempt to save RAM with large reports

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590430_sys_gh11192_CreateGreetingStandardTypeColumn.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590440_sys_gh11192_StartUsingGreetingStandardTypeColumn.sql

https://github.com/metasfresh/metasfresh/issues/11192

#11192 Introduce C_Greeting.GreetingStandardType

---

backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperReportFiller.java

Reverts metasfresh/metasfresh#11199

Revert "Attempt to save RAM with large reports"

---

backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/ModelChangeType.java
backend/de.metas.async/src/main/java/de/metas/async/api/impl/AbstractQueueDAO.java
backend/de.metas.async/src/main/java/de/metas/async/model/validator/Main.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_OrderLine_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_ShipmentSchedule_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefData.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/salesOrder.feature
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleQtysHelper.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/CreateMissingShipmentSchedulesWorkpackageProcessor.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleQtysHelperTest.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater_generate_Test.java

...after a delivery with qtyToDeliverOverride.
Also cleanups.

ShipmentScheduleUpdater: fix bug where qtyToDeliver was wrong..

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/BpartnerRestController.java
backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5590710_sys_gh11051_API_Audit_Adjustments.sql
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/RESTUtil.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV2.feature
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createPurchaseCandidateV2.feature
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/upsertPrices.feature
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/upsertProduct.feature
backend/de.metas.util.web/src/main/java/de/metas/util/web/MetasfreshRestAPIConstants.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ApiAuditService.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ApiRequestReplayService.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/filter/ApiAuditFilter.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/filter/FilterRegistrationConfig.java
misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JsonApiResponse.java
misc/de-metas-common/de-metas-common-rest_api/src/main/test/de/metas/common/rest_api/v2/SerializeDeserializeTest.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/application.properties
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/CamelRouteHelper.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/BPartnerLocationRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/BPartnerRouteBuilderV2.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/ExternalSystemRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/OrderLineCandRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/OrderRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/ProductRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/UnpackV2ResponseRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/resources/application.properties
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/application.properties

refs: https://github.com/metasfresh/metasfresh/issues/11051

activate audit filter for all v2-pre routes + refactoring

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590740_sys_gh_11211_Partner_Windows_Prio.sql

https://github.com/metasfresh/metasfresh/issues/11211

Partner windows prio

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_API_Request_Audit.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_API_Request_Audit.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/request/ApiRequestAudit.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/request/ApiRequestAuditRepository.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/audit/request/ApiRequestAuditRepositoryTest.java
backend/de.metas.adempiere.adempiere/base/src/test/resources/de/metas/audit/request/ApiRequestAuditRepositoryTest.snap
backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5590770_sys_gh11051_API_Audit_UI_tweaks.sql
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ApiAuditService.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/CustomHttpRequestWrapper.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/filter/ApiAuditFilter.java

refs: https://github.com/metasfresh/metasfresh/issues/11051

ignore filter in case content type is not application/json

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590750_sys_gh11208_CreateShopCategoryTable.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590760_sys_gh11208_CreateShopCategoryWindow.sql

https://github.com/metasfresh/metasfresh/issues/11208

#11208 Create Shop Category Table and window

---

frontend/src/components/widget/InlineTabWrapper.js

https://www.loom.com/share/eb1ebc2e5ef44e3aa669185aafac390a

11169 fix new btn

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/fresh_Product_Statistics_Non0_Report.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590850_sys_gh_11131_fresh_product_statistics_non0_report.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590860_sys_gh_11131_Article_Statistics_Excel.sql

https://github.com/metasfresh/metasfresh/issues/11131

Article statistics Excel

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/config/ApiAuditConfig.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/config/ApiAuditConfigRepository.java

refs: https://github.com/metasfresh/metasfresh/issues/11051

match audit config against org.ANY

---

frontend/src/components/board/Card.js
frontend/src/components/board/Lane.js
frontend/src/components/board/Sidenav.js
frontend/src/containers/Board.js

https://github.com/metasfresh/metasfresh/issues/11216
https://www.loom.com/share/65e5f1de9980491fa056c3c7d07aeb0f

11216 cards refresh

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Exclude_FlatrateConditions.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Exclude_FlatrateConditions.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590880_sys_gh_11220_M_Product_Exclude_From_Flatrate_Conditions.sql
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupTemplateRepository.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupCompensationChangesHandler.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_OrderLine.java

https://github.com/metasfresh/metasfresh/issues/11220
Not ready for integration yet

M_Product Excluded from Flatrate Conditions

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5591030_sys_gh11172_WriteOff_In_AllocationLines_TRL.sql

https://github.com/metasfresh/metasfresh/issues/11172

translations

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590910_sys_gh11219_ModifyProductTable.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5590920_sys_gh11219_ModifyProductWindow.sql

https://github.com/metasfresh/metasfresh/issues/11219

#11219 New Shop Columns in M_Product Table

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5591030_sys_gh11172_WriteOff_In_AllocationLines_TRL.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5591040_sys_gh11172_Writeoff_Employee_BankAccount_Parameter.sql
backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentDAO.java
backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/payment/process/C_Payment_Employee_WriteOff.java

https://github.com/metasfresh/metasfresh/issues/11172

Gh11172 corrections 2

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5591460_sys_gh11141_InvoiceVerificationWindowsUpdated.sql

https://github.com/metasfresh/metasfresh/issues/11141

#11141 Create Tables and Windows for invoice QA

---

frontend/src/actions/WindowActions.js
frontend/src/components/app/Modal.js
frontend/src/components/table/Table.js

https://www.loom.com/share/c2d2aee8b3f34874b6d9f9fcc90f4b21

Add websocket connection to the Modal

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Attribute.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Attribute.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5591490_sys_gh11244_Attribute_IsAlwaysUpdatable.sql
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributesBL.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributes.java

https://github.com/metasfresh/metasfresh/issues/11244

Gh11244 Attribute Always Updatable

---

frontend/src/components/widget/RawWidget.js

Don't patch again on blur if widget already patched

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5592110_sys_gh11264_AddIsEUOneStopShopColumn.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5592120_sys_gh11264_UpdateOrganizationWindow.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5592130_sys_gh11264_UpdateTaxRateCategoryName.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5592140_sys_gh11264_AddEUCountryTaxRates.sql

https://github.com/metasfresh/metasfresh/issues/11264
- add column IsEUOneStopShop and display it in Organization window
- Rename Tax Rate Category
- Add Tax Rates for EU countries

#11264 Tax changes

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5592410_sys_gh11268_CreateUserAttributeTable.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5592420_sys_gh11268_UserAttributeListAndTab.sql

https://github.com/metasfresh/metasfresh/issues/11268

#11268 Introduce Contact Attributes

---

frontend/src/assets/css/inputs.css
frontend/src/components/app/Prompt.js

https://www.loom.com/share/08a5a10218354dec8cd6a0ff97704998

11257 alt y

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ShipmentScheduleRepository.java

refs: https://github.com/metasfresh/metasfresh/issues/11262

support warehouse & bpartner override

---

frontend/src/components/table/TableFilter.js

Fix shortcut error

---

frontend/src/components/table/TableFilter.js

Fix regression in shortcuts rendering

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5592550_sys_gh11277_CreateC_BPartnerAttributeTables.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5592560_sys_gh11277_CreateC_BPartnerAttributeRefListAndElements.sql

https://github.com/metasfresh/metasfresh/issues/11277

#11277 Introduce C_BPartner_Attribute2, C_BPartner_Attribute3, C_BPartner_Attribute4, C_BPartner_Attribute5 Tables and Ref Lists

---

backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5592780_sys_gh11240_API_Audit_Folder.sql

refs: https://github.com/metasfresh/metasfresh/issues/11240

api-audit menu Folder

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/storage/impl/HUItemStorage.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/ShipmentSchedule.java

…rage
refs: https://github.com/metasfresh/metasfresh/issues/11240

Support HU_Item_Storage being out of sync with HU_Storage

---

frontend/src/components/widget/BarcodeScanner/BarcodeScanner.js
frontend/src/components/widget/BarcodeScanner/BarcodeScannerWidget.js

Docs for BarcodeScanner

---

frontend/src/assets/css/inputs.css
frontend/src/components/Process.js
frontend/src/components/widget/BarcodeScanner/BarcodeScannerBtn.js
frontend/src/components/widget/BarcodeScanner/BarcodeScannerWidget.js
frontend/src/components/widget/RawWidget.js

related to https://github.com/metasfresh/metasfresh/issues/11281
After the detection the field is populated with the result of the QR_code

ScanBtn on the right to improve UI

---

frontend/src/components/app/Prompt.js

Go to a SO and select some order lines

Just alt+Enter to submit in prompt

---

frontend/src/actions/WindowActions.js

Related to https://github.com/metasfresh/metasfresh/issues/11285

Refresh tab if there's `stale` in ws response

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5592630_sys_gh11282_QuickInputAttributesTables.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5592640_sys_gh11282_DisplayQuickInputAttributes.sql

https://github.com/metasfresh/metasfresh/issues/11282

#11282 Introduce C_BPartner_QuickInput_Attributes, 2, 3, 4, 5 and C_BPartner_Contact_QuickInput_Attributes

---

frontend/src/actions/ViewActions.js

https://www.loom.com/share/cdc42b735f2b403d810b43650d875d21

Remove the action that leads to 404

---

frontend/src/actions/WindowActions.js

Don't reject promise on successfull response

---

frontend/src/components/table/TableQuickInput.js

Fix freezing batch entry

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5593240_sys_gh11316_CreateC_CompensationGroup_Schema_CategoryTable.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5593250_sys_gh11316_CreateCompensationGroup_Schema_CategoryWindow.sql

https://github.com/metasfresh/metasfresh/issues/11316

#11316 Introduce C_CompensationGroup_Schema_Category table

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5592900_sys_gh11292_Missing_Node_From_Workflow_Message.sql
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/interceptor/AD_WF_Node.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/IPPRoutingRepository.java
backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/impl/PPRoutingRepository.java

* Add error message
* set the first node as starting node in workflow
https://github.com/metasfresh/metasfresh/issues/11292

Gh11292 AD_Workflow missing node 

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/isShowESR_QR.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/isShowQRBill.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5593370_sys_gh11322_AddFunction_isShowESR_QR.sql

#11322 ESR is shown although sysconfig de.metas.payment.esr.Enabled is set to N

#11322 Implement showing ESR or not by sys config

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5593600_sys_gh11282_Attribute_Field_Length.sql

https://github.com/metasfresh/metasfresh/issues/11282

Attributes field lengths

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_details_footer.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/taxnote.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/textsnippet.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5593410_sys_gh11324_AddTaxNoteFunctions.sql

#11324 Fetch VAT Notice in Documents from C_Tax

#11324 Implement tax note

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5593980_sys_sysconfig_webui_BPartnerSimpleFuzzySearchFilterProvider_enabled.sql
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/bpartner/filter/BPartnerSimpleFuzzySearchFilterProvider.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterDescriptor.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterParamDescriptor.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/sql/SqlDocumentFilterConverter.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/SqlViewFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewBindingFactory.java
backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/document/filter/sql/SqlDocumentFilterConvertersTest.java

https://github.com/metasfresh/metasfresh/issues/11353

#gh11353: Allow bpartner filter by name, value or city name.

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594250_sys_gh11364_OrderWindowTRLs.sql

https://github.com/metasfresh/metasfresh/issues/11364

#11364 order window: add missing trl in de_DE/de_CH

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocTypeQuery.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/ICompositeQueryFilter.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594670_sys_gh11343_MediatedOrder_Org.sql
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java

refs: https://github.com/metasfresh/metasfresh/issues/11343

fix mediated order org

---

frontend/src/components/widget/Link.js

https://www.loom.com/share/bd724d03e2e540ceb41ce28f95999d95

Extra safety check

---

frontend/src/actions/DashboardActions.js
frontend/src/assets/css/indicator.css
frontend/src/components/charts/Indicator.js
frontend/src/components/charts/RawChart.js
frontend/src/components/dashboard/DraggableWrapper.js

https://www.loom.com/share/4dae8d8d020d453884c174194499591f

11381 details link

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/RV_InvoiceForBPartner.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594790_sys_gh11380_CreateViewRV_InvoiceForBPartner.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594820_sys_gh11380_CreateTableRV_InvoiceForBPartner.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594830_sys_gh11380_CreateInvoiceTabBPartnerWindow.sql

https://github.com/metasfresh/metasfresh/issues/11380

#11380 Create Invoice Subtab in BPartner Window

---

backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceDAO.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLHandlCompleteAndReversalTest.java

https://github.com/metasfresh/metasfresh/issues/11360

#gh11360: prevent credit memo reversal from making the IC invoiceable again

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594950_sys_gh11362_OrgChange_Valrule_Improvement.sql
backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_PostalChange.java

https://github.com/metasfresh/metasfresh/issues/11362

Default Schema Group Category in postal change process

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_de_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_en_GB.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_en_US.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_fr_CH.properties
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_qr.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_Dunning_QR_Code.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5594970_sys_gh11387_Add_Docs_Sales_Dunning_QR_Code.sql

#11387 Implement QR report for dunning

#11387 Implement QR report for dunning 

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/process/impl/ProcessRestController.java
backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5595090_sys_gh11240_add_internal_hostname_sysconfig.sql
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ApiAuditService.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/HttpCallScheduler.java
backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ScheduledRequest.java

See the javadoc at ApiAuditService.executeHttpCall for details
Also rename ScheduleRequest to ScheduledRequest

fix v2 for remote invocations (not via external-systems) on our stack 

---

frontend/src/assets/css/indicator.css
frontend/src/components/charts/Indicator.js
frontend/src/components/charts/RawChart.js

https://github.com/metasfresh/metasfresh/issues/11386
using : https://momentjs.com/docs/#/displaying/fromnow/

time in indicators

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5594980_sys_gh11393_InvoiceVerificationTRLs.sql
backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_Verification_Run_Execute.java

https://github.com/metasfresh/metasfresh/issues/11393

#11393 Rename / change fields in invoice verification windows

---

backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5595170_sys_gh11397_AddRelationDeedToInvoiceCandidate.sql

refs: https://github.com/metasfresh/metasfresh/issues/11397

Relation from commission-deed to invoice-candidate and vice-versa

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595280_sys_gh11316_C_CompensationGroup_Schema_Category_Name_IncreaseSize.sql

https://github.com/metasfresh/metasfresh/issues/11316

Increase the size of c_compensationgroup_schema_category.Name

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_PostalChange.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_ProcessHelper.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/repository/OrgChangeRepository.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeService.java

https://github.com/metasfresh/metasfresh/issues/11362

Only use the default group category if a product exists in the target org

---

backend/de.metas.business/src/main/java/de/metas/banking/Bank.java

https://github.com/metasfresh/metasfresh/issues/11405

#11405 Bank's routingNo shall not be mandatory

---

frontend/src/assets/css/indicator.css
frontend/src/components/charts/Indicator.js
frontend/src/components/charts/RawChart.js

11413 errors rendering

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595860_sys_gh11417_AddR_Request_Direction.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595870_sys_gh11417_RequestWindowChanges.sql

https://github.com/metasfresh/metasfresh/issues/11417

Request Window changes #11417

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeBL.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595970_sys_gh11343_Fixed_Mediated_Order_Translations.sql
backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_Order_ReceiptSchedule.java

Mediated order translation fix

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596030_sys_gh11211_C_BPartner_Window_123_HigherZoomPrio.sql

https://github.com/metasfresh/metasfresh/issues/11211

Gh11211 prio default window

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_RelationType.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_RelationType.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/relation_type/RelationTypeRelatedDocumentsProvidersFactory.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/relation_type/SpecificRelationTypeRelatedDocumentsProvider.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595730_sys_gh11416_Delete_IsDirected.sql

refs: https://github.com/metasfresh/metasfresh/issues/11416

isDirected deleted

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Export.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Export.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/Update_C_BPartner_Export.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/C_BPartner_Export_View.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595830_sys_gh11428_BPartner_Export.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595990_sys_gh11428_BPartner_Export_Process_And_Scheduler.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596000_sys_gh11428_BPartner_Export_View_And_Function.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596040_sys_gh11428_BPartner_Export_RealEstate_Label_And_Filter.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596070_sys_gh11428_BPartner_Export_Update_Process_Linked_To_Table.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596120_sys_gh11428_BPartner_Export_Rebuild_Table.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596270_sys_gh11428_BPartner_Export_Postal_FromAndTo.sql
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/bpartner/filter/BPartnerExportFilterConverter.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/bpartner/filter/BPartnerExportFilterDescriptionProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java

https://github.com/metasfresh/metasfresh/issues/11428

Gh11428 BPartner Export Postal From-To filter

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/functions/Update_C_BPartner_Export.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/C_BPartner_Export_View.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596300_sys_gh11428_BPartner_Export_With_Flatrate_Conditions.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5596310_sys_gh11428_BPartner_Export_Translations.sql

https://github.com/metasfresh/he132/issues/110

Gh11428 bp export with flatrate conditions

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5595770_sys_gh11426_create_M_Product_Relationship_and_M_Product_AttachmentEntry_ReferencedRecord_v.sql
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_AttachmentEntry_ReferencedRecord_v.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_AttachmentEntry_ReferencedRecord_v.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/process/M_Product_AttachmentEntry_ReferencedRecord_v_Download.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/M_Product_AttachmentEntry_ReferencedRecord_v.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595840_ddl_gh11426_create_M_Product_AttachmentEntry_ReferencedRecord_v.sql

https://github.com/metasfresh/metasfresh/issues/11426

#gh11426: created M_Product_Relationship and M_Product_AttachmentEntry_ReferencedRecord_v

---

frontend/src/containers/DocumentList.js

https://www.loom.com/share/711cc5b789204b4dbce397c1daca56f5
If this fix is fine it should be CPed to scary_plum_uat also

Fix triggering spinner logic

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/letter/LetterRestController.java

#11432 Letter creation is not working anymore

#11432 Allow null location

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutPayment.java
backend/de.metas.business/src/main/java/de/metas/allocation/api/impl/AllocationBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceId.java
backend/de.metas.business/src/main/java/de/metas/payment/C_Payment.java
backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentBL.java
backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java
backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5596320_sys_gh11442_PaymentDiscount_Callout_Column_Deleted.sql

refs: https://github.com/metasfresh/metasfresh/issues/11442

Payment Discount not allocated when using Prepay Order fixed

---

frontend/src/containers/DocumentList.js

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

Fix triggering spinner logic (#11446)

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5596730_sys_gh11426_add_SourceTableColumn_for_attachment.sql

https://github.com/metasfresh/metasfresh/issues/11426

#gh11426: added AD_SQLColumn_SourceTableColumn entry

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5597080_sys_gh11428_C_BPartner_ID_FK_DeleteCascade.sql

https://github.com/metasfresh/metasfresh/issues/11428

Repair FK so it allows partners to be deleted

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5597220_sys_gh11426_M_Product_Relationship_rework.sql
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Relationship.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Relationship.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/views/M_Product_AttachmentEntry_ReferencedRecord_v.sql

https://github.com/metasfresh/metasfresh/issues/11426

#gh11426: IT test fixes

---

e2e/cypress.json
e2e/cypress/support/commands/general.js
e2e/cypress/support/index.js
e2e/package.json

https://github.com/metasfresh/metasfresh/issues/11402
-upgraded Cypress
-added loginViaForm command
- other tunning

11402 reshape

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5597010_sys_gh11458_AddIsBranchOfficeColumn.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5597020_sys_gh11458_PartnerRelationWindowDisplayIsBranchOffice.sql

https://github.com/metasfresh/metasfresh/issues/11458

#11458 Create C_BP_Relation.IsBranchOffice and display it in PartnerRelation window

---

backend/de.metas.acct.base/src/main/java/de/metas/acct/model/validator/C_BPartner.java
backend/de.metas.acct.base/src/main/java/de/metas/acct/process/C_AcctSchema_Update_DebtorIdAndCreditorId.java
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5596830_sys_gh11457_bpartner_debtorId_creditorId_update_logic.sql
backend/de.metas.acct.base/src/test/java/de/metas/acct/model/validator/BpartnerValueToDebtorCreditorIds.java
backend/de.metas.acct.base/src/test/java/de/metas/acct/model/validator/C_BPartnerTest.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_AcctSchema.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_AcctSchema.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AcctSchema.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IAcctSchemaBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AcctSchemaBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/AcctSchemaDAO.java
backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/acct/AcctSchemaTestHelper.java

https://github.com/metasfresh/metasfresh/issues/11457

#gh11457 allow updating C_BPartner.debtorId/C_BPartner.creditorId

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/WFDurationUnit.java
backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMConversionBL.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/PP_Order_RecordWork.java
backend/de.metas.util/src/main/java/de/metas/util/Check.java
backend/de.metas.util/src/main/java/de/metas/util/time/DurationUtils.java
backend/de.metas.util/src/test/java/org/adempiere/util/time/DurationUtilsTest.java

https://github.com/metasfresh/metasfresh/issues/11470

#gh11470: added support for converting decimal durations into integer durations of a smaller TemporalUnit

---

backend/de.metas.acct.base/src/main/java/de/metas/elementvalue/ElementValueRepository.java

#11479 Fix process of setting the parent of an account

#11479 Filter out inactive records and context clients

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5597720_sys_gh11436_SupplierApproval_Translations_Part2.sql
backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v1/payment/PaymentRestEndpointTest.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/OrderModuleInterceptor.java
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/order/interceptor/OrderTest.java

https://github.com/metasfresh/metasfresh/issues/11436

Gh11436 translations and order model interceptors

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_InvoiceProcessingServiceCompany_BPartnerAssignment.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_InvoiceProcessingServiceCompany_BPartnerAssignment.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingFeeComputeRequest.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfig.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyConfigRepository.java
backend/de.metas.business/src/main/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyService.java
backend/de.metas.business/src/test/java/de/metas/invoice/invoiceProcessingServiceCompany/InvoiceProcessingServiceCompanyServiceTest.java
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5597550_sys_gh11478_remadv_tweaks.sql
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java
misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/remadvimport/ecosio/EcosioRemadvConstants.java
misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/remadvimport/ecosio/JsonRemittanceAdviceLineProducer.java
misc/services/camel/de-metas-camel-edi/src/test/java/de/metas/edi/esb/remadvimport/ecosio/JsonRemittanceAdviceLineProducerTest.java
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/remadvimport/ecosio/EcosioRemadvTestFile.xml
misc/services/camel/de-metas-camel-edi/src/test/resources/de/metas/edi/esb/remadvimport/ecosio/JsonCreateREMADVRequest.json

refs https://github.com/metasfresh/metasfresh/issues/11478
Note: I have used the abs value for the discount amount. I saw it coming negative and afaik we have it as a positive value always.

REMADV related tweaks

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentCollection.java

https://github.com/metasfresh/metasfresh/issues/11474

#gh11474: unwrap LookupValue if possible when returning its value

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5595820_sys_gh11415_FixServiceDeliveryMenu.sql

https://github.com/metasfresh/metasfresh/issues/11415

#11415 Fix menue tree on releasetestit and instancesuat 

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/CommissionConstants.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionConfigFactory.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/services/CommissionProductService.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/process/FlatrateTermCreator.java
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5597540_sys_gh11488_WithoutCommissionAgreement.sql
backend/de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/interceptor/C_InvoiceFacadeServiceTest.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/services/CommissionConfigFactoryTest.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/commission/commissioninstance/services/repos/CommissionInstanceRepositoryTest.java
backend/de.metas.contracts/src/test/resources/de/metas/contracts/commission/commissioninstance/services/CommissionConfigFactoryTest.snap
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java

refs: https://github.com/metasfresh/metasfresh/issues/11488

Support BPartners without contract in commission deeds

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
backend/de.metas.business/src/main/java/de/metas/bpartner/quick_input/callout/C_BPartner_QuickInput.java

https://github.com/metasfresh/metasfresh/issues/11496

verify role's org access

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/command/GetProductsCommand.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/AttachmentUtil.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/GetAttachmentRouteConstants.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/processor/AttachmentProcessor.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/processor/DocumentProcessor.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/institutions/processor/PrepareInstitutionToBPartnerProcessor.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/java/de/metas/camel/externalsystems/alberta/common/AlbertaUtilTest.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/attachment/100_Attachment_UPSERT_RuntimeParam_Request.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/attachment/10_Document_GET_Response.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/attachment/40_Document_CREATE_Attachment_Request.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/attachment/50_Document_UPSERT_RuntimeParam_Request.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/attachment/90_Attachment_CREATE_Attachment_Request.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/institutions/10_3_UpsertBPartnerMetasfreshRequest_PD.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/institutions/60_3_UpsertBPartnerMetasfreshRequest_PH.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/ordercandidate/50_BPartnerUpsertRequest.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/ordercandidate/70_UpsertRuntimeParamRequest.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/patient/100_UpsertRuntimeParamRequest.json
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/patient/60_UpsertBPartnerMetasfreshRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/GetOrdersProcessor.java

* document-API: 
* query with the last document's updatedAt as opposed to createdAt
* assume the document to be always PDF
* product-API: fix a bug in metasfresh

div. Alberta Tweaks

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingslotsClearing/PackingHUsViewFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingslotsClearing/PackingHUsViewKey.java

https://github.com/metasfresh/metasfresh/issues/11305

fix PackingHUsView filtering

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/dataentry/layout/DataEntryTab.java
backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBL.java
backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchDAO.java
backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchListeners.java
backend/de.metas.async/src/main/java/de/metas/async/api/IQueueDAO.java
backend/de.metas.async/src/main/java/de/metas/async/api/IWorkpackageProcessorContextFactory.java
backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBL.java
backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/DocOutboundProducerService.java
backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/IDocOutboundProducer.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/material/interceptor/transactionevent/HUDescriptorService.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/material/interceptor/transactionevent/HUDescriptorsFromHUAssignmentService.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/material/interceptor/M_Transaction_PostTransactionEvent_HuDescriptorTest.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/material/interceptor/M_Transaction_PostTransactionEvent_InOutLineEventCreatorTest.java
backend/de.metas.marketing/serialletter/src/main/java/de/metas/letter/process/C_Letter_CreateFrom_MKTG_ContactPerson.java
backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/integration/OnePurchase_SeveralReceipts_Test.java
backend/de.metas.material/event/src/main/java/de/metas/material/event/commons/HUDescriptor.java
backend/de.metas.material/event/src/test/java/de/metas/material/event/MaterialEventSerializerTests.java

remove HUDescriptor#quantityDelta, it wasn't user and created confusion

---

backend/de.metas.serviceprovider/src/main/sql/postgresql/system/45-de.metas.serviceprovider/5599060_sys_gh11516_TimeBooking_IsBudgetIssueInvoiced.sql

refs: https://github.com/metasfresh/metasfresh/issues/11516

Budget issue invoiced in time-booking window

---

backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5599090_sys_gh11522_AddNewTherapyAndTherapyTypeValues.sql

https://github.com/metasfresh/metasfresh/issues/11522

#11522 New Values for Alberta Therapy and Alberta Therapy Type

---

backend/de.metas.business/src/main/java/de/metas/payment/api/PaymentQuery.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
backend/de.metas.payment.esr/src/main/java-gen/de/metas/payment/esr/model/X_ESR_ImportLine.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/actionhandler/impl/DuplicatePaymentESRActionHandler.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRImportDAO.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportDAO.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/model/validator/ESR_Main_Validator.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/validationRule/ESRPaymentActionValidationRule.java
backend/de.metas.payment.esr/src/main/sql/postgresql/system/5598870_sys_gh11508_AddDuplicatePaymentAction.sql
backend/de.metas.payment.esr/src/main/sql/postgresql/system/5598871_sys_gh11508_DropPaymentIndex.sql
backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/ESRImportTest.java
backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/ESRTestBase.java
backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/api/impl/ESRImportBLTest.java
backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/validationRule/ESRPaymentActionValidationRuleTest.java

#11508 Implement ESR payment action - duplicate payment

#11508 Implement ESR payment action - duplicate payment

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5599290_sys_gh11530_AddColumnC_async_Batch_IsProcessing.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5599300_sys_gh11530_DisplayeBatch_IsProcessingFlag.sql
backend/de.metas.async/src/main/java-gen/de/metas/async/model/I_C_Async_Batch.java
backend/de.metas.async/src/main/java-gen/de/metas/async/model/X_C_Async_Batch.java

https://github.com/metasfresh/metasfresh/issues/11530

#11530 Add new column C_async_Batch.IsProcessing and display it in the Batch window

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeBL.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5599500_sys_gh11447_ServiceAnnahmeFixReferenceField.sql

r
https://github.com/metasfresh/metasfresh/issues/11447
- make PO Refrence field not read only and not always updatable

#11447 Adding TRLs for Service Annahme and Request window and Change PO Reference in m_inout table to be identifie

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order_CompensationGroup.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order_CompensationGroup.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5599640_sys_C_Order_CompensationGroup_IsNamePrinted.sql
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCreateRequest.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupTemplate.java
backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
backend/de.metas.business/src/main/java/de/metas/product/acct/api/ActivityId.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/createQuotationFromProjectCommand/QuotationAggregator.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/createQuotationFromProjectCommand/RepairedProductAggregator.java

when generating quotation from project:
* generate names for compensation groups (1, 2, 3, etc)
* don't print those names

when generating quotation from project generate names for compensation groups

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Attribute.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/IAttributeDAO.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeDAO.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumnHelper.java

https://github.com/metasfresh/metasfresh/issues/11551

#gh11551 provide column descriptions for class based views

---

frontend/src/__tests__/components/table/TableCellLabel.test.js
frontend/src/__tests__/components/table/TableCellWidget.test.js
frontend/src/assets/css/table.css
frontend/src/components/table/TableCell.js
frontend/src/components/table/TableCellLabel.js
frontend/src/components/table/TableCellWidget.js
frontend/src/components/table/TableRow.js
frontend/src/components/widget/Labels/Label.js

https://www.loom.com/share/9ed8fbbd426e4db994db1ddc6caee459

11369 label in grid

---

frontend/package.json
frontend/src/__tests__/components/widget/List/RawList.test.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/List/RawList.js
frontend/src/components/widget/Lookup/Lookup.js
frontend/src/components/widget/Lookup/RawLookup.js
frontend/src/components/widget/TetheredDateTime.js
frontend/test_setup/jestSetup.js

Update `react-tether` to React 17 compatible

---

frontend/package.json
frontend/src/__tests__/components/widget/List/RawList.test.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/List/RawList.js
frontend/src/components/widget/Lookup/Lookup.js
frontend/src/components/widget/Lookup/RawLookup.js
frontend/src/components/widget/TetheredDateTime.js
frontend/test_setup/jestSetup.js

Reverts metasfresh/metasfresh#11542

Revert "Update `react-tether` to React 17 compatible"

---

frontend/src/components/widget/Checkbox.js

Fix Checkbox outside of filters

---

e2e/cypress/integration/picking/pick_HUs_and_create_shipment.js
e2e/cypress/page_objects/roles.js
e2e/package.json

https://github.com/metasfresh/metasfresh/issues/11556

11556 e2e end of July

---

backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportProcess.java
backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/impexp/BankStatementImportProcessTest.java

https://github.com/metasfresh/metasfresh/issues/11549

#gh11549 fix bank statement lines with TrxAmt=0.00 not being created

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/IHUReceiptScheduleBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleBL.java
backend/de.metas.handlingunits.base/src/main/java/org/adempiere/mm/attributes/spi/impl/AbstractWeightAttributeValueCallout.java
backend/de.metas.handlingunits.base/src/main/java/org/adempiere/mm/attributes/spi/impl/WeightNetAttributeValueCallout.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java

https://github.com/metasfresh/metasfresh/issues/11560

Gh11560 adjust hu storage of planning HUs with the net weight

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformServiceTests.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestinationTestSupport.java

https://github.com/metasfresh/metasfresh/issues/11565

extract CUs directly from LUs

---

frontend/package.json
frontend/src/__tests__/components/widget/List/RawList.test.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/Labels/Labels.js
frontend/src/components/widget/List/RawList.js
frontend/src/components/widget/Lookup/Lookup.js
frontend/src/components/widget/Lookup/RawLookup.js
frontend/src/components/widget/TetheredDateTime.js
frontend/test_setup/jestSetup.js

Second attempt, this time with Labels component also updated.
Related to #11554

Update react-tether to v2

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/BPartnerProductsProposalViewFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/BasePLVProductsProposalViewFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/OtherSalePricesProductsProposalViewFactory.java

https://github.com/metasfresh/metasfresh/issues/11567

#gh11567 set supportOpenValue in BE

---

frontend/src/actions/MenuActions.js
frontend/src/api/app.js
frontend/src/api/index.js
frontend/src/components/header/MenuOverlay.js
frontend/src/components/header/SubHeader.js
frontend/src/containers/NavigationTree.js
frontend/src/routes/PrivateRoute.js

Fix resetting breadcrumbs

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java

https://github.com/metasfresh/metasfresh/issues/11573

#gh11573: don't set a BPlocation that isn't marked as shipToDefault/shipTo

---

backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderRoutingRepository.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order.java

https://github.com/metasfresh/metasfresh/issues/11580

#gh11580 update relevant tabs when manufacturing order's workflow is changed

---

frontend/package.json
frontend/src/__tests__/actions/WindowActions.test.js
frontend/src/__tests__/components/filters/Filters.test.js
frontend/src/__tests__/components/widget/List/RawList.test.js
frontend/src/__tests__/components/widget/SelectionDropdown.test.js
frontend/src/__tests__/reducers/WindowHandler.test.js
frontend/src/actions/WindowActions.js
frontend/src/components/app/DocumentList.js
frontend/src/components/app/LoginForm.js
frontend/src/components/dashboard/DraggableWrapper.js
frontend/src/components/email/NewEmail.js
frontend/src/components/filters/Filters.js
frontend/src/components/filters/FiltersIncluded.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/header/SubHeader.js
frontend/src/components/letter/NewLetter.js
frontend/src/components/widget/List/List.js
frontend/src/components/widget/List/RawList.js
frontend/src/components/widget/MultiSelect.js
frontend/src/components/widget/RawWidget.js
frontend/src/components/widget/SelectionDropdown.js
frontend/src/components/window/Tabs.js
frontend/src/containers/DocumentList.js
frontend/src/reducers/windowHandler.js

Remove immutable.js completely

---

frontend/src/__tests__/components/table/TableCellLabel.test.js
frontend/src/components/table/TableCellLabel.js

Adapts for the case of one label

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5600420_sys_gh11597_RenameMaterialBalanceConfigStandardName.sql

https://github.com/metasfresh/metasfresh/issues/11597

#11597 Gebindesaldo - Improve M_Material_Balance_Config Standard Name

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5600510_sys_gh11600_UpdateBusinessPartnerAccountSheetReport.sql

https://github.com/metasfresh/metasfresh/issues/11600

 #11600 Budget für Mitarbeiter 2

---

frontend/src/utils/filterHelpers.js

Fix the way Labels captions are formed 

---

backend/de.metas.business/src/main/java/de/metas/inout/IInOutDAO.java
backend/de.metas.business/src/main/java/de/metas/inout/impl/InOutDAO.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/ISerialNoBL.java
backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/SerialNoBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUInOutBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutBL.java
backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/customerreturns/RepairCustomerReturnsService.java
backend/de.metas.servicerepair.base/src/main/sql/postgresql/system/80-de.metas.servicerepair/5600160_sys_gh11588_hide_active_hus_in_customer_returns_view.sql
backend/de.metas.servicerepair.webui/src/main/java/de/metas/servicerepair/customerreturns/process/HUsToReturn_SelectHU.java

https://github.com/metasfresh/metasfresh/issues/11588

#gh11588 prevent a HU from being added to the same return request multiple times

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5600610_sys_gh11605_change_M_ProductPrice_useScalePrice_to_List.sql
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_ProductPrice.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_ProductPrice.java
backend/de.metas.business/src/main/java-legacy/org/compiere/process/M_PriceList_Create.java
backend/de.metas.business/src/main/java/de/metas/adempiere/pricing/spi/impl/rules/ProductScalePrice.java
backend/de.metas.business/src/main/java/de/metas/pricing/service/ProductPriceQuery.java
backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/process/CopyPriceToStandard.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/pricing/modelvalidator/M_ProductPrice.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/product/modelvalidator/MProductPriceValidator.java
backend/de.metas.vertical.pharma/src/main/java/de/metas/impexp/product/MProductPriceCloningCommand.java

https://github.com/metasfresh/metasfresh/issues/11605

#gh11605 change M_ProductPrice.UseScalePrice from Y/N to Y/N/S

---

frontend/src/components/header/SubHeader.js

Fix subheader actions

---

e2e/Dockerfile
frontend/src/assets/css/inputs.css
frontend/src/components/widget/List/RawList.js
frontend/src/components/widget/Lookup/Lookup.js

Flag single filed from the composite field when this is mandatory and is invalidated by the backend.
Demo
https://www.loom.com/share/c925c4c674f3415d92b09d3e46c22ef0

11615 fields bpartner status

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUAssignmentBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUAssignmentDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ddorder/api/impl/HUDDOrderBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/document/impl/AbstractHUAllocations.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOutLine.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/InOutProducerFromReceiptScheduleHU.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HUAssignmentBLTest.java

https://github.com/metasfresh/metasfresh/issues/11588

#gh11588 allow deletion on M_InOutLine if assigned M_HU.HUStatus=Planning

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5600350_sys_gh11488_Cleanup_duplicate_zero_commission_contracts.sql

refs: https://github.com/metasfresh/metasfresh/issues/11488

fix duplicate contracts

---

backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5601200_sys_gh11625_add_webui_no_results_found_messages.sql

https://github.com/metasfresh/metasfresh/issues/11625

#gh11625 added No results found message translations to /messages bundle

---

frontend/src/components/widget/List/RawList.js
frontend/src/components/widget/Lookup/RawLookup.js

related to https://github.com/metasfresh/metasfresh/issues/11622

Replace hardcoded strings with corresponding counterparts

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/MBPartnerLocation.java
backend/de.metas.adempiere.adempiere/base/src/test/java/org/compiere/model/MakeUniqueNameCommandTest.java

https://github.com/metasfresh/metasfresh/issues/11631

#gh11631 make bpartner location name unique and based on pattern: City Address1 CompanyName [Address2] [Address3] [Address4] [Country] (2)

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_MembershipMonth.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_MembershipMonth.java
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5601430_sys_gh11643_AddMembershipMonthStrcture.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5601430_sys_gh11643_AddMembershipMonthStructure.sql

#11643 Create a membership month structure

#11643 Create a membership month structure 

---

backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5600530_sys_gh11612_Shopware_GetProducts_Command.sql
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/Shopware6Constants.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/ShopwareClient.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/product/JsonProduct.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/product/JsonProducts.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/product/GetProductsRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/product/ImportProductsRouteContext.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/product/ProductUpsertRequestProducer.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/product/processor/GetProductsProcessor.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/api/model/product/TestPOJOs.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/product/GetProductsRouteBuilderTests.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/product/10_JsonExternalSystemRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/product/20_JsonProducts.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/product/30_CamelUpsertProductRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/product/40_JsonESRuntimeParameterUpsertRequest.json

refs: https://github.com/metasfresh/metasfresh/issues/11612

Process to sync products from shopware to metasfresh

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/productspecifications/report_component.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5602340_sys_gh11636_UpdateProductWindowField.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5602380_sys_gh11636_UpdateProductIngredientsV.sql

https://github.com/metasfresh/metasfresh/issues/11636

#11636 Modification to window Ingredients and Change Product Specification Report 

---

backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/ExternalSystem_Config_StepDef.java
backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config.java
backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemParentConfig.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeExternalSystemProcess.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/rabbitmq/ExternalSystemMessageSender.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/rabbitmq/ExternalSystemQueueConfig.java
backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5593800_sys_gh11341_Drop_ExternalSystem_CamelUrl.sql
backend/de.metas.externalsystem/src/test/java/de/metas/externalsystem/ExternalSystemConfigRepoTest.java
backend/de.metas.externalsystem/src/test/resources/de/metas/externalsystem/ExternalSystemConfigRepoTest.snap
misc/de-metas-common/de-metas-common-externalsystem/src/main/java/de/metas/common/externalsystem/ExternalSystemConstants.java
misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/ProcessLogger.java
misc/services/camel/de-metas-camel-externalsystems/core/pom.xml
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/ProcessLoggerImpl.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/from_mf/CallDispatcherRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/resources/application.properties
misc/services/camel/de-metas-camel-externalsystems/core/src/test/java/de/metas/camel/externalsystems/core/from_mf/CallDispatcherRouteBuilderTest.java

..also log messages
refs: https://github.com/metasfresh/metasfresh/issues/11341
(cherry picked from commit 1bc90019a0d8dfea59942f308122adaf09c93245 && 9a437216b8a1049a3304a21a8cd9457369356bad)

Invoke ExternalSystem via RabbitMQ CP (#11342)

---

frontend/src/components/widget/Labels/Labels.js

https://www.loom.com/share/9ca22c34aa4441628920823d0345132e
rel to -> https://github.com/metasfresh/metasfresh/issues/11674
also related to https://github.com/metasfresh/metasfresh/issues/11675 (fixes that one as well)

Fix the Labels component alignment and cursor position

---

frontend/package.json
frontend/src/components/app/MasterWindow.js
frontend/src/containers/Dashboard.js

rel to https://github.com/metasfresh/metasfresh/issues/11670
- move copy-webpack-plugin to devDependencies
- comment/disable the usage of Hints and Steps
- removed intro.js* deps

11670 disable tutorial

---

frontend/src/__tests__/actions/WindowActions.test.js
frontend/src/actions/WindowActions.js
frontend/src/assets/css/styles.css
frontend/src/components/Container.js
frontend/src/components/app/SpinnerOverlay.js
frontend/src/constants/ActionTypes.js
frontend/src/reducers/windowHandler.js

https://www.loom.com/share/f2a845eecf0d4ba780f65e86340e54b1

Add spinner while adv search data is fetched

---

frontend/src/assets/css/styles.css

rel to https://github.com/metasfresh/metasfresh/issues/11685

Fix - make inputs unavailable while spinner is loading

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5603470_sys_gh11691_MakeReadOnlyInvoiceingBasedOnField.sql

https://github.com/metasfresh/metasfresh/issues/11691

#11691 Make Sales Order Line "Invoicing based on" field Read Only

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5603660_sys_gh11654_AddMIssingTRLFachrichtung.sql

https://github.com/metasfresh/me03/issues/9024

#11654 Create Occupation Hierarchy tables and Validation Rules

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Env.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/LabelsLookup.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceContext.java

https://github.com/metasfresh/metasfresh/issues/11701

gh11701 provide `OrgAccessSql` param if possible

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5603820_sys_gh11709_CostEstimateDocument.sql

https://github.com/metasfresh/metasfresh/issues/11709

#11709 Create Cost Estimate Document Type and Print Format

---

frontend/src/components/widget/DatePicker.js
frontend/src/components/widget/WidgetRenderer.js

https://www.loom.com/share/37cae6ae520e4c408b6e267e40b0d221

11712 filter picking t v2

---

backend/de.metas.edi/src/main/java-gen/de/metas/esb/edi/model/I_EDI_Desadv.java
backend/de.metas.edi/src/main/java-gen/de/metas/esb/edi/model/I_EDI_DesadvLine.java
backend/de.metas.edi/src/main/java-gen/de/metas/esb/edi/model/X_EDI_Desadv.java
backend/de.metas.edi/src/main/java-gen/de/metas/esb/edi/model/X_EDI_DesadvLine.java
backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5603340_sys_gh11713_desadv_add_deliveryViaRule_and_tweak_UI.sql
misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd

forward DeliveryViaRule from C_Order to EDI_Desadv

---

frontend/src/actions/AppActions.js
frontend/src/components/app/LoginForm.js

Run `loginSuccess` on form login

---

backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5589210_sys_gh11134_AD_User_sqlcolumns.sql
backend/de.metas.vertical.healthcare.alberta/src/main/sql/postgresql/system/80-de.metas.vertical.healthcare.alberta/5604450_sys_gh11134_Alberta_Gender.sql

https://github.com/metasfresh/metasfresh/issues/11134

Gh11134 merge correction

---

frontend/src/actions/ViewActions.js

https://www.loom.com/share/ee4033613bea4cfbbc23ffb521d5cd31
Rel to https://github.com/metasfresh/metasfresh/issues/11730

Add caption when rawmodal is open

---

frontend/src/__tests__/components/widget/Checkbox.test.js
frontend/src/components/widget/Checkbox.js
frontend/src/components/widget/WidgetRenderer.js
frontend/src/containers/WidgetWrapper.js
frontend/src/hooks/useAuth.js
frontend/src/hooks/usePrevious.js
frontend/test_setup/fixtures/widget/checkbox.json

Fix checkboxes's communication between the layers

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5604700_sys_gh11734_AddActiveFilterProductPriceWindow.sql

https://github.com/metasfresh/metasfresh/issues/11734

#11734 Add isActive Filter to window Product Price

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5605340_sys_gh11744_AddUniqueIndexForFachrichtungTabels.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5605350_sys_gh11744_FixFachrichtungDuplicates.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5605490_sys_gh11744_AddUniqueIndexForFachrichtungTabels.sql

https://github.com/metasfresh/metasfresh/issues/11744

#11744 Create Unique indexes for Fachrichtung tabels

---

frontend/src/__tests__/components/filters/Filters.test.js
frontend/src/api/view.js
frontend/src/components/filters/Filters.js
frontend/src/utils/filterHelpers.js
frontend/src/utils/index.js

Send defaultValues from filters, SP merge

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5605310_sys_gh11701_add_C_Bpartner_RelatedRecord1.sql
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_EditableAttribute1.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_QuickInput_RelatedRecord1.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_RelatedRecord1.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_EditableAttribute1.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_QuickInput_RelatedRecord1.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_RelatedRecord1.java
backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Env.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/attributes/BPartnerRelatedRecord.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/attributes/BPartnerRelatedRecordId.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/attributes/BPartnerRelatedRecords.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/attributes/related/service/BpartnerRelatedRecordsRepository.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/attributes/related/service/adapter/BPRelatedRecords1Adapter.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/attributes/related/service/adapter/RelatedRecordsAdapter.java
backend/de.metas.business/src/main/java/de/metas/bpartner/quick_input/service/BPartnerQuickInputRelatedRecordsRepository.java
backend/de.metas.business/src/main/java/de/metas/bpartner/quick_input/service/BPartnerQuickInputService.java
backend/de.metas.business/src/main/java/de/metas/bpartner/quick_input/service/attributes_record_adapter/BPQuickInputRelatedRecords1RecordAdapter.java
backend/de.metas.business/src/test/java/de/metas/bpartner/quick_input/service/BPartnerQuickInputServiceUpdateNameAndGreetingTest.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/LabelsLookup.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceContext.java

https://github.com/metasfresh/metasfresh/issues/11701

gh11701 add C_BPartner_RelatedRecord1 table and C_BPartner_EditableAttribute1

---

frontend/src/__tests__/components/filters/Filters.test.js
frontend/src/api/view.js
frontend/src/components/filters/Filters.js
frontend/src/utils/filterHelpers.js
frontend/src/utils/index.js

Related to #11742 
This seems to contradict https://github.com/metasfresh/metasfresh/blob/master/frontend/src/utils/filterHelpers.js#L316 but without sending the defaultValue we're getting incorrect results in data and filters.

Send filter's defaultValue

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5605970_sys_gh11758_AddProcessOfSettinOrderlIne.sql
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
backend/de.metas.manufacturing/src/main/java/org/eevolution/process/PP_Order_SetC_OrderLine.java

#11758 Implement possibility to set sales order line in manufacturing order

#11758 Implement possibility to set sales order line in manufacturing order

---

frontend/src/containers/App.js
frontend/src/hooks/useAuth.js

Unblock the flow when user types token again

---

backend/de.metas.business/src/main/java/de/metas/pricing/IPricingResult.java
backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingResult.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_Flatrate_Conditions.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_SubscrDiscount.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_SubscrDiscount_Line.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Conditions.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_SubscrDiscount.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_SubscrDiscount_Line.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/SubscriptionDiscount.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/SubscriptionDiscountLine.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/SubscriptionDiscountLineId.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/pricing/SubscriptionPricingRule.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/repository/ISubscriptionDiscountRepository.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/repository/SubscriptionDiscountQuery.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/repository/impl/SubscriptionDiscountRepository.java
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5603650_sys_gh11728_subscrdiscount.sql

https://github.com/metasfresh/metasfresh/issues/11728

gh11728 added subscription discount logic

---

backend/de.metas.business/src/main/java/de/metas/banking/BankAccount.java
backend/de.metas.business/src/test/java/de/metas/banking/BankAccountTest.java

https://github.com/metasfresh/metasfresh/issues/11763

remove "/" and what's after it from an ESR account number

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/JsonRetrieverService.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/ordercandidates/impl/MasterdataProvider.java
backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v1/bpartner/BPartnerRecordsUtil.java
backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/v2/bpartner/BPartnerRecordsUtil.java
backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v1/bpartner/BpartnerRestControllerTest.snap
backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v1/bpartner/ContactRestControllerTest.snap
backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v1/bpartner/bpartnercomposite/JsonRetrieverServiceTest.snap
backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/BpartnerRestControllerTest.snap
backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/ContactRestControllerTest.snap
backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/bpartnercomposite/JsonRetrieverServiceTest.snap
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartner.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerContact.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/SalesRep.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositesLoader.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/ChangeLogUtil.java
backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5605910_sys_gh11762_C_BPartner_InternalName_Column.sql
misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/response/JsonResponseBPartner.java
misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/response/JsonResponseContact.java
misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/response/JsonResponseSalesRep.java
misc/de-metas-common/de-metas-common-ordercandidates/src/main/java/de/metas/common/ordercandidates/v2/request/JsonOLCandCreateRequest.java
misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JSONPaymentRule.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/OLCandRequestProcessor.java

refs: https://github.com/metasfresh/metasfresh/issues/11762

Extend v2-BPartner-JSON

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5606140_sys_gh11763_Display_QR_IBAN_In_BankAccount.sql

https://github.com/metasfresh/metasfresh/issues/11763

Gh11763 qr iban

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/CreateSalesOrderFromProposalCommand.java

https://github.com/metasfresh/metasfresh/issues/11780

There's no need to save the new order line here

---

backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java

https://github.com/metasfresh/metasfresh/issues/11778

#11778 Change Delivery Via Rule when Business Partner is changed 

---

backend/de.metas.business/src/main/java/de/metas/payment/api/PaymentQuery.java
backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportDAO.java

https://github.com/metasfresh/metasfresh/issues/11508

Gh11508 use payment date in query

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5606930_sys_gh11803_CreateIncotermTableAndModifyOrderTable.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5606940_sys_gh11803_CreateIcontermElements.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5607250_sys_gh11803_IcontermsInSalesOrderWindow.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5607290_sys_gh11803_MigrateIncoterms.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5607520_sys_gh11803_IncotermWindowData.sql

https://github.com/metasfresh/metasfresh/issues/11803

Gh11803 incoterms tables

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5606720_sys_gh11810_AddSeqNoToDistributionOrderDoc.sql

https://github.com/metasfresh/metasfresh/issues/11810

#11810 Fix Distributionsauftrag document sequence, TRL and actions

---

frontend/src/routes/KeyRoutes.js
frontend/src/utils/index.js

Fix navigation from the header menu

---

frontend/src/api/view.js

Related to https://github.com/metasfresh/metasfresh/issues/11825
https://www.loom.com/share/e216883e62564a489b8a7b9e0b0f1e05

Correct formatting

---

misc/services/mobile-webui/mobile-webui-frontend/src/constants/index.js
misc/services/mobile-webui/mobile-webui-frontend/src/index.js
misc/services/mobile-webui/mobile-webui-frontend/src/serviceWorkerRegistration.js

Unregister service worker based on config

---

frontend/src/components/widget/RawWidget.js

Fix showing password in clear text

---

misc/services/mobile-webui/mobile-webui-frontend/package.json
misc/services/mobile-webui/mobile-webui-frontend/src/index.js

Note: Haven't tested this on Windows. Theoretically it should work without problems

Hash version injection 

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5610770_sys_gh11822_FixBiDirectionalRelationTypes.sql

https://github.com/metasfresh/metasfresh/issues/11822

#11822 Create missing Relation Types

---

frontend/src/components/widget/InlineTabWrapper.js
frontend/src/containers/WidgetWrapper.js

Rel to https://github.com/metasfresh/metasfresh/issues/11931
Demo: https://www.loom.com/share/4884fe908eb444c1863a3e3fbc4cf021

Fix saving address when clicking outside

---

misc/services/mobile-webui/mobile-webui-frontend/src/App.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/actions/ApplicationsActions.js
misc/services/mobile-webui/mobile-webui-frontend/src/actions/RoutingActions.js
misc/services/mobile-webui/mobile-webui-frontend/src/api/confirmation.js
misc/services/mobile-webui/mobile-webui-frontend/src/api/launchers.js
misc/services/mobile-webui/mobile-webui-frontend/src/components/Header.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/WFProcessScreen.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/AbortActivity.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/confirmButton/ConfirmButton.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/applicationScreen/AppCard.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/applicationScreen/ApplicationsScreen.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/wfLaunchersScreen/WFLaunchersScreen.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/reducers/appHandler.js
misc/services/mobile-webui/mobile-webui-frontend/src/reducers/headers.js
misc/services/mobile-webui/mobile-webui-frontend/src/reducers/launchers.js
misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses_status/index.js
misc/services/mobile-webui/mobile-webui-frontend/src/services/navigationMiddleware.js
misc/services/mobile-webui/mobile-webui-frontend/src/utils/translations.js

Modified the ConfirmButton to be more reusable. Also we couldn't confirm the workflow so fixed this as well and fetched the applications on app init.
Had to change target and got tons of conflicts so decided to just create a new PR. Here's the old one:
https://github.com/metasfresh/metasfresh/pull/11889

Abort workflow button with prompt

---

frontend/src/components/table/TableCell.js
frontend/src/components/widget/Attributes/Attributes.js
frontend/src/components/widget/Attributes/AttributesDropdown.js
frontend/src/components/widget/Checkbox.js
frontend/src/components/widget/RawWidget.js
frontend/src/components/widget/WidgetRenderer.js

Related to #11919 and had to pull the changes from #11869

Update Attributes layout on PATCH

---

backend/de.metas.acct.base/src/main/java/de/metas/acct/doc/DocLine_Invoice.java
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5611840_sys_gh11929_M_Product_Acct_Consider_CompensationSchema.sql
backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java

https://github.com/metasfresh/metasfresh/issues/11929

M_Product_Acct_Consider_CompensationSchema

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java

https://github.com/metasfresh/metasfresh/issues/11941

#11941 prefer locations with isShipToDefault/isBillToDefault when defaulting for an order

---

misc/services/mobile-webui/mobile-webui-frontend/src/App.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/components/UpdateCheck.jsx

Rel to https://github.com/metasfresh/metasfresh/issues/11939
no calls to version present anymore

Dont call the version check if there is no service worker registered

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5612550_sys_gh11953_CalculateCustoms_InvoiceLine_BruttoWeight.sql

#11953 Compute properly the gross weight in Customs Invoice

#11953 Compute properly the gross weight in Customs Invoice

---

misc/services/mobile-webui/mobile-webui-frontend/package.json
misc/services/mobile-webui/mobile-webui-frontend/src/index.js

Reverts metasfresh/metasfresh#11912
fails in windows/git shell:
tried to yarn too, same issue.

Revert "Hash version injection "

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_DocType.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_DocType.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5612630_sys_gh11962_Kreditoren_Nachbelastung_DocType.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5612700_sys_gh11962_Kreditoren_Nachbelastung_Process.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5612790_sys_gh11962_Kreditoren_Nachbelastung_RelationTypes.sql
backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AdjustmentChargeCreateRequest.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/outOfStockNotice.feature
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/salesOrder.feature
backend/de.metas.swat/de.metas.swat.base/src/main/java/org/adempiere/invoice/process/C_Invoice_PO_CreateAdjustmentCharge.java

https://github.com/metasfresh/metasfresh/issues/11962

Nachbelastung (Kreditoren)

---

backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_Flatrate_Term.java
backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Term.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5612870_sys_gh11968_StoreInitialFlatrate_term_id.sql
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5612871_sys_gh11968_Set_C_Flatrate_Term_Master_ID.sql
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5612872_sys_gh11968_Make_C_Flatrate_Term_Master_ID_mandatory_And_add_in_window.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/C_OrderLine_ShipmentSchedule.java

#11968 Implement possibility to know easily the first contract from a hierarchy chain

#11968 Implement possibility to know easily the first contract from a hierarchy chain 

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOFromSOsAggregationKeyBuilder.java
backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/48-de.metas.order/5612540_sys_gh11955_attachment_trls.sql
backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/order/createFrom/po_from_so/impl/CreatePOFromSOsAggregationKeyBuilderTest.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/attachmenteditor/OrderAttachmentRow.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/attachmenteditor/OrderAttachmentRows.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/attachmenteditor/OrderAttachmentRowsLoader.java
backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/order/attachmenteditor/OrderAttachmentRowsLoaderTest.java

refs: https://github.com/metasfresh/metasfresh/issues/11955

fixes around attachment modal & "generate PO from SO" process

---

backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5613300_sys_gh11906_Process_C_Order_CreateForAllMembers_TRL.sql

https://github.com/metasfresh/metasfresh/issues/11906

Additional products trl

---

frontend/src/assets/css/inputs.css

Use whole width of the lookup field

---

misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/processor/AttachmentProcessor.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/attachment/processor/GetAttachmentProcessor.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/main/java/de/metas/camel/externalsystems/alberta/common/AlbertaUtil.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/java/de/metas/camel/externalsystems/alberta/common/AlbertaUtilTest.java
misc/services/camel/de-metas-camel-externalsystems/alberta/de-metas-camel-alberta-camelroutes/src/test/resources/de/metas/camel/externalsystems/alberta/attachment/100_Attachment_UPSERT_RuntimeParam_Request.json

...see comment in AttachmentProcessor for details

use the current attachment's uploadDate as API param for the next call

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerBankAccountsSaveRequest.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeRepository.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerContactSaveRequest.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerLocationSaveRequest.java
backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerSaveRequest.java
backend/de.metas.business/src/main/java/de/metas/bpartner/quick_input/service/BPartnerQuickInputService.java
backend/de.metas.business/src/test/java/de/metas/bpartner/composite/repository/BPartnerCompositeRepositoryTest.java
backend/de.metas.business/src/test/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaverTest.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/service/OrgChangeCommand.java

https://github.com/metasfresh/metasfresh/issues/11995

Option to save bpartner composite without validating permissions

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Attribute4.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner_Attribute5.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User_Attribute.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Attribute4.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner_Attribute5.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5613890_sys_gh12000_ExtendAttributesTables.sql

#12000 Extend Bpartner attribute tables

#12000 Add more values and regenerate models

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5614360_sys_gh12007_invoiceLineAllocType.sql
backend/de.metas.contracts/src/main/java/de/metas/contracts/commission/commissioninstance/businesslogic/sales/commissiontrigger/salesinvoiceline/SalesInvoiceFactory.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Line_Alloc.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Line_Alloc.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateAllocCreateRequest.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceLineAllocType.java

https://github.com/metasfresh/metasfresh/issues/12007

Credit memo commission instance

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridTabVO.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/ad_tab_v.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5613540_sys_gh11986_AddIsAutodetectDefaultDateFilter.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5613541_sys_gh11986_AddIsAutodetectDefaultDateFilterInViews.sql
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/accounting/filters/FactAcctFilterDescriptorsProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/bpartner/filter/BPartnerExportFilterDescriptionProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/bpartner/filter/BPartnerSimpleFuzzySearchFilterProvider.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/provider/DocumentFilterDescriptorsProvidersService.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/provider/fullTextSearch/FTSDocumentFilterDescriptorsProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/provider/standard/StandardDocumentFilterDescriptorsProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/provider/userQuery/UserQueryDocumentFilterDescriptorsProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/geo_location/GeoLocationDocumentService.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/picking/packageable/filters/PackageableFilterDescriptorProviderFactory.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/CreateFiltersProviderContext.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/comments/CommentsServiceTest.java
backend/de.metas.ui.web.base/src/test/resources/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoaderTest.snap

#11986 Implement AutodetectDefaultDateFilter

#11986 Implement AutodetectDefaultDateFilter 

---

misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/client/GRSSignumDispatcherRouteBuilder.java

refs  https://github.com/metasfresh/metasfresh/issue)s/11991

auth header fix

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Incoterms.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Invoice.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InOut.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Incoterms.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Invoice.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InOut.java
backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/grid/CreateFromShipment.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5614830_sys_gh12013_Add_C_Incoterms_all_over.sql
backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInOut.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInOut.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/invoicecandidate/HandlerTools.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/ReturnsInOutHeaderFiller.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceHeader.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java

* Add C_incoterm_ID into:
- C_invoice_candidate
- C_Invoice
- M_InOut
* Remove old Incoterms field from app dictionary tables, but not dropping the column yet

#12013 Extend inconterms 

---

misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/common/StepScanScreenComponent.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/manufacturing/PickQuantityButton.jsx
misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses_status/manufacturing.js

https://recordit.co/BtBMu90cAC
Just noticed stupid gif is too short

Calculate activity issue line's quantity on step change

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5615460_sys_gh12051_add_m_product_id_param_to_pp_order_printLabel.sql
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_PrintLabel.java

https://github.com/metasfresh/metasfresh/issues/12051

#gh12051 allow printing for individual HUs of main product

---

misc/services/mobile-webui/mobile-webui-frontend/src/reducers/wfProcesses_status/manufacturing.js

https://recordit.co/1dj31PaA6s

Fix calculating mfg activity status completion

---

misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/manufacturing/MaterialReceiptLineScreen.jsx

Duplicate of https://github.com/metasfresh/metasfresh/pull/12055 because Jenkins

Fix receive quantity

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5616150_C_User_Role_IsCustomUserRestriction.sql

https://github.com/metasfresh/metasfresh/issues/12066

#12066 added C_User_Role.IsCustomUserRestriction and AD_User.IsCustomUserRestriction

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5616300_sys_gh12071_add_RabbitMQ_Sent_message.sql
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/user/role/repository/UserRoleRepository.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/rabbitmqhttp/interceptor/C_User_Assigned_Role.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/rabbitmqhttp/interceptor/C_User_Role.java
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/rabbitmqhttp/process/C_BPartner_SyncTo_RabbitMQ_HTTP.java

https://github.com/metasfresh/metasfresh/issues/12071

#12071 only show C_BPartner_SyncTo_RabbitMQ_HTTP when multi selection or when current record has not been exported yet

---

frontend/src/actions/AppActions.js
frontend/src/constants/ActionTypes.js
frontend/src/containers/MasterWindow.js
frontend/src/index.jsx
frontend/src/reducers/appHandler.js
frontend/src/utils/index.js

Rel to https://github.com/metasfresh/metasfresh/issues/11927
https://www.loom.com/share/cf46b0b58ef04de8851d68352ef0f0ec

Popstate listener to deal with edge cases for the browsers Back button

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionService.java
backend/de.metas.contracts/src/test/java/de/metas/contracts/subscription/impl/SubscriptionCommandTest.java

https://github.com/metasfresh/metasfresh/issues/12084

#12084 invalidate C_SubscriptionProgress cache when pauses are inserted/removed

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup/legacy/report_details.jrxml

#12108 Add m_product_ID to aggregation group for Bestellkontrolle zum Kunden drucken report

#12108 Add product id in the aggregation

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/ProcessHUsAndPickingCandidateCommand.java

https://github.com/metasfresh/metasfresh/issues/12105

fallback on picking candidate HU as picked HU

---

misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/PickQuantityPrompt.jsx

Don't show negative quantities in the prompt

---

frontend/src/utils/index.js

related to : https://github.com/metasfresh/metasfresh/issues/11927
local demo: https://www.loom.com/share/ae2c56edcab04685a639067b4b508c38

Fix the issue with the back and forward button

---

Jenkinsfile
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/impl/PaySelectionBL.java
misc/services/buildfile.groovy
misc/services/procurement-webui/buildfile.groovy

https://github.com/metasfresh/metasfresh/issues/12125

#12125 copy if available C_Invoice.POReference to C_PaySelectionLine.Reference

---

backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5618050_sys_fix_invoice_aggregation.sql
backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5618060_sys_gh12133_invoice_candidate_move_tax_fields.sql

move tax fields

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_ShipmentSchedule.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/impl/HUShipmentScheduleInvalidateBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/segments/ShipmentScheduleSegmentFromHUStorage.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentSchedulePA.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/CreateMissingShipmentSchedulesWorkpackageProcessor.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/async/UpdateInvalidShipmentSchedulesWorkpackageProcessor.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/IShipmentScheduleInvalidateBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/invalidation/impl/ShipmentScheduleInvalidateBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_ShipmentSchedule.java

otherwise it might get allocated too much stock

fix around shipment schedule creation and allocation

---

backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
frontend/src/containers/DocumentList.js
frontend/src/utils/index.js

Deal with the special case of paging where we need to preserve location and be able to use the Back and Fw buttons to go back/fw and access the previous visualised pages
https://www.loom.com/share/bad99eba6dd843d6abf9e6edbd7c99a0
rel to : https://github.com/metasfresh/metasfresh/issues/11927

Deal with the special case of paging where we need to preserve location

---

frontend/src/components/app/LoginForm.js

rel to : https://github.com/metasfresh/metasfresh/issues/12165

history was not retrieved from the props. added fix

---

frontend/src/components/keyshortcuts/GlobalContextShortcuts.js

related to: https://github.com/metasfresh/metasfresh/issues/12168
https://www.loom.com/share/ce68f35298c3431d97a4070eb0b4c3ed

Adjust scroll position according to the position of the carret

---

backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/mediatedCommissionContract.feature
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/tradeMarginCommissionContract.feature

refs https://github.com/metasfresh/metasfresh/pull/12102

fix commission flaky tests

---

frontend/src/components/widget/Lookup/RawLookup.js

Related to: https://github.com/metasfresh/metasfresh/issues/12169

RawLookup typeahead fix, show only the results from the last 

---

frontend/src/components/table/Table.js
frontend/src/constants/Constants.js

rel to : https://github.com/metasfresh/metasfresh/issues/12171
Demo in SO listing - https://www.loom.com/share/29371b9f53674f7c9ecf790d059006fc
Demo in modal - https://www.loom.com/share/197efe65d11f4d4390a4a185e1bde4ad

shift up and down feat

---

backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/grssignum/interceptor/ExternalSystem_Config_GRSSignum.java
backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5619330_sys_gh12195_ExternalSystem_Config_GRSSignum_IsAuto_readOnlyLogic.sql

refs: https://github.com/metasfresh/metasfresh/issues/12195

Tweak Auto-Send Vendors to GRS

---

frontend/src/__tests__/components/filters/Filters.test.js
frontend/src/assets/css/styles.css
frontend/src/components/filters/Filters.js
frontend/src/utils/filterHelpers.js
frontend/test_setup/fixtures/filters.json
frontend/test_setup/fixtures/filters/filtersStoreFacet.json
frontend/test_setup/fixtures/filters/filtersStoreFour.json
frontend/test_setup/fixtures/filters/filtersStoreInline.json
frontend/test_setup/fixtures/filters/filtersStoreThree.json

Properly display custom active filters to the user

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5619740_sys_gh11961_changed_relation_between_c_invoices.sql

https://github.com/metasfresh/metasfresh/issues/11961

#11961 changed relation type for invoices via ref_invoice_id to only consider invoices with opposite SoTrx

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentAssignmentBL.java

refs: https://github.com/metasfresh/metasfresh/issues/12208

Keep locator if it is not afterPicking

---

frontend/src/__tests__/containers/MasterWindow.test.js
frontend/src/actions/InlineTabActions.js
frontend/src/actions/WindowActions.js
frontend/src/api/window.js
frontend/src/components/widget/List/RawList.js
frontend/src/components/window/Tab.js
frontend/src/containers/MasterWindow.js
frontend/src/utils/index.js

Support multiple sorting options in Tabs

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableRow.java

https://github.com/metasfresh/metasfresh/issues/12227

#12227 prevent error in Picking terminal v2

---

frontend/src/__tests__/components/filters/Filters.test.js
frontend/src/components/filters/FiltersItem.js
frontend/src/components/widget/RawWidget.js
frontend/src/utils/widgetHelpers.js

Focus first field in the filters panel

---

backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5619590_sys_gh12207_invoicing_perf_indices.sql
backend/de.metas.marketing/base/src/main/java/de/metas/marketing/base/process/MKTG_ContactPerson_ProcessBase.java

https://github.com/metasfresh/metasfresh/issues/12230

Gh12230 marketing contact persons

---

backend/de.metas.business/src/main/java/de/metas/pricing/IPricingResult.java
backend/de.metas.business/src/main/java/de/metas/pricing/rules/Discount.java
backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingResult.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/pricing/SubscriptionPricingRule.java
backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5619760_sys_gh11728_correct_IfForeignDiscountsExist_labels.sql

https://github.com/metasfresh/metasfresh/issues/11728

#11728 prevent setting discount if one has already been calculated. Reverse labels for IfForeignDiscountsExist values

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_DatevAcctExport.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_DatevAcctExport.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/spreadsheet/process/ExportToSpreadsheetProcess.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5620220_sys_gh12239_Add_Exportdate_Exportby.sql

Add new exportdate and exportby colums in table DatevAcctExport

Gh12239 add exportdate exportby

---

backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/invoicecandidates/request/JsonEnqueueForInvoicingRequest.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/HUShippingFacade.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java

other classes: just minor improvements

HUShippingFacade: avoid packaging-IC to end up in separate invoice

---

e2e/cypress/integration/picking/pick_HUs_and_create_shipment.js
e2e/cypress/support/commands/general.js
e2e/cypress/support/commands/navigation.js

Fixes for some of the tests that are failing. Adapts to the changes done for the quick actions.
Reduced the no of failing tests to only 9.
https://dashboard.cypress.io/projects/5yp4q1/runs/1285/specs
Note: the build has unstable status due to cucumber random fails.

12254 e2e begin jan2022

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveTUsToDirectWarehouse.java

https://github.com/metasfresh/metasfresh/issues/12265

#12265 prevent error when doing Material withdrawal (move). Show original CUs after splitting

---

frontend/src/utils/index.js

do not merge yet (waiting for Daniela to do some tests)
Fix for the case of diff filters applied
https://www.loom.com/share/519d0730acdb4691b4ac94e51a284690
rel to : https://github.com/metasfresh/metasfresh/issues/11927
Note: build is unstable due to cucumber tests that fail.

diff filtered views

---

misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/README.md

refs: https://github.com/metasfresh/metasfresh/issues/11944

Create GRS mapping docu

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621040_sys_gh12296_C_BPartner_OldValue.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621041_sys_gh12296_C_BPartner_ChangeColumnLegths.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621042_sys_gh12296_C_BPartner_CreditorId_DebtorId_TechNote.sql

https://github.com/metasfresh/metasfresh/issues/12296

C_BPartner.OldValue

---

backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5621220_sys_gh12312_BPartnerLookupVia_MetasfreshId_Description.sql
misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/common/JsonMetasfreshId.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/BPartnerUpsertRequestProducer.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/OLCandRequestProcessor.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_Tests.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/GetOrdersRouteBuilder_HappyFlow_withBPartnerLookupVia_metasfreshId.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/01_JsonExternalSystemShopware6ConfigMappings.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/50_CamelUpsertBPartnerCompositeRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/50_CamelUpsertBPartnerCompositeResponse.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/60_JsonOLCandCreateBulkRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_bPartnerLookupVia_metasfreshId/63_JsonOrderPaymentCreateRequest.json

refs: https://github.com/metasfresh/metasfresh/issues/12312

shopware - Lookup contact of B2B customer

---

frontend/src/components/header/BookmarkButton.js
frontend/src/components/header/MenuOverlayItem.js

Add to main menu as well the icons

---

backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBuilder.java
backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBuilder.java
backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/ConcatenatePDFsCommand.java
backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/PrintingQueueQueryRequest.java
backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Invoice_Candidate_EnqueueSelectionForInvoicingAndPDFConcatenating.java

#12307 Use org parameter when invoicing automatically

#12307 Use org parameter when invoicing automatically 

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/ShipmentCandidateAPIService.java
backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5621350_sys_gh12329_OxidUserId_sysconfig.sql
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandDAO.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java

refs: https://github.com/metasfresh/metasfresh/issues/12329

ShipmentCandidateAPIService switch between Shopware and Oxid

---

backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/ordercandidates/impl/JsonConverters.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandCreateRequest.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
misc/de-metas-common/de-metas-common-ordercandidates/src/main/java/de/metas/common/ordercandidates/v2/request/JsonOLCandCreateRequest.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/ImportOrdersRouteContext.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/BPartnerUpsertRequestProducer.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/CreateBPartnerUpsertReqProcessor.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/OLCandRequestProcessor.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/50_CamelUpsertBPartnerCompositeRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/60_JsonOLCandCreateBulkRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_zeroTax/50_CamelUpsertBPartnerCompositeRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_zeroTax/60_JsonOLCandCreateBulkRequest.json

refs: https://github.com/metasfresh/metasfresh/issues/12314

send extended bpartnerName to /orders/sales/candidates

---

backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5619720_sys_gh12218_ShopwareTrls.sql
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/README.md

refs: https://github.com/metasfresh/metasfresh/issues/12218

de-metas-camel-shopware6/README.md and trls

---

frontend/src/components/widget/CostPrice.js

rel to: https://github.com/metasfresh/metasfresh/issues/12337
within the table:
In document view:

Use the same conv function as on the table

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/spreadsheet/csv/CSVWriter.java

https://github.com/metasfresh/metasfresh/issues/12334

Make sure UTF-8 bom is enforced in csvs

---

frontend/src/assets/css/inputs.css

related to: 
https://github.com/metasfresh/metasfresh/issues/12325
resizing demo:
https://www.loom.com/share/91b8a282321d420b8cacc26153ac7c4c

12325 fix widgets right icon

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621820_sys_gh12296_C_BPartner_OldValue_Vendor_And_Customer.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5621870_sys_gh12296_C_BPartner_Incoterms_Vendor_And_Customer.sql

https://github.com/metasfresh/metasfresh/issues/12296

incoterms and old_value for customer and vendor

---

frontend/src/components/table/TableRow.js
frontend/src/components/window/Column.js

rel to: https://github.com/metasfresh/metasfresh/issues/12351
https://www.loom.com/share/36b89aef4d7b41a2bc45f03c614bedd5

Add truly unique key for the cells

---

frontend/src/assets/css/attachments.css
frontend/src/components/documentReferences/DocumentReferences.js
frontend/src/components/header/Attachments.js

rel to: https://github.com/metasfresh/metasfresh/issues/12357

12357 loading gear side

---

frontend/src/containers/App.js
frontend/src/hooks/useAuth.js
frontend/src/routes/TokenRoute.js

Related to #12347 
Too long for a gif unfortunately https://recordit.co/JwHs8Jkd2z

Fix authentication with token

---

frontend/src/__tests__/actions/TablesActions.test.js
frontend/src/actions/TableActions.js
frontend/src/actions/WindowActions.js
frontend/src/assets/css/table.css
frontend/src/components/table/Table.js
frontend/src/components/table/TableWrapper.js
frontend/src/containers/Table.js
frontend/src/reducers/tables.js

rel to: https://github.com/metasfresh/metasfresh/issues/12349
Demo
https://www.loom.com/share/29b44c6b70d74a82bb2cc8b4171a5901
Done with Slow 3G network throttling (visible starting from 2:42 min)

webui frontend: render loading indicator while included tab data is loading

---

frontend/src/__tests__/actions/TablesActions.test.js
frontend/src/actions/TableActions.js
frontend/src/actions/WindowActions.js
frontend/src/assets/css/table.css
frontend/src/components/table/Table.js
frontend/src/components/table/TableWrapper.js
frontend/src/containers/Table.js
frontend/src/reducers/tables.js

Reverts metasfresh/metasfresh#12350

Revert "webui frontend: render loading indicator while included tab data is loading"

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5622910_sys_gh11961_combine_PO-SO_and_SO-PO_relations.sql

https://github.com/metasfresh/metasfresh/issues/11961

#11961 combine PO->SO, as well as SO->PO relations.

---

frontend/src/assets/css/indicator.css
frontend/src/assets/css/styles.css

rel to: https://github.com/metasfresh/mf15/issues/1334

Auto height for dashboard kpi

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5623160_sys_gh12410_add_docNo_sequence_for_Eingangsrechnung.sql

https://github.com/metasfresh/metasfresh/issues/12410

#12410 add document number for DocType=Eingangsrechnung

---

frontend/src/__tests__/actions/TablesActions.test.js
frontend/src/actions/TableActions.js
frontend/src/actions/WindowActions.js
frontend/src/assets/css/table.css
frontend/src/components/table/Table.js
frontend/src/components/table/TableFilter.js
frontend/src/components/table/TableWrapper.js
frontend/src/containers/Table.js
frontend/src/reducers/tables.js

rel to: https://github.com/metasfresh/metasfresh/issues/12349

12349 handle404new

---

frontend/src/assets/css/attachments.css

rel to: https://github.com/metasfresh/metasfresh/issues/12363
https://www.loom.com/share/6ece43b4ebef425fb6f8104a9a30fc64

Harmonize alignment also for attachments and refs

---

backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/salesOrder.feature
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/process/C_Order_CreatePOFromSOs.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/ui/web/order/BOMExploderCommand.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/ui/web/order/OrderLineCandidate.java
backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/45-de.metas.ordercandidate/5623150_sys_gh12318_add_error_message.sql
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/12318

#12318 group same products from different sub-BOMs into a single OrderLine when exploded

---

misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/JsonError.java
misc/services/camel/de-metas-camel-externalsystems/common/pom.xml
misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/ExternalSystemCamelConstants.java
misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/error/ErrorProcessor.java
misc/services/camel/de-metas-camel-externalsystems/common/src/test/java/de/metas/camel/externalsystems/common/error/ErrorProcessorTest.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/ErrorReportRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/restapi/GRSRestAPIRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/vendor/PushBPartnerRouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/pom.xml

refs: https://github.com/metasfresh/metasfresh/issues/12422

externalsystems https EP shall provide better Error-infos

---

backend/de.metas.async/src/main/java/de/metas/async/asyncbatchmilestone/AsyncBatchMilestoneObserver.java
backend/de.metas.async/src/main/java/de/metas/async/asyncbatchmilestone/AsyncBatchMilestoneService.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_CreditLimit_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_Stats_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_ShipmentSchedule_QtyPicked_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefConstants.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/ShipmentRestController_StepDef.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/creditLimit.feature
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleAllocDAO.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleAllocDAO.java

refs: https://github.com/metasfresh/metasfresh/issues/12364

Failed shipment via API creates inconsistent state

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5623220_sys_gh12414_Add_DatevAccounting_Type_ProvisionStorno.sql

https://github.com/metasfresh/metasfresh/issues/12414

Datev Export Type Provision Storno

---

frontend/src/components/table/TableWrapper.js

Don't close included tab on scrollbar click

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
backend/de.metas.business/src/main/java/de/metas/order/IOrderLineBL.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
backend/de.metas.business/src/main/java/de/metas/order/impl/OrderLineBL.java
backend/de.metas.business/src/main/java/de/metas/order/location/adapter/OrderLineMainLocationAdapter.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/InfrastructureSupport.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/RunCucumberTest.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_OrderLine_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableUtil.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_ShipmentSchedule_StepDef.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/salesOrder.feature
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5623180_sys_gh12405_AllowDifferentPartners.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_OrderLine.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOFromSOsAggregator.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/createFrom/po_from_so/impl/CreatePOLineFromSOLinesAggregator.java

#12409 Copy shipto partner and address for SO order line to PO orderline

#12409 Copy shipto partner and address for SO order line to PO orderline 

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Bank.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_DataImport.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Bank.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_DataImport.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5623610_sys_gh12372_DataImport_Per_Bank.sql
backend/de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/I_I_BankStatement.java
backend/de.metas.banking/de.metas.banking.base/src/main/java-gen/org/compiere/model/X_I_BankStatement.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportProcess.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/model/validator/C_Bank.java
backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/process/C_BankStatement_ImportAttachment.java
backend/de.metas.business/src/main/java/de/metas/banking/Bank.java
backend/de.metas.business/src/main/java/de/metas/banking/BankCreateRequest.java
backend/de.metas.business/src/main/java/de/metas/banking/api/BankAccountService.java
backend/de.metas.business/src/main/java/de/metas/banking/api/BankRepository.java
backend/de.metas.business/src/main/java/de/metas/banking/api/impl/BPBankAccountDAO.java

https://github.com/metasfresh/metasfresh/issues/12372

Data Import Per Bank

---

backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/Invoice450FromCrossVersionModelTool.java
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/test/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/Invoice450RequestConversionServiceTest.java
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/test/resources/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_450/Invoice450RequestConversionServiceTest.snap
backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_450_request/src/test/resources/public_examples/Abrechnung Praktischer Arzt TARMED 450_noEsrBank.xml

https://github.com/metasfresh/metasfresh/issues/12185

#12185 only convert Esr9 to EsrQR if a bank is defined

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateRepository.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidatesQuery.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotViewRepository.java

…already fetched picking slots

PickingCandidateRepository: load only the picking candidates for our already fetched picking slots

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/picking/pickingslot/PickingHURowsRepository.java

PickingCandidateRepository: don't load HU attributes because they are not needed anyways

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5623160_sys_gh12410_add_docNo_sequence_for_Eingangsrechnung.sql

https://github.com/metasfresh/metasfresh/issues/12410

#12410 replace locally generated ID with idserver generated IDs

---

backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_HU_PackingMaterial_StepDef.java
backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_PackingMaterial.java
backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU_PackingMaterial.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HuPackingMaterial.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HuPackingMaterialId.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/HuInOutInvoiceCandidateVetoer.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/HuPackingMaterialQuery.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUPackingMaterialDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUPackingMaterialDAO.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/Main.java
backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5624040_sys_gh12460_add_M_HU_PackingMaterial_IsInvoiceable.sql
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/ModelWithoutInvoiceCandidateVetoer.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java

https://github.com/metasfresh/metasfresh/issues/12460

#12460 add ability to prevent packing material from being invoiced

---

backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/ConcatenatePDFsCommand.java

#10801 Invoice from wrong Org in Batch PDF

Filter printing queues per org from async batch

---

backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java

https://github.com/metasfresh/metasfresh/issues/12460

#12460 rework M_InOutLine->C_Invoice_Candidate veto logic to prevent error

---

backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java

https://github.com/metasfresh/th173/issues/282

Purchaseand and sales Order incoterms filled from BP

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5624398_sys_gh12473_update_AD_AttachmentEntry_ReferencedRecord_v.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5624399_sys_gh12473_create_ad_product_certification_v.sql
backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5624400_sys_gh12473_create_ad_product_certification_v_table_window.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/views/AD_Product_Certification_v.sql

https://github.com/metasfresh/metasfresh/issues/12473

#12473 create AD_AttachmentEntry_ReferencedRecord_v

---

backend/de.metas.acct.base/src/main/java/de/metas/acct/impexp/AccountImportProcess.java

https://github.com/metasfresh/metasfresh/issues/12493

account import: set parent element value

---

backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/sql/SqlForFetchingLookupById.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/sql/SqlOrderByValue.java
backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/sql/SqlSelectDisplayValue.java
backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/window/descriptor/sql/SqlOrderByValueTest.java

https://github.com/metasfresh/metasfresh/issues/12498

#12498 fix ORDER BY so that instead of sorting by the entire array, only sort by the displayed value

---

frontend/package.json
frontend/src/__tests__/components/widget/Attributes/Attributes.test.js
frontend/src/actions/TableActions.js
frontend/src/components/table/Table.js
frontend/src/components/table/TableCell.js
frontend/src/components/table/TableRow.js
frontend/src/components/widget/Attributes/Attributes.js
frontend/src/components/widget/Attributes/AttributesDropdown.js
frontend/src/components/widget/WidgetRenderer.js
frontend/src/constants/actions/TableTypes.js
frontend/src/containers/Table.js
frontend/src/containers/WidgetWrapper.js
frontend/src/reducers/tables.js
frontend/src/utils/tableHelpers.js

Tab navigation in Attributes

---

misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/ShopwareClient.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/PathSegmentsEnum.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/java/de/metas/camel/externalsystems/shopware6/ShopwareTestConstants.java

https://github.com/metasfresh/metasfresh/issues/12511

#12511 remove /v3 prefix from Shopware endpoints

---

backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInOut.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInOut.java
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
backend/de.metas.contracts/src/main/java/de/metas/contracts/invoicecandidate/HandlerTools.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/ReturnsInOutHeaderFiller.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceHeader.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5625580_gh12518_Add_IncotermLocationIntoInvoiceCandidate.sql
backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5625780_sys_gh12518_AddIncotermsIntoAggregation.sql

#12518 Copy incoterm location from order to invoice and location

#12518 Copy incoterm location from order to invoice and location 

---

backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java

https://github.com/metasfresh/metasfresh/issues/12372

Gh12372 iban same org

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/get_BOM_Product_Cost.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/get_BOM_Product_Differences.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/get_BOM_Product_Price.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/get_Product_Price.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/get_Product_Price_Difference_Pct.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/types/pp_product_bom_pricing_result.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5626420_sys_gh12537_add_BOM_Product_Price_Differences_process.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5626520_sys_gh12537_bom_product_prices_report.sql

https://github.com/metasfresh/metasfresh/issues/12537

#12537 create BOM_Product_Price_Differences process

---

backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
backend/de.metas.shipper.gateway.dhl/src/test/java/de/metas/shipper/gateway/dhl/CreateShipmentRequestFromDeliveryOrderDEtoCHTest.java

https://github.com/metasfresh/metasfresh/issues/12551

#12551 add SOAPAction request header

---

backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/IHUTrxBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/hutransaction/impl/HUTrxBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java

issue introduced by https://github.com/metasfresh/metasfresh/pull/12547

hotfix exception on destroying an empty aggregated TU

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5626780_sys_gh12548_MR_Candidates_Window_Modifs.sql
backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5626920_sys_gh12548_MR_Candidates_Window_Modifs.sql

https://github.com/metasfresh/th173/issues/276
https://github.com/metasfresh/metasfresh/issues/12548

Material Receipt Candidates window modifications (ID - 540196)

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/ordercheckup_with_barcode/report_details.jrxml

https://github.com/metasfresh/sp80/issues/1664
https://github.com/metasfresh/metasfresh/issues/12566

Fix Jasper Report C_Order_MFGWarehouse_Report_With_Barcode

---

backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeShopware6Action.java

https://github.com/metasfresh/metasfresh/issues/12571

#12571 invoke Shopware actions using Shopware config's orgId. Cleanup

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5627270_sys_gh12585_Display_Tolerance_Fields.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5627290_sys_gh12585_Tolerance_Fields_TRL.sql

https://github.com/metasfresh/metasfresh/issues/12585

Display tolerance fields

---

backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfoLog.java

https://github.com/metasfresh/metasfresh/issues/12571

#12571: populate current timestamp when receiving external system log message

---

backend/de.metas.business/src/main/java/de/metas/bpartner/quick_input/service/BPartnerQuickInputService.java

https://github.com/metasfresh/ap177/issues/114
https://github.com/metasfresh/metasfresh/issues/12608

Fix Vendor flag in BPartnerQuickInputService

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/pricelist/report_details.jrxml

#12612  Fix logic for showing prices in Price list comparison report

#12612  Fix logic for showing prices in Price list comparison report

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/allergen_label.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/hazard_label.jrxml
backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/label_lu.jrxml
backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/562840_sys_gh12534_Adjust_lu_label_function.sql

#12534 Drop SIgnal

---

backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java

https://github.com/metasfresh/metasfresh/issues/12127

import correction

---

backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_Invoice.java
backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_Order.java

https://github.com/metasfresh/metasfresh/issues/12506

differentiate between SO and PO BPartner payment rule

---

backend/de.metas.marketing/serialletter/src/main/java/de/metas/letter/service/async/spi/impl/C_Letter_CreateFromMKTG_ContactPerson_Async.java

#12635 Set proper rendered address when creating Serial letters

#12635 Render the address for serial letter

---

backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBL.java
backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchDAO.java
backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBL.java
backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchDAO.java
backend/de.metas.async/src/main/java/de/metas/async/asyncbatchmilestone/AsyncBatchMilestoneObserver.java
backend/de.metas.async/src/main/java/de/metas/async/model/validator/C_Queue_WorkPackage.java
backend/de.metas.async/src/main/java/de/metas/async/processor/impl/CheckProcessedAsynBatchWorkpackageProcessor.java
backend/de.metas.async/src/main/java/de/metas/async/processor/impl/WorkpackageProcessorTask.java
backend/de.metas.async/src/test/java/de/metas/async/api/impl/AsyncBatchBLTest.java
backend/de.metas.material/event/src/main/java/de/metas/material/event/commons/ProductDescriptor.java
backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/async/C_OLCandToOrderEnqueuer.java

refs: https://github.com/metasfresh/metasfresh/issues/12241

enhance `CheckProcessedAsynBatchWorkpackageProcessor`

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5629580_sys_gh1436_update_translations_import_formats_subcriptions

added updates to translations in the window "Import Formats" for the Subscriptions (Flatrate)
for https://github.com/metasfresh/mf15/issues/1436

Updated translations for "Import Format - Subscritions"

---

backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bom/asiSupportOnProductBOM.feature
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/GRSSignumConstants.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/bom/processor/PushBOMProductsProcessor.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBOMLine.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/java/de/metas/camel/externalsystems/grssignum/to_grs/api/model/JsonBOMTest.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/bom/0_JsonBOM.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/bom/20_BOMUpsertCamelRequest.json

refs: https://github.com/metasfresh/metasfresh/issues/12650

GRS add country attribute in BOM-component

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5629850_sys_gh12657_Sort_Prices_By_Pricelist_And_ValidFrom.sql

https://github.com/metasfresh/metasfresh/issues/12657

Price sort by pricelist and validFrom

---

backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_QRCode_StepDef.java
backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_StepDef.java
backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/hu/handlingUnitsRestController.feature
backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/grssignum/ExportHUToGRSService.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ClearanceStatusInfo.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/service/HUQRCodesRepository.java
backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/impl/HandlingUnitsBLTest.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsRestController.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/JsonGetByQRCodeRequest.java
backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/LoadJsonHURequest.java
misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/handlingunits/JsonAllowedHUClearanceStatuses.java
misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/handlingunits/JsonHU.java
misc/de-metas-common/de-metas-common-manufacturing/src/main/java/de/metas/common/handlingunits/JsonSetClearanceStatusRequest.java
misc/de-metas-common/de-metas-common-manufacturing/src/test/java/de/metas/common/handlingunits/JsonAllowedHUClearanceStatusesTest.java
misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/HURouteBuilderV2.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/main/java/de/metas/camel/externalsystems/grssignum/from_grs/hu/ClearHURouteBuilder.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/java/de/metas/camel/externalsystems/grssignum/from_grs/hu/ClearHURouteBuilderTest.java
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/hu/10_ClearHUCamelRequest.json
misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-grssignum/src/test/resources/de/metas/camel/externalsystems/grssignum/from_grs/hu/10_ClearanceStatusRequest.json

refs: https://github.com/metasfresh/metasfresh/issues/12662

HU-Clearance support for aggregated HUs

---

backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5630790_sys_gh12473_add_created_columns.sql

https://github.com/metasfresh/metasfresh/issues/12473

#12473 added created/createdBy column, remove "main" label

---

backend/de.metas.payment.sepa/base/src/main/sql/postgresql/system/70-de.metas.payment.sepa/5630390_sys_gh12673_add_IsExportBatchBookings_flag_to_UI.sql

https://github.com/metasfresh/metasfresh/issues/12673

#12673 add IsExportBatchBookings flag to Payment Selection window

---

backend/de.metas.contracts/src/main/java/de/metas/contracts/pricing/trade_margin/CustomerTradeMarginService.java

MarginCommission: get product sales rep product price by SHIP_TO

---

backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/DocLine_Inventory.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Inventory.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InventoryLine.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Inventory.java
backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InventoryLine.java
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5630830_sys_gh12663_ExplicitCostPrice.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5630850_mig_gh12663_ExplicitCostPrice_UpdateExistingLines.sql
backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5630860_mig_gh12663_MinimalInventur_ImportFormat_ExplicitCostPrice_DefaultTrue.sql
backend/de.metas.business/src/main/java/de/metas/costing/CostDetailCreateRequest.java
backend/de.metas.business/src/main/java/de/metas/costing/CurrentCost.java
backend/de.metas.business/src/main/java/de/metas/costing/methods/AveragePOCostingMethodHandler.java
backend/de.metas.business/src/test/java/de/metas/costing/methods/AveragePOCostingMethodHandlerTest.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/inventory/impexp/ExplicitCostPrice.java
backend/de.metas.handlingunits.base/src/main/java/de/metas/inventory/impexp/InventoryImportProcess.java

https://github.com/metasfresh/metasfresh/issues/12663

M_InventoryLine.IsExplicitCostPrice

---

backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5631450_sys_gh12506_Invoice_PaymentRule.sql

https://github.com/metasfresh/metasfresh/issues/12506

reactivate standard payment rules PayPal and DirectDeposit

---

backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ResponseHandler.java

refs: https://github.com/metasfresh/metasfresh/issues/12708

API Audit - fix weird error message in case of "non-routed" requests

---

backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/process/DHL_ShipmentOrder_DhlLabel_Download.java

https://github.com/metasfresh/metasfresh/issues/12551

#12551 only show process when selected record contains pdf data

---

backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5631920_sys_C_AllocationHdr_more_filters.sql
backend/de.metas.business/src/main/java-legacy/org/compiere/model/MAllocationHdr.java

C_AllocationHdr improvements
